### ISSUE TITLE
erodedDragBounds should be based on options.crosshairSize

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/scenery-phet#105]
During code review #68, @samreid and I noticed that the erodedDragBounds is always eroded by a constant 4, regardless of what the crosshair size is. Is this intentional, or is this meant to be related to the crosshair size?

**Comment by bereaphysics** [comment]
The new measuringTape does not have eroded drag Bounds  by default.  (see https://github.com/phetsims/scenery-phet/commit/aa6e92ea021091d1f3fc0cb1e0d90ecc6dcd4982). Closing since no longer relevant.
