### ISSUE TITLE
Units in MeasuringTape

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/scenery-phet#107]
During code review #68, @samreid and I noticed that model units (feet, meters, etc.) must be passed in, but that the original tape length is specified in view coordinates. To make things cleaner and more consistent, it would probably be better to specify the initial tape length in model coordinates, and requiring the client code to also pass in the modelViewTransform for the simulation.

For example, in a sim we might need to create a measuring tape that has an initial length of 1 meter long, which would be difficult to do with the current API.

**Comment by bereaphysics** [comment]
Here is the new API
````
  /**
   * Constructor for the measuring Tape
   * @param {Property.<Object>} unitsProperty - it has two fields, (1) name <string> and (2) multiplier <number>, eg. {name: 'cm', multiplier: 100},
   * @param {Property.<boolean>} isVisibleProperty
   * @param {Object} [options]
   * @constructor
   */
  function MeasuringTape( unitsProperty, isVisibleProperty, options )
```

It was used successfully for implementing the measuringTape in Fluid Pressure and Flow.

The basePosition is specified in view coordinates but the lenght of the unrolled tape is specified in model coordinates. Assigning to @aaronsamuel137 for review

**Comment by bereaphysics** [comment]
This issue is no longer relevant since we committed a new measuringTape in 
https://github.com/phetsims/scenery-phet/commit/aa6e92ea021091d1f3fc0cb1e0d90ecc6dcd4982

Now both tip and base position are specified in model coordinates
