### ISSUE TITLE
[measuring-tape] Possible performance issue

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#121]
In MeasuringTape.js, I saw this code:

```js
      // in order to avoid all kind of geometrical issues with position, let's reset the baseImage upright and then set its position and rotation
      baseImage.setRotation( 0 );
      baseImage.rightBottom = basePosition;
      baseImage.rotateAround( basePosition, angle );
```

This is 3 scenery matrix update operations which could potentially be rolled into one matrix update.  I recommend testing performance on our slowest supported device to see if this is necessary.

**Comment by bereaphysics** [comment]
The three matrix operations are still present in the most recent incarnation of MeasuringTape ( see https://github.com/phetsims/scenery-phet/commit/aa6e92ea021091d1f3fc0cb1e0d90ecc6dcd4982).
The Ipads 2 and 3 does not show perform degradation with the measuringTape. 

Although it is technically possible to roll the scenery operations into one matrix, it is very ugly code with lots of sine and cosine and it will be impossible to maintain for mere mortals. In absence of performance issue, it is preferable to leave it as is.
