### ISSUE TITLE
ThermometerNode has a problem at maxTemperature

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#127]
Fixing #123 (minTemperature) exposed a problem with maxTemperature. At maxTemperature, the fluid is covering up the top part of the glass. Compare the screenshots (below) from scenery-phet's demo and LiquidExpansionThermometer.java.  Note how the glass has thickness around its *entire* border in the Java version.

![screenshot_412](https://cloud.githubusercontent.com/assets/3046552/5440753/50460e62-8448-11e4-9563-bf3af548182f.png)

![screenshot_411](https://cloud.githubusercontent.com/assets/3046552/5440755/518bf50c-8448-11e4-8577-54a2393b72db.png)

**Comment by pixelzoom** [comment]
To summarize the status of this issue...
> Assigning to @jbphet for a second opinion, since he didn't like the non-3D version.

**Comment by pixelzoom** [comment]
When I tried to fix the 1-px overlap issue that @samreid pointed out above, I found it unnecessarily difficult to do so, due to lack of documentation and var names that are not descriptive (e.g., rectangleX). I correct some of this, and improved the doc.  I also added TODO items where there appear to be errors.

**Comment by pixelzoom** [comment]
Changed the API and implementation to use 'bulb' and 'tube' consistently, instead of sometimes referring to 'sphere' and 'rect'. Commits:
https://github.com/phetsims/friction/commit/74c7a15fb7542b455a3d6395a29a79ae07f591f9
https://github.com/phetsims/blackbody-spectrum/commit/6c36251c0d222d1ba2326276ff766c81b6ad7b9f
https://github.com/phetsims/scenery-phet/commit/a644621341ae5a8c2b8ca442bb891ff860504f70

**Comment by pixelzoom** [comment]
Seam is fixed:

![screenshot_452](https://cloud.githubusercontent.com/assets/3046552/6099036/aba058e2-afab-11e4-9537-eee1f609020b.png)

**Comment by pixelzoom** [comment]
If @jbphet is OK with the look of the thermometer, then this issue can be closed.

**Comment by jbphet** [comment]
I checked it out in the Friction sim and in the scenery-phet demo.  Looks great in both.  Closing.
