### ISSUE TITLE
Faucet knob "jumps" when fully opened in Firefox

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/scenery-phet#131]
When using the latest faucet (http://www.colorado.edu/physics/phet/dev/html/scenery-phet/1.0.0-dev.2/scenery-phet_en.html?screens=3) I noticed that when I pull the knob out all the way there is a slight separation between the blue knob and the gray plunger. 

I managed to grab a screenshot: 
![screen shot 2015-01-08 at 11 11 58 am](https://cloud.githubusercontent.com/assets/7852916/5667744/428d97bc-9727-11e4-945c-c273df99daf7.png)

It only seems to happen on Firefox (33.1.1) on my Mac (10.9.5) and is not an issue on Chrome or Safari.

**Comment by pixelzoom** [comment]
I reproduced this in scenery-phet 1.0.0-dev.2.  It also occurs in published sims like Beer's Law Lab 1.2.3, see http://phet.colorado.edu/sims/html/beers-law-lab/latest/beers-law-lab_en.html.  So it's not at all related to recent changes to the faucet image files. This is a long-standing issue with rendering image files in Firefox.  It's my understanding that this is not something that we can fix. @jonathanolson, could you please comment?

**Comment by pixelzoom** [comment]
@jonathanolson, still awaiting your comment on this issue.

**Comment by pixelzoom** [comment]
This is still a problem after moving to Scenery 0.2. I resolved the gap between shaft and flange by introducing a 1-pixel overlap.  But the entire knob moves a bit vertically when you drag it.

**Comment by pixelzoom** [comment]
Updated to FF 35.0.1 on Mac OS, and I don't see the knob moving around anymore. So this issue is resolved, closing.
