### ISSUE TITLE
migrate ConductivityTesterNode and LightBulbNode to scenery-phet

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#132]
See https://github.com/phetsims/acid-base-solutions/issues/128 for prior discussion and requirements.

**Comment by pixelzoom** [comment]
LightBulbNode and associated resources were migrated to scenery-phet in https://github.com/phetsims/scenery-phet/commit/f88d824d533d82e20a180efe58aa942324901333.

**Comment by pixelzoom** [comment]
Remaining tasks:
• remove dependency on ConductivityTester
• make the entire tester movable
• add "short circuit" feature
• add convenience function for creating an icon (for use in control panels, toolboxes, etc.)
• move from acid-base-solutions to scenery-phet

**Comment by pixelzoom** [comment]
ConductivityTesterNode has been generalized quite a bit, and moved to scenery-phet. But it doesn't have all of the features required by SASS, so don't use it yet.  Features currently missing include:

• option to make the entire tester movable
• option for "short circuit" feature
• convenience function for creating an icon (for use in control panels, toolboxes, etc.)

**Comment by pixelzoom** [comment]
Note to self: Consider making the entire ConductivityTesterNode move based on its model location, then position the probes relative to the tester.  That would remove the requirement state in the doc header ("This node assumes that it is located at (0,0)") and would simplify repositioning (dragging) of the entire tester.

**Comment by pixelzoom** [comment]
The light bulb and battery in SASS are much larger than in ABS. So I'm guessing that these constructor options will probably be needed:

> lightBulbScale: 1,
> batteryScale: 1

If this is the case, then we'll also need larger default image files. And we'll undoubtedly have problems with the quality of those files on Firefox and IE.

**Comment by pixelzoom** [comment]
Need to locate the .ai file for battery.png.

**Comment by pixelzoom** [comment]
Found .ai file for battery in Unfuddle, added it to this repo, renamed .png file to match .ai file. https://github.com/phetsims/scenery-phet/commit/12b2370f8be26880d749468a42d9168201eb4a4e

**Comment by pixelzoom** [comment]
I'm not going to make ConductivityTesterNode responsible for dragging itself. That functionality is already generalized in MovableDragHandler, which can be applied to any Node, and allows you to tailor the dragBounds to your situation.  If you want to make a ConductivityTesterNode movable, here's the pattern:

```js
var locationProperty = new Property(...);
var dragBounds = new Bounds2(...);
var conductivityTesterNode = new ConductivityTesterNode(..., locationProperty,...);
conductivityTesterNode.addInputListener( new MovableDragHandler( { 
  locationProperty: locationProperty,
  dragBounds: dragBounds
  }, ... );
```

**Comment by pixelzoom** [comment]
Once thing remaining to do, create larger PNG files for the bulb and battery, then add these options for ConductivityTesterNode:

> lightBulbScale: 1,
> batteryScale: 1

and propagate lightBulbScale to LightBulbNode.

**Comment by pixelzoom** [comment]
Dilema... If I make the lightbulb and battery PNG files larger (to satisfy SASS), then they will look lousy in ABS on Firefox and IE.

**Comment by pixelzoom** [comment]
@AshrafSharf please try this out in SASS. Let me know if the bulb and battery really need to be larger (scalable) or whether we can live with the size used in ABS.

**Comment by pixelzoom** [comment]
I added options.bulbImageScale and batteryImageScale. In ABS they are scaled to 0.33 and 0.6 respectively. So there's definitely some ability to make them larger for SASS.

**Comment by pixelzoom** [comment]
Sound probably add modelViewTransform as an option to ConductivityTesterNode. ABS uses no modelViewTransform, but I can imagine sims that will need one.  The default would be identity.

**Comment by AshrafSharf** [comment]
@pixelzoom @samreid by giving different scale values to bulbImageScale (0.7) and batteryImageScale (0.8) we could bring the bulb and battery image appearance close to the original implementation. I have included the screen shot below after integrating the scenery-phet conductivityTesterNode with SASS sim. (yet to implement dragging though)


![image](https://cloud.githubusercontent.com/assets/8498160/6191792/3d20b12a-b3d2-11e4-96ed-3134888bccb7.png)

**Comment by pixelzoom** [comment]
Looks good to me. Let me know if you need any assistance with dragging. See the example I gave in above, using MovableDragHandler.

Does SASS have any need for a model-view transform? That's the only feature that's not yet implemented.

**Comment by AshrafSharf** [comment]
@pixelzoom Thanks for the suggestion. I will implement MovableDragHandler and let you know if I find any issues. SASS has its own specific model-view transform but in this case I converted the model values to view, before passing them to ConductivityTesterNode. Only the location Property has two way binding which I can convert back to model value when dragged.

**Comment by pixelzoom** [comment]
@AshrafSharf I've added options.modelViewTransform to ConductivityTesterNode. If you'd prefer not to convert values before passing them to ConductivityTesterNode, take it for a test drive. Note that some of the options (as documented) are still in the view coordinate frame. Disclaimer: the modelViewTransform feature has not been thoroughly tested.

**Comment by pixelzoom** [comment]
modelViewTransform is now tested and debugged.

ConductivityTesterNode is also represented in the scenery-phet demo application.

**Comment by pixelzoom** [comment]
There is one TODO item in code that I don't plan to address at this time. Here it is, in context:

```js
    // @private short-circuit indicator, centered above the light bulb
    assert && assert( brightnessProperty.get() > 0 ); //TODO layout will be wrong if lightBulbNode has rays
    this.shortCircuitNode = new Text( shortCircuitString, {
      font: options.shortCircuitFont,
      fill: options.shortCircuitFill,
      centerX: this.lightBulbNode.centerX,
      bottom: this.lightBulbNode.top,
      visible: false // initial state is no short circuit
    } );
```

I'm not going to deal with this now because I believe that brightness will typically be zero (or can be set to zero, as a workaround) when ConductivityTesterNode is constructed.  In the meantime, the assertion will alert you to the constraint.

**Comment by pixelzoom** [comment]
[2/20/15, 12:12:34 PM] Chris Malley: Does anyone have time to review my work on ConductivityTesterNode? https://github.com/phetsims/scenery-phet/issues/132
[2/20/15, 12:13:43 PM] Chris Malley: No pressure, I know that everyone is very busy.  But if anyone has time, please self-assign. If it goes unassigned until next Friday, I'll close it.

**Comment by pixelzoom** [comment]
Code to review includes:
scenery-phet.LightBulbNode
scenery-phet.ConductivityTesterNode

Example usages include:
scenery-phet demo (Components screen)
acid-base-solutions
sugar-and-salt-solutions

**Comment by jonathanolson** [comment]
I'm not in a good position to do a code review (haven't used/seen any of that code), but acid-base-solutions is hitting an assertion on ConductivityTesterNode line 88:

```
Error: Assertion failed: undefined
    at window.assertions.assertFunction (http://192.168.0.2:8080/assert/js/assert.js:22:13)
    at ABSConductivityTesterNode.ConductivityTesterNode (http://192.168.0.2:8080/scenery-phet/js/ConductivityTesterNode.js?bust=1424713438242:88:48)
    at new ABSConductivityTesterNode (http://192.168.0.2:8080/acid-base-solutions/js/common/view/ABSConductivityTesterNode.js?bust=1424713438242:22:28)
    at IntroductionView.AcidBaseSolutionsView (http://192.168.0.2:8080/acid-base-solutions/js/common/view/AcidBaseSolutionsView.js?bust=1424713438242:46:34)
    at new IntroductionView (http://192.168.0.2:8080/acid-base-solutions/js/introduction/view/IntroductionView.js?bust=1424713438242:21:27)
    at IntroductionScreen.Screen.call.backgroundColor [as createView] (http://192.168.0.2:8080/acid-base-solutions/js/introduction/IntroductionScreen.js?bust=1424713438242:75:34)
    at http://192.168.0.2:8080/joist/js/Sim.js?bust=1424713438242:401:28
    at Function.St (http://192.168.0.2:8080/sherpa/lodash-2.4.1.min.js?bust=1424713438242:23:149)
    at new Sim (http://192.168.0.2:8080/joist/js/Sim.js?bust=1424713438242:391:7)
    at http://192.168.0.2:8080/acid-base-solutions/js/acid-base-solutions-main.js?bust=1424713438242:37:5
```

**Comment by pixelzoom** [comment]
Thanks @jonathanolson, assertion expression was incorrect, fixed.
