### ISSUE TITLE
ThermometerNode options.backgroundFill is buggy

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#134]
In ThermometerNode, the backgroundFill option does not fill the sphere. Demonstrated by adding backgroundFill: 'yellow' to scenery-phet demo. See screenshot below.

![screenshot_449](https://cloud.githubusercontent.com/assets/3046552/6094045/98ebd72a-aed5-11e4-8969-d8d6eac92286.png)

**Comment by pixelzoom** [comment]
Fixed in https://github.com/phetsims/scenery-phet/commit/0fece5b3b7d3d2232c0f0507a6af8e8ae2f7fed6/.

Assigning to @aaronsamuel137 to review.

**Comment by aaronsamuel137** [comment]
Thanks for fixing this! It's much cleaner to do it this way than with a Rectangle, not sure why I didn't think of that. Looks great. Closing.
