### ISSUE TITLE
why does ThermometerNode have separate glass-thickness options for bulb and tube?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#135]
ThermometerNode has these options:

> fluidBulbSpacing: 2, // space between the tube wall and the fluid inside it
> fluidTubeSpacing: 2, // space between the bulb wall and the fluid inside it

If I set these to different values in the scenery-phet demo:

> fluidBulbSpacing: 6,
> fluidTubeSpacing: 2,

it looks like this:

![screenshot_450](https://cloud.githubusercontent.com/assets/3046552/6094058/49b806fa-aed6-11e4-92cc-3a0d74758c1d.png)

Two issues with this:

(1) It looks odd.
(2) Any client who wants to change the 'glass thickness' must change 2 options, and set them to the same value.

Highly recommended to change this to options.glassThickness.  The only sim using different values for fluidBulbSpacing and fluidTubeSpacing is Friction, and I'm not convinced that it's doing so intentionally because it looks odd.

Assigning to @aaronsamuel137 for comment. Other developers please chime in.

**Comment by pixelzoom** [comment]
The Java implementation (LiquidExpansionThermometerNode) did not have separate widths for the glass in the tube vs bulb, they were the same.

**Comment by samreid** [comment]
Yes, a single `glassThickness` sounds good.

**Comment by aaronsamuel137** [comment]
I agree that this is a good idea. The only reason I added these as different options was because I was attempting to preserve the look of Friction exactly as it was when I integrated the new thermometer. In any case, I've updated the options to have a single glassThickness option.

Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Looks like you missed usages of fluidTubeSpacing and fluidBulbSpacing in blackbody-spectrum. I cleaned them up, see above commit. Closing.
