### ISSUE TITLE
ThermometerNode: height of tube is incorrect

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#136]
ThermometerNode has these options that should determine the height of the node:

```js
tubeWidth: 30,
tubeHeight: 100,
lineWidth: 4,
```

After outlineNode is created, this assertion should be true (but isn't):

```js
assert && assert( outlineNode.height === options.tubeHeight + options.bulbDiameter + options.lineWidth );
```

Btw... It's `+ options.lineWidth` because the half of the stroke on top and bottom is outside the shape.

The problem is that the rounded top on the tube is being added to options.tubeHeight. So the client ends up with a tube that is taller than requested.

**Comment by pixelzoom** [comment]
Putting a `debugger` breakpoint before the assertion, here's what I see in the console when running scenery-phet demo:

> options.tubeHeight + options.bulbDiameter + options.lineWidth 
> 154
> outlineNode.height
> 164

So in this case, the thermometer is 10-px taller than expected.

**Comment by pixelzoom** [comment]
Tube height is now fixed so that the assertion passed. But now the tick marks look "off". Based on the Java version, the ticks should start from the top of the straight portion of the tube. Looks like they are starting below that (perhaps 1 tick below?)

![screenshot_451](https://cloud.githubusercontent.com/assets/3046552/6094240/50c8d84e-aedf-11e4-8328-6a36a214acae.png)

**Comment by pixelzoom** [comment]
Tube height and tick marks are fixed. Assigning to @aaronsamuel137 to review.

**Comment by aaronsamuel137** [comment]
Much more readable now, thanks! Closing.
