### ISSUE TITLE
focusable should not be set in ResetAllButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#138]
ResetAllButton is currently setting `focusable:true`. This should be handled in `RoundButtonView`, as is done currently in `RectangularButtonView`.

Added by @samreid in  https://github.com/phetsims/scenery-phet/commit/7cdfe905d29dd7ff92218f8267cd1c77a80f3845.

**Comment by pixelzoom** [comment]
Fixed and tested. This involved relocating 1 line of code. All of the various 'round' sun buttons are now accessible, instead of only the Reset All button.

Assigned to @samreid for a quick look.

**Comment by pixelzoom** [comment]
@samreid you may also want to take a look at FAMB.GoPauseButton. It's using RoundPushButton, but is setting `focusable: false`.

**Comment by samreid** [comment]
Thanks for making this change, it seems good.

For FAMB, the focusable:false is commented as:

```js
focusable: false//handled in the parent
```

This means that normally the RoundPushButtons would have been focusable, but we wanted to treat the Go and Pause buttons as a unified button even though it is implemented as two separate RoundPushButtons.  Overriding focusable to false in the RoundPushButtons and setting focusable:true in the parent is one way to get there.  Reassigning to @pixelzoom for discussion, feel free to close if all is well.

**Comment by pixelzoom** [comment]
Got it, that makes sense. Closing.
