### ISSUE TITLE
proposed API change for MovableDragHandler

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#139]
The current API mixes some things that are not required into the constructor parameters, specifically dragBounds and mvt.  Here's the current API:

```js
  /**
   * @param {locationProperty:Property.<Vector2>, [dragBounds]:Bounds2} movable
   * @param {ModelViewTransform2} mvt
   * @param {Object} [options]
   * @constructor
   */
  function MovableDragHandler( movable, mvt, options ) {
    options = _.extend( {
      startDrag: function( event ) {},  // use this to do something at the start of dragging, like moving a node to the foreground
      endDrag: function( event ) {}  // use this to do something at the end of dragging, like 'snapping'
    }, options );
```
Proposed API is to move dragBounds and modelViewTransform to options. It would look like this:

```js
/**
   * @param {Property.<Vector2>} locationProperty
   * @param {Object} [options]
   * @constructor
   */
  function MovableDragHandler( locationProperty, options ) {
    options = _.extend( {
      dragBounds: null, // {Bounds2} dragging will be constrained to these optional bounds
      modelViewTransform: ModelViewTransform2.createIdentity(), // {ModelViewTransform2}
      startDrag: function( event ) {},  // use this to do something at the start of dragging, like moving a node to the foreground
      endDrag: function( event ) {}  // use this to do something at the end of dragging, like 'snapping'
    }, options );
```

There are currently 22 occurrences of 'new MovableDragHandler', so this refactor won't be too difficult.

@jonathanolson @samreid @jbphet does this sound OK to you?

**Comment by jbphet** [comment]
Looks like an improvement to me.  Much more compact and clear.

**Comment by bereaphysics** [comment]
Indeed, this is a bit more intuitive and  mvt.createIdentity default will be useful.

**Comment by jonathanolson** [comment]
Looks good to me.

**Comment by pixelzoom** [comment]
Changes complete, as described above. 

Sims that were touched (and tested):

beers-law-lab
bending-light
blackbody-spectrum
fluid-pressure-and-flow
pendulum-lab
ph-scale
sugar-and-salt-solutions
under-pressure

Closing.
