### ISSUE TITLE
port PhetColorScheme

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#140]
This replaces https://github.com/phetsims/phetcommon/issues/22.

Port the Java version of PhetColorScheme. It will live in scenery-phet because Color is part of scenery.util, and PhetColorScheme is PhET-specific colors.  After porting, designers/developers can discuss how to modify the color scheme.

**Comment by pixelzoom** [comment]
This is done. 

I removed:
- generic colors (e.g., 'red') that were duplicated in scenery.Color
- generic colors (e.g. 'PALE_BLUE') that were not used anywhere in the Java implementation

Assigning to @ariel-phet to decide how to proceed. Below is additional information to decisions.

According to the code documentation:
> This is based on the google doc here:
> http://spreadsheets.google.com/ccc?key=0Ajw3oS4YmCBqdDZzYUhlMksxZ0lfUHZ3bXUzM0JNU3c&hl=en&pli=1#gid=0 

Here's an overview of where PhetColorScheme is used in the Java implementation.

RED_COLORBLIND is by the far the most-used color. It appears in build-an-atom, energy-forms-and-changes, energy-skate-park, fractions, gravity-and-orbits, ideal-gas, molecule-polarity, photon-absorption, states-of-matter, sugar-and-salt-solutions, and piccolo-phet. And it should undoubtedly appear in more sims (e.g., forces-and-motion-basics uses Color.red for friction force). As noted in phetsims/phetcommon#22, we've been duplicating RED_COLORBLIND in HTML5 sims, so recommended to start using this immediately. 

All of the other colors in PhetColorScheme appear only in 1 sim, or are not used at all.

Here are the colors used by only 1 sim. Since most of these are `work-energy`, I suspect that the idea to standardize color may have originated around the time of that's sim's development.

> GRAVITATIONAL_FORCE: gravity-and-orbits
HEAT_THERMAL_ENERGY: work-energy
KINETIC_ENERGY: work-energy
POTENTIAL_ENERGY: work-energy
REAL_PART: work-energy
TOTAL_ENERGY: work-energy
VELOCITY: gravity-and-orbits

Here are the colors that are (surprisingly) not used.

> ACCELERATION (moving-man defines its own different color)
APPLIED_FORCE (forces-and-motion-basics defines its own different color)
ELASTIC_ENERGY
FRICTION_FORCE (forces-and-motion-basics defines its own different color)
IMAGINARY_PART
NET_WORK
NORMAL_FORCE
POSITION
TOTAL_FORCE
WALL_FORCE (moving-man and rotation define their own different colors)

**Comment by pixelzoom** [comment]
I searched around for copies of color-blind red and replaced them with PhetColorScheme.RED_COLORBLIND. See commits above.

I also see quite a few uses of 'red', which should probably be inspected on a case-by-case basis.

**Comment by samreid** [comment]
Can (/should?) we move RED_COLORBLIND from PhetColorScheme to Color?  It may be much more convenient for many usage sites.

**Comment by pixelzoom** [comment]
@samreid asked:
> Can (/should?) we move RED_COLORBLIND from PhetColorScheme to Color?

Depends on whether we want to consider it to be something that's PhET-specific, or whether we're confident that it's general enough (and has been tested well enough) to be part of the Scenery API.

**Comment by pixelzoom** [comment]
I inspected various uses of 'red', "red' and Color.RED in sims, and created issues for evaluating whether they should be using RED_COLORBLIND.

**Comment by pixelzoom** [comment]
Tangential issue moved to https://github.com/phetsims/scenery-phet/issues/174 (move PhetColorScheme.RED_COLORBLIND to scenery.Color?)

Closing.
