### ISSUE TITLE
Generalize MovableDragHandler to handle dynamical bounds

### ISSUE THREAD

**Issue by bereaphysics** [phetsims/scenery-phet#142]
For charges-and-fields, the drag bounds are dynamical and set by the size of the window. By having dragBounds as property, it is possible to constrain the location to be within the dynamical dragBounds.

Here is how it is done in charges-an-fields: https://github.com/phetsims/charges-and-fields/blob/master/js/charges-and-fields/view/MovableDragHandler.js

It would be good if this capability could live in the common-code.

One consideration that arises is how to deal with a location that is no longer within the dragBounds
(due a change of  the dragBounds). For charges and fields the dragBoundListener constrains the location to be within the dragBounds 

````
    // constrain the location to always be within the dragBounds
    this.dragBoundsPropertyListener = function( bounds ) {
      locationProperty.set( constrainLocation( locationProperty.value, bounds ) );
    };
    this.dragBoundsProperty.link( this.dragBoundsPropertyListener );
````
This is probably the most common scenario but different behavior might be wanted (for instance the location could be set  to its initial position if it is caught outside of the dragBounds). I don't know if it is best to include this behavior  in the MovableDragHandler as an options or to let the client deal with it.

Assigning to @pixelzoom since he wrote the original MovableDragHandler

**Comment by pixelzoom** [comment]
FYI, I probably won't have a chance to look at this until Monday, 3/16.

**Comment by pixelzoom** [comment]
Here's what I had in mind:

(1) Add private field `this._dragBounds = options.dragBounds;`
(2) Add ES5 setter and getter for dragBounds, following the pattern used in scenery.
(3) When dragBounds is set, check whether locationProperty.value is within the dragBounds. If not, move locationProperty to the nearest position within the dragBounds.

@bereaphysics does that sound like it will meet your needs?

**Comment by pixelzoom** [comment]
Since Bounds2 is mutable, we may want to make a copy of the dragBounds in the constructor and setDragBounds, in case the client is ill-behaved and mutates the dragBounds.

**Comment by bereaphysics** [comment]
yes that would work for my need.

**Comment by pixelzoom** [comment]
I can get to it when I'm done with the flu. Or feel free to proceed if you'd like. Up to you...

**Comment by bereaphysics** [comment]
I'll leave it to you since I don't feel very confident about touching the common code.

**Comment by bereaphysics** [comment]
I'm going to give it a try after all

**Comment by bereaphysics** [comment]
The options dragBounds had to be set to Bounds2.EVERYTHING instead of null.

**Comment by bereaphysics** [comment]
Assigning to @pixelzoom for review. For your information, Charges and Fields uses the setter for dragBounds.

**Comment by pixelzoom** [comment]
Thanks @bereaphysics, looks great. 

I made a couple of doc and "cosmetic" changes, which you're welcome to review. I moved the ES5 setter and getter next to setDragBounds and getDragBounds, ala the pattern used in scenery (e.g., see scenery.Node). I also removed an `if ( self._dragBounds )` test, since dragBounds is no longer optional (defaults to Bounds2.EVERYTHING.)

Closing.
