### ISSUE TITLE
Make shapes within common buttons non-pickable for better performance

### ISSUE THREAD

**Issue by jbphet** [phetsims/scenery-phet#143]
While working with @jonathanolson on https://github.com/phetsims/molecules-and-light/issues/98, he noticed that the reset all button, play/pause button, and step button all have some shapes within them that require hit testing.  This has a slight performance cost, since hit testing is often a bit computationally expensive, especially for elaborate shapes like that of the curved arrow in the reset all button.  It would be a marginal performance improvement for all sims that use these buttons to make the shapes within them unpickable.

**Comment by jbphet** [comment]
This ended up touching a lot of the common buttons.  I tested all affected buttons, most in multiple sims.  I couldn't test the rewind one because this button is only used in Gravity and Orbits and the rewind functionality seems to be broken.

Assigning to @jonathanolson for a quick sanity check sort of review before closing.

**Comment by pixelzoom** [comment]
@jbphet Any reason why you didn't just make the button supertype (e.g. RectangularPushButton, RoundPushButton) set pickable:false for its options.content, rather than making the subtype/client responsible for that?  With the current approach, we're going to need to remember to do this for new buttons.

**Comment by samreid** [comment]
I am wondering what @pixelzoom is wondering.

**Comment by jbphet** [comment]
I just didn't think of it.  My bad.  I'll make the changes.

**Comment by jbphet** [comment]
Addressed in Sun by doing what was suggested above, i.e. making the content node non-pickable.  See commit https://github.com/phetsims/sun/commit/0d501fd42c31d650ed4040c15f6c0b7052dad73d.  Assigning to @samreid to review.

**Comment by samreid** [comment]
The above change set looks good to me, thanks @jbphet
