### ISSUE TITLE
branch: open-stax

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#145]
@samreid I believe that you created this branch.  Please indicate what it's for, and when/whether you expect to delete it.

**Comment by pixelzoom** [comment]
Related to open-stax branch of forces-and-motion-basics?

**Comment by samreid** [comment]
Openstax uses a gray UI for certain components--this was a demonstration how to do so.  I think it is no longer needed.

**Comment by samreid** [comment]
I deleted the openstax branch here and in FAMB.  Closing.
