### ISSUE TITLE
Changes to MovableDragHandler for GAO

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/scenery-phet#148]
I am consider making a few changes to MovableDragHandler that will make it usable in Gravity and Orbits.

1. Make the modelViewTransform have setters and getters (much like @bereaphysics did with the bounds in #142). In GAO, there is a Property<ModelViewTransform> that changes as the sim is scaled in and out.

2. Add an optional method "onDrag" that gets called every time "drag" is called. This would be used to notify when the user has modified a body's position.

Any objections to or concerns with these changes?

**Comment by pixelzoom** [comment]
Sounds great.

**Comment by aaronsamuel137** [comment]
I've made these changes, feel free to review if you'd like @pixelzoom.

**Comment by pixelzoom** [comment]
I inspected the changes, looks good, closing.
