### ISSUE TITLE
EyeDropperNode.on replaces Node.on

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#149]
In phetsims/together#85 I noticed that EyeDropperNode.on overwrites Node.on.  Thought this might cause trouble depending on how scenery is relying on `on`.

**Comment by samreid** [comment]
Here are lines that overwrite the Node Events mixin:

```js
    set on( value ) { this.onProperty = value; },

    get on() { return this.onProperty.value; },
```

**Comment by pixelzoom** [comment]
EyeDropperNode was moved over from beers-law-lab.DropperNode.  At the time that DropperNode was written, Node had no `on` function.  So this is a general problem - as function and fields are added to Scenery, is someone checking to make sure that they are not used by existing subtypes?

I will rename the EyesDropperNode function to something else.

**Comment by pixelzoom** [comment]
Suggestions for what I should rename `on` to in EyeDropperNode? In order for this to make sense, I guess I should also rename `onProperty`.

**Comment by pixelzoom** [comment]
How about `dispensing` and `dispensingProperty`? That should be pretty safe :)

**Comment by pixelzoom** [comment]
EyeDropperNode is used in beaker, beers-law-lab, ph-scale and scenery-phet (demo).

**Comment by pixelzoom** [comment]
@jonathanolson I haven't made any changes to fix this yet, but the droppers in beers-law-lab, ph-scale, etc. appear to be still functioning properly.  How can that be the case if I'm overriding Node.on?  You described it as essential to (among other things) registering input listeners.

**Comment by pixelzoom** [comment]
@samreid and @jbphet:  To address this issue, I'll be changing onProperty to dispensingProperty. This affects the together API for beaker.  Do you want me to change 'beakerScreen.dropper.on' to 'beakerScreen.dropper.dispensing'?

**Comment by pixelzoom** [comment]
Ditto for concentration-api.js.

**Comment by jonathanolson** [comment]
Interesting, will look into it. I typically try to do onStatic since it won't require array copies on notifications.

**Comment by pixelzoom** [comment]
@samreid  and @jbphet Note that 2 changes were made to together APIs. Notify clients as appropriate. The changes are:

```
// beaker-api.js
'beakerScreen.dropper.dispensing' -> 'beakerScreen.dropper.dispensing'

// concentration-api.js 
'concentrationScreen.dropper.dispensing' -> 'concentrationScreen.dropper.dispensing'
```

**Comment by pixelzoom** [comment]
Done, closing.  If anyone wants to review, go for it.

**Comment by pixelzoom** [comment]
Btw... There are other places where this is very likely to be a problem again.  For some UI components, 'on' is the natural name for a Property.  onProperty occurs throughout the sun button package; in sun switches (OnOffButton, ABSwitch); in Color Vision for the light; in Beer's Law Lab for the light and AT Detector,...
