### ISSUE TITLE
FaucetNode needs a dispose function

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#150]
When @jbphet & I were working on tandem instrumentation for concentration, in https://github.com/phetsims/beers-law-lab/issues/98 we added instrumentation into FaucetNode.  We also wanted to add a dispose() method that would unregister from tandem, but (a) there were many many other listeners that would need to be removed during dispose and (b) we didn't think FaucetNode is something that would be dynamically created/disposed during a sim.  If we create a sim where FaucetNodes are dynamically created/disposed, this issue will suddenly become very important.

**Comment by pixelzoom** [comment]
Changing title. FaucetNode definitely needs a dispose function.

**Comment by pixelzoom** [comment]
> there were many many other listeners that would need to be removed 

There are 3 property observers that need to be unlinked and 1 tandem that needs to be removed.  This is 10 minutes of work.  I'll do it.

**Comment by pixelzoom** [comment]
10 minutes to implement, 30  minutes to fix a broken tandem in beers-law-lab (where I was trying to test this.)  

Input listeners added to nodes that are created by FaucetNode do not need to be cleaned up. 

Tested in the context of ConcentrationView by calling solventFaucetNode.dispose. The solvent faucet seemed to be broken, as expected. 

Assigning to @samreid for review.

**Comment by samreid** [comment]
The implementation looks correct and complete.  Closing.
