### ISSUE TITLE
Create a HeaterCoolerNode

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#151]
The HeaterCoolerNode is used in 'Energy Forms and Changes' and 'States of Matter'.  It is an element that can heat up or cool down objects in the sim environment.  It is currently implemented in 'States of Matter' but it will be used frequently throughout PhET sims so @jbphet suggested that it be generalized and moved to scenery-phet.

It is currently called StoveNode in States of Matter, but the more recent and descriptive name for it is HeaterCoolerNode.

**Comment by jessegreenberg** [comment]
I renamed StoveNode to HeaterCoolerNode and moved it to scenery-phet.  In order to make it a common sim component I did the following:

- HeaterCoolerNode colors and properties are now optional parameters rather than constants.
- Optional snapToZero property was added to control whether or not the slider snaps to off.  This is a feature from the original Java.
- Scale the 'Heat' and 'Cool' labels to support translations.

Reassigning to @jbphet for review.

**Comment by jessegreenberg** [comment]
The HeaterCoolerNode needs independent front and back components so that objects can be layered inside of the heater to create a 3D effect.  

The HeaterCoolerNode also needs optional parameters that enable and disable heating/cooling.

**Comment by jessegreenberg** [comment]
I split HeaterCoolerNode into HeaterCoolerFront and HeaterCoolerBack.  Both of these exist in scenery-phet.  HeaterCoolerNode still exists as a convenience node that layers these two front and back components in case a sim does not require layering nodes 'inside' of the stove.  

The optional parameters to enable/disable heating/cooling have been added.

**Comment by jbphet** [comment]
For the most part this looks good.  There are a couple of things that @jessegreenberg should probably address:
+ There is a multiplier - 0.1 - that is used in a number of places to control the size of the opening in the top of the burner relative to the width.  This should be pulled into one place so that it could be changed easily if needed.  This would make it much easier to turn it into an option some day if needed.
+ StoveNode looks like it still exists and is in use in States of Matter.  This should be swapped out for HeaterCoolerNode, and will give us a chance to test it out.

I've also done a little bit of comment editing.

**Comment by jessegreenberg** [comment]
The multiplier has been consolidated to a single constant in HeaterCoolerBack. The value also defines the shape of HeaterCoolerFront so it is a static property of HeaterCoolerBack with public access.  Please let me know if you would rather have this done a different way.

HeaterCoolerNode has replaced StoveNode in States of Matter and StoveNode has been removed from that sim.

Reassigning to @jbphet for review.

**Comment by pixelzoom** [comment]
Poking @jbphet. Review requested on 5/15/2015.

**Comment by jbphet** [comment]
Better late than never, I suppose.

For the most part, everything looks good.  I did some minor cleanup/editing of comments and some spacing.  The only other question/comment I have is that there is some code in HeaterCoolerBack.js that looks like this:
```js
      heatCoolLevelProperty: new Property( 0 ), // Property set through interaction with slider.  Max value for heating, min for cooling.
```
I think ```heatCoolAmountProperty``` would be more clear for the name, and I don't quite understand what the part of the comment about max and min value is trying to communicate.  From looking at the code, I think the valid range for this property is -1 (for max cooling) to +1 (for max heating).  It would be good to make this clear.

Assigning to @jessegreenberg to finish up, he can close when comment above is addressed.

**Comment by pixelzoom** [comment]
This one is so close, I can taste it.  But it hasn't gotten any love since 3/30/2016.

**Comment by jessegreenberg** [comment]
Done in the commit above, I renamed the Property as suggested in https://github.com/phetsims/scenery-phet/issues/151#issuecomment-203527486 and clarified the valid range in the documentation and added an assertion in HeaterCoolerBack.

Since the Property changed, I also updated the usages in states-of-matter and energy-forms-and-changes.

Closing.
