### ISSUE TITLE
unified approach to color profiles

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#156]
(5/7/2015 developer meeting)

Develop a unified approach for color profiles.

Properties for colors, base types for common color profiles (e.g. "projector"),...

Similar to the direction used in molecule-shapes.

Related issue: https://github.com/phetsims/joist/issues/222

**Comment by aaronsamuel137** [comment]
I can take a look at this when I am implementing color profiles for GAO.

**Comment by samreid** [comment]
This is somewhat out on a limb and very brainstormy, but I wonder if it makes sense to use a tandem-like approach for implementing color profiles.  That is to say: declaring color profiles as a set of tandem path => color, then using actual tandem instances for setting colors during initialization.  On the one hand, tandem/together is very well suited for this task.  On the other hand, we cannot at the moment deliver together.js with production sims, though we could possibly use tandem.js and additional interpreters in production sims.

**Comment by pixelzoom** [comment]
Strongly related to https://github.com/phetsims/joist/issues/222 (color inversion feature needs to be cleaned up).

**Comment by aaronsamuel137** [comment]
Started working on GAO again this week, and finally got around to revisiting this issue. I've made a first pass by creating a ColorProfile superclass based off of MoleculeShapsColors.

Probably a good idea to discuss at developer meeting.

**Comment by jessegreenberg** [comment]
Developer Meeting 9/22/15: JO will review progress on this.

**Comment by jonathanolson** [comment]
Implementation looks good, I'll want to move over Molecule Shapes.

Adding developer-meeting tag again to briefly review the API, then I'll plan on adding documentation for long-term use (including recommended changes if any).

**Comment by pixelzoom** [comment]
9/24/15 dev meeting notes:
• rename default to something else? (ES6 issue? defaultColor? defaultValue?)
• remove vestigial assert in ColorProfile
• assert that default is provided (since it's required)
• fallback to default if the requested profile doesn't exist
• rename GravityAndOrbitsColors to GravityAndOrbitsColorProfile

**Comment by samreid** [comment]
> • rename default to something else? (ES6 issue? defaultColor? defaultValue?)

After discussion, consensus seemed to be that `default` sounds good.

**Comment by samreid** [comment]
We should also discuss how ColorProfile should be used in Joist, which has colors, strokes and different navbar colors.

**Comment by aaronsamuel137** [comment]
I've made these changes. Notably, applyProfile( .. ) has been replaced with profileNamePropety.set( ... ). We could leave it as a wrapper method if you want to keep the same API as before.

Assigning to @jonathanolson for review.

**Comment by samreid** [comment]
It seems like an important part of ColorProfile is its ability to synchronize with a color picker in another frame, but there is no documentation about how to do so in ColorProfile.js.  Can @aaronsamuel137 or @jonathanolson elaborate?

**Comment by samreid** [comment]
After taking a closer look, I'd like to propose an alternate approach for discussion:

(1) The color profile is simply a global property instance:
```js
// It's a string Property with initial value 'default'.
var colorProfileProperty = require('GRAVITY_AND_ORBITS/colorProfileProperty'); 
```

(2) Each file that provides a color that may be customized based on the profile imports the colorProfile as above.  Then it applies its own logic for dealing with the color profile:

```js
// In BodyNode.js
colorProfileProperty.link( function( colorProfile ) {
	text.fill = colorProfile==='default' ? 'black' : 'white';
} );

// You could also use an map here if desired.
var textFill = {projector:'white'};
colorProfileProperty.link( function( colorProfile ) {
	text.fill = textFill[colorProfile] || 'black'; // fallback to default
} );
```

My motivation for doing this is to keep the colors colocated with where they are used.  If I make changes to BodyNode.js, such as renaming it or deleting it, I won't need to remember to update GravityAndOrbitsColorProfile.

Trying to maintain a global list of all customizable colors in a simulation seems like a more complex solution than necessary, why not encapsulate this behavior within each class that needs customization?

**Comment by aaronsamuel137** [comment]
>It seems like an important part of ColorProfile is its ability to synchronize with a color picker in another frame, but there is no documentation about how to do so in ColorProfile.js

I added some documentation about this in the above commit.

**Comment by aaronsamuel137** [comment]
>After taking a closer look, I'd like to propose an alternate approach for discussion:

I have no major objections to this approach. If we use a global Property instead of a global PropertySet, we still might want to create a subclass that allows for the iframe communication.

One thing that is nice about a global list of colors is that, at least in GAO, the same color property is used in multiple files, so it would need to be factored out as a global anyway.

Also, I think there was some discussion of scenery allowing Properties as fills, etc., so leaving the colors as Properties might have an advantage. But we'll have to ask @jonathanolson about this.

**Comment by jonathanolson** [comment]
> After taking a closer look, I'd like to propose an alternate approach for discussion

I like the simplicity, but I've had a preference for factoring out colors into a separate constants file before the original pattern was created. For me, it just makes it easy to identify colors to change, and with profiles, it's easier to have the colors all in the same location (for adding profiles and not hitting tons of files). The ColorProfile approach is also a bit more explicit about how you want colors done (instead of having code with conditionals for it).

> Also, I think there was some discussion of scenery allowing Properties as fills, etc., so leaving the colors as Properties might have an advantage.

Yup, that's the plan. Instead of the example:
```js
var text = new Text( someString, { ... } );
var textFill = {projector:'white'};
colorProfileProperty.link( function( colorProfile ) {
    text.fill = textFill[colorProfile] || 'black'; // fallback to default
} );
```
it would be:
```js
var text = new Text( someString, { fill: MoleculeShapesColors.panelText } );
...
panelText: {
  default: 'black',
  projector: 'white'
}
```

> Trying to maintain a global list of all customizable colors in a simulation seems like a more complex solution than necessary, why not encapsulate this behavior within each class that needs customization?

I see it as encapsulating color information in one place, so that it can additionally support showing a color picker + sim (to help decide on color choices), which I've found very helpful. How would we support the color picker with the alternate option?

**Comment by samreid** [comment]
> For me, it just makes it easy to identify colors to change, and with profiles, it's easier to have the colors all in the same location

So would recommend to have *all* of the simulation colors in that file, or just the customizable colors?

**Comment by pixelzoom** [comment]
> So would recommend to have all of the simulation colors in that file, or just the customizable colors?

I'd like to have both mutable and immutable colors in the one profile. So it would be nice if ColorProfile supported both flavors.

**Comment by samreid** [comment]
Beers Law Lab has 31 occurrences of `fill:` and 22 occurrences of `stroke:`.  Do we really want to move *all* of these into a single file?  In my opinion, it has served us really well in the past to declare these in the files where they are used.  Also, if there is a good reason for factoring all Colors into a single file, why shouldn't we also do this for Fonts, layout spacing, Strings, etc etc etc.

**Comment by pixelzoom** [comment]
> Do we really want to move all of these into a single file?

No. To clarify... It would be nice to specify colors that are currently factored out into a .js file, for example HookesLawColors.js.  These are colors that are either used in multiple places, or tended to evolve during the development process.  It's not necessary (or even desirable) to factor out every color used anywhere in the sim.

**Comment by samreid** [comment]
It seems like we have a difference of opinion on the subject of where colors should be declared:

@pixelzoom said:
> It's not necessary (or even desirable) to factor out every color used anywhere in the sim.

@jonathanolson said:
> I've had a preference for factoring out colors into a separate constants file before the original pattern was created

Here's another question from @jonathanolson:
> How would we support the color picker with the alternate option?

Brainstorming here, but we could do something like this:
```
var myRect = new Rectangle(0,0,100,100,{fill:'red'});
ColorPicker.register(myRect,'fill');
```

Also, from https://github.com/phetsims/scenery-phet/issues/156#issuecomment-143004614 we shouldn't settle on a strategy until we know how it will be handled in Joist.

Should we schedule this for a developer-meeting, or continue discussing here in the comments?

**Comment by pixelzoom** [comment]
> It seems like we have a difference of opinion on the subject of where colors should be declared:

How is this a difference of opinion? We're both saying that we prefer to encapsulate colors in one file. And nowhere in @jonathanolson's comment do I see that he's proposing that *all* colors (fills and strokes) must be specified in one file.

**Comment by samreid** [comment]
It sounded to me like @jonathanolson was proposing to put all colors in one file.

> it's easier to have the colors **all** in the same location
 (emphasis added)

Let's hear from @jonathanolson and go from there.

**Comment by pixelzoom** [comment]
I'm also proposing to have "the colors all in the same location". I'm not proposing to have "all colors" in the same locations, and @jonathanolson didn't say that either.

**Comment by samreid** [comment]
We may both benefit from a voice conversation here.

**Comment by samreid** [comment]
@aaronsamuel137 I'd also like to meet with you to discuss (a) how we can address color profiles issues Joist and potentially other common code repos and (b) if there is a way to get the advantages of this pattern without having to move declarations of colors that are used only once in the sim.

Also, if we went with a pattern like
```js
ColorPicker.register(myRect,'fill');
```

then it seems like the colors don't necessarily *need* to be wrapped in Properties--we should discuss the advantages and disadvantages of wrapping them in Properties.

**Comment by aaronsamuel137** [comment]
Sounds good. I can meet Monday morning after the accessibility meeting. I'll probably want to zoom in for that instead of coming to campus.

**Comment by samreid** [comment]
Sounds great, see you (remotely) then.

**Comment by jonathanolson** [comment]
> It sounded to me like @jonathanolson was proposing to put all colors in one file.

I guess I was proposing that I'd want all colors that could potentially change (e.g. for testing color palettes with the picker, or projector colors, etc.) in the same place. Molecule Shapes has a few colors (e.g. black text on screen icons) where the color can't be changed. I wouldn't be against ALL of the colors being moved to MoleculeShapesColors (as only 2 files have hardcoded colors).

I did find it convenient for color testing/tweaking to have basically every color be available for change, but other developers may disagree. Out of all of the colors in MoleculeShapesColors, only **3** do not change based on the profile, so I'd say it was convenient to basically have **all** of the colors in the same file. This may be different in sims that don't switch from dark to light backgrounds.

**Comment by aaronsamuel137** [comment]
Working with @samreid on this issue, we devised a way to keep many of the benefits of ColorProfile while being able to keep the colors local the file they are used in. It would entail adding the following method to ColorProfile:

```js
    /**
     *
     * @param instance
     * @param attribute
     * @param description
     * @param defaultColor
     * @param colorMap
     */
    addColoredInstance: function( instance, attribute, description, defaultColor, colorMap ) {

      window.addEventListener( 'message', function( evt ) {
        var data = JSON.parse( evt.data );
        if ( data.type === 'setColor' && data.name === description ) {
          instance[ attribute ] = new Color( data.value );
        }
      } );

      this.profileNameProperty.link( function( profileName ) {
        var color = colorMap[ profileName ] || defaultColor;
        instance[ attribute ] = color;

        var hexColor = color.toNumber().toString( 16 );
        while ( hexColor.length < 6 ) {
          hexColor = '0' + hexColor;
        }

        window.parent && window.parent.postMessage( JSON.stringify( {
          type: 'reportColor',
          name: name,
          value: '#' + hexColor
        } ), '*' );
      } );
    }
```

With the following usage:

```js
    GravityAndOrbitsColorProfile.addColoredInstance( this, 'fill', 'Right Control Panel Background', Color.WHITE, {
      projector: Color.BLACK
    } );
```


@samreid: I like this approach because you don't have a duplication of the name.

**Comment by aaronsamuel137** [comment]
Flagging for dev meeting, but feel free to discuss asynchronously instead if developers have time beforehand.

**Comment by jonathanolson** [comment]
That seems to get tricky when you have multiple places for the same color, right? Can all of them safely addColorInstance? Do you only pick one, or just have a color constants file that registers it one time?

And many times access to the Color property itself is helpful, and we DON'T want to link it. How would that be handled?

**Comment by samreid** [comment]
> That seems to get tricky when you have multiple places for the same color, right? 

When a color is used in more place than one, it should be factored out.  If it is also supposed to be customizable, then you can create a color property for it, then call addColorInstance on the color property.

> And many times access to the Color property itself is helpful, and we DON'T want to link it. 

Can you elaborate?  Not sure what case you are referring to.  I'm available for voice if you prefer to discuss it there.

**Comment by jonathanolson** [comment]
> Can you elaborate? Not sure what case you are referring to. I'm available for voice if you prefer to discuss it there.

Say whenever the color changes (or is initialized), we want to set something's fill to color.withAlpha( alpha ). Doesn't seem easy if our support is only to mutate an attribute of a passed in object to addColoredInstance.

**Comment by samreid** [comment]
My recommendations:
1. If you need to use a constant color in 1 place, create it in that place
2. If you need to use a constant color in 2+ places, factor it out.
3. If you need to use a color Property in 1 place, create a color property in that place
4. If you need to use a color Property in 2+ places, factor it out.
5. If you want your color to appear in the color picker, add it to the color picker.
6. If you need colors to have different profiles, use addColorInstance (the example in https://github.com/phetsims/scenery-phet/issues/156#issuecomment-145601024 combines 5-6 but they wouldn't need to be combined).

Rules 1-4 apply to numbers, line widths, strings, etc which is why it makes sense to me that it should also apply to colors.

**Comment by jonathanolson** [comment]
> Rules 1-4 apply to numbers, line widths, strings, etc which is why it makes sense to me that it should also apply to colors.

However we handle translated strings similarly to how I've handled colors. For a sim, they are ALL in the same file, and then you have a way of accessing it (require() or access to the profile).

Just putting all colors in one place (1 rule) seems much more maintainable and simple to me. Will plan to discuss at developer meeting.

**Comment by samreid** [comment]
Consensus: We will go with a single color file.  Any colors used >1 time, or that need to be dynamically changed (in the color picker) or handled differently in different profiles should appear there.

**Comment by samreid** [comment]
We will not go back to old sims to factor out colors, just for new simulations.

**Comment by jbphet** [comment]
Or for existing simulations for which there is a request to support projector mode or some other color profile.

**Comment by pixelzoom** [comment]
@jonathanolson Do you feeling like this was addressed by your work in https://github.com/phetsims/scenery-phet/issues/278?

**Comment by jonathanolson** [comment]
Yes, closing.
