### ISSUE TITLE
Bracket node

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#158]
There's a need for a general bracket node. 

hookes-law needs a vertical bracket, as shown in this mockup:

![screenshot_519](https://cloud.githubusercontent.com/assets/3046552/7638772/5c7c2aa6-fa34-11e4-8f3b-4375e2db7cb5.png)

states-of-matter has a vertical bracket that looks almost identical:

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/3046552/7638880/30c69846-fa35-11e4-87c6-75707025c46e.png)

reactants-products-and-leftovers has a horizontal bracket (HBracketNode) that is more curvy:

![screenshot_520](https://cloud.githubusercontent.com/assets/3046552/7638768/5062241e-fa34-11e4-8169-41c165962304.png)

Unless there's some reason why the "set of straight lines" look is important, I'm going to generalize HBracketNode from reactants-products-and-leftovers.

**Comment by pixelzoom** [comment]
@arouinfar Would a curvy bracket be OK in hookes-law?

@jbphet Would a curvy bracket be OK in atomic-interactions?

**Comment by arouinfar** [comment]
@pixelzoom, yes, absolutely!

**Comment by pixelzoom** [comment]
The bracket in states-of-matter is implemented in ForcesControlPanel. It's not currently a separate Node subtype, and isn't particularly general.  So I still think the best approach is to generalize reactants-products-and-leftovers.HBracketNode, which is most of the way there.

**Comment by jbphet** [comment]
I think a curvy one would look fine in atomic-interactions, probably better than the one that's there.

As you can see from the screenshot from atomic-interactions, the one used there would look better if it were a little asymmetrical.  If it's easy to do, you might want to add the ability to alter the position of the "point".

**Comment by pixelzoom** [comment]
Accidentally checked in BracketNode in https://github.com/phetsims/scenery-phet/commit/98a4f5b09c929af2a92f07c71dc2594b634b052c.  It's not ready yet, so don't start using it.

**Comment by pixelzoom** [comment]
@jbphet wrote:
> you might want to add the ability to alter the position of the "point".

I did this, see options.bracketTipLocation.

BracketNode now supports various orientations (up, down, left, right).  And I've added it to the scenery-phet demo (Components screen).   And BracketNode is now being used in reactants-products-and-leftovers.

Assigning to @jbphet to review.

**Comment by jbphet** [comment]
Code looks good, seems like options are well thought out.  I added one additional option for line width, but it's pretty trivial.  I've integrated this into states-of-matter/atomic-interactions and it worked well.  Closing.
