### ISSUE TITLE
MultiLineText bugs

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#162]
In constructor:
> thisNode.text = text;

In set text:
> thisNode._text = string;

In get text:
> return this._text;

So we have `thisNode.text` and `thisNode._text`. They should all be the same.

**Comment by pixelzoom** [comment]
This is also potentially problematic, added by @samreid with comment "Fixes for the Adapted from PhET text fill".

```js  
getTextNodes: function() {
  var vbox = this.children[ 0 ];
  return vbox.getChildren();
},
```

This relies on the container for the Text nodes being the first child.  This can easily be broken by calling insertChild or moveChildToBack.

**Comment by pixelzoom** [comment]
In the constructor, this is actually calling the ES5 setter:

**Comment by pixelzoom** [comment]
This is also a problem, in `set text` at line 57:

```
    thisNode.children = [ new VBox( {
          children: value.split( '\n' ).map( function( line ) {
            if ( line.length === 0 ) { line = ' '; }  // creates a blank line between consecutive line breaks
            return new Text( line, _.omit( thisNode._options, 'align' ) );
          } ),
          align: thisNode._options.align
        } ) ];
```

So changing the text blows away all children that were previously added.

**Comment by pixelzoom** [comment]
Yet another problem.  If you do this:

```js
var text = new MultilineText( 'foo', { fill: 'green' } );
text.fill = 'red';
text.text = 'bar';
```

... you will not get red text, you'll get green text. This is because setFill does not save the new fill, and setText uses the fill that was provided by the constructor.

**Comment by pixelzoom** [comment]
I believe I've addressed all of the issues identified herein.  Some of these problems with introduced by a change made for "Adapted from PhET", and I have no idea how to test that.  So I tested in the context of AboutDialog, using this code snippet, which changes the "lead design" value string and fill.

```js
if ( credits.leadDesign ) {
      var t = new MultiLineText( StringUtils.format( leadDesignString, credits.leadDesign ), multiLineTextOptions );
      t.fill = 'red';
      t.text = 'Hello World';
      children.push( t );
    }
``` 

Assigning to @samreid to review, since he made the changes for "Adapted from PhET".

**Comment by samreid** [comment]
Looks good, I reviewed the code and tested using this snippet:

```js
    var multiLineText = new MultiLineText( 'hello\nworld\nnice\nto see you', { align: 'left', x: 100, y: 100 } );
    console.log( multiLineText.text );
    multiLineText.fill = 'blue';
    this.addChild( multiLineText );
    multiLineText.text = 'gretings\nagain';
    console.log( multiLineText.text );
```

And the output was as expected.  Closing.
