### ISSUE TITLE
LineArrowShape

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#165]
ArrowNode currently uses ArrowShape to draw arrows that look like this:

![screenshot_533](https://cloud.githubusercontent.com/assets/3046552/8092042/908abc04-0f74-11e5-8f67-f37d87e64cf9.png)

Hooke's Law requires an arrow that looks like this:

![screenshot_534](https://cloud.githubusercontent.com/assets/3046552/8092055/a1f4f52c-0f74-11e5-82d6-3acca48a8081.png)

This new type of arrow is currently implemented in hookes-law.LineArrowNode, but should be generalized and moved to scenery-phet.  It's currently not fillable, it doesn't support a head at both ends of the arrow, and the precision of the tip is off a bit because it doesn't account for lineWidth.

Tentative plan:
• create LineArrowShape, with options that are identical to ArrowShape
• add an option to ArrowNode that specifies whether to use ArrowShape or LineArrowShape, defaults to ArrowShape

**Comment by pixelzoom** [comment]
For Hooke's Law, it's important to resolve the problem with the precision of the tip, so I'll probably do this sooner rather than later.

**Comment by pixelzoom** [comment]
Unless we use options.tailWidth for the width of the head segments, it seems impossible for LineArrowShape have the same API as ArrowShape.  That seems like an abuse of options.tailWidth. @jonathanolson suggested renaming tailWidth to bodyWidth throughout the ArrowShape/ArrowNode API, and at all use sites.  There are currently 121 occurrences of "tailWidth", so I'm going to wait on that until the end of this issue.

**Comment by pixelzoom** [comment]
Another questions, see line drawing below. headWidth presumable corresponds to dimension "w" in the drawing. But does "headHeight" correspond to "h1", "h2", or something else?

![screenshot_535](https://cloud.githubusercontent.com/assets/3046552/8093154/7bff53fa-0f7c-11e5-9144-fd403e48df8f.png)

**Comment by samreid** [comment]
I think headHeight would be h1.

**Comment by pixelzoom** [comment]
I asked:
> A question about the displacement vectors in Hooke’s Law…  They are implemented using LineArrowNode, something I implemented for Hooke’s Law but intend to move to common code.  See https://github.com/phetsims/scenery-phet/issues/165.  This is not needed by others sims yet, so there’s no pressing need to complete the work.  But there is one quirk that I’d like your input on. Because the arrow is a stroked (versus filled) shape, the position of the tip is not precise - it’s off by (approximately) half the line width. The longterm plan is to reimplement LineArrowNode as a filled shape, but that’s a nontrivial chunk of work. The imprecision doesn’t seem to be a significant issue in Hooke’s Law, and I don’t recall anyone (expect me :) noticing it.  So… Is this something that needs to be resolved before publishing, or can it be published with this slight imprecision of the displacement vectors?

@arouinfar replied:
> I don't see this as an issue that should block publication. I certainly haven't noticed the imprecision of the displacement vector, so I doubt it is likely to cause confusion among students and teachers. I can also make a note of this in the teacher tips.

So I'm removing the "high priority" label from this issue.

**Comment by pixelzoom** [comment]
Unassigning. No plans to work on this until someone needs it in another sim.

**Comment by pixelzoom** [comment]
This came up in 1/4/18 status meeting.  We had decided to defer moving this to common code until another sim needed it.  Masses and Springs is has an identical copy of LineArrowNode.js.   @Denz1994 let's generalize LineArrowNode.js and move it to scenery-phet.

**Comment by Denz1994** [comment]
I will work on cleaning up documentation and implementation in DisplacementArrowNode.js for Masses and Springs. Once that is complete, @pixelzoom and I can work on consolidating this into common code.

**Comment by ariel-phet** [comment]
Noting as possible work for @andrea-phet

**Comment by samreid** [comment]
@pixelzoom and @Denz1994 I want to clarify the proposed work for this issue.  Should the new arrow depicted in https://github.com/phetsims/scenery-phet/issues/165#issuecomment-110901143 be drawn as a filled shape with 9 vertices, or as a stroked shaped with 4 vertices?

**Comment by pixelzoom** [comment]
+1 for filled shape. In addition to being more flexible, the (unstroked) length will be more accurate.

**Comment by pixelzoom** [comment]
I'm going to unassign myself for now. When someone starts working on this, feel free to get me involved.

**Comment by ariel-phet** [comment]
Bumping to high priority as this should be done as part of getting masses and springs to publication

**Comment by Denz1994** [comment]
Discussion with @jonathanolson:
 
In response to @pixelzoom: 

> add an option to ArrowNode that specifies whether to use ArrowShape or LineArrowShape, defaults to ArrowShape

1. The options are not shared between ArrowShape and LineArrowNode. There would need to be workarounds for options like ```options.fill``` which isn't required for LineArrowNode. Other examples include: ```headHeight, isDynamicHead, scaleTailToo, fractionHeadHeight``` There seems to be a mismatch in the options api.

2. LineArrowNode needs two subPaths for the tailNode (line segment) and the headNode (3 points). ArrowShape currently uses a Path for points only. There is another mismatch in how the Paths are drawn.

3. Line joins and rounding arrow verticies would not be possible with a stroked arrow. These actions may be desirable in the future and it presents another mismatch.

@pixelzoom Thoughts on how we should proceed with consolidating LineArrowNode into ArrowNode?

As of right now @jonathanolson and I are leaning towards not combining the two and leaving LineArrowNode as its own common code component.

**Comment by pixelzoom** [comment]
> As of right now @jonathanolson and I are leaning towards not combining the two and leaving LineArrowNode as its own common code component.

Fine with me.

**Comment by Denz1994** [comment]
I am going to close this issue then. I've investigated how to consolidate ArrowNode.js with LineArrowNode.js and after review with @pixelzoom and @jonathanolson it makes sense to leave them separate. Thanks for the input. Closing.

**Comment by pixelzoom** [comment]
`LineArrowNode` was also moved from masses-and-spring to scenery-phet with this TODO, which was presumably addressed by closing this issue:

```js
3 //TODO scenery-phet#165 reimplement as LineArrowShape and a Path subtype, move to scenery-phet
```

... and with this TODO, which has no associated issue number:

```js
126 // TODO: Are these points correct? Would it be better to add a line segment for the tail?
```

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/scenery-phet/issues/165#issuecomment-391346542, @Denz1994 said:
> I've investigated how to consolidate ArrowNode.js with LineArrowNode.js and after review with @pixelzoom and @jonathanolson it makes sense to leave them separate.

But I see significant changes to ArrowNode.  Option `useArrowShape` was added, it's using `LineNode.getArrowPoints`, and some TODO comments were added without associated issue numbers.  @Denz1994 did you accidentally commit this, or forget to revert it?

**Comment by pixelzoom** [comment]
@Denz1994 and I collaborated via Slack and cleaned things up.  Changes to `ArrowNode` were indeed something that should not have been committed or should have been reverted.   They were rolled back in the above commits.

**Comment by pixelzoom** [comment]
SCENERY_PHET/LineArrowNode had been used in one place in hookes-law, but there was still one place using HOOKES_LAW/LineArrowNode.   I cleaned things up in the above commits, and deleted HOOKES_LAW/LineArrowNode.   That completes this issue.  Closing.
