### ISSUE TITLE
NumberPicker highlighting is broken

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#168]
As reported in https://github.com/phetsims/balancing-chemical-equations/issues/101#issuecomment-119715620, the top and bottom halves of the number display no longer highlight on pointer over.

**Comment by pixelzoom** [comment]
Bug introduced in 73d83fd892ac1413fb2803fbdc6e3310774da44d on 1/15/15, when PressAndHoldListener was factored out for use in ArrowButton.

**Comment by pixelzoom** [comment]
Fixed. @aaronsamuel137 would you mind verifying? There's a sample NumberPicker in the "Components" screen of the scenery-phet demo app.

**Comment by aaronsamuel137** [comment]
Looks good. There is one behavior that seems odd to me where mousing over the space between the arrows and the number picker itself doesn't have the highlight. Is this intended? It looks a little weird if you go to mouseover the number picker and the highlight flashes on and off when going over this region.

**Comment by aaronsamuel137** [comment]
Assigning to @pixelzoom to comment or address

**Comment by pixelzoom** [comment]
Moved the feature request to https://github.com/phetsims/scenery-phet/issues/169.

Closing.
