### ISSUE TITLE
highlight behavior of NumberPicker

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#169]
There is one behavior that seems odd to me where mousing over the space between the arrows and the number picker itself doesn't have the highlight. Is this intended? It looks a little weird if you go to mouseover the number picker and the highlight flashes on and off when going over this region.

**Comment by pixelzoom** [comment]
This could be addressed by adding a transparent overlay that covers both an arrow and its associated half (top or bottom) of the numeric display.  Then attach the inputListeners to the overlays instead of the arrows and numeric display.  pointerArea changes should also apply to the overlaps.

**Comment by pixelzoom** [comment]
Enhancement completed in https://github.com/phetsims/scenery-phet/commit/62d12071a7768241b8b62d65f5d4c966ff31b514. 

For the primary work... I added an invisible rectangle on top of the arrow + background piece, and applied input event processing and pointer areas to that.  Here's the relevant bit of code:

```js
    // parents for 'up' and 'down' components
    var upParent = new Node( { children: [ upBackground, this.upArrow ] } );
    upParent.addChild( new Rectangle( upParent.localBounds ) ); // invisible overlay
    var downParent = new Node( { children: [ downBackground, this.downArrow ] } );
    downParent.addChild( new Rectangle( downParent.localBounds ) ); // invisible overlay
```

Other changes:
• moved static functions (createVerticalGradient, updateColors) outside of the constructor
• better names for a couple of options (updated in clients)
• reorganized the code in the constructor a bit, specifically the code related to pointer areas and computation of colors

Assigning to @aaronsamuel137 for review.  You can test in one or more of these places:
• scenery-phet demo, "Components" screen
• Graphing Lines, any screen
• Balancing Chemical Equations, any screen

**Comment by aaronsamuel137** [comment]
Looks great to me. Thanks! Closing
