### ISSUE TITLE
tandem should not be passed to supertype

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#171]
In general, if a type calls tandem.addInstance, then the tandem should not be passed to the supertype, as this can lead to multiple calls to addInstance. There several examples in scenery-phet (EyeDropperNode, FaucetNode,...) where a subtype calls tandem.addInstance, and then proceeds to pass the tandem to its supertype.

**Comment by samreid** [comment]
Please see my thoughts over here https://github.com/phetsims/sun/issues/192#issuecomment-121104265

**Comment by pixelzoom** [comment]
7/14/15 dev meeting consensus: If you pass a tandem through options, don't pass it to supertype unless you document why you're doing so.

**Comment by pixelzoom** [comment]
@samreid In light of the work you did recently in phetsims/together#236, should this issue be closed?

**Comment by pixelzoom** [comment]
I believe that the

**Comment by pixelzoom** [comment]
I believe that the above recommendation is no longer valid.  If we implemented the proposal in  https://github.com/phetsims/sun/issues/192#issuecomment-169191660, then:
(1) tandem is passed through to supertype, and
(2) tandem.createSupertypeTandem is used in subtypes

**Comment by samreid** [comment]
Correct, we are going to try sun#192 next, closing.
