### ISSUE TITLE
move PhetColorScheme.RED_COLORBLIND to scenery.Color?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#174]
In https://github.com/phetsims/scenery-phet/issues/140#issuecomment-77626617, @samreid asked:

> Can (/should?) we move RED_COLORBLIND from PhetColorScheme to Color? It may be much more convenient for many usage sites.

My opinion is no - RED_COLORBLIND is PhET-specific, so it doesn't belong in scenery.Color.

Assigning to @jonathanolson for his opinion.

**Comment by jonathanolson** [comment]
It sounds best to keep it in PhetColorScheme. Was the recommendation to support fill: 'red_colorblind' or fill: Color.RED_COLORBLIND?

**Comment by samreid** [comment]
I was thinking of Color.RED_COLORBLIND.

**Comment by pixelzoom** [comment]
8/20/15 dev meeting consensus: leave in scenery-phet. 

Closing.
