### ISSUE TITLE
Add ability to change head options in ArrowNode

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#175]
In trig-tour, there is an arrow that can change head width and height so that the head does not cover up the tail as the arrow shrinks down in size.  This seems like a good feature to have generalized in ArrowNode.

A possible way to do this would be to change setTailAndTip() to setArrowShape():
```
     /**
     * Set the tail and tip locations to update the arrow shape.  Optionally pass in new value for the headHeight,
     * headWidth, and tailWidth.
     * 
     * @param {number} tailX
     * @param {number} tailY
     * @param {number} tipX
     * @param {number} tipY
     * @param {object} options
     */
    setArrowShape: function( tailX, tailY, tipX, tipY, options ) {
      options = _.extend( this.options, options );
      this.shape = new ArrowShape( tailX, tailY, tipX, tipY, options );
    }
```
Would anyone object to this, or suggest a different method?

**Comment by pixelzoom** [comment]
I believe that this may be the feature that you're looking for: https://github.com/phetsims/scenery-phet/issues/33.

**Comment by jessegreenberg** [comment]
Yes, that is exactly what I am looking for.  Thanks!  Closing this now as it is duplicate.
