### ISSUE TITLE
Too many screens?

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#177]
Thanks to https://github.com/phetsims/bending-light/issues/165 the example now has 5 screens.  Is this too many?  It renders properly, but long ago we decided we would never have a sim with more than N screens, and it looks like we reached N+1.  How should we proceed?

![image](https://cloud.githubusercontent.com/assets/679486/9633065/065fc6b2-5148-11e5-8ba7-d666a53d983d.png)

**Comment by pixelzoom** [comment]
For this specific case:
• Bug: the new (5th) screen should not be named "Spring"
• The intensity meter doesn't warrant its own screen. It should probably be on the "Components" screen, with other similar compound components. To do that, you should address the overcrowding issue on that screen, rather than create a new screen.  Brainstorming: Select which component to test via a combo box on the "Components" screen.

**Comment by samreid** [comment]
Fixed the name above.  Lint fixes coming!

**Comment by samreid** [comment]
The lint fixes have arrived!

**Comment by pixelzoom** [comment]
This general issue (what to do about >4 screens) also came up recently in https://github.com/phetsims/hookes-law/issues/16#issuecomment-119759271 (when I added the "Springs" screen), and we decided to kick the can down the road.  The road is apparently coming to an end :)

**Comment by ariel-phet** [comment]
:+1: on the combo box

**Comment by samreid** [comment]
Perhaps a horizontal set of radio buttons along the bottom of the screen (just above the navbar) would work well.  We could easily put an icon in each one.  It would be like one layer of nesting for the navbar choices, and make it easy to see all of your choices at once and not have to click through a menu to change to the one you want.

**Comment by jbphet** [comment]
Discussed in 9/3/2015 developer meeting and came to a consensus that having the controls in some sort of parent control on the "Components" screen is a good approach.

Personally, I'd vote for putting them in a carousel, but a combo box or radio buttons would also be fine.  This can be left to the implementer's discretion.

@samreid will delete 5th screen and move things from there into the "Components" screen.

**Comment by pixelzoom** [comment]
> Personally, I'd vote for putting them in a carousel, but a combo box or radio buttons would also be fine. 

-1 for carousel.  I want to go immediately to the the sub-category that I'm interested in, I don't want to have to scroll through N sets of things to get there.

-1 for radio bottons. As we add radio buttons, they take up more space.

+1 for combo box. It takes up the smallest amount of space, and takes up the same amount of space regardless of the number of sub-catagories.

**Comment by pixelzoom** [comment]
I reorganized this using ComboBox, but did it in such a way that each "demo" is encapsulated in a separate function, and there's a data structure that could be used to create some other type of control. Here's the data structure:

```js
    // To add a demo, create an entry here.
    var demos = [
      { label: 'BracketNode', node: demoBracketNode( this.layoutBounds ) },
      { label: 'ConductivityTesterNode', node: demoConductivityTesterNode( this.layoutBounds ) },
      { label: 'EyeDropperNode', node: demoEyeDropperNode( this.layoutBounds ) },
      { label: 'FaucetNode', node: demoFaucetNode( this.layoutBounds ) },
      { label: 'LightSensorNode', node: demoLightSensorNode( this.layoutBounds ) },
      { label: 'MeasuringTape', node: demoMeasuringTape( this.layoutBounds ) },
      { label: 'NumberPicker', node: demoNumberPicker( this.layoutBounds ) },
      { label: 'RulerNode', node: demoRulerNode( this.layoutBounds ) },
      { label: 'StarNode', node: demoStarNode( this.layoutBounds ) },
      { label: 'ThermometerNode', node: demoTemperatureNode( this.layoutBounds ) }
    ];
```

Here's a screenshot of the "Components" screen, with the combo box expanded.

![screenshot_596](https://cloud.githubusercontent.com/assets/3046552/9692652/b5f7dd38-5307-11e5-98bd-0d7c57cca15b.png)

**Comment by pixelzoom** [comment]
Assigning this to @samreid to review, since the work was originally assigned to him.

**Comment by pixelzoom** [comment]
The "Sliders" screen was also getting a little crowded, with layout dependencies between the demos. So I applied the same "combo box" treatment to the "Sliders" screen.

**Comment by samreid** [comment]
Looks great.  My only recommendations are:

(1) allow a query parameter to select the initially selected node
(2) check how long it takes to launch the application with all components nodes instantiated.  Then test again with no component nodes instantiated.  If it is more than 500ms to create all of the nodes, consider creating them lazily and one at a time rather than all up-front.

@pixelzoom thoughts on these recommendations?  Should I implement them?

**Comment by pixelzoom** [comment]
If you'd like those features, go for it.

**Comment by samreid** [comment]
On my platform, it takes 600ms to create all of the demo nodes.  230ms is taken in creating ProbeNode and its controls.  I guess this is enough to make me want to make this usable for isolated tests.

**Comment by samreid** [comment]
Proposed query parameter for selecting a single component:

(for example)
?component=ProbeNode

Then you can easily iterate on a component using ?screens=3&component=MyComponent

**Comment by samreid** [comment]
I added these features above, please see commit message.  @pixelzoom would you please take a look and let me know if you have any recommendations for those changes?

**Comment by pixelzoom** [comment]
Looks good. My only suggestion would be to make the query parameter plural (`components`), similar to other query parameters like `screens`.  You may want to iterate on >1 related components.

**Comment by pixelzoom** [comment]
Eg: ?screens=3&component=ProbeNode,RulerNode

**Comment by pixelzoom** [comment]
I took a closer look at the implementation... The demos are filtered after they've been instantiated.  So how does this improve startup time?  If it doesn't then recommended to simply make `?component` be the component that's selected in the combo box at startup, rather than making it be the only component in the combo box.

**Comment by pixelzoom** [comment]
Ah, I see.... You changed the allDemos structure to include functions that create the demos.

In that case, why not instantiate components on demand (when first selected), and make `?component` be the initial selection?

**Comment by pixelzoom** [comment]
I'm going to take a stab at what I described immediate above.

**Comment by pixelzoom** [comment]
All demos now appear in the combo box, but they are create on demand (that is, created and added to the scenegraph when they are selected from the combo box).  The 'component' query parameter simply determines which demo is initially selected in the combo box, e.g.:

http://localhost/~cmalley/Github/scenery-phet/scenery-phet_en.html?screens=3&component=ProbeNode

Back to @samreid for review.

**Comment by pixelzoom** [comment]
Since the "Sliders" screen has a similar mechanism for selecting a demo, should apply this same pattern there? With a similar query parameter like 'slider'?

**Comment by pixelzoom** [comment]
Easy to apply this pattern to "Sliders" screen now (rather than later), so I did it.  Example:

http://localhost/~cmalley/Github/scenery-phet/scenery-phet_en.html?screens=2&slider=WavelengthSlider

**Comment by pixelzoom** [comment]
ComponentsView and SlidersView were identical, except for the query parameter name and the set of demos. Factored out base type DemosView.

**Comment by pixelzoom** [comment]
OK, think I'm done. Really ready for review now :)

**Comment by samreid** [comment]
These changes look great, I have used them to develop ProbeNode in isolation and it has been working very well.  Good idea applying the same idea to the slider screen.  Closing.
