### ISSUE TITLE
Generalize the colors for ProbeNode

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#179]
The LightSensorNode is hard-coded to be green, with many variants & shades of green to make it look nice and 3d.  We should (eventually?) generalize this to support any color scheme.  Discovered in https://github.com/phetsims/bending-light/issues/165

**Comment by samreid** [comment]
Perhaps a good time to generalize this would be the first time we have a non-green LightSensorNode?

**Comment by samreid** [comment]
I generalized the colors above.  With the same base color as the concentration probe, I get this:

![image](https://cloud.githubusercontent.com/assets/679486/9751958/55d90738-5668-11e5-82ba-bdde2b7c931d.png)

Let's go an extra mile and put a color picker in the scenery-phet playground.

**Comment by samreid** [comment]
I don't think we have a true color picker yet.  Could use a wavelength slider?

**Comment by samreid** [comment]
Wavelength slider added above, colors look good across a wide variety (shadows a bit hard to see against yellow, but I think that is acceptable).

**Comment by samreid** [comment]
Reassigned to @pixelzoom to take the colors for a test drive.

**Comment by pixelzoom** [comment]
Changed issue title since LightSensorNode was renamed to ProbeNode.

**Comment by pixelzoom** [comment]
A color chooser would be better, but a WavelengthSilder seems OK.

Showing the wavelength value seems unnecessary, so I hid it in https://github.com/phetsims/scenery-phet/commit/71fdecc554193e083c6249e462b7d1b80ea50170. 

The initial state color of the ProbeNode in the demo is out of sync with the WavelengthSlider. And I don't understand the rationale behind this bit of code:

```js
    // Only switch to the wavelength slider after it has been changed once
    var useWavelength = false;
    wavelengthProperty.lazyLink( function() {
      useWavelength = true;
    } );
```

The slider and probe color should be synchronized.

**Comment by pixelzoom** [comment]
A problem with using WavelengthSlider is that you can't set some color values, e.g. the default color of ProbeNode ('#008541').

**Comment by pixelzoom** [comment]
How about RGB sliders instead of WavelengthSlider?

**Comment by pixelzoom** [comment]
Reversing my opinion of WavelengthSlider... A problem with using WavelengthSlider is that you can't set some color values, e.g. the default color of ProbeNode ('#008541').

How about RGB sliders instead of WavelengthSlider?

**Comment by samreid** [comment]
> How about RGB sliders instead of WavelengthSlider?

I'd rather see a scenery-phet (or sun?) color picker.  Even if bare-bones, it would be useful here, reusable elsewhere, etc.  And it could grow features when needed.

**Comment by pixelzoom** [comment]
A general color picker would be nice (and not the first time it's come up), but that's a separate project. For now I've replaced the WavelengthSlider with RGB sliders. See https://github.com/phetsims/scenery-phet/commit/0baef9a96c1dcb90f2aad6ef6d20750074015ec5.

**Comment by samreid** [comment]
Looks good.  So, anything else left to do here?

**Comment by samreid** [comment]
Handling different angles for the gradients is handled in https://github.com/phetsims/bending-light/issues/165

**Comment by pixelzoom** [comment]
Everything seems to be addressed, closing.
