### ISSUE TITLE
LightSensorNode looks odd at some combinations of width/height

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#180]
LightSensorNode was ported from Bending Light in https://github.com/phetsims/bending-light/issues/165.  It behaves well when width and height are within a nearby range of the default width and height, but when they are radically different, you get shapes like this:

![image](https://cloud.githubusercontent.com/assets/679486/9636855/0001891e-515b-11e5-8a97-5bd340babd57.png)

Since most of our simulations use values near to the default width and height, this may be acceptable.  Raising this as an issue for discussion in the review of https://github.com/phetsims/bending-light/issues/165

**Comment by samreid** [comment]
Having trouble deciding whether the glass region should always be circular:
![image](https://cloud.githubusercontent.com/assets/679486/9749398/eb8f808c-5649-11e5-8843-7a4086fbac34.png)

```js
    var radius = Math.min( width, height * 100 / 151 ) * 0.38;
    var innerCirclePath = new Path( Shape.circle( 0, 0, radius ), {
```
or not:

![image](https://cloud.githubusercontent.com/assets/679486/9749493/8dd273a4-564a-11e5-836e-d3acce5b8e3e.png)

```js
var innerCirclePath = new Path( new Shape().ellipticalArc( 0, 0, width * 0.35, height * 100 / 151 * 0.35, Math.PI, 0, Math.PI * 2, false ), {
```

@pixelzoom can you vote?

**Comment by pixelzoom** [comment]
If the part of the probe that surrounds the glass is not constrained to be circular, then +1 for the glass not being circular.  

I guess this makes it more general. But all PhET probes thus far have had circular glass with circular surrounding area.

**Comment by samreid** [comment]
I went elliptical in the above commit. but I'm seeing a chord across the ellipse like so, for some settings of width/height:

![image](https://cloud.githubusercontent.com/assets/679486/9750172/adc56c3c-5651-11e5-98d8-a0d1dd421e0c.png)

It is easy to reproduce this problem in the scenery-phet demo for "ProbeNode".  @jonathanolson can you see what is wrong with the kite ellipse?

**Comment by samreid** [comment]
Oh, it looks like the problem is with the radial gradient fill, not with the kite shape.

**Comment by samreid** [comment]
Gradient fill fixed above.

**Comment by samreid** [comment]
OK the probe can handle any width and height, closing.
