### ISSUE TITLE
ProbeNode: add an option to rotate the gradients

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#183]
So the probe can be used at different orientations, the highlight gradient should have a settable angle.  We should add controls to test the angle in the demo app.  We can use NumberControl, with options.decimalPlaces for snapping and options.majorTicks for the 2pi label.

See parent issue https://github.com/phetsims/bending-light/issues/165

**Comment by samreid** [comment]
Option added above, with a new slider in the scenery-phet demo harness.  @pixelzoom can you review at your convenience?

**Comment by pixelzoom** [comment]
Integration into scenery-phet demo has problems.  The "Light Angle" control was added to a block that is commented as "Color controls".  And there's no space between the color (RGB) controls and the "Light Angle" control, which is unrelated.  I put a panel around the color controls to group them.  Also added labeled tick marks to the "Light Angle" control.

A couple of issues with the feature itself:

(1) Is "Light Angle" the most useful option to provide? This is a PhET-specific component (scenery-phet), and PhET's convention is for light to come from top-left.  And we know the default orientation of this node is with light at top-left. It would be preferably not to have to deal with both rotation and lightAngle when using non-default orientations of ProbeNode.  Is there another way that this can be handled? Can be look at the node's (global) rotation and decide how to shade the geometry?  

(2) The default value of `options.lightAngle` is `4.25`. I'd rather see this expressed in terms of Math.PI. And if the light is coming from the top-left, shouldn't the value be `1.25 * Math.PI` ?

**Comment by samreid** [comment]
> Can be look at the node's (global) rotation and decide how to shade the geometry?

That sounds tricky--often the node is rotated after it is created so this would require us to be able to mutate the gradient of the instance rather than just getting it right during initialization.

> Is there another way that this can be handled? 

I am somewhat concerned that spending >2hrs here to make the light angle operate seamlessly with the probe rotation may only end up saving us ~5 minutes/sim.  If (!) these figures are accurate, the break-even point would be around 24 simulations.  Do you have different values for the variables in the preceding sentences?

The light angle issue herein also overlaps significantly with #192 which is still an unknown in terms of approach and workload.

**Comment by samreid** [comment]
Factored out Math.PI above.  The only outstanding issue here is the API for the lighting angle.  I have previously noted that this overlaps with #192 significantly and hence should probably be worked on together with it.

**Comment by samreid** [comment]
I'd also appreciate hearing @pixelzoom thoughts based on https://github.com/phetsims/scenery-phet/issues/183#issuecomment-144463325 above.

**Comment by pixelzoom** [comment]
@samreid wrote:
> I'd also appreciate hearing @pixelzoom thoughts based on https://github.com/phetsims/scenery-phet/issues/183#issuecomment-144463325 above.

I was just pointing out that using anything other than the default orientation for the probe *requires* you to set the lightAngle.  If it's too difficult to couple them, the OK with me to leave as is.  But highly recommended to document that lightAngle must be changed if the orientation is changed, in order to keep PhET lighting policy consistent.

**Comment by samreid** [comment]
Yes, let's add documentation that it is up to the developer to set the lightAngle since it is generally difficult to automatically handle gradient changes due to the global rotation changes.

**Comment by samreid** [comment]
I added docs above, copied here for your convenience:

```js
  // constants
  var DEFAULT_OPTIONS = {
    radius: 50,
    innerRadius: 35,
    handleWidth: 50,
    handleHeight: 30,
    handleCornerRadius: 10,

    /**
     * in radians, the angle of the incoming light.  0 is from the right, PI/2 from the bottom, PI from the left, etc.
     * The default is from the upper-left.  Generally, it is difficult to know the global rotation of the ProbeNode
     * and automatically update the lightAngle when the global rotation changes, so this is up to the developer
     * to set properly.  The light in PhET simulations often comes from the top-left, so please set this value
     * accordingly depending on the context of how the probe is embedded in the simulation.
     */
    lightAngle: 1.35 * Math.PI,
    color: '#008541', // {Color|string} darkish green

    // The circular part of the ProbeNode is called the sensor, where it receives light or has crosshairs, etc.
    // or null for an empty region
    sensorType: glass()
  };
```

@pixelzoom anything else for this issue?

**Comment by pixelzoom** [comment]
Looks great, closing.
