### ISSUE TITLE
ProbeNode should be rounded

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#184]
It was squared for generalization in https://github.com/phetsims/bending-light/issues/165 but now it should be rounded out again.

**Comment by samreid** [comment]
I rounded out the bottom corners in the above commit, you can adjust the rounding dynamically in the scenery-phet demo.  Here's the default radius=10:

![image](https://cloud.githubusercontent.com/assets/679486/10093774/d4dc1f94-6314-11e5-88ab-a714cf699c19.png)

Here's corner radius = 0:
![image](https://cloud.githubusercontent.com/assets/679486/10093779/e03bd88e-6314-11e5-87da-195d4f8134bc.png)

You can also kind of make a magnifying glass:
![image](https://cloud.githubusercontent.com/assets/679486/10093795/039035c8-6315-11e5-88de-a12c9cb014a0.png)

@ariel-phet @pixelzoom @arouinfar do you think we should spend additional time to round the "neck" corners?

**Comment by ariel-phet** [comment]
I would say yes...it would seem more aesthetically consistent.

**Comment by samreid** [comment]
I texted my colleagues:

Hey Everybody (but perhaps mostly @jonathanolson), I have a line segment adjoined to another line segment at an angle theta.  Now instead of a sharp angle, I would like to show a smooth curve between the 2 line segments.  How do I do this with Kite Shape?

Reassigning to @jonathanolson for feedback.

**Comment by samreid** [comment]
@jonathanolson said curveTo

**Comment by samreid** [comment]
I rounded out the corners above, now the default looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/10105928/de4de33c-636e-11e5-90fb-f8954ae9d044.png)
