### ISSUE TITLE
Add controls for the cross-hairs/glass/empty in the demo application.

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#185]
Also, make the crosshairs and glass default options public in ProbeNode.  See parent issue https://github.com/phetsims/bending-light/issues/165

**Comment by samreid** [comment]
I added radio buttons to the scenery-phet demo to test the following options for the sensor type:
null: (empty)
glass
crosshairs
a non-default glass.

One deficiency is that while possible, it is not easy to change the location of the center of the gradient for the glass, but in my opinion this is subtle and not necessary to implement at this time.

@pixelzoom can you review this and let me know if you have suggestions?

**Comment by pixelzoom** [comment]
Looks good to me.

**Comment by samreid** [comment]
Thanks, closing.

**Comment by pixelzoom** [comment]
Reopening.

The API for creating the sensor portion of the probe seems a bit convoluted and complicated.

Here's the interface, ProbeNode line 192:

```js
       // Sensor types
      // @public 
      crosshairs: crosshairs,
      glass: glass
```

Issues:

(1) These are not sensor types (as the comment says). These are functions *that return a function* that creates a {Node} that represents the sensor part of the probe. That seems unnecessarily complicated. 

(2) The terse names of these are misleading. My first instinct was that their type was {Node}. 

(3) `options.sensorType` is similarly misleading. It is a function that returns a function that creates a node. It's type is also undocumented in DEFAULT_OPTIONS, and the document that is there is incomplete/misleading.

So I don't thing we're done here, the API needs work.

**Comment by pixelzoom** [comment]
Recommendations:

• Add `radius` as a first (required) parameter to functions `glass` and `crosshairs`. This gets rid of the "function that returns a function that returns a Node" complexity, and it's simply "function that returns a Node".

• Rename options.sensorType to sensorFunction, document that it's a {function} that takes `{number} radius` and `{Object} [options]` parameters, and returns `{Node}`.

• Rename statics `glass` and `crosshairs` to `createGlassSensor` and `createCrosshairsSensor` respectively.

**Comment by pixelzoom** [comment]
I'm going to take a stab at this.

**Comment by pixelzoom** [comment]
Ah... I see why you did the "function that returns a function" thing here. You want the client to provide the options, and ProbeNode to provide the radius.  There must be a better API.

**Comment by samreid** [comment]
Can we schedule an appointment to collaborate on this?  I'm unclear what the issues are and what your recommendations are.

**Comment by pixelzoom** [comment]
I think the first step should be to see if anyone shares my concerns about the current API/implementation, as summarized in https://github.com/phetsims/scenery-phet/issues/185#issuecomment-143845748. If not, then perhaps no changes are needed. If they also find it confusing, then we can discuss how to revise. 

@jbphet can you take a look?

**Comment by pixelzoom** [comment]
Poking @jbphet on this, since it's starting to be integrated into sims (beers-law, ph-scale,...)

**Comment by jbphet** [comment]
I just spent some time looking at this, and I would say that yes, I find the portion of the API that controls the glass and crosshairs to be confusing.  At the least there should be some better documentation and naming (as @pixelzoom suggests above).  Whether or not its worth the time to think through a generally better approach, well, I'll leave that to @pixelzoom and @samreid.  My guess is that this component will generally be used with basic options, and if the type of customization supported by these options is needed, the developer would be able to figure them out from the demos.

I'm assuming there was at least some input from designers about potentially needing custom glass and crosshairs at some point.  If not, these seems like overkill versus just having options to turn each one on or off.

**Comment by pixelzoom** [comment]
Back to @samreid.  @jbphet also finds it confusing. But as he said, developers will probably figure it. So I'd be OK with leaving the API basically as is, but renaming options `sensorType` to `sensorTypeFunction` and documenting it correctly.

**Comment by samreid** [comment]
I replaced sensorType=sensorTypeFunction globally (4 files), tested Beer's Law Lab, the components view in the scenery-phet demo and ph-scale, and they all seem to be working properly.  I'll commit shortly.

**Comment by samreid** [comment]
I committed above.  Also, after commiting this I recalled a conversation earlier where @pixelzoom expressed an interest in "freezing" beer's law lab code during release candidate testing, see https://github.com/phetsims/chipper/issues/396#issuecomment-154195376 Please let me know if this work should be reverted and deferred until that release candidate testing is complete, or if there is anything else to do here.

**Comment by pixelzoom** [comment]
Looks good, closing.
