### ISSUE TITLE
Add GREEN_COLORBLIND to PhetColorScheme?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#187]
In trig-tour, a GREEN_COLORBLIND is used with components rgb(0, 185, 0).  It performed well in colorblind tests when used alongside RED_COLORBLIND.

Should GREEN_COLORBLIND be added to PhetColorScheme?  If so, we should search for cases of 'green' being used in sims with RED_COLORBLIND and replace with PhetColorScheme.GREEN_COLORBLIND.

**Comment by pixelzoom** [comment]
9/24/15 dev meeting:

• Yes, add to PhetColorScheme.
• Do not need to replace uses of 'green'.  If there are colorblind problems, we'll catch them in testing.

**Comment by jessegreenberg** [comment]
GREEN_COLORBLIND added to the PhetColorScheme.  Since we do not need to look for instances of 'green' and replace, this can be closed.
