### ISSUE TITLE
API for resetting optional parameters

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#189]
In ArrowNode, there is a pattern for setting the doubleHead optional parameter post construction that looks like:

```@private``` closure in the constructor:
```js
    this.setDoubleHeaded = function( doubleHead ) {
      options.doubleHead = doubleHead;
    };
```
```@public``` setter in the prototype:
```js
    /**
     * @public - set whether the arrow has one triangle or two
     * @param doubleHead
     */
    setDoubleHead: function( doubleHead ) {
      this.setDoubleHeaded( doubleHead );
      this.updateShapePoints();
      this.updateShape();
    }
```
In the future we will likely want to set other optional parameters as well.  Should we assume the above API for setting options?  Something along the lines of scenery.Node.mutate( options ) could be one alternative.

**Comment by pixelzoom** [comment]
9/29/15 dev meeting:  Store options that are needed by prototypes, rather than use function closures.

**Comment by jessegreenberg** [comment]
Done in the commit above.  Reassigning to @aaronsamuel137 for review.

**Comment by aaronsamuel137** [comment]
Looks good! Closing
