### ISSUE TITLE
pattern for exposing default options

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#190]
I'm going to discuss this in the context of scenery-phet.ProbeNode, but it can apply to any common code.  And I've seen these same mistakes in other contexts.

Here's the pattern that was used to expose default options:

```js
1 define( function( require ) {
2
3   var DEFAULT_OPTIONS = {…};
4
5   function ProbeNode( options ) {
6     options = _.extend( DEFAULT_OPTIONS, options );
7   }
8
9  return inherit( Node, ProbeNode, {}, {
10    DEFAULT_OPTIONS: DEFAULT_OPTIONS
11  } );
12
13 } );
```

Two problems with this pattern.

(1) On line 6, the `_.extend` call will modify `DEFAULT_OPTIONS`, overwriting it with any options that are provided by the client. (This was fixed in ProbeNode.)

(2) On line 19, DEFAULT_OPTIONS is made available to clients, where it can be accidentally modified. (This is still a problem in ProbeNode.)

Here's a fixed version of the above pattern, which clones DEFAULT_OPTIONS.  DEFAULT_OPTIONS  remains private, it's not mutated, and the client has no opportunity to modify it.
 
```js
1 define( function( require ) {
2
3   var DEFAULT_OPTIONS = {…};
4
5   function ProbeNode( options ) {
6     options = _.extend( _.clone( DEFAULT_OPTIONS ), options );
7   }
8
9  return inherit( Node, ProbeNode, {}, {
10    getDefaultOptions: function() { return_.clone( DEFAULT_OPTIONS ); }
11  } );
12
13 } );
```

@samreid @jbphet @jonathanolson @aaronsamuel137 @jessegreenberg Thoughts? Other patterns?

**Comment by samreid** [comment]
Does

```js
_.extend( {}, DEFAULT_OPTIONS, options )
```
 do the same thing as 

```js
_.extend( _.clone( DEFAULT_OPTIONS ), options )`
```

**Comment by samreid** [comment]
Should we use freeze rather than clone?  What about depth issues? (I think clone and freeze are shallow).

**Comment by pixelzoom** [comment]
> Does ... do the same thing as ...

Same result.

**Comment by pixelzoom** [comment]
> (I think clone and freeze are shallow).

The use _.cloneDeep when necessary.

**Comment by pixelzoom** [comment]
> (I think clone and freeze are shallow).

Use _.cloneDeep when necessary.

JavaScript freeze is shallow; values that are objects can still be modified, unless they are also frozen.

**Comment by pixelzoom** [comment]
ProbeNode.js:
> DEFAULT_OPTIONS: DEFAULT_OPTIONS

Panel.js:
> defaultOptions: defaultOptions

Which naming convention should we use?

**Comment by pixelzoom** [comment]
9/29/15 dev meeting:
• prefer `_.extend( {}, DEFAULT_OPTIONS, options )`
• `assert && DEFAULT_OPTIONS.freeze()`
• use uppercase `DEFAULT_OPTIONS`, since it's a constant
