### ISSUE TITLE
ProbeNode exposes DEFAULT_OPTIONS to modification

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#191]
See https://github.com/phetsims/scenery-phet/issues/190 for a more general discussion of exposing default options.

Here's the code in question: 

```js
// statics
    {

      // @public {read-only}, make the defaults publicly available to clients in case they need to make
      // customizations, such as 0.9 x the default width
      DEFAULT_OPTIONS: DEFAULT_OPTIONS,
```

This makes the DEFAULT_OPTIONS instance available to clients, where it can (and will) be accidentally modified.  Recommended to change to:

```js
getDefaultOptions: function() { return _.clone( DEFAULT_OPTIONS ); }
```

**Comment by pixelzoom** [comment]
In #190, we decided to expose DEFAULT_OPTIONS, but freeze it conditionally to prevent modification during development.

**Comment by pixelzoom** [comment]
Assigned to @samreid for review.

**Comment by samreid** [comment]
Looks good, thanks, closing.
