### ISSUE TITLE
ProbeNode: improve shading

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#192]
See https://github.com/phetsims/beers-law-lab/issues/111#issuecomment-144111525

**Comment by samreid** [comment]
Worked with @jonathanolson on this a bit, his recommendation is to create shapes for discrete segments with alpha varying between 0 and 1 so that the background shading shows through.

For instance, something like this:

```js
    var bevelLength = 5.5;
    var arcShape = new Shape().ellipticalArc( 0, 0, radius - bevelLength / 2, radius - bevelLength / 2, 0, Math.PI * arcExtent, Math.PI * (1 - arcExtent), false );
    var distance = 7.5;
    var arcPath = new Path( arcShape, {
      stroke: new RadialGradient( 0, 0, radius - bevelLength / 2 - distance / 2, 0, 0, radius - bevelLength / 2 + distance / 2 )
      //.addColorStop( 0, 'blue' )
      //.addColorStop( 1, 'red' ),
        .addColorStop( 0, color.withAlpha( 1 ) )
        .addColorStop( 0.3, color.withAlpha( 0.25 ) )
        .addColorStop( 0.6, color.withAlpha( 0 ) )
        .addColorStop( 1, color.withAlpha( 1 ) ),
      lineWidth: distance
    } );
```

**Comment by samreid** [comment]
Here's a snapshot of the BLL image which we would like to emulate as closely as possible: 

![image](https://cloud.githubusercontent.com/assets/679486/10655394/72e06f2a-7831-11e5-923b-8fa6117084d8.png)

**Comment by samreid** [comment]
Here's my starting point:

![image](https://cloud.githubusercontent.com/assets/679486/10655789/3df03346-7835-11e5-95ea-920351ee8f31.png)

**Comment by samreid** [comment]
Here's after some tweaking gradients and strokes:

![image](https://cloud.githubusercontent.com/assets/679486/10655987/74f66c96-7837-11e5-9378-8f1a2f6235cc.png)

This seems somewhat better, but it seems like I need to round that white highlight stroke in the top region.

**Comment by samreid** [comment]
I rounded out that topleft shading:

![image](https://cloud.githubusercontent.com/assets/679486/10656175/618ca308-7839-11e5-94bc-a064ee602ed5.png)

@ariel-phet or @pixelzoom does this look good enough?

**Comment by ariel-phet** [comment]
Looks good to me

**Comment by samreid** [comment]
Thanks @ariel-phet, I'll close the issue.  @pixelzoom please reopen the issue if you disagree or if there are other things to do here.

**Comment by pixelzoom** [comment]
Looks a tad too dark at the bottom to my eye, but ok with me.

**Comment by ariel-phet** [comment]
Ah...I was looking at the specular highlight, but I would agree a bit dark at the bottom

**Comment by ariel-phet** [comment]
@samreid - possible to keep the highlight as you have and make the bottom more like your "starting point" comment?

**Comment by samreid** [comment]
Sure, that should be easy to modify.  I'll leave this assigned to me at medium priority.

**Comment by samreid** [comment]
I reduced the shadowing at the bottom of the probe node, here's the latest snapshot:

![image](https://cloud.githubusercontent.com/assets/679486/10700486/3fa09716-797b-11e5-811d-e3ef69d87f51.png)

@pixelzoom what do you think?

**Comment by pixelzoom** [comment]
:+1:
