### ISSUE TITLE
Useless call?

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#193]
@jonathanolson ESList is reporting useless call for these cases:

```
/Users/samreid/github/dot/js/Permutation.js
  50:7  error  unnecessary ".call()"  no-useless-call

/Users/samreid/github/scenery/js/display/PixiSelfDrawable.js
  43:9  error  unnecessary ".call()"  no-useless-call

/Users/samreid/github/scenery/js/display/SVGSelfDrawable.js
   65:9   error  unnecessary ".call()"  no-useless-call
  147:30  error  unnecessary ".call()"  no-useless-call
  163:30  error  unnecessary ".call()"  no-useless-call
```

Can we fix them or is there a reason they need to be that way?

**Comment by pixelzoom** [comment]
Why is this in scenery-phet? The calls are in scenery and dot.

**Comment by samreid** [comment]
Looks like a manual error, this should have been created in scenery repo.

**Comment by jonathanolson** [comment]
Fixed the mentioned issues.

**Comment by zepumph** [comment]
While working on https://github.com/phetsims/chipper/issues/794, I found a TODO marked for this issue, and a commented out lint rule. It looks like back in 2015 it was worth changing these usages, and when I added the lint rule back in, there were  only 5 issues, so I fixed them, @jonathanolson please review these and close if all seems good, and keeping the lint rule is best.

**Comment by pixelzoom** [comment]
Assingned to @jonathanolson for review for 27 months. Raising priority to high.

**Comment by jonathanolson** [comment]
@zepumph, the commit https://github.com/phetsims/phet-io-wrappers/commit/90d9f607abb5b67438a73fb1dec452c860d638b1 looks buggy (the array of parameters should have been removed into a parameter list). I can't find this code in master, does it still exist?

**Comment by jonathanolson** [comment]
The others look good!

**Comment by zepumph** [comment]
Agreed. It isn't there anymore. Closing
