### ISSUE TITLE
MovableDragHandler should accept forwarded events

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#195]
During today's discussion of dragging items from the toolbox, a suggestion from @jbphet was to forward input events from one listener to another.  I would like to explore this strategy in Bending Light.  Bending Light uses MovableDragHandler (which has logic for keeping nodes in bounds, dragging relatively to the drag point, and listeners that bump out nodes if they are dropped behind a control panel).  However, MovableDragHandler encapsulates its start/drag/end logic and there is no point of access to forward events to them.

One straightforward way to make event forwarding possible for MovableDragHandler would be to store the start/drag/end methods (privately) and provide methods for forwarding to them.

While it is unfortunate to change a widely used scenery-phet file during redeployments, I believe the refactor will be straightforward, and important in proceeding with this strategy for the publication of bending light.

**Comment by samreid** [comment]
I've moved the start/drag/end methods to `@private` attributes and added methods for forwarding to them.  It works like a charm in Bending Light for the protractor and I tested Concentration, which uses MovableDragHandler and did not observe any problems.  I chose property & method names that are currently unique and therefore will not collide with anything else, so this should be a safe refactor and not interfere with S2015R.

Since this is a widely used scenery-phet class, these changes should be reviewed.  @pixelzoom may wish to be apprised of these proposed changes but perhaps @jbphet would be a good reviewer since he has experience with the event forwarding pattern.  (Or I'm happy for >=2 reviews).

This is working well for the protractor in bending light so I wanted to get to a good commit point.  I'll work on using this for the other (composite) probe types next and let you know if any modifications are necessary, or if this pattern will work for those cases.

Lint is passing and I'll commit shortly.  Also, IntroView.js is pretty messy now and will be undergoing surgery as I work on the listeners for the other probes, so I'll comment the usage site here for review:

```js
    // Add an input listener to the toolbox icon for the protractor, which forwards events to the MovableDragHander
    // for the node in the play area
    protractorNodeIcon.addInputListener( new SimpleDragHandler( {
      start: function( event ) {
        
        // Show the protractor in the play area and hide the icon
        protractorInPlayAreaProperty.value = true;
        
        // Center the protractor on the pointer
        protractorLocationProperty.value = protractorNode.globalToParentPoint( event.pointer.point );

        // Forward the start event to the drag handler
        protractorNodeListener.forwardStartEvent( event );
      },
      drag: function( event ) {

        // Forward the drag event to the drag handler
        protractorNodeListener.forwardDragEvent( event );
      },
      end: function( event ) {

        // Forward the end event to the drag handler
        protractorNodeListener.forwardEndEvent( event );
      }
    } ) );
```

**Comment by samreid** [comment]
@jbphet @pixelzoom should I label this issue as S2015R since it will appear in many of those republished sims?

**Comment by samreid** [comment]
Also to the reviewer:  I'm not too happy with the method names:
forwardStartEvent
forwardDragEvent
forwardEndEvent

It sounds somewhat like MovableDragHandler would be forwarding the events instead of receiving a forwarded event?  Please suggest a better name if you can think of one.

**Comment by pixelzoom** [comment]
>  a suggestion from @jbphet was to forward input events from one listener to another.

I don't recall that being the suggestion (though I may have missed it).  I recall a discussion about the toolbox icon handling the movement of the newly-created tool after the initial click on the toolbox icon. Then subsequent interactions with the tool would occur directly with its drag handler.  That's the approach that was used in Glaciers (Java) and it worked well.  So I'm skeptical that this new functionality is necessary.

**Comment by samreid** [comment]
@pixelzoom can we discuss over voice at your convenience?

**Comment by samreid** [comment]
@pixelzoom & I discussed this implementation, and it seems like forwarding events to MovableDragHandler will work well.  We discussed an alternate approach (I think it is like the approach in Glaciers) where a different instance of the same class of listener would be added to the tool icon and to the play area icon, but it was unclear how this would handle nodes with >=1 sub-elements.

@pixelzoom please chime in if there are critical details I omitted here.

**Comment by pixelzoom** [comment]
I'm on board. :+1:

**Comment by samreid** [comment]
@jbphet this should still be reviewed and discussed, at your convenience.

**Comment by pixelzoom** [comment]
I'm considering using this feature, but I see that it hasn't been reviewed.  @jbphet when do you think this might be closed?

**Comment by jbphet** [comment]
I'll look at it today and will try incorporating into Expression Exchange as a test case.

**Comment by jbphet** [comment]
I've reviewed this, and the idea seems sound and the changes look good.  Here are a few minor notes:

There is a comment in the constructor documentation that says, 
```
   * @param {Property.<Vector2>} locationProperty - in model coordinate frame
   *        OR {get:...,set:...}, used in Bending Light's PrismNode as somewhat of a hack.
```
I don't like the sound of that - we shouldn't mention specific simulation use cases in the documentation if we don't think they should be fully supported.  Is this comment still true? Can the documentation be updated or can the Bending Light code be improved based on these new changes?

I see what you mean about the names of the handlers for the forwarded events.  How about something like ```handleForwardedStartEvent``` and so forth?  More verbose, I know, but possibly clearer.

@samreid should be added to list of authors

I also made some minor documentation changes.

Before assigning back to @samreid I'll try to integrate it into Expression Exchange, which is a newer simulation that could make use of this approach.

**Comment by jbphet** [comment]
Integration into Expression Exchange isn't going to be as quick as I'd initially thought because the creation pattern currently used in that sim doesn't have immediate access to the node that is created by the view, so I'll need to figure out how best to handle this.  I'll go ahead and turn this back over to @samreid to address the notes above and so that @pixelzoom can start looking at using it, and will work on the integration with Expression Exchange later.

**Comment by samreid** [comment]
@jbphet thanks for your review.  It looks like all of the Bending Light cases are now using Property, so I've removed that disclaimer.  I renamed the methods as you recommended, and it seems good.  I added myself to the list of authors and updated the copyright date.  Reassigning to confirm changes and see if there is anything else to do here.

**Comment by jbphet** [comment]
Changes look good, closing.

**Comment by pixelzoom** [comment]
Reopening. 

There's a problem here.  Each call to SimpleDragHandler start/drag/end gets both an Event and a Trail.  This API propagates only the Event, and ignores the Trail.  That may have been sufficient so far, but it's not a general solution for forwarding drag information.  

@samreid @jbphet @jonathanolson Any reason why it's acceptable to ignore the trail?

**Comment by pixelzoom** [comment]
This is also masked at use sites in bending-light and circuit-construction-kit.  For example, in bending-light.ToolIconListener:

```js
SimpleDragHandler.call( this, {
      start: function( event ) {
        init( event );

        // Forward the event to the components
        for ( var i = 0; i < components.length; i++ ) {
          components[ i ].handleForwardedStartEvent( event );
        }
      },
      drag: function( event ) {

        // Forward the event to the components
        for ( var i = 0; i < components.length; i++ ) {
          components[ i ].handleForwardedDragEvent( event );
        }
      },
      end: function( event ) {

        // Forward the event to the components
        for ( var i = 0; i < components.length; i++ ) {
          components[ i ].handleForwardedEndEvent( event );
        }
      }
    } );
```

PhET convention is to include unused parameters in function signatures.  The start/drag/end functions above all commit the `trail` parameter.

**Comment by samreid** [comment]
For completeness we should probably pass the trails through.

**Comment by samreid** [comment]
> The start/drag/end functions above all commit the trail parameter.

I presume you meant omit?

**Comment by pixelzoom** [comment]
Yes, thank, edited.

**Comment by pixelzoom** [comment]
Two observations:

(1) Forwarding the trail might be problematic, since some other node/hander will be handling the event, and it will have a different trail. 

(2) I don't think the current implementation is the best way to add forwarding. All these "handler" functions currently do is call the functions that were provided as options to TandemDragHandler (and its supertype SimpleDragHandler).  If these options were saved and made accessible as public fields in SimpleDragHandler, then there'd be no reason to add these handler functions. And forwarding could be done for all  SimpleDragHandlers, not just MovableDragHandler. For example, in bending-light.ToolIconListener, `components[ i ].handleForwardedStartEvent( event )` would become `components[ i ].start( event, trail )`.

**Comment by pixelzoom** [comment]
Regarding (2)... In function-builder, I'm not using MovableDragHandler, I have my own subtype of SimpleDragHandler.  And I therefore have no way to use this "forwarding" feature.

**Comment by samreid** [comment]
> All these "handle" functions currently do is call the functions that were provided as options to TandemDragHandler (and its supertype SimpleDragHandler).

Yes, this is correct.  I'm interested in pursuing the "store the start/drag/end" functions in SimpleDragHandler if we can do that in a way that is unlikely to cause name collisions.

**Comment by samreid** [comment]
@jonathanolson what are your thoughts about this?

**Comment by jonathanolson** [comment]
In Charges and Fields, it seemed simple enough to have one input listener on the object in the panel (just the down event) that would trigger creation of a draggable object, then call ```startDrag( event )``` on the drag listener for that (with no need to pass a trail). Is that the type of forwarding you were talking about?

Seems beneficial if we could discuss on a call sometime. And my long-term recommendation is "I should write something better than SimpleDragHandler".

**Comment by samreid** [comment]
@jonathanolson and I will discuss this offline.

**Comment by pixelzoom** [comment]
I'm no longer planning to use this feature in function-builder.

**Comment by samreid** [comment]
@jonathanolson and I looked into the way Charges and Fields just calls startDrag(event) on the play area drag listener (which adds a listener to the pointer, in the usual SimpleDragHandler way), and it seems like a good pattern.  I will try this pattern for Circuit Construction Kit, when I am working on the toolbox listeners.  @jonathanolson also looked at ToolIconListener and other details from Bending Light toolbox icons and said that the way it is implemented is OK for now, no need to change due to bugs or maintainability issues, but good to look into the startDrag(event) forward for future, instead of the forward-each-event strategy used in Bending Light.

**Comment by jonathanolson** [comment]
@samreid, anything I should be handling here, or is the recommended input approach working well enough that we don't need changes here?

**Comment by samreid** [comment]
@jonathanolson can I call startDrag(event) on two listeners with the same event?  If so, we may be able to use that strategy and get rid of the MovableDragHandler forwarding features (which are admittedly awkward).

**Comment by jonathanolson** [comment]
> can I call startDrag(event) on two listeners with the same event?

Technically yes, but the first (SimpleDragHandler) listener would presumably mark the pointer as "dragging with this listener" and the second listener wouldn't start the drag.

**Comment by samreid** [comment]
Generally, I'd like to move to patterns where MovableDragHandler doesn't need forwarded events, but I don't have time to work on this now, unassigning.

**Comment by ariel-phet** [comment]
Issue is stale...closing. A new issue will be made if we need this later.
