### ISSUE TITLE
problem with specular highlight on ProbeNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#196]
Discovered while integrating ProbeNode into ph-scale (https://github.com/phetsims/ph-scale/issues/61).

There's a problem with the lightAngle option in ProbeNode.  It seems to assume that the specular highlight is applied to some part of the rounded section of the probe, and that's definitely not the case. 

Here's an example, from ph-scale.MacroPHMeterNode, line 245:

```js
    ProbeNode.call( thisNode, {
      sensorType: ProbeNode.crosshairs( {
        intersectionRadius: 6
      } ),
      radius: 34,
      innerRadius: 26,
      handleWidth: 30,
      handleHeight: 25,
      handleCornerRadius: 12,
      lightAngle: 0.85 * Math.PI,
      color: 'rgb( 35, 129, 0 )',
      rotation: Math.PI / 2,
      cursor: 'pointer'
    } );
```

Here's what it looks like if you scale the probe up up by 2x (so that you can see it better):

![screenshot_37](https://cloud.githubusercontent.com/assets/3046552/10770338/601cf632-7cb0-11e5-95dc-bb7004fa38fc.png)

Note how the highlight looks mangled where the probe handle starts. Looks like the specular highlight has a problem if the light shines on the handle.

**Comment by pixelzoom** [comment]
This is a blocking issue for ph-scale, https://github.com/phetsims/ph-scale/issues/61.

**Comment by pixelzoom** [comment]
Recommended to add a rotation control to the ProbeNode demo in scenery-phet, so that this can be properly tested.

**Comment by pixelzoom** [comment]
I've added a rotation control to the ProbeNode demo in scenery-phet.

**Comment by pixelzoom** [comment]
I guess the rotation control in the ProbeNode demo wasn't actually necessary, since the problem can be easily seen using the lightAngle control only.  Some examples:

lightAngle = 2.45

![screenshot_44](https://cloud.githubusercontent.com/assets/3046552/10830143/af02a97e-7e43-11e5-9df6-07d60f8a6b47.png)


lightAngle = 1.45

![screenshot_45](https://cloud.githubusercontent.com/assets/3046552/10830154/bfb16486-7e43-11e5-8eda-f38c3e307215.png)

**Comment by pixelzoom** [comment]
I removed the rotation control from the ProbeNode demo in scenery-phet.

**Comment by samreid** [comment]
The specular highlight is being simulated with linear gradients, which becomes tricky around the handle.  Still, by updating the geometry a bit, I have got it to look like this:

![image](https://cloud.githubusercontent.com/assets/679486/10896765/53dde2d2-8179-11e5-8c6e-7a109f3c31b9.png)

This is flickery as a function of angle, and may only work well for predetermined angles.  But this seems overall better behavior than the previous version, so I'll commit shortly.

**Comment by samreid** [comment]
I committed the fix above, which uses better geometry to create the gradients for the highlights.  My recommendation is to use an angle where the rendering looks good such as 1.9*pi.  Hopefully this is sufficient.  If not, then we wish to discuss ways to create the specular highlight other than with the LinearGradient.

**Comment by samreid** [comment]
It looks like the highlight angles are reversed in the above commit--the BLL probe is looking odd.  I'll reverse them shortly.

**Comment by samreid** [comment]
After the above commit, the BLL probe is looking good again:

![image](https://cloud.githubusercontent.com/assets/679486/10896956/76f28c72-817a-11e5-90fe-5f7da58101fe.png)

So the recommended angle for the sideways probe would now be 0.9*pi or thereabouts.  @pixelzoom can you take a look at using that number or thereabouts?

**Comment by pixelzoom** [comment]
I'm confused... In https://github.com/phetsims/scenery-phet/issues/196#issuecomment-153185420, @samreid says to use 0.9*pi. But I'm using 1.25*pi and it still looks like the screenshot he provided. 

The problem was also not with the beers-law-lab.ATDetectorProbe, the problem was with ph-scale.MacroPHMeterNode due to its orientation.  It looks better, see screenshot:
![screenshot_52](https://cloud.githubusercontent.com/assets/3046552/10982150/edf1469c-83c8-11e5-9bcd-39d6b4f9e778.png)

But the general problem remains, as demonstrated very clearly in scenery-phet demo. The highlight looks messed up if it's on the handle. For example with lightAngle:0.70*pi, it looks like this:
![screenshot_53](https://cloud.githubusercontent.com/assets/3046552/10982208/3476c38a-83c9-11e5-8311-65190de8fdf6.png)

**Comment by samreid** [comment]
Here's what I see in the scenery-phet test:

0.9pi
![image](https://cloud.githubusercontent.com/assets/679486/10983703/6242340e-83d1-11e5-930c-2dace9de49ae.png)

1.25pi
![image](https://cloud.githubusercontent.com/assets/679486/10983713/73fa9682-83d1-11e5-895d-18e60ac107cc.png)

> The highlight looks messed up if it's on the handle.

Yes, here are my comments about the handle from above:

1. The specular highlight is being simulated with linear gradients, which becomes tricky around the handle. 
2. My recommendation is to use an angle where the rendering looks good [...]
3. Hopefully this is sufficient. If not, then we wish to discuss ways to create the specular highlight other than with the LinearGradient.

Are you saying this is insufficient and hence we should discuss ways to create the specular highlight other than with Linear Gradient?

**Comment by pixelzoom** [comment]
Ah, misread. You were recommending 0.9 for scale.MacroPHMeterNode ("the sideways probe") but showing a screenshot of beers-law-lab.ATDetectorProbe. Got it.

> 1. The specular highlight is being simulated with linear gradients, which becomes tricky around the handle.
> 2. My recommendation is to use an angle where the rendering looks good [...]

If we have a probe where the handle points up, and PhET lighting convention is upper-left, then how can we satisfy #2?  I don't see how we can say "just don't put the probe in an orientation were the gradient looks bad."  This is supposed to be a general solution for probes.  So it seems like the highlight needs to look good regardless of orientation or lightAngle.

**Comment by samreid** [comment]
Here is 0.15pi, wouldn't that work for when the handle is pointing up?

![image](https://cloud.githubusercontent.com/assets/679486/10984286/94162b80-83d5-11e5-9e71-127f6677dd05.png)

**Comment by pixelzoom** [comment]
Looks lousy at the bottom center of the handle.  But that's not the point. You appear to be advocating that we should limit the possible usable combinations of orientations (rotations) and lightAngle, as a workaround for an implementation deficiency. I doubt that designers will be aware of that limitation, and I don't think they should need to be. So I'm advocating that we fix it now.

**Comment by samreid** [comment]
I'm not opposed to improving the specular highlight on this component--I think it is a good idea.  @jonathanolson and I spent a little bit of time on this a few weeks ago and were looking into ideas like separate gradients for each subpath in the shape.  It was unclear how well we could get the gradients to line up and eventually I settled on the approach above.  What I would recommend first is to make sure the above approach (linear gradients) is working as it should--make sure the bounding box that determines the geometry of the linear gradients is at the correct positioning.  If that is indeed correct and linear gradients are insufficient here, then I'll likely need help to proceed.

If the above seems too expensive or tricky, then we may wish to discuss limiting the light angles to be "leftTop", "rightTop", etc. in the API though this may rule out putting the probes at an angle other than 0, 90, 180, 270.

I'll leave this assigned to me for now to make sure the geometry of the linear gradients is correct.  If it is, then we should discuss what option above to take next.

**Comment by ariel-phet** [comment]
@samreid I would chime in here that in the long run we don't want to limit ourselves to particular angles of the probe. 0, 90, 180, 270 may well work for any future use cases, but it *could* occur that we want a diagonal probe.

My recommendation would be to make sure things look good at those 4 angles, and future work can wait until a design case comes up (which it may never) that requires other angles.

**Comment by samreid** [comment]
Based on @ariel-phet's comment I'll remove the "High Priority" label, but leave assigned to myself to investigate whether the linear gradients are working as prescribed.

**Comment by samreid** [comment]
I determined that the specular highlight strategy is indeed incompatible with linear gradients.  But I have found another way to do the highlighting that doesn't suffer from this problem.  It doesn't exactly have the same "pop" the previous version did, but perhaps it is not too different and may be acceptable.  I'll put the code here rather than in a branch:

```js
// Copyright 2015, University of Colorado Boulder

/**
 * A physical-looking probe with a handle and a semicircular sensor region, used in simulations like Bending Light and
 * Beer's Law Lab to show how much light is being received. It is typically connected to a body with readouts with a
 * curved wire. The origin is in the center of the circular part of the sensor (which is not vertically symmetrical).
 *
 * This code was generalized from Bending Light, see https://github.com/phetsims/bending-light/issues/165
 *
 * @author Sam Reid (PhET Interactive Simulations)
 * @author Chandrashekar Bemagoni (Actual Concepts)
 * @author Chris Malley (PixelZoom, Inc.)
 */
define( function( require ) {
  'use strict';

  // modules
  var inherit = require( 'PHET_CORE/inherit' );
  var Node = require( 'SCENERY/nodes/Node' );
  var Shape = require( 'KITE/Shape' );
  var Path = require( 'SCENERY/nodes/Path' );
  var Vector2 = require( 'DOT/Vector2' );
  var LinearGradient = require( 'SCENERY/util/LinearGradient' );
  var RadialGradient = require( 'SCENERY/util/RadialGradient' );
  var Color = require( 'SCENERY/util/Color' );
  var Line = require( 'SCENERY/nodes/Line' );
  var Circle = require( 'SCENERY/nodes/Circle' );
  var EllipticalArc = require( 'KITE/segments/EllipticalArc' );
  var Ray2 = require( 'DOT/Ray2' );

  // Glass is one of the probe types, shows a shiny reflective interior in the central circle
  var glass = function( options ) {
    var GLASS_DEFAULTS = {
      centerColor: 'white',
      middleColor: '#E6F5FF', // light blue
      edgeColor: '#C2E7FF'    // slightly darker blue, like glass
    };
    options = _.extend( GLASS_DEFAULTS, options );
    return function( radius ) {
      return new Circle( radius, {
        fill: new RadialGradient( -radius * 0.15, -radius * 0.15, 0, -radius * 0.15, -radius * 0.20, radius * 0.60 )
          .addColorStop( 0, options.centerColor )
          .addColorStop( 0.4, options.middleColor ) // light blue
          .addColorStop( 1, options.edgeColor ) // slightly darker blue, like glass
      } );
    };
  };

  // Crosshairs can be shown in the central circle
  var crosshairs = function( options ) {
    var CROSSHAIRS_DEFAULTS = {
      stroke: 'black',
      lineWidth: 3,

      // The amount of blank space visible at the intersection of the 2 crosshairs lines
      intersectionRadius: 8
    };
    options = _.extend( CROSSHAIRS_DEFAULTS, options );
    return function( radius ) {

      var lineOptions = { stroke: options.stroke, lineWidth: options.lineWidth };
      return new Node( {
        children: [
          new Line( -radius, 0, -options.intersectionRadius, 0, lineOptions ),
          new Line( +radius, 0, +options.intersectionRadius, 0, lineOptions ),
          new Line( 0, -radius, 0, -options.intersectionRadius, lineOptions ),
          new Line( 0, +radius, 0, +options.intersectionRadius, lineOptions ) ]
      } );
    };
  };

  // constants
  var DEFAULT_OPTIONS = {
    radius: 50,
    innerRadius: 35,
    handleWidth: 50,
    handleHeight: 30,
    handleCornerRadius: 10,

    /**
     * in radians, the angle of the incoming light.  0 is from the right, PI/2 from the bottom, PI from the left, etc.
     * The default is from the upper-left.  Generally, it is difficult to know the global rotation of the ProbeNode
     * and automatically update the lightAngle when the global rotation changes, so this is up to the developer
     * to set properly.  The light in PhET simulations often comes from the top-left, so please set this value
     * accordingly depending on the context of how the probe is embedded in the simulation.
     */
    lightAngle: 1.35 * Math.PI,
    color: '#008541', // {Color|string} darkish green

    // The circular part of the ProbeNode is called the sensor, where it receives light or has crosshairs, etc.
    // or null for an empty region
    sensorTypeFunction: glass()
  };
  assert && Object.freeze( DEFAULT_OPTIONS );

  /**
   * Constructor for the ProbeNode
   * @param {Object} [options]
   * @constructor
   */
  function ProbeNode( options ) {

    options = _.extend( {}, DEFAULT_OPTIONS, options );

    var color = Color.toColor( options.color );

    // To improve readability
    var radius = options.radius;

    // the top of the handle, below the circle at the top of the sensor
    var handleBottom = radius + options.handleHeight;

    // The shape of the outer body, circular at top with a handle at the bottom
    var arcExtent = 0.8;
    var handleWidth = options.handleWidth;
    var innerRadius = Math.min( options.innerRadius, options.radius );
    var cornerRadius = options.handleCornerRadius;

    var neckCornerRadius = 10;

    // We must know where the elliptical arc begins, so create an explicit EllipticalArc for that
    // Note: This elliptical arc must match the ellipticalArc call below 
    var ellipticalArcStart = new EllipticalArc( new Vector2( 0, 0 ), radius, radius, 0, Math.PI * arcExtent, Math.PI * (1 - arcExtent), false ).start;

    var createShape = function() {
      return new Shape()

      // start in the bottom center
        .moveTo( 0, handleBottom )

        // Kite Shape automatically lineTo's to the first point of an arc, so no need to lineTo ourselves
        .arc( -handleWidth / 2 + cornerRadius, handleBottom - cornerRadius, cornerRadius, Math.PI / 2, Math.PI, false )
        .lineTo( -handleWidth / 2, radius + neckCornerRadius )
        .quadraticCurveTo( -handleWidth / 2, radius, ellipticalArcStart.x, ellipticalArcStart.y )

        // Top arc
        // Note: his elliptical arc must match the EllipticalArc above
        .ellipticalArc( 0, 0, radius, radius, 0, Math.PI * arcExtent, Math.PI * (1 - arcExtent), false )

        .quadraticCurveTo( handleWidth / 2, radius, +handleWidth / 2, radius + neckCornerRadius )
        .arc( handleWidth / 2 - cornerRadius, handleBottom - cornerRadius, cornerRadius, 0, Math.PI / 2, false )

        .lineTo( 0, handleBottom );
    };

    var sensorShape = createShape()
      .moveTo( innerRadius, 0 )
      .arc( 0, 0, innerRadius, Math.PI * 2, 0, true )
      .close();

    var outline = createShape().close();

    // The light angle is variable so that you can create a probe node that is pointing up or to the side
    var lightAngle = options.lightAngle;

    var center = sensorShape.bounds.center;
    var v1 = Vector2.createPolar( 1, lightAngle );
    var intersections = sensorShape.intersection( new Ray2( center, v1 ) );
    var gradientSource = intersections[ intersections.length - 1 ].point.plus( v1.timesScalar( 1 ) );

    var v2 = Vector2.createPolar( 1, lightAngle + Math.PI );
    var intersections2 = sensorShape.intersection( new Ray2( center, v2 ) );
    var gradientDestination = intersections2[ intersections2.length - 1 ].point.plus( v2.timesScalar( 1 ) );

    var outerShapePath = new Path( sensorShape, {
      stroke: new LinearGradient( gradientSource.x, gradientSource.y, gradientDestination.x, gradientDestination.y )
        .addColorStop( 0.0, color.colorUtilsBrightness( 0.7 ) ) // highlight
        .addColorStop( 1.0, color.colorUtilsBrightness( -0.5 ) ), // shadow
      fill: new LinearGradient( gradientSource.x, gradientSource.y, gradientDestination.x, gradientDestination.y )
        .addColorStop( 0.0, color.colorUtilsBrightness( +0.5 ) ) // highlight
        .addColorStop( 0.03, color.colorUtilsBrightness( +0.4 ) )
        .addColorStop( 0.07, color.colorUtilsBrightness( +0.4 ) )
        .addColorStop( 0.11, color.colorUtilsBrightness( +0.2 ) )
        .addColorStop( 0.3, color.colorUtilsBrightness( +0.0 ) )
        .addColorStop( 0.8, color.colorUtilsBrightness( -0.2 ) ) // shadows
        .addColorStop( 1.0, color.colorUtilsBrightness( -0.3 ) ),
      lineWidth: 2
    } );

    // the front flat "surface" of the sensor, makes it look 3d by putting a shiny glare on the top edge
    var innerPath = new Path( sensorShape, {
      fill: options.color,

      // y scale is an empirical function of handle height, to keep bevel at bottom of handle from changing size
      scale: new Vector2( 0.9, 0.93 + ( 0.01 * options.handleHeight / DEFAULT_OPTIONS.handleHeight ) ),
      centerX: outerShapePath.centerX,
      stroke: color.colorUtilsBrightness( +0.3 ).withAlpha( 0.5 ),
      lineWidth: 1.2,
      y: 2 // Shift it down a bit to make the face look a bit more 3d
    } );

    var children = [];

    if ( options.sensorTypeFunction ) {
      children.push( options.sensorTypeFunction( radius ) );
    }

    children.push(
      outerShapePath,
      innerPath
      //new Circle( 3, { center: gradientSource, fill: 'blue' } ),
      //new Circle( 3, { center: gradientDestination, fill: 'red' } )
    );

    Node.call( this, {
      children: children,
      mouseArea: outline,
      touchArea: outline
    } );

    this.mutate( options );
  }

  return inherit( Node, ProbeNode, {},

    // statics
    {

      // @public {read-only}, make the defaults publicly available to clients in case they need to make
      // customizations, such as 0.9 x the default width
      DEFAULT_OPTIONS: DEFAULT_OPTIONS,

      // Sensor types
      // @public 
      crosshairs: crosshairs,
      glass: glass
    } );
} );
```

and here's a movie of how it looks:
![probe](https://cloud.githubusercontent.com/assets/679486/11161779/e3636ee0-8a43-11e5-9d5e-854ad8c96304.gif)

Thoughts @ariel-phet or @pixelzoom ?

**Comment by pixelzoom** [comment]
Looks pretty nice to me. Could you publish a dev version of the scenery-phet demo, so that we can play with it?

**Comment by samreid** [comment]
In attempt to avoid the overhead of a branch (which I perceive as (a) create the branch (b) create an issue for the branch (c) commit the changes to the branch (d) publish from the branch (e) delete the remote branch (f) delete the local branch (g) close the branch issue), I have pasted the code into this comment https://github.com/phetsims/scenery-phet/issues/196#issuecomment-156618209 and commented "I'll put the code here rather than in a branch".  That being said, I do not know a non-hackish way to publish a dev version without having pushed the code to GitHub (unless it is ok to publish a dev version with SHAs that are uncommitted).

Can you copy/paste the code from the comment above and test locally?  Or let me know if there is a more streamlined/less hackish way I can publish a dev version for you.

If @pixelzoom thinks it looks OK then we could commit to master and create a dev version for @ariel-phet to review.

Or if you think a branch is warranted here, just let me know--wasn't sure what you had in mind exactly.

**Comment by jonathanolson** [comment]
I've made working-copy changes, built a sim and put it under spot's dev/olsonjb before. I don't have a problem with individual built sim files that aren't possible to produce, but I wouldn't want them put up as dev versions (in the main dev directories).

**Comment by pixelzoom** [comment]
Checking the change into master, build a dev version, revert master?

**Comment by samreid** [comment]
If we suspect that this new version solves the problem in the previous version and initial feedback is that it looks pretty nice, can I just leave the change in master instead of immediately reverting it?  Or are there imminent master-based redeploys that must use the old ProbeNode?

**Comment by pixelzoom** [comment]
Less time to just do it than discuss it.

http://www.colorado.edu/physics/phet/dev/html/scenery-phet/1.0.0-dev.13/scenery-phet_en.html?screens=3&component=ProbeNode

@ariel-phet please play with the "Light Angle" control and comment on whether this looks OK to you.

**Comment by samreid** [comment]
> On a Skype call with @ariel-phet, he wanted to know if the highlight was still "toned down" as we had done in 33f3162.

My intention during these changes was to match the visual style of the previous iteration but without the visual glitches.  I was able to get close to the same look but with a different implementation strategy.

> @samreid as a corollary I think adjusting the alpha of the highlight would be good to have generalized. 

In the new implementation, the shading is handled in this code:

```js
    var outerShapePath = new Path( sensorShape, {
      stroke: new LinearGradient( gradientSource.x, gradientSource.y, gradientDestination.x, gradientDestination.y )
        .addColorStop( 0.0, color.colorUtilsBrightness( 0.7 ) ) // highlight
        .addColorStop( 1.0, color.colorUtilsBrightness( -0.5 ) ), // shadow
      fill: new LinearGradient( gradientSource.x, gradientSource.y, gradientDestination.x, gradientDestination.y )
        .addColorStop( 0.0, color.colorUtilsBrightness( +0.5 ) ) // highlight
        .addColorStop( 0.03, color.colorUtilsBrightness( +0.4 ) )
        .addColorStop( 0.07, color.colorUtilsBrightness( +0.4 ) )
        .addColorStop( 0.11, color.colorUtilsBrightness( +0.2 ) )
        .addColorStop( 0.3, color.colorUtilsBrightness( +0.0 ) )
        .addColorStop( 0.8, color.colorUtilsBrightness( -0.2 ) ) // shadows
        .addColorStop( 1.0, color.colorUtilsBrightness( -0.3 ) ),
      lineWidth: 2
    } );
```

The highlights are now handled completely with colorUtilsBrightness and no longer using alpha.  We could introduce some flexibility to how the colorUtilsBrightness factors are selected.  In my opinion, the primary options are:

(a) add a background color picker to the scenery-phet test and try to introduce a ProbeNode option that allows tweaking of the colorUtilsBrightness factors (or some other way of modifying the color stops), and try to come up with options that make it possible for the shading to look good on a wide variety of combinations of probe color + background color

(b) purposefully ignore the problem for now and work on generalizing the highlights the first time we come to a situation where the probe color + background color yields a combination where the default highlighting doesn't look good.

In my opinion (a) is a daunting problem, if we we set out to explore a 6-dimensional (r1,g1,b1,r2,g2,b2) space and try to introduce options that look good throughout that space.  We could cut down the problem somewhat by picking likely probe node color + background color combinations.  Or we can just wait until they come up in practice.

In either case, should we commit the proposed change above, since it resolves the visual glitch as a function of angle?

**Comment by ariel-phet** [comment]
@samreid go ahead an commit the proposed change, we can see it in the sim itself. My guess is that it will be fine.

**Comment by samreid** [comment]
After the change, here is how it looks in the sim:

![image](https://cloud.githubusercontent.com/assets/679486/11583364/26b0a3f2-9a16-11e5-94c0-067e6b73daec.png)

Committing shortly...

**Comment by samreid** [comment]
Committed above, @ariel-phet @pixelzoom where do you want to go next?  Let me know if you want me to create a dev version.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/scenery-phet/issues/196#issuecomment-161890131 @samreid wrote:
> After the change, here is how it looks in the sim:

Clearly not pH Scale (unless you changed the background color), which has been "the sim" discussed so far. Which sim is this?

**Comment by samreid** [comment]
I put the probe in front of a solution.

**Comment by ariel-phet** [comment]
@samreid yes please publish a dev version.

**Comment by samreid** [comment]
Published here: http://www.colorado.edu/physics/phet/dev/html/ph-scale/1.3.0-dev.2/ph-scale_en.html

**Comment by ariel-phet** [comment]
Ugh...I hate to say this, but when I compare to the published sim, this just looks "off"...especially when I put the probe in a dark solution (like blood). The new probe just has way too much white in the highlight (why I was hoping we could adjust the alpha), and there also appears to be a slight highlight on the inner left radius, which seems odd and inconsistent.

![ph](https://cloud.githubusercontent.com/assets/4051174/11632275/93b877f4-9cc3-11e5-90c8-01e71b163d91.PNG)
![ph-dev](https://cloud.githubusercontent.com/assets/4051174/11632276/93dcf1ce-9cc3-11e5-930f-bf3a4ef098b0.PNG)

**Comment by ariel-phet** [comment]
I think the basic message is that the specular highlight really should be subtle, the current implementation is far too "shiny".

**Comment by samreid** [comment]
Good discovery @ariel-phet, it seems the probe node was optimized against a white background.  It seems like the edge of the probe should be more gray, like the image.  I'll take a look.

**Comment by samreid** [comment]
@pixelzoom commented in https://github.com/phetsims/build-an-atom/issues/110#issuecomment-162576942

The highlight was toned down in https://github.com/phetsims/scenery-phet/commit/33f3162822238368ddac713bf7d4c6c7bcddee86 by increasing the transparency:

```
-        .addColorStop( 0.05, new Color( 'white' ).withAlpha( 0.8 ) ) // light
+        .addColorStop( 0.05, new Color( 'white' ).withAlpha( 0.5 ) ) // light
```

Looks like this change may not have been incorporated when the overall gradient approach was changed.

**Comment by samreid** [comment]
I changed the first stroke color stop (line 168) to 'gray' and now it looks like this (against the blood solution):

![image](https://cloud.githubusercontent.com/assets/679486/11657576/ef18443c-9d7a-11e5-97d0-e677b0e89396.png)

And like this against white:
![image](https://cloud.githubusercontent.com/assets/679486/11657588/06b69b5c-9d7b-11e5-905b-b8418261b555.png)

Screenshots seem OK?  Shall I publish a new dev version?

**Comment by pixelzoom** [comment]
Gray won't necessarily look great on all probe colors. Any reason why the stroke can't be white with transparency, so that the color of the probe is mixed into the highlight?

**Comment by samreid** [comment]
I believe the stroke extends beyond the fill of the shape, so with transparency, that part of the shape would look translucent.  To solve that: we could add another solid stroke layer in back, then transparency in front?  May be good to collaborate on with 2 pairs of eyes.  I'll flag for discussion in developer meeting to see if @pixelzoom wants to look at this with me afterwards.

**Comment by pixelzoom** [comment]
12/8/15 dev meeting - @samreid and I will pair on this when I'm feeling better.

**Comment by pixelzoom** [comment]
I've been feeling better for quite awhile. Now all I need is some time.

**Comment by pixelzoom** [comment]
I was going to suggest investigating whether we could add support to scenery for stroking "inside" and "outside".  But the advertising banner at http://www.w3schools.com/cssref/css3_pr_outline-offset.asp seems to be offering me advice:

![screenshot_107](https://cloud.githubusercontent.com/assets/3046552/12328662/9d4926e4-ba99-11e5-9f03-b08a7c357130.png)

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/scenery-phet/issues/196#issuecomment-162943771, @samreid suggested:
> we could add another solid stroke layer in back, then transparency in front?

That sounds like it would work. Do you think we should compensate for the extra "size" that this would add?

**Comment by jonathanolson** [comment]
Using a smaller stroke in front and a thicker stroke in back is probably the fastest way, depending on what types of curves are used.

You can also create offset-shapes (dilated/eroded) and stroke those. If an elliptic/quadratic/cubic segment is offset, it is discretized (converted to a lot of line segments), and that might potentially hurt performance.

**Comment by samreid** [comment]
Rather than adding another solid layer in the back, which would need to be matched properly to the front transparent layer to look right, I tried just toning down the stroke highlight/shadows.  Originally went from 0.7 to -0.5.  Taking this to 0.2 to -0.2, it looks like this against blood:

![image](https://cloud.githubusercontent.com/assets/679486/12774451/4712c91a-ca02-11e5-8355-b47a2deed8c3.png)

And like this against white:

![image](https://cloud.githubusercontent.com/assets/679486/12774457/51948f18-ca02-11e5-82a5-b7c5a0cf30c4.png)

It seems like this is the desired effect since it is using the base color of the probe (just not lightening and darkening it so much).

The changed code would be 

```js
    var outerShapePath = new Path( sensorShape, {
      stroke: new LinearGradient( gradientSource.x, gradientSource.y, gradientDestination.x, gradientDestination.y )
        .addColorStop( 0.0, color.colorUtilsBrightness( 0.2 ) ) // highlight
        .addColorStop( 1.0, color.colorUtilsBrightness( -0.2 ) ), // shadow
```

@pixelzoom and/or @ariel-phet can you take a look and advise?

**Comment by ariel-phet** [comment]
@samreid that looks good in the screenshots, but would be best to look at as a dev version to see in context. However, we just made a bunch of changes to concentration/BLL, I would want to make sure this has very little chance of mucking anything up if we try it out in a dev version.

**Comment by pixelzoom** [comment]
Let's visit this sometime next week, after the feature requests to the "Concentration" screen have been delivered to the customer.

**Comment by samreid** [comment]
> I would want to make sure this has very little chance of mucking anything up if we try it out in a dev version.

There are a few risk-free ways we can proceed, one possibility would be if @ariel-phet has a some ~10 minutes or so:
1. Navigate to scenery-phet/js/ProbeNode.js in your working copy
2. On line 168, change 0.7 to 0.2
3. On line 169, change -0.5 to -0.2
4. Test in Beer's Law Lab, and Ph Scale and Ph Scale basics
5. Revert changes when done

This also has the advantage that if +/-0.2 is too dark/bright you could tinker with the values.  @ariel-phet are you interested in looking into it like this?

**Comment by ariel-phet** [comment]
@samreid @pixelzoom can we publish a dev version?

**Comment by samreid** [comment]
I can do this.

**Comment by samreid** [comment]
I committed above but realized I have many working copy changes in several repos that I'm not ready to commit yet, so @pixelzoom please feel free to publish or I'll do it once my working copy is clean.  Alternatively @ariel-phet could pull the change above and test locally (or using phet-test).

**Comment by ariel-phet** [comment]
happy to pull the change

**Comment by pixelzoom** [comment]
@ariel-phet Not sure which dev version you had in mind.  But it's worth reviewing in ph-scale, beers-law-lab, and scenery-phet (Components screen).  Looks nice to me.

**Comment by ariel-phet** [comment]
@pixelzoom will check all three

**Comment by ariel-phet** [comment]
All looking good to me. Feel free to close if you feel the work is done @samreid

**Comment by samreid** [comment]
Thanks for your help improving the look of this component @ariel-phet and @pixelzoom, closing.
