### ISSUE TITLE
API problem with BoundedDragHandler

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#197]
@samreid did an initial checkin of BoundedDragHandler on 9/15/15, with commit message indicating that it's used by ToolListener.  It's constructor signature is:

`function BoundedDragHandler( boundsProperty, options ) {`

... but `boundsProperty` is unused.

It also does this:

`this._dragBounds = options.dragBounds.copy(); // @private`

... but there is no default value for options.dragBounds.

So apparently the constructor arg is ignored, the bounds must be passed via options, and there is no default for the bounds.  There is also nothing in this file that indicates that this is a work in progress.

This API should be fixed.

**Comment by pixelzoom** [comment]
I would think that bounds are required for a BoundsDragHandler, and that there is no good default. So my recommendation is to pass the bounds via the constructor arg, not via options.

**Comment by samreid** [comment]
BoundedDragHandler deleted above, closing.
