### ISSUE TITLE
bad extension of options in FaceWithPointsNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#200]
Here's the problem:

```js
    this.options = _.extend( {
    ...
    }, options );
```

Now if someone accidentally uses `options` instead of `this.options` in the constructor, they may get the wrong value.  The preferred approach (in general) is:

```js
    options = _.extend( {
    ...
    }, options );
    this.options = options; // @private
```

**Comment by pixelzoom** [comment]
In this case, there are only 3 options that are needed in prototype functions, so it would be preferrable to save those 3 options only.  Ie:

```js
 options = _.extend( {
    ...
    }, options );
    this.showZeroPoints = options.showZeroPoints; // @private
    this.pointsAlignment = options.pointsAlignment; // @private
    this.spacing = options.spacing; // @private
```

**Comment by pixelzoom** [comment]
This anti pattern was introduced in @f6779a3. Assigning to @samreid  for review.

**Comment by pixelzoom** [comment]
This anti pattern was introduced in f6779a3. Assigning to @samreid for review.

**Comment by samreid** [comment]
I skimmed the code change and it seems good, I also tested FaceWithPointsNode as it appears in FractionMatcher.  Closing.
