### ISSUE TITLE
MovableDragHandler should handle alternate targets

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#203]
MovableDragHandler is currently hard-coded to us event.currentTarget as the coordinate frame of the drag.  However, this restriction makes it difficult or impossible to use MovableDragHandler on a component of a node.  I recommend to add a target option to the constructor which would override the event.currentTarget.

This will immediately be useful in solving https://github.com/phetsims/bending-light/issues/283

We should also discover how this proposal relates to the work done in #195, if at all.

**Comment by samreid** [comment]
In the above commit, I added support for alternate targetNode instances in MovableDragHandler.  @jonathanolson can you review & discuss this when time allows?

**Comment by jonathanolson** [comment]
Changes look fine, let me know if you'd like to discuss.

As noted previously, I hope to have a better drag-handling listener soon!

**Comment by samreid** [comment]
I'm OK to close, we can discuss if/when issues arise, thanks for taking a look.
