### ISSUE TITLE
Embedding mark handling for SubSupText/MultilineText

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/scenery-phet#207]
See https://github.com/phetsims/rosetta/issues/103 for the problem.

A description of the ideal solution is that if we need to split up a string like:
```js
\u202aH<sub>2</sub>O\u202c'
```
that a utility would handle the extraction of directional chunks, like:
```js
'\u202aH\u202c'
```
In this case, we'd want to handle general embedding mark levels, with an API like StringUtils.extractText( startIndex, endIndex ).

SubSupText currently uses jQuery parseHTML for parsing, so we may need to look into alternatives (or do something like turn paired embedding marks into ```<span dir="rtl">``` and ```</span>``` before parsing.

**Comment by jonathanolson** [comment]
Even if HTMLText had the correct bounds, SubSupText has improved visual appearance still, so we'd probably keep it anyways? (https://github.com/phetsims/scenery-phet/issues/29).

Since both SubSupText and MultiLineText are in scenery-phet, I'm planning on putting the associated string embedding-mark slice support into phetcommon's StringUtils.

**Comment by pixelzoom** [comment]
>  SubSupText has improved visual appearance still, so we'd probably keep it anyways? (#29).

Good point, SubSupText gives us "tweaking ability" that we're going to continue to need.

**Comment by jonathanolson** [comment]
I have working-copy solutions and improvements, but will need to wait until later tonight before committing (didn't have time for automated tests again).

**Comment by jonathanolson** [comment]
Support is complete, @pixelzoom, do you mind reviewing the SubSupText (and reviewing or referring review for StringUtils/MultiLineText?)

**Comment by pixelzoom** [comment]
Skimmed the related files, looks good to me, and well documented. Closing.
