### ISSUE TITLE
should MultiLineText scale all lines uniformly when using 'maxWidth' option?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#209]
Something is not quite right with how MultiLineText is handling the `maxWidth` option. It's scaling each line individually, which is probably not what we want. 

For example, in models-of-the-hydrogen-atom.BoxOfHydrogenNode, we have this string:

`"Box of\nHydrogen"`

And with `?stringTest=double`, it looks like this when `maxWidth` is set:

![screenshot_66](https://cloud.githubusercontent.com/assets/3046552/11228581/d63f8d84-8d4a-11e5-9e86-013022d1c72e.png)

Scaling each line differently looks very odd. Shouldn't all lines be scaled uniformly?

@jonathanolson @samreid @jbphet @jessegreenberg what do you think?

**Comment by pixelzoom** [comment]
Looks like this would be easy to fix.  In MultiLineText, change line 72 from this:

`return new Text( line, _.omit( thisNode.options, 'align' ) );`

to this:

`return new Text( line, _.omit( thisNode.options, 'align', 'maxWidth' ) );`

**Comment by pixelzoom** [comment]
With the above change, the example looks like this:

![screenshot_67](https://cloud.githubusercontent.com/assets/3046552/11228660/7de46636-8d4b-11e5-9e89-575d7a115ac1.png)

Looks correct to me, so I'm going to go for it.

**Comment by pixelzoom** [comment]
@samreid would you mind reviewing? Should be a quickie.

**Comment by samreid** [comment]
Yes, this solution looks correct because it scales the entire node (with 0+ Text instances) rather than setting maxWidth on each Text instance *and* the parent.  I tested some values in MOTHA and it worked as expected, closing.
