### ISSUE TITLE
implement a standard close ('X') button

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#210]
I need a close button in models-of-the-bydrogen-atom. With all of the work that's been done on dialogs and other sims, I'm surprised to find that there is no such thing. I see 3 almost-identical implementations, which look like code has been copy-pasted: in neuron, under-pressure, and fluid-pressure-and-flow.  

For example, in neuron.MembranePotentialChart:

```js
    // close button
    // TODO: Should go into common code if not already there
    var closeIconLength = 5;
    var xIcon = new Path( new Shape()
        .moveTo( -closeIconLength, -closeIconLength )
        .lineTo( closeIconLength, closeIconLength )
        .moveTo( closeIconLength, -closeIconLength )
        .lineTo( -closeIconLength, closeIconLength ),
      { stroke: 'white', lineWidth: 2.5 }
    );
    var closeButton = new RectangularPushButton( {
      baseColor: PhetColorScheme.RED_COLORBLIND,
      content: xIcon,
      xMargin: 4,
      yMargin: 4,
      listener: function() {
        thisChart.neuronModel.potentialChartVisible = false;
      }
    } );
```

**Comment by pixelzoom** [comment]
CloseButton push. Issues created for the sims (that I could identify) that have this duplicated code.

@jbphet please review.

**Comment by jbphet** [comment]
Looks good to me, thanks for doing this.  Closing.
