### ISSUE TITLE
SubSupText options support

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#215]
It looks like a few options in SubSupText are no longer supported.  Options ```subXSpacing``` ```supXSpacing``` and ```supYOffset``` have no effect and are never referenced in the node construction.

**Comment by jessegreenberg** [comment]
It looks like these options were removed from construction in commit 3b640aaa273c05945b0a4048db277ae4d98bc35c for compatibility with embedding marks.

Added them back, @jonathanolson would you mind reviewing?

**Comment by jonathanolson** [comment]
Yikes, sorry! Looks good, closing.
