### ISSUE TITLE
implement EyeDropperNode.dispose

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#216]
EyeDropperNode currently leaks memory if instances are created that don't exist for the lifetime of the sim. Need to implement `dispose`.

**Comment by pixelzoom** [comment]
Work completed. @jessegreenberg randomly chosen to review.

**Comment by jessegreenberg** [comment]
Looks good overall.  However, in ```this.disposeEyeDropperNode```, I think the ```emptyObserver``` was meant to be unlinked.

```js

**Comment by pixelzoom** [comment]
Ah, copy-paste error, good catch @jessegreenberg .  Fixed and closing.   Feel free to take a peek.
