### ISSUE TITLE
Disabled components should not be pickable

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#219]
While investigating https://github.com/phetsims/phet-io/issues/282 I saw the following components that had setEnabled or set enabled without obvious setting of pickable:false:
- [ ] NumberPicker (it could be that I just don't understand how pickability is being handled here)
- [ ] EyeDropperNode

**Comment by pixelzoom** [comment]
We're not using `pickable:false` for disable components, we're using `inputEnabled:false`.

**Comment by pixelzoom** [comment]
@samreid is there anything to do here?

**Comment by samreid** [comment]
Looks like inputEnabled will work for those components and no additional work is necessary (though one day we may make NumberPicker and EyeDropperNode extend UIComponent.)
