### ISSUE TITLE
i18n of accessibility labels

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#22]
Accessibility labels are currently not localized, and I believe this is the case throughout all code (not just 'sun').

For example, in TimerToggleButton:

``` javscript
 _.extend( { addRectangle: true, label: 'Timer' }, options ) ); // TODO: i18n
```

Related questions:
- Will labels be spoken by a screen reader? If so, they need to be localized. 
- Should we prefix all accessibility strings with something ('accessibility.' ?) so that translators can identify them  
- Are there other non-label strings that have a similar issue?

**Comment by pixelzoom** [comment]
@jessegreenberg can you please evaluate whether this issue is still necessary? It's my understanding that a11y strings have been factored out into files like OhmsLawA11yStrings.js, and are no longer inlined.

**Comment by zepumph** [comment]
This issue has been superceded by https://github.com/phetsims/rosetta/issues/221.
