### ISSUE TITLE
Odd display issue for ParametricSpringNode

### ISSUE THREAD

**Issue by mattpen** [phetsims/scenery-phet#220]
The ParametricSpringNode is behaving strangely in masses-and-springs.  When given a large width and stretched to a certain length the edges turn into spikes, screenshot attached.  I was able to recreate the behavior in chrome and FF for MAS, but I could not recreate it in the PSN demo.

![image](https://cloud.githubusercontent.com/assets/11747676/13338371/2c8c5e10-dbde-11e5-9836-df01495f0586.png)

ParametricSpringNode properties:
```
aspectRatio: 4
deltaPhase: 3pi/2
lineWidth: 10
loops: 10
phase: pi
pointsPerLoop: 40
radius: 10
xScale: -6.05
```

**Comment by mattpen** [comment]
I recreated similar behavior in the PSN demo:

![image](https://cloud.githubusercontent.com/assets/11747676/13339105/6e0f0298-dbe3-11e5-967f-3ce4ad9cf94d.png)

**Comment by jessegreenberg** [comment]
I am wondering if adding lineJoin: 'round' to ParametricSpringnode pathOptions could help reduce this effect.

**Comment by mattpen** [comment]
Actually changing pointsPerLoop in the MAS example to 30 fixed it.  I'll try that fix tonight.

**Comment by mattpen** [comment]
@jessegreenberg - I think that fixes it! After adding that line I can't recreate the behavior in the scenery-phet demo any more.  Thanks

**Comment by mattpen** [comment]
@jonathanolson - Tagging you so you are aware of the change for any upcoming maintenance releases.
