### ISSUE TITLE
GaugeNode should limit the width of its text

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#222]
See https://github.com/phetsims/energy-skate-park-basics/issues/337

**Comment by samreid** [comment]
Empirically I determined radius*1.3 to be a good fit:

![image](https://cloud.githubusercontent.com/assets/679486/13442489/b1366a8c-dfb9-11e5-859f-090977f87df0.png)

**Comment by samreid** [comment]
The above pic is from ESPB, below is FAMB:
![image](https://cloud.githubusercontent.com/assets/679486/13442543/05e3c71e-dfba-11e5-92ea-2cee00f3b9be.png)

Seems good in both cases, I'll commit.

**Comment by samreid** [comment]
Fixed in the above commit, @jessegreenberg can you please review?

**Comment by jessegreenberg** [comment]
Changes look great, verified that it looks good in FAMB and ESPB.  Back to @samreid to close unless there are other related issues to see through.

**Comment by samreid** [comment]
Thanks @jessegreenberg, closing.
