### ISSUE TITLE
Gauge Node does not handle long string labels

### ISSUE THREAD

**Issue by aadish** [phetsims/scenery-phet#223]
The gauge node for long strings currently look like this 
![capture](https://cloud.githubusercontent.com/assets/4546788/13537548/afe82544-e202-11e5-8df3-77b079c681a2.PNG)

Seems like maxWidth is not set for the label

**Comment by jessegreenberg** [comment]
@aadish I think this was recently handled in https://github.com/phetsims/scenery-phet/issues/222.  With a fresh pull of scenery-phet is this still an issue?

**Comment by aadish** [comment]
@jessegreenberg you were correct I hadn't pulled the latest branch. Thanks for pointing it out. 
Closing this issue
