### ISSUE TITLE
AccessiblePeer has no dispose function

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#226]
As noted in https://github.com/phetsims/tasks/issues/546#issuecomment-198165557... AccessiblePeer constructor has `@param {DOMElement} domElement`, to which it adds listeners. It has no `dispose` function, so it never removes listeners, creating a potential memory leak. As a common-code component, AccessiblePeer should definitely have a `dispose` function.

**Comment by pixelzoom** [comment]
Mea culpa... AccessiblePeer does have a `dispose` function. But it doesn't call removeEventListener:

```js
dispose: function() {
      this.disposed = true;

      // for now
      this.freeToPool && this.freeToPool();
    }
```

**Comment by jessegreenberg** [comment]
AccessiblePeer now removes its event listeners.  Closing.
