### ISSUE TITLE
"drawer" UI component needed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#228]
Function Builder requires a new type of UI component. It's a "drawer" that can be opened and shut. In the design doc, it's described as having a "grabbable tab sticking out" that can be pulled to reveal the "contents" of the drawer.  The doc doesn't specify, but I suppose you close the drawer by pushing the tab in the opposite direction.

Here's are 3 such drawers in Function Builder, shown in the closed position:

![closed](https://cloud.githubusercontent.com/assets/3046552/13974416/22fd8372-f071-11e5-8d69-c25a53679818.png)

Here are the same 3 drawers in the open position:

![opened](https://cloud.githubusercontent.com/assets/3046552/13974421/2c255b5a-f071-11e5-80a0-72fecf6b9385.png)

Since this drawer needs to handle 3 different types of contents (table, graph, equation) in Function Builder, I'll need to generalize this anyway.  So I might as well create something that other sims can use. 

Next up, nailing down the behavioral requirements (underspecified in the design doc).

**Comment by pixelzoom** [comment]
Labeling for developer meeting, in case someone else has already implemented something similar. @samreid @jonathanolson @jbphet @jessegreenberg please chime in if you know of any relevant prior work.

Also mentioning @amanda-phet and @ariel-phet, in case they want to chime in.

**Comment by pixelzoom** [comment]
Design questions:

(1) According to the design doc, you drag the tab to open/close the drawer.  Do you need to fully open/close it, or does it continue to open/close after you stop dragging?

(2) Does clicking on the tab (without dragging) do anything? 

(3) The tab looks very similar to the iOS menu button (eg, the PhET menu button in the navigation bar), which is something you click, not something you drag.  Will that be a problem? Do we need a different look for the tab?

(4) The examples shown in the mockups above are all vertical drawers. Should the implementation support horizontal drawers? Does this decision affect the look of the tab? 

(5) iOS uses an arrow to open/close a drawer-like component (see for example Control Center). 
The arrow indicates the direction to drag.  Should we imitate that design?  Will that conflict with Carousel arrows, or the arrows on the table shown in the mockups above?

**Comment by samreid** [comment]
I'm not aware of any components like that, the closest match I'm aware of is the Accordion Box, but it's a bit different.

**Comment by jonathanolson** [comment]
I have not implemented anything similar to that.

**Comment by pixelzoom** [comment]
Work on this is proceeding in function-builder.Drawer.

**Comment by pixelzoom** [comment]
There is a good start on this in `function-builder.Drawer`. It has been generalized, and the only dependency on function-builder is the namespace (functionBuilder.js).  I never got any "official" requirements for this, so everything that I did is specific to function-builder.  Since function-builder is currently the only client, I will ruminate on whether to migrate this to scenery-phet, or leave that for the next developer who needs a drawer.

**Comment by pixelzoom** [comment]
Here's a screenshot from function-builder's "Equations" screen, showing the current look:

![screenshot_49](https://cloud.githubusercontent.com/assets/3046552/15589887/03242e98-2352-11e6-9341-d7868c5f0d9d.png)

**Comment by pixelzoom** [comment]
function-builder.Drawer is generalized and could be moved to scenery-phet.  

@samreid @jbphet @jessegreenberg @andrewadare Do any of you have strong feelings on whether to
(a) move it now, or (b) move it when needed in another sim?

**Comment by pixelzoom** [comment]
@ariel-phet feel free to chime in on whether to move it now or later.

**Comment by jbphet** [comment]
I would prefer to see it moved now, since the next potential user is more likely to find it in the common code if they are looking around.  It's a cool UI component, so I have little doubt that it will be reused.

**Comment by pixelzoom** [comment]
Thanks @jbphet, that's enough of a quorum for me :)

I've moved Drawer to scenery-phet. The only modification needed was to adjust its namespace.

@andrewadare Would you mind reviewing this as part of function-builder code review (https://github.com/phetsims/function-builder/issues/55)?

**Comment by pixelzoom** [comment]
I also added a demo for Drawer to the "Components" screen of the scenery-phet demo app.

**Comment by andrewadare** [comment]
@pixelzoom The Drawer.js source looks great: no TODO's, ample documentation, disposal code is in place, no lint or assertion errors, and nothing appears awkward or out of place about the design or interface.

I played with the simple "Hellow Drawer" example and it works without any problems.

**Comment by pixelzoom** [comment]
@andrewadare Anything else to do here?

**Comment by andrewadare** [comment]
No, Drawer.js looks great as far as I am concerned. Close at your discretion.

**Comment by andrewadare** [comment]
Well, the only thing remaining is tandem instrumentation, but that hinges on the outcome of https://github.com/phetsims/phet-io/issues/77

**Comment by pixelzoom** [comment]
No PhET-iO instrumentation is needed at this time, including `Tandem.validateOptions`.  See https://github.com/phetsims/phet-io/issues/77#issuecomment-230825758.

Closing.
