### ISSUE TITLE
move RESET_ALL_BUTTON_BASE_COLOR to PhetColorScheme.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#231]
ResetAllButton.RESET_ALL_BUTTON_BASE_COLOR should be moved to PhetColorScheme.

**Comment by pixelzoom** [comment]
Done, fixed the once occurrence in CCKB. Assigning to @samreid, since he added ResetAllButton.RESET_ALL_BUTTON_BASE_COLOR on 3/2/16, presumably for CCKB.

**Comment by samreid** [comment]
I fixed a circuit-constructionn-kit lint issue introduced above.

**Comment by samreid** [comment]
Looks good, thanks, closing.
