### ISSUE TITLE
complete the port of VisibleColor

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#232]
VisibleColor was only partially ported from Java, and there's some stuff missing that is needed for models-of-the-hydrogen-atom.

**Comment by pixelzoom** [comment]
Common-code components that use VisibleColor:

SpectrumNode
WavelengthSlider

Sims that use VisibleColor directly or indirectly:

beers-law-lab
bending-light
blackbody-spectrum
color-vision
models-of-the-hydrogen-atom
molecules-and-light

**Comment by pixelzoom** [comment]
Port completed, tested all of the above.

Randomly assigned to @jessegreenberg to review.

**Comment by jessegreenberg** [comment]
Port looks good to me, and I tested out ```wavelengthToColor``` and ```colorToWavelength``` functions in a simple test case, they behaved exactly as I would have expected.  Reassigning to @pixelzoom in case there is anything left to do before closing.
