### ISSUE TITLE
GaugeNode oddities

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#233]
This was noted while implementing GaugeNode.dispose in https://github.com/phetsims/scenery-phet/issues/201 with @andrewadare.

GaugeNode has a couple of things that look wrong.

(1) `this.label` is annotated as private. It is not used outside the constructor, so should be a `var`.

(2) `updateEnabledProperty` documentation is confusing/wrong:

```js
// Optional property to pass in--if the client provides a updateEnabledProperty
// then the needle will only be updated when changed and visible (or made visible)
updateEnabledProperty: new Property( true )
```

Within the implementation of GaugeNode, `updateEnabledProperty` has nothing to do with visibility. If the goal is to disable updates when a GaugeNode is visible, that must be handled by the client, by setting `updateEnabledProperty` to `false` when the node is invisible.

**Comment by pixelzoom** [comment]
Similar confusing documentation about `updateEnabledProperty` appears in energy-skate-park-basics.GaugeNeedleNode, added by @samreid.  So I suspect that this is where the `updateEnabledProperty` feature and doc originated.

**Comment by pixelzoom** [comment]
(3) `var linear = require( 'DOT/Util' ).linear;`  We have discouraged this type of import.

**Comment by samreid** [comment]
> (3) var linear = require( 'DOT/Util' ).linear; We have discouraged this type of import.

I see 6 occurrences of this across 5 repos.

**Comment by pixelzoom** [comment]
I have no intention of fixing all occurrences of `var linear = require( 'DOT/Util' ).linear`.

**Comment by pixelzoom** [comment]
Cleanup completed. Assigned to @samreid for review.

**Comment by samreid** [comment]
> I have no intention of fixing all occurrences of var linear = require( 'DOT/Util' ).linear.

This will be done in the above referenced issue.

**Comment by samreid** [comment]
I simplified the listeners and reformatted the JSDoc in the above commits.  I'll create a small test harness to make sure memory is un-leaky.

**Comment by samreid** [comment]
Creating and disposing 1000 GaugeNodes doesn't show any memory issues:
![image](https://cloud.githubusercontent.com/assets/679486/14536782/652d197a-0231-11e6-8679-a75fd7e60f21.png)

Other changes seem good.

Here's my harness for testing memory:
```js
// Copyright 2013-2015, University of Colorado Boulder

/**
 * A single screen for the Energy Skate Park: Basics sim.
 *
 * @author Sam Reid
 */
define( function( require ) {
  'use strict';

  // modules
  var EnergySkateParkBasicsModel = require( 'ENERGY_SKATE_PARK_BASICS/energy-skate-park-basics/model/EnergySkateParkBasicsModel' );
  var EnergySkateParkBasicsScreenView = require( 'ENERGY_SKATE_PARK_BASICS/energy-skate-park-basics/view/EnergySkateParkBasicsScreenView' );
  var Image = require( 'SCENERY/nodes/Image' );
  var inherit = require( 'PHET_CORE/inherit' );
  var Screen = require( 'JOIST/Screen' );
  var Node = require( 'SCENERY/nodes/Node' );
  var GaugeNode = require( 'SCENERY_PHET/GaugeNode' );
  var Property = require( 'AXON/Property' );
  var ScreenView = require('JOIST/ScreenView');

  function EnergySkateParkBasicsScreen( name, homescreenIcon, navbarIcon, draggableTracks, friction, options ) {
    Screen.call( this, name, new Image( homescreenIcon ),
      function() { return {}; },
      function() {
        var node = new ScreenView(  );
        var p = new Property( 1 );
        var gaugeNode = new GaugeNode( p, 'label', { min: 0, max: 10 } );
        node.addChild( gaugeNode );
        node.step = function() {
          gaugeNode.dispose();
          node.removeAllChildren();
          gaugeNode = new GaugeNode( p, 'label', { min: 0, max: 10 } );
          console.log( 'init' );
          node.addChild( gaugeNode );
        };
        return node;
      }, {
        navigationBarIcon: new Image( navbarIcon ),
        tandem: options.tandem
      } );
  }

  return inherit( Screen, EnergySkateParkBasicsScreen );
} );
```

I also spot tested Energy Skate Park: Basics and Forces and Motion: Basics.

**Comment by pixelzoom** [comment]
> I simplified the listeners and reformatted the JSDoc in the above commits. 

For the dispose pattern, we were trying to stick with the observer being named similarly to the Property, eg:

`valueProperty.unlink( valueObserver );`

Your simplification violates that pattern, but I'm not going to change it back.

**Comment by pixelzoom** [comment]
> I simplified the listeners and reformatted the JSDoc in the above commits. 

For the dispose pattern, we were trying to stick with the observer being named similarly to the Property, eg:

`valueProperty.unlink( valueObserver );`

Your simplification violates that pattern:

`valueProperty.unlink( updateNeedle );`

...but I'm not going to change it back.
