### ISSUE TITLE
StepBackButton is a reflected version of StepButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#235]
StepButton and StepBackButton look identical, reflected about the y-axis.  Why do we need both?

**Comment by pixelzoom** [comment]
For example, in Neuron:

![screenshot_07](https://cloud.githubusercontent.com/assets/3046552/14541708/81df2ea2-0248-11e6-8d63-c9b6c6d20423.png)

**Comment by pixelzoom** [comment]
Can't reflect the button, or the lighting would be wrong with 3D appearance.  But we can reflect the icon.

**Comment by pixelzoom** [comment]
StepButton should have an option that determines whether it's icon is forward or back. Then delete StepBackButton.

**Comment by pixelzoom** [comment]
Major problem here, introduced in 1ea01980de4fb57b10710f6da27cf4271238d7b3 by @jbphet.  StepButton and StepBackButton have totally opposite semantics for their `enabledProperty` param. 

The constructor used to be:

`function StepButton( stepFunction, playProperty, options )` 

and it was changed to:

`function StepButton( stepFunction, enabledProperty, options )` 

and the listener is this, which is most definitely *not* whether the button is enabled:

`enabledProperty.link( function( value ) { stepButton.enabled = !value; } );`

In StepBackButton, the listener is correct:

`enabledProperty.link( function( value ) { stepButton.enabled = value; } );`

**Comment by pixelzoom** [comment]
Fixing the above is going to require fixing 16 call sites, in 13 sims.

**Comment by pixelzoom** [comment]
RewindButton has a similarly wonky constructor and listener:

```js
function RewindButton( stepFunction, playProperty )

playProperty.link( function( value ) { stepButton.enabled = !value; } );
```

**Comment by pixelzoom** [comment]
I spent a couple of hours trying to untangle this spaghetti and punted. 

Assigning to @jbphet for thoughts on how to proceed.

**Comment by pixelzoom** [comment]
Here's what I ended up doing:
• made StepButton the base type, with subtype StepForwardButton and StepBackButton
• replaced uses of StepButton with StepForwardButton (13 sims)
• tested all of the above

Assigning to @jbphet for review.

**Comment by jbphet** [comment]
The restructuring/refactoring makes sense to me, the commits look good.  I tested the behavior on the current master versions of Neuron, States of Matter, and Molecules and Light since these are simulations with which I'm quite familiar, and they all appeared to behave correctly.  Thanks @pixelzoom - this seems like a good improvement.  Closing.
