### ISSUE TITLE
various issues in RewindButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#236]
Noted while working on https://github.com/phetsims/scenery-phet/issues/235.

• doc is wrong, looks like copy/paste from elsewhere
• stepFunction param should be replaced by options.listener
• has playProperty constructor param, while other similar buttons (StepButton,...) have enabledProperty
• playProperty assume you never want to rewind while playing, not a generally good assumption, and is in fact not what is done in GAO
• playProperty is not used by the 1 call site (GAO), which instead sets enabled directly

**Comment by pixelzoom** [comment]
There is only 1 call site, in GAO, so best to fix this now.

**Comment by pixelzoom** [comment]
Done. Assigned to @samreid to review.

**Comment by samreid** [comment]
I reviewed the commits and tested the rewind button in the sim, seems like it is working properly.  Closing.
