### ISSUE TITLE
More flexible number formatter for NumberPicker

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#240]
@kathy-phet requested in https://github.com/phetsims/proportion-playground/issues/20

> Also is it hard for the spinner in the apple scene to have

> $1, $2, $3?

**Comment by samreid** [comment]
There is a straightforward solution to this that seems general enough without being risky, so I'll proceed in master.  Perhaps good to have the original author @pixelzoom take a look when complete.

**Comment by samreid** [comment]
The solution I will pursue provides a default option:

```js
formatText: function( text ) {return text;} // Text processor that can be used for formatting the text
```

which can be overriden by providing a different formatText option.

**Comment by samreid** [comment]
I implemented the solution in master as described above and exercised it in Proportion Playground (see associated commit).  @pixelzoom are you available to review this change?

**Comment by pixelzoom** [comment]
Since this is NumberPicker and not TextPicker, how about `formatNumber` instead of `formatText`?

**Comment by pixelzoom** [comment]
Also, your use of this new feature in Proportion Playground doesn't appear to be localized:

```js
formatText: function( text ) {return '$' + text;} // Put a $ sign in front of the spinner number
```

**Comment by samreid** [comment]
> Since this is NumberPicker and not TextPicker, how about `formatNumber` instead of `formatText`?

There is already a formatting phase that converts `number` to `string` before it is passed to the format function:
```js
Util.toFixed( rangeProperty.get().min, options.decimalPlaces )
```

I'm concerned that naming it `formatNumber` might give the wrong impression that the input is a `number`.  To be clear, we could call it something like `formatFixedNumberString`.

**Comment by samreid** [comment]
> Also, your use of this new feature in Proportion Playground doesn't appear to be localized:

Thanks @pixelzoom, this is fixed in the above commit.

**Comment by pixelzoom** [comment]
Change to `Util.toFixedNumber` and the input will be a number.

**Comment by samreid** [comment]
```js
Util.toFixed(0.1,3) // gives "0.100"
Util.toFixedNumber(0.1,3) // gives 0.1
```
If we switch to toFixedNumber then we would lose the trailing decimal places.

**Comment by pixelzoom** [comment]
I unfortunately don't have time to pursue this, so proceed as you see fit.

**Comment by samreid** [comment]
OK, let's proceed with the current implementation and we can revisit in the future if trouble is spotted, closing.
