### ISSUE TITLE
NumberControl needs to be tandemized

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#241]
In order to support PhET-iO instrumentation of Circuit Construction Kit: Black Box Study for issue https://github.com/phetsims/circuit-construction-kit/issues/138, NumberControl.js must be instrumented.

**Comment by samreid** [comment]
It has a Text node that will need to be converted to TandemText.

**Comment by samreid** [comment]
The text `NumberControl` doesn't appear in the function-builder source directory, so I may not need to synchronize work with @pixelzoom on this.

**Comment by pixelzoom** [comment]
I'm not clear on what this means.

**Comment by pixelzoom** [comment]
Ah, I see... "so I may *not* need to synchronize work".  Feel free to proceed without me.

**Comment by samreid** [comment]
Does Function Builder use NumberControl.js?  It doesn't appear so, but there may be a transitive dependency that is unclear.  I'd like to work on NumberControl but don't want to hamper development of Function Builder if it is using NumberControl.

**Comment by pixelzoom** [comment]
NumberControl not used by Function Builder.  Hooke's Law is the only other sim that uses it.

**Comment by samreid** [comment]
Thanks, good to know.

**Comment by samreid** [comment]
I instrumented NumberControl and NumberDisplay and tested that they work properly in Circuit Construction Kit: Black Box Study (instrumented) and in Hooke's Law (uninstrumented), will commit shortly.

**Comment by samreid** [comment]
Committed, @jbphet @andrewadare or @pixelzoom feel free to reopen if you wish to review.

**Comment by pixelzoom** [comment]
I don't see:
• a call to `Tandem.validateOptions`
• a call to `tandem.addInstance` for the NumberControl instance
• a call to  `tandem.removeInstance` in `dispose`

Are some of these unnecessary in this case?

**Comment by samreid** [comment]
Those are all necessary, thanks for pointing that out.  I've added them, tested in CCK-phet-io and Hooke's Law (phet), and all seems well, committing shortly.

**Comment by samreid** [comment]
Validation also missing for NumberDisplay.js, I'll add it shortly.

**Comment by samreid** [comment]
I validated options for NumberDisplay above and tested in Expression Exchange, all seems well.  CCK grunt is also passing, so lint seems OK.  @pixelzoom anything else to do here?

**Comment by pixelzoom** [comment]
👍 Closing.
