### ISSUE TITLE
code review EyeToggleButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#242]
This was moved over from function-builder and should be reviewed. 

How to handle tandem instrumentation is dependent on the outcome of phetsims/phet-io#77

**Comment by pixelzoom** [comment]
Somewhat related to phetsims/function-builder#55, which is why I assigned @andrewadare.

**Comment by andrewadare** [comment]
This tiny piece of code does not leave many places for problems to hide.

Source formatting looks good; interface is simple and reasonable; comments and docs are in place; memory is reclaimed; no lint or assertion problems--not much more to say, apart from the tandem issue already mentioned.

I didn't see a test example in scenery-phet, but clearly it's working fine in Function Builder.

I am confident to sign off on this.

**Comment by pixelzoom** [comment]
Thanks @andrewadare.  I've added EyeToggleButton to the scenery-phet demo.

**Comment by pixelzoom** [comment]
No PhET-iO instrumentation is needed at this time, including `Tandem.validateOptions`.  See https://github.com/phetsims/phet-io/issues/77#issuecomment-230825758.

Closing.
