### ISSUE TITLE
problems with API for StepBackButton and StepForwardButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#243]
Noticed while adding buttons to the scenery-phet demo.

Multiple problems with the API for StepBackButton and StepForwardButton, which have these constructors:

```js
  /**
   * @param {function} stepFunction
   * @param {Property.<boolean>} enabledProperty
   * @param {Object} [options]
   * @constructor
   */
  function StepBackButton( stepFunction, enabledProperty, options );

  /**
   * @param {function} stepFunction
   * @param {Property.<boolean>} playingProperty - button is disabled when this is true
   * @param {Object} [options]
   * @constructor
   */
  function StepForwardButton( stepFunction, playingProperty, options );
```

(1) Parameters that do the same thing have different names: `enabledProperty` vs `playingProperty`.

(2) StepBackButton and StepForwardButton are subtypes of PushButton, which has its own enabledProperty.  Why do these buttons need an extra enabledProperty?  All other buttons in scenery-phet require the client to use the enabledProperty provided by the button.

(3) Why is `stepFunction` a required parameter? It's likely that there `function() {}` is a reasonable default.  If that's the case, then it should be an option.

(4) Due to 1-3, the API for these buttons looks different than other scenery-phet buttons.

Assigning to @samreid for comment, since I believe he was the original author. (I factored out StepButton recently.)

**Comment by pixelzoom** [comment]
Looking more closely at (1) above... playingProperty actually has inverted semantics. The button is disabled when when true.

**Comment by pixelzoom** [comment]
I also see this in both buttons:

```js
    assert && assert( !options.listener, 'stepFunction replaces options.listener' );
    options.listener = stepFunction;
```

Why is this difference necessary? Why can't we just use `options.listener`, like other buttons?

**Comment by samreid** [comment]
(1) Yes those parameters should be unified.  I'm not sure whether we should go with isPlayingProperty, or enabledProperty.  I don't know why these diverged.
(2) I think this was just a way to disable the buttons when the sim is in "play" (not pause) mode.  It was assuming the sim already had a property for that.  As described in (1) we should make this consistent.
(3) It seems incorrect for button listeners to be optional.  Why would a simulation have a button that does nothing?  However, there is precedent for the listener being passed as an option (perhaps for uniformity with other options and so it is a named parameter), so I'm ok to stick with that precedent.
(4) I agree
(preceding comment) Sure, sounds like a good plan to use options.listener as for other buttons.

**Comment by pixelzoom** [comment]
I'll assign this to me to clean up, low priority.

**Comment by pixelzoom** [comment]
Check list, for what I need to change and test...

Sims that use `StepBackButton`:

- [ ] neuron

Sims that use `StepForwardButton`:

- [ ] bending-light
- [ ] color-vision
- [ ] energy-forms-and-changes
- [ ] energy-skate-park-basics
- [ ] fluid-pressure-and-flow
- [ ] forces-and-motion-basics
- [ ] gravity-and-orbits
- [ ] molecules-and-light
- [ ] neuron
- [ ] pendulum-lab
- [ ] rutherford-scattering
- [ ] states-of-matter
- [ ] wave-on-a-string

**Comment by pixelzoom** [comment]
In the above commits, I removed the `stepFunction` constructor parameter for `StepForwardButton` and `StepButton`, and used `options.listener` instead.  Adjusted all call sites, and tested all sims listed in https://github.com/phetsims/scenery-phet/issues/243#issuecomment-230833561.

**Comment by pixelzoom** [comment]
(6) The only reason why we currently need separate "forward" and "back" buttons is because of the https://github.com/phetsims/sun/issues/236 (a problem with buttons in general).  Working around this problem requires different values for the `xContent` option.

**Comment by pixelzoom** [comment]
If we fixed phetsims/sun#236, then we really don't need StepForwardButton and StepBackButton. We add a `playProperty` option to supertype StepButton, for clients that want the convenience of disabling the button when playProperty.value === true.  Other clients could use button.enabled direction (neuron is an example of where this would be more appropriate.)

Here's what a typical call site would look like:

```js
var playingProperty = new Property( false );

var stepForwardButton = new StepButton( {
  direction: 'forward',
  listener: function() { .... },
  playingProperty: playingProperty
} );


var stepBackButton = new StepButton( {
  direction: 'back',
  listener: function() { .... },
  playingProperty: playingProperty
} );
```

**Comment by samreid** [comment]
> If we fixed phetsims/sun#236, then we really don't need StepForwardButton and StepBackButton. 

In fact, we could move the content offset into StepButton (checks the direction to determine the offset) even if we don't fix phetsims/sun#236 and then we wouldn't really need StepForwardButton and StepBackButton.  But on the other hand, I'm wondering if it is simpler for developer to look for StepForwardButton, or StepButton and know they must supply a direction parameter.

There is some precedent for this pattern in HBox, which is a trivial subclass of LayoutBox whose sole purpose is to provide `{ orientation: 'horizontal' }`, but  `new HBox` reads a bit more elegantly than `new LayoutBox({orientation: 'horizontal'})`.

**Comment by pixelzoom** [comment]
@samreid How do you feel about making `playProperty` and option, for the scenario shown in https://github.com/phetsims/scenery-phet/issues/243#issuecomment-230856616?

**Comment by pixelzoom** [comment]
@samreid wrote:
> we could move the content offset into StepButton (checks the direction to determine the offset) even if we don't fix phetsims/sun#236

Will do.

**Comment by pixelzoom** [comment]
Here's what would be added to StepButton to support disabling the button while the sim is playing:

```js
function StepButton( options ) {

  options = _.extend( {
    ...
    playProperty: null // {Property.<boolean>|null} button is disabled when this is true
  }, options );

  ...

  // Disable this button when playing
  var thisButton = this;
  playingProperty.link( function( value ) { thisButton.enabled = !value; } );
}
```

**Comment by pixelzoom** [comment]
... and we should probably implement `dispose`, to unlink from `playingProperty` if it was provided.

**Comment by samreid** [comment]
> @samreid How do you feel about making playProperty an option, for the scenario shown in #243 (comment)?

Yes, sounds good, let's make it an option.

**Comment by pixelzoom** [comment]
The only usage of StepBackButton so far is in neuron, here's the call site in NeuronScreenView:

```js
 var stepBackwardButton = new StepBackButton( stepBackEnabledProperty, {
```

Note the variable name is `stepBackwardButton`, not `stepBackButton`.  Should we rename `StepBackButton` button to `StepBackwardButton`, and the option from "back" to "backward".  The antonym of "forward" is "backward", not "back".

**Comment by samreid** [comment]
Not feeling too strongly about it, but slightly in favor of "backward" instead of "back".

**Comment by pixelzoom** [comment]
Add options `playingProperty` to StepButton, fixed up and tested all call sites.

**Comment by pixelzoom** [comment]
StepBackButton renamed to StepBackwardButton.

StepForwardButton and StepBackwardButton added to scenery-phet demo.

All work completed here. @samreid would you mind reviewing?

**Comment by samreid** [comment]
- [x] scenery-phet demo looks good
- [ ] this assertion should have a comment (in both occurrences): `assert && assert( !options.direction );`
- [ ] Why not simplify this extend call?  Currently written as:

```js
StepButton.call( this, _.extend( {}, options, { direction: 'backward' } ) );
```

Why not write as the following, since we already asserted that direction doesn't appear in the options?
```js
StepButton.call( this, _.extend( { direction: 'backward' }, options ) );
```

- [ ] These lines read kind of confusingly to me:
```js
var BUTTON_RADIUS = ( options && options.radius ) ? options.radius : 20;
```

Would it be better to use this?
```js
var BUTTON_RADIUS = options && options.radius || 20;
```

Also in both of these logics, it is impossible to provide a radius of 0 because it is falsy.  Perhaps that is a good thing in this case though.

- [x] I skimmed through usage sites and didn't see any trouble.  
- [x] I tested Wave on a String and all seems well.

**Comment by samreid** [comment]
I made a few of the recommendations above, will wait to discuss the "These lines read kind of confusingly to me:" part with @pixelzoom

**Comment by samreid** [comment]
Here's an implementation that allows 0 radius values:

```js
options && typeof options.radius==='number' ? options.radius : 20
```

I didn't grok the original proposal right away, but really I'm fine with any of the proposed solutions for this (including the original).

**Comment by pixelzoom** [comment]
Re the computation of BUTTON_RADIUS in https://github.com/phetsims/scenery-phet/issues/243#issuecomment-230923192...

This one doesn't do what you think it does. It returns true or false, not a radius value.

```js
var BUTTON_RADIUS = options && options.radius || 20;
```

I'm fine with either of these, but prefer the first (the current implementation) since a zero radius is almost certain to cause RoundPushButton to fail.

```js
var BUTTON_RADIUS = ( options && options.radius ) ? options.radius : 20;
var BUTTON_RADIUS = ( options && typeof options.radius==='number' ) ? options.radius : 20;
```

**Comment by samreid** [comment]
Let's stick with the current implementation then.

But just to clarify in case there is a misunderstanding, the JavaScript || operator does not always return a boolean.  Here is a transcript from my console:

![image](https://cloud.githubusercontent.com/assets/679486/16783065/b5a4deac-483f-11e6-8941-d52cf68210fe.png)

If this makes sense to you, then please close the issue.

**Comment by pixelzoom** [comment]
Got it, thanks for the clarification. Closing.
