### ISSUE TITLE
This repo should have a stylistically similar name to our other repos

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#246]
It seems inconsistent to have names for other repos like sun, kite, dot, shred, vegas, litmus, twixt, etc and scenery-phet sticks out like a sore thumb.
- Would it take a lot of work to rename it and maintain compatibility with old builds? Yes.
- Will we all agree on a great new name? No.
- Would it be better to rename it now instead of later?  Yes.

I am leaning toward "let's go for it", but not sure if I'm aware of all the ramifications.

**Comment by jessegreenberg** [comment]
I agree that it is out of PhET repo name style and that sooner is better than later.  However, I recall some discussion about deprecating/replacing scenery-phet, but can't find an issue anywhere about it.  If that is still a long term goal, the renaming work would be less important.

**Comment by samreid** [comment]
> However, I recall some discussion about deprecating/replacing scenery-phet

Are you thinking of our plans to deprecate/disseminate phetcommon? https://github.com/phetsims/phetcommon/issues/24

**Comment by jessegreenberg** [comment]
Indeed, yes sorry.  That is the issue I was thinking of, and that makes a lot more sense.

**Comment by samreid** [comment]
Since it will probably take more than 30 minutes, we decided not to go for this now.  @ariel-phet said we may go for this on a rainy day in the future, but not the near future.

**Comment by pixelzoom** [comment]
> scenery-phet sticks out like a sore thumb

Doesn't bother me at all.  Given the problems that it will create, and the time/cost involved, I really don't see the point in even considering a name change.

**Comment by samreid** [comment]
It seems the biggest cost would be dealing with dependencies.json during maintenance releases.  For this cost alone, I'm OK to close this issue.  We can reopen it in the future if want headaches in the future.  @pixelzoom please close if you agree.
