### ISSUE TITLE
multiple issues with MeasuringTape.createMeasuringTapeIcon

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#250]
(1) Returns the wrong node.

The current return statement is:

```js
return measuringTapeIcon.children[0];
```

The call to `measuringTape.toImage` is asynchronous, so unless the image is available immediately, this actually returns `measuringTape` (the full blown MeasureTape, not the Image).  We should be returning `measuringTapeIcon`, so that it can be put in the scenegraph, and then its child will be swapped when the image is available.  So this return should be changed to:

```
return measuringTapeIcon;
```

(2) Icon is pickable until the image is available.

Until the image is available, the node returned (`measuringTapeIcon`) has a child that is a full blown MeasureTape, which has a drag handler and can therefore be interacted with.  So the MeasureTape that is created internally should be created with `pickable:false`.

(3) `options` parameter is not applied to the node that is returned.

The `options` parameter is applied to the full-blown MeasureTape, not to the icon node that is returned. So good luck setting its cursor or other options.  And if you provide layout options (e.g. x, y, top, bottom), there's no telling what will happen when converting to an image.  I'm not sure how best to fix this -- maybe just document it.

**Comment by pixelzoom** [comment]
(4) Icon can't be properly centered.

MeasuringTape shows the value and units below the tape. This can be turned off using `setTextVisibility( false )` (sic), and this is in fact done in `createMeasuringTapeIcon`. But the invisible text still contributes to the bounds, which determines the size of the rendered image. And you end up with a bunch of blank pixels at the bottom.  Which makes it impossible to vertically center the icons.  E.g. in projectile-motion:

![screenshot_72](https://cloud.githubusercontent.com/assets/3046552/17227671/acb1ec4c-54cc-11e6-8b5f-4d95223de9c5.png)

**Comment by pixelzoom** [comment]
(5) Function name is redundant.  

`MeasuringTape.createMeasuringTapeIcon` is redundant. It should be MeasuringTape.createIcon`.

**Comment by pixelzoom** [comment]
(6) Duplicate implementations.

These similar implementations should be replaced with `MeasuringTape.createIcon`:

charges-and-fields.ChargesAndFieldsToolboxPanel: `createMeasuringTapeIcon`
fluid-pressure-and-flow.ToolsControlPanel: `createMeasuringTapeIcon`

**Comment by pixelzoom** [comment]
Fixed all of the above issues (1-6) and affected call sites. 

Assigning to @andrea-phet to review, since this was motivated by weirdness in projectile-motion,  and she and I were working on this together.

**Comment by andrea-phet** [comment]
It may be useful to be able to override `hasValue` when creating the icon. Even though this may not be the final decision, the design doc for projectile motion has the value text for the measuring tape icon visible:

![image](https://cloud.githubusercontent.com/assets/7988696/17229774/69f9965c-54d6-11e6-93c5-c5a82b99c044.png)

Everything else looks good. Assigning back to @pixelzoom to see if he wants to change the code.

**Comment by pixelzoom** [comment]
I made it possible to override options.hasValue, and tested in projectile-motion.ToolboxPanel like this:

```js
var measuringTapeIconNode = MeasuringTape.createIcon( {
  hasValue: true,
  textColor: 'black'
} );
```

**Comment by andrea-phet** [comment]
Thanks @pixelzoom Looks good, closing.
