### ISSUE TITLE
how to control layout of nodes for i18n?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#251]
I've encountered this a few times, most recently in https://github.com/phetsims/curve-fitting/issues/74#issuecomment-237897994. 

StringUtil.format (phetcommon) currently provides the ability to specify Java-style MessageFormat placeholders (e.g. {0} {1}) in a text string, then fill in those placeholders with other strings.  E.g.:

```
> StringUtils.format( 'Turn to the {0', turn to the {1}.', 'left', 'right' )
Turn to the left, turn to the right.
```

This is very useful for allowing translators to change the order of strings for their locale.   But it's insufficient when we need to insert arbitrary nodes into a string - for example, when the placeholders are for math symbols, which must be rendered in a different font, like this:

![screenshot_75](https://cloud.githubusercontent.com/assets/3046552/17444627/42eed4c2-5afe-11e6-9b21-fd67a8eedf4d.png)

Investigate ways to address this.

**Comment by pixelzoom** [comment]
Once way we could address this is via a new node type, perhaps call it `TextWithEmbeddedNodes`.  It looks for placeholders (e.g. {0}, {1}) in its text string, and inserts arbitrary nodes at those locations.  

Constructor:

```js
/**
 * @param {string} text - the text string, with placeholders
 * @param {Node[]} nodes - nodes that will be inserted at the location of the placeholders
 * @param {Object} [options] - see scenery.Text
 * @constructor
 */
function TextWithEmbeddedNodes( text, nodes, options )
```

Usage, for an English example:

```js
new TextWithEmbeddedNodes( 
  '{0} = some function, {1} = number of arguments',
  [ new Text( 'f', { font: new MathSymbolFont() } ), new Text( 'n', { font: new MathSymbolFont() } ) ],
  { font: new PhetFont() } ); 
```

Internally, this would split itself into multiple text strings, and replace the placeholders with the nodes provided.

**Comment by pixelzoom** [comment]
The `TextWithEmbeddedNodes` proposal above is still specific to text. Should we design something that is totally independent of node type?

**Comment by samreid** [comment]
`TextWithEmbeddedNodes` seems like the proper way to expose the ordering to translators.  Even if there is no displayed "text", this could still work.  Not sure if that is the right name is TextWithEmbeddedNodes in that case.

**Comment by samreid** [comment]
We reviewed this at the Aug 11 meeting and decided to wait until @pixelzoom returns for further discussion.

**Comment by pixelzoom** [comment]
8/18/16 dev meeting: Since ordering and spacing relies on a text-string pattern, probably makes sense to do this as described for TextWithEmbeddedNodes. 

Since I already worked around this in curve-fitting, this is low priority, and unassigned.

**Comment by pixelzoom** [comment]
There has been no work on this (and apparently no need) for 3.5 years, so closing this issue.
