### ISSUE TITLE
NumberControl: distinct values for tweaker increment and slider constraint

### ISSUE THREAD

**Issue by veillette** [phetsims/scenery-phet#252]
In the process of thinking about generalizing the layout of NumberControl (#217), we need to generalize some options to accommodate them within NumberControl.

NumberControl has an option called delta that controls (1) the increment of the tweakers, and (2)  the thumb on the slider via,

```
    var slider = new HSlider( numberProperty, numberRange, _.extend( {
      startDrag: options.startCallback,
      endDrag: options.endCallback,
      constrainValue: function( value ) {
        // constrain to delta
        value = Util.roundSymmetric( value / options.delta ) * options.delta;
        // constrain to range
        return numberRange.constrainValue( value );
      })

```

The custom made NumberControl in pendulumLab uses two different values.   
![image](https://cloud.githubusercontent.com/assets/7633344/17451127/68214db8-5b32-11e6-97e9-7e436171a6d9.png)

For instance, the length of the pendulumcan be incremented by 0.01 meter through the tweakers, whereas the slider is constrained to rounded to 0.10 meter.  I think the idea was to use the tweaker to get the high-precision.

**Comment by veillette** [comment]
Putting this on @pixelzoom radar since he wrote NumberControl.

**Comment by pixelzoom** [comment]
@veillette You can accomplish what you want to do without any changes to the current implementation. It's not very clear from looking at `options = _.extends`, but the client can provide `options.constrainValue`, which is passed to HSlider.  What you see at line 136 is the default implementation of `constrainValue`, which uses the same delta for the arrows and slider.

To clarify this, we should move the default value of  `constrainValue` closer to the `options = _.extends` call to make it clear that this can be overridden. Something like this at line 76:

```js
options.constrainValue = options.constrainValue || function( value ) {
  // constrain to delta
  value = Util.roundSymmetric( value / options.delta ) * options.delta;
  // constrain to range
  return numberRange.constrainValue( value );
};

@veillette Your thoughts?

**Comment by veillette** [comment]
I see it now.  In principle no change is needed. 
However, as you point out it is not so clear from a cursory read of the options. 
I would support your proposed change.

**Comment by pixelzoom** [comment]
I'll handle the proposed changes.

**Comment by pixelzoom** [comment]
It's also problematic to pass the entire `options` to HSlider, as is being done at NumberControl line 113:

```js
 var slider = new HSlider( numberProperty, numberRange, _.extend( {
      ...
    }, options, {
     ...
    } ) );
```

This makes it virtually impossible to use layout or scaling options with NumberControl, since passing them to HSlider will cause those options to be applied to the HSlider.  We should probably be using `_.pick` to extract the options that are relevant to HSlider.

**Comment by pixelzoom** [comment]
The issue of passing options to HSlider is a big can of worms, so I've created a separate issue, see https://github.com/phetsims/scenery-phet/issues/255.

@veillette would you mind reviewing the work that's been done here? It's all in the one commit shown immediately above (https://github.com/phetsims/scenery-phet/commit/7bdcfade04a8f0408314516c8a1d92e6ff786fa2).

**Comment by veillette** [comment]
Thanks @pixelzoom , it looks good. closing
