### ISSUE TITLE
revise API for NumberDisplay

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#253]
See https://github.com/phetsims/sun/issues/85.

In particular, a better API would be:

```js
  // valid values for options.align
  var ALIGN_VALUES = [ 'center', 'left', 'right' ];

 /**
   * @param {Property.<number>} numberProperty
   * @param {Range} numberRange
   * @param {Object} [options]
   * @constructor
   */
  function NumberDisplay( numberProperty, numberRange, options ) {

    options = _.extend( {
      align: 'right', // see ALIGN_VALUES
      valuePattern: '{0}', // {string} if you want units or other verbage, add them to the pattern, e.g. '{0} L'
      ...
```

**Comment by pixelzoom** [comment]
In many uses of NumberDisplay, I see the empty string provide for units. E.g. in unit-rates.EditNumberDisplayNode:

```js
74 this.numberDisplay = new NumberDisplay( valueProperty, options.numberRange, '', pattern, numberDisplayOptions );
```

This further suggests that the pattern should be an options, and the units should be part of the pattern.

**Comment by pixelzoom** [comment]
The API for NumberDisplay has been revised, as described above.

@jbphet @schmitzware @jessegreenberg Be aware that this change affected expression-exchange, unit-rates, and rutherford-scattering.  I compared before/after behavior and saw no changes in these sims, but you may wish to review.

Randomly assigning to @jbphet for review.

**Comment by pixelzoom** [comment]
Also note that this is similar to the API used in sun.NumberSpinner, so we may eventually be able to incorporate NumberDisplay into NumberSpinner.

**Comment by pixelzoom** [comment]
@jbphet It would be nice to have this reviewed before we discuss https://github.com/phetsims/scenery-phet/issues/254 at developer meeting.

**Comment by jbphet** [comment]
Okay, I'll review before the meeting.

**Comment by jbphet** [comment]
The reasoning behind making units and pattern into options makes sense to me, and the changes look good.  It seems to be working fine in Expression Exchange.  Thanks for doing this - it's a good improvement.

I'll remove my assignment.  @pixelzoom mentioned discussing this at developer meeting, so I won't close it.
