### ISSUE TITLE
revise API for NumberControl?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#254]
The API for NumberDisplay (which is used by NumberControl) was recently revised, to make formatting of the displayed value more flexible.  See https://github.com/phetsims/scenery-phet/issues/253.

Should a similar API change be made to NumberControl? It would make the format more flexible; it's currently limited to "{0} {1}", where {0} is value and {1} is units. But it would require more string file entries, e.g. in hooks-law I'd need to add "{0} m", "{0} N", "{0} N/m".

If we're going to do this... Now would be a good time to do so, since circuit-construction-kit-common (unpublished) and hookes-law are the only clients.  In the case of hookes-law, it looks straightforward - I could either add entries to the string file, or inject the desired units into the existing pattern ("pattern.0value.1units" with value "{0} {1}"). In the case of circuit-construction-kit-common, it didn't look as straightforward, @samreid would need to handle the conversion.

**Comment by pixelzoom** [comment]
Revising the API for NumberControl would also have the advantage of making it consistent with NumberDisplay and NumberSpinner.

**Comment by pixelzoom** [comment]
The next dev meeting that I'll be attending is 8/25/16, so you may wish to defer discussion of this until then.

**Comment by schmitzware** [comment]
IMHO the more general/flexible the better. So, I like the idea of just having a pattern that can be passed in as an option rather than assuming that all you'll ever want is a value and a unit (i.e. in the unit rates case I tack on a pre-value currency symbol). I'd vote for extending this to NumberControl also.

**Comment by jbphet** [comment]
I just reviewed the changes to NumberDisplay that were related to this, and the changes made there were an improvement.  Making the NumberControl API consistent with the revised NumberDisplay API seems like a good idea.

**Comment by pixelzoom** [comment]
8/18/16 dev meeting: Proceed with making NumberControl API similar to NumberDisplay.

**Comment by pixelzoom** [comment]
API has been changed and hookes-law has been converted.  

circuit-construction-kit-common needs to be converted (see TODO in CircuitElementEditPanel). Assigning to @samreid to handle this.

**Comment by samreid** [comment]
I updated CCK, is there anything else to do for this issue?

**Comment by pixelzoom** [comment]
Nope. Closing.
