### ISSUE TITLE
LaserPointerNode: add option to hide button

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#256]
In models-of-the-hydrogen-atom, we need a LaserPointerNode that doesn't have a toggle button on it.  Add `options.hasButton`.

**Comment by pixelzoom** [comment]
Adding `options.hasButton` also making LaserPointerNode conform to PhET's standard for the enabled/disabled feature (as described in https://github.com/phetsims/sun/issues/241#issuecomment-234031982).  Both changes were made in the above commit, and I added an "enabled" check box to scenery-phet demo for testing.

**Comment by pixelzoom** [comment]
@samreid would you mind reviewing?

**Comment by samreid** [comment]
There are a few problems with the proposed implementation:

(1) The DISABLED_OPTIONS are initialized like so:

```js
  var DEFAULT_OPTIONS = {
    enabledProperty: new Property( true ),
    // etc.
  };
```
And extended like so:
```js
options = _.extend( {}, DEFAULT_OPTIONS, options );
```
This means the same Property instance ends up registered as the same enabledProperty for multiple LaserPoinerNodes (using default options).  For instance, if a simulation has 3 LaserPointerNodes (using default options), and one of them is disabled, they will all become disabled.  You can test this by commenting out this line for both LaserPointerNodes in the ComponentsView, so they will get the default enabled property.

```js
enabledProperty: enabledProperty,
```
Then assign a LaserPointer as a global:
```js
window.rightLaserNode = rightLaserNode;
```

When running the simulation, type `window.rightLaserNode.setEnabled(false);` into the console and observe both laserPointerNodes become disabled.

(2) Dispose is broken for the button instance.  The button is declared like so:

```js
    if ( options.hasButton ) {

      // etc.

      // @private
      this.button = ( options.buttonType === 'toggle' ) ?
                    new RoundStickyToggleButton( false, true, onProperty, buttonOptions ) :
                    new RoundMomentaryButton( false, true, onProperty, buttonOptions );

      children.push( this.button );
    }
```

and the dispose is implemented like so:
```js
    // @private called by dispose
    this.disposeLaserPointerNode = function() {
      thisNode.button.dispose();
      thisNode.enabledProperty.link( enabledObserver );
      options.tandem && thisNode.options.removeInstance( thisNode );
    };
```

If the button is never assigned, there will be `undefined is not a function` in dispose.

(3) Dispose should unlink.  In the dispose function (see above), the enabledProperty is linking the enabledObserver.  This should be changed to unlink.

(4) lint is failing:

```
/Users/samreid/github/scenery-phet/js/LaserPointerNode.js
  25:7  error  "TNode" is defined but never used  no-unused-vars
```

**Comment by pixelzoom** [comment]
Ugh. I botched that one, thanks for catching.  Re (4), lint is failing because I accidentally deleted the `tandem.addInstance` call.

Fixed in the above commit.

**Comment by samreid** [comment]
Looks great, thanks, closing.
