### ISSUE TITLE
LaserPointerNode creates unnecessary this.tandem

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#257]
Noted while working on #256.

LaserPointerNode line 99:

```js
    this.tandem = options.tandem; // @private
    this.tandem && this.tandem.addInstance( this, TNode );
```

But `this.tandem` is not used outside of the constructor, so it's unnecessary.

**Comment by pixelzoom** [comment]
Looks like I added this code in 700d3f4a87ffd499fba6b12c28849bdb0f23d25f.   Fixed up in the above commit.  @samreid would you mind reviewing, to make sure I didn't break any PhET-iO sims?

**Comment by samreid** [comment]
I fixed options.tandem.removeInstance in the above commit, tested BLL in instance-proxies wrapper.  All seems well, closing.

**Comment by pixelzoom** [comment]
> I fixed options.tandem.removeInstance in the above commit

Doh. Maybe I should stay out of common code today.
