### ISSUE TITLE
WavelengthSlider needs additional options

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#260]
Noted while working on models-of-the-hydrogen-atom.

If you decrease `options.trackHeight`, then the value may collide with the buttons, e.g.:

![screenshot_79](https://cloud.githubusercontent.com/assets/3046552/17871834/88e4d6a0-687a-11e6-8540-0f4cfd9a546f.png)

So it would be nice to be able to control the size of the tweaker buttons, and the vertical spacing between the bottom of the value and the top of the track.

**Comment by pixelzoom** [comment]
It would also be nice if default for the vertical spacing between the bottom of the value and the top of the track were computed automatically, so that the value doesn't collide with the tweakers.

**Comment by pixelzoom** [comment]
Added options.ySpacing and options.maxTweakersHeight, working nicely in MOTHA:

![screenshot_80](https://cloud.githubusercontent.com/assets/3046552/17872201/3092fdae-687c-11e6-9d8f-dcda316b37b6.png)

@samreid Would you mind taking a peek?

**Comment by samreid** [comment]
All 3 commits look good, my only question is whether we would like a more specific term in place of `ySpacing`, perhaps something like `verticalValueDisplayMargin`?  It seems like `ySpacing` runs the risk of colliding with some future term.

**Comment by pixelzoom** [comment]
Changed `ySpacing` to `valueYSpacing`.

**Comment by samreid** [comment]
Sounds good, closing.
