### ISSUE TITLE
more efficient implementation of pause icon

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#268]
The pause symbol is 2 vertical bars. Currently it's implemented like this in `PlayPauseButton`:

```js
    var bar = function() { return new Rectangle( 0, 0, barWidth, barHeight, { fill: 'black' } ); };
    var bar1 = bar();
    var bar2 = bar();
    var pausePath = new HBox( { children: [ bar1, bar2 ], spacing: barWidth } );
```

This implementation requires 3 nodes and a function. (Also, `pausePath` is poorly named, since it's an `HBox`, not a `Path`.)

Consider changing to this implementation, which requires 1 Node:

```js
    var pauseShape = new Shape()
      .rect( 0, 0, barWidth, barHeight )
      .rect( 2 * barWidth, 0, barWidth, barHeight );
    var pausePath = new Path( iconShape, { fill: 'black' } );
```

**Comment by samreid** [comment]
Their bounds look the same:

![image](https://cloud.githubusercontent.com/assets/679486/18209694/1ad95e62-70f2-11e6-93cf-b52d1faefc90.png)

Their rendering looks the same:
![image](https://cloud.githubusercontent.com/assets/679486/18209718/33342f82-70f2-11e6-8616-3d0a2d6c0767.png)

![image](https://cloud.githubusercontent.com/assets/679486/18209731/44e6b830-70f2-11e6-8b05-47d9a4b3712d.png)

Sanity check with blue to make sure I'm using the new path:
![image](https://cloud.githubusercontent.com/assets/679486/18209747/599c3b60-70f2-11e6-88d4-efa8e47ec3cf.png)

All looks good, I'll commit shortly.

**Comment by samreid** [comment]
Fixed as recommended, @pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
👍 Closing.
