### ISSUE TITLE
use fontawesome 'refresh' icon for RefreshButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#269]
Noted while working on https://github.com/phetsims/unit-rates/issues/123.

Fontawesome has a 'refresh' icon.  RefreshButton doesn't use it, and instead implements its own icon that is almost identical - except that the arrows go in the opposite direction (counterclockwise, instead of clockwise). 

RefreshButton:

![screenshot_40](https://cloud.githubusercontent.com/assets/3046552/19131595/3cc384aa-8b0d-11e6-9d09-0d84f3866d98.png)

Fontawesome:

![screenshot_39](https://cloud.githubusercontent.com/assets/3046552/19131602/4026283c-8b0d-11e6-8520-b50ceda910d1.png)

Recommended to switch to FontAwesomeNode. We'll need to import the SVG data for fa-refresh (see http://fontawesome.io/icon/refresh/).

**Comment by pixelzoom** [comment]
Labeling for developer meeting, since changing to fontawesome 'refresh' will change the direction of the arrows for all sims that use RefreshButton.

**Comment by pixelzoom** [comment]
10/6/16 dev meeting: I will change RefreshButton to extend FontAwesomeNode( 'refresh' ).

**Comment by pixelzoom** [comment]
Assigning to @jbphet to review.  RefreshButton was sparsely used, with little standardization other than the icon. So I simply deleted it and replaced occurrences with `RectangularPushButton( { content: FontAwesomeNode( 'refresh' ), ... } )`. If you feel that having a first-class RefreshButton is generally useful, feel free to create one.

**Comment by jbphet** [comment]
Changes look fine to me.  Assigning to @ariel-phet to decide if he's okay not having a 'standard' refresh button, since I seem to remember spending some time discussing this in design meetings at one point.

**Comment by ariel-phet** [comment]
I think this is fine as a change in terms of not having a "standard" refresh button (we will certainly use the standard icon) but the actual function of the refresh button has been a bit sim specific.
