### ISSUE TITLE
factor out common button color

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#270]
This color is duplicated in 5 places:

``` js
new Color( 242, 233, 22 )
```

And documented in various ways, all of which indicate that it's dependent on the PhET logo:

``` js
// BackButton.js
      // Default base code matches the yellow in the PhET logo (the one with the paper airplane).
      baseColor: new Color( 242, 233, 22 )

// RefreshButton.js
     baseColor: new Color( 242, 233, 22 )//Color match with the yellow in the PhET logo
```

This color should be in PhetColorScheme.

**Comment by pixelzoom** [comment]
Assigning to @samreid since he appears to have created (or at least documented) the duplication.

**Comment by pixelzoom** [comment]
I see this color in 2 other places, expressed in hex format.  In EraserButton and PaperAirplaneNode:

```js
fill: '#F2E916'
```

**Comment by pixelzoom** [comment]
... and there may be others. Recommended to also look in vegas and sun.

**Comment by samreid** [comment]
I see 10 occurrences of `242, 233, 22` and 16 occurrences of `F2E916`.

**Comment by samreid** [comment]
I updated make-a-ten above.  Pinging @jonathanolson so he can pull/merge.  I tested in the game, and made sure lint is passing.

**Comment by samreid** [comment]
In the above commits, I factored out the numeric form in about 10 places.  For each sim, I tested lint and runtime in requirejs mode.  I also threw in some lint fixes for griddle (not sure how those sneaked in).  Next up should be `F2E916`.

**Comment by samreid** [comment]
In the above commits, I factored out the `F2E916` occurrences.  I tested by grunting and launching every sim, though I did not play all the way through an arithmetic level.

@pixelzoom would you like to review?  Should we add a note to the code review doc to check for this in the future?

**Comment by samreid** [comment]
> Should we add a note to the code review doc to check for this in the future?

Or a lint rule?

**Comment by pixelzoom** [comment]
I don't think we should have a lint rule for a specific color.  We could have a lint rule that looks for color literals that correspond to colors in PhetColorScheme.  But due to the number of ways of expressing colors (Color, string, RGB, RGBA, hex,...) that seems like a lot of work for dubious benefits.

I'm also not sure if this should be specifically called out in the code review or developer guidelines. "Don't copy and paste literals" should be a best practice that all good developers follow.

**Comment by samreid** [comment]
Sounds good, anything else to do here?

**Comment by pixelzoom** [comment]
Nope. Closing.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/joist/issues/158, it sounds like we need a PhetColorScheme constant for other both the yellow and blue in the PhET logo.  So I've renamed PHET_YELLOW to PHET_LOGO_YELLOW, in anticipation of adding PhET_LOGO_BLUE.

**Comment by pixelzoom** [comment]
Reopening.

@samreid where did you get this value for yellow in the PhET logo?

```js
var PHET_LOGO_YELLOW = new Color( 242, 233, 22 );
```

Looking at brand/phet/images/logo.png and phet-cafepress/webite-assets/phet-logo-registered.svg, I see 'rgb( 254, 225, 5 )'.

**Comment by pixelzoom** [comment]
The official PhET logo file is apparently brand/phet/assets/phet-brand-assets.ai.  Inspecting that file confirms that the logo colors are:

yellow = 'rgb( 254, 225, 5 )'
blue = 'rgb( 106, 206, 245 )'

**Comment by pixelzoom** [comment]
PHET_LOGO_YELLOW changed to Color( 254, 225, 5 ) in above commit.

Here's what the change looks like in the context of the "Start Over" button in the Game screen of area-builder.

Incorrect color (  242, 233, 22 ):

![screenshot_83](https://cloud.githubusercontent.com/assets/3046552/20722794/35288d74-b625-11e6-97a7-a5d6e751fa72.png)

Correct color ( 254, 225, 5 ):

![screenshot_84](https://cloud.githubusercontent.com/assets/3046552/20722787/30853bc8-b625-11e6-9e54-219b7b38a259.png)

The correct color is very close, slightly brighter.  So I don't think this will negatively impact any sims. 

@samreid Please review.

**Comment by samreid** [comment]
Looks good, thanks!
