### ISSUE TITLE
NumberKeypad: API provides no way to get a 'number'

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#273]
Line 39:

```js
digitStringProperty: new Property( '' ) // create a digit string property or use the one supplied by the client
```

So I can't get a number from NumberKeypad?... This makes no sense to me. What is the rationale for providing the number as a string?

**Comment by jbphet** [comment]
```digitStringProperty``` changes as the user enters digits so that clients can know and display exactly what the user has entered.  If it were a number property instead, and the user entered, say, 3.40001, there would be no change in the number property's value for each of the zeros entered until the 1 was entered.

**Comment by pixelzoom** [comment]
How does that preclude also offering the value as a number?

**Comment by jbphet** [comment]
@pixelzoom asked

> What is the rationale for providing the number as a string?

That was answered in https://github.com/phetsims/scenery-phet/issues/273#issuecomment-257903922.

...then...

> How does that preclude also offering the value as a number?

It doesn't, and adding an API to retrieve the value as a number would be fine with me.

**Comment by pixelzoom** [comment]
Not going to bother with this. I did rename `digitStringProperty` to `valueStringProperty` because a number consists of other things than "digits" (e.g. sign, decimal point,...)
