### ISSUE TITLE
NumberKeypad: add support for negative numbers

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#274]
Hard to believe that there's no support for entering negative numbers. But they are going to be needed by area-model-multiplication.

**Comment by pixelzoom** [comment]
At 11/10/16 design meeting, we identified that we need to add a '+/-' key, like this:

![screenshot_68](https://cloud.githubusercontent.com/assets/3046552/20329097/80d25714-ab53-11e6-9553-adfbb533b434.png)

Now where to add it?

With all current keys enabled, the keypad currently looks like this:

![screenshot_69](https://cloud.githubusercontent.com/assets/3046552/20329128/b0289460-ab53-11e6-8c0c-06d4b558fcb1.png)

**Comment by amanda-phet** [comment]
It should also be specified that the button can be pressed *before* typing a number as well as *after*. 

While the submit/enter button is separate from the keypad, I find it hard to come up with a scenario where we won't have a button like that. This is what I imagined happening: 
![screen shot 2016-11-16 at 5 32 31 pm](https://cloud.githubusercontent.com/assets/7852916/20371542/c864da3c-ac22-11e6-9af6-72252aee200b.png)

**Comment by pixelzoom** [comment]
The decimal and sign buttons are both optional.  The above shows the layout for decimal=true, sign=true.

Please show desired layouts for:

• decimal=true, sign=false
• decimal=false, sign=true
• decimal=false, sign=false

**Comment by pixelzoom** [comment]
Oh, wait... The Enter button is *not* part of the keypad.  So including it in the layout is problematic.

**Comment by pixelzoom** [comment]
@jbphet would like your input on this issue.

**Comment by amanda-phet** [comment]
![screen shot 2016-11-17 at 11 11 15 am](https://cloud.githubusercontent.com/assets/7852916/20401574/99e73f30-acb6-11e6-8554-3f778a4f556b.png)

**Comment by pixelzoom** [comment]
And decimal=true, sign=true is this?

![screenshot_232](https://cloud.githubusercontent.com/assets/3046552/20402175/e62349f0-acb8-11e6-838b-c302724cb4f9.png)

**Comment by amanda-phet** [comment]
I'm not sure... If NOT having a submit button is a possibility then I'd want to come up with an alternative that looks better than this. Perhaps something along these lines:

![screen shot 2016-11-17 at 11 32 55 am](https://cloud.githubusercontent.com/assets/7852916/20402359/9cf272dc-acb9-11e6-986d-a5a3199032e2.png)

**Comment by jbphet** [comment]
I think the layout with the "Enter" key in https://github.com/phetsims/scenery-phet/issues/274#issuecomment-261118157 looks pretty decent, better than the layout just above.  I suspect that this isn't the only request that we will get to support an Enter key, even though we haven't needed one thus far.  If that is what is needed, we should consider adding it.

If we do need to support Enter, I feel like this would push us towards the architecture where the keypad only reports what button was pressed, and the logic for making a string/number out it would be external.  That way the handler code could have an "onSubmit" function and we wouldn't have to worry about adding such a thing to the keypad code.  Just feels like a nice "separation of concerns" sort of thing to me.

**Comment by pixelzoom** [comment]
Adding @jonathanolson to this discussion. When he and I discussed NumberEntryControl, he had some good arguments for why an Enter key should not be included.  See https://github.com/phetsims/scenery-phet/issues/271#issuecomment-257379394.

**Comment by jbphet** [comment]
Assigning to @aadish to address during the implementation of the new keypad.

**Comment by pixelzoom** [comment]
The new Keypad has support for negative numbers (KeyID.PLUS_MINUS), and new development should be using Keypad instead of NumberKeypad.  So perhaps we can close this issue as "won't fix".  @jbphet do you agree?

**Comment by jbphet** [comment]
Agreed - since `NumberKeypad` has been deprecated, and `Keypad` supports negative numbers, this one should be closed.  I've marked it with the label that indicates that this won't be fixed.
