### ISSUE TITLE
NumberKeypad: can't enter 0 before decimal place

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#275]
Unit Rates expresses displays currency as dollars and cents (e.g.) '$0.25'.  But it's impossible to enter the leading zero in NumberKeypad.  As soon as you enter the decimal point, the zero is erased (e.g. '.25'). 

@jbphet Is this a bug or a feature?

**Comment by pixelzoom** [comment]
If I change the behavior of this to allow 1 leading 0 before the decimal place, are there any sims that it will break?

**Comment by jbphet** [comment]
I'd say it's a bug.  If I recall correctly, leading zeros are intentionally removed from integers, and perhaps the same code is kicking in (inappropriately) for the decimal point.  I have only used this control in simulations where a decimal point wasn't needed, so functionality related to the decimal point has likely had little to no testing and refinement.

**Comment by jbphet** [comment]
I'm not aware of any sims that will be broken by allowing a leading zero in front of the decimal place.  Sounds like the right thing to do to me.

**Comment by pixelzoom** [comment]
Fixed. @jbphet please review.

**Comment by jbphet** [comment]
The commit above didn't look quite right to me, but it looks like the problem I noticed was fixed in https://github.com/phetsims/scenery-phet/commit/b4a0e3df8adb8cf082ccebda4cfb40fae3b29800.

**Comment by jbphet** [comment]
The commits look good and I did a quick regression test on Arithmetic and Area Builder and saw no problems.  These two sims don't make use of decimal points, so I also did a bit of testing on Unit Rates, and saw no problems there either.  Closing.
