### ISSUE TITLE
ColorProfile issues

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#277]
Encountered while working on https://github.com/phetsims/scenery-phet/issues/276 (conversion to PropertySet) ...

(1) Incorrect documentation for `@param {Array.<Color|string>} colors` in ColorProfile constructor.

(2) Inappropriate use of inheritance in `GravityAndOrbitsColorProfile` and `StatesOfMatterColorProfile`.

**Comment by pixelzoom** [comment]
@jessegreenberg please review GOA.
@jbphet please review SOM.
Whoever reviews last, please close this issue.

**Comment by jbphet** [comment]
Changes for SOM look good, and I tested the projector mode, which is the main use case for this color profile so far.  Everything worked correctly.

**Comment by pixelzoom** [comment]
@jessegreenberg ping.

**Comment by pixelzoom** [comment]
@jessegreenberg ping again.

**Comment by jessegreenberg** [comment]
Very sorry I took so long.  I reviewed the change and it is an improvement in GAO.  I tested the projector mode option and it works great.  Closing.
