### ISSUE TITLE
[branch] dag-movable-drag-handler

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/scenery-phet#285]
For testing an improvement to MovableDragHandler that doesn't error (like https://github.com/phetsims/energy-forms-and-changes/issues/31) on things with a DAG nature, at least when targetNode isn't provided.

**Comment by jonathanolson** [comment]
Commit is https://github.com/phetsims/scenery-phet/commit/8f3aeba8b70e6306a0e2a72de97cbe709ab8f01f.

@pixelzoom, can you review this to see if this would potentially cause any drag problems?

Essentially, globalToParentPoint will fail on something with a DAG. Instead of using that, we can get the provided trail and use that instead (as long as a targetNode is not provided).

**Comment by jonathanolson** [comment]
Investigating automated testing failure in bending-light, I'll probably have another patch:

```
TypeError: Cannot read property 'globalToParentPoint' of undefined
    at MovableDragHandler.movableDragHandlerStart (http://localhost:8080/scenery-phet/js/input/MovableDragHandler.js?bust=1480458579604:57:72)
    at MovableDragHandler.handleForwardedStartEvent (http://localhost:8080/scenery-phet/js/input/MovableDragHandler.js?bust=1480458579604:139:12)
    at start (http://localhost:8080/bending-light/js/common/view/ToolIconListener.js?bust=1480458579604:28:27)
    at ToolIconListener.startDrag (http://localhost:8080/scenery/js/input/SimpleDragHandler.js?bust=1480458579604:152:28)
    at ToolIconListener.tryToSnag (http://localhost:8080/scenery/js/input/SimpleDragHandler.js?bust=1480458579604:178:14)
    at ToolIconListener.down (http://localhost:8080/scenery/js/input/SimpleDragHandler.js?bust=1480458579604:195:12)
    at Input.dispatchToTargets (http://localhost:8080/scenery/js/input/Input.js?bust=1480458579604:846:31)
    at Input.dispatchEvent (http://localhost:8080/scenery/js/input/Input.js?bust=1480458579604:788:14)
    at Input.downEvent (http://localhost:8080/scenery/js/input/Input.js?bust=1480458579604:672:14)
    at Input.mouseDown (http://localhost:8080/scenery/js/input/Input.js?bust=1480458579604:315:14)
```

**Comment by jonathanolson** [comment]
Bending Light was doing some crazy forwarding of events (that should probably be changed in the future, I saw "HACK" in all caps).

Fixed in above commit and https://github.com/phetsims/bending-light/commit/21c0e1135c4773ed00ef9d105a85e10320b2cec3.

**Comment by pixelzoom** [comment]
@jonathanolson asked:
> @pixelzoom, can you review this to see if this would potentially cause any drag problems?

I'll try to get to this during 12/1/16 meetings. If I don't, then it may be awhile before I get to this.

**Comment by pixelzoom** [comment]
(1) I found this to be a little confusing and a bit of an anti-pattern:

```( options.targetNode ? options.targetNode : trail ).globalToParentPoint```

In one case `globalToParentPoint` is called to a Node, in the other case for a Trail. And it works because the `globalToParentPoint` API is identical for Node and Trail types.

(2) Should the `trail` argument be passed to these function calls?

```js
55  options.startDrag( event );
70 options.onDrag( event );
75 options.endDrag( event );
```

**Comment by pixelzoom** [comment]
Back to @jonathanolson's question:
> @pixelzoom, can you review this to see if this would potentially cause any drag problems?

If `trail.globalToParentPoint` is guaranteed to be equivalent to `event.currentTarget`, then it shouldn't cause any problems.  But I seem to recall running into an situation recently where event and trail provided different results.

**Comment by pixelzoom** [comment]
(1) I found this to be a little confusing and a bit of an anti-pattern:

```( options.targetNode ? options.targetNode : trail ).globalToParentPoint```

In one case `globalToParentPoint` is called to a Node, in the other case for a Trail. And it works because the `globalToParentPoint` API is identical for Node and Trail types.  Any reason why you didn't use `event.currentTarget`?  E.g.:

```( options.targetNode ? options.targetNode : event.currentTarget ).globalToParentPoint```

(2) Should the `trail` argument that was added be passed to these function calls?

```js
55 options.startDrag( event );
70 options.onDrag( event );
75 options.endDrag( event );
``` 

(3) Will this cause problems?

Looks correct, but difficult to say with certainty.  If you used `event.currentTarget` instead of `trail`, then I'd be more confident that behavior would be unchanged for clients that didn't provide `options.targetNode`.   If you use `trail` --  I seem to recall running into an situation recently where `event` and `trail` provided different results.

**Comment by jonathanolson** [comment]
For (1) and (2), it is critical that a Trail is used, since the node itself does not have a unique trail (thus the error and workaround). Trail would ideally ONLY be used (never calling globalToParentPoint), but I'm really not sure about how ```options.targetNode``` is used. Can't use ```event.currentTarget``` since it's not a Trail.

> Should the trail argument that was added be passed to these function calls?

I'd say definitely yes.

> If you use trail -- I seem to recall running into an situation recently where event and trail provided different results.

Yes, and that's the case here (SimpleDragHandler does NOT provide the full Trail to what was actually picked, but provides the possibly-shortened trail up to the currentTarget):

```js
this.trail = event.trail.subtrailTo( event.currentTarget, true );
// ...
this.options.start.call( null, event, this.trail );
```

**Comment by pixelzoom** [comment]
Unless you can think of some way to robustly test before merging... I'd say go ahead and merge into master and we'll catch anything that breaks in testing.

**Comment by jonathanolson** [comment]
Merged, will notify team on Skype about the chance of things breaking and where to report (here).
