### ISSUE TITLE
NumberPicker's color/pressedColor are not mutable

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/scenery-phet#287]
Having mutable colors would help proportion-playground a lot (in one place, duplicate overlapping pickers of different colors are used, and swapped between).

@pixelzoom, any thoughts about this potential refactoring?

**Comment by pixelzoom** [comment]
Looks like this is mainly useful for the "paint bucket" scene on the "Explore" screen, where there's a "Black & White" checkbox.  Is that correct?

**Comment by jonathanolson** [comment]
Correct.

Current code for the workaround:
```js
      if ( color instanceof Array ) {
        var pickers = color.map( function( singleColor ) {
          return createPicker( property, range, singleColor, label, pickerOptions );
        } );
        // Only show the picker that should be visible
        options.pickerColorProperty.link( function( showSecond ) {
          pickers[ 0 ].visible = !showSecond;
          pickers[ 1 ].visible = showSecond;
        } );
        return new Node( {
          children: pickers
        } );
      }
      else {
        return createPicker( property, range, color, label, pickerOptions );
      }
```

It doesn't seem terribly complicated, so it may be best to not tackle the common-code changes right now.

**Comment by pixelzoom** [comment]
> It doesn't seem terribly complicated, so it may be best to not tackle the common-code changes right now.

That's my feeling too.  The payoff doesn't seem to be worth the effort.

You could also try to sell the design team on the idea of having a "B&W paint can" (an additional scene) instead of an option in the "paint can" scene.  Depending on whether it's important to switch between B&W vs color for the same spinner values.

**Comment by jonathanolson** [comment]
> That's my feeling too. The payoff doesn't seem to be worth the effort.

Agreed, will close. If I run into this again, I may tackle it then.

> You could also try to sell the design team on the idea of having a "B&W paint can" (an additional scene) instead of an option in the "color paint can" scene. Depending on whether it's important to switch between B&W vs color for the same spinner values...

I think it's beneficial, and we might get a 3rd color scheme in the future.

**Comment by jonathanolson** [comment]
Had a need for this, reopening.

**Comment by jonathanolson** [comment]
With https://github.com/phetsims/scenery/issues/612 implemented, this was fairly trivial to implement. Only complicated thing is the need to create a derived property to handle the `darker()` property, and to dispose of that property if it is created.

@pixelzoom, would you like to review?

**Comment by jonathanolson** [comment]
Notably, https://github.com/phetsims/area-model-common/issues/59 needs to have the color change while pressing down, so the previous strategy was a no-go.

**Comment by pixelzoom** [comment]
I won't get to this until Monday 6/19 at the earliest.

**Comment by pixelzoom** [comment]
I seem to recall that we (the dev group) decided to generally avoid polymorphic parameters and options.  But polymorphism is the basis for the solution here, i.e.:

```js
49 color: new Color( 0, 0, 255 ), // {Color|string|Property.<Color|string>} color of arrows, and top/bottom gradient on pointer over
50 backgroundColor: 'white', // {Color|string|Property.<Color|string>} color of the background when pointer is not over it
```

And results in conditional code like this:

```js
if ( options.color instanceof Property ) {
```

I also see that this pattern has been pushed all the way down into `scenery.Gradient`:

```js
70      assert && assert( color === null ||
                        typeof color === 'string' ||
                        color instanceof Color ||
                        ( color instanceof Property && ( color.value === null ||
                                                         typeof color.value === 'string' ||
                                                         color.value instanceof Color ) ),
```

Should we discuss this with other developers?...

**Comment by jonathanolson** [comment]
The alternative would be to do things like:
```js
new Path( {
  fill: Paint.createFromString( 'red' ),
  stroke: Paint.NO_PAINT // null
} );
```
where everything now needs to create wrapper objects.

It would technically simplify documentation, at the (in my opinion unneeded) verbosity in client usage.

**Comment by pixelzoom** [comment]
I think that some things, like `{Color|string}` are fine.  And could get used to `{Color|string|Property.<Color|string>}`.   I'm just a little concerned about going down the slippery slope where many things in scenery (and other APIs) become `{type|Property.<type>}`, and the parameter/option names don't tell you which ones support this.

**Comment by samreid** [comment]
We previously investigated `type|Property.<type>` elsewhere in scenery (though I can't recall where) and it seemed like it worked great, hence @jonathanolson informed us he was going to investigate the same strategy for colors.

**Comment by jonathanolson** [comment]
> Is polymorphism part of the approach that you had in mind for addressing phetsims/sun#290 (Mutability of view nodes)?

For colors, yes (since you can generally pass those directly to Scenery, unless you need to make lighter/darker copies).

For other things, having explicit properties seems better.

**Comment by pixelzoom** [comment]
> For other things, having explicit properties seems better.

Assuming that you're referring to Properties and not properties...

Why is it better to use polymorphism for colors and explicit Properties for other things?  

E.g., why not use polymorphism for lineWidth, like this? :

```js
var line1 = new Line( {
  lineWidth: 2
} );

var line 2 = new Line( {
  lineWidth: new Property( 1 )
} );
```

**Comment by jonathanolson** [comment]
Color Property support hit ~20 months ago (https://github.com/phetsims/scenery/issues/471), and I recently fixed the gap in support for this with gradients (https://github.com/phetsims/scenery/issues/612).

> I'm just a little concerned about going down the slippery slope where many things in scenery (and other APIs) become {type|Property.<type>}, and the parameter/option names don't tell you which ones support this.

I believe this is exclusive to color-like things (fills/strokes) for now. If I wanted to go down a path of more things being supported, I'd want EVERY Scenery parameter to support it. No current plans, but I've noticed a slight desire to be able to do this for visibility.

For Colors in common code, I'd prefer having methods that factor out lighter/darker changes properly.

**Comment by pixelzoom** [comment]
@samreid said:
> ...  @jonathanolson informed us he was going to investigate the same strategy for colors.

Sorry, I must have missed that.  

If we can get one other developer to sign off on polymorphism, I'm OK with closing this issue.

**Comment by jonathanolson** [comment]
> Why is it better to use polymorphism for colors and explicit Properties for other things?

Colors were the predominant Property type you'd want to pass things in, it hasn't come up as much for others?

But as far as Scenery is concerned, being able to pass in Properties could also be quite helpful.

**Comment by jonathanolson** [comment]
> @jonathanolson informed us he was going to investigate the same strategy for colors.

https://github.com/phetsims/scenery-phet/issues/156#issuecomment-144763766 and the comments below I believe is the main discussion for this initial approach.

**Comment by jonathanolson** [comment]
> Why is it better to use polymorphism for colors and explicit Properties for other things?

An argument against this is the effort it took Scenery-side. Since the Color type is mutable (not used too often), to handle a `{Property.<Color|string>}` that itself is mutable requires listeners to handle three different ways to change it:

- Change the fill itself (new `{Property.<Color|string>}`)
- Change the value of the `{Property}`
- Change the color values of the Color.

**Comment by pixelzoom** [comment]
@jonathanolson said:
> #156 (comment) and the comments below I believe is the main discussion for this initial approach.

Can you point me to where polymorphism is discussed in this issue? I don't see it, perhaps I missed it.

**Comment by jessegreenberg** [comment]
> I believe this is exclusive to color-like things (fills/strokes) for now. If I wanted to go down a path of more things being supported, I'd want EVERY Scenery parameter to support it.

This seems reasonable to me, and makes it clear what does/doesn't support ```type|Property.<type>```.

**Comment by jonathanolson** [comment]
> Can you point me to where polymorphism is discussed in this issue? I don't see it, perhaps I missed it.

Sorry, it looks like there was basically no discussion on it there. There may have been some discussion in person, as I seem to have created the color-property issue ~11 minutes after your dev notes on the subject were posted.

**Comment by pixelzoom** [comment]
@jessegreenberg said:
> This seems reasonable to me, and makes it clear what does/doesn't support `type|Property.<type>`.

It makes it clear only if every parameter and option that is a color supports polymorphism.

**Comment by jonathanolson** [comment]
One thing about our current polymorphism+documentation combination is not having a "shortcut" way to specify something that can be passed to a fill or stroke. Currently the type documentation (pulled from setFill) is `{null|string|Color|Property.<string|Color>|LinearGradient|RadialGradient|Pattern}`.

Having to place that everywhere any parameter should be a fill/stroke is unfortunate.

**Comment by jessegreenberg** [comment]
> It makes it clear only if every parameter and option that is a color supports polymorphism.

Agreed, and I think that is the plan for Scenery color now, correct?  Now that ```scenery.Gradient``` accepts color Properties, are there any remaining color options in Scenery that still don't support polymorphism?

**Comment by zepumph** [comment]
>Currently the type documentation (pulled from setFill) is `{null|string|Color|Property.<string|Color>|LinearGradient|RadialGradient|Pattern}`.

That is a bummer, is there anyway with jsdoc to say "See setFill for types?"

**Comment by jbphet** [comment]
Here's a take on pros and cons:

Pros:
+ The pattern has been extremely useful in the places we've used it so far, such as implementing color schemes using Properties

Cons:
+ Library code is complicated by having to do a bunch of type checking
+ Library code will likely be inconsistent, with some options supporting ````type|Property.<type>``` and some not, which makes it harder to ramp up on correct usage of the library
+ Documentation can be verbose
+ Keeping the documentation up to date and trustworthy is hard, and there will likely be times and places were we don't do it

Even though the cons outnumber the pros, I still like the pattern so much that I'm okay with it.  We should just be aware of the cost and should work hard to have correct documentation and good `assert` statements so that we devs can figure the problem out quickly if we try to use a Property-wrapped value for an unsupported option.

By the way, @jonathanolson said
> I believe this is exclusive to color-like things (fills/strokes) for now.

I can think of a non-color case that would be useful right now.  In Gene Expression Essentials was have a lot of shapes that morph over time.  If Path supported ```Shape|Property<Shape>```, it would save a lot of effort and be entirely awesome.  In other words, we will definitely find situations where this pattern will be useful for the future, so we should have a general consensus on whether or not it's okay (which seems to be what we are concluding) and, if so, how to use, document, and check it consistently.

**Comment by pixelzoom** [comment]
We have a quorum to proceed with polymorphic parameters and options, so review of NumberPicker gets a 👍.   

Back to @jonathanolson in case there's anything else to do here.

**Comment by jonathanolson** [comment]
Noted fill/stroke type documentation for discussion in https://github.com/phetsims/scenery/issues/631.

**Comment by jonathanolson** [comment]
Noted accepting Properties as values in https://github.com/phetsims/scenery/issues/632. If anyone feels like this should be proposed for implementation, then please comment there.

**Comment by jonathanolson** [comment]
> Back to @jonathanolson in case there's anything else to do here.

I think this issue is complete, thanks!
