### ISSUE TITLE
General icons for keyboard keys

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#288]
From #https://github.com/phetsims/john-travoltage/issues/142

There are icons for keyboard keys in john-travoltage that look like
![capture](https://cloud.githubusercontent.com/assets/6396244/21861641/eb3cedaa-d7f2-11e6-8522-a13e48b9f135.PNG)

They will eventually be used in multiple sims and should be moved to scenery-phet.

**Comment by jessegreenberg** [comment]
Moved to scenery-phet.  In ComponentsView, I added an example for a partial keyboard:
![capture](https://cloud.githubusercontent.com/assets/6396244/21874439/230b89a0-d832-11e6-9dc6-348b2842ccba.PNG)

I also created types for common keys (TabKeyNode, ShiftKeyNode, EnterKeyNode) so strings for these keys don't need to be included in the sim.

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/john-travoltage/issues/145, @jonathanolson had this review comment:

I'd typically opt for a non-branching pattern in this case:
```js
// outside constructor
var DIRECTION_ANGLES = {
  up: 0,
  down: Math.PI,
  left: -Math.PI / 2,
  right: Math.PI / 2
};

// in constructor
assert && assert( DIRECTION_ANGLES[ direction ] !== undefined, 'Some description' ); // if desired for checking
```

```js
// in pathOptions
{
  // ...
  rotation: DIRECTION_ANGLES[ direction ],
  // ...
}
```
I'd also typically inline pathOptions since it's only used once:

```js
var arrowPath = new Path( arrowShape, {
  fill: arrowFill,
  stroke: arrowStroke,
  lineJoin: arrowLineJoin,
  lineWidth: arrowLineWidth,
  rotation: DIRECTION_ANGLES[ direction ]
} );
```

**Comment by jessegreenberg** [comment]
@jonathanolson the key nodes were moved from john-travoltage to scenery-phet.  Would you like to review further or can this be closed?

**Comment by jonathanolson** [comment]
Briefly reviewed, looks good. Closing.
