### ISSUE TITLE
change API for NumberPicker options upFunction and downFunction

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#292]
I ran into this while working on https://github.com/phetsims/unit-rates/issues/163...

`NumberPicker` currently has these options, which control how the up and down buttons compute the next value, where `valueProperty` is a constructor parameter:

```js
50 upFunction: function() { return valueProperty.get() + 1; },
51 downFunction: function() { return valueProperty.get() - 1; },
```

Rather than requiring access to `valueProperty`, methinks that these functions should be passed `value`, like this:

```js
50 upFunction: function( value ) { return value + 1; },
51 downFunction: function( value ) { return value - 1; },
```

There are currently only 3 clients that use this feature.  And since this involves adding a function parameter, it won't break any existing clients.  

An (optional?) task would be to clean up existing client code,  like this in `function-builder.FBNumberPicker`:

```js
    options.upFunction = function() {
      var value = valueProperty.get() + 1;
      if ( value === 0 && options.skipZero ) {
        value++;
      }
      assert && assert( !( options.skipZero && value === 0 ), 'programming error, zero should be skipped' );
      return value;
    };

 options.downFunction = function() {
      var value = valueProperty.get() - 1;
      if ( value === 0 && options.skipZero ) {
        value--;
      }
      assert && assert( !( options.skipZero && value === 0 ), 'programming error, zero should be skipped' );
      return value;
    };
```

... and this in `gravity-force-lab-basics.MassControl`:

```js
      upFunction: function() { return massProperty.get() + GravityForceLabBasicsConstants.BILLION_MULTIPLIER; },
      downFunction: function() { return massProperty.get() - GravityForceLabBasicsConstants.BILLION_MULTIPLIER; },
```

**Comment by pixelzoom** [comment]
The 3rd use is in `graphing-lines.CoordinatePicker`:

```js
    // computes value when 'up' button is pressed
    options.upFunction = function() {
      var x1New = a1.get() + 1;
      if ( x1New === a2.get() && b1.get() === b2.get() ) { // will points be the same?
        x1New++;
        if ( x1New > range.get().max ) { // did we skip too far?
          x1New = a1.get();
        }
      }
      return x1New;
    };

    // computes value when 'down' button is pressed
    options.downFunction = function() {
      var x1New = a1.get() - 1;
      if ( x1New === a2.get() && b1.get() === b2.get() ) { // will points be the same?
        x1New--;
        if ( x1New < range.get().min ) { // did we skip too far?
          x1New = a1.get();
        }
      }
      return x1New;
    };
```

This could certainly take advantage of the `value` parameter, but would continue to require access to other constructor args.

**Comment by pixelzoom** [comment]
API and client usages changed, as described above. I tested all sims that were modified.  

And the lucky sim developer who gets to review this issue is:

```
> _.shuffle( [ 'JB', 'JG', 'JO', 'SR' ] )[0]
"JG"
```

... @jessegreenberg !

**Comment by jessegreenberg** [comment]
Looks great to me, thanks!  I spotted one more client usage in ```graphing-lines.SlopePicker```.  I also tested the other sims mentioned above that were modified. Closing.

**Comment by pixelzoom** [comment]
Reopening. I want to update that usage in `SlopePicker`.

**Comment by jessegreenberg** [comment]
@pixelzoom sorry, should have clarified that I did update it in https://github.com/phetsims/graphing-lines/commit/cdb43fd3df5ef328e2ad7919e4fa71aea6917276, unless you notice something else that needs to be updated.

**Comment by pixelzoom** [comment]
Got it, looks good. Thanks! Closing.
