### ISSUE TITLE
NumberAccumulator: parseFloat called with radix argument

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#293]
In NumberAccumulator:

```js
172 returnValue = parseFloat( stringValue.replace( NEGATIVE_CHAR, '-' ).replace( DECIMAL_CHAR, '.' ), 10 );
```

`parseFloat` does not take a radix argument. You are likely confusing it with `parseInt`.

**Comment by aadish** [comment]
@pixelzoom thanks for pointing this out, fixed by above commit
