### ISSUE TITLE
GaugeNode should have optional ticksize

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#295]
The GaugeNode doesn't allow one to specify size of ticks through options, so it doesn't look very good when it is a small size.
![capture](https://cloud.githubusercontent.com/assets/6396244/24266150/671b15cc-0fcb-11e7-8ebe-081e013da81b.PNG)

The size label for the GaugeNode is scaled as a function of the radius:
```js
maxWidth: options.radius * 1.3,
```
I am not sure if the label will need to be scaled down either for very small GaugeNodes.

**Comment by jessegreenberg** [comment]
Also the tick line width.

**Comment by jessegreenberg** [comment]
From https://github.com/phetsims/forces-and-motion-basics/issues/220#issuecomment-288823497

**Comment by jessegreenberg** [comment]
There are now options for 
```js
      majorTickLength: 10,
      minorTickLength: 5,
      majorTickLineWidth: 2,
      minorTickLineWidth: 1,

      // defines max width of the label, relative to the radius
      maxLabelWidthScale: 1.3, 
```

@jbphet would you mind reviewing, just since you are listed as an author?

**Comment by jbphet** [comment]
Looks good to me, sorry it took so long for me to review.  Closing.
