### ISSUE TITLE
NumberPicker value maxWidth

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/scenery-phet#297]
The current maxWidth is generated based on the largest of the formatted min/max values.

Unfortunately, string tests (when used with formatText to add a dollar sign) make this very large.

Any objections to NumberPicker supporting a valueMaxWidth that caps the actual maxWidth used, or overrides it?

**Comment by pixelzoom** [comment]
No objection.

**Comment by jonathanolson** [comment]
Implemented, feel free to review if you have time.

I had to actually apply the maxWidth after checking the height for the background, so that it didn't shrink the picker vertically (having pickers of different heights looks bad).

**Comment by pixelzoom** [comment]
Inspected commit, tested a couple of sims, looks good to me. Closing.
