### ISSUE TITLE
RichText: support for rich text with HTML-style tags

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#300]
@jonathanolson created RichText, motivated by XSS problems (see https://github.com/phetsims/chains/issues/3#issuecomment-291927666).  It has a dependency on himalaya (3rd-party lib), so it currently lives in scenery-phet.

@jonathanolson said in https://github.com/phetsims/chains/issues/3#issuecomment-292111091:

Documentation on RichText (for discussion during developer meeting):

Displays rich text with HTML-style tags by splitting it into multiple (child) Text nodes.

It should be a close to drop-in replacement for SubSupText, and supports the following markup and features:
- `<b>` and `<strong>` for bold text
- `<i>` and `<em>` for italic text
- `<sub>` and `<sup>` for subscripts / superscripts
- `<u>` for underlined text
- `<s>` for strikethrough text
- `<font>` tags with attributes color="cssString", face="familyString", size="cssSize"
- `<span>` tags with a dir="ltr" / dir="rtl" attribute
- Unicode bidirectional marks (present in PhET strings) for full RTL support

Examples from the scenery-phet demo:

- `new RichText( 'RichText can have <b>bold</b> and <i>italic</i> text.' ),`
- `new RichText( 'Can do H<sub>2</sub>O (A<sub>sub</sub> and A<sup>sup</sup>), or nesting: x<sup>2<sup>2</sup></sup>' ),`
- `new RichText( 'Additionally: <font color="blue">color</font>, <font size="30px">sizes</font>, <font face="serif">faces</font>, <s>strikethrough</s>, and <u>underline</u>' ),`
- `new RichText( 'These <b><em>can</em> <u><font color="red">be</font> mixed<sup>1</sup></u></b>.' ),`
- `new RichText( '\u202aHandles bidirectional text: \u202b<font color="#0a0">مقابض</font> النص ثنائي <b>الاتجاه</b><sub>2</sub>\u202c\u202c' )`

**Comment by pixelzoom** [comment]
This is tagged for developer meeting because @jonathanolson would like feedback.

**Comment by pixelzoom** [comment]
For the benefit of other devs, you can find a demo of `RichText` at (e.g.):

http://localhost/~cmalley/Github/scenery-phet/scenery-phet_en.html?ea&screenIndex=3&showHomeScreen=false&component=RichText

**Comment by pixelzoom** [comment]
I like this a lot, and the implementation looks great. 

Thoughts:
 
• If we can figure out how to add the hibernate dependency to scenery, this would be a nice addition to scenery.
 
• Deprecate SubSupText immediately.

• Replace SubSupText were possible to avoid XSS security issues. There are currently 44 instances of `var SubSupText`.  This could be done gradually over time.  I would do it immediately for all of my sims. And keep in mind what  @jonathanolson said in https://github.com/phetsims/scenery/issues/528#issuecomment-292592354:
> It's not fully compatible, as RichText treats its content as HTML, so the & character (if desired) would need to be encoded as &amp; in RichText.

**Comment by samreid** [comment]
> • If we can figure out how to add the hibernate dependency to scenery, 

I think he means himalaya.

**Comment by pixelzoom** [comment]
Yep, himalaya (can't blame that one on autocorrect ;) Fixed in my comment.

**Comment by jonathanolson** [comment]
I'll look into being able to embed Himalaya (and potentially return to having versions with other things embedded).

**Comment by samreid** [comment]
I haven't used SubSup text too much (at all?) in my sims.

**Comment by pixelzoom** [comment]
4/13/17 dev meeting: Everyone who is interested has already replied.  Can proceed with moving this from prototype to production.

**Comment by jonathanolson** [comment]
Replaced the desired usages, removed SubSupText (spot-checked 5 simulations). Closing.
