### ISSUE TITLE
ProbeNode breaks if you pass in options.children

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#302]
While working on circuit-construction-kit-common/js/common/view/AmmeterNode.js, I tried passing in children to the ProbeNode and it caused the ProbeNode to not display at all.

**Comment by samreid** [comment]
Fixed above and updated CCK to supply children in the options.  @pixelzoom can you please review the change?  Main questions:
1. Is this likely to cause problems for existing code?
2. Is this a good strategy for supporting children options in common code components?
3. Should this strategy be used in other node subclasses?  If so, can/should it be factored out somehow?

**Comment by pixelzoom** [comment]
I will look at the commits.  But unless there was a very good reason to pass in children to ProbeNode, I would have wrapped the ProbeNode in a Node, and added the additional children to the Node.

**Comment by pixelzoom** [comment]
FYI, I have also been using this pattern for subtypes of Node that don't support propagating children through options:

```js
assert && assert( !options.children, 'decoration not supported' );
options.children = [...];
Node.call( this, options );
```

**Comment by pixelzoom** [comment]
This entire section has a bad smell:

```js
    // Any children supplied in the options should be added on top of the probe node itself
    if ( options.children ) {
      children = children.concat( options.children );
      delete options.children;
    }

    Node.call( this, {
      children: children,
      mouseArea: outline,
      touchArea: outline
    } );

    this.mutate( options );
```

Imo, passing options to the supertype constructor, then later calling `mutate`, is an anti-pattern that should be avoided, as demonstrated by 2 specific issues here:

(1)  `mouseArea` and `touchArea` are set via `Node.call` to values computed in the constructor. And then (if provided via options) they will be overridden by the call to `mutate`.  Not at all obvious.  And if `options.mouseArea` and `options.touchArea were provided`, then there was no need to compute values in the constructor. 

(2) `children` is then handled differently than `mouseArea` and `touchArea`.   It's set via `Node.call`.  But then it's _not_ overridden by the call to `mutate`, due to the `delete options.children` statement.  Again, not at all obvious. 

I would replace the above code with:

```js
    options.mouseArea = options.mouseArea || createShape().close();
    options.touchArea = options.touchArea || createShape().close();
    
    if ( options.children ) {
      options.children = children.concat( options.children );
    }
    else {
      options.children = children;
    }
    
    Node.call( this, options );
```

**Comment by pixelzoom** [comment]
@samreid asked:

> 1. Is this likely to cause problems for existing code?

Unlikely to affect existing code.  And decoration by clients shouldn't affect  the ability to position the ProbeNode; i.e., it origin should still be "in the center of circular part of the sensor".

> 2. Is this a good strategy for supporting children options in common code components?

Imo, no, not as currently implement. See suggested change in https://github.com/phetsims/scenery-phet/issues/302#issuecomment-295360403.

I also don't think it's desirable to support decoration in all common-code components, especially when it complicates the implementation.

> 3. Should this strategy be used in other node subclasses? If so, can/should it be factored out somehow?

I don't think that's necessary.

> 4. Should we mutate the children array instead of creating a new one with concat?

See suggested change in https://github.com/phetsims/scenery-phet/issues/302#issuecomment-295360403.

**Comment by samreid** [comment]
Thanks, the strategy of updating options looks much cleaner.  I adopted your solution and simplified one line, it tests OK in Beer's Law Lab (no decorations) and CCK (with decorations).  If all seems well, this issue can be closed.

**Comment by pixelzoom** [comment]
👍 Closing.
