### ISSUE TITLE
Should electrons be in common code?

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#303]
I noticed that CCK has electrons copied from John Travoltage.  "Factoring out" sounds more desirable than "copy/paste", but we should decide how things should look.  In https://github.com/phetsims/build-an-atom/issues/155 I identified that BAA electrons are missing their "-" while JT and CCK have the "-".  Also, the sphere shading in BAA looks much better and the color scheme is a bit different.  We should decide what is best and factor it out as much as possible.  I'd like to use it for CCK in the near future.

Assigning @ariel-phet and @arouinfar since the next questions are design questions about how we want the electrons to look generally (and in CCK in particular).

- [x] john travoltage
- [x] circuit construction kit
- [ ] charges and fields

**Comment by ariel-phet** [comment]
@samreid I think the goals in BAA vs JT/CCK are a bit different.

Feel free to factor out the JT electrons, but leave the BAA electrons as is.

In BAA, the learning goal is centered more around the idea of electrons as subatomic particles, so the more obvious spherical shading seems appropriate. However in JT/CCK the learning goal is centered more around electrons as charge/current carriers, thus a flatter look, the minus sign, and the color scheme seems to fit better with these sims.

Perhaps factor these out as "electronCharges" as such to distinguish them. 

Note - Charges and Fields also uses this "charge" style

**Comment by samreid** [comment]
@ariel-phet I'm not sure why you added the "code review label".

**Comment by ariel-phet** [comment]
@samreid - it seems to me that this sort of question falls under that category, you care considering refactoring and "common-izing" code. That seems like the kind of issue that comes up in a review of the code.

**Comment by samreid** [comment]
Sounds good, thanks!

**Comment by samreid** [comment]
In the above commit, I added ElectronChargeNode and used it in John Travoltage and Circuit Construction Kit.  Charges and Fields had plus and minus charges combined into one type so I left it as is.  @jessegreenberg can you double check that John Travoltage still works properly and review these changes?

**Comment by pixelzoom** [comment]
This request to double-check John Travoltage was assigned to @jessegreenberg almost 4 years ago.  I'm guessing that we would have noticed a problem by now, so I'm just going to close.
