### ISSUE TITLE
UpDown Spinner has Hardwired constants

### ISSUE THREAD

**Issue by coledu** [phetsims/scenery-phet#305]
I would like to point out that the radius and the separation of the up down spinner is hardwired into the code. I think the spinner will benefit more if we are able to change the radius of the spinner as an option and have a default value set for the radius. We would like to use this functionality in fractions-intro. I would also recommend that we change the shape width depending upon the radius in order to make it look proportional. Now, we would have to make a few changes in this code in order to make the button look correctly proportional. The code I have mention thus far is located in UpDownSpinner.js on line 33 and 40. As way as these changes, I would suggest we add separation as an option in order to change the distance between the two buttons. You can see in the screenshot below that the java version of fraction-intro have a larger separation in the tab Build a Fraction. 
 
![image](https://cloud.githubusercontent.com/assets/26030529/26059472/e464502c-394f-11e7-83ef-2d374d5387de.png)

We will also need to make these changes in the LeftRightSpinner and in any code that call these. Such as Fraction-intro, Fraction-Comparison, and Expression-Exchange. These changes are not necessary needed but will add flexibility to the code and we have an impact on future code and design decisions.

@samreid what do you think about this idea.

**Comment by samreid** [comment]
> I would like to point out that the radius and the separation of the up down spinner is hardwired into the code. I think the spinner will benefit more if we are able to change the radius of the spinner as an option and have a default value set for the radius.

I see what you are referring to in UpDownSpinner.js:

```js
    var shapeWidth = 26;
    var upShape = new Shape().moveTo( 0, 0 ).lineTo( shapeWidth / 2, -10 ).lineTo( shapeWidth, 0 );
    var downShape = new Shape().moveTo( 0, 0 ).lineTo( shapeWidth / 2, 10 ).lineTo( shapeWidth, 0 );

    var upIcon = new Path( upShape, { lineWidth: 5, stroke: 'black', lineCap: 'round' } );
    var downIcon = new Path( downShape, { lineWidth: 5, stroke: 'black', lineCap: 'round' } );

    var radius = 20;
```

> I would also recommend that we change the shape width depending upon the radius in order to make it look proportional.

I agree, if we generalize the radius and shape width, we would also need to update those shapes so they would look the same.  Another alternative would be to add an option for setting the spacing, then allowing the user to scale up and down the entire node, however, this could stretch out the highlights and shadows, so the strategy you suggested is superior.

It looks like UpDownSpinnner and LeftRightSpinner were developed for Fractions Comparison (which is incomplete) and duplicate a lot of code with each other.  So I think it is a good idea to generalize these.  LeftRightNumberSpinner in Expression Exchange looks like it is designed to fit other criteria, showing a text readout instead of just the buttons, and it leverages sun.NumberSpinner, which looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/26075393/593b70c0-3972-11e7-9e9f-16a9b5b0ccf1.png)

These spinners are used in expression exchange and reactants products and leftovers and I am thinking it may be good to use them for Fractions Intro if they are more production ready.  It looks like they are locked in to using Rectangular buttons and I don't know how rigid the design is for Fractions Intro or how flexible NumberSpinner is.  I'll ask @ariel-phet if we can use NumberSpinner for Fraction Intro design.

**Comment by samreid** [comment]
@ariel-phet, thanks to @coledu I discovered that our currently implemented sun spinner looks like the one in the preceding comment.  Can we use that for Fractions Intro?

**Comment by samreid** [comment]
Also, @pixelzoom if we use the sun.NumberSlider, we may need a way to hide/suppress the numeric readout.  Is that supported by sun.NumberSlider?  If not, can it easily be added?

**Comment by pixelzoom** [comment]
> Also, @pixelzoom if we use the sun.NumberSlider ...

Assuming that you mean sun.NumberSpinner (not NumberSlider)....

The history of spinners, and the need for a numeric spinner,  is documented in https://github.com/phetsims/sun/issues/85. The nonstandard spinners in the fractions sims were noted as far back as Nov 2015. 

> ... we may need a way to hide/suppress the numeric readout. Is that supported by sun.NumberSlider? If not, can it easily be added?

It doesn't look difficult to add. More difficult is deciding whether it's better to add `options.valueVisibleProperty`, or set/get `valueVisible`.

But as you've already noted, fractions isn't even using NumberSpinner.  So the bigger questions are:

(1) Can you change the design to use the existing NumberSpinner, and delete the fractions-specific spinners?
(2) If not, then do you just modify UpDownSpinner and LeftRightSpinner to have the features that @coledu is requesting? 
(3) Or do you try to merge UpDownSpinner and LeftRightSpinner  into NumberSpinner by "skinning" it differently?

**Comment by samreid** [comment]
Here's a mockup with the square spinners (not grayed out properly for this mockup), @ariel-phet will that be OK?

![image](https://cloud.githubusercontent.com/assets/679486/26088176/e11a1fc4-39b2-11e7-900e-27eab539be28.png)

**Comment by ariel-phet** [comment]
@samreid @veillette square spinners are fine. We made this sim as one of our first ventures into designing for touch interfaces, and at the time round seemed friendly. We will likely pixel polish dimensions and such, but the square spinner should cause no issues.

**Comment by samreid** [comment]
@ariel-phet sounds good.

@coledu @veillette please investigate using the sun.NumberSpinner for this simulation.

Also tagging @jonathanolson so he is aware of this pending change.

**Comment by coledu** [comment]
One reason we have thought of not using NumberSpinner is that we would like to use a skin that resembles the original java sim. In addition, we do not want the spinner to be linked to the numerator but to the ContainerSet and have a callback connected to the spinner such that when it is pressed, it will animate a piece from the bucket to the cell or vice versa and update the numerator to be the number of filled cells in the container. Third it is relatively easy to add a fire on hold option to the UpDownSpinner and we were successfully able to add this feature this to our copy of UpDownSpinner. However, UpDownSpinner has a hard-coded callback function that it passes to RoundPushButton. If we could change UpDownSpinner to take the callback functions as an option, then we could pass our own function to perform the described behavior. We will implement this today and provide an update at the end of the day.

**Comment by jonathanolson** [comment]
It looks like the biggest issue is that the Range on a created NumberSpinner can't be changed dynamically (as the range would need to change).

> we would like to use a skin that resembles the original java sim.

I believe a consistent look between HTML simulations is more important, and @ariel-phet noted above that this shouldn't be a problem.

> In addition, we do not want the spinner to be linked to the numerator but to the ContainerSet and have a callback connected to the spinner such that when it is pressed, it will animate a piece from the bucket to the cell or vice versa and update the numerator to be the number of filled cells in the container.

The cleanest way seems to have this linked to the numerator, and the ContainerSet should listen to the numeratorProperty. When it increases, trigger the animation out of that many pieces.

> Third it is relatively easy to add a fire on hold option to the UpDownSpinner

Yes, it's possible to implement the same behavior. It's better to use a common shared component so this is not necessary.

**Comment by jonathanolson** [comment]
Also for the Range change issue, ideally NumberSpinner could accept a `{Property.<Range>}` instead of a `{Range}`?

@pixelzoom, would that refactoring be acceptable (you look like the original author)? I'd prefer to avoid recommending to recreate a NumberSpinner whenever the range changes, as this would mean you can't (with touch) increase the numerator and denominator at the same time.

**Comment by pixelzoom** [comment]
@jonathanolson asked:
> ... @pixelzoom, would that refactoring be acceptable ...

Sounds OK to me.  I'm sure that you've thought of this, but...

```js
rangeProperty.link( function( range ) {
  if ( !range.contains( numberProperty.value ) ) {
    // adjust numberProperty.value so that it's in range
  }
} );
```

**Comment by pixelzoom** [comment]
An additional advantage of changing to `rangeProperty` is that `NumberSpinner` and `NumberPicker` will now have the same constructor signature -- which they should, since the are functionally interchangeable UI components.   Someone should probably review their `options` -- they should be the same where possible.  (Perhaps this should be a separate issue?)

**Comment by pixelzoom** [comment]
While we're on the subject of spinner/picker...  In Equality Explorer, I had the need for a non-numeric picker, for selecting one of several operators.   Currently called ObjectPicker, shown on the left here:

![screenshot_270](https://user-images.githubusercontent.com/3046552/26895670-87c60b84-4b7f-11e7-8a4a-3335f427118d.png)

In Java, spinners were general enough to hold more than just numbers.  And I suspect that we'll run into this need for JS spinners at some point.  So we should probably investigate whether it's possible to have a base type of spinner (and picker) that is agnostic about the type of things that are being selected.

**Comment by coledu** [comment]
![image](https://user-images.githubusercontent.com/26030529/26895270-1bad70b2-4b8f-11e7-81de-6a5432e79490.png)
This is what @veillette says. There are additional concerns mainly in fractions-intro equality lab tab, the spinners must control  not only one number but an entire fraction. As you see in the screenshot above the left and right spinner control the entire fraction in the equality lab. Seconds, we would like the numerator to be a derived property which would be independent of the spinner since many drag interactions can change the value of the numerator. This seem beyond the scope of what number spinner does.

**Comment by pixelzoom** [comment]
> the left and right spinner control the entire fraction in the equality lab.

Left-right spinner could control a single {Property.<number>} valueProperty.  Then the view is responsible for representing it as a fraction. 

>  we would like the numerator to be a derived property

Unclear which numerator you're referring to here.  If it's the left-hand side of the equation, and you want to control the numerator with a spinner, then the number cannot be a DerivedProperty, because a DerivedProperty cannot be changed directly.

**Comment by pixelzoom** [comment]
In either case... You should be able to implement this UI with standard spinners.  But it may require some adapter Properties.

**Comment by jonathanolson** [comment]
> This is what @veillette says. There are additional concerns mainly in fractions-intro equality lab tab, the spinners must control not only one number but an entire fraction. As you see in the screenshot above, the left and right spinner control the entire fraction in the equality lab. Second, we would like the numerator to be a derived property which would be independent of the spinner since many drag interactions can change the value of the numerator. This seems beyond the scope of what number spinner does.

I'm not sure I understand. In the example you show, it looks like the upper-left spinner changes the left numerator, the bottom-left spinner changes the left denominator, and the right spinner changes a multiplier applied to the numerator and denominator.

I see three NumberProperties that the spinners are directly controlling, whose ranges may potentially change.

> many drag interactions can change the value of the numerator

The spinner doesn't have to be the only thing that can adjust those properties.

**Comment by pixelzoom** [comment]
@jonathanolson said:
> The spinner doesn't have to be the only thing that can adjust those properties.

... and in fact _should not_ assume that the spinner is the only thing adjusting those Properties. This is point of the MVC pattern.

**Comment by jonathanolson** [comment]
Changed NumberSpinner's range => rangeProperty. @pixelzoom can you review?

**Comment by pixelzoom** [comment]
Changes for NumberSpinner range => rangeProperty look good.   I'm not sure what else this issue is supposed to cover, so leaving the issue open.

**Comment by jonathanolson** [comment]
Created a code-review issue for this (https://github.com/phetsims/fractions-intro/issues/62), as I believe all necessary changes have been made.

If I notice there are other common-code changes needed for the sim, I'll make those.
