### ISSUE TITLE
NumberPicker doesn't recalculate background with range changes

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/scenery-phet#306]
Noticed in https://github.com/phetsims/area-model-common/issues/5.

If you create a NumberPicker with a small value range, it computes the maximum size of the readout and uses that. If you change the range to support huge numbers, it doesn't compensate.

**Comment by jonathanolson** [comment]
I guess that would work, but it's ugly (having to create a Text instance with the same Font, no way to grab the default Font used, etc.) Depending on the client to iterate over values to see what they actually need is painful too (e.g. is '8' wider than '9' in this font on this device?)

**Comment by jonathanolson** [comment]
Decided not to recalculate the size with range changes, and instead recommend passing in the maximum range initially for proper sizing. If range changes SHOULD cause resizes, the client can reconstruct the NumberPicker (presumably with something like MutableOptionsNode). Closing.

**Comment by samreid** [comment]
There are still TODOs marked for this issue, discovered during https://github.com/phetsims/chipper/issues/946

**Comment by pixelzoom** [comment]
The remaining TODO was vestigial, addressed as described by @jonathanolson in https://github.com/phetsims/scenery-phet/issues/306#issuecomment-302763200.  I've removed the TODO. Closing.
