### ISSUE TITLE
Combine LightRaysNodes into a single Path

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#309]
@jonathanolson suggested that we may get better performance to have all LightRaysNode children to be a single Shape/Path instead of multiple like this:

![image](https://cloud.githubusercontent.com/assets/679486/26370130/25880a48-3fb4-11e7-8559-857c0e6ff933.png)

**Comment by Denz1994** [comment]
We are now using Path to create a shape for the rays rather than an array of Lines. Using phet.joist.sim.display.popupDebug() @samreid and I found that this creates significantly fewer instances of for the rays.

**Comment by pixelzoom** [comment]
Looks good, and tested OK in acid-base-solutions.

I did notice that LightRaysNode `options` is a little messy, so I'm going to fix that in #313.

**Comment by pixelzoom** [comment]
Reopening.  After constructor, LightRaysNode currently has no Shape.  That seems a little dangerous.  If you were to pass in any of the options that require bounds (center, left, right,...) then that would presumably trigger an assertion failure.

**Comment by pixelzoom** [comment]
I verified that if you try to do this:

```js
new LightRaysNode( 10, { 
  centerX: 100
} );
```

... then you'll get an assertion failure in `Node.translate` line 1768 with message "x should be a finite number".

**Comment by samreid** [comment]
On skype @jonathanolson reported

If it's something whose center is naturally at the origin and changes in size, it's not too sketchy (just use translation / x,y to position it, since positioning based on bounds is probably not desired)

**Comment by pixelzoom** [comment]
> positioning based on bounds is probably not desired

Using `centerX` to center on (e.g.) a lightbulb seems like a non-hypothetical use case.

@samreid I'm not sure why you assigned this back to me.  If you think it's not a problem that needs to be addressed, just say so and close the issue.

**Comment by pixelzoom** [comment]
... And if `center` and other bounds-related options are not going to be supported, it may be prudent to add an assertion to verify that those options are not present.

**Comment by Denz1994** [comment]
@samreid Can we reserve this issue for tomorrow in between meetings? I would like to help with the assertions.

**Comment by samreid** [comment]
What do you think about adding an invisible moveTo/lineTo for when the rays are invisible?  Then we can still support centering, etc.

**Comment by jonathanolson** [comment]
If this is a common problem, Nodes could have a `pretendEmptyBoundsAreAroundOrigin` flag that could be turned on in cases like this?

I still have a preference for just using translation, as defining the 'center' of nothing as the origin sounds like a bad precedent.

**Comment by pixelzoom** [comment]
> What do you think about adding an invisible moveTo/lineTo for when the rays are invisible? Then we can still support centering, etc.

An invisible Circle with radius `bulbRadius` might be more straightforward.

**Comment by pixelzoom** [comment]
@jonathanolson said:
> If this is a common problem, Nodes could have a `pretendEmptyBoundsAreAroundOrigin` flag that could be turned on in cases like this?

I don't think that's necessary.  I would prefer to have (1) common-code components that have well-defined bounds, and (2) clear error messages for when that's violated.

> I still have a preference for just using translation, as defining the 'center' of nothing as the origin sounds like a bad precedent.

Agreed.

**Comment by pixelzoom** [comment]
Marking as "blocks publication".   This issue has been in an "in progress" state for way too long, and I would be apprehensive about publishing any sim that uses LightRaysNode.

**Comment by Denz1994** [comment]
In the constructor of `LightRayNode` `setBrightness(0)` is called which sets the `Path.shape` to an invisible `Circle`. `options.mutate()` is then called to ensure the Path has bounds before applying any options. 

@jonathanolson has reviewed this and it has been tested in `scenery-phet/demo` by passing in options such as `centerX:100`. 

Closing this issue.
