### ISSUE TITLE
add line break to RichText

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#310]
This came up in https://github.com/phetsims/joist/issues/71#issuecomment-306625844.  And it would be nice to jettison MultiLineText.

Add markup for specifying line breaks, with options for justification ('left', 'center', 'right') and leading. 

`<br>` seems like a fine markup for line break.

**Comment by pixelzoom** [comment]
MultiLineText uses `\n` for line breaks. So unless we want to change string files, we should probably support `\n` in RichText.

**Comment by jonathanolson** [comment]
> MultiLineText uses \n for line breaks. So unless we want to change string files, we should probably support \n in RichText.

But MultiLineText doesn't unescape HTML entities (or handle other things like a subset of HTML), so strings with ampersands or other characters would also break if we started using RichText instead. It seems like there are two totally different encodings, and trying to switch one to the other is problematic. (Could cause issues for credits?)

Additionally, if RichText is meant to be an HTML subset, wouldn't `\n` be treated as just another whitespace character?

**Comment by pixelzoom** [comment]
All good points.  But this was proposed as a replacement for MultiLineText.  So our options are:

(1) Keep MultiLineText
(2) Change all strings that use MultiLineText formatting

@jonathanolson what do you recommend?

**Comment by jonathanolson** [comment]
I'm not sure, changing strings to use a new formatting seems error-prone, as for a time both MultiLineText and RichText-based implementations would be trying to use the same strings in babel. @jbphet, what are your thoughts on changing string formatting?

**Comment by pixelzoom** [comment]
6/15/17 dev meeting consensus:  Line breaks would be generally useful, proceed.

**Comment by jonathanolson** [comment]
There are a lot of complicated edge cases for this, going to hold off until it goes up in priority.

**Comment by jonathanolson** [comment]
Unicode algorithm: http://unicode.org/reports/tr14/

There exists at least one implementation in JS with an MIT license: https://github.com/devongovett/linebreak (may require some Node.js => browser porting).

**Comment by jonathanolson** [comment]
NOTE: This is mostly complete, except line breaks/lineWrap next to trailing whitespace (or leading whitespace for RTL) isn't working well with align.

I'll need to somewhat change how whitespace is handled, so `" <br>"` or `"<br> "` is handled correctly with alignment.

**Comment by jonathanolson** [comment]
Added line-break support (along with 'align' and 'leading'). In addition, lineWrap is implemented (with the slight caveat that it can split lines at HTML tag boundaries in addition to whitespace). Also, functions can be provided (in addition to strings) as values for the links object (which will be called when the link is clicked).

@pixelzoom, anything else that should be done?

**Comment by pixelzoom** [comment]
👍 RichText looks good. 

@zepumph I see TRichText in scenery and scenery-phet.  Should the one in scenery-phet be deleted?

**Comment by jonathanolson** [comment]
> @zepumph I see TRichText in scenery and scenery-phet. Should the one in scenery-phet be deleted?

Sorry, I forgot to delete the scenery-phet one, but maybe it would be good to confirm with @zepumph whether that is safe?

**Comment by zepumph** [comment]
It's safe and removed!

**Comment by pixelzoom** [comment]
👍 Closing.
