### ISSUE TITLE
UpDownSpinner / LeftRightSpinner

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/scenery-phet#311]
Looks like very duplicated code, presumably would be handled by a single file instead of with two variants. I don't want to have to duplicate changes in both files for https://github.com/phetsims/fractions-intro/issues/62.

Additionally, it has some quirky differences between the two (a result of copy-paste?), with unbalanced touch areas:
![spinner](https://user-images.githubusercontent.com/480878/27067236-0cb7c4f4-4fc7-11e7-8777-cd1750304ae7.PNG)

Presumably this would be a candidate for a full rewrite into one file with the added features from https://github.com/phetsims/fractions-intro/issues/62?

**Comment by jonathanolson** [comment]
Additionally, I'm not sure why a valueProperty is passed in. Two callbacks (one for each button) would be more suitable for uses like fractions-intro.

**Comment by samreid** [comment]
I thought we were trying to delete these variants and focus on the other spinner implementation?

**Comment by samreid** [comment]
Sorry, I'm catching up on the other issue.  Will write back soon.

**Comment by jonathanolson** [comment]
Deferring, no need for fractions-intro currently.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/scenery-phet/issues/584#issuecomment-783537929, @samreid said:
> Let's delete/deprecate UpDownSpinner and LeftRightSpinner from scenery-phet and recommend using NumberPicker and/or generalizing RoundNumberSpinner instead.

So I see no reason to spend time on duplicate code in these classes. Closing.
