### ISSUE TITLE
RTL parentheses

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/scenery-phet#312]
@phet-steele pointed out that RTL parentheses are improperly handled by RichText now (see http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.1.0-rc.1/plinko-probability_en.html?stringTest=rtl).

It looks like RichText was not re-wrapping with directional marks (which lets the browser re-flow parenthesis and reverse them).

**Comment by jonathanolson** [comment]
@phet-steele, can you verify that the above change fixes this issue in plinko (with the string test)?

**Comment by phet-steele** [comment]
@jonathanolson plinko looks good, is there another sim that should be checked for regression?

**Comment by phet-steele** [comment]
> is there another sim that should be checked for regression?

Checked M&L, Gene Expression Essentials, and JT. All was well.

**Comment by jonathanolson** [comment]
Can't think of anything else that should be checked, thanks!

**Comment by phet-steele** [comment]
@ariel-phet what say you about a maintenance release for this fix? Currently the list of affected sims are small, but if they get translated into an RTL language....who knows what will happen?

Deployed RichText sims that would be considered for translation (and therefore a maintenance release):

graphing-lines 1.2
graphing-slope-intercept 1.0
chains 1.2
john-traovltage 1.3

Sim in rc that will need the patch:

resistance-in-a-wire 1.3

**Comment by ariel-phet** [comment]
@phet-steele this does seem like a good idea for a maintenance release. 

@jonathanolson would this be tough to fit in?

**Comment by zepumph** [comment]
This would need to hit JT 1.3-phetio and resistance in a wire 1.3-phetio as well.

**Comment by jonathanolson** [comment]
> @jonathanolson would this be tough to fit in?

It's probably fairly simple, seems worth the maintenance release to me also. OK to go ahead?

> This would need to hit JT 1.3-phetio and resistance in a wire 1.3-phetio as well.

Sounds good. I'll be notifying everyone on phet-dev when this is ready to go so I can manually hit places that need it.

**Comment by zepumph** [comment]
>manually hit places that need it.

Sounds good, let me know if you need help

**Comment by jonathanolson** [comment]
@ariel-phet, also let me know if there's anyone I should collaborate with to teach how to do the automated releases.

**Comment by ariel-phet** [comment]
@jonathanolson potentially @jessegreenberg or @zepumph or both (as I get the feeling that as we have more a11y sims, things will come up that require patches for a11y features)

**Comment by ariel-phet** [comment]
What say you a11y crew? @zepumph @jessegreenberg?

**Comment by zepumph** [comment]
Whatever is best. I'm happy to help.

**Comment by jonathanolson** [comment]
I'll plan to include the change from https://github.com/phetsims/scenery-phet/issues/315 with this.

@zepumph, what would a good time to have a call about the maintenance release (and start things off)?

**Comment by zepumph** [comment]
It would be good to get @jessegreenberg in on this too, if you are planning to give a basic rundown on the whole maintenance release process. Anytime tomorrow after 1 MST or so is good with me.

**Comment by jessegreenberg** [comment]
Definitely, thanks.  I am free tomorrow from 1pm MT to 3:45pm MT, or anytime after 5pm.

**Comment by zepumph** [comment]
We met today, and it was a good introduction into the maintenance release process for @jessegreenberg and I. It also seemed helpful for us to do phet-io releases together to get accustomed to that side of things.  Next steps are to work with @jonathanolson in the future, and perhaps @jessegreenberg or I can drive to get more familiar with the process. As we go I think there will be some good discussion on how we can improve the process. Currently it automates a lot of the mundane and repetitive parts, while still allowing room for sanity checks, which is really nice. I'm not yet sure how/if there is much we can do to improve the process. Thanks for the tour @jonathanolson! Please let us know when we can work together again.

**Comment by jonathanolson** [comment]
Deployment handled, closing.
