### ISSUE TITLE
clean up options in LightRaysNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#313]
Noticed while reviewing https://github.com/phetsims/scenery-phet/issues/309.

`options` are kind of messed up in LightRaysNode, needs clean up.

**Comment by pixelzoom** [comment]
Specifically... LightRaysNode doesn't have an `_.extends` call where the options are defined, documented and given default values.

**Comment by pixelzoom** [comment]
Factored out default options into LightRaysNode.DEFAULT_OPTIONS, which can be used in clients (like LightBulbNode) to cherry-pick options.  Removed duplicated default options from clients. 

Assigning to @samreid to review since CCK is the only non-common-code client.

**Comment by samreid** [comment]
Things are looking great, but I think this.options should be renamed this.lightRaysNodeOptions.  Storing this.options seems like it may get stomped on in a future subclass or parent class.  If you agree I'm happy to make the change.

**Comment by pixelzoom** [comment]
> I think this.options should be renamed `this.lightRaysNodeOptions`.

I that case we should cherry pick from DEFAULT_OPTIONS.  Done in above commit, @samreid please review.

**Comment by samreid** [comment]
Looks great, thanks, closing.
