### ISSUE TITLE
RichText documentation is incomplete

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#315]
Skype:
> [6/21/17, 1:11:30 PM] Jonathan Olson: "a < b" would be an error if you try to use it in RichText, but should work in MultiLineText. "a &lt; b" would be correct for RichText
[6/21/17, 1:11:35 PM] Jonathan Olson: they use totally different encodings
[6/21/17, 1:12:11 PM] Jonathan Olson: So essentially each translated string should eventually be tagged so Rosetta knows whether HTML entities need to be encoded, etc.
[6/21/17, 1:12:19 PM] Chris Malley: RichText doc doesn't indicate that HTML entities must be used. That's news to me.

Add documentation about entities, and any other markup constraints that may be missing.

**Comment by jonathanolson** [comment]
So, this is awkward.

I'm using himalaya (https://github.com/andrejewski/himalaya) to parse the HTML. It looks like I misinterpreted its "content" field on a "text" element, which is definitely not the element.textContent (expected), but is the equivalent of innerHTML. And I didn't run across this case when testing, or in the sims I've been involved with.

So, the current implications of this... there's no way to display a '<' character in RichText.

It looks like I should be able to use _.unescape() to do this (yay Lodash!).

I'm tagging this for developer meeting so others are aware of the scope of the changes, and the format for RichText.

**Comment by jonathanolson** [comment]
Implemented a fix for the encoding.

Added the following temporarily:
```js
      if ( this._text.indexOf( '&' ) >= 0 || this._text.indexOf( '< ' ) >= 0 ) {
        throw new Error( this._text );
      }
``
and saw no errors in a quick automated test. Indicates that this is probably unlikely to have caused a problem so far.

**Comment by jonathanolson** [comment]
I'll include in the maintenance release for RichText, and will create an issue for rosetta support.

**Comment by jonathanolson** [comment]
Noted in the maintenance release issue (https://github.com/phetsims/scenery-phet/issues/312) and created an issue for the validation (https://github.com/phetsims/rosetta/issues/156). Closing.
