### ISSUE TITLE
RichText link support

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/scenery-phet#316]
I'd propose that RichText should support hyperlinks, e.g. something like:

```js
new RichText( 'Go to the <a href="phetLink">PhET Website</a> for more information', {
  links: {
    phetLink: 'https://phet.colorado.edu'
  }
} );
```

This would use LinkText (or an equivalent) to display the link.

I don't want translators (or essentially anyone who can append query parameters to override strings) to be able to set URLs for security purposes, so there is a level of indirection there (and any non-matching link would either error out, or be handled as a non-link).

Thoughts?

**Comment by samreid** [comment]
That does seem like something RichText should support, and a good API for it.  However, I am unfamiliar with the implementation of RichText or LinkText so I can't tell if this will be easy enough or too complicated to implement.

**Comment by jonathanolson** [comment]
> I can't tell if this will be easy enough or too complicated to implement.

Very easy to implement.

**Comment by samreid** [comment]
Would it need extensive testing across different platforms?  Or relying on a strategy we are already comfortable with?

**Comment by jonathanolson** [comment]
Presumably it wouldn't need testing, as we've used LinkText (I believe) successfully in the past.

**Comment by jbphet** [comment]
Would it be possible to use a pattern and a supporting string util function that would allow everything except the link to be translated?

**Comment by jonathanolson** [comment]
> Would it be possible to use a pattern and a supporting string util function that would allow everything except the link to be translated?

I'd love to have more details on any alternative or pattern. It should handle not letting the user just add `<a href="http://something.bad">...</a>` directly into a string and having that turn up in the link.

So far, I think providing the URLs directly to RichText is the safest approach.

**Comment by samreid** [comment]
Sounds good, take my upvote!

**Comment by pixelzoom** [comment]
Looks generally good.  But I'd use named placeholder syntax for the link, e.g. `{{phetLink}}`.  This will allow Rosetta to identify the placeholder as something that can't be changed, and translators are conditioned to identify placeholders. 

```js
new RichText( 'Go to the <a href="{{phetLink}}">PhET Website</a> for more information', {
  links: {
    phetLink: 'https://phet.colorado.edu'
  }
} );
```

**Comment by jonathanolson** [comment]
Decision at 7/6/17 meeting to implement above with @pixelzoom's placeholder pattern.

**Comment by jonathanolson** [comment]
Added support.

Also:

- Added the ability to set `{ links: true }` and it just uses the links in the string.
- Added the ability to change the default link fill (`linkFill`)
- Didn't use LinkText, since it was cleaner overall to implement in RichText directly (can have formatting inside a link, which is potentially important).

Closing, but if anyone wants to review please re-open.

**Comment by jonathanolson** [comment]
For reference, examples in the demo view:
```js
new RichText( 'HTML entities need to be escaped, like &amp; and &lt;.' ),
new RichText( 'Supports <a href="{{phetWebsite}}"><em>links</em> with <b>markup</b></a>.', {
  links: {
    phetWebsite: 'https://phet.colorado.edu'
  }
} ),
new RichText( 'Or also <a href="https://phet.colorado.edu">links directly in the string</a>.', {
  links: true
} ),
new RichText( 'Links not found <a href="{{bogus}}">are ignored</a> for security.' )
```
