### ISSUE TITLE
Should we use named placeholders in common code?

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#317]
In https://github.com/phetsims/circuit-construction-kit-common/issues/380#issuecomment-312682355 @pixelzoom said:

The general issue is how (or whether) to change UI components that use numbered placeholders as part of their public API. NumberControl and NumberDisplay do this through options.valuePattern. Are their other common-code APIs that do something similar? Should/can we change these APIs to use named placeholders? What is the affect on client code?

Note that the following clients would be affected by changes to NumberControl: cck, gravity-force-lab, hookes-law, projectile-motion, unit-rates.

**Comment by samreid** [comment]
It looks like a general way to solve this in common code is to pass a function that formats numbers, rather than passing one kind of pattern or another.

```js
// old way:
new NumberControl({valuePattern:'{0} ohms'});

// proposed way
new NumberControl({numberFormatter:new ValuePatternFormatter('{0} ohms')});

// or
new NumberControl({numberFormatter:new NamedValuePatternFormatter('{{resistance}} ohms', 'resistance')});
```

**Comment by samreid** [comment]
Another feature which would be nice (and possible given the numberFormatter pattern described above) is that we may sometimes wish to change the units based on the value.  For instance: 
2 Volts
1 Volt

**Comment by pixelzoom** [comment]
As mentioned above, this affects several sims, including projectile-motion. And @andrea-phet would like to know how to proceed with https://github.com/phetsims/projectile-motion/issues/60.

**Comment by jonathanolson** [comment]
> Another feature which would be nice (and possible given the numberFormatter pattern described above) is that we may sometimes wish to change the units based on the value.

And in some languages like Slovenian, it has a "dual" concept, where there are three cases: 1, 2, 3+. Russian also has some intricacies with changing numbers. Usually we haven't been handling the plural/singular distinction for readouts, but if we do, I'd encourage we look at what type of solutions would be needed.

**Comment by pixelzoom** [comment]
Here's the recommended approach. Use named placeholders in new client code.  Map to numbered placeholders where needed for common code.

```js
// strings file
  "valueUnits": {
    "value": "{{value}} {{units}}"
  },

// client code
var valueUnitsString = require( 'string!.../valueUnits' )

var valuePattern = StringUtils.fillIn( valueUnitsString, {
  value: '{0}',
  units: metersString
} );

var numberControl = new NumberControl( ..., {
  valuePattern: valuePattern
  ...
} );
```

**Comment by samreid** [comment]
OK I made this change in CCK code.

**Comment by pixelzoom** [comment]
We made decisions in https://github.com/phetsims/scenery-phet/issues/317#issuecomment-315156244.  And @samreid applied the decisions in CCK.

@samreid anything else to do here?

**Comment by samreid** [comment]
We're all set, thanks!  Closing.
