### ISSUE TITLE
recommend renaming Timer.js to TimerNode.js

### ISSUE THREAD

**Issue by jbphet** [phetsims/scenery-phet#319]
There is a widely used type in phet-core named `Timer.js`.  In order to avoid confusion, I think it would be better to rename the timer node in scenery-phet to something like `TimerNode` or `Stopwatch` or something along those lines.

This came up when reviewing Masses and Springs, which uses the scenery-phet version of this type.  I'm more used to the phet-core version, and it had me briefly confused.  Tagging @Denz1994 so that he knows about this proposed change.

Assigning to @jonathanolson, since he is the only PhET developer listed as an author.

**Comment by jonathanolson** [comment]
Don't know what you mean, no one would name something that badly.

I only see scenery-phet's TimerNode (ignore the above commits).

**Comment by jbphet** [comment]
Huh, I could've sworn.  Ah well, never mind then.  Closing.
