### ISSUE TITLE
Add Emitters to other Text Types

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#323]
From https://github.com/phetsims/scenery-phet/issues/322#issuecomment-317074146

>We should potentially solidify a 'text api' across all of our implementations of text (Text, HTMLText, RichText, MultilineText, LinkText, ShadowText, ...). Many of these are children of Text, but not all of them. Maybe it would be good to have a parent of all texts that could solidify this api. I will bring this up in a new issue though.

Currently there are no trigger calls in MultilineText or RichText. I think it would be worth pursuing. For PhET-iO it could potentially help consolidate the Text api. 

I'm not sure how to proceed, tagging for dev meeting.

**Comment by pixelzoom** [comment]
Reviewing for developer meeting.  This originally came up in the context of PhET-iO, where an ideal API would provide the client with a "base API" for text, without having to worry about what specific implementation of text.  But having a "base API" for various types of text would also make life easier for PhET developers.

**Comment by jonathanolson** [comment]
There are actually some inherent performance disadvantages for how RichText and other "composite" types handle text.

Having things like RichText/MultiLineText handle rendering within Scenery internals would help a ton with mutation, and could give it the same API. Also feels like something Scenery should be able to handle natively.

**Comment by ariel-phet** [comment]
@samreid @zepumph @jonathanolson will discuss

**Comment by jessegreenberg** [comment]
The only other thing I noticed was that this issue is recommending adding trigger to Text types, but since Events is deprecated, would now be a good time to switch to Emitter for Text types?

**Comment by samreid** [comment]
Why are we discussing `trigger`?  Do you mean a way to be notified when the text changes?

**Comment by zepumph** [comment]
>Events is deprecated, would now be a good time to switch to Emitter for Text types?

Sorry I didn't realize that Events is deprecated. Emitters are probably the way to go.

>Do you mean a way to be notified when the text changes?
 yes that's what I'm talking about.

I'll change the name.

**Comment by zepumph** [comment]
This issue was solved for the phet-io cases. We now have trigger calls for MultilineText and RichText and have a textProperty to customize these through the phet-io API. Anything else here @samreid?

**Comment by samreid** [comment]
This looks great.  The only problem I see is that MultilineTextIO and RichTextIO are 99% identical.  I'm not sure how to address that though, perhaps a new issue.
