### ISSUE TITLE
Instrument accessibility types

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#327]
After talking with @jessegreenberg, we thought that it would be good to instrument some accessibiltiy types that are meant for global screen reader control like `UtteranceQueue.js` and `AriaHerald.js`

Currently there are instrumented properties in AriaHerald that we have been setting directly, but that should be changed instead to use the AriaHerald api with a `TAriaHerald`

**Comment by zepumph** [comment]
@samreid these are static types, like `phetio.js`. Is it possible to addInstance on these? I'm a bit confused about where phetio/TPhETIO's addInstance call is.

**Comment by zepumph** [comment]
They aren't really globals, but they are "global" to the sim, and just used statically.

**Comment by samreid** [comment]
@zepumph and I discussed where to put the addInstance calls, please let me know if you run into further questions.

**Comment by zepumph** [comment]
In the above commits I instrumented AriaHerald as Type TAriaHerald. I think the next step will be to uninstrument the internal properties, since they seem to be implementation details, and not public. @jessegreenberg you mentioned in our discussion today that these properties were only created for PhET-iO (maybe I heard wrong). If that is so, can they be deleted fully, and the implementation of AriaHerald simplified?

**Comment by zepumph** [comment]
In the above commits I instrumented AriaHerald as Type TAriaHerald. I think the next step will be to uninstrument the internal properties, since they seem to be implementation details, and not public. @jessegreenberg you mentioned in our discussion today that these properties were only created for PhET-iO (maybe I heard wrong). If that is so, can they be deleted fully, and the implementation of AriaHerald simplified?

**Comment by samreid** [comment]
Perhaps consider leaving read-only properties so they can be inspected or observed?

**Comment by jessegreenberg** [comment]
> discussion today that these properties were only created for PhET-iO (maybe I heard wrong).

That is correct.  Does PhET-iO enforce read only Properties? If the Properties are replaced with Emitters would that help?

**Comment by zepumph** [comment]
>Perhaps consider leaving read-only properties so they can be inspected or observed?

Good idea, do we have this currently? I could imagine an option specific to TProperty called 'phetioReadonlyProperty'. This would short circuit the set method, but nothing else. 

This seems like it could work, but we may want to change these to derived properties instead, since this functionality is already kinda set up there? I'm not sure exactly how that would work. @jessegreenberg's suggestion for emitters is probably better. I defer to him.

**Comment by jessegreenberg** [comment]
After thinking about it, I am leaning more toward Property rather than Emitter.  Property supports inspection while Emitter only supports observing.

In this case it isn't too critical that the Properties are read-only, alerts will still work as well as aria-live.  But by setting directly, they won't leverage some of the protections in AriaHerald that prevent rapid alerts from being ignored, and alerts will still be spoken when AriaHerald is disabled.

**Comment by jessegreenberg** [comment]
> and alerts will still be spoken when AriaHerald is disabled.

With PhET-iO, maybe we *want* the client to have this freedom?

**Comment by jessegreenberg** [comment]
My preference is to leave Properties in marked as read-only to the best of our ability.

**Comment by zepumph** [comment]
I think this is the best that we have right now in terms of communicating read-only to PhET-iO. See @jbphet's work

```js
    this.activeProperty = new Property( false, {
      tandem: options.tandem.createTandem( 'activeProperty' ),
      phetioValueType: TBoolean,
      phetioInstanceDocumentation: 'this Property is read-only, do not attempt to set its value'
    } );
```

Maybe I should take the time now to create an option like I was saying above, `phetioReadonlyProperty`.

My main hesitation with that is that it breaks the convention of having TTypes just wrap the Type, because it adds functionality to the TType that the Property doesn't have.

**Comment by jessegreenberg** [comment]
@zepumph I understand your concern.  In this case, ```phetioInstanceDocumentation``` seems good enough.

**Comment by samreid** [comment]
> Maybe I should take the time now to create an option like I was saying above, phetioReadonlyProperty.

> My main hesitation with that is that it breaks the convention of having TTypes just wrap the Type, because it adds functionality to the TType that the Property doesn't have.

Maybe `phetioReadOnly` would be a property on the Property?

**Comment by zepumph** [comment]
These were commits from yesterday that I just pushed. I also added the read only doc just so that it's there right now. Let's bring this back up at phet-io meeting.

**Comment by zepumph** [comment]
I instrumented the UtterenceQueue I think this will help as we move into descriptions with OL.

**Comment by zepumph** [comment]
For now we don't need to instrument Utterance because `UtteranceQueue.addToFront` can take in an Utterance or a string. Phet-io won't let you pass in an Utterence Type proper across the frame anyways, so I think this is best. Thanks for making this easy on me @jessegreenberg. I'll do more as needed.

**Comment by samreid** [comment]
> Phet-io won't let you pass in an Utterence Type proper across the frame anyways, so I think this is best. 

I don't know most of the context here, but TUtterance is only a file away!

**Comment by zepumph** [comment]
I think this issue is ready to close. We will continue to discuss `phetioReadonly` inhttps://github.com/phetsims/axon/issues/145. We can add more functionality to `TUtteranceQueue` as we go. Passing off to @jessegreenberg to make further suggestions or to close.

**Comment by jessegreenberg** [comment]
Nothing else from me, thanks for working on it @zepumph! Closing.
