### ISSUE TITLE
AriaHerald, renamed to ariaHerald?

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#328]
Since it is a static object and not a constructed type, it may be more idiomatic to have it be lower case. 

Throughout the project usages look like:

```js
  var AriaHerald = require( 'SCENERY_PHET/accessibility/AriaHerald' );
      AriaHerald.announcePolite( alertString );
```

rather than `new AriaHerald`

This is the same strategy that is employed for phetio.js, since it too is just a POJsonO.

@jessegreenberg what do you think?

**Comment by jessegreenberg** [comment]
I disagree @zepumph, PhET convention for naming such Objects is typically to start with an upper case.  For instance things like phet-core/Timer, shred/AtomIdentifier, and Objects that implement factory functions all start with an upper case.

**Comment by zepumph** [comment]
Sounds good!
