### ISSUE TITLE
add fractionHeadHeight feature to ArrowNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#33]
Make this behave similar to Java implementation, see piccolophet.ArrowNode.

This is essentially implemented already in molecule-polarity.DipoleNode.

**Comment by pixelzoom** [comment]
@jessegreenberg requested this feature in #175:
> In trig-tour, there is an arrow that can change head width and height so that the head does not cover up the tail as the arrow shrinks down in size.

Let me know how soon this feature is needed, whether want to tackle this, and whether you need assistance. I recommend that you start by looking at piccolophet.ArrowNode in the Java code.

**Comment by jessegreenberg** [comment]
Thank you @pixelzoom, I would like to tackle this.  Implementing this would significantly simplify LineArrow code in trig-tour.  I am taking a look at the Java now.

**Comment by jessegreenberg** [comment]
Assigning to myself, I can take a stab at this soon.

**Comment by jessegreenberg** [comment]
I added this feature to ArrowNode/ArrowShape in the commit above.  The feature added was ported from phetcommon\view\graphics\Arrow.java.

**Comment by jessegreenberg** [comment]
@pixelzoom, would you mind reviewing these changes?

**Comment by pixelzoom** [comment]
I inspected the code and test-drove it in trig-tour. :+1: Closing.
