### ISSUE TITLE
replace MultiLineText with RichText

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#331]
RichText now supports line breaks, which was the sole purpose of MultiLineText.  It would be nice to get rid of MultiLineText.  But MultiLineText used `\n`, while RichText uses `<br>`.   So for translated strings (which is the majority of MultiLineText uses), we'd need to either (1) change translated strings, or (2) support `\n` in RichText. 

There are 90 occurrences of `\n` in *-en.json (English string files). Unclear whether all of them are associated with MultiLineText.

MultiLineText should be avoided in new development.

**Comment by pixelzoom** [comment]
Two non-translated occurrences of MultiLineText that I replaced:

acid-base-solutions: https://github.com/phetsims/ph-scale/commit/5cb93745d8d86d66e48cfe810ced4ab346174ea5
vegas: https://github.com/phetsims/vegas/commit/8654582a763431d4ab0d196329cf3d3d81b12f75

**Comment by pixelzoom** [comment]
It looks like we could reimplement MultiLineText like this:

```js
define( function( require ) {
  'use strict';

  // modules
  var RichText = require( 'SCENERY/nodes/RichText' );

  function MultiLineText( text, options ) {

   // replace '\n' with '<br>' and delegate to RichText
    RichText.call( text.replace( /\n/g, '<br>' ), options );
  }

  sceneryPhet.register( 'MultiLineText', MultiLineText );

  return inherit( RichText, MultiLineText );
} );
```

@jonathanolson your thoughts?

**Comment by pixelzoom** [comment]
If we reimplement MultiLineText as in https://github.com/phetsims/scenery-phet/issues/331#issuecomment-322596536,  then I guess we'd also have to change `TMultiLineText` to extend `TRichText`.

**Comment by jonathanolson** [comment]
> It looks like we could reimplement MultiLineText like this

I guess it depends on how often it would be needed.

**Comment by pixelzoom** [comment]
@jonathanolson said:
> I guess it depends on how often it would be needed.

The idea would be to not use MultiLineText in new development, so it should not be "needed" at all in that regard.  What I'm proposing is that instead of changing translated strings, or having to maintain MultiLineText, we simply make MultiLineText convert the strings to a form that can be used by RichText, then replace  MultiLineText's implementation with RichText.

**Comment by jonathanolson** [comment]
I have no problem with recreating MultiLineText as you have described.

**Comment by pixelzoom** [comment]
8/17/17 dev meeting: We decided it's safest to leave MultiLineText "as is".  And we will annotate as `@deprecated`.

**Comment by pixelzoom** [comment]
5 years and 7 months later... In https://github.com/phetsims/scenery/issues/1542, MulitLineText was finally deleted, replaced by RichText.  The `\n' character is now supported by `RichTextOptions.replaceNewlines`.
