### ISSUE TITLE
[IE11] Number.MAX_SAFE_INTEGER not supported

### ISSUE THREAD

**Issue by phet-steele** [phetsims/scenery-phet#332]
Scroll down to browser compatibility: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

This is being used as an option in `NumberAccumulator.js` at line 36:

```
options = _.extend( {
      maxDigitsRightOfMantissa: 0,
      maxDigits: Number.MAX_SAFE_INTEGER.toString().length
    }, options );
```

projectile-motion, as far as I know, is the first sim to use `NumberAccumulator.js` via `Keypad.js` and is failing to load on Win7 IE11. For phetsims/QA/issues/39. Assigning to @pixelzoom and @andrea-phet for now since it is blocking projectile-motion's rc.

**Comment by phet-steele** [comment]
Confirmed would not load on Win 8 IE11

**Comment by andrea-phet** [comment]
In the above commit I copied strategies used in other places such as node and Function Builder. Assigning to @phet-steele to check.

**Comment by pixelzoom** [comment]
Bummer. Unless we want to drop IE11 support, this is going to require another RC with full test matrix. 

Mentioning @jbphet since he's the primary developer for keypad. @jonathanolson since he's using this in area-model.

**Comment by phet-steele** [comment]
@jbphet requested to be assigned, so here he goes!

**Comment by phet-steele** [comment]
Oh he is, nvm.

**Comment by jonathanolson** [comment]
Presumably IE11 devices pointing at bayes continuous testing would have caught this and flagged errors before the RC?

**Comment by pixelzoom** [comment]
@jonathanolson said:
> Presumably IE11 devices pointing at bayes continuous testing would have caught this and flagged errors before the RC?

I'm also wondering why this wasn't caught sooner.

**Comment by jonathanolson** [comment]
>> Presumably IE11 devices pointing at bayes continuous testing would have caught this and flagged errors before the RC?
>
> I'm also wondering why this wasn't caught sooner.

To clarify, only Chrome headless instances are doing continuous testing right now. It's set up so you can point an IE11/whatever browser at the loop and it will also test, and I've recommended that we should have one browser per supported platform testing (to catch issues like this), but it is not currently being done.

**Comment by pixelzoom** [comment]
@jbphet What is your recommendation for addressing this in projectile-motion. We're in RC phase, and would prefer not to start over with master.

**Comment by pixelzoom** [comment]
@jbphet What is your recommendation for addressing this in projectile-motion? We're in RC phase, and would prefer not to start over with master. See https://github.com/phetsims/QA/issues/39#issuecomment-324198237

**Comment by jbphet** [comment]
I'm investigating now, and will make a recommendation and fix shortly.  We can make a branch of scenery-phet and cherry pick only the fix, as we often do for similar situations, so you won't need to restart the RC process.

**Comment by pixelzoom** [comment]
It looks like there have been changes to NumberAccumulator.js in master since projectile-motion's 1.0 release branch was created.  Let's be careful not to pick up those changes - make only the changes needs to fix this issue.  That may involve manually patching NumberAccumulator.js, vs cherry picking the file.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/scenery-phet/issues/332#issuecomment-323870556, @andrea-phet said:
> In the above commit I copied strategies used in other places such as node and Function Builder. 

I don't see anything like this in Function Builder, and I'm not sure what the reference to "node" is about.   I do see this in lodash:

```js
    /**
     * Used as the [maximum length](http://ecma-international.org/ecma-262/6.0/#sec-number.max_safe_integer)
     * of an array-like value.
     */
    var MAX_SAFE_INTEGER = 9007199254740991;
```

**Comment by pixelzoom** [comment]
According to http://ecma-international.org/ecma-262/6.0/#sec-number.max_safe_integer, `Number.MAX_SAFE_INTEGER` is new in ES6.   And with WebStorm set to "ECMAScript 5.1" compliance (Preferences > Languages & Frameworks > JavaScript), `Number.MAX_SAFE_INTEGER` is clearly flagged in the WebStorm Editor as `undefined`. 

@jbphet Do you have your IDE set to ES5 compliance?

**Comment by pixelzoom** [comment]
@jbphet and I discussed via Zoom.  He's going to change to `maxDigits: 15` in a branch created off of the scenery-phet sha that is shown in projectile-motion 1.0 dependencies.json. 

In master, he's going to do something like:

```js
var MAX_SAFE_INTEGER = Number. MAX_SAFE_INTEGER  || 9007199254740991;
var MAX_DIGITS = MAX_SAFE_INTEGER.toString().length;
...
options = _.extend( {
  ...
  maxDigits: MAX_DIGITS
}, options );

assert && assert( options.maxDigits > 0 && options.maxDigits <= MAX_DIGITS, 
  'maxDigits out of range: ' + options.maxDigits );
```

**Comment by jbphet** [comment]
Actually, I'm going to set `maxDigits` to 15 in both places.  My reasoning is that while `Number.MAX_SAFE_INTEGER` is 16 digits long, it is less than the number represented by 16 9 digits in a row, so using `MAX_SAFE_INTEGER.toString().length` could allow users to enter values that JavaScript can't represent.  I just tried this from the console in Chrome, and number is not correctly stored.

**Comment by pixelzoom** [comment]
OK.  I suggested using `MAX_SAFE_INTEGER.toString().length - 1`, which is `15`.  But whatever you want to do.

**Comment by pixelzoom** [comment]
Should probably also add this assertion in master:

```
assert && assert( options.maxDigitsRightOfMantissa => 0 && options.maxDigitsRightOfMantissa <= options.maxDigits, 
  'maxDigitsRightOfMantissa is out of range: ' + options.maxDigitsRightOfMantissa );
```

**Comment by pixelzoom** [comment]
I asked:
> @jbphet Do you have your IDE set to ES5 compliance?

Slack:

John Blanco [12:03 PM] Mine is - and was - set to ECMAScript 5.1. It does flag Number.MAX_SAFE_INTEGER, I'd just never noticed.  Aadish did this originally, and I missed it on code inspection.
Chris Malley [12:04 PM] I missed it too :) Guess I should set WebStorm to use a more noticeable color.

**Comment by jbphet** [comment]
Okay, this should be fixed in master, and I've created a branch and done a quick fix for the projectile-motion RC.  The branch in scenery-phet is projectile-motion-1.0, and the SHA that should be picked up is 6c693b230fefb6356c880249a3261e0aaab2a440.

**Comment by pixelzoom** [comment]
@jbphet see https://github.com/phetsims/scenery-phet/issues/332#issuecomment-324413016

**Comment by jbphet** [comment]
Added the additional verification suggested in https://github.com/phetsims/scenery-phet/issues/332#issuecomment-324413016.

**Comment by pixelzoom** [comment]
@phet-steele please verify in master.

Since `MAX_SAFE_INTEGER` is no longer involved in the projectile-motion-1.0 branch, this issue should be good to go for projectile-motion 1.0.0-rc.2.

**Comment by phet-steele** [comment]
@pixelzoom, projectile-motion successfully loads in Win 7, 8, 10 IE11 from master.

**Comment by phet-steele** [comment]
Fixed in projectile-motion rc.2. Anything left to do, @pixelzoom?

**Comment by pixelzoom** [comment]
Nothing else to do, closing.
