### ISSUE TITLE
ScientificNotationNode removes zeroes to right of decimal in mantissa

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#334]
```ScientificNotationNode.toScientificNotationNode``` returns an object like ```{mantissa:{number}, exponent:{number}}```.  Since mantissa is a number, we lose the zeroes to the right of the decimal and the precision specified by the option ```mantissaDecimalPlaces```. To keep consistent precision when there are zeroes to the right of the decimal mantissa needs to be a string.

For instance
```js
ScientificNotationNode.toScientificNotation( 15.666, { mantissaDecimalPlaces: 2 } )
```
will provide 1.57 x 10^1.

```js
ScientificNotationNode.toScientificNotation( 15, { mantissaDecimalPlaces: 2 } )
```
will provide 1.5 x 10^1 (instead of 1.50 x 10^1).

Can we restore precision for mantissa with Util.toFixed before returning in ```toScientificNotation```? @pixelzoom since you were the original author do you have any thoughts?

**Comment by pixelzoom** [comment]
@jessegreenberg said:
> To keep consistent precision when there are zeroes to the right of the decimal mantissa needs to be a string.

This seems like an OK direction to me.  But a couple of things to consider:

(1) For `{mantissa:{string}, exponent:{number}}`, it seems inconsistent/confusing to have different types.  `toScientificNotation` should probably return `{mantissa:{string}, exponent:{string}}`.

(2) All call sites for `toScientificNotation` need to be examined. Any that are assuming that mantissa or exponent are `{number}` will need to be changed.   This currently includes usage throughout `ScientificNotationNode`, and `ISLCForceArrowNode` lines 167, 169, 170.

**Comment by jessegreenberg** [comment]
```toScientificNotation``` returns {mantissa: {string}, exponent: {string}}, and I updated usages in ScientificNotationNode and ISLCForceArrowNode.  @pixelzoom would you mind reviewing?

**Comment by pixelzoom** [comment]
👍 Closing.
