### ISSUE TITLE
add PhetColorScheme.BUTTON_YELLOW

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#337]
For a few sims now, I’ve been using `PhetColorScheme.PHET_LOGO_YELLOW` for the `baseColor` of buttons.  This seems to be a color that PhET has standardized on for buttons.  But it feels wrong to be using `PHET_LOGO_YELLOW`.  If someone tweaks the logo color, it's not obvious that we'll be also changing the color of a _lot_ of buttons.    There are currently 36 occurrences of `PHET_LOGO_YELLOW`, and most of them appear to be button colors.

I'm going to add `PhetColorScheme.BUTTON_YELLOW`, and use it where appropriate.

**Comment by pixelzoom** [comment]
I noticed that ZoomButton was using its own shade of yellow for `baseColor`.  Since it's a standard button, I've changed it to use `PhetColorScheme.BUTTON_YELLOW`.  Devs alerted on Slack dev-public channel.

**Comment by pixelzoom** [comment]
Devs notified on Slack developer channel:
> Uses of PHET_LOGO_YELLOW for buttons have been replaced with BUTTON_YELLOW throughout all PhET code.  Same snazzy color, different name.  Please refrain from using PHET_LOGO_YELLOW for buttons.

**Comment by pixelzoom** [comment]
And the lucky reviewer is...

> _.shuffle( [ 'JB', 'JG', 'JO', 'MK', 'SR' ] )[0]
"JG"

**Comment by jessegreenberg** [comment]
The replacement looks great, thanks.  I also did a search and remaining usages of ```PhetColorScheme.PHET_LOGO_YELLOW``` seem appropriate.
