### ISSUE TITLE
MeasuringTapeNode: Add optional transparent rectangle behind readout

### ISSUE THREAD

**Issue by arouinfar** [phetsims/scenery-phet#339]
In https://github.com/phetsims/charges-and-fields/issues/139, it was reported that the the readout of `MeasuringTapeNode` can be occluded by the E-field arrows. 
![image](https://user-images.githubusercontent.com/8419308/31037258-4dfc92d0-a52d-11e7-9ab5-59080ea2b78f.png)

A similar issue can occur in Projectile Motion. A stroke was added to the text to improve readability, but a shaded rectangle behind the readout would have been a bigger improvement.
![image](https://user-images.githubusercontent.com/8419308/31037252-42982ff8-a52d-11e7-9f56-293502869150.png)

Typically, we have added a transparent rectangle behind text to improve its readability. See, for example, the cannon in Projectile Motion or the equipotential values in Charges and Fields.
![image](https://user-images.githubusercontent.com/8419308/31037399-f097c8a2-a52d-11e7-998f-179e3f86a309.png) ![image](https://user-images.githubusercontent.com/8419308/31037425-0f2ac562-a52e-11e7-95b5-02f35c3c5503.png)

@pixelzoom commented that
> The tape measure is implemented in scenery-phet `MeasuringTapeNode`. I see no option for adding a shaded rectangle behind the value readout. A quick look suggests that it wouldn't be too difficult to add.

I think it would be worthwhile to add an optional transparent rectangle behind the readout of `MeasuringTapeNode`, given that it is used in many sims, and others may have similar occlusion issues. 

Assigning to @ariel-phet for consideration and reassignment to the appropriate developer, should we proceed with this change.

**Comment by ariel-phet** [comment]
@arouinfar seems like a nice change.

**Comment by ariel-phet** [comment]
@pixelzoom said:

> We already have scenery-phet NumberDisplay, which “Displays a Property of type {number} in a background rectangle”

So there might be a nice common code way to achieve this change. He is going to take a stab at this at some point, but if it turns into more than around ~1 hour of work he is going to bail and reassign to me.

**Comment by pixelzoom** [comment]
It should be just a quick swap of `Text` for `NumberDisplay`.  But incredibly, `MeasuringTapeNode` made `this.labelText` public.  So I can't just swap.  I have to find all of the clients who are using `this.labelText` and relying on the fact that it's `Text`.

**Comment by pixelzoom** [comment]
Looks like the only client using `this.labelText` is projectile-motion `ProjectileMotionScreenView`:

```js
205 measuringTapeNode.labelText.stroke = 'white';
206 measuringTapeNode.labelText.lineWidth = 0.3;
```

And those things should be settable via options, not by reaching into `MeasuringTapeNode`.

**Comment by pixelzoom** [comment]
Hmmm... Looks to me like projectile-motion is stroking the text for the same reason that we're trying to add a transparent background behind the value.   @arouinfar as lead designer of projectile-motion, do you recall if this is why the text is being stroked? And would it be OK to get rid of that and use a transparent white background?

**Comment by arouinfar** [comment]
@pixelzoom in Projectile Motion, the stroke around the `MeasuringTapeNode` readout was added as a band-aid because there was no support for a transparent background (see the 2nd screenshot in https://github.com/phetsims/scenery-phet/issues/339#issue-261781595). The stroke around the text can be killed and replaced with a transparent white background.

**Comment by pixelzoom** [comment]
Next problem is that `MeasuringTapeNode` defaults the color of the text to 'white'.  I'll resist the urge to rant about default values like this in common code, but suffice it to say that the default should be 'black' (as is the case with scenery).   Since `NumberDisplay` defaults to 'black' text on a 'white' background, I'll need to either (a) apply an ugly bandaid in `MeasuringTapeNode` to avoid changing the defaults, or (b) change the defaults and visit every use of `MeasuringTapeNode` to avoid breaking anything.  There are 12 occurrences of "var MeasuringTapeNode = require`, so I'm leaning towards (b).

**Comment by pixelzoom** [comment]
Since `MeasuringTapeNode` takes a mutable `unitsProperty`, I'll need to make units mutable in `NumberDisplay`.

**Comment by pixelzoom** [comment]
Using `NumberDisplay` isn't going to work without a lot of effort - there's too much of a mismatch between `NumberDisplay` and `MeasuringTapeNode`.  Things like units, numberRange,...

**Comment by pixelzoom** [comment]
Tracking required changes to projectile-motion in https://github.com/phetsims/projectile-motion/issues/156.

**Comment by pixelzoom** [comment]
I've added this feature.

New options to MeasuringTapeNode:

```js
      textBackgroundColor: null, // {Color|string|null} fill color of the text background
      textBackgroundXMargin: 4,
      textBackgroundYMargin: 2,
      textBackgroundCornerRadius: 2,
```

New public functions in MeasuringTapeNode:

```js
    /**
     * Sets the color of the text background
     * @param {Color|string|null} color
     * @public
     */
    setTextBackgroundColor: function( color )
```

I also renamed `labelText` to `valueNode`, and made it `@private`. 

New options are tested and demonstrated in scenery-phet's demo application - select "MeasuringTapeNode" from the combo box on the "Components" screen.

Also tested and integrated into projectile-motion and charges-and-fields.

**Comment by pixelzoom** [comment]
I'm going to wait until @arouinfar has reviewed sim changes (https://github.com/phetsims/charges-and-fields/issues/139, https://github.com/phetsims/projectile-motion/issues/156) before I assign this to be reviewed.

**Comment by pixelzoom** [comment]
And the lucky reviewer is:

> _.shuffle( [ 'JB', 'JG', 'JO', 'MK', 'SR' ] )[0]
"JB"

**Comment by jbphet** [comment]
The code changes look good, and I tested it out and projectile-motion and charges-and-fields, and it worked - and looked - great.  Nicely done @pixelzoom.  Closing.
