### ISSUE TITLE
consolidate ArrowNode and MutableArrowNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#34]
Discussed at 2/25/14 developer meeting in the context of #30. Notes:

- A single implementation of arrows is preferred.

- Why is MutableArrowNode needed? Is it really an issue in GAO, or are there other things contributing to poor performance? (e.g., multiple updates during one animation cycle)

- MutableArrowNode is a much more complicated implementation than ArrowNode. Prefer the less complicated implementation, if possible.

**Comment by samreid** [comment]
I removed MutableArrowNode.js above. Let us focus our efforts on faster performing arrows in https://github.com/phetsims/scenery-phet/issues/28 when necessary.
