### ISSUE TITLE
Handle ModelViewTransform2 position inversion in KeyboardDragHandler

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/scenery-phet#344]
The current KeyboardDragHandler inverts the change in y values for nodes within sims that use a ModelViewTransform2 where negative values are toward the bottom of the sim.

The ideal solution will involve likely involve the creation of a base drag handler, see https://github.com/phetsims/scenery/issues/716.

For now, @jessegreenberg and I discussed creating an option flag that will allow for the inversion of position deltas.

**Comment by jessegreenberg** [comment]
KeyboardDragHandler has been deleted and replaced with KeyboardDragListener in https://github.com/phetsims/scenery/issues/716. This type supports transforms, so this can be closed.
