### ISSUE TITLE
ObjectPicker: migrate from equality-explorer

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#345]
PhET needs a picker that can handle any type of object (ala Java spinners).

PhET currently has `NumberPicker`, which allows you to choose an integer from a range. Here's an example with 4 NumberPickers in the Slope screen of [Graphing Lines 1.2.1](https://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.2.1/graphing-lines_en.html):

![screenshot_434](https://user-images.githubusercontent.com/3046552/34062532-3be967c6-e1aa-11e7-9033-acafebd92f99.png)

In Equality Explorer, a picker is needed to chose between a set of operators (+,-,×,÷ ).  Here's what that looks like in the _Operations_ screen of [Equality Explorer 1.0.0-dev.47](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.47/equality-explorer_en.html?initialScreen=4); the "operator picker" is on the left, NumberPicker is to the right of it:

![screenshot_435](https://user-images.githubusercontent.com/3046552/34062576-7cf959ba-e1aa-11e7-80c8-cc94f7072366.png)

To implement this in Equality Explorer, I took the fast lane -- I copied `NumberPicker` to `ObjectPicker`, then modified it heavily.  

`ObjectPicker` is currently documented with "TODO: migrate to common code".   And it's going to be a significant chunk of work. Ideally, `NumberPicker` would be a specialized version of `ObjectPicker`, or they should at least share a supertype. And maybe there should be a `StringPicker`, as a convenience for use in scenarios like Equality Explorer. PhET-iO and a11y will need to be addressed, since they are supported by `NumberPicker`.  

One major difference between `ObjectPicker` and `NumberPicker` is how the values and their associated Nodes are handled. `ObjectPicker` provides a list of arbitrary values and the Node to display for each value.  `NumberPicker` is very different - it takes a range of numbers and mutates a single node that the displays a number from the range.   There are undoubtedly other differences -- this will not be easy.

Assigned to me with "deferred" priority. I'm not going to touch it until Equality Explorer is wrapping up or published. Other developers will certainly be involved.

Tagging @ariel-phet so that he's aware that this non-trivial common-code work will need to be done in the future.

**Comment by ariel-phet** [comment]
Noting that this might be a good project for @andrea-phet

**Comment by pixelzoom** [comment]
If this is assigned to @andrea-phet, I'll collaborate on it with her.

**Comment by pixelzoom** [comment]
Note that ObjectPicker has a new options that will be general useful for pickers.  The option is `{boolean} wrapEnabled`.  When `false`, the up/down picker arrows are disabled when the value is the last/first in the list of items.  When `true`, the picker arrows are never disabled, and cycling through the values simply wraps around to the beginning/end of the item list.  If you press the up arrow while the last item is displayed, it wraps around to display the first item. Similarly, if you press the down arrow while the first item is displayed, it wraps around to display the last item.

**Comment by pixelzoom** [comment]
To support the complicated UX specified in https://github.com/phetsims/equality-explorer/issues/45, I added options `upEnabledProperty` and `downEnabledProperty`.  If specified by the client, the client is fully responsible for the managing the enabled/disabled state of the up/down buttons.  This yet-another difference from NumberPicker that will need to be addressed.

**Comment by pixelzoom** [comment]
Another deviation from NumberPicker.... ObjectPicker now has these color options, which we found useful in Equality Explorer:

```js
      backgroundColor: 'white', // {Color|string} color of the background when pointer is not over it
      arrowsColor: 'blue', // {Color|string} color of arrows
      arrowsPressedColor: null, // {Color|string|null} color of arrows when pressed, computed if null
      gradientColor: null, // base color of top/bottom gradient on pointer over, defaults to options.arrowsColor if null
      gradientPressedColor: null, // {Color|string|null} color top/bottom gradient when pressed, computed if null
```

I think these would be useful in NumberPicker too.

**Comment by pixelzoom** [comment]
Looking at NumberPicker, I see that there have been significant changes for a11y and phetio.  This will further complicate reconciling ObjectPicker and NumberPicker.   

There is no way that this issue can be completed before publishing Equality Explorer 1.0.   So I'm going to leave it marked as deferred, and anticipate that it will be addressed at some point in the (possibly distant) future, when another sim needs ObjectPicker.  @ariel-phet @amanda-phet FYI.

**Comment by pixelzoom** [comment]
Since NumberPicker and ObjectPicker have diverged so much, and since they have fundamental differences in how they assemble and present the choices... What we should probably do is factor out everything having to do with the "look" of the buttons and the value display, and leave it up to NumberPicker and ObjectPicker to fill in the specifics.

**Comment by pixelzoom** [comment]
With the NumberPicker changes in https://github.com/phetsims/scenery-phet/issues/626 and https://github.com/phetsims/scenery-phet/issues/627, ObjectPicker and NumberPicker are starting to diverge significantly.  At the very least, deprecated listeners should be replaced, ala NumberPicker.

**Comment by pixelzoom** [comment]
In the above commit, I made the following modifications to ObjectPicker, to bring it in line with NumberPicker:

* use an enumeration for ButtonState
* use increment/decrement terminology instead of up/down
* replace deprecated input listeners

**Comment by pixelzoom** [comment]
It's been 4+ years since I opened this issue, and no one has needed ObjectPicker.  So I'm going to go ahead and close this issue.  If/when a sim needs ObjectPicker, the responsible developer can handle generalization and migration to common-code, and I'll be happy to assist.

**Comment by samreid** [comment]
As discovered in https://github.com/phetsims/chipper/issues/946, there are TODOs in the code referring to this issue.  Reopening.

**Comment by pixelzoom** [comment]
TODO deleted. Closing.
