### ISSUE TITLE
FaucetNodeIO: misleading constructor parameter name

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#346]
FaucetNodeIO constructor:

```js
  /**
   * Wrapper type for phet/sun's Faucet class.
   * @param faucet
   * @param phetioID
   * @constructor
   */
  function FaucetNodeIO( faucet, phetioID ) {
    assert && assertInstanceOf( faucet, phet.sceneryPhet.FaucetNode );
    NodeIO.call( this, faucet, phetioID );
  }
```

Beside the lack of type expressions (see https://github.com/phetsims/phet-io/issues/1284)...  The `faucet` parameter name is misleading, since its type is expected to be `FaucetNode`.   By PhET convention, something named `faucet` would typically be a model element, while `faucetNode` would be the corresponding view Node.   So recommended to rename `faucet` to `faucetNode`.

**Comment by pixelzoom** [comment]
Addressed in above commit. @samreid please review.

**Comment by samreid** [comment]
Looks great, thanks, closing.
