### ISSUE TITLE
NumberControl title font regression

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/scenery-phet#347]
It looks like https://github.com/phetsims/scenery-phet/commit/43003c98312542244bfabd73a044e270ceade334#diff-22cf8008e26ed989c8977040d76d6913 added titleFontWeight (with a default of `'normal'`) to NumberControl.

The font weight is generally included in the Font object (which titleFont should be), so I don't see why it should be separate. This change also made the pendulum lab titles non-bold (when they specify a bold font).

@zepumph, as it looks like this was added as part of https://github.com/phetsims/rutherford-scattering/issues/128, do you mind if I remove all usages of titleFontWeight, and convert any usages into using the correct weight in the font?

**Comment by jonathanolson** [comment]
Decided I could move forward and implement the changes. Closing.

**Comment by zepumph** [comment]
Thanks for doing this
