### ISSUE TITLE
erroneous phetioType in PhetFont

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#349]
PhetFont.js:

```js
18 var FontIO = require( 'SCENERY/util/FontIO' ); // TODO: we should have PhetFontIO

38       phetioType: FontIO
```

Two problems:

(1) A TODO was added here without creating an associated GitHub issue. 

(2) The phetioType is misplaced. Either PhetFont should be setting `phetioType: PhetFontIO`, or Font should be setting `phetioType: FontIO`. 

Slack discussion about PhetFont:

Chris Malley [3:51 PM]
Why does MathSymbolFont contain a call to `Tandem.indicateUninstrumentedCode`, while PhetFont does not?

Sam Reid [3:52 PM]
It looks like PhetFont is already instrumented

Chris Malley [3:52 PM]
phetioType?

Sam Reid [3:53 PM]
`Tandem.indicateUninstrumentedCode` is like a TODO that fails when running in PhET-iO as a reminder to instrument that code.

Chris Malley [3:53 PM]
options.phetioType is not in Font because we need to keep it out of scenery? (edited)

Sam Reid [3:54 PM]
I think the original reason was that we didn’t want to require instrumentation of all Font instances.  But it seems the better solution would just be to make tandem optional.

Chris Malley [3:54 PM]
FontIO is described as the IO type for Font.  So shouldn’t it be set in Font?

Sims are generally using PhetFont (or they should be), so aren’t we already instrumenting all font instances? (edited)

PhetFont line 18:  `var FontIO = require( 'SCENERY/util/FontIO' ); // TODO: we should have PhetFontIO`

Sam Reid [4:00 PM]
We should move phetioType: FontIO to Font.js and mark it as Tandem.optional.
I don’t have time to do so right now, but I could work on it later on.

**Comment by pixelzoom** [comment]
Probably also want to look at the call to `Tandem.indicateUninstrumentedCode` in MathSymbolFont. Does it need to be there? Do we play to instrument all MathSymbolFont instances?

**Comment by samreid** [comment]
> (1) A TODO was added here without creating an associated GitHub issue.

Is this policy for every common repo, or only for the ones mentioned in the lint rule (currently limited to joist)?

**Comment by samreid** [comment]
I moved FontIO to Font.js, and removed `indicateUninstrumentedCode` from MathSymbolFont.  Lint-everything is passing.  Aqua is running (no systemic problems).  A regex search (which may be incomplete) indicates Balloons and Static Electricity is using a tandemized font.  Search was:

`tandem: tandem\.createTandem\( '\w+Font`

It checks out OK in the instance proxies.

I also opened https://github.com/phetsims/scenery/issues/732 about simplifying Font.  If that cannot be simplified, I'll reassign this issue to @jonathanolson to see if there's a better way to deal with options and PhetioObject and the string constructor.  Let's go on hold until discussing https://github.com/phetsims/scenery/issues/732

**Comment by jonathanolson** [comment]
> I also opened phetsims/scenery#732 about simplifying Font. If that cannot be simplified, I'll reassign this issue to @jonathanolson to see if there's a better way to deal with options and PhetioObject and the string constructor. Let's go on hold until discussing phetsims/scenery#732

Font now just takes an options object.

**Comment by samreid** [comment]
Font.js looks great after @jonathanolson's changes, reassigning to @pixelzoom to review and see if there is anything else for this issue.

**Comment by pixelzoom** [comment]
Looks good to me. Closing.
