### ISSUE TITLE
branch: configuration

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#350]
Identified by `print-branches.sh`. Most recent commit by @samreid. Please describe.

**Comment by samreid** [comment]
This branch is still under investigation as part of https://github.com/phetsims/tasks/issues/730  Unassigning for now.

**Comment by pixelzoom** [comment]
phetsims/tasks#730 was closed on 4/2.   Is there a reason to keep this branch? Anything to merge to master?

**Comment by pixelzoom** [comment]
Hmmm.. Looks like this branch no longer exists.  @samreid what was it's fate?

**Comment by samreid** [comment]
We no longer need that branch, I'm not sure who deleted it (maybe be?) but we (I?) neglected to close this issue, closing.

**Comment by pixelzoom** [comment]
Due to https://github.com/phetsims/special-ops/issues/196#issuecomment-823486502, this branch was restored.  It will need to be deleted again.  Reopening and self assigning.

**Comment by pixelzoom** [comment]
Re-deleted using GitHub UI.  Closing.
