### ISSUE TITLE
Ruler transparency / opacity, font, length, width inconsistent across sims

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/scenery-phet#352]
Noticed while testing for Masses and Springs 1.0.0-dev.81. This is related to phetsims/QA/issues/103.

In Masses and Springs, the ruler looks like this:

![ms](https://user-images.githubusercontent.com/31285590/36816288-a799f60e-1c9a-11e8-9e35-1e45061effb6.png)

In Pendulum Lab, the ruler looks like this:

![pl](https://user-images.githubusercontent.com/31285590/36816300-ad3c2528-1c9a-11e8-8a34-33e25d85743a.png)

I'm wondering if we should make the look of the ruler consistent across all sims. @phet-steele and I prefer the ruler in Masses and Springs.

**Comment by arouinfar** [comment]
Good observation @lmulhall-phet. In general, RulerNode has a few options for customization, so its appearance may vary, depending on the particular needs of a sim.

For example, the ruler in Coulomb's Law is gray, has 100% opacity, and has some padding between the 0/100 and the end.
![image](https://user-images.githubusercontent.com/8419308/36817353-184c399a-1c9e-11e8-9c61-074483336d35.png)

However, it's still consistent with other ISLC sims. For example, here's the latest in Gravity Force Lab:
![image](https://user-images.githubusercontent.com/8419308/36817404-4c3f6556-1c9e-11e8-9ccd-59820e804b51.png)

While PL and MAS do not share a common repo, they are related sims. Where possible, elements should be consistent across the two. I would be in favor of tweaking the PL ruler to match the one in MAS. 

How does that sound @ariel-phet?

**Comment by ariel-phet** [comment]
@arouinfar @lmulhall-phet - I do not think the ruler needs to be consistent across all sims.

The transparency is important in measuring the position of the masses in Masses & Springs, but less critical in pendulum lab. Pendulum lab was following the older design that makes the ruler more "real-life". However, I am fine if that is changed to a semi-transparent version if we feel that is more useful.

Your call @arouinfar, and I generally agree with the sentiment of PL and MAS being consistent.

**Comment by arouinfar** [comment]
>  I do not think the ruler needs to be consistent across all sims.

I generally agree @ariel-phet, but I think it's nice for related sims to be consistent, where possible. 

For PL, the ruler's primary goal is to set the scale, which I think would still be achievable with a semi-transparent ruler. It may also make measuring the distance to the COM slightly easier. I'll open an issue in the PL repo, and then close this.
