### ISSUE TITLE
put standard math symbols in MathSymbols.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#353]
After discussion with @amanda-phet and discussion in Slack dev-public, we decide it would be good to create MathSymbols.js, so that (a) sims are all using the same math symbols, and (b) it's easy to change the math symbols in the future.

**Comment by amanda-phet** [comment]
Reminder, here is the issue from 2015 where some discussion happened: https://github.com/phetsims/scenery/issues/457 

In that issue is also a link to the google doc keeping track of some of our decisions. The doc should be updated as new decisions are made. Here is that doc: https://docs.google.com/document/d/19DGsx0mXdMAihw7u8M_kx-6jrQCFOrfaBhYYCF3l1Io/edit#

**Comment by pixelzoom** [comment]
MathSymbols.js has been migrated from equality-explorer, and is now used in equality-explorer.  I added some obvious symbols that are not currently used in equality-explorer, but are highly likely to be needed (not equals, unary plus).

Labeling for developer meeting for these purposed:
(1) Make developers aware that they should be using these symbols.
(2) Decide what to about sims that do not use these symbols.

**Comment by samreid** [comment]
Looks good, I recommend to retrofit old sims.

**Comment by pixelzoom** [comment]
I have 2 sims that could be retrofitted, identified by the issues above.

**Comment by jessegreenberg** [comment]
The only sim I am responsible for that uses math symbols is trig-tour. Unfortunately, the symbols are defined in trig-tour-strings_en.json so I won't be able to use MathSymbols.js there.

**Comment by jbphet** [comment]
Expression Exchange currently uses MathSymbolFont in conjunction with the letters x, y, and z to create expressions.  It uses plus, minus, and equals symbols as well.  Would the proposed retrofitting impact this simulation?

Also, the Arithmetic simulation uses the usual plus, minus, multiply, divide, and equals characters.  Would this one need updating?

**Comment by pixelzoom** [comment]
To clarify... The point is that we should all be using one set of constants for these characters.  This ensures that we're all using the same characters, makes it easy to change in the future, and improves readability (e.g. `'\u00D7'` vs `MathSymbols.TIMES`).

**Comment by jonathanolson** [comment]
I've swapped area-model to use these constants. Thanks!

I added the "dot" constant, used for multiplication, notably where the TIMES would be unclear ('x' used as a variable, e.g. x × x). Called it DOT, if anyone has objections, I don't care about the name.

Also, do people mind if I add comments indicating that `'\u002b'` is equivalent to `'+'` and other commonly-used strings? When factoring out constants, I had to do console checks to verify equality, since `'\u002b'` is a bit harder to read. e.g.:
```js
PLUS: '\u002b', // equivalent to '+'
```

**Comment by Denz1994** [comment]
MAS has been updated to include `MathSymbols.js`. I'm with @zepumph on waiting to see how new symbols to `MathSymbols.js` should be added after dev meeting discussion.

**Comment by pixelzoom** [comment]
@jonathanolson asked:
> Also, do people mind if I add comments indicating that '\u002b' is equivalent to '+' and other commonly-used strings?  ...

I started to do this, then decide to just use the ASCII chars wherever ASCII and Unicode are equivalent.  See previous commit.   If anyone strongly prefers using Unicode consistently, we can change it back.

**Comment by zepumph** [comment]
- [ ] resistance-in-a-wire
- [ ] ohms-law

**Comment by jessegreenberg** [comment]
Developer meeting 3/8/18:

Regarding https://github.com/phetsims/scenery-phet/issues/353#issuecomment-371364716, we decided that it is better to use ASCII characters.

**Comment by jessegreenberg** [comment]
@ariel-phet: it would be valuable  to make issues in sims that need to use MathSymbols.js, we don't need to actively chip away at this.

@jonathanolson suggested this get a code review check list item.

@pixelzoom said it is up to each developer to go through and update to use MathSymbols.js

@ariel-phet said to take an hour in the next week to identify. If you want to just fix without making an issue, go for it but make a comment in this issue so we know how much time this issue takes.

**Comment by jbphet** [comment]
We were asked in the 3/8/2018 to identify the sim for which we are responsible that need to be updated to use these symbols.  For me, there are two that clearly need it:

+ Arithmetic
+ Expression Exchange

There are some other cases that are a bit ambiguous.  I'll list them below, and @ariel-phet can say whether an update is needed:

+ Build an Atom - plus and minus symbols on the charge meter
+ Faraday's Law - plus an minus symbols on the voltmeter (both the readout and the connector tabs)
+ Neuron - plus symbols on the ion names, e.g. Na+

The plus and minus symbols are also used on some zoom buttons, and I'm assuming that these do **not** need to be replaced, such as in:

+ custom zoom control buttons in Neuron ZoomControl
+ sun's ExpandCollapseButton
+ scenery-phet's PlusNode and MinusNode, which are used in a bunch of places.

@ariel-phet - can you weigh in on the sims in the 2nd list above and confirm (or not) my thoughts on the third set?

**Comment by samreid** [comment]
Here are the problems I identified in my responsible-dev sims:

* Bending Light  - uses the % sign
* Circuit Construction Kit: family -voltmeter and ammeter have negatives
* Fraction Matcher - equals sign and greater than/less than (stylized, may be scenery nodes)
* Sugar and Salt Solutions  - divided by symbol / in bar chart
* Under Pressure - division symbol

Are we factoring out the `'%'`, or using a unicode for it?

**Comment by pixelzoom** [comment]
@samreid asked:
> Are we factoring out the `'%'`, or using a unicode for it?

```
> '\u0025' === '%'
true
```

... so per https://github.com/phetsims/scenery-phet/issues/353#issuecomment-371540393, we're using `'%'`.

**Comment by ariel-phet** [comment]
@jbphet we will discuss as a group, Certainly for the third group, I see these as UI symbols not really "math" symbols, so I agree, they should remain. 

Group 2 is a bit ambiguous. I suppose it is merely a question of if it is better/cleaner for maintainability

**Comment by jessegreenberg** [comment]
I reviewed sims assigned to me through responsible_dev.md. The only one that uses math symbols is trig-tour, but they symbols have been added to translatable strings so I can't use MathSymbols.js there.

**Comment by samreid** [comment]
Based on @jessegreenberg's comment I opened https://github.com/phetsims/trig-tour/issues/88

**Comment by jonathanolson** [comment]
I'm going to go through my sims and check.

**Comment by jonathanolson** [comment]
I've handled my sims, unassigning.

**Comment by zepumph** [comment]
I have handled my sims, RIAW and OL, added RHO adn OHMS to symbols.

**Comment by samreid** [comment]
@jbphet anything else to do for this issue?

**Comment by pixelzoom** [comment]
To clarify....  Everyone at 3/29/18 developer meeting had taken care of their sims. @jbphet wasn't present, commits looks like he may have addressed his sims, but we weren't sure.  So assigned to @jbphet -- please close when your sims are done.

**Comment by jbphet** [comment]
Yes, I've made the updates in my sims.  Closing.
