### ISSUE TITLE
Measuring tape updates 

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#354]
Moved from https://github.com/phetsims/scenery/issues/745

I'd like to make the following changes to MeasuringTapeNode to support Wave Interference:

1. Add a `baseDragEnded` option, so I can get a callback to test being dropped in the toolbox
2. Add an `interactive` option, so I can easily create an icon (much easier than MeasuringTapeNode.createIcon, which looks like a mess).

**Comment by samreid** [comment]
Committed https://github.com/phetsims/scenery-phet/commit/aac43396d64dd4464addc26694813d6e2908bddc

**Comment by samreid** [comment]
I implemented the proposed changes and am leveraging them in Wave Interference. @ariel-phet can you please recommend someone to review these common code changes?

**Comment by ariel-phet** [comment]
@mbarlow12 are you up for reviewing these?

**Comment by mbarlow12** [comment]
@ariel-phet sure thing! On it today or tomorrow AM.

**Comment by mbarlow12** [comment]
The changes referenced in the above commit look ok. I have a few questions/comments:
- the base and tip drag handlers share a lot of similar code, _might_ be worth considering condensing the drag handlers into a common type.
- baseDragHandler is a method while the tip drag handler is not, is there a use case for starting the tip drag in a similar fashion to `stargBaseDrag()`?
- there seems to be some reference inconsistencies for the `basePositionProperty`. Sometimes it's referenced from `this` and others it's from `options`. If that's intentional, then all's well.

**Comment by samreid** [comment]
(1) Here's a visual diff of the drag handlers:

![image](https://user-images.githubusercontent.com/679486/37632136-564ea192-2bb2-11e8-9328-a48c84d02943.png)

Maybe we could factor out
```js
  if ( options.isTipDragBounded ) {
    var constrainedTipLocation = self._dragBounds.closestPointTo( unconstrainedTipLocation );
    // translation of the tipPosition (subject to the constraining drag bounds)
    self.tipPositionProperty.set( constrainedTipLocation );
  }
  else {
    self.tipPositionProperty.set( unconstrainedTipLocation );
  }
```

(2) I think the reason for `startBaseDrag` is for when the measuring tape is dragged out of the toolbox (which would be by the base instead of the tip).

(3) Good catch, it would be good to be consistent about this.  Not sure if `options.basePositionProperty` or `this. basePositionProperty` is preferable in the constructor.  I guess I'm leaning toward the latter.

Thoughts @mbarlow12?

**Comment by mbarlow12** [comment]
@samreid one thought I had for (1) was to create a dragHandler subtype that would accept a property as an argument. For example, the `start` callbacks do perform the same ops just with different properties. Maybe a MeasuringTapeDragHandler?

The catch is that this is common code, so I'm a little unfamiliar with our best practices in such situations.

For 2 and 3, that all sounds good to me.

**Comment by samreid** [comment]
OK I'll work on moving (3) toward using this.basePositionProperty, then create a new issue for (1).

**Comment by samreid** [comment]
I committed a fix for (3) and created https://github.com/phetsims/scenery-phet/issues/360.  @mbarlow12 can you double check my changes in the preceding commit?  Close if all is well.

**Comment by mbarlow12** [comment]
I checked all instances of `\w+Property`, and none are preceded by `options` after initial assignment—all good. Closing.

**Comment by mbarlow12** [comment]
@samreid  after closing https://github.com/phetsims/scenery-phet/issues/360 is there anything further for these sorts of code reviews (ie smaller changes/common code)?

**Comment by samreid** [comment]
That seems sufficient, thanks for your help.
