### ISSUE TITLE
Migrate Pendulum Lab NumberControl layout to scenery-phet

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#358]
Sam Reid [3:03 PM]
I need a control that looks like this:

Sam Reid [3:03 PM]
uploaded this image: image.png 

Sam Reid [3:03 PM]
What is the best way?

Jonathan Olson [3:03 PM]
NumberControl

Sam Reid [3:04 PM]
Thanks, I’ll take a look

Chris Malley [3:04 PM]
Label and value fields so spaced out looks odd to me.

Sam Reid [3:05 PM]
Here’s the full mock-up for context.  Chris, what do you recommend?

Sam Reid [3:05 PM]
uploaded this image: image.png 

Chris Malley [3:05 PM]
I see no reason not to use the default NumberControl layout, e.g.:

Chris Malley [3:05 PM]
uploaded this image: screenshot_513.png 

Jonathan Olson [3:06 PM]
Looks very similar to Pendulum Lab's layout (PendulumNumberControl), which was decided so that the labels on the left look more like headers/titles

Jonathan Olson [3:06 PM]
uploaded this image: PendulumNumberControl(s) 

Chris Malley [3:06 PM]
Is that one of the implemented layouts?

Sam Reid [3:07 PM]
Yes, it looks just like Pendulum Lab.  Can/should we move the Pendulum one to common code?

Chris Malley [3:07 PM]
I seem to recall that it supports multiple layouts…
So is Pendulum Lab using a NumberControl with a custom layout?

Sam Reid [3:08 PM]
It seems so

Jonathan Olson [3:08 PM]
It is a custom layout. I remember parts of the layout being semi-sim-specific at the time

Sam Reid [3:08 PM]
It supplies a 43-line layout function, and also applies other tweaks

Chris Malley [3:08 PM]
Or is it _not_ using NumberControl in order to achieve a non-standard layout.

Jonathan Olson [3:08 PM]
but I think this is the 3rd time I've seen demand for that general type of layout

Sam Reid [3:08 PM]
Pendulum Lab, Wave Interference and what?

Jonathan Olson [3:09 PM]
It's using NumberControl with a custom layout

Chris Malley [3:09 PM]
good
then migrate the custom layout to NumberControl.

Jonathan Olson [3:10 PM]
uploaded this image: masses and springs 

Jonathan Olson [3:10 PM]
but that one's slightly different, so I'm not sure it counts

Sam Reid [3:10 PM]
What about this?
    ```var trackWidth = 500;
    var testControl = new NumberControl( title, property, range, _.extend( {}, numberControlOptions, {
      trackSize: new Dimension2( trackWidth, PendulumLabConstants.TRACK_HEIGHT )
    } ) );

    var testWidth = testControl.width;
    testControl.dispose();

    NumberControl.call( this, title, property, range, _.extend( {}, numberControlOptions, {
      trackSize: new Dimension2( trackWidth + PendulumLabConstants.RIGHT_CONTENT_WIDTH - testWidth, PendulumLabConstants.TRACK_HEIGHT )
    } ) );```

Chris Malley [3:11 PM]
Sure would be nice if designers understood what layouts are available. Or UI components, for that matter.

Sam Reid [3:11 PM]
Jon do you want to move that layout function to NumberControl, or should I?

Jonathan Olson [3:11 PM]
Ahh yes, our lovely "we don't allow specifying how wide this component is, so you need to create one with content, measure how much UI it adds around the content, and use that for your ACTUAL stuff"
@samreid, go ahead, let me know if there are issues?

Sam Reid [3:12 PM]
Will do, wish me luck

Chris Malley [3:12 PM]
Would also be nice if developers questioned layouts that aren’t one of the available layouts.  So we could identify new layouts that are really needed (like this one), put it in common code, and not end up with multiple variants (like we have here with MAS, PL, WI)

Jonathan Olson [3:13 PM]
MAS uses built-in layouts with different options

Chris Malley [3:13 PM]
@samreid can you address all 3 sims (MAS, PL, WI) during this migration?

Jonathan Olson [3:14 PM]
PL had different constraints that I wasn't sure would ever apply to another sim, so I didn't want to put a PL-specific layout in common code

Chris Malley [3:14 PM]
What do you mean “MAS uses built-in layouts”?
Do you mean it’s not using NumberControl?

Jonathan Olson [3:14 PM]
`layoutFunction: NumberControl.createLayoutFunction1( ... )`

Chris Malley [3:15 PM]
So why can’t MAS use the same layoutFunction as PL and WI?
And if it can’t use the same layoutFunction for some reason, that seems like a defect in MAS.

Jonathan Olson [3:15 PM]
I don't know the design, I don't know if it was supposed to be the same. I just said it was similar

Chris Malley [3:16 PM]
It looks similar enough that I don’t think designers would have a problem with using the same layout in MAS. (edited)

Jonathan Olson [3:16 PM]
and the PL version reads out at least 4 custom PL-specific options in creating its layout

**Comment by samreid** [comment]
Moved in preceding commits, @jonathanolson can you please review/test?

**Comment by jonathanolson** [comment]
Looks good, snapshot comparison agrees. Thanks!
