### ISSUE TITLE
TimerNode is specifying the same values as the defaults

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#359]
TimerNode currently has this code:

```js
    var roundedRectangle = new ShadedRectangle( container.bounds.dilated( panelPad ), {
      baseColor: new Color( 80, 130, 230 ),
      cornerRadius: 10
    } );
```

However, the cornerRadius and baseColor are identical to the defaults in ShadedRectangle.  Hence they should be removed from the TimerNode options.

This came up in Wave Interference because I wanted to match the baseColor and cornerRadius of TimerNode--factoring it out to ShadedRectangle seems a reasonable way to do it.

**Comment by samreid** [comment]
Fixed above, @ariel-phet can you recommend a reviewer?  It should take <10 minutes.

**Comment by ariel-phet** [comment]
Asking @jessegreenberg to give this a quick go.

**Comment by jessegreenberg** [comment]
Change looks good @samreid, can't see why this would cause issues. As a sanity check I checked pendulum-lab and masses-and-springs before/after commits and TimerNode's in both sims looked identical. Closing.
