### ISSUE TITLE
Extra "chrome" beneath faucet control looks odd and distracting

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#36]
Can we get rid of the extra gradient beneath the faucet controls?  It looks kind of like a bug in the rendering.

Here's a picture of the faucet with its controls:
![faucetnored](https://cloud.githubusercontent.com/assets/679486/2550357/3489d5bc-b682-11e3-9900-d0d223981d5f.png)

Here I highlighted the region that looks odd:
![faucetred](https://cloud.githubusercontent.com/assets/679486/2550360/3be91638-b682-11e3-9e21-b3f85c3c46ea.png)

I think it is odd and also visually distracting.  Why not "mount" the slider directly to the top of the faucet pipe?

**Comment by pixelzoom** [comment]
@ariel-phet Should this be closed? I don't believe that the "chrome" is going away.

**Comment by ariel-phet** [comment]
Yes, this can be closed.
