### ISSUE TITLE
Factor out listener code in MeasuringTapeNode?

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#360]
From https://github.com/phetsims/scenery-phet/issues/354

@mbarlow12 said:

> the base and tip drag handlers share a lot of similar code, might be worth considering condensing the drag handlers into a common type.

**Comment by samreid** [comment]
Here's a visual diff of the drag handlers:

![image](https://user-images.githubusercontent.com/679486/37632136-564ea192-2bb2-11e8-9328-a48c84d02943.png)

Maybe we could factor out
```js
  if ( options.isTipDragBounded ) {
    var constrainedTipLocation = self._dragBounds.closestPointTo( unconstrainedTipLocation );
    // translation of the tipPosition (subject to the constraining drag bounds)
    self.tipPositionProperty.set( constrainedTipLocation );
  }
  else {
    self.tipPositionProperty.set( unconstrainedTipLocation );
  }
```

**Comment by samreid** [comment]
@mbarlow12 said:

> @samreid one thought I had for (1) was to create a dragHandler subtype that would accept a property as an argument. For example, the start callbacks do perform the same ops just with different properties. Maybe a MeasuringTapeDragHandler?
> 
> The catch is that this is common code, so I'm a little unfamiliar with our best practices in such situations.

**Comment by samreid** [comment]
My instinct is that the factored out code will be more difficult to read/understand/maintain than the independent code, but I'm not opposed to someone taking the time to try it out.  @mbarlow12 if you want to go for it, I'll review.  Another possibility would be to wait on this until we are visiting MeasuringTape again, say for a11y or phet-io.

**Comment by mbarlow12** [comment]
@samreid is it correct that the `_isTimUserControlled` setting determines whether dragging the base moves just the base itself or the tip as well?

**Comment by samreid** [comment]
Yes, if the user is dragging the tip, then drags the base at the same time (say, on iPad with multitouch), then the tip won't translate.

**Comment by mbarlow12** [comment]
@samreid After looking at things a bit more, I agree with you regarding keeping the dragHandlers as they are. I also don't think it makes sense to factor out
```js
  if ( options.isTipDragBounded ) {
    var constrainedTipLocation = self._dragBounds.closestPointTo( unconstrainedTipLocation );
    // translation of the tipPosition (subject to the constraining drag bounds)
    self.tipPositionProperty.set( constrainedTipLocation );
  }
  else {
    self.tipPositionProperty.set( unconstrainedTipLocation );
  }
```
for a minimal line reduction—seems like it would feel out of context and, like you said, less readable. Closing.
