### ISSUE TITLE
BucketFront visual artifacts

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/scenery-phet#361]
I saw some bugginess in the fractions bucket:
![bucket-fractions](https://user-images.githubusercontent.com/480878/37789634-1716ea06-2dca-11e8-86c8-9ab1497a03e9.PNG)
where it looked polygonal in a bit. On close inspection, the edge of the bucket looks improperly calculated (in BucketFront):
![bucket-fractions-close](https://user-images.githubusercontent.com/480878/37789665-287fc5ba-2dca-11e8-81d4-d1939fba0895.PNG)
and this is also an issue (with a slightly different presentation of the bug) in things like Build an Atom:
![bucket-build-an-atom-close](https://user-images.githubusercontent.com/480878/37789679-3443b67c-2dca-11e8-8321-7176793e98e0.PNG)
It should be curved all the way until where it meets the bucket's "side" line.

@ariel-phet, should I tackle this myself? It's a fairly independent issue that might be suitable for someone else if desired.

**Comment by ariel-phet** [comment]
@jonathanolson  - good eye. I would say this is low priority (since you are the first person to point it out!). 

Can you give me an estimate of what it would take to fix this, and then assign back to me?

**Comment by jonathanolson** [comment]
> Can you give me an estimate of what it would take to fix this, and then assign back to me?

My way of estimating something like this is to look into it (so I have a commit above that fixes it).

Looks like this was introduced with a workaround for https://github.com/phetsims/build-an-atom/issues/173. I've applied a fix (basically making the offset smaller by a factor of 10, which should presumably keep the workaround but make it basically invisible).

@jbphet can you review?

**Comment by jbphet** [comment]
Looks good to me, and thanks for adding comments.  Closing.
