### ISSUE TITLE
standardize the "Info" button

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#363]
Related to https://github.com/phetsims/equality-explorer/issues/51, where we're considering adding an "Info" button.

Two sims currently use the international "Info" symbol on a button.  They are masses-and-spring and pendulum-lab.  In both cases, the button uses a fontawesome icon and looks like this:

![screenshot_524](https://user-images.githubusercontent.com/3046552/37985692-b93f4a2c-31b6-11e8-9b38-17f406521c7c.png)

Two things to be done:

(1) Decide on the look of the "Info" button, to be used in all PhET sims.

(2) Create SCENERY_PHET/buttons/InfoButton, instead of duplicating code.

---

Slack discussion about the above button:

Chris Malley [11:45 AM]
Used in masses-and-springs and pendulum-lab.

Amanda McGarry [11:45 AM]
oh really? I didn’t realize. I’ll look at those sims
I see, they use a round button with a blue icon
thanks. Maybe we can use something similar

Chris Malley [11:49 AM]
Why wouldn’t we use the same button?

Amanda McGarry [11:50 AM]
We can, I just don’t love it. It’s fine we can just use the same one.

Chris Malley [11:50 AM]
If you don’t love it, then let’s discuss standardizing.  There’s no reason for PhET to have multiple different Info buttons.

Amanda McGarry [11:50 AM]
of course, I was thinking of talking to Amy about it and if she tried other designs
Like, why not a square button. the round one makes sense, but the i looks off centered even though I’m sure it’s not.. it’s just the shading

Chris Malley [11:51 AM]
I think the round button is very appropriate, since the icon is generally round.
Off-center is an illusion with _all_ round buttons, caused by the drop shadow.  One of the many reasons why I personally prefer flat buttons.

Amanda McGarry [11:53 AM]
The blue is also funny to me. why not black? I was just going to ask Amy these questions because I figured they tried different variations and came to this one for a reason
we use sooo many different blues in all our PhET sims...

Chris Malley [11:54 AM]
Black would be a fine choice for the icon.   The blue is a fill that’s being applied, independent of the icon.

Amanda McGarry [11:55 AM]
anyway, I’ll include this button and make some mockups that include it and the info dialog

**Comment by pixelzoom** [comment]
The info button in masses-and-springs (added 10/6/17) is a blatant copy-paste of code from pendulum lab (added 8/29/17).  This issue should have been dealt with when the first copy needed to be made.

**Comment by pixelzoom** [comment]
I factored `InfoButton` out of masses-and-springs and pendulum-lab. @Denz1994 @jonathanolson FYI.

**Comment by pixelzoom** [comment]
@amanda-phet FYI, there is now a common-code button called `InfoButton`.   Modifications to the "look" should be made there.  Sims that are not using this button should use it.

**Comment by amanda-phet** [comment]
Discussed with @arouinfar and I don't think we need any design discussions since the actual icon color can be specified in the sim.

**Comment by pixelzoom** [comment]
Do you mean the icon _fill_?  (the blue part). That cannot currently be specified in InfoButton.

**Comment by amanda-phet** [comment]
ah, I misunderstood when you said "The blue is a fill that’s being applied, independent of the icon."

**Comment by pixelzoom** [comment]
I've added an option to specify the icon fill.

**Comment by pixelzoom** [comment]
To clarify....

Here's what InfoButton looks like with default settings. Black icon on a gray button.

![screenshot_525](https://user-images.githubusercontent.com/3046552/37991111-83e4ee0e-31c5-11e8-9bec-adc11804ccf3.png)

Here's what InfoButton looks like with a blue icon (`iconFill: 'rgb( 41, 106, 163 )'`), as in masses-and-springs and pendulum lab:

![screenshot_526](https://user-images.githubusercontent.com/3046552/37991128-94856a0e-31c5-11e8-83ed-9197efd93089.png)

Here's what InfoButton looks like when you set the button color (`baseColor`) to the standard PhET yellow. Note the the color shows through the hole (which is the 'i') in the fontawesome icon.

![screenshot_527](https://user-images.githubusercontent.com/3046552/37991196-cc20e556-31c5-11e8-819a-951c903df217.png)

**Comment by amanda-phet** [comment]
Looks great to me.
