### ISSUE TITLE
HelpContent should use nested option objects 

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#364]
I saw this while working on https://github.com/phetsims/scenery/issues/748,

I think this would make things much easier to implement the accessibility features we want. For example. . .
```
        a11yIconTagName: 'li',
        a11yIconLabelTagName: null,
        a11yIconContainerTagName: null,
        a11yIconAccessibleLabel: null,
        a11yIconPrependLabels: false
```
all of those icon options wouldn't have to be explicitly set to a default.

@jessegreenberg, you were working on this on Friday, was there an issue you were looking at? If so please take over there.

UPDATE: this applies to `SliderControlsHelpContent` and `GeneralControlsHelpContent` as well.

**Comment by zepumph** [comment]
Here is the schema that the project is using for nested options. https://github.com/phetsims/tasks/issues/730#issuecomment-370860967

**Comment by jessegreenberg** [comment]
Done, I think this is much improved. @zepumph would you please review? In particular,` labelWithIcon` is using nested options,  but `labelWithIconList` is not because all  options apply to one node. The  result is that the options for the two functions look very different but do similar things. Is this OK?

**Comment by zepumph** [comment]
Good stuff here, I really like what you did with the nesting in labelWithIcon.

>     * @return {Object} - Object that looks like {label: <Node>, icon: <Node>}

Why is `labelWithIcon` not returning a node? That seems weird, and likely a bug to me. At the very least all HelpContent factory functions should return the same type.

I have the same question for  `labelWithIconList`, but it is also documented ideally but incorrectly (as an HBox).

>but labelWithIconList is not because all options apply to one node.

I think that you should still use the nested options, so that it is clear that these options aren't being applied to the "Label with icont list Node" but rather just the icon list (vbox), and should probably be named with that in mind, something like `iconListVBoxOptions`/`iconsVBoxOptions`?

Back to you

**Comment by jessegreenberg** [comment]
> Why is labelWithIcon not returning a node?

The reason it is not a node is so HelpContent can manage horizontal layout of vertically layered groups of help content, like this
![capture](https://user-images.githubusercontent.com/6396244/38588724-9cb96d18-3ce4-11e8-83de-656792184326.PNG)

HelpContent makes sure that the icons for each group are aligned.

**Comment by jessegreenberg** [comment]
Fixed and tried to clarify JSDoc with above commit.

**Comment by jessegreenberg** [comment]
> I think that you should still use the nested options...

This was done with the above commits. @zepumph could  you please review the above comments?

**Comment by zepumph** [comment]
Looks good. Thanks @jessegreenberg!

**Comment by jessegreenberg** [comment]
Thanks @zepumph, is more work needed for this issue?

**Comment by zepumph** [comment]
nopedy
