### ISSUE TITLE
Add a glass option to LaserPointerNode

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#366]
LaserPointerNode currently looks like this:

![image](https://user-images.githubusercontent.com/679486/38211447-b7fe0c28-3677-11e8-8f4a-46f15b3699f9.png)

We want to add a glass part for one sim like this:

![image](https://user-images.githubusercontent.com/679486/38211453-bebae752-3677-11e8-8fc7-a07c0e279e13.png)

I asked in slack:

> Should that glass part be an option coded in LaserPointerNode.js or use composition/inheritance to add it in another file?

@jessegreenberg replied:

> Seems like it could be useful for other sims later, so I have a slight preference for adding to LaserPointerNode.js

And @jbphet gave that a 👍, so I created this issue.

@arouinfar said:

> The base color used for the glass is rgb(188, 225, 238).  Anything in that general realm would be fine

**Comment by samreid** [comment]
I should also point out that the reason we are adding the glass is since we don't want the object to be perceived as a "laser".  That being said, I don't think that's enough of a good reason to move this code elsewhere.  And renaming LaserPointerNode to LaserOrMaybeLEDOrOtherLightSourceNode doesn't sound too catchy.  Maybe LightSourceNode, since laser light is a form of light?

**Comment by arouinfar** [comment]
@samreid I like the sound of LightSourceNode.

**Comment by samreid** [comment]
Implemented above, and demonstrated in http://localhost/scenery-phet/scenery-phet_en.html?brand=phet&ea&screens=3&component=LaserPointerNode as well as http://localhost/wave-interference/wave-interference_en.html?brand=phet&ea

@ariel-phet can you please assign a reviewer?

To the reviewer: I'm using the "nested options" strategy we discussed in https://github.com/phetsims/tasks/issues/730, and I'd like to know what name you recommend for the file, please see discussion in the preceding two comments.

**Comment by ariel-phet** [comment]
@zepumph -- batter up!

**Comment by samreid** [comment]
@Denz1994 said:

![image](https://user-images.githubusercontent.com/679486/38258227-1ec3cfa4-371f-11e8-9cbb-e84fd185487c.png)

> Sorry for the late response. M&S is using a laserPointNode as handle for a movableLine. I vote for keeping it an option in laserPointNode, similar to the “hasButton” option.

**Comment by zepumph** [comment]
This looks good to me, I like your implementation of the nested options @samreid. One suggestion is to include a sentence somewhere explaining what the "glass" is.

**Comment by samreid** [comment]
I described what the glass is in the commit, @zepumph can you please review?

**Comment by samreid** [comment]
Thanks for the review, closing.
