### ISSUE TITLE
We need a FrequencySlider

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#371]
At the Wave Interference design meeting, we concluded we need to be able to reverse the WavelengthSlider, so that the high frequencies are shown to the right instead of the left (that is, we are using it as a "Frequency" slider instead of a Wavelength slider.)

My initial thought for the API would be to add an option like:

```js
increasingWavelength: true
```

or maybe something like:
```js
blueOnTheLeft: true
```

However, I realized that if I swapped the min and max like so:

```js
    var lightFrequencySlider = new WavelengthSlider( model.wavelengthProperty, {
      minWavelength: VisibleColor.MAX_WAVELENGTH,
      maxWavelength: VisibleColor.MIN_WAVELENGTH,
```
and disabled the corresponding assertion statements that checked that min < max, then it rendered properly (though the input listener was broken):

![image](https://user-images.githubusercontent.com/679486/38706824-e2e8d16a-3e6b-11e8-866e-cba090b343ad.png)

However, if we stick with that pattern, then min and max may not be the best prefixes (since max would be greater than min).

@pixelzoom can you please recommend an API for this before I proceed?

**Comment by samreid** [comment]
> However, if we stick with that pattern, then min and max may not be the best prefixes (since max would be greater than min).

For instance, we could go with `leftWavelength` and `rightWavelength`.

**Comment by samreid** [comment]
It also crossed my mind that we might be able to flip the slider with a scenery node scale (-1,1), but is that a hack?

**Comment by samreid** [comment]
Indeed, putting `scale: new Vector2( -1, 1 )` in the options seems to work properly (including input listeners), maybe we should go with that?

**Comment by samreid** [comment]
I renamed the issue to "We need a frequency slider" because if you only reverse the wavelengths, you do not have the right "spacing" between frequency points.  That is, we will want the transform to be linear in frequency (not -1/Hz), which is different.  

The WavelengthSlider currently has an api: `minWavelength`, `maxWavelength`.  We could still use those values for a frequency slider if you compute `minWavelength = speed of light / maxFrequency` etc.

I'll hold off until I can discuss the API with @pixelzoom.

**Comment by pixelzoom** [comment]
It sounds to me like there are enough differences that we may want to create a new `FrequencySlider`, rather than trying to coerce `WavelengthSlider` into handling both wavelength and frequency.  Then see what bits `WavelengthSlider` and `FrequencySlider` share, and factor out a base type.

**Comment by samreid** [comment]
I renamed SpectrumNode => WavelengthSpectrumNode and confirmed it looks identical in Molecules and Light.  Committing.

**Comment by pixelzoom** [comment]
I won't have time to look at this until next week.  But hopefully none of these changes make it difficult to add UV and IR to WavelengthSlider, as is required for https://github.com/phetsims/scenery-phet/issues/211 (needed by MOTHA).

**Comment by samreid** [comment]
> But hopefully none of these changes make it difficult to add UV and IR to WavelengthSlider, as is required for #211 (needed by MOTHA).

I introduced a new type `SpectrumSlider` which takes a min value, max value and color mapping function.  I expect it would make it easier to add UV and IR.  For instance, in the visible range, you would return `VisibleColor.wavelengthToColor()`, and in the UV range you could return `Color.gray`.  You could even use that function to add the vertical lines, if they are still desired.  The trick will be adding the text in the track--we may wish to add getter for the track node to make that easy, or a `add/removeTrackChild` method on `SpectrumSlider`.

**Comment by samreid** [comment]
I finished creating FrequencySlider, kept the same interface for WavelengthSlider, and renamed SpectrumNode => WavelengthSpectrumNode.  I recommend the changes be reviewed since (a) they are used in several sims (b) they will affect how we proceed with #211 and (c) I have some questions for the reviewer:

- [ ] I couldn't figure out why the value was being clamped in WavelengthSlider before--I removed it so SpectrumSlider is more general, and can handle default values between 0-1.  If necessary, we could add an option for flooring, but I don't know if that's necessary/valuable.
- [ ] I followed the same pattern for strings as was used for the wavelength, even though it is an older pattern, is that OK or should we use the new template string pattern (and mismatch with the wavelength slider)?
- [ ] For default text display for frequency, I chose to use Tera Hz (THz), is that OK?

@ariel-phet can you please prioritize/schedule/delegate?

**Comment by pixelzoom** [comment]
@samreid said:
> renamed SpectrumNode => WavelengthSpectrumNode

I see both SpectrumNode and WavelengthSpectrumNode in scenery-phet, both with commits on 4/13/2018.  Please clarify.

**Comment by pixelzoom** [comment]
@samreid asked:
> I followed the same pattern for strings as was used for the wavelength, even though it is an older pattern, is that OK or should we use the new template string pattern (and mismatch with the wavelength slider)?

New code should use the new pattern.  FrequencySlider is new code.

**Comment by pixelzoom** [comment]
I see these assertions in FrequencySlider:

```js
    assert && assert( typeof options.minValue === 'undefined', 'minValue is supplied by FrequencySlider' );
    assert && assert( typeof options.maxValue === 'undefined', 'maxValue is supplied by FrequencySlider' );
```

Why not this?

```js
    assert && assert( options.minValue === undefined, 'minValue is supplied by FrequencySlider' );
    assert && assert( options.maxValue === undefined, 'maxValue is supplied by FrequencySlider' );
```

**Comment by pixelzoom** [comment]
@samreid asked:
> - [ ] I couldn't figure out why the value was being clamped in WavelengthSlider before--I removed it so SpectrumSlider is more general, and can handle default values between 0-1. If necessary, we could add an option for flooring, but I don't know if that's necessary/valuable.

I have no recollection.  If you remove it, test thoroughly.

> - [ ]  I followed the same pattern for strings as was used for the wavelength, even though it is an older pattern, is that OK or should we use the new template string pattern (and mismatch with the wavelength slider)?

New code should use the new pattern.  FrequencySlider is new code.

> - [ ] For default text display for frequency, I chose to use Tera Hz (THz), is that OK?

No idea. Probably a question for designers.

**Comment by samreid** [comment]
From https://github.com/phetsims/scenery-phet/issues/371#issuecomment-381473785

The question is about whether to use `x.y===undefined` or `typeof x.y==='undefined'`.  They seem equivalent, I'll change to the former.

**Comment by samreid** [comment]
Remaining work:

- [ ] use x.y===undefined
- [ ] Playing with FrequencySlider in the scenery-phet demo... the arrow buttons don't work.
- [ ] I have no recollection. If you remove it, test thoroughly.
- [ ] New code should use the new pattern. FrequencySlider is new code.

**Comment by samreid** [comment]
I addressed the issues raised during review, @pixelzoom anything else to do before closing?
