### ISSUE TITLE
ContextLossFailureDialog problems

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#373]
Related to https://github.com/phetsims/joist/issues/413#issuecomment-384010740, where the Dialog close button is now mandatory. 

ContextLossFailureDialog has overlap of content and button, e.g.:

![screenshot_591](https://user-images.githubusercontent.com/3046552/39261327-5d1dbe02-4879-11e8-93b0-76a801d8bcc9.png)

**Comment by pixelzoom** [comment]
I addressed the overlap problem by increasing the margins, the same approach that @jonathanolson used for UpdateDialog.  And I added ContextLossFailureDialog to the scenery-phet demo so that it's not such a pain to test.   Here's what it looks like now:

![screenshot_592](https://user-images.githubusercontent.com/3046552/39262067-91f28bc4-487b-11e8-8239-dcf53bb479dd.png)

But there seems to be a bigger problem here.  Unless the user clicks the "Reload" button, the sim is going to be messed up.  Should there be a close button?  Should they be allowed to click outside the Dialog to close it without reloading (a pre-existing problem)?   

Assigning to @jonathanolson for comment.

**Comment by jonathanolson** [comment]
I don't feel strongly either way. @ariel-phet thoughts?

**Comment by pixelzoom** [comment]
Another option:

(4) Override `hide` so that reload is done regardless of how the dialog is closed.  Trivial.

I'm going to do this for now.

**Comment by pixelzoom** [comment]
The sim is now reloaded regardless of how the dialog is dismissed.  Over to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good to me.
