### ISSUE TITLE
CT is unhappy with ContextLossFailureDialog in demo app

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#375]
Related to https://github.com/phetsims/scenery-phet/issues/373, reported by @phet-steele.

When I added ContextLossFailureDialog to scenery-phet's demo, that made CT unhappy.  During fuzz testing, it's pressing the Reload button, which reloads the page.

I brainstormed with @phet-steele about this, and decided that we don't want to change CT.  Instead, I'll add an option to ContextLossFailureDialog that allows the client to change the listener for the Reload button.

**Comment by pixelzoom** [comment]
Work completed in above commit. @phet-steele please review, close if all is well.

**Comment by phet-steele** [comment]
CT is happy with the workaround, thanks @pixelzoom.
