### ISSUE TITLE
Disable trash button looks very clickable

### ISSUE THREAD

**Issue by phet-steele** [phetsims/scenery-phet#383]
Not sure what happened to the trash button (can't find discussions). Here is what the good **disabled** button looked like in masses-and-springs 1.0.0-dev.80 (randomly chose dev version out of a hat):

<img width="117" alt="screen shot 2018-06-05 at 11 55 47 am" src="https://user-images.githubusercontent.com/5863899/40993762-abc7607c-68b7-11e8-9d47-f880956e8f5c.png">

Here is what the bad button looks like in masses-and-springs 1.0.0-dev.109:

<img width="107" alt="screen shot 2018-06-05 at 11 56 12 am" src="https://user-images.githubusercontent.com/5863899/40993764-abf82a7c-68b7-11e8-919d-5fc4a2bf378e.png">

It now looks much more clickable in dev.109 since we've lost the "gray-out". @arouinfar this button is now problematic IMO; I've tried to mistakenly press it multiple times. I checked pendulum-lab on master and it now has the same discrepancy with the published version. @Denz1994 @jonathanolson not sure how this button changed, but it certainly is a common issue.

Just for the record, here is what the button looks like when you CAN press it, in both versions:

<img width="96" alt="screen shot 2018-06-05 at 11 55 56 am" src="https://user-images.githubusercontent.com/5863899/40993763-abe088ea-68b7-11e8-943f-a2fb8b20d695.png">

Seen on macOS 10.13.4 Chrome. For phetsims/QA/issues/126.

<details>
<summary>Troubleshooting Information</summary>

URL: https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-dev.109/phet/masses-and-springs_all_phet.html
Version: 1.0.0-dev.109 2018-06-04 18:26:22 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
Language: en-US
Window: 1920x1013
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"37d5839c","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"7d12527d","branch":"master"},"dot":{"sha":"bd4d7035","branch":"master"},"griddle":{"sha":"7be25724","branch":"master"},"joist":{"sha":"85b10c15","branch":"master"},"kite":{"sha":"3b76b24a","branch":"master"},"masses-and-springs":{"sha":"ff22d8d5","branch":"master"},"phet-core":{"sha":"a34b9659","branch":"master"},"phet-io":{"sha":"851c0e4c","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"5204ea8e","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"ccaaaa4b","branch":"master"},"phet-io-wrappers":{"sha":"d4607c36","branch":"master"},"phetcommon":{"sha":"ddb76c0c","branch":"master"},"query-string-machine":{"sha":"1f2322e4","branch":"master"},"scenery":{"sha":"dc89d619","branch":"master"},"scenery-phet":{"sha":"4d719538","branch":"master"},"sherpa":{"sha":"ded365aa","branch":"master"},"sun":{"sha":"7addb3e6","branch":"master"},"tandem":{"sha":"3e1c8fd3","branch":"master"},"twixt":{"sha":"050e8f19","branch":"master"}}
</details>

**Comment by jonathanolson** [comment]
Was working after the refactoring in pendulum lab. I'm going to bisect to determine when it started failing.

**Comment by jonathanolson** [comment]
Looks like the offending commit is https://github.com/phetsims/sun/commit/91d665826dcbe7afcca1a0b63432932f88f995ce.

**Comment by arouinfar** [comment]
@phet-steele good catch. I agree this is problematic, so I'm glad @jonathanolson found the offending commit.

**Comment by jonathanolson** [comment]
@phet-steele can you verify that @jbphet's commit fixes this in master?

**Comment by lmulhall-phet** [comment]
@jonathanolson, @jbphet, it seems to be fixed in master.

**Comment by phet-steele** [comment]
I see, so we just missed one from phetsims/sun/issues/173. Looks good, thanks for the fix @jbphet @jonathanolson.
