### ISSUE TITLE
precision problem with NumberControl arrows

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#384]
NumberControl has a precision problem, discovered while working on https://github.com/phetsims/hookes-law/issues/52.  In the listeners for the arrow buttons, code like this is supposed to constrain the value to increments of some delta:

```js
186 var value = numberProperty.get() + delta;
187 value = Util.roundSymmetric( value / delta ) * delta; // constrain to delta
```

For some small deltas, this simply doesn't work.  Example:

```
> 0.008 + 0.001
0.009000000000000001
> dot.Util.roundSymmetric( ( 0.008 + 0.001 ) / 0.001 ) * 0.001
0.009000000000000001
```

@jonathanolson suggested using this algorithm (use 1/delta) for delta < 1, but noted that "it’s still… approximate, but it works in way more cases. the approximation happens to be exact in that case".   

```
> dot.Util.roundSymmetric( ( 0.008 + 0.001 ) * 1000 ) / 1000
0.009000000000000001
```

Perhaps a better approach would be to use `Util.toFixedNumber` to limit value to the same number of decimal places as delta.

**Comment by pixelzoom** [comment]
I added Util `numberOfDecimalPlaces` and the convenience function `roundToInterval`.  @jonathanolson would you mind reviewing, since you're somewhat familiar with this from Slack? If you'd prefer a different name for `roundToInterval`, feel free to change.

**Comment by pixelzoom** [comment]
Oops, let me add UtilTests before @jonathanolson reviews.

**Comment by pixelzoom** [comment]
Unit tests pushed. Back to @jonathanolson.

**Comment by jonathanolson** [comment]
The dot commits look good to me, thanks!
