### ISSUE TITLE
PlayPauseButton and StepButton have different names for the same Property

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#388]
Discovered while working on Gas Properties.

PlayPauseButton has constructor parameter `{Property.<boolean>} runningProperty`.
StepButton has option `{Property.<boolean>} playingProperty`.
These buttons are often used together.
Both implemented by @samreid.

Any objection to using the same name in both cases?
Any preference on which name?

**Comment by samreid** [comment]
Perhaps `isPlayingProperty` would be clearest for both cases.  What do you think?

**Comment by pixelzoom** [comment]
Renamed to `isPlayingProperty`.  @samreid have a look, then close.

**Comment by samreid** [comment]
The renaming looks complete and correct, closing.

**Comment by jessegreenberg** [comment]
It looks like sims using StepButton option `playingProperty` weren't updated after the rename to use `isPlayingProperty`.

**Comment by jessegreenberg** [comment]
Updated usages with the above commits, reclosing.
