### ISSUE TITLE
When is it necessary to use the `dragTarget` pattern?

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#394]
As discussed in https://github.com/phetsims/wave-interference/issues/23#issuecomment-412501329, TimerNode uses a `dragTarget` which listeners should be attached to instead of `this`.  Is this because `this` has buttons on it?  When else would we benefit from, or be required to use, this pattern?

**Comment by pixelzoom** [comment]
Short answer: You need to use this pattern any time that the thing that you're dragging has interactive subcomponents (buttons, sliders, etc).   If it's a common-code component (like TimerNode), you could override `addInputListener` and `removeInputListener` to add the listener to the appropriate subcomponent, but that may be more trouble than it's worth.

**Comment by samreid** [comment]
Makes sense to me, closing.
