### ISSUE TITLE
add support for consecutive line breaks to MultiLineText

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#4]
... for example: 'Hello\n\nWorld'

One way to do this would be to look for consecutive line breaks, then insert a sun.Rectangle (stroke:null, fill:null) whose height is equal to the height of some capital letter (eg 'X').

Other suggestions?

**Comment by samreid** [comment]
I tested a few `\n` in the credits, reviewed the change set and it seems this will work well, thanks @pixelzoom
