### ISSUE TITLE
Add a buttonXSpacing option to TimerNode

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#400]
From https://github.com/phetsims/scenery-phet/issues/372#issuecomment-419196541:

@pixelzoom said TimerNode should have an option `buttonXSpacing: 5` that can be changed if you want more/less space between the buttons.

**Comment by samreid** [comment]
Added in the preceding commit, ready for @Denz1994 review as part of https://github.com/phetsims/scenery-phet/issues/403

**Comment by Denz1994** [comment]
The `buttonSpacing` options works as expected, except when the buttons are spread further than the width of the `TimerNode`. I would expect that if the buttonSpacing value makes the buttons exceed the width of the TimerNode, then the buttons should stop expanding outward. However, it seems like any excess horizontal spacing gets converted into vertical spacing. The below image is produced with a spacing of `buttonSpacing: 20`

![image](https://user-images.githubusercontent.com/13894380/46157054-e5954900-c248-11e8-9001-125678cf760f.png)

**Comment by Denz1994** [comment]
Also the `buttonSpacing` option doesn't handled negative numbers well. It causes the buttons to over lap. Maybe the `buttonSpacing` option can be limited (using an assertion) to a value within the horizontal bounds of the `TimerNode` with a slight margin so the buttons aren't directly on the edge of the `TimerNode`. 

Or maybe `TimerNode` can have static bounds so the whole timer doesn't change size. That approach may conflict with the decision made regarding https://github.com/phetsims/capacitor-lab-basics/issues/244#issuecomment-425137729. Assigning @samreid for added input.

**Comment by pixelzoom** [comment]
> Also, the buttonSpacing option doesn't handle negative numbers well.

`assert && assert( options.buttonXSpacing >= 0, '...' );`

**Comment by samreid** [comment]
Thanks for taking this for a test drive @Denz1994, I added 2 commits to address the issues you raised.  Can you please review?

**Comment by samreid** [comment]
Thanks for the review @Denz1994, closing.
