### ISSUE TITLE
Should TimerNode allow units to precede the readout for RTL?

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#402]
From https://github.com/phetsims/scenery-phet/issues/372#issuecomment-419198966

@pixelzoom said that it would be nice for RTL languages to show the units before the numeric readout in the TimerNode.  As far as I know, we have rarely, if ever, added direction-specific logic to our layout code.  Is this something we want to address in this case?  Assigning @pixelzoom, @jbphet, and @ariel-phet for discussion.

**Comment by pixelzoom** [comment]
> As far as I know, we have rarely, if ever, added direction-specific logic to our layout code.

This is not layout code.  This is a value followed by units.  And I'm certain that you'll find the `{{value}} {{units}}` pattern used in PhET sims.   And if you want to make part of the number smaller, use RichText.

**Comment by samreid** [comment]
In https://github.com/phetsims/scenery-phet/issues/372#issuecomment-386185029 @jonathanolson said:

> we may need arbitrary nodes for some things.

Hence this is being developed as multiple nodes instead of a single RichText node.  Should we revisit that decision?

Also, if we use RichText and the numeric value of, say, a millisecondsProperty is `123.45678` and we want to format it as `123.46 ms` with the `.46` as smaller, would this be done with an i18n string like `{{integerPart}} <span style="font-size: 12px;">{{decimalPart}}</span> {{units}}`?

**Comment by pixelzoom** [comment]
TimerNode is presumably for displaying time.  So I don't see the need for "arbitrary nodes" or huge amounts of flexibility here.  What we should be able to do is agree on a way to display time, and (importantly) in a way that is not locale-specific.   Using RichText and StringUtils.fillIn seems like it fits the bill.

**Comment by ariel-phet** [comment]
@arouinfar can you comment here? Would persian/arabic type languages want units displayed to the left for time? My google search of images suggests that time is read left to right even in RTL languages

**Comment by arouinfar** [comment]
While Persian and Arabic (not sure about other RTL languages) read numbers LTR, I believe the expectation is that the units would still be to the left. In general, we've used the `{{value}} {{units}}` pattern to allow translators to decide on whether a unit should be displayed to the left or right of the number.

Ideally, the version of timerNode that displays units would also include the `{{value}} {{units}}` pattern. If that's not feasible, then we can add it to the pile of not-ideal-but-still-usable features of using sims in an RTL locale.

**Comment by arouinfar** [comment]
Just to add -- digital time is read LTR in the same way as it is in LTR locales (hh:mm:ss). The issue here is that we now have a version of timerNode with explicit units, so it would be nice to support the `{{value}}{{units}}` pattern, though perhaps not critical.

**Comment by jbphet** [comment]
Based on @arouinfar's comment above, I concur that support for a format pattern should exist.  Others have described similar thinking on this, but mine is that there would be something like a `readoutFormatString` that would be associated with TimeNode and would be `{{value}} {{units}}` by default, reversible for RTL languages.  I don't think the format would need to be an option to the node.  If there were no units, this portion would end up blank when filled in which may work fine, or possibly the string template is not used in that case.  As for the mixed font sizes, that seems tricky, and maybe we should revisit that design decision in order to simplify things.  Or, if the embedded HTML that @samreid proposes [above](https://github.com/phetsims/scenery-phet/issues/402#issuecomment-422069806) works right away, go with that.

**Comment by samreid** [comment]
> As for the mixed font sizes, that seems tricky, and maybe we should revisit that design decision in order to simplify things.

The current implementation of TimerNode is to show the decimal points in a smaller font and the units in an even smaller font, like so:

![image](https://user-images.githubusercontent.com/679486/45974623-20a43c00-bfff-11e8-8aa7-82d471df947f.png)

The straightforward implementation of `{{value}} {{units}}` would look something like this:

![image](https://user-images.githubusercontent.com/679486/45974788-afb15400-bfff-11e8-952a-004d0fdc6c0e.png)

@arouinfar and @ariel-phet is that acceptable design?

**Comment by arouinfar** [comment]
@samreid the straightforward approach looks fine to me!

**Comment by jonathanolson** [comment]
Hmm, I thought they were handled as separate strings because you didn't want numbers to jitter back-and-forth when digits change (e.g. `11` is not as wide as `88` on fonts, so the decimal point or whatnot would jitter back and forth).

Alternatively, we could parse the `{{value}} {{units}}` string, determine in which order things show up, and then rearrange the nodes.

**Comment by samreid** [comment]
What about using a monospace font?

**Comment by jonathanolson** [comment]
> What about using a monospace font?

That also would work nicely, and may look a bit better even (most timers use monospaced fonts).

**Comment by samreid** [comment]
Do we have a precedent or pattern for using monospace fonts in our sims?  Or will we need to investigate what is web-safe and contains the glyphs we may need?

**Comment by jonathanolson** [comment]
> Do we have a precedent or pattern for using monospace fonts in our sims? Or will we need to investigate what is web-safe and contains the glyphs we may need?

I haven't used it before. Basically probably pick monospace fonts on Win/Mac/Chromebook/etc. that look nice, and put "monospace" at the end (uses the system default monospaced font).

Also if a code point isn't handled by the font, the browser uses a fallback. So I don't think we need to look into which fonts contain which glyphs.

**Comment by samreid** [comment]
> Alternatively, we could parse the {{value}} {{units}} string, determine in which order things show up, and then rearrange the nodes.

That sounds like it could lead to confusion and problems.  For instance, let's say a Greek translator specified `{{value}} απο {{units}}`, what would we do with the `απο`?

**Comment by jonathanolson** [comment]
> That sounds like it could lead to confusion and problems. For instance, let's say a Greek translator specified {{value}} απο {{units}}, what would we do with the απο?

Ignore it! But yes, that may not be the best.
