### ISSUE TITLE
Code Review for TimerNode, particularly with respect to the new units option

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#403]
From https://github.com/phetsims/scenery-phet/issues/372#issuecomment-421681294

@zepumph commented:

> Discussed in dev meeting today. We think that @Denz1994 would be a good candidate for a review of this. Assigning to him.

Please also see other comments and linked issues in #372 (marked above https://github.com/phetsims/scenery-phet/issues/372#issuecomment-422056883 ) which pertain to review.  

It would be good for these changes to be reviewed before publishing new simulations with these changes.  This includes but is not limited to https://github.com/phetsims/capacitor-lab-basics/issues/244 and the upcoming RC for wave interference.

**Comment by samreid** [comment]
Also be aware there is a scenery-phet component test that demonstrates the TimerNode and changing units.

**Comment by Denz1994** [comment]
Noting my [comment](https://github.com/phetsims/capacitor-lab-basics/issues/244#issuecomment-424438184) here from https://github.com/phetsims/capacitor-lab-basics/issues/244. The units option works as expected.

**Comment by Denz1994** [comment]
This may be a silly consideration, but the unit option is flexible enough to allow for any `Node`. This allows for some extreme TimerNode configurations such as having another `TimerNode` within the `unitsNode` option.

![image](https://user-images.githubusercontent.com/13894380/46155660-d52f9f00-c245-11e8-8ffe-a8c45059ca9c.png)


My proposed workaround would be checking for instances of `Text` or `RichText` in the `unitNode` option. If it is too much work to contrain the types in this option perhaps we can leave it up to the developer's good grace that that won't create something as atypical as shown above.

**Comment by samreid** [comment]
In https://github.com/phetsims/scenery-phet/issues/402#issuecomment-424175305 we are considering switching the readout to a single string which would include minutes, seconds, and optionally units.

**Comment by samreid** [comment]
In https://github.com/phetsims/scenery-phet/issues/402#issuecomment-425230441 we decided to keep the separate numbers/fonts and not handle RTL for this component.

**Comment by samreid** [comment]
@Denz1994 reported:

> The units option works as expected.

In my opinion, our next steps to decide whether or not to limit the flexibility to specify an arbitrary node are not a blocking issue, so I'll unlabel the issue.

**Comment by samreid** [comment]
> My proposed workaround would be checking for instances of `Text` or `RichText` in the `unitNode` option. If it is too much work to constrain the types in this option perhaps we can leave it up to the developer's good grace that that won't create something as atypical as shown above.

My inclination is to leave it as an arbitrary Node and not check for a particular subtype.  It is unlikely for a developer to use a different type, and if they intentionally use a different type then it likely will be for a good reason.  That being said, I added a comment that said the Node would probably be Text or RichText.  @Denz1994 is that OK, and is there anything else for this issue?

**Comment by Denz1994** [comment]
The documentation is good enough, but I did want to note the flexibility to support any node. That was the last point in this issue so I'll close. Thanks @samreid.
