### ISSUE TITLE
StarShape should have ability to choose number of star points

### ISSUE THREAD

**Issue by arnabp** [phetsims/scenery-phet#404]
Starshape is currently restricted to five pointed stars. An option should be made to allow any number of star points.

Feature needed for phetsims/blackbody-spectrum

**Comment by jbphet** [comment]
@arnabp and I looked through this together briefly, and for the most part it looks good.  We decided that it would be preferable to come up with some name other than "iMax" for the iteration loop.  Also, consider using `_.times`, which is a nice underscore method for fixed iterations.

**Comment by arnabp** [comment]
Issues were addressed, closing.
