### ISSUE TITLE
utteranceQueue.setInterval is broken

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#407]
You can set this value, but the timer's interaval was created in the initialize call, and it isn't destroyed and rebuild with the new interval, so this is likely buggy. I haven't seen any usages of this though, so it seems alright for now.

**Comment by zepumph** [comment]
These changes look very nice. I added some tests also to help understand the changes better. Things seem to be working well. Thank you!

**Comment by zepumph** [comment]
Anything else here?

**Comment by jessegreenberg** [comment]
Thanks for the thorough review @zepumph, I think this can be closed.
