### ISSUE TITLE
Create AlertableDef type

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#409]
I was thinking it would be nice to have a type definition, like `ColorDef.js` that typed out every legal arg that can be passed to utteranceQueue queueing methods. Right now that is just `{string|Utterance}`, but it could change/grow. I am finding myself writing a fair few method that is basically wrapping an utteranceQueue method with extra metadata (see `MovementDescriber.alert()`). This seems like an approach that will be used a lot. It is nice to not have to repeat all of the legal alerable types, especially if it changes in the future. For example, if because of #406 we accept `{Array.<string>}`, then we wouldn't have to change all usages, but rather the `AlertableDef`.

What do people think? What is a good name?

**Comment by jessegreenberg** [comment]
I agree, sounds good to have. For instance, I imagine we may just want to support numbers. What is the best way to handle an array?

**Comment by jessegreenberg** [comment]
I gave it a shot and tried it in MovementDescriber. @zepumph and @mbarlow12 what do you think?

**Comment by zepumph** [comment]
I like it a lot. I moved assertions to be at the source. What do you think?

**Comment by jessegreenberg** [comment]
I think this looks very nice, thanks for the recommendation @zepumph. Good to have this in utteranceQueue, but it will probably be useful elswhere in functions using or generating alertables. Closing this issue.
