### ISSUE TITLE
Move "static" fields in utteranceQueue

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#412]
Found while taking a look at https://github.com/phetsims/scenery-phet/issues/407. utteranceQueue used to be a static collection of functions, but now it is an initialized singleton, and the fields at the top of the file are confusing without being assigned to the instance.

**Comment by jessegreenberg** [comment]
Done, referencing these fields in utteranceQueue functions is much clearer.

**Comment by zepumph** [comment]
@jessegreenberg I made a few updates to this. What do you think?

**Comment by jessegreenberg** [comment]
Very nice, thanks for the cleanup and conversion to es6.
