### ISSUE TITLE
Updates to AriaHerald

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#414]
From #406 @zepumph said, 

>I'm going to do a few updates to AriaHerald. I'm going to make it a class, convert it to es6, give it an emitter, and see about integrating that into the tests. I'm going to move this into a new issue though.

**Comment by zepumph** [comment]
I think this is a large improvement. Thanks @jessegreenberg for the suggestion.

I have one question though, why should we assert the existence of domElements even when we aren't initialized?

@jessegreenberg what do you think about moving these assertions to the initialize method? I don't feel strongly, it just seems weird that all PhET code that imports this file should held to such strict standards.

On top of that question will you review the above commits?

**Comment by jessegreenberg** [comment]
Commits look good, and thanks for renaming to ariaHerald since it is a singleton. I moved the assertions to the initialize function as you recommended. Thanks! Closing.
