### ISSUE TITLE
Should utteranceQueue be cleared on reset?

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#415]
In JT I see that the reset-all button is clearing the utteranceQueue. If we want to do this, I think we should handle it in the ResetAllButton.js file itself, instead of just handling each case separately. @jessegreenberg can you think of a reason that we would either want to or not want to add `utteranceQueue.clear()` somehow to the `isFiringProperty`?

I think the lazyLink in ResetAllButton could nicely read something like:
```js

    this.isFiringProperty.lazyLink( function( isFiring ) {
      utteranceQueue.enabled = !isFiring;

      if ( isFiring ) {
        utteranceQueue.clear();
      }
      else {
        utteranceQueue.addToBack( new Utterance( {
          alert: resetAllAlertString,
          uniqueGroupId: 'resetAllButtonAlert'
        } ) );

      }
    } );

```

@jessegreenberg what do you think?

**Comment by zepumph** [comment]
discovered as part of #407

**Comment by jessegreenberg** [comment]
Totally agree, your recommendation looks great. Added above, and I removed the line in john-travoltage. Checking for other sims doing this now.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/john-travoltage/commit/491c3bd57179d0e9491edc787e894fa4c5a7b181

**Comment by jessegreenberg** [comment]
Only three usages of clear now, BalloonNode, ResetAllButton, and utteranceTests. @zepumph back to you, anything else?

**Comment by zepumph** [comment]
How very nice. Closing
