### ISSUE TITLE
solidify difference between "Describer" and "Alerter"

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#417]
From multiple discussions during meetings and https://github.com/phetsims/friction/issues/133.

I named things with the `Describer` suffix when they actually alerted to utteranceQueue. Whereas there are other files called describers than just work with text and return strings. We should make sure that those two different types have different suffixes. 

I said two names in the issue title, but I'm up for discussion. Please each comment on what you think (even if it is "I don't care stop wasting my time), and we can go from there.

Once we decide on appropriate suffixes, then we should rename files appropriately.

**Comment by jessegreenberg** [comment]
+1 from me that the distinction will be useful in the future. Also, like "Describer" and "Alerter" or "AlertManager".

**Comment by zepumph** [comment]
Alright sounds good. I'll rename and update documentation.

**Comment by mbarlow12** [comment]
Sorry for the late input here. I've been using StringManager and AlertManager in the ISLC sims. The idea I've been working toward is that there's a central type that only manages dynamic content. Static labels and help text are just required directly where they're needed.

I'm not as sold on the AlertManager; it's pretty much just a wrapper to abstract away Utterances and utteranceQueue. 1 less include in some places, and I suppose it's a little more centralized for better maintainability.

Some other ideas could be:
AccessibleContentManager
PDOMTextifier
DynamicContentManager
TextHandler
DynamicDescriber

All that said, I like the brevity of 'Describer' and 'Alerter'. `GravityForceLabBasicStringManager` has felt a wee cumbersome.

**Comment by zepumph** [comment]
My only comment would also be to praise the idea of a single work "suffix" that could be easily tacked on to types

**Comment by zepumph** [comment]
Currently we have tons of `*Describer` types that have been working really well for us. We haven't yet needed `*Alerter` types, and likely we won't need to, since utteranceQueue logic to this point has been quite a bit simpler, instead just wiring up the proper calls the the Describers. We can update the pattern in the future if needed, but for now I'm feeling pretty good.
