### ISSUE TITLE
NumberDisplay: add minBackgroundWidth option

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#420]
NumberControl needs a way to specify the minimum width of its NumberDisplay's background.  Required to address https://github.com/phetsims/beers-law-lab/issues/126#issuecomment-436810280.

**Comment by pixelzoom** [comment]
Done.  NumberDisplay now has option `minBackgroundWidth`.  It's settable through NumberControl via option `valueMinBackgroundWidth`.  

Randomly selected @chrisklus to review.

**Comment by chrisklus** [comment]
Looks good @pixelzoom, the NumberDisplay is staying at a constant width. Back to you.
