### ISSUE TITLE
Redesign GrabButton type

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#421]
I was thinking about this because of difficulties with https://github.com/phetsims/friction/issues/144. It has actually become a total pain in the butt to try to keep the grabButton's focusHighlight in sync visually with the "wrappedNode"

After speaking with @jessegreenberg about this. We thought that maybe making it a mixin would be nice. After poking around with a potential implementation I found two immediate issues with that which could potentially be sorted out, but totally stopped me in my tracks this evening.

1. GrabButtonNode is subtyped for Friction specific logic. Perhaps we should look to http://justinfagnani.com/2015/12/21/real-mixins-with-javascript-classes/ for a pattern with inheritance and mixins coexisting. I'm not sure that unidiomatic approach (for phet) is the best way to plow forward.
2. GrabButtonNode was toggling accessibleVisible on the "wrappedNode" when it still wanted the grabButton visible. This worked when not in a mixin because the `GrabButtonNode` had two children, `wrappedNode`, and `grabButton` (that actually was the PDOM button). In the mixin, we can't toggle accessibleVisible on the "wrappedNode" (now `this`), because `grabButton` will have to be a child of it. How do we hide the parent while displaying the child without having access to a higher up ancestor to set `accessibleOrder` such that we pull out the child from the scene graph to a better spot for the PDOM. 

I'm really not sure how to proceed, but I'll keep cranking away at it next week, perhaps with a bit of conversation with others before diving in too deep. 

I'm surprised this type is ending up being so complicated as a general solution. Worst case we may just need to create a GrabButtonNode that doesn't wrap anything, and then design pattern/convention in how we link up listeners to connect it and the draggable node. I don't think we are there yet though.

**Comment by zepumph** [comment]
I renamed this issue because, after talking with @jonathanolson, I am going to change the way that the general grab button is implemented. Currently the GrabButtonNode is passed a node for it to add as a child. This is problematic for many reasons, like that that changes the scene graph structure and transform of the draggable node. Ideally we would want to keep that the same while we added a11y to a type.

Instead we looked into a structure where we add grab button functionality as a child to the draggable node. This involves changing what we are doing in friction, but it will end up being much more robust.

**Comment by zepumph** [comment]
Here is some pseudo code about the new strategy:
```js
class BookNode {
  super();

  this.grabNode = new GrabNode( this );

  // we want the grab node as a child
  this.addChild( this.grabNode );
}

class GrabNode {
  constructor() {
    this.addInputListener( {
      keydown: event => doSomeDrag( event )      
    } );

    this.targetListener = {
      click: event => {
        this.accessibleVisible = true;
        this.focus();
      }
    };
  }

  attach( targetNode ) {
    targetNode.tagName = 'button';
    targetNode.addInputListener( {
      click: event => {
        this.visible = true;
        this.focus();
      }
    } );
  }


  getA11yConfigOptions() {
    return {
      tagName: 'button'
    }
  }
}

////////////////////////////////////////

class GrabNode {
  constructor( targetNode ) {
    this.addChild( targetNode );
  }
}


////////////////////////////////////


class BookNode {
  super();

  this.initializeGrab( ... );

  this.grabNode = new GrabNode( this );



  this.children = [
  ];

  // we want the grab node as a child
  this.addChild( this.grabNode );
}

Grabbable.mixInto( BookNode );


const Grabbable = {
  mixInto( type ) {
    extend( type.prototype, {
      initializeGrab( ... ) {
        this.addChild( new GrabNode( this ) );
      }
    } );
  }
};

class GrabNode {
  constructor() {
    this.addInputListener( {
      keydown: event => doSomeDrag( event )      
    } );

    this.targetListener = {
      click: event => {
        this.accessibleVisible = true;
        this.focus();
      }
    };
  }

  attach( targetNode ) {
    targetNode.tagName = 'button';
    targetNode.addInputListener( {
      click: event => {
        this.visible = true;
        this.focus();
      }
    } );
  }


  getA11yConfigOptions() {
    return {
      tagName: 'button'
    }
  }
}
```

**Comment by zepumph** [comment]
In the above commits I overhauled `GrabButtonNode`

Basically now the structure is that "GrabButtonNode" is the application div that gets a11y dragging listeners attached to it.

Whatever "parent" type node that is passed in to the constructor becomes the "button" of the grab interaction. See BookNode.js for an example of how "this" is passed into the `GrabButtonNode` type.

There are a ton of TODOs left for this, including probably renaming the file, but the main thing left to handle is "cueing". There is no support for this right now. I think it would be best for the cues to be part of the focusHighlight, but I was having trouble figuring out how that works (generally or just for friction) with focusHighlightLayerable highlights.

I'll keep working on this, but may not be able to make more progress for a week or so.

In the mean time, I think it would be good for @jessegreenberg just to know the direction this is going. Perhaps we can meet soon to talk about what it looks like currently, and to investigate ways to proceed, as right now I'm a bit stuck. I'll add it to the a11y dev meeting too.

**Comment by zepumph** [comment]
Next I'm going to get space bar working correctly.

**Comment by zepumph** [comment]
The above comment feels like a workaround to me. But at least space is working in friction. It also fixed strange bug where the draggableNode wasn't properly removed from the focus order when you tabbed away from it, and then came back to it.

While working on that I realized that one of the main issues left is about accessibleOrder. And the above workaround relates to that too.

In the GrabButtonNode we used to have the ability to set the `accessibleOrder` such that the draggableNode and the grab button were peers. This is important for multiple reasons, and, for the space bar bug above, because then they don't share bubbling events in the hierarchy. 

Basically there seems to be three ways to proceed regarding the PDOM hierarchy of grab interactions:
1. Convince ourselves that it is ok for the application div to be inside a button
2. Recognize that the pattern of using this type involves potentially reaching into a type in order to properly set the `accessibleOrder`. In BookNode this would look like `FrictionScreenView` pulling the `a11yGrabDragInteractionNode` out of the scene graph with `this.accessibleOrder = [chemistry
3. We completely rethink this type for the general case again.

I would like to tag @jessegreenberg to discuss the pros and cons about how to proceed. Please look at BookNode.js and how it uses this new type (I'm about to rename it to A11yGrabDragNode`). Do you see what it would take to change the accessibleOrder to make the `BookNode` and the `A11yGrabDragNode` siblings. Whereas ideally we could set that from `A11yGrabDragNode`.

**Comment by terracoda** [comment]
@zepumph, this is very interesting work. I would like to point out that the Grab book button that you have created in Friction sounds different in two very important ways than the Grab balloon button in BASE. Here are the interesting differences I notices when using VoiceOver:
1. On grab, I never hear "group, web application"
2. On release, I never hear the refocusing of the grab button label, "Grab book, button"

These are 2 positives and I would like to know very much how you are doing this. Are you using `aria-roledescription` anywhere, and if so where?

**Comment by jessegreenberg** [comment]
We discussed the first bullet point during a11y meeting today, and couldn't think of a reason why the application role inside the button would be problematic for a11y.

In BASE, the focusable div is contained under a parent div with role=application. Sorry, I couldn't find any documentation about why this is but remember it being considered and tested. We might want to do that here too but that doesn't seem problematic.

@jessegreenberg will review point 2 outside of meeting time.

**Comment by jessegreenberg** [comment]
We ran similar HTML through a validator and got this output:
![capture](https://user-images.githubusercontent.com/6396244/48789831-ecc25b80-ecbb-11e8-8bda-288eca616b03.PNG)

Since it works with AT, we are not sure if this is a problem.

**Comment by jessegreenberg** [comment]
@terracoda tested in VO, lets also test in NVDA and JAWS to see if this works OK, that will help inform about whether it is OK to have non-valid HTML.

**Comment by terracoda** [comment]
@jessegreenberg, after seeing that message in the A11y Tree, I think we are not hearing the expected application role and the name of the re-focused button because the information is not being exposed in the A11y Tree.

**Comment by terracoda** [comment]
I am still curious to hear what JAWS and NVDA do.

**Comment by jessegreenberg** [comment]
Testing with NVDA and Firefox: Alerts and movement all work correctly. When I grab the book, I do not hear anything like "Application, section" (which I do in BASE).

**Comment by zepumph** [comment]
It seems like this nesting is causing issues. . .

**Comment by terracoda** [comment]
Thanks @jessegreenberg! This was very helpful. I think we need to stick to the structure that worked in BASE. That solution worked for all AT we support. 

@zepumph, do you think your generalizable draggable object could work with BASE's sibling structure, or a similar sibling structure? There is a difference in the two sims as BASE's draggable balloon has the heading `<h3>Yellow Balloon</h3>` and the Chemistry book in Friction does not (at this point) have a similar heading.

Would something like this work:
```html
<button data-focusbale="true">Grab Chemistry book<button>
<div role="application" data-focusbale="true/false 
with true after grab button is pressed, then false on release" 
aria-roledescription="Grabbed Chemistry book??">
Grabbed Chemistry book??
</div>
```
I put question marks next to the attribute content that I'll need to test out. I'm thinking, if the `application <div>` represents the Grabbed book, maybe it is best to name it, "Grabbed Chemistry book".

Are there options for providing different aria-roledescription content? For example:
- On initial grab: 
```html 
<div role="application" data-focusbale="true/false" 
aria-roledescription="Grabbed Chemistry book, move in four directions">
Grabbed, Chemistry book, move in four directions
</div>
```
- On subsequent grabs, after successful left-right movement:
```html 
<div role="application" data-focusbale="true/false" 
aria-roledescription="Grabbed Chemistry book">
Grabbed, Chemistry book
</div>
```

**Comment by zepumph** [comment]
From the link above:
>Content model:
Phrasing content, but there must be no interactive content descendant.

@terracoda I like that DOM structure best too, such that the button and application div are peers. I will work on figuring out the best way to proceed based on the javascript structure. Tagging for a11y meeting. @jessegreenberg hopefully we can discuss this Monday. Marking as high priority as it is some of the only friction work left.

**Comment by zepumph** [comment]
I made progress on this. I updated the type so that it changes  the PDOM content of just a single node. This seems promising, and I am happy with the direction.

Right now there isn't really any way to support aria role description, or anything else that can't be set with options.

there is also a bit of strangeness with focusHighlightLayerable that I want to make sure is a bit more robust.

**Comment by zepumph** [comment]
This has been implemented at a basic level for some time now. Today I cleaned up a bit more. I think we are ready to close this issue, but first I will outline a bit of summary from this work.

We looked into multiple structures, both with Nodes and the PDOM, to create the grab/drag interaction. While trying to balance generalization, simplicity, and robustness, the best solution that revealed itself was to actually mutate the a11y instrumentation of the same node, alternating between a grabbable item in the PDOM, and a draggable item.

This was best because it made things simple in the scene graph. When using two nodes (one for the button and one for the div), then one needed to be a child to the other, or you needed a container. Both of these thoughts made for a clunky client side implementation. Parent/child relationships made for difficulties in custom focusHighlights. Requiring a container separated the a11y logic away from the traditional logic (input listeners, transformation, addChild, etc). 

I would say that the weirdest/most annoying part of this pattern is that you cannot add inputListeners for a11y directly to the node. Instead you have to add them to `options.listenersForDrag` or `options.listenersForGrab`. These are cycled just like the options are mutated for each a11y interaction mode. I like this more than other solutions, and I think once I was used to the pattern, it was simple enough, but it is not idiomatic to PhET, and will seem weird I think. I tried to document it as much as possible.

Closing.

**Comment by pixelzoom** [comment]
Reopening.  This TODO by @samreid has not been addressed:

```js
    // TODO: Likely we will need to monitor the parent for changes, and update accordingly, though for now it works in friction, see https://github.com/phetsims/scenery-phet/issues/421
```

**Comment by samreid** [comment]
The TODO was introduced in https://github.com/phetsims/scenery-phet/commit/79db8d49e51cd547e555431821d4af2ebacd9346, reassigning accordingly.

**Comment by zepumph** [comment]
I thought that I had to monitor the parent for changes, but I could not reproduce a case where that was needed. Here is my exploration patch. Each time the grabDragCueNode was exactly where I expected it to be. 

I think I will close this issue and remove the TODO. If in the future we find a case where this cue translation is buggy (which hasn't happened in the last year and a half), I will know where to look!


<details>

```diff

Index: js/demo/ComponentsScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/demo/ComponentsScreenView.js	(revision 0e35bd229ab8755084c34d9ab890773f8abd936e)
+++ js/demo/ComponentsScreenView.js	(date 1586911247473)
@@ -1436,12 +1436,20 @@
 const getDemoGrabDragInteraction = tandem => {
   return function( layoutBounds ) {
 
+    const circlePositionProperty = new Vector2Property( Vector2.ZERO );
+    const parentCircle = new Circle( 80, { fill: 'red' } );
+    parentCircle.addInputListener( new DragListener( {
+      positionProperty: circlePositionProperty
+    } ) );
+    circlePositionProperty.linkAttribute( parentCircle, 'translation' );
+
     const rect = new Rectangle( 0, 0, 100, 100, {
       tagName: 'div',
       role: 'application',
       fill: 'blue',
       cursor: 'pointer'
     } );
+    rect.center = Vector2.ZERO;
     const positionProperty = new Vector2Property( Vector2.ZERO );
     positionProperty.linkAttribute( rect, 'translation' );
 
@@ -1455,7 +1463,7 @@
     rect.addInputListener( keyboardDragListener );
 
     // @private
-    this.grabDragInteraction = new GrabDragInteraction( rect, {
+    const grabDragInteraction = new GrabDragInteraction( rect, {
       objectToGrabString: 'rectangle',
       grabbableAccessibleName: 'grab rectangle',
 
@@ -1464,8 +1472,15 @@
       tandem: tandem.createTandem( 'grabDragInteraction' )
     } );
 
+    rect.rotation = Math.PI;
+    rect.x = 20;
+    parentCircle.addChild( rect );
+    parentCircle.rotation = Math.PI;
+
+    window.grabDrag = grabDragInteraction;
+
     return new Node( {
-      children: [ rect ],
+      children: [ parentCircle ],
       center: layoutBounds.center
     } );
   };
Index: js/accessibility/GrabDragInteraction.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/accessibility/GrabDragInteraction.js	(revision 0e35bd229ab8755084c34d9ab890773f8abd936e)
+++ js/accessibility/GrabDragInteraction.js	(date 1586911339111)
@@ -279,8 +279,8 @@
     };
     this.grabFocusHighlight.highlightChangedEmitter.addListener( onHighlightChange );
 
-    // TODO: Likely we will need to monitor the parent for changes, and update accordingly, though for now it works in friction, see https://github.com/phetsims/scenery-phet/issues/421
     this.grabCueNode.prependMatrix( node.getMatrix() );
+    this.node.transformEmitter.addListener( () => { console.log( 'transform is happeneing' )} )
     this.grabFocusHighlight.addChild( this.grabCueNode );
     if ( this.dragCueNode ) {
       this.dragCueNode.prependMatrix( node.getMatrix() );


</details>
