### ISSUE TITLE
ColorProfile suggestions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#422]
Suggestions after adding my very first color profiles to Gas Properties ...

- [ ]  `ColorProfile` name is misleading, rename to something more accurate. 
An initial conceptual hurdle for me was in the naming of ColorProfile.  If ‘projector’ is a profile name, then I would think of the colors associated with ‘projector’ as a ‘color profile’.   But that's not what `ColorProfile` is.  From the doc, it “Handles multiple color profiles”, which is self-referential. `ColorProfileManager` or perhaps `ColorProfiles` (plural) would be better.

- [x] Swap constructor parameters.
It would also be nice to swap the params to ColorProfile constructor, which is currently `new ColorProfile( colors, profileName )`.  It’s nice to see what the `profileNames` are first, and `colors` is typically a multiple-line object.  I was referred to SOMColorProfile as an example, I didn’t even see the `profileNames` arg in that example, and that caused me a bit of grief.  Compare:

```js
// current order of args
new ColorProfile( {
   backgroundColor: {
     default: 'black',
     projector: 'white'
   },
   ...
   handleColor: {
     default: 'blue',
     projector: 'green'
   },
}, [ 'default', 'projector' ] );

// better order of args?
new ColorProfile( [ 'default', 'projector' ], {
   backgroundColor: {
     default: 'black',
     projector: 'white'
   },
   ...
   handleColor: {
     default: 'blue',
     projector: 'green'
   },
} );
```

**Comment by pixelzoom** [comment]
I swapped constructor parameters in the above commits.

**Comment by pixelzoom** [comment]
There are currently 13 singletons created using `new ColorProfile`.  If we rename `ColorProfile`, then we should rename these 13 singletons, which appears to be possible using global string replacement.

**Comment by jonathanolson** [comment]
> ColorProfileManager or perhaps ColorProfiles (plural) would be better.

Sounds fine to me. I agree the current name is confusing.

**Comment by pixelzoom** [comment]
This has been labeled for dev meeting since 11/12/18, and the proposal has a thumbs-up from @jonathanolson and @samreid.  That seems like enough time for other devs to chime in, so I'm going to move forward with renaming `ColorProfile` to `ColorProfiles`.

**Comment by pixelzoom** [comment]
As I got into the rename, I started to have second thoughts.  While `ColorProfile` constructor takes multiple profile names and descriptions, only _one_ profile is active at a time.  So uses sites look best with `ColorProfile` singular, e.g.:

`stroke: FractionsCommonColorProfile.numberStrokeProperty,`

So I'm going to leave this alone.  Closing.
