### ISSUE TITLE
HeaterCoolerNode problems

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#423]
I'm trying to use `HeaterCoolerNode` in Gas Properties.  Lots of problems...

- [x] (1) The `width` option is a disaster. Given the number of sims that use this, it's difficult for me to understand how there can be so many problems with the `width` option, including:

* the hole in the top of the bucket is off to one side
* the labels hang off the left edge of the bucket
* the flames and ice aren't scaled down and stick out the sides

Example with `width: 50`:

![screenshot_850](https://user-images.githubusercontent.com/3046552/48387988-1aecdd80-e6b5-11e8-9ae2-4ea3dfb3674e.png)

- [x] (2) `width` is a seriously sketchy option to be passing to Node. The `options` arg is passed to the superclass `Node`.  Node has a `width` getter.  Not a problem now, but this is asking for trouble in the future. Highly recommended to use an option name that is more specific to `HeaterCoolerNode`.

- [x] (3) `heatCoolAmountProperty` is currently:

```js
heatCoolAmountProperty: new Property( 0 ), // Property set through interaction with slider.  +1 for max heating, -1 for max cooling.
```

It should be:

```js
const DEFAULT_HEAT_COOL_AMOUNT_PROPERTY = new NumberProperty( 0, {
  range: new Range( -1, 1 ) // +1 for max heating, -1 for max cooling
} );
...
heatCoolAmountProperty: DEFAULT_HEAT_COOL_AMOUNT_PROPERTY
```

- [x] (4) There are no `dispose` functions. `HeaterCoolerNode`, `HeaterCoolerFront` and `HeaterCoolerBack` need to dispose of the things that they create.  In Gas Properties, I'm using `options.heatCoolAmountProperty`, and there's no way for me to unlink this things from the Property.

- [x] (5)  This documentation is not useful:
```js
      heatEnabled: true, // Can this node heat the environment?
      coolEnabled: true // Can this node cool the environment?
```
This was probably copied over from the first sim that used `HeaterCoolerNode`.  But there's nothing here that's in any way related to an "environment".  I haven't tried these options, but I'm guessing that they enable/disable the heat or cool range of the slider.

Assigning to @ariel-phet to decide who should work on this.

**Comment by pixelzoom** [comment]
- [ ] There's no way to adjust the size or pointer areas of the slider thumb.

**Comment by phet-steele** [comment]
There is also the mystery of phetsims/states-of-matter/issues/224. Can't help but wonder if the code was better that maybe we could have cracked that case.

**Comment by Denz1994** [comment]
@pixelzoom mentioned the documentation for the`heatEnabled` and `coolEnabled` options is ambiguous ([above comment](https://github.com/phetsims/scenery-phet/issues/423#issue-380040501)). Setting `heatEnabled: false` causes the slider to only have a "cool" setting where sliding towards "cool" raises the ice cube image, producing this:
![image](https://user-images.githubusercontent.com/13894380/48513704-75f41100-e82a-11e8-8360-5d2aaa05ca0c.png)

I tracked down this [comment](https://github.com/phetsims/scenery-phet/issues/151#issuecomment-100706893) by @jessegreenberg when this was first implemented a few years ago
https://github.com/phetsims/scenery-phet/commit/40849d74d59a6fb4d532a3568636f60304d885a9. @jessegreenberg Do you know why this option was introduced or should we consult the original designer? I don't see any usages for these options in sim code. 

Would it be safe to remove? If not, I can come up with a better descriptor in the documentation.

**Comment by Denz1994** [comment]
I'll update the documentation for the`heatEnabled` and `coolEnabled` options and leave them implemented.

**Comment by pixelzoom** [comment]
How about adding tests to scenery-phet demo to confirm that they actually work?

**Comment by Denz1994** [comment]
I added 3 instances of HeaterCoolerNode to scenery-phet demo. The `heatEnabled` option limits the VSlider Range to `min:0, max:1`. The `coolEnabled` option limits the Range to `min:-1, max:0`.

While doing this, I noticed that adding multiple instances of the HeaterCoolerNode on the same ScreenView causes the `HeaterCoolerNode.heatCoolAmountProperty` to be shared between each instance. So using the slider on one HeaterCoolerNode, causes the other sliders to adjust the property and raise the fire/ice images. Try this by sliding the node named "Cooler" on the demo screen and you'll see the "Heater" node adjust.

The current workaround is to declare a new NumberProperty in the options. 
`heatCoolAmountProperty: new NumberProperty()`. This is what was done for the instance named "Heater Cooler" in the demo screen.

**Comment by pixelzoom** [comment]
>  I noticed that adding multiple instances of the HeaterCoolerNode on the same ScreenView causes the HeaterCoolerNode.heatCoolAmountProperty to be shared between each instance.

If you're passing the same `heatCoolAmountProperty` to each instance, then this is expected - and desired.  That's classic Model-View-Controller pattern.

**Comment by pixelzoom** [comment]
Ah, I see what you're talking about.  This is definitely a problem:

```js
  const DEFAULT_HEAT_COOL_AMOUNT_PROPERTY = new NumberProperty( 0, {
    range: new Range( -1, 1 ) // +1 for max heating, -1 for max cooling
  } );
```

A Property (for the reasons that you mentioned) should never be factored out as constant for a default option value.   If the default is not used by any clients, then +1 for making `heatCoolAmountProperty` a required constructor parameter, and ditching the option.

**Comment by Denz1994** [comment]
In response to the issues with the width option, it has been removed for now. Instances in sim code currently make use of the `scale` option for sizing. This handles sizing for all 3 components (`HeaterCoolerNode`, `HeaterCoolerBack`, and `HeaterCoolerFront`). Because all of the components are handled in 3 separate nodes, I think `scale` represents a good option for sizing. Thoughts otherwise  @pixelzoom?

The separate components are useful for instances like EFAC where layer nodes need to be layered between components. See  energy-forms-and-changes/js/intro/view/EFACIntroScreenView.js.

>     // set up left heater-cooler node, front and back are added separately to support layering of energy chunks

**Comment by pixelzoom** [comment]
FYI, this API change broke Gas Properties, fixed in the above commit.

**Comment by pixelzoom** [comment]
Re https://github.com/phetsims/scenery-phet/issues/423#issuecomment-444608827:
> ... Because all of the components are handled in 3 separate nodes, I think scale represents a good option for sizing. Thoughts otherwise @pixelzoom?

OK to remove `width` option, `scale` sounds appropriate.

**Comment by pixelzoom** [comment]
> In response to the issues with the width option, it has been removed for now.

I still see `width` option in HeaterCoolerNode.  It appears to be unused.

> > ... Because all of the components are handled in 3 separate nodes, I think scale represents a good option for sizing. Thoughts otherwise @pixelzoom?

`scale` sounds appropriate.

**Comment by pixelzoom** [comment]
@Denz1994 said:
> I think scale represents a good option for sizing

I said:
> Agreed, `scale` sounds appropriate.

.. except now I see that HeaterCoolerNode passes all of its options to the supertype, the HeaterCoolerFront instance, and the HeaterCoolerBack instance.   So if I do `new HeaterCoolerNode(..., { scale: 0.5 } )`, the scale is going to be applied twice.

**Comment by pixelzoom** [comment]
So... some more check list items:

- [ ] HeaterCoolerNode should not pass complete set of `options` to is subcomponents.  

- [ ] In HeaterCoolerNode, consider using nested options for the subcomponents. I.e.:

```js
options = _.extend( { 
  ...

// options passed to HeaterCoolerFront
  frontOptions: {
    ...
  },
  
  // options passed to HeaterCoolerBack
  backOptions: {
    ...
  }
}, options );
```

**Comment by Denz1994** [comment]
Front and back options have been added as options and are null by default. The subcomponents they are passed into (i.e. `new HeaterCoolerNodeFront( new NumberProperty(), frontOptions)`) provide proper defaults using `options = _.extend( { ... }, options );`

This also prevents options such as `scale:` to be applied twice.

**Comment by pixelzoom** [comment]
@Denz1994 I don't any commits that adjust the `scale` for sims that use HeaterCoolerNode.  This is a breaking change for those sims, since their HeaterCoolerNode will now be significantly smaller.

**Comment by Denz1994** [comment]
Good point. For the instances that use a scaling option, the size is slightly larger after the changes (scenery-phet `checkout c6940819f36395f49c613f2da1e2ecba31165d2e`).

In gas-properties before (left) and after (right):

![image](https://user-images.githubusercontent.com/13894380/49828641-664ce700-fd5a-11e8-838e-3ccf005c3a11.png)![image](https://user-images.githubusercontent.com/13894380/49828553-31409480-fd5a-11e8-8842-aa6e677ffdbf.png)

This is a similar result to SOM. I will go forward with adjusting the scales at each instance to fit the original size.

**Comment by Denz1994** [comment]
Related issues have been closed and checklist items have been addressed. Leaving to @pixelzoom to close or add further input.

**Comment by pixelzoom** [comment]
Not ready to be closed.  Documentation of options in HeaterCoolerFront and HeaterCoolerBack is still incomplete. Some options are missing any documentation, some are missing type expressions.

**Comment by pixelzoom** [comment]
@Denz1994 I see that you did the ES6 conversion.  The use of `let` is incorrect.  You've used it throughout where `const` should be used.  `let` should only be used for things that will change.

**Comment by Denz1994** [comment]
Referencing https://github.com/phetsims/scenery-phet/issues/435#issuecomment-446698118 in this issue.

**Comment by Denz1994** [comment]
Options have been updated with documentation and `DEFAULT_BASE_COLOR` has been refactored as suggested in https://github.com/phetsims/scenery-phet/issues/435#issuecomment-446698118. Leaving to @pixelzoom to close or add further input.

**Comment by pixelzoom** [comment]
In the above commit, I fixed a couple of minor doc things that I didn't notice previously, specifically:

`heatCoolAmountProperty` is not optional, so:
 
```js
@param {NumberProperty} heatCoolAmountProperty
```

nested options can be `null`, so:

```js
        // {*|null} options passed to HeaterCoolerFront
        frontOptions: null,

        // {*|null} options passed to HeaterCoolerBack
        backOptions: null
```

@Denz1994 feel free to close this issue after taking a peek.

**Comment by Denz1994** [comment]
Thanks for the follow-up. Closing.
