### ISSUE TITLE
add font options to TimerNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#424]
I'm using TimerNode is Gas Properties.

We recently went through a lot of discussion and review of TimerNode, especially the time display. See for example: https://github.com/phetsims/scenery-phet/issues/400, https://github.com/phetsims/scenery-phet/issues/402, https://github.com/phetsims/scenery-phet/issues/403.  So I'm very surprised to find that there is no ability to customize the fonts.  Or maybe it's expected that the entire timer will be scaled? 

@samreid please advise.

**Comment by samreid** [comment]
What font is desired for Gas Properties usage of TimerNode?  Does it differ from the hard-coded font values?  If Gas Properties indeed needs a different font, can all simulations use that font?  In a moment, I'll commit options that will allow the client to customize the fonts, but it would be best if we can choose defaults that work well in the majority of cases.

**Comment by samreid** [comment]
After the above commit, you can specify font options like so:

```js
    // Initialize with longest possible string
    var unitsNode = new Text( 'ms', {
      font: new PhetFont( 30 )
    } );
    var mutableUnitsTimerNode = new TimerNode( new Property( 12.34 ), new Property( true ), {
      smallFont: new PhetFont( 30 ),
      largeFont: new PhetFont( 45 ),
      unitsNode: unitsNode
    } );
```

![image](https://user-images.githubusercontent.com/679486/48392198-7d4ed980-e6c7-11e8-8773-00e5dd161f2a.png)

Back to you @pixelzoom

**Comment by pixelzoom** [comment]
> What font is desired for Gas Properties usage of TimerNode? Does it differ from the hard-coded font values? If Gas Properties indeed needs a different font, can all simulations use that font?

As long as `layoutBounds` can be set for ScreenView,  there should never be an assumption that all sims can use the same font.

**Comment by pixelzoom** [comment]
@samreid and I had a Slack conversation a couple of days ago in which he pointed out that we could save memory by factoring out constants for default option values.  So I was surprised to see the new font options implemented like this in `TimerReadoutNode`:

```js
        // {Font} - shown for the numbers before the decimal
         largeFont: new PhetFont( 20 ),

         // {Font} - shown for the numbers after the decimal
         smallFont: new PhetFont( 15 )
```

I factored these out as constants, and made them part of the public interface, so that they can use used to create units that match the size of numbers:

```js
  // constants
  const DEFAULT_LARGE_FONT = new PhetFont( 20 );
  const DEFAULT_SMALL_FONT = new PhetFont( 15 );
...
        // {Font} - shown for the numbers before the decimal
        largeFont: DEFAULT_LARGE_FONT,

        // {Font} - shown for the numbers after the decimal
        smallFont: DEFAULT_SMALL_FONT
...
  // Make the default fonts public, to inform creation of optional unitsNode
  TimerReadoutNode.DEFAULT_LARGE_FONT = DEFAULT_LARGE_FONT;
  TimerReadoutNode.DEFAULT_SMALL_FONT = DEFAULT_SMALL_FONT;
```

Back to @samreid for review.

**Comment by samreid** [comment]
> So I was surprised to see the new font options implemented like this in TimerReadoutNode.

I'm not confident we want to eagerly apply this pattern everywhere.  In https://github.com/phetsims/unit-rates/issues/207#issuecomment-437215699 we saved 20MB by factoring out one variable, because there were so many Emitter instances.  For a simulation with <=1 TimerNode, the change above would have no effect and for N<10 TimerNodes the proposed change would have minimal effect.  The disadvantage of this pattern is separating values from where they are used.

That being said, in this case, the change looks reasonable because it provides the default fonts as statics.
