### ISSUE TITLE
buggy layout of units in TimerReadoutNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#425]
The baseline of the units in TimerReadoutNode is not vertically aligned with the baseline of numbers in the time display.  This is obvious when you use units that have a descender, like 'ps'.  (None of the tests in scenery-phet demo use units with descenders.)

Here's the example that I'm wrestling with in Gas Properties. Notice how the 'ps' is riding high.

![screenshot_851](https://user-images.githubusercontent.com/3046552/48392209-8e97e600-e6c7-11e8-9973-ed3f9a3be7bb.png)

**Comment by samreid** [comment]
What font sizes are you using?  In the scenery-phet demo I'm seeing:

![image](https://user-images.githubusercontent.com/679486/48392356-357c8200-e6c8-11e8-94c8-045d066e6942.png)

Is your code committed?  When I check the "Stopwatch" checkbox in Gas Properties, I do not see a TimerNode.

**Comment by pixelzoom** [comment]
In Gas Properties, units are in the same font size as the small numbers. The above commit to scenery-demo demonstrates the problem.  Here's a screenshot:
 
![screenshot_852](https://user-images.githubusercontent.com/3046552/48432847-c720d980-e732-11e8-8f5e-96132728b904.png)

**Comment by pixelzoom** [comment]
As the font size for the units increases, the problem becomes more pronounced.  Here's scenery-phet `demoTimerNode` with `var unitsNode = new Text( 'ms', { font: new PhetFont( 20 ) } );`

![screenshot_905](https://user-images.githubusercontent.com/3046552/49315453-f9f4fc80-f4aa-11e8-9318-3848493467e2.png)

**Comment by samreid** [comment]
Proposed fix pushed.  fontSize: 20 looks like:

![image](https://user-images.githubusercontent.com/679486/49400900-d926e400-f702-11e8-92b6-a0861483d1d5.png)

@pixelzoom please review and advise.

**Comment by pixelzoom** [comment]
Looks good. Tested with various font sizes, baselines remained aligned. Closing.
