### ISSUE TITLE
no way to disable start button in TimerNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#427]
Gas Properties has play/pause/step control.  When the sim is paused, I'd like to disable the start button on TimerNode.  There's currently no way to do that, as the `playPauseButton` is private.

**Comment by pixelzoom** [comment]
@arouinfar your call for Gas Properties.

**Comment by arouinfar** [comment]
Thanks for that description @samreid! In general, leaving the start button on the timerNode enabled while the sim is paused allows for users to more easily set up timed experiments. This is the desired behavior, and I do not think Gas Properties should be any different, but thanks for asking @pixelzoom.
