### ISSUE TITLE
change UI state when TimerNode reaches maxValue

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#429]
When TimerNode reaches its maximum, time number stops changing, but the state of `playPauseButton`(which should really be called `playStopButton`) indicates that it's still in the 'playing' state.  Screenshot from Gas Properties:

![screenshot_853](https://user-images.githubusercontent.com/3046552/48439970-d446c400-e744-11e8-9a4d-50e0e02aeb33.png)

 Per @arouinfar, the button state should change to 'stopped', and the button should be disabled until `resetButton` is pressed.  

<details>
<summary>Slack discussion with @arouinfar</summary>

Chris Malley [12:59 PM]
TimerNode apparently goes to 99.99 ps and then just stops, with the button still in the “playing” state.  Does that seem odd/wrong?

Amy Rouinfar [12:59 PM]
I think Sam added a max limit to timerNode, but from what I remember, the max time should have been closer to 999.99.

Chris Malley [1:00 PM]
Ah… There’s a `maxValue` option.  But regardless, should it stop in the “playing” state?

Amy Rouinfar [1:00 PM]
It caused some weird layout problems if you let it go forever.
Yeah, I think it seems better to stop the playing state.

Chris Malley [1:00 PM]
And disable the play button until it’s reset?

Amy Rouinfar [1:00 PM]
Yes
That seems reasonable to me
</details>

**Comment by pixelzoom** [comment]
Above I said:
> ... `playPauseButton` (which should really be called `playStopButton`) ...

The button does indeed do play/pause.  What's incorrect is the icon for pause.  TimerNode is currently using the icon for 'stop', making it totally inconsistent with PlayPauseButton.

**Comment by samreid** [comment]
We didn't want the text display to change size during the runtime of the sim, hence we chose to size it to accommodate the largest text.

**Comment by pixelzoom** [comment]
Inspected commit, tested in Gas Properties. Looks good, closing.
