### ISSUE TITLE
change TimerNode icons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#430]
A couple of problems with the icons used by TimerNode:

(1) TimerNode is currently using a different icon for 'play' than PlayPauseButton.  See screenshots below.  Recommended to use the same icon in all places - PlayPauseButton, TimerNode and PeriodTimerNode. (See also https://github.com/phetsims/scenery-phet/issues/428 about duplication of the play button icon.)

![screenshot_855](https://user-images.githubusercontent.com/3046552/48440679-c7c36b00-e746-11e8-9f79-41392ed58975.png)

![screenshot_854](https://user-images.githubusercontent.com/3046552/48440666-c2662080-e746-11e8-96de-9f305050f255.png)

(2) TimerNode uses a stop icon, but actually does a pause.  Pressing the button again continues to accumulate time.  Recommend to use the same pause button that appears on PlayPauseButton.  Screenshots:

![screenshot_856](https://user-images.githubusercontent.com/3046552/48440808-1b35b900-e747-11e8-89dd-ec947cfc4f30.png)

![screenshot_857](https://user-images.githubusercontent.com/3046552/48440813-1d981300-e747-11e8-8450-32e9c5fe6ca2.png)

**Comment by pixelzoom** [comment]
I asked @arouinfar about this on Slack.  Here reply was:
> Amy Rouinfar [1:17 PM]
> It does seem more consistent to use the same styling on the triangles and pause instead of a square.
> 
> I was not involved in those decisions, and don’t know if there are historical reasons if/why KP or AP would have requested the current behavior.

Assigning to @ariel-phet for a design decision.  @samreid FYI.

**Comment by pixelzoom** [comment]
> My recollection was that we intentionally did not want to use the same icons so as to disambiguate action on the timer from action on the sim.

OK, but what about using the 'stop' icon when TimerNode does not 'stop', it pauses?

**Comment by pixelzoom** [comment]
> My recollection was that we intentionally did not want to use the same icons so as to disambiguate action on the timer from action on the sim.

OK, so you want to make the play icon look different, I'll buy that.

But what about using the 'stop' icon when TimerNode does not 'stop', it pauses?

**Comment by pixelzoom** [comment]
I'm also not clear on why it was important to use a different icon for 'play', but the same icon for 'stop'.  

![screenshot_862](https://user-images.githubusercontent.com/3046552/48450957-770f3a80-e765-11e8-8075-1b39ff16eb72.png)

![screenshot_855](https://user-images.githubusercontent.com/3046552/48440679-c7c36b00-e746-11e8-9f79-41392ed58975.png)

**Comment by pixelzoom** [comment]
By the way... The only reason that I care about this at all is because I need to create a new component with a play/pause button like the one in TimerNode.  And that play/pause button is now duplicated in at least 2 places, see https://github.com/phetsims/scenery-phet/issues/428.  So if I have to deal with this, I figured that I'd see if PhET wants to standardize on the play/pause icon.

**Comment by pixelzoom** [comment]
By the way... The only reason that I care about this at all is because I need to create a new component (for Gas Properties) with a play/pause button like the one in TimerNode.  And that play/pause button is now duplicated in at least 2 places, see https://github.com/phetsims/scenery-phet/issues/428.  So if I have to deal with this, I figured that I'd see if PhET wants to standardize the play/pause icon, or even when to use these icons.

**Comment by ariel-phet** [comment]
@pixelzoom made a good suggestion in #428 of using a different fill but unifying icons. I am on board with that. I am fine with the icon changing to a pause button, perhaps we also try the alternate fill in the pause button to keep a consistent look on timer node?

**Comment by pixelzoom** [comment]
@ariel-phet Alternate fill for pause button looks pretty awful:

![screenshot_889](https://user-images.githubusercontent.com/3046552/49114290-14359d00-f255-11e8-9dbe-7932eaf1d2e3.png)

**Comment by pixelzoom** [comment]
TimerNode icons are changed, along with a bunch of cleanup and a `dispose` bug fix. See above commits.  

The pause icon is still filled with black. It looked awful with "alternate fill":

![screenshot_889](https://user-images.githubusercontent.com/3046552/49116960-7219b300-f25c-11e8-90a6-ce1b331081a1.png)
 
The play icon is still using the inverted fill.  I still think that this makes it look somewhat disabled, and I don't really understand the concern about confusion with the play/pause button for the sim.  I think it looks much better with the "standard" black fill, see comparison below.   But I'll defer to others.

![screenshot_890](https://user-images.githubusercontent.com/3046552/49117022-aee5aa00-f25c-11e8-8fc7-a9431fe54400.png) ![screenshot_891](https://user-images.githubusercontent.com/3046552/49117030-b1e09a80-f25c-11e8-8d52-fdba2a36b207.png)

Assigning to @ariel-phet to decide if there's more to do here, or have someone review.

**Comment by samreid** [comment]
The filled buttons seem preferable.  More consistent, look nicer, don't look disabled.

**Comment by arouinfar** [comment]
While I have a slight preference for the so-called "alternate fill" play button, its corresponding pause looks terrible. It's not immediately recognizable as a pause button, which is problematic. 

For consistency, I would vote for standard black play and pause icons.

**Comment by pixelzoom** [comment]
Since all of the votes have been for using `iconFill: 'black'` as the default for all icons, I've gone ahead and made that change.  You can test drive this in master with the scenery-phet demo application.  Compare TimerNode in the _Components_ screen to `PlayPauseButton` in the _Buttons_ screen to see that they look and behave consistently.

Assigned to @ariel-phet  for signoff.

**Comment by arouinfar** [comment]
@pixelzoom I think the play/pause button on the TimerNode is looking nice.

<img width="123" alt="screen shot 2018-11-29 at 10 12 53 am" src="https://user-images.githubusercontent.com/8419308/49239258-86c28c00-f3bf-11e8-8b73-75f2727b66f5.png"> <img width="127" alt="screen shot 2018-11-29 at 10 12 27 am" src="https://user-images.githubusercontent.com/8419308/49239260-86c28c00-f3bf-11e8-95aa-ce81b915ba90.png">

**Comment by pixelzoom** [comment]
It's also nice that there's consistency in Gas Properties, where these icons appear in multiple places, see below.  They are all using the same Shape common code. 

![screenshot_898](https://user-images.githubusercontent.com/3046552/49239659-8971b100-f3c0-11e8-896a-73bb3e08a2df.png)

**Comment by ariel-phet** [comment]
Sounds good, closing
