### ISSUE TITLE
support for "no value" in NumberDisplay

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#431]
In https://github.com/phetsims/states-of-matter/issues/236#issuecomment-438838653, @arouinfar identified many UI components that display "no value" as "-" (hypen), e.g.:

<img src="https://user-images.githubusercontent.com/8419308/48515671-928a4c00-e81e-11e8-881a-c26665e562a1.png" width=150>  <img src="https://user-images.githubusercontent.com/8419308/48515856-2f4ce980-e81f-11e8-881f-71517fc74b9d.png" width=150> <img src="https://user-images.githubusercontent.com/8419308/48515882-3e339c00-e81f-11e8-9be2-d0eb75c81621.png" width=150><img src="https://user-images.githubusercontent.com/8419308/48515901-4ab7f480-e81f-11e8-8a53-d4126f2648de.png" width=150>

And in that same issue, I recommended using `NumberDisplay` for displaying temperature in SOM, and that's what I've done in Gas Properties.  But `NumberDisplay` does not currently support "no value". 

Questions:
* Should NumberDisplay support "no value"? (I believe so.) 
* Can we standardize on '-' for the "no temperature" value? Or should we use a longer dash like "—" (em dash)?
* Does the "no value" string need to be translatable?

**Comment by arouinfar** [comment]
Not sure how relevant it is, but these tools all use slightly different methods to display "-". Since I had already dug through .js files when investigating https://github.com/phetsims/states-of-matter/issues/236#issuecomment-438838653, I'll add the code snippets below.

IntensityMeter in bending-light displays the "miss" string, "-" 
https://github.com/phetsims/bending-light/blob/master/bending-light-strings_en.json#L44-L45
```js
44  "miss": {
45    "value": "-"
```

PHMeter in ph-scale displays null
https://github.com/phetsims/ph-scale/blob/master/js/macro/model/PHMeter.js#L29
```js
29    this.valueProperty = new Property( null ); // @public null if the meter is not reading a value
```

Tracer in projectile-motion also displays null
https://github.com/phetsims/projectile-motion/blob/master/js/common/model/Tracer.js#L36-L37
```js
36    // @public {Property.<DataPoint||null>} point that the tracer is displaying information about, or null if no info displayed
37    this.dataPointProperty = new Property( null );
```

ConcentrationMeterNode in beers-law-lab has READOUT_NO_VALUE set to "-"
https://github.com/phetsims/beers-law-lab/blob/master/js/concentration/view/ConcentrationMeterNode.js#L49
```js
49  var READOUT_NO_VALUE = '-'; // displayed in the readout when the meter is not measuring anything
```

To answer @pixelzoom's questions:

> Should NumberDisplay support "no value"? (I believe so.)

Yes, absolutely!

> Can we standardize on '-' for the "no temperature" value?

Yes. I would go even further to standardize all "no value" readings across phet sims to "-", though I realize that's probably beyond the scope of this particular issue.

> Does '-' need to be translatable?

No, I don't believe so.

Of the examples in https://github.com/phetsims/scenery-phet/issues/431#issue-380914464, only the IntensityMeter in Bending Light is translatable. The sim has been translated into 60 locales (about a third of those don't use a Latin alphabet), and only one locale chose to internationalize the hyphen (to an underscore). That locale happens to be es_MX and @DianaTavares confirmed that "-" and "_" aren't meaningfully different, and it was probably a typo on her part. She also said, "I like the idea of making this readouts not translatable!"

**Comment by pixelzoom** [comment]
@arouinfar What do you think about using a longer dash, like emdash "—"?   Hyphens looks a little small to me, and I suspect that's why "- -" was used in SOM.

**Comment by pixelzoom** [comment]
Done in the above commit.  If the value is `null`, then this string constant is displayed:

```js
26 var NO_VALUE_STRING = '\u2014'; // em dash
```

 I'm using this for the temperature combo box in Gas Properties, e.g.:

![screenshot_876](https://user-images.githubusercontent.com/3046552/48653277-4fb4a980-e9c1-11e8-86a8-7bb481335eed.png)

As for using this consistently in all sims... There are 2 ways to approach that:

(1) make all sims use NumberDisplay (more work)
(2) factor out NO_VALUE_STRING and have sims use that constant (less work)
 
Over to @arouinfar to decide how (and whether) to proceed with making this consistent across all sims.

**Comment by pixelzoom** [comment]
In the above commit, I moved the constant to an option, so that it can be customized:

```js
      // string that is displayed when numberProperty.value is null
      noValueString: '\u2014', // em dash
```

**Comment by arouinfar** [comment]
> As for using this consistently in all sims... There are 2 ways to approach that:
>
>(1) make all sims use NumberDisplay (more work)
>(2) factor out NO_VALUE_STRING and have sims use that constant (less work)

I'm not a dev, so it's hard for me to make this sort of call. Both sound reasonable, but perhaps (1) is closer to overkill, while (2) seems like a less-invasive way to give us the desired look. I'm leaning toward (2). 

There isn't a particular rush to use an emdash across all sims. I would think we could chip away at it as these components are revisited in the scope of regular sim work.

**Comment by pixelzoom** [comment]
I think we should proceed with factoring out the string, since there will likely be places where it should be used that are not appropriate to use NumberDisplay. 

Labeling for developer meeting to see if adding this to MathSymbols would be too much of a stretch:

`NO_VALUE: '\u2014', // em dash`

Or is there a better place to put this?

**Comment by jonathanolson** [comment]
MathSymbols seems like a nice place for it.

**Comment by pixelzoom** [comment]
Proposal:
* add `NO_VALUE: '\u2014', // em dash` to MathSymbols
* use `NO_VALUE` in sims where "no value" is shown in a display (as identified by @arouinfar)

**Comment by pixelzoom** [comment]
I asked for feedback on 12/6/18.  I see 3 votes for putting this in MathSymbols, and no votes against.  And I guess I'll assume that other devs have no opinion.   So I'm going to proceed as proposed.

**Comment by pixelzoom** [comment]
`MathSymbols.NO_VALUE` has been added.  I identified sims that needed to use it based on the screenshots in https://github.com/phetsims/scenery-phet/issues/431#issue-380914464, and searching for `'-'` in the code bases.  The sims that changed are:

bending-light
beers-law-lab
fluid-pressure-and-flow
ph-scale
projectile-motion

@arouinfar please have  look at these in master and verify that you're happy with the end result. If all looks well, please close this issue.

**Comment by arouinfar** [comment]
Looks great @pixelzoom, thanks!

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/energy-skate-park/issues/56 I am using NumberDisplay to represent values that can sometimes be "null". In that case, the displays should look like
![image](https://user-images.githubusercontent.com/6396244/51778850-f3ad8600-20d1-11e9-9ae2-d3a9773d9d30.png)

When there are values, they are right aligned. So the "no value" case needs different alignment and shouldn't use the optional `valuePattern`. @pixelzoom is this something NumberDisplay can support?

**Comment by jessegreenberg** [comment]
Possibly with new options `noValuePattern` and `noValueAlign` or something?

**Comment by jessegreenberg** [comment]
Most examples of "no value" in https://github.com/phetsims/scenery-phet/issues/431#issue-380914464 have the dash centered with no units, so I am actually wondering if this should be the default behavior.

**Comment by pixelzoom** [comment]
> When there are values, they are right aligned. So the "no value" case needs different alignment and shouldn't use the optional valuePattern. 

Why should "no value" be aligned differently than values? Why not align it the same as values?

> @pixelzoom is this something NumberDisplay can support?

I'm not clear on what you're asking.  NumberDisplay does not currently support dynamic alignment, or a different alignment for "no value".

**Comment by jessegreenberg** [comment]
I think generally it looks strange to have units to next to `MathSymbols.NO_VALUE`, and the usage in gas-properties is a special case. And if units are removed in that case, alignments of `MathSymbols.NO_VALUE` other than center will also usually look strange, even if the values have right or left alignment.
![image](https://user-images.githubusercontent.com/6396244/51851799-a0664e00-22f2-11e9-8e69-18a45a91ab6f.png)

**Comment by pixelzoom** [comment]
https://github.com/phetsims/scenery-phet/issues/431#issuecomment-458209963 doesn't look strange to me at all.   I think it's fine (and perhaps even preferable) place the "no value" symbol in the same place the a value would have appeared.

**Comment by pixelzoom** [comment]
One more note...  Regardless of what is decided for NumberDisplay, this is something that will not be trivial to standardize.  There are plenty of displays that utilize "no value", do not use NumberDisplay, and do their own custom placement of value and "no value".   From https://github.com/phetsims/scenery-phet/issues/431#issue-380914464, the Intensity, pH, and Concentration meters are all examples that do not use NumberDisplay.

**Comment by pixelzoom** [comment]
I'm going to add option `noValueAlign` to NumberDisplay.  If not provided, it will default to `align`.

**Comment by jessegreenberg** [comment]
I find the example in https://github.com/phetsims/scenery-phet/issues/431#issuecomment-458215239 compelling. @pixelzoom do you have any thoughts about optionally filling in `options.valuePattern` for no value?

**Comment by pixelzoom** [comment]
I'll also add:

```js
noValuePattern: null, // {string|null} If null, defaults to options.valuePattern
```

**Comment by pixelzoom** [comment]
Options added in above commits.  By default, the same alignment and pattern are used numeric values and "no value".    If you want different behavior for "no value", see `noValueAlign" and `noValuePattern`.  To experiment with these options, see `demoNumberDisplay` in ComponentsScreenView of scenery-phet demo.   

@jessegreenberg would you please review?

**Comment by jessegreenberg** [comment]
This is great, thanks for adding this @pixelzoom.
