### ISSUE TITLE
issues with GaugeNode 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#432]
I need to use `GaugeNode` in Gas Properties.  This issue notes things that were done poorly when this was moved to common code.  

First, some issues related to these lines:

```js
5  * This was originally ported from the speedometer node in forces-and-motion-basics.
...
30     * @param {string} label label to display (scaled to fit if necessary)
31      * @param {Range} range
...
38      radius: 67,
...
42      anglePerTick: Math.PI * 2 / 4 / 8,
...
      // 8 ticks goes to 9 o'clock (on the left side), and two more ticks appear below that mark.
      // The ticks are duplicated for the right side, and one tick appears in the middle at the top
49      numTicks: ( 8 + 2 ) * 2 + 1,
```

- [x] Line 5: Ported, but apparently not cleaned up and generalized.

- [x] Line 30: `{Node} label` would be more flexible
  
  UPDATE: No op, see https://github.com/phetsims/scenery-phet/issues/432#issuecomment-452144281

- [x] Line 31: Insufficient doc. What happens if `valueProperty` exceeds `range`? I guess I'll spend 15 minutes finding out, as will everyone who uses this.

- [x] Line 38: This doesn't look like a general default. I'm guessing it was the value needed by FAMB.  This is a chronic problem in common code, blue sun buttons being the most infamous.

- [x] Line 42: Default value is (almost) incomprehensible, and dependent on magic numbers on line 49.

- [x] Line 49: Again, default value is almost incomprehensible, and dependent on magic numbers on line 42. 

Other issues:

- [x] There should be an assertion that `options.numTicks * options.anglePerTick <= 2 * Math.PI` 

- [x] The needle should probably stop at max/min when `valueProperty` is out of `range`, rather than blowing past the min/max tick marks.  (I haven't confirmed that this is what happens, but it looks that way from reading the code.)

  UPDATE: I've (@chrisklus) tested out-of-range values in the scenery phet demo and they are handled gracefully. I don't yet understand why, though. It doesn't look like any clamping is happening.

  Oh, I understand now. The slider that I hooked up to it in the scenery-phet demo was clamping it on initialization. I'll add a clamp in GaugeNode.

- [x] `dispose`  does not handle `options.updateEnabledProperty` properly.  If GaugeNode owns `options.updateEnabledProperty`, it needs to call `options.updateEnabledProperty.dispose`.   If the client owns it, then is needs to call `options.updateEnabledProperty.unlink`.  This is a potential memory leak.

- [x] PhET-iO deregistration is not handled by `dispose`. `foregroundNode` and `labelNode` are given tandems, so we presumably need to call `dispose` on these subcomponents in order to deregister them.  This is a potential memory leak.

- [x] `GaugeNode` is not represented in the scenery-phet demo application.

@ariel-phet I can certainly take care of these.  But perhaps it would be a good learning experience for someone else?

**Comment by ariel-phet** [comment]
@chrisklus is up for this work

**Comment by ariel-phet** [comment]
@chrisklus I believe @jbphet did this initial port, so also feel free to consult with him on this work

**Comment by pixelzoom** [comment]
Re:

> - [ ] The needle should probably stop at max/min when valueProperty is out of range, rather than blowing past the min/max tick marks. (I haven't confirmed that this is what happens, but it looks that way from reading the code.)

What I'm observing is that if valueProperty.value > range.max, there is no error. But the needle is at range.min, and that makes no sense to me.

**Comment by chrisklus** [comment]
@pixelzoom my apologies for not getting to more of this sooner. I have some questions for a few of these.

>{Node} label would be more flexible

Right now the position of the label is hard coded as
```js
centerX: 0,
centerY: -options.radius / 3
```
Should this be able to be set by options?


>`38      radius: 67,`
Line 38: This doesn't look like a general default. I'm guessing it was the value needed by FAMB. This is a chronic problem in common code, blue sun buttons being the most infamous.

Should I set this to, say 100, and then go through and update the current usages that don't set radius? I see 6 occurrences that either don't set radius or instead use scale to set the size.


```js
42      anglePerTick: Math.PI * 2 / 4 / 8,
...
      // 8 ticks goes to 9 o'clock (on the left side), and two more ticks appear below that mark.
      // The ticks are duplicated for the right side, and one tick appears in the middle at the top
49      numTicks: ( 8 + 2 ) * 2 + 1,
```
> Line 42: Default value is (almost) incomprehensible, and dependent on magic numbers on line 49.
> Line 49: Again, default value is almost incomprehensible, and dependent on magic numbers on line 42.

I'm thinking about having constants `DEFAULT_SPAN` (radians) and `DEFAULT_NUMBER_OF_TICKS` and then options: 
```js
numberOfTicks: DEFAULT_NUMBER_OF_TICKS,
anglePerTick: DEFAULT_SPAN / DEFAULT_NUMBER_OF_TICKS,
minorTicksPerMajor: 2 // since this is not flexible right now
```
How does that sound to you?

**Comment by pixelzoom** [comment]
Re "{Node} label would be more flexible"...  Let's punt on that change.  I hadn’t considered that the label was being instrumented, and we probably want it to appear as a subcomponent for GaugeNode in Studio.  And non-string labels for GaugeNode are highly unlikely.

**Comment by pixelzoom** [comment]
@chrisklus I'm about to start working on the Gas Properties model for pressure, and I hope to be hooking `GaugeNode` up to that model within the next 3-5 days.  And in doing so, I will undoubtedly hit some of the issues that I've identified.  Should I take over completion of this issue, or do you have time to address it with high priority?

**Comment by chrisklus** [comment]
@pixelzoom thanks for the heads up, I'll finish it with high priority.

**Comment by chrisklus** [comment]
@pixelzoom I've completed your requested changes. Please review.

**Comment by pixelzoom** [comment]
Thanks much for the quick response.   But several problems are still present

(1)  The change made in https://github.com/phetsims/scenery-phet/commit/af1676a369532b9e6793cfc615100531cf4135ff introduces a reentrant Property issue. When `valueProperty` changes, it calls `updateNeedle`, which in turn may change `valueProperty`. Relevant lines of code:

```js
109 var updateNeedle = function() {
...
  valueProperty.value = Util.clamp( valueProperty.get(), range.min, range.max );
...
};
...
130 valueProperty.link( updateNeedle );
```

(2) GaugeNode is failing when range has a negative value.  To demonstrate, use this line in SCENERY_PHET/ComponentsScreenView, `demoGaugeNode`:

```js
428 var gaugeValueRange = new Range( -100, 100 );
```

(3) Re this item:
 
> - [ ] The needle should probably stop at max/min when valueProperty is out of range, rather than blowing past the min/max tick marks. 

The gauge shouldn't fail when its range is exceeded.  It should just stop the needle at its min/max positions.  After the changes, I'm now seeing a hard failure when the gauge's range is exceeded. To demonstrate, use this line in SCENERY_PHET/ComponentsScreenView, `demoGaugeNode`:

```js
429    var sliderValueRange = new Range( gaugeValueRange.min - 20, gaugeValueRange.max + 20 );
```

(4) Re `updateEnabledPropertySupplied`...  Other UI components use `ownsEnabledProperty`, which has inverse semantics.  See for example `Checkbox`, `ComboBox, `Slider`, `FineCoarseSpinner`, and `NumberPicker`.  Recommended to use this same pattern, since there's a plan to factor it out, see https://github.com/phetsims/sun/issues/257.

**Comment by chrisklus** [comment]
>(1)  The change made in https://github.com/phetsims/scenery-phet/commit/af1676a369532b9e6793cfc615100531cf4135ff introduces a reentrant Property issue. When `valueProperty` changes, it calls `updateNeedle`, which in turn may change `valueProperty`. A Property observer should not change the Property that it's observing.

Oh duh, whoops. Should I just clamp the property value as a new var, then?

```js
// clamp value to valid range and map it to an angle
var clampedValue = Util.clamp( valueProperty.get(), range.min, range.max );
var needleAngle = Util.linear( range.min, range.max, startAngle, endAngle, clampedValue );
```

>(2) GaugeNode is failing when range has a negative value. 

Yeah, there is an assert preventing negative values, which I assumed was the desired behavior. Should I remove the assert?

> (3) The gauge shouldn't fail when its range is exceeded.  It should just stop the needle at its min/max positions.  After the changes, I'm now seeing a hard failure when the gauge's range is exceeded.

Only because of the reentry you identified in (1). My proposed fix for (1) gracefully handles exceeded ranges.

>(4) Re updateEnabledPropertySupplied... Other UI components use ownsEnabledProperty, which has inverse semantics. See for example Checkbox, ComboBox, Slider, FineCoarseSpinner, and NumberPicker`. Recommended to use this same pattern, since there's a plan to factor it out, see phetsims/sun#257.

Thanks for the tip, I haven't seen this before.

**Comment by chrisklus** [comment]
Since this is high priority (and the reentry issue was breaking CT), I went ahead and pushed my two proposed changes from https://github.com/phetsims/scenery-phet/issues/432#issuecomment-476385107.

I updated the range in scenery-phet demo so negative values and the out-of-range behavior are apparent.

Ready for review.

**Comment by pixelzoom** [comment]
Looking good! A couple of things....

* Clarification about the range.  Since GaugeNode isn't should be usable for any quantity, there should be no constrain that the range must be positive.  Thanks for taking care of that, solution looks good.

* Thing things were missing related to `enabledProperty`.  (1) Any option that's referenced in the code should be represented by a default value and documentation in the options hash.  That was not the case, so I added it in  https://github.com/phetsims/scenery-phet/commit/042b616046625bf8cd4d2f280167a61bc26bba1c.  (2) If the client doesn't provide `options.enabledProperty`, they should be able to use the `enabledProperty` created by GaugeNode.  That was not possible, so I added `this.enabledProperty` in https://github.com/phetsims/scenery-phet/commit/5ce1fd0fabceae035ac9a016035f18dd67c9575a.

The other commits above were some minor documentation fixes. 

Back to @chrisklus, feel free to close this if all looks to be in order.

**Comment by chrisklus** [comment]
>(1) Any option that's referenced in the code should be represented by a default value and documentation in the options hash.

Oh yeah, understood.

>(2) If the client doesn't provide options.enabledProperty, they should be able to use the enabledProperty created by GaugeNode.

Right! Thanks for making these changes and letting me know what needed improvement.

Ready to close.
