### ISSUE TITLE
HeaterCoolerNode should not dispose heatCoolAmountProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#436]
Related to changes made for #423.

In HeaterCoolerNode, the constructor is:

`constructor( heatCoolAmountProperty, options )`

And then `disposeHeaterCoolerNode` is calling:

`this.heatCoolAmountProperty.dispose();`

HeaterCoolerNode should _not_ be disposing of `heatCoolAmountProperty`, since it does not own that Property.

**Comment by Denz1994** [comment]
`this.heatCoolAmountProperty` is no longer being disposed of by the HeaterCoolerNode. `HeaterCoolerNode.dispose()` only disposes of `HeaterCoolerFront` and `HeaterCoolerBack`.

**Comment by Denz1994** [comment]
#438 has further input from @pixelzoom that should address further complications with the dispose functions.

**Comment by Denz1994** [comment]
Leaving to @pixelzoom to close along with #438.
