### ISSUE TITLE
HeaterCoolerBack has unused options

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#437]
Related to #423 and https://github.com/phetsims/scenery-phet/issues/435.

These HeaterCoolerBack options are not used:

```js
        snapToZero: true, // controls whether the slider will snap to the off.
        heatEnabled: true, // Can this node heat the environment?
        coolEnabled: true // Can this node cool the environment?
```

Looks like they were copy-pasted from HeaterCoolerFront and HeaterCoolerBack.

**Comment by chrisklus** [comment]
Thanks @Denz1994! Closing.
