### ISSUE TITLE
Add a value readout to GaugeNode

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#440]
In FAMB and now ESP there was a request that GaugeNode display a readout of the value like
![image](https://user-images.githubusercontent.com/6396244/50021415-026b2e00-ffa7-11e8-92ab-bf49eb33d40a.png)

@samreid and @jbphet (original authors) do you mind if I add this value readout to GaugeNode? I also noticed that @chrisklus is doing some work in GaugeNode  in #434, just pinging him in case he has any thoughts.

**Comment by samreid** [comment]
Sounds reasonable!  Do you think this will use `NumberDisplay`?

**Comment by jessegreenberg** [comment]
Yes, that makes it easy, thanks! It turns out I may not be able to use this in energy-skate-park anyway though because that sim uses a custom node for the needle with webgl for performance and passes a dummy Property to the GaugeNode.

In gas-properties and states-of-matter the readout has a different style (granted in gas-properties it uses a combobox):
![image](https://user-images.githubusercontent.com/6396244/50022791-5415b780-ffab-11e8-93de-3b79dfe75f64.png)
![image](https://user-images.githubusercontent.com/6396244/50022814-63950080-ffab-11e8-8b89-3ba25f457cf1.png)

**Comment by jessegreenberg** [comment]
OK, thanks, I made the above issue for ESP.

**Comment by jessegreenberg** [comment]
I still added this to GaugeNode. I felt that the displays in gas-properties and states-of-matter were different enough that those could remain custom. 

The display in FAMB can only report the absolute value for speed so I also added a mapValue option to NumberDisplay to support this.

@samreid would you have time to review this? If not feel free to reassign to me.

**Comment by jessegreenberg** [comment]
Hmm, should the default NumberDisplay option for mapValue in GaugeNode be
```js
mapValue: function( value ) { return Math.abs( value ); }
```
because gauges typically report absolute values?

**Comment by samreid** [comment]
> mapValue: function( value ) { return Math.abs( value ); }

I would be more inclined to `assert && assert(value>=0)` -- it seems if some Property is given to a gauge and it goes negative it may indicate a logic error.

**Comment by samreid** [comment]
> @samreid would you have time to review this? If not feel free to reassign to me.

I am backlogged a bit, but could try to get to this in a few weeks.  Is there a deadline?

**Comment by jessegreenberg** [comment]
> I would be more inclined to assert && assert(value>=0) -- it seems if some Property is given to a gauge and it goes negative it may indicate a logic error.

OK, sounds good.

I see the assertion I added to NumberDisplay is being thrown in projectile-motion in Bayes CT. Ill take a look.

**Comment by jessegreenberg** [comment]
I added the recommended assertion to GaugeNode. Ensuring that GaugeNode's NumberDisplay is non-negative made my changes to NumberDisplay unnecessary so I reverted those changes.

There is no deadline, just a common code change that should be reviewed. Now that changes are isolated to GaugeNode and hidden behind an option this touches far fewer sims, so feels OK if this isn't hit right away.

**Comment by pixelzoom** [comment]
I didn't realize this work was being done.  @arouinfar and others have requested that the combobox-style display used in Gas Properties and SOM should become the standard, and I've been working on the combobox in #449.    I think we can meet all needs, but this issue is nowhere close to resolved.

**Comment by pixelzoom** [comment]
Btw... If it were me, I would not have added this value display directly to GaugeNode.   There's no need for the additional complexity in GaugeNode (more options, more code,..), since the value display is entirely independent of the gauge.  The value display could have been added to a subclass that decorates GaugeNode with the value display.  And then sims that need a combobox-type display could have used a similar subclass of GaugeNode that's decorated with a combobox-type display.

**Comment by pixelzoom** [comment]
Looking more at GaugeNode, I'm really don't like the way this was done, especially:

```js
    // @private {NumberDisplay} - display for the valueProperty, hidden by default
    this.numberDisplay = new NumberDisplay( valueProperty, range, options.numberDisplayOptions );
    this.addChild( this.numberDisplay );
```

So every GaugeNode instance gets the overhead of a NumberDisplay, regardless of whether it's needed.  In Gas Properties, I need a different type of display, and I shouldn't be paying a penalty for a display that I don't need.   And this was know about Gas Properties and SOM before this feature was implemented. 

So please create a subclass of GaugeNode that adds this display, and move the NumberDisplay out of GaugeNode.

**Comment by pixelzoom** [comment]
Nested options pattern is also applied incorrectly. 

```js
      // options passed to the NumberDisplay, see NumberDisplay for full list of available options
      numberDisplayOptions: {},
```

should be:

```js
 // {*|null} options passed to the NumberDisplay, see NumberDisplay for full list of available options
 numberDisplayOptions: null
```

There is no need to create an object for the default value.  This means that every GaugeNode instance results in at least one more object allocation.

**Comment by jessegreenberg** [comment]
OK, this makes sense. Reassigning to me.

**Comment by jessegreenberg** [comment]
The above commit removes NumberDisplay from GaugeNode, creates a new subtype of GaugeNode called ValueGaugeNode that includes a NumberDisplay. And the nested options pattern was fixed.

**Comment by pixelzoom** [comment]
@jessegreenberg One bug fix in the above commit.  Otherwise looks great.  Feel free to close after having a look.

**Comment by jessegreenberg** [comment]
Oops, thank you! OK, thanks for reviewing, closing this issue.
