### ISSUE TITLE
Consider use of `innerHTML` in ariaHerald

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/scenery-phet#441]
From https://github.com/phetsims/gravity-force-lab/issues/131.

We're currently setting the `textContent` of the `aria-live` elements which strips HTML Entities (e.g. `&times;`) instead of rendering them. 

It may be more pertinent to simply spell out such cases, but we could also consider adding a flag to the config object that indicates the inclusion of HTML in the alert.

**Comment by jessegreenberg** [comment]
I committed this and it seems OK with NVDA. @mbarlow12 can you please review and test if this fixes things in VO?

**Comment by mbarlow12** [comment]
Thanks @jessegreenberg. My only hesitation would be whether we want to fully support all HTML features in our alerts. The most significant use case I can think of would be for MathML, which may be a valid consideration as we move onto a11y tooling in more math-heavy sims.

Can you think of a situation where it would be useful to include generic HTML in an `aria-live` element?

**Comment by mbarlow12** [comment]
Results are mixed. The entity is now correctly rendered, but VO appears to contextually read "multiplication" or "times" depending on some unknown parameters. `aria-live` elements are read as "multiplication" while PDOM list items appear as "times". Very odd.

**Comment by jessegreenberg** [comment]
OK understood, thanks for testing. In that case we may have to go back to passing in "times" as a full string.  We do not have control over how VO interprets the context unfortunately.

**Comment by mbarlow12** [comment]
@jessegreenberg I'll do a little testing/digging this week to see if there might be a way for us to tweak what VO reads.

**Comment by jessegreenberg** [comment]
Closing this issue for now, we will work on this naturally when we require more complicated entities in alerts.
