### ISSUE TITLE
HeaterCoolerNode: add ability to hide slider

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#442]
Gas Properties design document specifies that the slider (the entire slider) needs to be hidden when temperature is held constant.   This is not currently supported by HeaterCoolerNode and needs to be added.

**Comment by pixelzoom** [comment]
These also no ability to disable the slider. So either way, this issue will result in a change.

**Comment by pixelzoom** [comment]
Back to @arouinfar since this is a design issue.

**Comment by pixelzoom** [comment]
12/20/18 Gas Properties design meeting:  Add ability to hide the entire slider.

**Comment by pixelzoom** [comment]
Houston, we have problems here.  

It looks like EFAC also needed access to the slider, and the access was provided in a questionable way. In https://github.com/phetsims/scenery-phet/commit/86fa5798c83e8541c4b810875b47ef44937e1624, @chrisklus made HeaterCoolerFront's `heatCoolSlider` a `@protected` field, so that it could be accessed to set `pickable` (see EFAC/LinkableHeaterCoolerFront) and to listen to `isThumbDraggingProperty` (see EFACIntroScreenView).  A couple of problems with what was done:

(1) Always evaluate names when making something public. `heatCoolSlider` is a lousy name.  It's redundant, and is different enough from "HeaterCooler" to be confusing. I renamed it to `slider` in the above commit.

(2) The slider was made `@protected` for `HeaterCoolerFront`, but there's no way to get at it from the more commonly used `HeaterCoolerNode`.  

(3)  EFACIntroScreenView is violating the `@protected` visibility of the slider.  It's only visible to subclasses of `HeaterCoolerFront`, which is not `EFACIntroScreenView`.  The offending lines are:

```js
196 leftLinkableHeaterCoolerFront.slider.isThumbDraggingProperty,
197 rightLinkableHeaterCoolerFront.slider.isThumbDraggingProperty
```

(4) This is a change to common code. Was it reviewed?

**Comment by pixelzoom** [comment]
I started down the path of making making the slider `@private` and adding methods like `setSliderVisible`, `setSliderPickable`, and `addSliderIsThumbDraggingListener`.  Boy was that awkward. Those methods would need to be added to both `HeaterCoolerFront` and `HeaterCoolerNode`.   And there are likely to be more slider properties that we'll need to access in the future.  So I bailed, and decided to just make slider `@public`:

In HeaterCoolerFront:

```js
      // @public With this visibility annotation comes great power - use it wisely.
      // See https://github.com/phetsims/scenery-phet/issues/442
      this.slider = new VSlider( heatCoolAmountProperty,
```

In HeaterCoolerNode:

```js
      // @public With this visibility annotation comes great power - use it wisely.
      // See https://github.com/phetsims/scenery-phet/issues/442
      this.slider = heaterCoolerFront.slider;
```

And I'm now using this in Gas Properties to hide the slider when temperature is held constant. In `GasPropertiesHeaterCoolerNode`:

```js
      // Hide the slider when temperature is held constant
      holdConstantProperty.link( holdConstant => {
        this.slider.visible = ( holdConstant !== HoldConstantEnum.TEMPERATURE );
      } );
```

**Comment by pixelzoom** [comment]
@chrisklus since you've been in HeaterCoolerNode a bunch, would you mind reviewing this? If you have any reservations about making the slider `@public`, perhaps get a second opinion from @jbphet.

**Comment by chrisklus** [comment]
>(1) Always evaluate names when making something public. heatCoolSlider is a lousy name. It's redundant, and is different enough from "HeaterCooler" to be confusing. I renamed it to slider in the above commit.

>(2) The slider was made `@protected` for HeaterCoolerFront, but there's no way to get at it from the more commonly used HeaterCoolerNode.

Noted, thank you.

>(4) This is a change to common code. Was it reviewed?

Not yet. https://github.com/phetsims/energy-forms-and-changes/issues/60 has been awaiting review.

>would you mind reviewing this? 

>I started down the path of making making the slider `@private` and adding methods like setSliderVisible, setSliderPickable, and addSliderIsThumbDraggingListener. Boy was that awkward.

That does sound very clunky. I agree that `@public` is the way to go. I've looked through the commits that you've made since I was last in here and your changes look good. Thanks for adding this to HeaterCoolerNode.
