### ISSUE TITLE
new sims are using old-style formatting patterns

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#446]
Noted during Wave Interference code review https://github.com/phetsims/wave-interference/issues/259.

Wave Interference, a new sim, is necessarily using old-style (numeric placeholders) formatting patterns:

```js
  "cmValue": {
    "value": "{0} cm"
  },
  "nmValue": {
    "value": "{0} nm"
  },
```

New-style (named placeholders) would be:

```js
  "cmValue": {
    "value": "{{value}} cm"
  },
  "nmValue": {
    "value": "{{value}} nm"
  },
```

I say "necessarily using" because we have common components (`NumberControl`, `NumberDisplay`,...) that use this format.  

Creating more strings that use the old-style seems like something that we want to avoid.

Options, in order of increasing cost/complexity:

(1) Tolerate this and do nothing.

(2) Make client code adapter new-style patterns to UI components that use old-style components. E.g.

```js
const oldPattern = '{0} cm';
const newPattern = StringUtils.format( oldPattern, '{{value}}' );
const string = StringUtils.fillIn( newPattern, { value: 10 } );
```

(3) Provide a utility for doing (2).

(4) Change the UI components to recognize both old-style and new-style.

(5) Change the UI components to use new-style, and change all existing translations.

**Comment by jonathanolson** [comment]
I could be remembering incorrectly, but I thought we would use the new style (`'{{value}} cm'`) and then `StringUtils.fillIn( str, { value: '{0}' } )` when we had to provide things to a component that required numbered values. It seems like option (2) in practice, but is not very verbose.

An example is in masses-and-springs for use with NumberControl:
```js
        valuePattern: StringUtils.fillIn( gravityValueString, {
          gravity: '{0}'
        } ),
```
with the string:
```js
  "gravityValue": {
    "value": "{{gravity}} m/s<sup>2</sup>"
  },
```

I also see this pattern being used a lot when searching for `'{0}'`. I'd propose that this adapter pattern is fine for now, particularly since trying to update everything to named strings would break a lot of currently-translated strings.

**Comment by pixelzoom** [comment]
Raising priority since this is blocking https://github.com/phetsims/wave-interference/issues/266.

**Comment by pixelzoom** [comment]
My recollection is the same as what @jonathanolson said in https://github.com/phetsims/scenery-phet/issues/446#issuecomment-449064164.  But I thought we should revisit since (a) Wave Interference isn't using that pattern, and (b) it's not a great longterm solution.

**Comment by pixelzoom** [comment]
I volunteered for this at today's status meeting 12/20/18.  The plan is to make NumberDisplay support both numbered and named placeholders, with the constrain that they be `{0}` and `{{value}}` respectively.

**Comment by pixelzoom** [comment]
Something I ran into immediately when using named placeholders with NumberDisplay... `StringFormat.fillIn` fails an assertion if all placeholders are not filled in.  

Here's a typical example: 

```js
const valueUnitsString = requirejs( ... ); // "{{value}} {{units}}"
...
const numberDisplay = new NumberDisplay( ..., {
  format: StringFormat.fillIn( valueUnitsString, {
    units: 'nm'
  } )
} );
```

The above will fail because `{{value}}` is left unfilled, intended to be filled in by NumberDisplay.

Does anyone object to changing the behavior of `StringFormat.fillIn`, so that it's OK to leave placeholders unfilled?  @samreid @jonathanolson?

**Comment by pixelzoom** [comment]
I could do this:

```js
const numberDisplay = new NumberDisplay( ..., {
  format: StringFormat.fillIn( valueUnitsString, {
    value: '{{value}}`,
    units: 'nm'
  } )
} );
```

... but that's exactly the type of workaround that we're trying to remove.

**Comment by pixelzoom** [comment]
`StringUtils.fillIn` currently finds all placeholders, requires a key:value pair for each placeholder, and ignores any extra key:value pairs.   Perhaps it should process all key:value pairs, and require that each key:value pair has a placeholder, and ignore unfilled placeholders.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/scenery-phet/issues/446#issuecomment-450001644 got a 👍 on Slack.

**Comment by pixelzoom** [comment]
These repose are currently using the workaround to covert `{{value}}` to `{0}`, search for `value: '{0}'`.

- [ ] gas-properties
- [ ] inverse-square-law-common
- [ ] projectile-motion

**Comment by samreid** [comment]
Unit test phetcommon/phetcommon-tests.html?ea is failing, can you please take a look before I review?

**Comment by pixelzoom** [comment]
Will do. I didn't realize that phetcommon had unit tests.

**Comment by pixelzoom** [comment]
Unit tests are fixed and passing.

**Comment by pixelzoom** [comment]
`StringUtils.fillIn` no longer requires that all parameters be filled in.  And the hack of converting `{{value}}` to `{0}` is not longer needed for NumberControl and NumerDisplay.

So this:

`valuePattern: StringUtils.fillIn( pattern0Value1UnitsString, { value: '{0}', units: unitString } ),`

should be changed to this:

`valuePattern: StringUtils.fillIn( pattern0Value1UnitsString, { units: unitString } ),`

**Comment by pixelzoom** [comment]
In addition to wave-interference `ISLCObjectControlPanel`, there are other sims that are doing some wonky replacements of '{0}'.

cck-common: There are 6 translated strings that should be using `{{value}}` instead of something like `{{voltage}}`.   And if you don't want to change the strings, then the replacement should be with `{{value}}`, not `{{0}``, like in  CircuitElementEditContainerNode.

masses-and-springs: GravityAndDampingControlNode, MassValueControlPanel.  These have a problem with their translated strings file. Where they have '{{gravity}}' and '{{mass}}', they should have '{{value}}'. Then the replacement to '{0}' is not needed. Not sure how this made it through code review.

pendulum-lab: PendulumNumberControl and its use in FrictionSliderNode, the `pattern` param seems to be totally unnecessary.  GravityControlNode wouldn't need '{0}' replacement if string `gravitationalAccelerationPattern` was `"{{value}} m/s<sup>2</sup>".

trig-tour: CoordinatesRow should be converted to named placeholders, since it doesn't involve translated strings.

**Comment by pixelzoom** [comment]
I'll create sim-specific issues for all of the above.

**Comment by pixelzoom** [comment]
To prevent a proliferation of `'{{value}'` and `'{0}'` string literals, I've added `NAMED_PLACEHOLDER` and `NUMBERED_PLACEHOLDER` static constants to NumberDisplay.

**Comment by pixelzoom** [comment]
Sim-specific issues have been created for sims that are doing unnecessary replacement or should be using constants instead of string literals. 

Back to @samreid to continue review.

**Comment by samreid** [comment]
I skimmed the commits and didn't see anything that requires further work.  

I added `@deprecated` annotation and converted to block comment so IDEA (and maybe other tools) can indicate usages as deprecated:

![image](https://user-images.githubusercontent.com/679486/53842909-10a16880-3f5e-11e9-8fdf-19f5a2b1dcdd.png)

Back to @pixelzoom about this last point--close if all is well.
