### ISSUE TITLE
Use nested options pattern for arrow buttons in NumberControl

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/scenery-phet#448]
From https://github.com/phetsims/coulombs-law/issues/89, I found that NumberControl only allows setting the `scale` and `delta` of the ArrowButtons. After discussing with @zepumph and @samreid, the nested options pattern (outlined [here](https://github.com/phetsims/phet-info/blob/147b5c5e34a83fb5f499c74903ee068b5bef5154/doc/phet-software-design-patterns.md#nesting)) seems to be the best solution.

I've found 31 files requiring NumberControl, and some set the options in a somewhat atypical fashion (e.g. Hooke's Law).

I've currently implemented the nested options as
```js
options.arrowButtonOptions = _.extend( {
  scale: options.arrowButtonScale,
  delta: options.delta
},
options.arrowButtonOptions );
```
to keep from breaking the existing uses. Should we consider a chip-away issue to address common components/nodes that aren't currently using the nested pattern for subcomponent/child options?

**Comment by jonathanolson** [comment]
> Should we consider a chip-away issue to address common components/nodes that aren't currently using the nested pattern for subcomponent/child options?

Sounds fine with me.

**Comment by pixelzoom** [comment]
I fixed a couple of problems in the above commit:

* arrowButtonOptions was added to the end, but (conventionally) phetio and a11y options are always last
* arrowButtonOptions was not documented

**Comment by pixelzoom** [comment]
@mbarlow12 there's a problem with this intermediate solution.  

Consider this usage:

```js
const numberControl = new NumberControl( ..., {
  arrowButtonOptions: {
    delta: 2
  }
} );
```

This is a problem, because now `options.delta` and `options.arrowButtonOptions.delta` will have different values (1 and 2 respectively).  And some of the constructor is using `options.delta`, other parts are using `options.arrowButtonOptions.delta`:

```js
144       var newValue = Util.roundToInterval( value, options.delta ); // constrain to multiples of delta, see #384

159 var delta = options.arrowButtonOptions.delta; // to improve readability
```

**Comment by mbarlow12** [comment]
Actually, this is an issue with the NumberControl implementation. While it's included as an option key for ArrowButton, none of ArrowButton's supertypes accept that key. "delta" only has a few occurrences in `sun` at all.

So, "delta" should not be included in the arrowButtonOptions object at all.

**Comment by mbarlow12** [comment]
@pixelzoom Fine by me, but I'm happy to handle it this afternoon as well.

**Comment by pixelzoom** [comment]
Go for it.  Based on Slack, it sounds you have other reasons to be in NumberControl.  And I have other common-code fish to fry.

**Comment by pixelzoom** [comment]
I took care of this in the above commits.   Relevant code in NumberControl:

```js
      // {*|null} options propagated to ArrowButton
      arrowButtonOptions: null,
...
    // Defaults for ArrowButton
    options.arrowButtonOptions = _.extend( {
      scale: 0.85
    }, options.arrowButtonOptions );
...
    var delta = options.delta; // to improve readability
```

In beers-law-lab, gravity-force-lab, masses-and-springs, pendulum-lab, and projectile-motion, I changed `arrowButtonScale: N` to `arrowButtonOptions: { scale: N }`.  And I tested all of those sims to verify that arrow buttons are the desired size.

@mbarlow12 please review.

**Comment by pixelzoom** [comment]
Oops, standby.  Something is broken with the arrow buttons.

**Comment by pixelzoom** [comment]
The problem I'm seeing is with the arrow buttons in Beer's Law Lab. That problem is unrelated to this issue, since the arrow buttons don't work in [1.7.0-dev.2](https://bayes.colorado.edu/dev/html/beers-law-lab/1.7.0-dev.2/phet/beers-law-lab_en_phet.html).   They were probably broken by https://github.com/phetsims/beers-law-lab/issues/126.

**Comment by pixelzoom** [comment]
Beer's Law Lab fixed in https://github.com/phetsims/beers-law-lab/issues/233, unrelated to this issue.

@mbarlow12 OK to resume review.

**Comment by mbarlow12** [comment]
Combined with commits for https://github.com/phetsims/scenery-phet/issues/451 this looks complete. Closing.
