### ISSUE TITLE
ComboBoxDisplay - new UI component

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#449]
Related to the combo box in Gas Properties and SOM that displays a dynamic value (temperature, pressure)...  Investigate creating something like `ComboDisplay` that extends `ComboBox`.

**Comment by pixelzoom** [comment]
[ComboDisplay](https://github.com/phetsims/gas-properties/blob/master/js/common/view/ComboDisplay.js) currently lives in the gas-properties repo, where it is used for the thermometer and pressure gauge.  The documentation describes it as:

>  The lovechild of a ComboBox and a NumberDisplay. Allows the user to choose one of N dynamic numeric values.

Remaining tasks:

- [ ] Move to scenery-phet
- [ ] Recommend using it in SOM

**Comment by pixelzoom** [comment]
@arouinfar @ariel-phet See https://github.com/phetsims/scenery-phet/issues/449#issuecomment-449261595 Do you have suggestions for a better name than `ComboDisplay`?

**Comment by ariel-phet** [comment]
@pixelzoom It seems something like `ComboReadOut` could also work, but it seems like the ReadOut idea already has a precedent as a Display. 

I would think potentially `ComboDisplayBox` might be clearer since it feels most related to `ComboBox` and seems to inherit much of its functionality and look from `ComboBox`

**Comment by pixelzoom** [comment]
@ariel-phet How about `ComboBoxDisplay`?

**Comment by arouinfar** [comment]
While I like the cleverness naming this so-called lovechild `ComboDisplay`, I think `ComboBoxDisplay` is a bit clearer, so I'd vote for that.

**Comment by pixelzoom** [comment]
@jbphet This will be used in SOM (see https://github.com/phetsims/states-of-matter/issues/236), so let me know if you have any suggestions for name.   The front runner is currently `ComboBoxDisplay`.

**Comment by jbphet** [comment]
`ComboBoxDisplay` is fine by me.

**Comment by pixelzoom** [comment]
I've migrated ComboBoxDisplay to scenery-phet, and created a demo.  But it looks like ComboBox's `align` option is currently broken.  So I'm going to wait to ask for a review until that's fixed.

**Comment by pixelzoom** [comment]
ComboBox's `align` option is fixed, so this is ready for review. 

@ariel-phet please assign someone to review.  Since this will be used in SOM, someone familiar with that sim might be a good choice.

**Comment by jbphet** [comment]
I reviewed `ComboBoxDisplay` and the test code in `ComponentsScreenView`, and tested the behavior in the scenery-phet demo, and it all looks great to me.  I'll go ahead an integrate it into states-of-matter, and will re-open this if I run into anything major, but for now it seems that this is ready for closing.
