### ISSUE TITLE
Reset all button should be disabled when sim is already reset

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#45]
If it's not too expensive, I think it would be nice to disable the reset all button when the sim is already reset, so it doesn't look like something else the user can "do".

**Comment by pixelzoom** [comment]
@ariel-phet This issue has been open since May 2014.   Is there really any reason to do this?

**Comment by samreid** [comment]
Some additional thoughts about the matter:

1. The sim may look odd if it started up with a grayed out reset all button.
2. How would this overlap with accessibility?
3. Would we need extra work for PhET-iO to support resetting to arbitrary states?

It seems like a lot of work to detect when the sim has changed from the default state, we should only pursue this if we think it will be a significantly improved user experience.

**Comment by ariel-phet** [comment]
This issue can definitely be closed. Hitting the reset button return the sim to its default state, if it is already in its default state, pressing it still counts as a button press it just has no obvious consequence. never a problem in interviews or any observed interactions. I think of this as perfectly equivalent to the "refresh" button on a webpage...you can hit that button many times, but it may not actually change what you see.
