### ISSUE TITLE
FineCoarseSpinner - new UI component

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#450]
Factor this component out of FAMB, for use in Gas Properties:

![screenshot_947](https://user-images.githubusercontent.com/3046552/50310449-3c34ac80-045f-11e9-93b6-cbeaeca743bc.png)

The relevant FAMB code is:

https://github.com/phetsims/forces-and-motion-basics/blob/e121da8973cf0d1f35df13d57c1c5575b0e569fe/js/motion/view/MotionScreenView.js#L182-L220

**Comment by pixelzoom** [comment]
For Gas Properties, "fine" is 1, "coarse" is 50.

**Comment by arouinfar** [comment]
@pixelzoom the control is looking/feeling really nice! I like the name FineCoarseSpinner -- it's descriptive and concise. I don't have a better suggestion for you.

**Comment by pixelzoom** [comment]
Some feedback on  Slack developer channel:

Chris Malley [9:32 AM]
I’m soliciting names for this control, currently `FineCoarseSpinner` and living in Gas Properties: ...

Sam Reid [9:36 AM]
I can’t think of a better name at the moment.  But I did notice several other *Spinner.js components in our libraries.

AccessibleNumberSpinner
FineCoarseSpinner
LeftRightNumberSpinner
LeftRightSpinner
NumberSpinner
RoundNumberSpinner
UpDownSpinner

I bet we have some opportunity to coalesce these.  For instance, the LeftRightSpinner + LeftRightNumberSpinner + FineCoarseSpinner maybe could all use the same type with different options.

Michael Barlow [9:46 AM]
Is it just 2 step sizes in either direction? DualStepSpinner?

**Comment by ariel-phet** [comment]
@pixelzoom no other great suggestions (`TwoStepSpinner` sounds a bit too much like a line dance probably)

**Comment by pixelzoom** [comment]
FineCoarseSpinner has been moved to scenery-phet, and a demo was added to SCENERY_PHET/ComponentsScreenView.

**Comment by pixelzoom** [comment]
About the various spinner variants, @samreid said:
> ... I bet we have some opportunity to coalesce these. 

Tracking in https://github.com/phetsims/sun/issues/436

**Comment by pixelzoom** [comment]
There are two remaining tasks here:

>  - [ ] Use in FAMB.
> - [ ] Add PhET-iO instrumentation (required for FAMB).

@ariel-phet My recommendation would be to create a new issue in FAMB, and handle instrumentation as part of adding this to FAMB.   And that activity would also serve as review of this issue.  Does that sound OK?  If so, who would you like that FAMB issue assigned to?

**Comment by ariel-phet** [comment]
@pixelzoom that sounds good. Please assign that issue to @jessegreenberg

**Comment by pixelzoom** [comment]
See https://github.com/phetsims/forces-and-motion-basics/issues/274. 

Closing.
