### ISSUE TITLE
color-coding of thermal energy

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#455]
In https://github.com/phetsims/scenery-phet/issues/320, @jonathanolson said that the `MoveToTrashButton` is (by default) color-code to thermal energy:

![trash-can](https://user-images.githubusercontent.com/480878/28189721-63acbece-67e4-11e7-9c84-08535a1b00e3.png)

The button is used in ESP, MAS, and Pendum Lab.  E.g. in MAS:

![screenshot_958](https://user-images.githubusercontent.com/3046552/50864961-e5850900-1360-11e9-9daa-5e9d44d97cc4.png)

If this is supposed to be color-code to thermal energy, then why is it not using `PhetColorScheme.HEAT_THERMAL_ENERGY`, which is `new Color( 255, 85, 0 )`?  It's currently using `baseColor: new Color( 230, 230, 240 )`.  

I also see no use of `PhetColorScheme.HEAT_THERMAL_ENERGY` in these sims, so this problem likely extends beyond the `MoveToTrashButton`.   Colors are probably duplicated within and across sims.  And we should examine whether `PhetColorScheme.HEAT_THERMAL_ENERGY` current value is correct.

@arouinfar?

**Comment by pixelzoom** [comment]
From `EnergySkateParkColorScheme`:

 thermalEnergy: new Color( '#FF5500' ), // red colorblind

This does in fact match `PhetColorScheme.HEAT_THERMAL_ENERGY`.  But it should be using `PhetColorScheme.HEAT_THERMAL_ENERGY`.  And the `MoveToTrashButton` is currently color-coded incorrectly.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/scenery-phet/issues/320 and https://github.com/phetsims/scenery-phet/commit/5f1402cab5220a43d81c4cf07958943f05aa402c, I've set the default arrow color of `MoveToTrashButton` to `PhetColorScheme.HEAT_THERMAL_ENERGY`.

**Comment by arouinfar** [comment]
@pixelzoom Illustrator says that `rgb(255, 85, 0)` is equivalent to `#ff5500`.

In mockups, the arrow is `rgb(255, 85, 0)` (RED_COLORBLIND/HEAT_THERMAL_ENERGY). I don't know why a different red was used in some implementations of the `MoveToTrashButton`. This was never a design request, nor can I remember ever being asked what color to use (the ESPB design predates me). 

My guess is that MAS looked to PL's usage of this button. PL was not originally ported in-house, and the dev probably just used some random red that looked about right, rather than seeing what had been done previously in ESPB.

**Comment by arouinfar** [comment]
Since it looks like @pixelzoom already made the commits to update the default color to `PhetColorScheme.HEAT_THERMAL_ENERGY`, I'll go ahead and close.

**Comment by pixelzoom** [comment]
Not ready to close.  None of these 3 sims is using `PhetColorScheme.HEAT_THERMAL_ENERGY`.  ESP has duplicated that color.  And I haven't discovered what the other 2 sims are doing.

**Comment by pixelzoom** [comment]
This problems extends to the other energy colors.

PhetColorScheme:

```
HEAT_THERMAL_ENERGY: RED_COLORBLIND,
...
KINETIC_ENERGY: Color.GREEN,
...
POTENTIAL_ENERGY: Color.BLUE,
...
TOTAL_ENERGY: TAN_ORANGE,
```

EnergySkateParkColorScheme:

```js
    kineticEnergy: new Color( '#00cc1a' ),
    potentialEnergy: new Color( '#3282D7' ),
    thermalEnergy: new Color( '#FF5500' ), // red colorblind
    totalEnergy: new Color( '#B4B400' ), // dirty yellow
```

@arouinfar is there any reason why EnergySkateParkColorScheme should not be using PhetColorScheme?

**Comment by pixelzoom** [comment]
New issue is https://github.com/phetsims/scenery-phet/issues/456. Closing this issue.
