### ISSUE TITLE
Increase pointer area for reset all button

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#458]
From #64 

@ariel-phet would you like to increase the pointer area for the reset all button?  It currently looks like this:

![image](https://user-images.githubusercontent.com/679486/35877149-c168945c-0b31-11e8-920a-5d973eb796c5.png)

May be a good idea as we are moving toward smaller screens.

**Comment by samreid** [comment]
If I recall correctly, in https://github.com/phetsims/joist/issues/542 we decided not to go back through old simulations and unify their layout bounds.  However, all new simulations will use the default layout bounds.

Therefore, it seems we can take the following next step for this issue:

(A) Choose the default visual radius and pointer area radius for ResetAllButton as prescribed in https://github.com/phetsims/scenery-phet/issues/458#issuecomment-446296242

Simulations using the default values for ResetAllButton will automatically get the new values, regardless of whether they use the default layout bounds or not.

After we do step (A), it will be up to @ariel-phet to decide whether we should iterate through all simulations and do the following sub-step:

B. For each simulation: determine whether the new defaults for ResetAllButton are acceptable--this will depend on the sim's layout bounds and the context of the ResetAllButton.  If not acceptable, the visual radius and pointer area radius can be adjusted.

I want to check in with @ariel-phet before proceeding, since this could quickly turn into a large chip-away issue.

**Comment by ariel-phet** [comment]
@samreid I would say do step (A) and then just make a checklist of sims not using the default layout bounds, and assign an issue to me with that checklist to look at the sims in master. If there is an issue in any of these checklist sims, I will make separate adjustment issues for those in the appropriate repos.

**Comment by samreid** [comment]
Using https://phet-dev.colorado.edu/html/states-of-matter-basics/1.0.7/states-of-matter-basics_en.html?showPointerAreas as a reference point, I tuned the values for the reset all button radius and touch area dilation in the Scenery PhET demo until they matched.  The closest matching values I could find are:

```
RESET_ALL_BUTTON_RADIUS = 20.8 (was originally 24)
touchAreaDilation: 5.2, (was originally 0)
```

I'll commit these to master and open a new issue to make further updates based on these defaults.   

I sent a message on Slack:

> ResetAllButton default size and default pointer area will be changing shortly in https://github.com/phetsims/scenery-phet/issues/458.  After committing, I’ll open a new “blocks publication” issue to (a) make sure the new defaults don’t disrupt simulations and (b) see if any simulations with non-default layout bounds need to be updated.

@ariel-phet anything else to do in this issue?

**Comment by ariel-phet** [comment]
There is a task to check over these changes, but the size and dilation look correct. Closing.
