### ISSUE TITLE
Touch area overlap of FineCoarseSpinner buttons

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#459]
From #450 and https://github.com/phetsims/forces-and-motion-basics/issues/274. With default options, there is a slight overlap in the touch areas of adjacent ArrowButtons of the FineCoarseSpinner. 
![image](https://user-images.githubusercontent.com/6396244/51572127-70dac000-1e72-11e9-9441-894fc810e273.png)

Overlap becomes greater if spacing is reduced. In forces-and-motion-basics, there was a special shape to get around this.
```js
    // define custom touch areas so the arrow buttons don't overlap
    var doubleLeftShape = new Shape.rect( 0, -ARROW_TOUCH_DILATION, doubleLeftArrowButton.width + ARROW_TOUCH_DILATION, doubleLeftArrowButton.height + 2 * ARROW_TOUCH_DILATION );
    doubleLeftArrowButton.touchArea = doubleLeftShape;
```

Should something similar be added to FineCoarseSpinner?

**Comment by pixelzoom** [comment]
This is due to the non-general default dilation in ArrowButton:

```js
      touchAreaXDilation: 7,
      touchAreaYDilation: 7,
```

**Comment by pixelzoom** [comment]
Done. The defaults pointer areas for the ArrowButtons are:

```js
        // pointer areas
        touchAreaXDilation: 3,
        touchAreaYDilation: 3,
        mouseAreaXDilation: 0,
        mouseAreaYDilation: 0
```

Here's how it looks in the Components screen of scenery-phet demo with `?showPointerAreas`:

<img width="347" alt="screenshot_1004" src="https://user-images.githubusercontent.com/3046552/51574951-42a6b180-1e6d-11e9-910f-307006ffd32c.png">

@jessegreenberg ready for review.

**Comment by jessegreenberg** [comment]
Overlap is gone, thanks.
