### ISSUE TITLE
Add enable/disable to FineCoarseSpinner

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#461]
In https://github.com/phetsims/forces-and-motion-basics/issues/274 I replaced the custom ArrowButtons and value readout with new UI component FineCoarseSpinner. But in forces-and-motion-basics, the component needs to be full disabled in some circumstances. When disabled, all ArrowButtons should look disabled, and the NumberDisplay text should have a different fill (probably a greyish color by default).

@pixelzoom would you like me to do this as part of https://github.com/phetsims/forces-and-motion-basics/issues/274 or would you like to do this from https://github.com/phetsims/scenery-phet/issues/450?

**Comment by pixelzoom** [comment]
Ready for review.

**Comment by pixelzoom** [comment]
See also the "enabled" checkbox that I added to the demo of FineCoarseSpinner in scenery-phet.

**Comment by jessegreenberg** [comment]
Thanks @pixelzoom, this looks great and is working well in FAMB. Closing,

**Comment by pixelzoom** [comment]
Reopening.  I just noticed that disposeFineCoarseSpinner is unlinking without checking `hasListener`.  If `valueProperty` or `enabledProperty` is disposed by the client before FineCoarseSpinner is disposed, this will fail:

```js
      this.disposeFineCoarseSpinner = () => {
        valueProperty.unlink( valuePropertyListener );
        if ( ownsEnabledProperty ) {
          this.enabledProperty.dispose();
        }
        else {
          this.enabledProperty.unlink( enabledObserver );
        }
...
```

**Comment by pixelzoom** [comment]
Fixed in the above commit. @jessegreenberg feel free to take a peek.  But I'm going to (re)close since this change was so trivial.
