### ISSUE TITLE
Improve HelpContent pattern for creating labels with icons

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#462]
From, a list of work included:
- [x] look at uses of maxWidth. I handled this mostly, but we should make sure that there aren't other spots to make this nicer. Also note I added the assertion back in in HelpContent to help catch usages.
- [x] look at usages of HelpContent.DEFAULT_{{SOMETHING}}
- [x] doc HelpContentRow
- [x] MAL goes a bit outside, may want to be tweaked

The remaining item is 
>look at usages of HelpContent.DEFAULT_{{SOMETHING}}

The pattern at the moment requires client to create a TExt or RichText, and then use HelpContent.DEFAULT_LABEL_FONT, HelpContent.DEFAULT_MAX_WIDTH, and others. This was originally done because the first implementation of HelpContent allowed labels to be any Node, not just Text or RichText. But we have since restricted the labels to be Text, so functions like `labelWithIcon` and `labelWithIconList` can create the text internally. This should remove almost all usages of HelpContent.DEFAULT_{{SOMETHING}}.

**Comment by jessegreenberg** [comment]
Done for HelpContent.labelWithIcon. HelpContent.labelWithIconList is next.

**Comment by jessegreenberg** [comment]
After the above commits, the only usage of HelpContent.DEFAULT_* is HelpContent.DEFAULT_ICON_SPACING in SliderControlsHelpContent.

**Comment by jessegreenberg** [comment]
I think that usage is totally OK, the problem was the explosion of usages of HelpContent.DEFAULT_LABEL_FONT since we had to create the Text for the label every time we needed a row of HelpContent.

So now the label fonts can be private and removed from HelpContent statics. And they can be renamed from DEFAULT_LABEL_FONT to just LABEL_FONT since they cannot be overridden with options.

**Comment by jessegreenberg** [comment]
OK @zepumph I went ahead with this. Would you mind reviewing? Mostly just the changes to HelpContent.labelWithIcon and HelpContent.labelWithIconList. Do you think there is anything left to do for this issue?

**Comment by zepumph** [comment]
Oh my goodness sorry for the delay. I didn't see anything that I didn't love here! Especially with the work done since creating `KeyboardHelpSection`. Back to you friend.

**Comment by pixelzoom** [comment]
There's a lot of work that's been done here, but looks like it stalled out close to finish line -- no progress in 20 months.  Raising priority to high, labeling as blocking.

**Comment by jessegreenberg** [comment]
I reviewed comments and commits, nothing else to do here and review was complete. Closing.
