### ISSUE TITLE
ThermometerNode should have ability to access linear function inverse

### ISSUE THREAD

**Issue by arnabp** [phetsims/scenery-phet#463]
A temperatureToHeight function was added previously to allow public access to the linear function, but the inverse was never added. A heightToTemperature function should be made to allow to allow for temperature thumb mapping. 

Feature needed for https://github.com/phetsims/sun/issues/473 and phetsims/blackbody-spectrum#61

**Comment by arnabp** [comment]
Assigning @jbphet for code review

**Comment by jbphet** [comment]
@arnabp and I reviewed this together and made some changes to the function names.  I think our work here is done, closing.
