### ISSUE TITLE
focusHighlight for ResetAllButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#465]
In ResetAllButton:

```js
57    this.focusHighlight = new Shape().circle( 0, 0, options.radius + 5 );
```

Why is this in ResetAllButton? 

Shouldn't this be the default for all subclasses of RoundPushButton, with an option for how much to dilate the radius?

**Comment by jessegreenberg** [comment]
Absolutely, and we can go one further and put it in RoundButtonView.

**Comment by jessegreenberg** [comment]
Oh, that line of code already exists in RoundButtonView and is duplicated. So we can remove from ResetAllButton and add the option.

**Comment by jessegreenberg** [comment]
Done in the above commits, @pixelzoom would you please take a look and close if all is well?

**Comment by pixelzoom** [comment]
👍 Closing.
