### ISSUE TITLE
transparency for HeaterCoolerNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#467]
Gas Properties is the first sim where I've used `HeaterCoolerNode`.  Something that I noticed immediately is that the "cooler" image (ice cubes) is transparent, while the "heater" image (flames) is opaque.  For example:

<img width="135" alt="screenshot_1077" src="https://user-images.githubusercontent.com/3046552/53272781-77e23180-36af-11e9-9676-b2af21ece4bd.png"> <img width="132" alt="screenshot_1076" src="https://user-images.githubusercontent.com/3046552/53272793-7add2200-36af-11e9-9d85-fe49070341b3.png">

The transparency is a nice touch, and I think it would look good with the flames. 

@arouinfar @jbphet what do you think?

**Comment by jbphet** [comment]
Sure, transparent flames sounds good, or at least worth a try.  Please make sure it looks decent in the sims that use it before committing.

**Comment by pixelzoom** [comment]
@jbphet said:
> Please make sure it looks decent in the sims that use it before committing.

`HeaterCoolerNode` is used in gas-properties and states-of-matter.
`HeaterCoolerBack` is used in energy-forms-and-changes.

The opacity of the ice cubes is 80% (ice-cube-stack.ai).  So a good starting place for the flames (flame.ai) would be 80%.    That would look like this in gas-properties:

<img width="129" alt="screenshot_1080" src="https://user-images.githubusercontent.com/3046552/53362825-43ad8180-38f8-11e9-80c8-7c8671e2fa07.png"> <img width="110" alt="screenshot_1081" src="https://user-images.githubusercontent.com/3046552/53362830-47410880-38f8-11e9-8089-f0106cf19e78.png">

Another way to address this would be to make both images opaque, and add options to HeaterCoolerNode to specify their opacity.  For example:

```js
flameOpacity: 0.8,
iceCubesOpacity: 0.8,
```


@arouinfar your opinion?

**Comment by arouinfar** [comment]
@pixelzoom at first, this seems like a natural adjustment to make, but it's actually a bit tricky.

Looking at ice-cube-stack.ai, the individual ice cubes have 80% opacity to create the illusion of a stack of ice cubes. There's quite a bit of overlap between ice cubes, so the apparent opacity of the ice-cube-stack is greater than 80%. To me, the fire looks too transparent in https://github.com/phetsims/scenery-phet/issues/467#issuecomment-467146912, compared to the ice cubes.

If I make the ice-cube-stack completely opaque, it loses some its likeness to an actual ice stack, looking more like a bunch of random quadrilaterals. Reducing the opacity of the exported ice-cube-stack.png will not recover the detail that was originally in ice-cube-stack.ai, either.
![image](https://user-images.githubusercontent.com/8419308/53370042-3ef5c700-3912-11e9-8fa1-c818ee7ab159.png)

Personally, I would just leave the the opacity alone.

**Comment by pixelzoom** [comment]
Looks odd to me, but OK, leaving alone.
