### ISSUE TITLE
TimerNode: bad propagation of options

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#468]
In TimerNode.js:

```js
function TimerNode( timeProperty, runningProperty, options ) {

    options = _.extend( {
       // See also options that pass through to TimerReadoutNode
...
    }, options );
...
    var timerReadoutNode = new TimerReadoutNode( timeProperty, options );
69  timerReadoutNode.centerX = 0;
```

Line 69 is needed because all options (including transforms) are being propagated to `TimerReadoutNode`.   While this hack may work for translation, it doesn't address other transforms.   Introduced in https://github.com/phetsims/scenery-phet/commit/25570409f9856df5a23586cecd11b2d3bcaacfb by @samreid.

`TimerReadoutNode` options should be either cherry-picked or nested (preferred). 

Assigned to @ariel-phet to prioritize and assign.

**Comment by pixelzoom** [comment]
Affected sims:

- [ ] capacitor-lab-basics (passing `scale: 0.6`)
- [ ] masses-and-springs (calling `scale( 0.5 )` after instantiation)
- [ ] wave-on-a-string
- [ ] gas-properties (passing `unitsNode`) 
- [ ] wave-interference (passing `unitsNode`)

**Comment by ariel-phet** [comment]
@Denz1994 can you handle this as I believe you are pretty familiar with TimerNode these days?

**Comment by Denz1994** [comment]
`TimerNode.js` now uses nested options for `TimerReadoutNode.js`. The signiture for these options are as follows:

```
constructorOptions = _.extend({
    // otherOptions: ...

    // options passed through to TimerReadoutNode
    timerReadoutNodeOptions:null // To be filled below

    // moreOptions: ...
})
```

```
// Near TimerReadoutNode declaration
options.timerReadoutNodeOptions = _.extend( {
      unitsNode: null,
      largeFont: DEFAULT_LARGE_FONT,
      smallFont: DEFAULT_SMALL_FONT,
      maxValue: options.maxValue,
    }, options.timerReadoutNodeOptions );
```
Defaults for these fields are defined in `TimerNode.js`. The default values for `largeFont` and `smallFont` have been added as statics to maintain compatibility with callsites (see `Gas_Properties/js/common/view/StopWatch.js` constructor `options`).

The refactor to call sites mainly involved refactoring to target `options.timerReadoutNodeOptions` before adjusting any fields such as `maxValue`.

This was tested in by adjusting options in sim code. For example, in WOASView was refactored to 
```
    var timer = new TimerNode( model.timerSecondProperty, model.timerStartProperty, {
      timerReadoutNodeOptions: { unitsNode: new Text( 'TEST_TEST' ) }
    } );
```
To produce : 
![image](https://user-images.githubusercontent.com/13894380/53435443-d3216600-39c6-11e9-9a59-d35507e52fd2.png)

Lastly, line 69 from the [original comment](https://github.com/phetsims/scenery-phet/issues/468#issue-414305599) has been removed.

@pixelzoom I didn't refactor any sim code related to CLB or MAS because `scale` should be handled by the refactored pattern for nested options. Could you please review these changes?

**Comment by Denz1994** [comment]
Fixing conflict during push.

**Comment by Denz1994** [comment]
Ready for feedback @pixelzoom.

**Comment by pixelzoom** [comment]
Moving in the right direction, but there are some issues:

(1) I didn't notice that TimerReadoutNode doesn't have an `options` parameter, it has `config`.  Why it has `config` is a question for @samreid. It doesn't make much sense to me, and it's not at all robust because there's no verification for most of the `config` fields.  I recommend to convert to `options`, and move defaults from  TimerNode to TimerReadoutNode.

(2) In general, all options should be represented (and documented) in the default options hash.  So in TimerNode, the default hash for options needs the following (which looks like you had in an earlier commit):

```
// options propagated to TimerReadoutNode
timerReadoutNodeOptions: null,
```

(3) You moved `TimerReadoutNode.DEFAULT_SMALL_FONT` to TimerNode, but didn't adjust the usage in GAS_PROPERTIES/StopwatchNode.  This isn't causing a CT failure, but the fonts in Gas Properties are visually messed up.  I don't see any uses of `DEFAULT_LARGE_FONT`. When changing the public API (including static constants), look for use sites.  

(4) TimerNode and TimerReadoutNode both use `options.maxValue`.   With the current implementation, this is perfectly legal and wrong:

```js
new TimerNode( ..., {
  maxValue: 500,
  timerReadoutNodeOptions: {
    maxValue: 200
  }
} );
```

So you before doing `options.timerReadoutNodeOptions = _.extend`, you have to verify that `options.timerReadoutNodeOptions` doesn't include `maxValue`:

```js
assert && assert( !options.timerReadoutNodeOptions || options.timerReadoutNodeOptions.maxValue === undefined, 
  'TimerNode sets maxValue' );
```

**Comment by pixelzoom** [comment]
Reviewing again because it looks like I pulled in the middle of a merge conflict.

Looks like (3) above was properly addressed, so ignore that one.  The others are still relevant.

**Comment by Denz1994** [comment]
(1) From [software-design-patterns](https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md) doc: 

> If there are some properties of the object parameter that are required, then the parameter should be called config. Some elements of the config parameter can be optional, but each one must be documented accordingly

`config.maxValue` is a required parameter in `timerReadoutNodeOptions`, so a config pattern seems appropriate here. Because `config.maxValue` is the only required parameter, it is the only parameter that needs verification. Verification is currently limited to:

```js
assert && assert( config.maxValue >= 0, 'TimerReadoutNode.maxValue should be non-negative' );
assert && assert( config.maxValue < 1E21, 'TimerReadoutNode.maxValue should be less than 1E21' );
```

Assuming my line of reasoning is correct above, should the asserts be changed to: 
```js
assert && assert( config.maxValue >= 1/100, 'TimerReadoutNode.maxValue should display values greater than 1/100 second' );
assert && assert( config.maxValue <= 3599.99, 'TimerReadoutNode.maxValue should be less than 59 minutes and 59.99 seconds' );
```

(2) `Timernode.options` now includes a default declaration of `timerReadoutNodeOptions`:
```js
// options propagated to TimerReadoutNode
timerReadoutNodeOptions: null,
```

(4) This check has been added as well. It now ensures that this example code below, altered from WOASView, is erroneous:
```js
 // Erroneous code
    var timer = new TimerNode( model.timerSecondProperty, model.timerStartProperty, {
      maxValue:3,
      timerReadoutNodeOptions: {
        unitsNode: new Text( 'test' ),
        maxValue:3
      }
    } );
```

Thoughts @pixelzoom.

**Comment by Denz1994** [comment]
From my above [comment](https://github.com/phetsims/scenery-phet/issues/468#issuecomment-469765776):
> config.maxValue is a required parameter in timerReadoutNodeOptions, so a config pattern seems appropriate here.

Is this accurate @samreid? Or should we refactor this into using an options pattern?

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/scenery-phet/issues/468#issuecomment-469765776:

> Some elements of the config parameter can be optional, but each one must be documented accordingly

There is currently no such documentation, and that's another problem.

>  Because `config.maxValue` is the only required parameter, it is the only parameter that needs verification.

`config.largeFont` and `config.smallFont` are also required, see lines 35 & 34. (Try using `undefined` for Text font.)   So the only value that is optional is `maxValue`. 

> should the asserts be changed to:
> `assert && assert( config.maxValue >= 1/100, 'TimerReadoutNode.maxValue should display values greater than 1/100 second' );`
> `assert && assert( config.maxValue <= 3599.99, 'TimerReadoutNode.maxValue should be less than 59 minutes and 59.99 seconds' );`

No, these are not the correct constraints for `maxValue`.  `config.maxValue > 0` might make more sense for the first assert.  But in general any maxValue > 0 is valid for `maxValue`, it will simply display in minutes and seconds.   E.g. `maxValue: 720` will display as "120:00" (120 minutes, 0 seconds), and there's nothing wrong with that.

@Denz1994 I still recommend converting TimerReadoutNode to options, and I'd be happy to work with you on it.

**Comment by pixelzoom** [comment]
Discussed with @Denz1994 on Slack, and decided to commit/push what I had in mind. See above commits.   @Denz1994 @samreid let me know if you have any questions/concerns.

**Comment by samreid** [comment]
I made a few minor changes in the preceding commits which may be good for @pixelzoom to be aware of. 

Also, I saw this check in TimerNode:

```js
    // fill in timerReadoutNodeOptions defaults
    assert && assert( !options.timerReadoutNodeOptions || options.timerReadoutNodeOptions.maxValue === undefined,
      'TimerNode sets maxValue' );
```

It's not a big difference, but it feels to me that `!x.hasOwnProperty('y')` is slightly clearer than `x.y === undefined`.  Let me know if you disagree.  No other issues or work noted.

**Comment by pixelzoom** [comment]
I don't have a preference on I've `x.hasOwnProperty('y')` vs `x.y === undefined`.  Either it better than `!x.y`, which is what we most commonly seem to be using.

**Comment by samreid** [comment]
Sounds good, closing.
