### ISSUE TITLE
NumberPicker: add enabledProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#470]
In https://github.com/phetsims/graphing-quadratics/issues/112 and https://docs.google.com/document/d/1OfHhIDuaBt-hhXVtpnJgM3Wm0iByJ7dmXd-2UkphUR4/edit#heading=h.8ee6hb1jovtf, we need the ability to enable/disable NumberPicker, via `enabledProperty`.

The fastest way to do this would be to add it to NumberPicker directly, using the same boilerplate that has been used for other UI components.  The more longterm solution is to create an "enabled" trait or mixin, as proposed in https://github.com/phetsims/sun/issues/257#issuecomment-458313096.

Assigning to @ariel-phet to prioritize and assign.

**Comment by pixelzoom** [comment]
@ariel-phet since this is a new feature, and "enabled" pattern is well understood, I'm going to self-assign and proceed.  I'm going to add boilerplate, which can be factored out later as part of phetsims/sun#257.

**Comment by pixelzoom** [comment]
Implemented and testing in various sims.  Also confirmed `enabledProperty` can be controlled in Studio, in the context of Graphing Quadratics.  I have not determined how to "feature" `enabledProperty` (or other internal Properties), but that seems like a more general issue that can be investigated separately.

@ariel-phet please assign someone to review.

**Comment by samreid** [comment]
I skimmed the change sets and tested in Graphing Quadratics studio.  All seems well.  My only question is about the latter commit: https://github.com/phetsims/scenery-phet/commit/1c0a1a764e1b29c8620604310203690c62badd21

In what circumstance would the `else if` predicate be false?  `self.enabledProperty.hasListener( enabledListener )`.  Should we add a code to clarify that case?

**Comment by pixelzoom** [comment]
> In what circumstance would the else if predicate be false? self.enabledProperty.hasListener( enabledListener ). Should we add a code to clarify that case?

@sam is asking about this 

```js
if ( ownsEnabledProperty ) {
  self.enabledProperty.dispose();
}
else if ( self.enabledProperty.hasListener( enabledListener ) ) {
  self.enabledProperty.unlink( enabledListener );
}
```

The `else if` occurs when the client has provided `options.enabledProperty`.  If the client disposed `enabledListener` before the `NumberPicker` instance, then `enabledListener` will no longer be a listener of `enabledListener`, and the `unlink` would fail (see Emitter `removeListener`, line 174).  

This shouldn't need documentation here.  This needs to be done for _any_ Property provided by the client, and is a frequent error in implementing `dispose{{Classname}}`.

**Comment by pixelzoom** [comment]
To clarify the previous comment...  If you `link( someListener )` to a `{Property} someProperty` that you don't own, you should always check `someProperty.hasListener( someListener )` before doing `someProperty.unlink( someListener )`.  You don't know if the owner has called `someProperty.dispose()` before you called  `someProperty.unlink( someListener )`, and you shouldn't be relying on ordering of these operations.

**Comment by pixelzoom** [comment]
Update: In https://github.com/phetsims/scenery-phet/issues/476#issuecomment-469825394, @zepumph pointed out that Emitter.removeListener now skips the assertion if the Emitter (Property) has been disposed.   So it's safe to omit the `hasListener` check.

**Comment by pixelzoom** [comment]
Update: In https://github.com/phetsims/scenery-phet/issues/476#issuecomment-469825394, @zepumph pointed out that Emitter.removeListener now skips the assertion if the Emitter (Property) has been disposed.   So it's safe to omit the `hasListener` check.

That said, I don't feel the need to remove it in `disposeNumberPicker`.

**Comment by pixelzoom** [comment]
While doing some work elsewhere, I noticed that AccessibleNumberSpinner `initializeAccessibleNumberSpinner` takes `enabledProperty` as it's 3rd argument.   Since NumberPicker did not previously have `enabledProperty`, `initializeAccessibleNumberSpinner` was being called with a dummy BooleanProperty for its 3rd arg, i.e.:

```js
    this.initializeAccessibleNumberSpinner( valueProperty, rangeProperty, new BooleanProperty( true ), _.extend( {
      a11yValueDelta: options.upFunction( valueProperty.get() ) - valueProperty.get()
    }, options ) );
```

So yikes, I almost missed this.  In the above commit, I've replaced the dummy Property with new `this.enabledProperty`:

```js
    this.initializeAccessibleNumberSpinner( valueProperty, rangeProperty, this.enabledProperty, _.extend( {
      a11yValueDelta: options.upFunction( valueProperty.get() ) - valueProperty.get()
    }, options ) );
```

@jessegreenberg Do I have this correct?

**Comment by jessegreenberg** [comment]
That is correct @pixelzoom, thanks.

**Comment by pixelzoom** [comment]
This didn't get assigned back to me in March 2019, so it fell through the crack. I don't see anything else to do here.  So closing.
