### ISSUE TITLE
NumberPicker fields should be local variables

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#472]
Noticed while working on #471.  These 2 Properties are not used outside of the constructor, and do not need to be instance fields. They should be local variables.

```js
    // @private must be detached in dispose
    this.upEnabledProperty = new DerivedProperty( [ valueProperty, rangeProperty ], options.upEnabledFunction );

    // @private must be detached in dispose
    this.downEnabledProperty = new DerivedProperty( [ valueProperty, rangeProperty ], options.downEnabledFunction );
```

**Comment by pixelzoom** [comment]
There are quite a few fields that should be local variables. I'm guessing that this is vestigial, from the days before ` this.disposeNumberPicker` was added and more things needed to be accessible in `dispose`.   

Here's the list of `@private` fields that should be local variables.

this.colorProperty
this.valueProperty
this.valueObserver
this.upEnabledProperty
this.downEnabledProperty

**Comment by pixelzoom** [comment]
Fields converted to local variables in the above commit.  Since these fields were all `@private`, I did not exhaustively test sims that use NumberPicker.  I tested a cross-section.   If a sim is using one of these `@private` fields, it will break in CT and should be fixed.

**Comment by pixelzoom** [comment]
@ariel-phet please assigning someone to review.

**Comment by chrisklus** [comment]
Changes looks good, I had no issues testing a couple sims with NumberPicker, and CT is showing no relevant failures. Back to @pixelzoom.
