### ISSUE TITLE
bug in BarrierRectangle disposeBarrierRectangle

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#476]
There's no listener passed to `unlink`, this will fail hard.

``` 
   // @private
    this.disposeBarrierRectangle = function() {
      modalNodeStack.lengthProperty.unlink();
    };
```

There should also be a `hasListener` test before doing the `unlink`, in case `modalNodeStack.lengthProperty` has already been disposed.

I can't tell when this was introduced, because BarrierRectangle was moved from joist to scenery-phet.  Assigning to the `@author` @zepumph.

**Comment by zepumph** [comment]
>There should also be a hasListener test before doing the unlink, in case modalNodeStack.lengthProperty has already been disposed.

In Emitter.removeListener (which is called from Property.unlink):

```

      // Throw an error when removing a non-listener (except when the Emitter has already been disposed, see
      // https://github.com/phetsims/sun/issues/394#issuecomment-419998231
      if ( assert && !this.isDisposed ) {
        assert && assert( index >= 0, 'tried to removeListener on something that wasn\'t a listener' );
      }
```

I don't think that the `hasListener` check is required @pixelzoom. At one point I added many of those checks around unlink calls and it didn't pass code review (and I removed them).

**Comment by zepumph** [comment]
@pixelzoom please review.

**Comment by pixelzoom** [comment]
Ah, I see....  The assertion in Emitter.removeListener is short-circuited if the Emitter has been disposed.   Sounds good, I'll note in some other issues were this has come up in the past 2 days.
