### ISSUE TITLE
NumberControl is doubly disabling its Slider

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#481]
In Gas Properties "Energy" screen, we have a NumberControl that can be disabled.  

Here's what it looks like enabled:

<img width="205" alt="screenshot_1118" src="https://user-images.githubusercontent.com/3046552/55351512-c7203c80-547b-11e9-9897-e50f21440597.png">

and disabled:

<img width="209" alt="screenshot_1117" src="https://user-images.githubusercontent.com/3046552/55351513-ca1b2d00-547b-11e9-9a19-adf1295ef097.png">

Note that when it's disabled, the slider is much dimmer (lower opacity value) than the rest of the component.  I suspect that this is because both the NumberControl and its Slider are reacting to the NumberControl's `enabledProperty`, and the Slider ends up having its opacity reduced twice; once by itself, once by its parent NumberControl.   The Slider should not be involved at all here.

Self assigning to investigate.

**Comment by pixelzoom** [comment]
It looks like this problem was introduced in https://github.com/phetsims/scenery-phet/commit/f5250b350b925aa3f4bd1445965bdff6e2cc87f8 for #451 (nested options).  `options.enabledProperty` should not be propagated to the Slider via `options.sliderOptions`.  Fixed in the above commit.  @mbarlow12 please review.

**Comment by pixelzoom** [comment]
After the fix, here's how the Gas Properties control looks when disabled:

<img width="207" alt="screenshot_1119" src="https://user-images.githubusercontent.com/3046552/55352265-afe24e80-547d-11e9-9a72-37aab51a2000.png">

**Comment by zepumph** [comment]
Yes that looks very nice to me. Since NumberControl is the parent node, setting it to be pickable false will apply to all children (or so I notice when manually toggling this Property in a sim). Thanks for implementing the bug when you saw it! Anything else here?

**Comment by pixelzoom** [comment]
Nope, I think we're done. Closing.
