### ISSUE TITLE
Remove utteranceQueue.setStepInterval

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#486]
After #485 I don't see much of a benefit for keeping utteranceQueue.setStepInterval. As it is, utteranceQueue.setStepInterval is not used at all in sims and even has this documentation already:

> Beware that this impacts the entire queue. Controlling timing of utterances is probably better managed by using options for an individual Utterance.

There are complications when considering the utteranceQueue interval and Utterance.alertStableDelay (to be added in #485). So I am going to remove it.

@zepumph please let me know if you have concerns.

**Comment by jessegreenberg** [comment]
Removed, assigning to @zepumph to make sure there are no concerns.

**Comment by zepumph** [comment]
This is great. We should decide on a time and that should be constant for all sims/runtimes. Back to you to close or what have you

**Comment by jessegreenberg** [comment]
Thanks for reviewing, timing for utteranceQueue was updated heavily in #491 so this can be closed.
