### ISSUE TITLE
HandleNode support for ColorDef

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#487]
I ran into this in Gas Properties, where is was impossible to use a ColorProfile with HandleNode because it doesn't fully support `{ColorDef}`, specifically `{Property.<null|string|Color>}`.   I don't need this immediately in Gas Properties, because there is currently no requirement to change the handle color for projector mode.  But it would nice to be able to experiment with the color in gas-properties-colors.html, and this prevents that.

`HandleNode` has 4 color options:

```js
        gripBaseColor: DEFAULT_GRIP_BASE_COLOR, // {Color|string} base color of gradient on the grip
        gripStroke: 'black', // {Color|string} stroke color of the grip
        attachmentFill: 'gray', // {Color|string} solid fill color for the attachments
        attachmentStroke: 'black', // {Color|string} stroke color of the attachments
```

- [x] These last 3 options should be documented as `{ColorDef}`.

- [x] The implementation should be changed so that they first of these options, `gripBaseColor`, can also be a `{ColorDef}`.  That's currently impossible because of this bit of code:

```js
      const gradientBaseColor = Color.toColor( options.gripBaseColor );
      const gripPath = new Path( gripShape, {
        lineWidth: options.gripLineWidth,
        stroke: options.gripStroke,
        fill: new LinearGradient( 0, 0, 0, GRIP_HEIGHT )
          .addColorStop( 0, gradientBaseColor )
          .addColorStop( 0.4, gradientBaseColor.brighterColor( 0.5 ) )
          .addColorStop( 0.7, gradientBaseColor )
          .addColorStop( 1.0, gradientBaseColor.darkerColor( 0.6 ) )
      } );
```

In https://github.com/phetsims/scenery/issues/962#issuecomment-480034075, we said:

> `PaintColorProperty` is useful for doing this. See for example `RectangularButtonView`.

**Comment by pixelzoom** [comment]
HandleNode now has option `{ColorDef} gripBaseColor`.   PaintColorProperty and the example in RectangularButtonView were very useful.  But it was tricky coming up with luminance values that preserved the same look of the handle gradient.  The original implementation was using Color `darkerColor` and `brighterColor`, while PaintColorProperty uses Color `colorUtilsBrighter` and `colorUtilsDarker`.  They are very different algorithms, so I had to fiddle with the values until things looked "close enough". 

I used ColorProfile with HandleNode in Gas Properties, see the last commit above.

@chrisklus would you mind reviewing this?  Since you'll need to do something similar in BicyclePumpNode, I thought this might be of interest to you.

**Comment by chrisklus** [comment]
Looks good, @pixelzoom. Your changes make sense to me, and I tested the implementation with gas-properties-colors.html. I'll use the same pattern in BicyclePumpNode.

>They are very different algorithms, so I had to fiddle with the values until things looked "close enough".

This seems problematic, do you know why this is? I see 19 usages of `brighterColor` or `darkerColor` in BicyclePumpNode, which will be a lot of fiddling. Though, I suppose I was planning on fine tuning the current usages anyway so that they exactly match the old hard-coded gradients (they are pretty close right now).

**Comment by pixelzoom** [comment]
@zepumph asked:
> This seems problematic, do you know why this is? ...

`brighterColor` and `darkerColor` (as indicated in their doc) implement the algorithm used by Java. There are provided so you don't have to fiddle with colors when porting sims from Java.  You'll have to ask @jonathanolson about the origin of `colorUtilsBrighter` and `colorUtilsDarker`, and why they are preferable for HTML5.

**Comment by chrisklus** [comment]
>`brighterColor` and `darkerColor` (as indicated in their doc) implement the algorithm used by Java. There are provided so you don't have to fiddle with colors when porting sims from Java.

Gotcha, thanks.

Well, there are over 100 usages of `colorUtilsBrighter` and `colorUtilsDarker`, so I don't think that algorithm is changing anytime soon...

Ready to close.
