### ISSUE TITLE
NumberControl pointer area dilation needs work 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#489]
We need to fix how pointer area dilation is handled in NumberControl.  From  https://github.com/phetsims/beers-law-lab/issues/236#issuecomment-482417491:

@arouinfar wrote:
> For Concentration, I'd keep the same inner boundary, but dilate in the other 3 directions.

@arouinfar is asking for this:

<img width="573" alt="screenshot_1131" src="https://user-images.githubusercontent.com/3046552/56009285-8787fa80-5c9c-11e9-9f23-15c134abd002.png">

Concentration is a NumberControl, and this is currently not supported.  In fact, this seems to be a general problem with NumberControl.  Pointer areas for the arrow buttons can only be dilated via `arrowButtonOptions`, and the dilation is the same amount around the button. That results in overlap with the slider thumb, e.g. in the screenshot below.   What we want is dilation similar to the arrow buttons for WavelengthSlider.  I'll create a scenery-phet issue to address this.

![screenshot_1130](https://user-images.githubusercontent.com/3046552/56009139-fb75d300-5c9b-11e9-9e45-71f475f1648e.jpg)

**Comment by pixelzoom** [comment]
@ariel-phet OK if I work on this?  It's going to take a couple of hours.

**Comment by pixelzoom** [comment]
There are 12 occurrences of `arrowButtonOptions:`.  Only one, in `projectile-motion.ProjectileMotionScreenView` uses pointer area options.  So this change should be relatively easy to address in call sites.

**Comment by pixelzoom** [comment]
Change to NumberControl in the above commits:

(1) Remove options related to pointer area dilation from `arrowButtonOptions`, handle asymmetrical dilation in NumberControl.

(2) Adjust default for `sliderOptions.thumbTouchAreaXDilation` so that thumb and arrow button pointer areas don't overlap.

Projectile Motion required no changes; the values used still look fine.

Beer's Law Lab is now using this, see https://github.com/phetsims/beers-law-lab/issues/236.

@ariel-phet please assign someone to review.

**Comment by KatieWoe** [comment]
Checked in master and saw that pH Scale basics seems to have gained this problem.  The published version and master both have this odd instance of a red pointer area that can be dragged on screen and manipulated as well.
![Image from iOS](https://user-images.githubusercontent.com/41024075/56069203-34b34f00-5d3f-11e9-8fe4-35efdd4b9aa7.png)

**Comment by KatieWoe** [comment]
Sorry ignore that.  I was in the wrong issue.

**Comment by ariel-phet** [comment]
@chrisklus seems like this should be quick, mind doing the review?

**Comment by chrisklus** [comment]
@pixelzoom Your changes look good and the pointer areas for NumberControl appear as desired in several sims that I checked out.

It might be nice to have a comment for `touchAreaXDilation` on line 105...

```js
touchAreaXDilation: 3.5,
touchAreaYDilation: 7,
```

...that explains this will be shifted so that one side will be 0 and the other side will be doubled (and therefore this actually matches the default value for `touchAreaYDilation`), but I see there are already two areas in the code that reference this "asymmetricalness", so perhaps it's unnecessary.

Ready to close when you are.

**Comment by pixelzoom** [comment]
@chrisklus good idea on the options doc, done in the above commit.  Closing.

**Comment by pixelzoom** [comment]
Note that in https://github.com/phetsims/my-solar-system/issues/324, it was discovered that shifting of the pointer areas was broken sometime between 4/2019 and 1/2024.   It was fixed in https://github.com/phetsims/scenery-phet/commit/c8bcaf718f6425069da359e3438ef484a5dbcf9f.
