### ISSUE TITLE
NumberControl with arrowButtonOptions or sliderOptions crashes on IE11

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#493]
Discovered in https://github.com/phetsims/circuit-construction-kit-common/issues/485, `Array.includes` is undefined on IE11, so any NumberControl with arrowButtonOptions or sliderOptions crashes on IE11.   This problem looks like it was introduced in f5250b350b925aa3f4bd1445965bdff6e2cc87f8 around Feb 2, 2019.

**Comment by samreid** [comment]
I pushed a proposed fix, @mbarlow12 can you please review?

**Comment by pixelzoom** [comment]
This is the tip of the iceberg.  There are many other places in PhET code where `Array.includes` is used, including core classes like Screen, Enumeration, ComboBox,...  How has this not been caught in testing?

**Comment by samreid** [comment]
For example, Screen.js usage of `Array.includes` is only in an assertion.

**Comment by pixelzoom** [comment]
Moving the general issue of replacing `Array.includes` with `_.includes` to https://github.com/phetsims/tasks/issues/998.

**Comment by pixelzoom** [comment]
> For example, Screen.js usage of Array.includes is only in an assertion.

Then that tells me that we're not testing with assertions on IE.  Why?!?
