### ISSUE TITLE
multiple problems with HeaterCoolerNode options

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#495]
There are multiple problems with HeaterCoolerNode options, discovered in Gas Properties.

- [x] This assertion expression is buggy:

```js
assert && assert( !options.backOptions, 'HeaterCoolerNode sets baseColor for HeaterCoolerBack' );
```

- [x] This assertion expression is buggy:

```
assert && assert( !options.frontOptions, 'HeaterCoolerNode sets baseColor for HeaterCoolerFront' );
```

- [x] This `_.extend` call is modifying `backOptions`, which violates best practices.

```js
const heaterCoolerBack = new HeaterCoolerBack( heatCoolAmountProperty, _.extend( options.backOptions, {
        baseColor: options.baseColor
      } ) );
```

- [x] This `_.extend` call is buggy. It's extending `backOptions` when it should be `frontOptions`. And it's modifying `backOptions`, which violates best practices.

```js
      const heaterCoolerFront = new HeaterCoolerFront( heatCoolAmountProperty, _.extend( options.backOptions, {
        baseColor: options.baseColor,
        leftTop: heaterCoolerBack.getHeaterFrontPosition()
      } ) );
```

- [x] `labelMaxWidth` and tick label scaling do the same thing, the latter should be removed.

```js
      // Create the label strings and scale them to support translations.
      const titleOptions = { font: options.labelFont, maxWidth: options.labelMaxWidth };
      const heatTitle = new Text( options.heatLabel, titleOptions );
      const coolTitle = new Text( options.coolLabel, titleOptions );
      const titles = [ heatTitle, coolTitle ];

      // Scale the titles to fit within the bucket front if necessary.
      const maxTitleWidth = Math.max( coolTitle.width, heatTitle.width );
      if ( maxTitleWidth > bottomWidth / 2 ) {
        titles.forEach( function( title ) {
          title.scale( ( bottomWidth / 2 ) / maxTitleWidth );
        } );
      }
```

**Comment by pixelzoom** [comment]
@chrisklus would you mind reviewing these changes, since you and I worked on this in the not-so-distant past?

**Comment by chrisklus** [comment]
@pixelzoom your changes look good and so do the various usages i checked out (HeaterCoolerNode cases, separated Front and Back cases, and with `stringTest=long`). Back to you.
