### ISSUE TITLE
use TimeControlNode in sims

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#496]
In scenery-phet, I see `TimeControlNode`, which looks like this:

![screenshot_966](https://user-images.githubusercontent.com/3046552/57643036-fd220780-7575-11e9-8c01-c262a957f9c7.png)

I see only 2 sims using it:  capacitor-lab-basics and masses-and-springs.   And there are many more sims that could be using.   I wasn't previously aware of this, so I'm going to use it in gas-properties --- assuming that we can agree on how to standardize "Normal/Slow" vs "normal/slow".

Assigning to @ariel-phet to prioritize and assign.  First step would be to identify which sims have this control, which might be a good task for QA.

**Comment by pixelzoom** [comment]
First step is to agree on capitalization of radio button labels.

@arouinfar @ariel-phet  The design doc for Gas Properties specifies “normal” and “slow” labels.   Many sims uses those same labels. But MAS and CL:B uses common-code component `TimeControlNode ` with radio buttons labeled “Normal” and “Slow”.   I don't agree that capitalization is appropriate here, and I prefer "normal" and "slow", but will change the common code to whatever designers agree on.

**Comment by arouinfar** [comment]
> I see only 2 sims using it: capacitor-lab-basics and masses-and-springs.

That's frankly quite surprising. Thanks for opening the issue @pixelzoom. The are also some older sims using "Normal" and "Slow Motion" (Bending Light and Energy Skate Park Basics come to mind), which could be updated to "Normal" and "Slow".

> First step is to agree on capitalization of radio button labels.

I don't particularly want to re-hash the great casing debate from https://github.com/phetsims/tasks/issues/953, but I still vastly prefer title case for UI components/titles. While I acknowledge there can be some very sim-specific exceptions where a lowercase string may be preferable, I do not think that `TimeControlNode` is one of them. In the case of `gas-properties` other UI components/titles use title casing, so I think lowercase 'normal' and 'slow' looks inconsistent.

**Comment by pixelzoom** [comment]
I'll need to add 2 things to TimeControlNode in order to use it in Gas Properties:

(1) enabledProperty
(2) make the normal/slow radio buttons optional

**Comment by pixelzoom** [comment]
Oh no...this is becoming an ordeal.  `TimeControlNode` has no `dispose`, and neither does `VerticalAquaRadioButtonGroup`.

**Comment by pixelzoom** [comment]
The Normal/Slow (speed) radio buttons are now optional,  so this control can be used in sims in either of these 2 configurations:

![screenshot_966](https://user-images.githubusercontent.com/3046552/57643036-fd220780-7575-11e9-8c01-c262a957f9c7.png)
![screenshot_967](https://user-images.githubusercontent.com/3046552/57654414-53507400-7591-11e9-98e4-67aafd6a6d1b.png)

Summary of changes, @ariel-phet these should be reviewed by someone:

* converted `TimeControlNode` to ES6
* made speed radio buttons optional by moving `isSlowMotionProperty` from a constructor parameter to an option
* added `dispose` to `TimeControlNode`
* added `options.enabledProperty` to `TimeControlNode`
* cleaned up all options for `TimeControlNode`
* converted `VerticalRadioButtonGroup` to ES6
* implemented `dispose` for `VerticalRadioButtonGroup`

**Comment by pixelzoom** [comment]
@Denz1994 FYI, `TimeControlNode` has undergone extensive changes. I've tested with MAS and CL:B, but it would be good for you to verify too.

**Comment by ariel-phet** [comment]
@Denz1994 could you do this review?

**Comment by Denz1994** [comment]
Picking back up on this issue. I made a minor doc update for option type expressions. `getPlayPauseButtonCenter` isn't being used anywhere but it may prove valuable to keep the positioning flexible as noted in its documentation. 

There is a `tandem: TANDEM.REQUIRED` as the default for the options object in `TimeControlNode`. My inclination was to make the `options` a `config` object because the `tandem` field required. Documentation in TANDEM.js says, "Some common code (such as Checkbox or RadioButton) must always be instrumented." 

@pixelzoom Should we enforce our config rules on option fields for TANDEM.REQUIRED`? This would also include updating `options` to `config` for other common code components aswell.

**Comment by pixelzoom** [comment]
> Should we enforce our config rules on option fields for TANDEM.REQUIRED?

It would be good to check in with the PhET-iO team (@samreid @zepumph @chrisklus).  But, no I don't think we need to change `options` to `config` just because the default is `tandem: Tandem.REQUIRED`.   Imo that's an acceptable exception to our rules for options vs config.

**Comment by chrisklus** [comment]
>Imo that's an acceptable exception to our rules for options vs config.

Agreed since it's not required for phet-brand sims using TimeControlNode
