### ISSUE TITLE
TimerNode has inappropriate touchArea option

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#497]
Yet-another inappropriate pointer area default, this one in TimerNode:

`      touchAreaDilation: 10,`

First, this kind of default doesn't belong in a common-code component, especially one this large.   This issue started when I discovered that I had to set `touchAreaDilation: 0` to use this in Gas Properties.

Second, why is there an option for touchArea, but no option for mouseArea?

Third, there's no need for pointer area options.  One can simply set `touchArea` or `mouseArea` directly on the TimerNode. E.g.:

```js
const timerNode = new TimerNode(...);
timerNode.touchArea = timerNode.localBounds.dilated( 10 );
timerNode.mouseArea = timerNode.localBounds.dilated( 5 );
```

So... I'm going to remove option `touchAreaDilation ` and address at call sites.

**Comment by pixelzoom** [comment]
Option removed, call sites changed. 

@ariel-phet please assign someone to review.

**Comment by Denz1994** [comment]
@pixelzoom Shouldn't the revised call site in WOAS read:

```js
timer.touchArea = timer.localBounds.dilated( 10 );
```

The original call site didn't pass in an override to `touchAreaDilation`, so it should match the default that was present in `TimerNode.options.touchAreaDilation`.

Otherwise, this change looks appropriate.

**Comment by pixelzoom** [comment]
@Denz1994 Sorry, I should have noted.  I modified WOAS's `touchAreaDilation` because it had a problem. With `touchAreaDilation:10`, it kisses the "Rulers" checkbox touchArea:

<img width="293" alt="screenshot_1184" src="https://user-images.githubusercontent.com/3046552/57743886-2cbf3580-7684-11e9-95f1-1e6f946b4d27.png">

Changing to `touchAreaDilation:5` resolved the problem. And regardless, the TimerNode is plenty big.

<img width="231" alt="screenshot_1185" src="https://user-images.githubusercontent.com/3046552/57743944-6132f180-7684-11e9-833e-ac0ca24dbd6e.png">

**Comment by pixelzoom** [comment]
Btw... If you want to change WOAS back to `touchAreaDilation:10`, go for it, you're the responsible dev.

**Comment by Denz1994** [comment]
Understood, but @jonathanolson is listed as the responsible dev for WOAS.

The WOAS TimerNode touch area looks good. Also from the use cases above, there weren't any instances where the mouse areas should be adjusted either.  Assigning back to @pixelzoom to close.
