### ISSUE TITLE
SpectrumSlider vs NumberControl

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#498]
In https://github.com/phetsims/wave-interference/issues/377 and moved to a new issue https://github.com/phetsims/wave-interference/issues/394, the wavelength slider in Wave Interference Diffraction Screen currently looks like this:

![image](https://user-images.githubusercontent.com/679486/57723375-b8fe3800-7645-11e9-96a3-ed895217b820.png)

It was requested that:

> Format like Wavelength NumberControl in Bending Light -- Readout between tweakers above track.

Here's how Bending Light's Wavelength control looks:

![image](https://user-images.githubusercontent.com/679486/57723438-d92df700-7645-11e9-8dd2-d9f0c01489e8.png)

Unfortunately, NumberControl doesn't have an option to use a wavelength gradient for the track, and WavelengthSlider doesn't support the rich layouts that NumberControl supports.  In bending light this was accomplished with custom code which is roughly here: https://github.com/phetsims/bending-light/blob/a1ee4a52fbd48763975cb90e271674dfc33d8552/js/common/view/WavelengthControl.js#L43-L110 and can be described as "delete the tweaker buttons that come with the WavelengthSlider and create completely different ones".

@pixelzoom and @samreid are listed as authors of WavelengthSlider.  @pixelzoom is listed as author of NumberControl.  So first I'd like to reach out to @pixelzoom to see how he recommends to proceed.

**Comment by samreid** [comment]
I experimented with showing a gradient in the slider track, and showing a drop-down thumb with a "cursor" area, and it looked like this:

<details>

```

Index: scenery-phet/js/SpectrumSlider.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery-phet/js/SpectrumSlider.js	(revision 6161b29baa4053c281c66175792154400b2fe4db)
+++ scenery-phet/js/SpectrumSlider.js	(date 1558110642000)
@@ -427,6 +427,7 @@
 
   // mix accessibility in
   AccessibleSlider.mixInto( SpectrumSlider );
+  SpectrumSlider.Thumb = Thumb;
 
   return SpectrumSlider;
 } );
Index: sun/js/Slider.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- sun/js/Slider.js	(revision d255c2028e17322e852514bfad866ca478ef0ae7)
+++ sun/js/Slider.js	(date 1558110833000)
@@ -12,6 +12,9 @@
   'use strict';
 
   // modules
+  const Rectangle = require( 'SCENERY/nodes/Rectangle' );
+  const VBox = require( 'SCENERY/nodes/VBox' );
+  const VisibleColor = require( 'SCENERY_PHET/VisibleColor' );
   var AccessibleSlider = require( 'SUN/accessibility/AccessibleSlider' );
   var BooleanProperty = require( 'AXON/BooleanProperty' );
   var Dimension2 = require( 'DOT/Dimension2' );
@@ -30,6 +33,7 @@
   var SliderIO = require( 'SUN/SliderIO' );
   var SliderThumb = require( 'SUN/SliderThumb' );
   var SliderTrack = require( 'SUN/SliderTrack' );
+  var SpectrumSlider = require( 'SCENERY_PHET/SpectrumSlider' );
   var sun = require( 'SUN/sun' );
   var SunConstants = require( 'SUN/SunConstants' );
   var Tandem = require( 'TANDEM/Tandem' );
@@ -184,6 +188,14 @@
       centerLineStroke: options.thumbCenterLineStroke,
       tandem: options.tandem.createTandem( 'thumb' )
     } );
+    const t = new SpectrumSlider.Thumb( 20, 20, {} );
+    thumb = new VBox( {
+      children: [
+        new Rectangle( 0, 0, 4, 30, 2, 2, { stroke: 'black' } ),
+        t
+      ]
+    } );
+    valueProperty.link( value => t.setFill( VisibleColor.wavelengthToColor( Util.linear( 0, 100, VisibleColor.MIN_WAVELENGTH, VisibleColor.MAX_WAVELENGTH, value ) ) ) )
 
     // Dilate the local bounds horizontally so that it extends beyond where the thumb can reach.  This prevents layout
     // asymmetry when the slider thumb is off the edges of the track.  See https://github.com/phetsims/sun/issues/282
@@ -193,7 +205,7 @@
     sliderParts.push( this.track );
 
     // do this outside of options hash, so that it applied to both default and custom thumbs
-    thumb.centerY = this.track.centerY + options.thumbYOffset;
+    thumb.centerY = this.track.centerY + options.thumbYOffset + 10;
     sliderParts.push( thumb );
 
     // Wrap all of the slider parts in a Node, and set the orientation of that Node.
Index: sun/js/SliderTrack.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- sun/js/SliderTrack.js	(revision d255c2028e17322e852514bfad866ca478ef0ae7)
+++ sun/js/SliderTrack.js	(date 1558105970000)
@@ -15,12 +15,16 @@
   'use strict';
 
   // modules
+  const Color = require( 'SCENERY/util/Color' );
+  const Util = require( 'DOT/Util' );
+  const VisibleColor = require( 'SCENERY_PHET/VisibleColor' );
   var Dimension2 = require( 'DOT/Dimension2' );
   var inherit = require( 'PHET_CORE/inherit' );
   var Node = require( 'SCENERY/nodes/Node' );
   var Rectangle = require( 'SCENERY/nodes/Rectangle' );
   var SimpleDragHandler = require( 'SCENERY/input/SimpleDragHandler' );
   var SliderTrackIO = require( 'SUN/SliderTrackIO' );
+  var SpectrumNode = require( 'SCENERY_PHET/SpectrumNode' );
   var sun = require( 'SUN/sun' );
   var Tandem = require( 'TANDEM/Tandem' );
 
@@ -80,6 +84,11 @@
     } );
     this.addChild( this.enabledTrack );
 
+    this.addChild( new SpectrumNode( {
+      size: new Dimension2( this.size.width, this.size.height ),
+      valueToColor: value => VisibleColor.wavelengthToColor( Util.linear( 0, 1, VisibleColor.MIN_WAVELENGTH, VisibleColor.MAX_WAVELENGTH, value ) )
+    } ) );
+
     // click in the track to change the value, continue dragging if desired
     var handleTrackEvent = function( event, trail ) {
       var transform = trail.subtrailTo( self ).getTransform();
Index: sun/js/demo/ComponentsScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- sun/js/demo/ComponentsScreenView.js	(revision d255c2028e17322e852514bfad866ca478ef0ae7)
+++ sun/js/demo/ComponentsScreenView.js	(date 1558106025000)
@@ -211,7 +211,7 @@
     var range = new Range( 0, 100 );
     var tickLabelOptions = { font: new PhetFont( 16 ) };
     var sliderOptions = {
-      trackSize: new Dimension2( 300, 5 ),
+      trackSize: new Dimension2( 300, 30 ),
       thumbTouchAreaXDilation: 15,
       thumbTouchAreaYDilation: 15,
       thumbMouseAreaXDilation: 5,

```

</details>

![image](https://user-images.githubusercontent.com/679486/57942040-b7bf4c00-788d-11e9-949b-7881c23f1cdd.png)

This seems like the right direction to me.  I know it will be complicated to create options or features to customize/create subcomponents, but this is a problem we need to solve anyways.  Maintaining independent parallel codebases for spectrum sliders vs non-spectrum sliders seems much worse in my opinion.  I'm estimating >250 lines of code of SpectrumSlider are redundant, including but not limited to tweaker buttons & input listeners which would need separate phet-io and a11y instrumentation.

**Comment by samreid** [comment]
@ariel-phet reviewed the issue and recommended scheduling discussion for Thursday.

**Comment by pixelzoom** [comment]
Related issue https://github.com/phetsims/scenery-phet/issues/501

**Comment by jessegreenberg** [comment]
5/23/19

- Group consensus is to proceed with option 1 above. @samreid will explore it, and if he runs into any trouble will report back. @samreid may reach out to @pixelzoom for advice if necessary.

**Comment by samreid** [comment]
A note about mutually exclusive options.  Slider.js already has this code:

```js
// {Node} optional thumb, replaces the default.
// Client is responsible for highlighting, disabling and pointer areas.
// The thumb is positioned based on its center and hence can have its origin anywhere
thumbNode: null,

// Options for the default thumb, ignored if thumbNode is set
thumbSize: new Dimension2( 17, 34 ),
thumbFill: 'rgb(50,145,184)',
thumbFillHighlighted: 'rgb(71,207,255)',
thumbStroke: 'black',
thumbLineWidth: 1,
thumbCenterLineStroke: 'white',
thumbTouchAreaXDilation: 11,
thumbTouchAreaYDilation: 11,
thumbMouseAreaXDilation: 0,
thumbMouseAreaYDilation: 0,
```

I don't see any logic about requiring these options to be mutually exclusive.  Similar options will be added for track, and I created a library for asserting the options are mutually exclusive.  In the case of the track, the usage is like so:

```js
if ( options ) {
  assert && assert( mutuallyExclusiveOptions( options, [ 'thumbNode' ], [
    'thumbSize', 'thumbFill', 'thumbFillHighlighted', 'thumbStroke', 'thumbLineWidth', 'thumbCenterLineStroke',
    'thumbTouchAreaXDilation', 'thumbTouchAreaYDilation', 'thumbMouseAreaXDilation', 'thumbMouseAreaYDilation'
  ] ), 'cannot provide both kinds of thumb options' );
}
```

This works great for Slider.  However, NumberControl supplies these default options whether or not `trackNode` or `thumbNode` are passed in:

```js
      trackSize: new Dimension2( 180, 3 ),
      thumbSize: new Dimension2( 17, 34 ),
      thumbTouchAreaXDilation: 6,
```

My choices are to (a) forego checks for mutual exclusivity until further discussion or (b) to only have NumberControl override defaults if `thumbNode` or `trackNode` are not supplied.  I'm inclined to go with (b), but this will probably require discussion.

**Comment by samreid** [comment]
The mutual exclusivity feature is catching occurrences in 

* coulomb's law
* molecules-and-light

where `thumbNode` and `thumbSize` are both being specified.  It seems nice to be able to detect and prevent this kind of problem.

**Comment by samreid** [comment]
- [ ] document and finish SpectrumTrack
- [ ] document and finish SpectrumThumb
- [ ] can WavelengthSlider/FrequencySlider be rewritten using new strategy?

**Comment by samreid** [comment]
I'm at a good checkpoint for review, will commit shortly.  If we decide we want to proceed with this strategy and once the API is finalized, we can port delete SpectrumSlider or rewrite it to use this new common code.

**Comment by samreid** [comment]
I got to a good checkpoint and committed an initial working proposal.  I added a new Slider constructor option `trackNode` which can be used to specify an alternate track.  This mirrors the pre-existing option `thumbNode` which has been widely used.  In https://github.com/phetsims/phet-core/issues/60 I also added support for checking that mutually exclusive options were not supplied.

@ariel-phet or @pixelzoom can you please recommend a reviewer?  For this issue and related issue https://github.com/phetsims/phet-core/issues/60

After the review is complete, we can address the follow-up steps identified in https://github.com/phetsims/scenery-phet/issues/498#issuecomment-498113391

**Comment by ariel-phet** [comment]
@pixelzoom if you are able to do this review, I think that would be the most efficient. If you feel you don't have time currently, feel free to kick it back to me to find someone else.

**Comment by pixelzoom** [comment]
I'll be happy to review, but I'm unlikely to get to it until Thursday.

The request that will take me the most time is this one:

@samreid said:
> Questions and focus for the reviewer (beyond the usual review procedure):
> 
> * Make sure the behavior for existing usages of Slider (without using trackNode) is still working correctly

@samreid have you made a pass at this verification yourself? If so, then perhaps I can just spot check.

**Comment by samreid** [comment]
I did the following verification:
* lint-everything is passing
* CT doesn't show any new problems related to this
* Tested the Evaporation slider in Beer's Law Lab
* Tested the Mass slider in Energy Skate Park: Basics
* Tested some sliders in Graphing Quadratics
* Tested the sliders with custom thumb in Coulomb's Law
* Tested all slider components in the scenery-phet demo, including the NumberControls

**Comment by pixelzoom** [comment]
Thanks for the clarification @samreid.  I haven't done any review of the changes yet, so I don't know how extensive they are.  Do you think that an exhaustive look at Slider usages is a good idea? If so, then perhaps some time should be scheduled with QA.

**Comment by samreid** [comment]
Changes to existing features are medium-small.  An exhaustive QA test of all sliders seems like overkill, but will be a good thing to say "heads up" during upcoming RC tests.

**Comment by pixelzoom** [comment]
Most of this looks good to me.  `assertMutuallyExclusiveOptions` looks generally useful, and appropriate to use here.  Handling of `trackNode` option in `Slider` looks good.

A few things that I think could be improved:

- [ ] `SpectrumTrack extends SliderTrack` is odd.  It's a track on top of a track.  How about factoring out a base class, something like:

```
SliderTrack - abstract, needs a Node for the track
   DefaultSliderTrack extends SliderTrack - provides a Rectangle for the track 
   SpectrumSlider extends SliderTrack - provides a SpectrumNode for the track
```

- [ ] Generally we want `new` to create a fully-functional instance.  But `new SliderTrack` creates an instance that is not usable (and will fail an assertion) until `setValueToPositionFunction` is called. SliderTrack used to have a `valueToPosition` option. I'm not clear on what it was removed, put presumably there was some problem.  Investigate restoring this option, or some other way to avoid creating a non-functioning instance.

- [ ] Are the scenery-phet demos named 'SliderWithSpectrumTrack' and 'NumberControlWithSpectrum' only temporary?  Demo names typically correspond to class names.

**Comment by pixelzoom** [comment]
Next, the answer to additional questions...

> Questions and focus for the reviewer (beyond the usual review procedure):
> 
> * Make sure the behavior for existing usages of Slider (without using trackNode) is still working correctly

I did not do an exhaustive test.  I spot-checked a few sims and didn't see any obvious problems. 

> * Currently, the `valueToColor` must be manually synchronized between the `SpectrumTrack` and `SpectrumThumb`, and the `SpectrumThumb.cursorHeight` must be manually synchronized with the track height. Can/should these be constrained somehow? If so, how?

@samreid Do you mean that you must pass the same  `valueToColor` to both the SpectrumSlider and Spectrum thumb?  If so, I think that's fine.  If something else, please clarify.

> * Does the API require modification before widespread usage?

See https://github.com/phetsims/scenery-phet/issues/498#issuecomment-499654770, specially for SliderTrack hierarchy.

**Comment by samreid** [comment]
> Generally we want new to create a fully-functional instance. But new SliderTrack creates an instance that is not usable (and will fail an assertion) until setValueToPositionFunction is called. SliderTrack used to have a valueToPosition option. I'm not clear on what it was removed, put presumably there was some problem. Investigate restoring this option, or some other way to avoid creating a non-functioning instance.

The problem is that the `valueToPosition` LinearFunction doesn't exist until the Slider constructor is partway through.  For clients that pass in a custom `SliderTrack`, they will not be able to supply the `valueToPosition` value until it is created.  We could do something like this, but in my opinion that is more complex:

```js
    const trackSize = options.trackNode ? options.trackNode.size : options.trackSize;

    // @private mapping between value and track position
    this.valueToPosition = new LinearFunction( range.min, range.max, 0, trackSize.width, true /* clamp */ );

    // @private track
    this.track = options.trackNode || new SliderTrack( valueProperty, this.valueToPosition, {

      // propagate options that are specific to SliderTrack
      size: options.trackSize,
      fillEnabled: options.trackFillEnabled,
      fillDisabled: options.trackFillDisabled,
      stroke: options.trackStroke,
      lineWidth: options.trackLineWidth,
      cornerRadius: options.trackCornerRadius,
      startDrag: options.startDrag,
      endDrag: options.endDrag,
      constrainValue: options.constrainValue,

      // phet-io
      tandem: options.tandem.createTandem( 'track' )
    } );

    if ( options.trackNode ) {
      this.track.setValueToPositionFunction( this.valueToPosition );
    }
```

Note, for instance, this makes it impossible to create a `SliderTrack` before passing it in to `Slider` because we don't have the `this.valueToPosition` yet.  But if you are convinced it is better, I'll go for it!  Or maybe you can recommend another way out of this problem?

**Comment by samreid** [comment]
> Are the scenery-phet demos named 'SliderWithSpectrumTrack' and 'NumberControlWithSpectrum' only temporary? Demo names typically correspond to class names.

I struggled with that.  I'm not sure where to put these because Slider is defined in sun, but the spectra are defined in scenery-phet, and take 2 classes to make it work.  Where do you recommend these go?

**Comment by pixelzoom** [comment]
@samreid said:
> The problem is that the valueToPosition LinearFunction doesn't exist ...... Or maybe you can recommend another way out of this problem?

I'll need to get back to you on that, self assigning.

> ... Where do you recommend these go?

Would it be useful to create `SpectrumSlider extends Slider` and `SpectrumNumberControl extends NumberControl`, then use those class names for the demo names?

**Comment by samreid** [comment]
> SpectrumTrack extends SliderTrack is odd. It's a track on top of a track. How about factoring out a base class, something like [...]

That sounds nice, I'm going to upgrade SliderTrack to ES6/class and look into it further.

**Comment by samreid** [comment]
@pixelzoom we could start with a default (identity function?) `valueToPosition` which is wrong but can be overriden when connected to the slider?

**Comment by pixelzoom** [comment]
`valueToPosition` is:

`new LinearFunction( range.min, range.max, 0, trackSize.width, true /* clamp */ );`

You know `range` because it’s a required Slider constructor arg. 

You know `trackSize` because it’s provided to the SliderTrack constructor via options. 

Change SliderTrack and SpectrumTrack constructors to:

`constructor( property, range, options )`

Then `new SliderTrack` has everything it needs to create `valueToPosition`, and `setValueToPositionFunction` is unnecessary.

**Comment by pixelzoom** [comment]
Example:

```js
const property = new NumberProperty( ..., {
  range: new Range(...)
} );
const mySlider = new Slider( property, property.range, {
  track:  new SpectrumTrack( property, property.range )
} )
```

**Comment by pixelzoom** [comment]
Slack:

That sounds good.  We will additionally need a way to update the range. Note that in Slider.js the valueToPosition function can change in enabledRangeObserver. Anyways, I can investigate that.

Chris Malley [1:27 PM]
You might want to consider using the NumberPicker approach for dynamic range:

```function NumberPicker( valueProperty, rangeProperty, options )```

**Comment by samreid** [comment]
Stashing a patch with progress on adding Range argument to tracks:

```
Index: scenery-phet/js/SpectrumTrack.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery-phet/js/SpectrumTrack.js	(revision 729e2844e2359fb3e3d63cb4856bbc0e74d6d44e)
+++ scenery-phet/js/SpectrumTrack.js	(date 1560200378000)
@@ -18,9 +18,10 @@
 
     /**
      * @param {Property.<number>} property
+     * @param {Range} range
      * @param {Object} [options]
      */
-    constructor( property, options ) {
+    constructor( property, range, options ) {
       options = _.extend( {
         size: new Dimension2( 150, 30 ),
 
Index: scenery-phet/js/demo/SlidersScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery-phet/js/demo/SlidersScreenView.js	(revision 729e2844e2359fb3e3d63cb4856bbc0e74d6d44e)
+++ scenery-phet/js/demo/SlidersScreenView.js	(date 1560200378000)
@@ -158,10 +158,15 @@
   const demoSliderWithSpectrum = layoutBounds => {
     const property = new Property( 380 );
     const wavelengthToColor = VisibleColor.wavelengthToColor;
-    return new HSlider( property, new Range( 380, 780 ), {
+    const range = new Range( 380, 780 );
+    return new HSlider( property, range, {
       center: layoutBounds.center,
-      trackNode: new SpectrumTrack( property, { minValue: 380, maxValue: 780, valueToColor: wavelengthToColor } ),
-      thumbNode: new SpectrumThumb( property, { valueToColor: wavelengthToColor } )
+      trackNode: new SpectrumTrack( property, range, {
+        minValue: 380,
+        maxValue: 780,
+        valueToColor: wavelengthToColor
+      } ),
+      thumbNode: new SpectrumThumb( property, range, { valueToColor: wavelengthToColor } )
     } );
   };
 
@@ -174,7 +179,8 @@
     const wavelengthToColor = VisibleColor.wavelengthToColor;
 
     // NumberControl with default layout
-    return new NumberControl( '', property, new Range( 380, 780 ), {
+    const range = new Range( 380, 780 );
+    return new NumberControl( '', property, range, {
       titleNodeOptions: {
         font: new PhetFont( 14 )
       },
@@ -183,8 +189,12 @@
         valuePattern: '{0} nm'
       },
       sliderOptions: {
-        trackNode: new SpectrumTrack( property, { minValue: 380, maxValue: 780, valueToColor: wavelengthToColor } ),
-        thumbNode: new SpectrumThumb( property, { valueToColor: wavelengthToColor } )
+        trackNode: new SpectrumTrack( property, range, {
+          minValue: 380,
+          maxValue: 780,
+          valueToColor: wavelengthToColor
+        } ),
+        thumbNode: new SpectrumThumb( property, range, { valueToColor: wavelengthToColor } )
       },
       center: layoutBounds.center,
       layoutFunction: NumberControl.createLayoutFunction3( {
Index: sun/js/Slider.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- sun/js/Slider.js	(revision 3cc1388b9bb4ed29a9ac4f77153897a34c7f3859)
+++ sun/js/Slider.js	(date 1560201569000)
@@ -186,7 +186,7 @@
     sliderParts.push( this.minorTicksParent );
 
     // @private track
-    this.track = options.trackNode || new SliderTrack( valueProperty, {
+    this.track = options.trackNode || new SliderTrack( valueProperty, range, {
 
       // propagate options that are specific to SliderTrack
       size: options.trackSize,
@@ -203,14 +203,8 @@
       tandem: options.tandem.createTandem( 'track' )
     } );
 
-    // @private mapping between value and track position
-    this.valueToPosition = new LinearFunction( range.min, range.max, 0, this.track.size.width, true /* clamp */ );
-
-    // Whether the track was created or passed in, set the valueToPosition function.
-    this.track.setValueToPositionFunction( this.valueToPosition );
-
     // Position the track horizontally
-    this.track.centerX = this.valueToPosition( ( range.max + range.min ) / 2 );
+    this.track.centerX = this.track.valueToPosition( ( range.max + range.min ) / 2 );
 
     // The thumb of the slider
     var thumb = options.thumbNode || new SliderThumb( {
@@ -279,7 +273,7 @@
         if ( self.enabledProperty.get() ) {
           var transform = trail.subtrailTo( sliderPartsNode ).getTransform(); // we only want the transform to our parent
           var x = transform.inversePosition2( event.pointer.point ).x - clickXOffset;
-          var newValue = self.valueToPosition.inverse( x );
+          var newValue = self.track.valueToPosition.inverse( x );
 
           valueProperty.set( options.constrainValue( newValue ) );
         }
@@ -304,7 +298,7 @@
 
     // update thumb location when value changes
     var valueObserver = function( value ) {
-      thumb.centerX = self.valueToPosition( value );
+      thumb.centerX = self.track.valueToPosition( value );
     };
     valueProperty.link( valueObserver ); // must be unlinked in disposeSlider
 
@@ -318,14 +312,15 @@
       var max = initialValueToPosition( enabledRange.max );
 
       // update the geometry of the enabled track
+      self.track.setEnabledRange( enabledRange );
       self.track.updateEnabledTrackWidth( min, max );
 
       // update the function that maps value to position for the track and the slider
-      self.valueToPosition = new LinearFunction( enabledRange.min, enabledRange.max, min, max, true /* clamp */ );
-      self.track.setValueToPositionFunction( self.valueToPosition );
+      // self.valueToPosition = new LinearFunction( enabledRange.min, enabledRange.max, min, max, true /* clamp */ );
+      // self.track.setValueToPositionFunction( self.valueToPosition );
 
       // clamp the value to the enabled range if it changes
-      valueProperty.set( Util.clamp( valueProperty.value, enabledRange.min, enabledRange.max ) );
+      // valueProperty.set( Util.clamp( valueProperty.value, enabledRange.min, enabledRange.max ) );
     };
     this.enabledRangeProperty.link( enabledRangeObserver ); // needs to be unlinked in dispose function
 
@@ -410,7 +405,7 @@
      * @private
      */
     addTick: function( parent, value, label, length, stroke, lineWidth ) {
-      var labelX = this.valueToPosition( value );
+      var labelX = this.track.valueToPosition( value );
 
       // ticks
       var tick = new Path( new Shape()
Index: sun/js/SliderTrack.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- sun/js/SliderTrack.js	(revision 3cc1388b9bb4ed29a9ac4f77153897a34c7f3859)
+++ sun/js/SliderTrack.js	(date 1560201099000)
@@ -16,6 +16,7 @@
 
   // modules
   const Dimension2 = require( 'DOT/Dimension2' );
+  const LinearFunction = require( 'DOT/LinearFunction' );
   const Node = require( 'SCENERY/nodes/Node' );
   const Rectangle = require( 'SCENERY/nodes/Rectangle' );
   const SimpleDragHandler = require( 'SCENERY/input/SimpleDragHandler' );
@@ -26,9 +27,10 @@
 
     /**
      * @param {Property.<number>} valueProperty
+     * @param {Range} range
      * @param {Object} [options]
      */
-    constructor( valueProperty, options ) {
+    constructor( valueProperty, range, options ) {
       super();
 
       options = _.extend( {
@@ -49,9 +51,8 @@
       // @public (read-only)
       this.size = options.size;
 
-      // @private - linear function that maps property value to position along the track.  Set after construction and
-      // if/when the function changes.
-      this.valueToPosition = null;
+      // @public (read-only) - linear function that maps property value to position along the track.
+      this.valueToPosition = new LinearFunction( range.min, range.max, 0, this.size.width, true /* clamp */ );
 
       // @private - Represents the disabled range of the slider, always visible and always the full range
       // of the slider so that when the enabled range changes we see the enabled sub-range on top of the
@@ -135,6 +136,10 @@
       const enabledWidth = maxX - minX;
       this.enabledTrack.setRect( minX, 0, enabledWidth, this.size.height );
     }
+
+    setEnabledRange( enabledRange ) {
+      this.enabledRange = enabledRange;
+    }
   }
 
   return sun.register( 'SliderTrack', SliderTrack );
Index: sun/js/demo/ComponentsScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- sun/js/demo/ComponentsScreenView.js	(revision 3cc1388b9bb4ed29a9ac4f77153897a34c7f3859)
+++ sun/js/demo/ComponentsScreenView.js	(date 1560201570000)
@@ -228,14 +228,7 @@
       slider = new VSlider( property, range, sliderOptions );
     }
 
-    // major ticks
-    slider.addMajorTick( range.min, new Text( range.min, tickLabelOptions ) );
-    slider.addMajorTick( range.getCenter(), new Text( range.getCenter(), tickLabelOptions ) );
-    slider.addMajorTick( range.max, new Text( range.max, tickLabelOptions ) );
 
-    // minor ticks
-    slider.addMinorTick( range.min + 0.25 * range.getLength() );
-    slider.addMinorTick( range.min + 0.75 * range.getLength() );
 
     // show/hide major ticks
     var majorTicksVisibleProperty = new Property( true );
@@ -305,6 +298,16 @@
     else {
       layoutBox = new HBox( layoutBoxOptions );
     }
+    setTimeout( () => {
+      // major ticks
+      slider.addMajorTick( range.min, new Text( range.min, tickLabelOptions ) );
+      slider.addMajorTick( range.getCenter(), new Text( range.getCenter(), tickLabelOptions ) );
+      slider.addMajorTick( range.max, new Text( range.max, tickLabelOptions ) );
+
+      // minor ticks
+      slider.addMinorTick( range.min + 0.25 * range.getLength() );
+      slider.addMinorTick( range.min + 0.75 * range.getLength() );
+    }, 5000 );
 
     return layoutBox;
   };
Index: wave-interference/js/diffraction/view/DiffractionScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- wave-interference/js/diffraction/view/DiffractionScreenView.js	(revision 55ceb0b006052a9e8827a6ad5888997563ff219c)
+++ wave-interference/js/diffraction/view/DiffractionScreenView.js	(date 1560200378000)
@@ -265,8 +265,9 @@
 
       const wavelengthToColor = VisibleColor.wavelengthToColor;
       const trackHeight = 20;
+      const range = new Range( 380, 780 );
       const wavelengthPanel = new WaveInterferencePanel(
-        new NumberControl( wavelengthString, model.wavelengthProperty, new Range( 380, 780 ), {
+        new NumberControl( wavelengthString, model.wavelengthProperty, range, {
           titleNodeOptions: {
             font: WaveInterferenceConstants.DEFAULT_FONT
           },
@@ -275,7 +276,7 @@
             valuePattern: '{0} nm'
           },
           sliderOptions: {
-            trackNode: new SpectrumTrack( model.wavelengthProperty, {
+            trackNode: new SpectrumTrack( model.wavelengthProperty, range, {
               minValue: 380,
               maxValue: 780,
               valueToColor: wavelengthToColor,

```

**Comment by samreid** [comment]
I'm going to split out the remaining work into separate issues.

**Comment by samreid** [comment]
We'll continue in the related issues, closing this parent issue.
