### ISSUE TITLE
migrate OopsDialog from equality-explorer

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#499]
Equality Explorer has `OopsDiaog`, which looks like this:

<img width="524" alt="screenshot_1187" src="https://user-images.githubusercontent.com/3046552/57811301-1cac6200-7727-11e9-8137-5c009d2bcf80.png">

It has these resources:

* phet-girl-wagging-finger.png
* phet-girl-wagging-finger.ai

[Gas Properties design document](https://docs.google.com/document/d/1HOCO6vXfqlHIf3MrdldaiZTPFKYWTzS9Jm8fw-b25EU/edit#) specifies a similar dialog:

> In the Pressure (↕V) mode, there will come a time when P cannot be held constant, as the container is at its min or max volume. At that point, the sim will switch to holding Nothing constant. The Oops dialog will be displayed (similar to Equality Explorer). Dialog contents TBD, but could be something like:

<img width="615" alt="screenshot_1188" src="https://user-images.githubusercontent.com/3046552/57811449-7d3b9f00-7727-11e9-9ef2-53d2d5dd10ee.png">

Slack conversation where @arouinfar signed off on using `OopsDialog`:

> Chris Malley [3:28 PM]
Re the Oops! dialog.  There currently is no common code for this.  It lives in Equality Explorer, the message is customizable, the PhET Girl image is not.  If you are happy with how it looks in Equality Explorer, it will save a lot of time to move that to scenery-phet.  If you want something else, then I’ll start from scratch or copy code.
> 
> Amy Rouinfar [3:32 PM]
So the “Right side of the balance is full.” string would be the only customizable thing? That seems fine to me.
> 
> Chris Malley [3:32 PM]
Yes. “Oops!” would move to scenery-phet strings file.  phet-girl-wagging-finger.png would move to scenery-phet/images/.
👍

**Comment by pixelzoom** [comment]
I discovered that "Oops!" is part of the message string, and I suspect that's actually better than being locked into "Oops!" everywhere.

`OopsDialog` and its resources have been moved to scenery-phet.  I converted it to an ES6 class, and I added a demo (Dialogs screen).

@ariel-phet please assign someone to review.

**Comment by chrisklus** [comment]
The code, usages, and demo in scenery-phet look good, and the dialog correctly handles long strings. Back to you @pixelzoom.
