### ISSUE TITLE
Should the GaugeNode make it possible to see which tick mark the needle is pointing to?

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#503]
From #502.

Regarding the z-order of the needle, I think it is somewhat problematic that you cannot see both the needle and the tickmark at the same time.  This is not a new problem introduced by fixes in #502--it was already pretty difficult to see both, here is a screenshot from published Forces and Motion: Basics (2.3.9)

![image](https://user-images.githubusercontent.com/679486/58578963-45445980-8207-11e9-87e1-2c38dfb873b6.png)

It seems like a somewhat poor user interface to cover up the tick marks.  For instance, in sliders we often extend the ticks so the thumb cannot completely cover them up:

![image](https://user-images.githubusercontent.com/679486/58579183-b2f08580-8207-11e9-9117-9d6268c57254.png)

May be less of a problem for GaugeNodes that are qualitative, but I thought I'd bring it up for discussion just in case.

Assigned to @ariel-phet for discussion/delegation.

**Comment by pixelzoom** [comment]
> It seems like a somewhat poor user interface to cover up the tick marks. 

I don't believe that anyone is actually reading tick marks with this gauge.   If they are trying to read ticks, then there are bigger problems; the ticks aren't labeled, and neither is the min/max. 

So I don't really think this is an issue.  But if you're convinced that it is, then make the needle a bit shorter.

**Comment by ariel-phet** [comment]
@pixelzoom @samreid the needle of the gauge should definitely not be behind the tickmarks in my opinion, I think that would look unrealistic and a bit odd.

Two changes would be ideal if we want to have a slightly more realistic gauge As in this picture:

![speedometer ttk](https://user-images.githubusercontent.com/4051174/58602693-12bc5000-824b-11e9-847d-10cfe8e1db9b.jpg)

1. Shorten the needle slightly as @pixelzoom suggested, that is clearly a tried and true UI design of speedometers. This seems like an easy and worthwhile enhancement. I would make the needle extend to halfway into the minor tickmark.

2. Give the needle a more "tapered" appearance. I am not sure if that has performance implications or other complexity, but it would make the needle more needle-y. 

I think we should do (1), (2) doesn't seem worth much effort.

**Comment by ariel-phet** [comment]
Whoever feels like making the needle short first, go for it.

**Comment by pixelzoom** [comment]
I'm on it.  

Minor ticks aren't placed like the gauge shown in https://github.com/phetsims/scenery-phet/issues/503#issuecomment-497171078, so "halfway into the minor tickmark" doesn't do much to address this.  It would look like this in scenery-phet demo:

<img width="405" alt="screenshot_1222" src="https://user-images.githubusercontent.com/3046552/58611493-8c186a80-826c-11e9-843e-38a568217da1.png">

So I used 1/2 of the _major tick_ length, which looks like this:

<img width="346" alt="screenshot_1223" src="https://user-images.githubusercontent.com/3046552/58611536-afdbb080-826c-11e9-903f-0fa9b08308ae.png">

@ariel-phet @samreid does this look acceptable?

**Comment by ariel-phet** [comment]
@pixelzoom looks good to me!

**Comment by samreid** [comment]
@pixelzoom does this issue require further work before closing? https://github.com/phetsims/scenery-phet/commit/a6683aea16aa0613dfc7c4f36fd01546af1c863f looks good to me.

**Comment by pixelzoom** [comment]
👍
