### ISSUE TITLE
NumberDisplay numberRange is confusing

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#504]
This has bothered me for awhile and was most recently pointed out by @zepumph in https://github.com/phetsims/scenery-phet/issues/482#issuecomment-499673892.

`NumberDisplay` constructor signature is:

```js
  /**
   * @param {Property.<number|null>} numberProperty
   * @param {Range} numberRange
   * @param {Object} [options]
   * @constructor
   */
  function NumberDisplay( numberProperty, numberRange, options ) {
```

The `numberRange` parameter is not actually the range of `numberProperty`.  It's used to size the display's background and set its maxWidth.   Here's the relevant code:

```js
    // determine the widest value
    var minString = valueToString( numberRange.min, options.decimalPlaces, options.noValueString );
    var maxString = valueToString( numberRange.max, options.decimalPlaces, options.noValueString );
    var longestString = StringUtils.fillIn( options.valuePattern, {
      value: ( ( minString.length > maxString.length ) ? minString : maxString )
    } );
```

We definitely don't want `NumberDisplay` to error if `numberRange` is exceeded. That's the responsibility of `numberProperty` or its owner.  What we do want to do is to specify a fixed size for the display, and have the value sized to fit if it exceeds the display's size.

Assigning to myself with low priority.

**Comment by pixelzoom** [comment]
When this is addressed, we'll also need to address the API for `ComboBoxDisplay`, which is exposing this wart in its `items` data structure.

**Comment by pixelzoom** [comment]
Thinking out loud...  Maybe we should:
* get ride of param `numberRange`
* add option `minWidth` to set an optional min width
* use existing option `maxWidth` to set an optional max width

**Comment by pixelzoom** [comment]
Adding label "meeting:developer".  Please weigh in on the proposed API change in https://github.com/phetsims/scenery-phet/issues/504#issuecomment-502909488, and/or suggest alternatives.

**Comment by samreid** [comment]
I don't understand how the proposal is supposed to size the rectangle to match the longest `valueToString` text, or how it is supposed to make that step unnecessary.  Would it help if the api changed something like this?

```js
  /**
   * @param {Property.<number|null>} numberProperty
   * @param {number[]} numbersThatMightBeTheLongestStringWhenRendered
   * @param {Object} [options]
   * @constructor
   */
  function NumberDisplay( numberProperty, numbersThatMightBeTheLongestStringWhenRendered, options ) {
```

**Comment by pixelzoom** [comment]
> I don't understand how the proposal is supposed to size the rectangle to match the longest valueToString text

It doesn't -- it does away with dependency on any value, and sets a `minWidth`.

**Comment by pixelzoom** [comment]
> I don't understand how the proposal is supposed to size the rectangle to match the longest valueToString text

It doesn't -- it does away with trying to compute min width from a value, and sets an explicit `minWidth`.

**Comment by samreid** [comment]
That sounds like a good solution to me.

**Comment by pixelzoom** [comment]
7/25/19 dev meeting:

What we want to be able to do is specify a fixed size for the display.  Currently we can't support pixel-polishing like "make that 2 pixels wider".   I'll investigate mutually exclusive `fixedWidth` and `range` options.   And I'll evaluate how many call sites need to be changed.

**Comment by pixelzoom** [comment]
NumberDisplay is used directly and as a subcomponent of several common-code UI components.   Here's an inventory of the usage sites.

Direct use:
24 - `new NumberDisplay`
1 - `extends NumberDisplay` 
0 - `inherit( NumberDisplay`

As a subcomponent of `ComboBoxDisplay`:
1 - `new ComboBoxDisplay`
2 - `extends ComboBoxDisplay`
0 - `inherit( ComboBoxDisplay`

As a subcomponent of `FineCoarseSpinner`:
3 - `new FineCoarseSpinner`
0 - `extends FineCoarseSpinner`
0 - `inherit( FineCoarseSpinner`

As a subcomponent of `NumberControl`:
37 - `new NumberControl`
3 - `extends NumberControl`
5 - `inherit( NumberControl`

As a subcomponent of `ValueGauge`:
2 - `new ValueGauge`
0 - `extends ValueGauge`
0 - `inherit( ValueGauge`

So there are 78 uses (25 direct, 53 indirect) that need to be inspected.

**Comment by pixelzoom** [comment]
As an interim "fix"... In the above commit, I renamed parameter `numberRange` to `displayRange`, and improved the documentation.  This is a small change, but should reduce the confusion about how this parameter is used. 

```js
  /**
   * @param {Property.<number|null>} numberProperty
   * @param {Range} displayRange - this range, with options.decimals applied, is used to determine the display width.
   *                               It is unrelated to the range of numberProperty.
   * @param {Object} [options]
   * @constructor
   */
  function NumberDisplay( numberProperty, displayRange, options ) {
```

**Comment by pixelzoom** [comment]
Based on the extensive use of `NumberDisplay` documented in https://github.com/phetsims/scenery-phet/issues/504#issuecomment-519322761, I'm not interested in doing the amount of Javascript busy-work that would be required to change this.  My recommendation is to leave it as is.   Labeling for dev meeting and assigning to @ariel-phet to decide how to proceed.

**Comment by jessegreenberg** [comment]
Going with a rename seems very reasonable to me and helps a lot. Previously, we said
>  Currently we can't support pixel-polishing like "make that 2 pixels wider"

Isn't that supported already by option xMargin?

**Comment by pixelzoom** [comment]
Adjusting `xMargin` will allow you to pixel polish the width of the NumberDisplay, but not the width of the value in the display.

At 8/8/19 dev meeting, we decided that this is sufficient, and will close.
