### ISSUE TITLE
Fix scenery-phet demo titles

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#507]
From https://github.com/phetsims/scenery-phet/issues/498#issuecomment-499654770 

> Are the scenery-phet demos named 'SliderWithSpectrumTrack' and 'NumberControlWithSpectrum' only temporary? Demo names typically correspond to class names.

I replied:

I struggled with that. I'm not sure where to put these because Slider is defined in sun, but the spectra are defined in scenery-phet, and take 2 classes to make it work. Where do you recommend these go?

> Would it be useful to create SpectrumSlider extends Slider and SpectrumNumberControl extends NumberControl, then use those class names for the demo names?

**Comment by samreid** [comment]
There is already a legacy file named "SpectrumSlider" which we are hoping to replace with Slider + SpectrumSliderTrack.

**Comment by samreid** [comment]
I fixed the name for the straightforward case.  For the `NumberControl` that specifies a spectrum in `sliderOptions`, the title remains `NumberControlWithSpectrum` and that seems sensible to me.  The value of creating a class that specifies that option does not seem like it will equal or exceed the cost.  

Back to @pixelzoom for discussion, or close at your discretion.

**Comment by pixelzoom** [comment]
Looks OK, closing.
