### ISSUE TITLE
FaucetNode accessibility should respect interactiveProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#510]
While working on https://github.com/phetsims/wave-interference/issues/412, @zepumph and I noticed that FaucetNode has an accessible peer dom element whether or not `interactiveProperty` is true.  We would like to change it so that FaucetNode is only keyboard navigable when `interactiveProperty` is true.

**Comment by samreid** [comment]
@zepumph and I collaborated to make this change.  We tested with Waves Intro as well as Concentration.  Lint is passing, and the root problem in Waves Intro is fixed.  However, neither of us is familiar with FaucetNode, so it would be great if @pixelzoom can do a review.  You can test the keyboard navigability by running Waves Intro, which now as `accessible: true` by default.

**Comment by pixelzoom** [comment]
I skimmed the above commits and my only conclusion is that I'm not qualified to review. I was not involved in adding a11y to FaucetNode, looks like @jbphet handled that in https://github.com/phetsims/scenery-phet/commit/7d606270a2de72ab26fe24e6fce1070da09e7534.  It would probably be best to have @jbphet or someone else on the a11y team review.

**Comment by samreid** [comment]
@jbphet or @jessegreenberg can you please take a look?

**Comment by jessegreenberg** [comment]
I reviewed, this change looks good to me, thanks!
