### ISSUE TITLE
Fixed decimal places in NumberDisplay restricts their usage

### ISSUE THREAD

**Issue by arnabp** [phetsims/scenery-phet#511]
NumberDisplay currently sets a fixed number of decimal places at which to display its numbers. This is done so that the maxWidth of the box can be calculated on construction. 

However, this has presented a problem in https://github.com/phetsims/projectile-motion/issues/173 where user entry for a property's value means the display should match however many decimal places the property itself has.

In the issue I posted one idea for a solution:
> modify NumberDisplay to accommodate the issues that have come up. This involves two changes: First I'd do a null check on the decimalPlaces option that doesn't use Util.toFixed if decimalPlaces is set to null. Second would be to create a maxDecimalPlaces option that is set to decimalPlaces by default, but when overridden is used to set the width of the NumberDisplay. The first change is pretty simple, but the second adds another option which can get overcomplicated.

However, I also noticed in https://github.com/phetsims/scenery-phet/issues/504 that @pixelzoom was considering doing away with using the range of the number to determine the min/max width of the box. If this were implemented, then the solution to this problem would simply be to display the NumberProperty as is, make decimalPlaces default to null, and only use Util.toFixed when decimalPlaces is given a value. I do believe this solution to be the better one, assuming @pixelzoom wants to move forward with #504 to begin with.

I don't believe this is a high priority issue for Projectile-Motion as a whole, but it is blocking the specific issue being addressed. Assigning to Ariel for prioritization.

**Comment by ariel-phet** [comment]
@pixelzoom marking medium priority since this sounds reasonably quick. If my impression is wrong, feel free to defer, or kick back to me.

**Comment by pixelzoom** [comment]
This should be a relatively easy change in `NumberDisplay`, and it's independent of #504.   The bulk of the time will be visiting all of the usages of `NumberDisplay`, identifying the ones that don't set `decimalPlaces`, and making them explicitly set `decimalPlaces: 0`.

**Comment by pixelzoom** [comment]
* 13 occurrences of "const NumberDisplay ="
* 1 occurrence of "var NumberDisplay ="
* 24 occurrences of "new NumberDisplay("
* 0 occurrences of "extends NumberDisplay"
* 0 occurrences of "inherit( NumberDisplay"
* 3 occurrences of "numberDisplayOptions"

**Comment by pixelzoom** [comment]
Also need to inspect all uses of `ComboBoxDisplay`, `FineCoarseSpinner`, `NumberControl`, `ValveGaugeNode` -- they use `NumberDisplay`. 

This is turning into a _lot_ of work.   So here's what I'm going to do is:
* Keep the default of `decimalPlaces: 0`, since there are so many places that assume that default.
* Add support for `decimalPlaces: null`, which can be used in Projectile Motion and any other places that want to show the full value without constraint on the number of decimal places.

**Comment by pixelzoom** [comment]
Support for `decimals: null` was added in the previous commit.  If you'd like to test this, go to `SCENERY_PHET/ComponentsScreenView` and in function `demoNumberDisplay` add `decimals: null` like this:

```js
    // Options for both NumberDisplay instances
    const numberDisplayOptions = {
      valuePattern: '{{value}} K',
      align: 'right',
      decimalPlaces: null
    };
```

Back to @arnabp for review, and to verify that this provides the functionality needed in Projectile Motile.

**Comment by arnabp** [comment]
Functionality matches what I'm looking for in Projectile Motion, looks good!
