### ISSUE TITLE
ThermometerNode ticks should have option to space by temperature

### ISSUE THREAD

**Issue by arnabp** [phetsims/scenery-phet#516]
Currently ThermometerNode spaces tick marks based on a pixel value. An option for spacing tick marks based on a temperature value would be more logical for thermometers where the exact temperature of the thermometer is important.

Feature needed from https://github.com/phetsims/blackbody-spectrum/issues/107

**Comment by arnabp** [comment]
Some things of note:

Originally ticks were added to the thermometer from the top down. I'm not sure why this was done and couldn't find any reasons in past commits. I changed it to bottom up so the minor/major ticks would make more sense with temperature based tick spacing. 

I also had to adjust how spacing was done in general, so this change affected all thermometer nodes in terms of exact tick placement. I spot checked most of the sims that used thermometers to verify that they looked okay, but this should be reviewed.

While working on this it also occurred to me that this should perhaps be the default behavior for tick spacing. ThermometerNode requires min and max temperature, I would think spacing the ticks based on temperature would be reasonable. Many commercial thermometers space at intervals of 10 degrees (with major ticks at 20), which could then be the default for the option. However, this would require going back to existing thermometers and deciding on a new value for temperature spacing where previously it was pixel based, so I'll leave this up to @pixelzoom to decide whether it's worth pursuing.

**Comment by pixelzoom** [comment]
Hmmm... I haven't looked at other sims, but this is a change to Gas Properties.  

Before:

<img width="244" alt="screenshot_1286" src="https://user-images.githubusercontent.com/3046552/61491152-dca66d00-a96b-11e9-93c4-7bcf732fc2cb.png">

After:

<img width="207" alt="screenshot_1287" src="https://user-images.githubusercontent.com/3046552/61491158-e203b780-a96b-11e9-8e76-016f0acba293.png">

I'm not sure that this is a change for the better.  @arouinfar what do you think?

**Comment by arouinfar** [comment]
@pixelzoom I think this is fine for Gas Properties, and I don't think it necessarily needs to block the rc. 

However, this very likely threw a wrench into Energy Forms and Changes where the tick marks had deliberate placement, so @chrisklus may want to comment here.

**Comment by arnabp** [comment]
Took a look at Energy Forms and Changes and there was some behavior there that wasn't intended (tick marks going into the curved top of the thermometer). Added a hotfix for that (gas properties remains unchanged).

**Comment by pixelzoom** [comment]
Back to your question in https://github.com/phetsims/scenery-phet/issues/516#issuecomment-512973502...
> While working on this it also occurred to me that this should perhaps be the default behavior for tick spacing. .... so I'll leave this up to @pixelzoom to decide whether it's worth pursuing.

I think that's a decision best left up to the sim designers, so assigning to @arouinfar.  In all of the sims where I've used ThermometerNode so far, the position of the mercury in the tube is qualitative, and the position/spacing/number of ticks is not significant.

**Comment by arouinfar** [comment]
> ThermometerNode requires min and max temperature, I would think spacing the ticks based on temperature would be reasonable. 

In general, that also sounds reasonable to me. 

Most of the time ThermometerNode is purely qualitative. Energy Forms and Changes is one exception, which has tick marks deliberately spaced in 25 *C increments, so the boiling point of water perfectly aligns with a tick mark.
<img width="194" alt="Screen Shot 2019-07-20 at 10 38 55 AM" src="https://user-images.githubusercontent.com/8419308/61581626-1d25f800-aade-11e9-9dd4-b8f4470ce3f4.png">

In master, the tick marks have shifted, and water's boiling point is not longer aligned. This is problematic.
<img width="196" alt="Screen Shot 2019-07-20 at 11 04 41 AM" src="https://user-images.githubusercontent.com/8419308/61581646-40e93e00-aade-11e9-9b94-39f08e314ab4.png">

I don't know all the nitty-gritty details of ThermometerNode, so I'm not sure if it would be relatively easy to adjust the tick marks in EFAC to recover the desired spacing. @chrisklus?

**Comment by chrisklus** [comment]
I think this change is a step in the right direction, but needs to be tuned a little bit (at least in EFAC's case). The new option is helpful for me to explicitly set min and max tick marks for desired temperatures, see https://github.com/phetsims/energy-forms-and-changes/issues/240#issuecomment-485991115.

![image](https://user-images.githubusercontent.com/5618316/61661356-14bdf080-ac89-11e9-8df4-65fa4932f0c2.png)

The usage in the screenshot above is leveraging this option. Since the major and minor tick marks alternate, I think the major tick marks should correspond to even numbers. In the case above, the spacing is correct (the amount space for ticks from 0 C to 300 C works out), but everything should be shifted up by one tick-space, so that there is no big gap at the top, and so 50, 100, 150 etc land on the big ticks.

Also, documentation is needed for the option.

**Comment by arnabp** [comment]
It was my initial intention that major ticks correspond to even multiples of tick spacing, but the large tick coming first in this case threw it off. I was able to fix that issue so major tick marks should now correspond to even numbers. 

I've also increased how high the final tick can go. This should make it so the gap at the top isn't so big without creating tick marks that go outside the thermometer itself (as it was in energy forms and changes before the hotfix). Gas properties looks closer to before as a result of this: 
<img width="261" alt="Screen Shot 2019-07-23 at 1 11 39 PM" src="https://user-images.githubusercontent.com/8583364/61742222-d9d2c000-ad4f-11e9-90c3-e6fffe5c0649.png">

Also added documentation. Please verify that energy forms and changes now looks as intended @chrisklus

**Comment by chrisklus** [comment]
EFAC thermometers look great, thanks @arnabp. Code looks good, too.

![image](https://user-images.githubusercontent.com/5618316/61749385-e3642400-ad5f-11e9-9012-266309f0b9cf.png)

**Comment by arnabp** [comment]
Passing this back to @pixelzoom since adjustments have been made for blackbody and EFAC use cases; to review changes and how best to move forward with possibly making this the default for thermometerNode.

**Comment by pixelzoom** [comment]
As I said in https://github.com/phetsims/scenery-phet/issues/516#issuecomment-513412746... In all of the sims where I've used `ThermometerNode` so far, the position of the mercury in the tube is qualitative, and the position/spacing/number of ticks is not significant. So whether this is a better default is a decision best left up to sim designers.  If the concerns that @arouinfar and @chrisklus had are addressed, and they agree that it's a better default, then I'm on board.  But it's their call.

**Comment by arouinfar** [comment]
The EFAC thermometer in https://github.com/phetsims/scenery-phet/issues/516#issuecomment-515795315 looks good to me, and serves the goals of that sim. It sounds like @chrisklus is also happy with the implementation, so I'd say `ThermometerNode` is good to go.

**Comment by chrisklus** [comment]
>It sounds like @chrisklus is also happy with the implementation, so I'd say ThermometerNode is good to go.

Yep, I'm happy with the option. 

@pixelzoom said:

>So whether this is a better default is a decision best left up to sim designers. If the concerns that @arouinfar and @chrisklus had are addressed, and they agree that it's a better default, then I'm on board. But it's their call.

No preference on default behavior - I'm happy to leave it qualitative as it's always been. Sounds like that is the more used case right now, anyway. And no more sim work needs to be done if we leave it as is.

@pixelzoom I couldn't tell if you were done reviewing - I'll pass back to you to finish or close if we are all satisfied.

**Comment by pixelzoom** [comment]
Yes, I've finished reviewing.  Back to @arnabp in case there's anything else to do here.

**Comment by arnabp** [comment]
Functionality needed for blackbody is in, everything else looks good. Closing.
