### ISSUE TITLE
ColorProfile should use StringProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#517]
In ColorProfile constructor:

```js
   var profileNameProperty = this.profileNameProperty = new Property( 'default', {
      tandem: tandem.createTandem( 'profileNameProperty' ),
      phetioType: PropertyIO( StringIO ),
      validValues: profileNames
    } );
```

From the code-review checklist:

> - [ ]  Properties should use type-specific subclasses where appropriate (.e.g BooleanProperty, NumberProperty, StringProperty) or provide documentation as to why they are not.

**Comment by pixelzoom** [comment]
Done in the above commit, tested with a couple of ColorProfiles.  @chrisklus would you mind glancing at this?

**Comment by chrisklus** [comment]
Looks good @pixelzoom, back to you.
