### ISSUE TITLE
Dilate touch area for FaucetNode shooter

### ISSUE THREAD

**Issue by chrisklus** [phetsims/scenery-phet#521]
For https://github.com/phetsims/energy-forms-and-changes/issues/239, @arouinfar asked if I could dilate the touch area of the FaucetNode handle a bit. It doesn't look like ShooterNode supports that yet, can we add this option @pixelzoom? I'm happy to do it unless you would prefer to.

**Comment by pixelzoom** [comment]
Go for it, I have too many other higher priority things on my plate right now.   I'll be happy to review the changes.

Thoughts:
* Add support for both touchArea and mouseArea dilation. 
* It's probably appropriate to do this via nested options, i.e. `shooterOptions`.  
* It looks like there is one existing option, `knobScale`, that should be moved to `shooterOptions`.  It has zero uses outside of FaucetNode.

So you'll end up with something like this for the nested options:

```js
shooterOptions: {
      knobScale: 0.6, // values in the range 0.6 - 1.0 look decent

      // pointer area dilation
      touchAreaXDilation: 0,
      touchAreaYDilation: 0,
      mouseAreaXDilation: 0,
      mouseAreaYDilation: 0
}
```

**Comment by chrisklus** [comment]
Thanks @pixelzoom. 

>It has zero uses outside of FaucetNode.

Because they share the same file, I nested the default options in FaucetNode options, and then passed them through to ShooterNode as config. I thought that seemed preferable to duplicating them in ShooterNode or just hiding them in ShooterNode.

@pixelzoom please review.

**Comment by pixelzoom** [comment]
Maybe I'm missing something, but this seems overly complicated:

```js
            var dxTouch = dx + config.touchAreaXDilation;
	    var dyTouch = dy + config.touchAreaYDilation;
	    var dxMouse = dx + config.mouseAreaXDilation;
	    var dyMouse = dy + config.mouseAreaYDilation;
	
	    // set pointer areas before scaling
	    knobNode.touchArea = Shape.rectangle( -dxTouch, -dyTouch, knobNode.width + 2 * dxTouch, knobNode.height + 2 * dyTouch );
	    knobNode.mouseArea = Shape.rectangle( -dxMouse, -dyMouse, knobNode.width + 2 * dxMouse, knobNode.height + 2 * dyMouse );
```
<br>
Is there some reason why this more typical way of dilating pointer areas can't be used? (untested)

```js
 // set pointer areas before scaling
knobNode.touchArea = knobNode.localBounds.dilatedXY( config.touchAreaXDilation, config.touchAreaYDilation );
knobNode.mouseArea = knobNode.localBounds.dilatedXY( config.mouseAreaXDilation, config.mouseAreaYDilation );
```

**Comment by chrisklus** [comment]
Using `localbounds` resulted in a much smaller pointer area than what you originally implemented, see the old usages of `dx` and `dy`. I added those in that way so that 0 dilation resulted in the same former behavior (same size pointer area).

Alternatively, I think we could use the standard way of dilating pointer areas and then have large default values so the usages of FaucetNode are unchanged.

**Comment by pixelzoom** [comment]
I think we should use localBounds, keep `0` as the default option values, and adjust the current usages of FaucetNode.

**Comment by pixelzoom** [comment]
... Or you could consult with designers and ask whether a non-zero default touchArea dilation is OK.

**Comment by chrisklus** [comment]
>adjust the current usages of FaucetNode.

There are only 6, but that seems strange to me that we would override with options for every case and never use the defaults. Is that just our standard practice - to have a node's pointer area default to its bounds?

>... Or you could consult with designers and ask whether a non-zero default touchArea dilation is OK.

Seems reasonable. @arouinfar what do you think?

**Comment by pixelzoom** [comment]
Yes, the default point area for any Node is is bounding rectangle.   So the current implementation for the shoot in FaucetNode does not yield the results that I'd expect.

**Comment by pixelzoom** [comment]
I discussed with @chrisklus via Zoom.  Here's what we're going to do for now:

* use `knobNode.localBounds.dilatedXY` to compute pointer areas
* set `mouseAreaXDilation` and `mouseAreaYDilation` defaults to `0`
* set `touchAreaXDilation` and `touchAreaYDilation` to  whatever is needed to provide the same touchArea before these changes were done   

Then @arouinfar and @chrisklus can work out whether `touchAreaXDilation` and `touchAreaYDilation` defaults should be `0`.

**Comment by arouinfar** [comment]
> Then @arouinfar and @chrisklus can work out whether `touchAreaXDilation` and `touchAreaYDilation` defaults should be 0.

This sounds reasonable to me, assuming that touch area dilations are normally 0 by default. However, if common UI components generally have some non-zero touch area dilation by default, then we should probably pick something greater than zero.

**Comment by chrisklus** [comment]
I've set the default touch area dilation to 0 and updated the relevant usages to the previous size, searching on `new FaucetNode`, `extendsFaucetNode`, and `FaucetNode.call`.

@pixelzoom please review.

**Comment by pixelzoom** [comment]
I reviewed the above changes. I verified that the XY touchArea dilation to these changes was (36.5,60), so using (37,60) at call sites seems reasonable.   Closing.
