### ISSUE TITLE
branch: sounds-in-common-code

### ISSUE THREAD

**Issue by jbphet** [phetsims/scenery-phet#524]
This branch will be used as a place to try out and hopefully finalize the strategies for integrating sound into common code components.  See https://github.com/phetsims/tambo/issues/73, https://github.com/phetsims/sun/issues/505, and https://github.com/phetsims/sun/issues/506.  There is also a parallel branch in sun for this work, see https://github.com/phetsims/sun/issues/521.

**Comment by jbphet** [comment]
The sounds for common UI components have been merged into master and I've just deleted the branch.  Closing.

**Comment by pixelzoom** [comment]
Due to https://github.com/phetsims/special-ops/issues/196#issuecomment-823486502, this branch was restored.  It will need to be deleted again.  Reopening and self assigning.

**Comment by pixelzoom** [comment]
Re-deleted using GitHub UI.  Closing.
