### ISSUE TITLE
Instrumentation tweaks to NumberDisplay

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#525]
From design meeting today in GFL in https://github.com/phetsims/gravity-force-lab/issues/76:

* `valueNode` renamed to `valueText`
* make it `phetioReadOnly`

Tagging @samreid because he made the initial implementation, and @pixelzoom because there are commits from him recently in the file.

**Comment by zepumph** [comment]
Over to @samreid to review.

**Comment by samreid** [comment]
The changes look great, thanks!
