### ISSUE TITLE
Should TimerNode be renamed to StopwatchNode?

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#530]
I noticed that in many occurrences such as Gas Properties, Pendulum Lab and CCK AC (design), the TimerNode is referred to as a "Stopwatch".  One exception is Wave on a String, where it is called "Timer".  I'm wondering if we should rename the JS file from TimerNode to StopwatchNode to be clearer?  Should we also rename the checkbox in Wave on a String to "Stopwatch" for across-sim consistency?

Tagging for https://github.com/phetsims/circuit-construction-kit-common/issues/449

**Comment by jonathanolson** [comment]
Sounds fine to me.

**Comment by arouinfar** [comment]
@samreid while perhaps a bit verbose, StopwatchNode would be more accurate. Generally, a timer counts down to zero, while a stopwatch counts up.

**Comment by arouinfar** [comment]
I would also be in favor of changing the string in WOAS to "Stopwatch", though it's not particularly urgent.

**Comment by samreid** [comment]
Marking for potential work in https://github.com/phetsims/circuit-construction-kit-common/issues/528

**Comment by samreid** [comment]
Most of this was covered in https://github.com/phetsims/gas-properties/issues/170.  @pixelzoom anything else to do for this issue in particular?

**Comment by pixelzoom** [comment]
Nothing I can think of. Closing.
