### ISSUE TITLE
Buggy setters in EyeDropperNode.js

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#531]

**Comment by samreid** [comment]
@zepumph I thought you might be able to think of a good way to search for other occurrences of the same kind of bug, can you please take a look at the change set?

**Comment by zepumph** [comment]
Using a regex I basically looked for something like "zProperty = X" where x doesn't have "Property" or "null" in it. I see 31 matches but didn't really look at them. Good luck!

`\w+Property = ((?!(Property|null)).)*$`

**Comment by samreid** [comment]
I didn't see any bugs of the form identified in https://github.com/phetsims/scenery-phet/commit/efd3844aa1c113f598bacf8877983ecc905f0ad9, but there were some other minor issues, I'll create side issues and close this one.
