### ISSUE TITLE
assertion commented out in ArrowNode setTipAndTail

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#532]
Discovered in vector-addition while determining how to handle zero-magnitude vectors uniformly in ArrowNode and LineArrowNode.  High priority.

In https://github.com/phetsims/scenery-phet/commit/42eaa4ea82477ddf436b2675b278fd7297c27824, @samreid commented out this assertion in ArrowNode `setTailAndTip`:

```js
// assert && assert( !(tailX === tipX && tailY === tipY), 'arrow should have different tail and tip' );
```

@samreid what is your reason for commenting this out? Please either (a) remove the assertion entirely and document the expected behavior when tip === tail, or (b) restore the assertion.

**Comment by pixelzoom** [comment]
Block https://github.com/phetsims/vector-addition/issues/177.

**Comment by samreid** [comment]
That change was apparently made while working on Masses and Springs, probably related to https://github.com/phetsims/kite/issues/69.

I removed the assertion and updated the documentation to indicate no arrow is shown when tail===tip.

**Comment by pixelzoom** [comment]
👍 closing
