### ISSUE TITLE
add tailDash feature to ArrowNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#533]
Motivated by decisions in https://github.com/phetsims/vector-addition/issues/177#issuecomment-531876724.

* `tailDash` value will be similar to `SCENERY/Line` `lineDash`, e.g. `tailDash: [ 3, 2  ]`
* `ArrowNode` will continue to be a subclass of `Path`, described by a single `Shape`
* dash will be constructed from tail to tip, so that any partial dash (or space) is near the tip

**Comment by pixelzoom** [comment]
Ugh, this is getting really complicated. `ArrowNode` and `ArrowShape` are full of optimizations that assume that the Shape can be described as a reusable set of Vector2 instances. And that's not possible if the tail is dashed.  @ariel-phet FYI.

**Comment by pixelzoom** [comment]
Ugh, this is getting really complicated. ArrowNode and ArrowShape are full of optimizations that assume that the Shape can be described as a reusable set of Vector2 instances. And that's not possible if the tail is dashed. @ariel-phet FYI.

**Comment by pixelzoom** [comment]
Slack discussion:

Chris Malley 1:47 PM
I’ve been asked to add a tailDash option to ArrowNode, see https://github.com/phetsims/scenery-phet/issues/533.   I’ve discovered that the current implementation is very tightly coupled to describing the Shape as a reusable {Vector2[]}, which assumes a solid tail.  The documentation indicates that this is for performance reasons.  Does anyone recall which sims rely on this?

Jonathan Olson 1:48 PM
I think it's a general-performance thing (a lot of sims update arrows every frame), I don't recall the original sim that triggered those changes, but I know it's not specific to it

Chris Malley 1:49 PM
I don’t see how this optimization could be possible with a dashed tail. So it seems like my options are (1) add a totally separate code-path inside ArrowNode (and ArrowShape?) if options.tailDash is provided, or (2) roll my own VectorNode that is specific to vector-addition and supports solid and dashed tails.

Jonathan Olson 1:52 PM
I could conceive of other simulations wanting a dashed tail

Chris Malley 1:52 PM
Me too. That was the thinking in adding to ArrowNode.  But it’s turning into a major project.
And if sims are really relying on this optimization, will it be OK if there’s no optimization for dashed tails? The optimization is intended to reduce the number of Vector2 instances created, reusing instances. ArrowShape (and ArrowNode) currently assume that they can iterate over the {Vector2[]} as a set of Shape.lineTo calls.   For dashed tails, I was going down the path of using Shape.rect for the dash segments.

Jonathan Olson 1:57 PM
I agree it seems like a major project, but it also seems like one that would be useful for the future. I don't think there's any way around the optimization bit for dashed tails.

Chris Malley 1:58 PM
Please clarify - by “any way around” do you mean “no way to implement” or “we must support optimization” ?

Jonathan Olson 2:00 PM
I mean "it's untenable to use the same Vector2[] approach for dashed tails, so performance for dashed tails will always be worse"

**Comment by pixelzoom** [comment]
The conclusion of the above Slack conversation as to try creating `DashedArrowShape`, and use it instead of `ArrowShape` in `ArrowNode`, if option `tailDash`.

**Comment by pixelzoom** [comment]
I tried creating `DashedArrowShape`.  It was a horrible mess, and I bailed.  

This is not currently feasible to add to `ArrowNode`/`ArrowShape` or `LineArrowNode`.  If this is a feature that is generally needed by sims, then I recommend a complete redesign and reimplementation of `ArrowNode` - a major project.   That's not something that I currently have time/interest for.   So to address https://github.com/phetsims/vector-addition/issues/177, we'll need to incur some technical debt and do something sim-specific to move forward.

@ariel-phet back to you to decide what to do with this issue (close, defer,...)

**Comment by ariel-phet** [comment]
@pixelzoom I actually think a sim specific implementation is totally appropriate currently. We can wait until some recalcitrant designer (ie me) demands dashed arrows in another sim before making a general solution. I think what you will have done in Vector Addition will be informative to that general solution when it becomes desired.

This might also potentially be nice work for someone like @brandonLi8 in the future, to take on something that is heavy common code lifting with some architectural direction. 

Marking deferred currently.

**Comment by pixelzoom** [comment]
The original idea proved to be both too complicated and unnecessary.  And it's not clear what (if anything) should be done.   So closing this issue.  If a similar feature is needed in the future, we can revisit.

**Comment by brent-phet** [comment]
Reopening per Slack conversation for Photoelectric Effect:

Jesse Greenberg  [10:10 AM]
For the energy diagram: scenery-phet's ArrowNode does not support a line-dash on the tail.

LineArrowNode does. Is it OK if we use that one instead? Difference is that there is no fill on the arrow head. Context attached too. (edited) 
2 files 4 repliesJesse Greenberg  [10:12 AM]
If not, I see other sims are recreating their own arrow Nodes to draw a line dash.

Or, we can look into moving support for this into scenery-phet, reopening [add tailDash feature to ArrowNode · Issue #533 · phetsims/scenery-phet](https://github.com/phetsims/scenery-phet/issues/533)

Brett Fiedler  [11:20 AM]
I would be okay with trying out the LineArrow for all arrows

Jesse Greenberg  [12:09 PM]
Alright, thanks. That will be fast, if we don't like it we can upgrade later.

Kathy Perkins  [8:47 AM]
[@Brent Marcus](https://phetsims.slack.com/team/U04TT4WR2GH) - Can you add this to the common code improvements? I don't think it would take JO long to do.... it seems a bit odd that its there isn't equavalency in the common code between the two modes here.
