### ISSUE TITLE
bug in NumberControl.createLayoutFunction3 documentation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#535]
Looks like changes to `NumberControl.createLayoutFunction3` (possibly in https://github.com/phetsims/scenery-phet/issues/526?) introduced this documentation bug:

```js
537  titleLeftIndent: 0, // {number|null}  if provided, add an HStrut on the left of the title to push the title to the right
```

`HStrut` is no longer involved.

**Comment by zepumph** [comment]
Thanks for that. It looks like I committed it with incorrect doc back in https://github.com/phetsims/scenery-phet/commit/b043daf3a2eb0ef3fa65e1849a6eb3ba2acb149b. I updated it above.

**Comment by pixelzoom** [comment]
👍
