### ISSUE TITLE
polish fractionalHeadHeight code in ArrowShape

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#545]
Related to #544...

`ArrowShape` has this option:

```js
40 fractionalHeadHeight: 0.5 // head will be scaled when headHeight is greater than fractionalHeadHeight * arrow length
```

Here's the test for whether the condition described above is met, also in `ArrowShape`:

```js
107 if ( length < options.headHeight / options.fractionalHeadHeight ) {
```

The `if` expression here doesn't match the documentation description, and is consequently difficult to read.  It should be:

```js
107 if ( options.headHeight > options.fractionalHeadHeight * length ) {
```

**Comment by pixelzoom** [comment]
There were other issues here... Unclear doc, duplicated computation to maximum head height, ...   I've addressed these in the above commits. Tested with all sims that use `isHeadDynamic` and `fractionalHeadHeight` (gravity-and-orbits, trig-tour, vector-addition), no problems noted. 

@chrisklus randomly selected to sanity check. Please close if all looks well.

**Comment by chrisklus** [comment]
Code changes look good, closing.
