### ISSUE TITLE
Add way to get directional movement description from MovementDescriber

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#546]
Needed for interactive description work in molecules-and-light. MovementDescriber currently supports creating and alerting directional movement. But there isn't a way to get the description of direction outside an alert.

I am imagining statics like
MovementDescriber.getDirectionDescription( angle )

or

MovementDescriber.getDirectionDescription( pointA, pointB )

would be helpful.

**Comment by jessegreenberg** [comment]
@zepumph since you were original author would you mind reviewing this? Example usage is in `ObservationWindow.getEmissionPhaseDescription`

**Comment by zepumph** [comment]
I made a few changes, mainly combining the diagonal descriptions into the cardinal directions object. Please review.

**Comment by pixelzoom** [comment]
Assigned to @jessegreenberg for review for ~15 months. Raising priority to high. @jessegreenberg when can you get to this?

**Comment by jessegreenberg** [comment]
The three commits above look good.
