### ISSUE TITLE
Grab/Drag grabbableOptions.appendDescription: true by default

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#550]
While working on https://github.com/phetsims/scenery-phet/issues/536, it looks like every help text given to a grab/drag interaction wants to be appended, so I'll make that the default.

**Comment by zepumph** [comment]
@jessegreenberg please review the addition of this default.

**Comment by jessegreenberg** [comment]
Yep, this is a better default, thanks.
