### ISSUE TITLE
NumberControl options to exclude numberDisplay and titleNode

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#552]
Like https://github.com/phetsims/scenery-phet/issues/549

**Comment by pixelzoom** [comment]
I don't see the need for this.  You can provide a custom value for `options.layoutFunction` that simply ignores its `numberDisplay` argument. 

In any case, unless there's an actual request for this feature, I'd like to close this issue.  We can revisit if/when this feature is needed.

@zepumph is this feature currently needed somewhere?

**Comment by zepumph** [comment]
Not that I know of, but because of phet io, if it comes up, I likely won't be enough to just not show it, because it will still be instrumented. I'm good to close until we need it though.
