### ISSUE TITLE
StepForwardButton modifies options that it doesn't own

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#556]
I ran into this in natural-selection.  

```js
  function StepForwardButton( options ) {

    options = options || {};

    assert && assert( !options.direction, 'StepForwardButton sets direction' );
    options.direction = 'forward';
```

If the `options` arg is used elsewhere, this modifies it for other clients.  This one is my bad.

**Comment by pixelzoom** [comment]
Fixed in the above commit.  Tested in scenery-phet demo and gas-properties.

@ariel-phet please assign someone to review.

**Comment by Denz1994** [comment]
Nice catch. I went ahead and made a similar commit to `StepBackwardButton.js`. I checked cases of `new StepForwardButton` and `new StepBackwardButton` to make sure options weren't being set for the `direction` field. 

@pixelzoom If the above [commit](https://github.com/phetsims/scenery-phet/commit/454f005f72b2bcbedf8b523aa68969c82b88ec96) looks good, you can close.

**Comment by pixelzoom** [comment]
Good catch @Denz1994.  Looks good, closing.
