### ISSUE TITLE
Vector2.add( Vector3 ) in YawPitchModelViewTransform3

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#558]
In `YawPitchModelViewTransform3`:

```js
    modelToViewPosition( modelPoint ) {

      assert && assert( modelPoint instanceof Vector3,
        'modelPoint must be of type Vector3. Received ' + modelPoint );

75    scratchVector2.setPolar( modelPoint.z * Math.sin( this.pitch ), this.yaw ).add( modelPoint );
      return this.modelToViewTransform2D.transformPosition2( scratchVector2 );
    }
```
<br>

On line 75, the `add( modelPoint )` bit is problematic, because it's adding a `Vector3` to a `Vector2`.  Documentation for Vector2 `add` indicates that its argument must be `{Vector2}`.   So this is working because `add` doesn't type-check its args (which could change) and Vector2 and Vector3 both satisfy duck type `{x:number, y:number}`.
 
Unless you want to go down the rabbit hole of changing Vector2 to use duck typing and appropriate arg validation throughout...  I recommended changing `YawPitchModelViewTransform3` to:

 ```js
75    scratchVector2.setPolar( modelPoint.z * Math.sin( this.pitch ), this.yaw ).addXY( modelPoint.x, modelPoint.y );
```
<br>

Commit history is incomplete since this code was recently moved from capacitor-lab-basics to scenery-phet. The issue likely originated in the port of CLModelViewTransform3D.java to CLBModelViewTransform3D.js. I'll start by assigning to @samreid, who handled the move and some recent commits.

**Comment by pixelzoom** [comment]
Doc for `modelToViewPosition ` is also incorrect:

```js
    /**
     * Maps a point from 3D model coordinates to 2D view coordinates.
     * @public
     *
     * @param {Vector3} modelPoint
     * @returns {Vector3}
     */
```

It returns `{Vector2}`.

**Comment by samreid** [comment]
I made the changes recommended above, skimmed the file for other significant problems and tested in Capacitor Lab: Basics.  Back to @pixelzoom for review.

**Comment by pixelzoom** [comment]
👍 closing.
