### ISSUE TITLE
Create KeyboardHelpIconFactory

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#559]
From https://github.com/phetsims/molarity/issues/177, @jessegreenberg and I think it is best to move icon logic to its own place. There are three items to think through here:

- [x]  Move icon specific functions from KeyboardHelpSection.js to this new type
- [x] Over in https://github.com/phetsims/molarity/issues/177 and in other usages factor out commonly repeated, complex icons like "up and down arrows" or "enter and space key" This is really where this new type will benefit us.
- [ ] Decide how we want to factor out "simple" icons, like `new HomeKeyNode()`. I think it is best to instead use something like `KeyboardHelpIconFactory.home()`, but perhaps it is a lower/optional priority to convert all usages of simple keys to use this new pattern.
- [x] UPDATE while working: can any static constants be moved to the icon factory?

Right now, and what is blocking https://github.com/phetsims/molarity/issues/177, is only to create the four icons that that type needs. everything else is just lower priority refactoring. After that, I think the most important work here is the move KeyboardHelpSection methods over.

**Comment by zepumph** [comment]
I moved the icon specific creators out of `KeyboardHelpSection` above. 

Now the only methods in KeyboardHelpSection are:

* `labelWithIcon`
* `labelWithIconList`
* `createJumpKeyRow`
* `alignHelpSectionIcons`
* `getGrabReleaseHelpSection`

> Decide how we want to factor out "simple" icons, like new HomeKeyNode(). I think it is best to instead use something like KeyboardHelpIconFactory.home(), but perhaps it is a lower/optional priority to convert all usages of simple keys to use this new pattern.

I'm ambivalent, siding slightly on the side of doing nothing, and refactoring in the future if we feel it is easier. 


@jessegreenberg please review.

**Comment by pixelzoom** [comment]
Assigned to @jessegreenberg for review for 12+ months.  Raising priority to high.  @jessegreenberg when can you get to this?

**Comment by jessegreenberg** [comment]
Thanks @zepumph, this looks good.  The last checkbox
> Decide how we want to factor out "simple" icons

Has since been done.

Closing.
