### ISSUE TITLE
How should the StopwatchNode behave at large time values?

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#565]
From https://github.com/phetsims/gas-properties/issues/170, @pixelzoom said:

> There are a couple of things that I really don't like about StopwatchNode, issues that are rooted in TimerNode and TimerReadoutNode:
> 
> * The timer stops when it reaches a max. That behavior would be OK as an option (not sure when I'd want to use it) but it's unacceptable as the only behavior. Imo, a design flaw.

It's unclear what the alternative supported behavior(s) should be.  @pixelzoom can you please elaborate, or let me know if this should be discussed with designers?

**Comment by pixelzoom** [comment]
I'd prefer to see the time display scale down, or at least have the option to do so.  Having it just stop seems potentially confusing.   You probably want to also discuss with designers.

**Comment by samreid** [comment]
@arouinfar can you please recommend how to proceed for this issue?

**Comment by arouinfar** [comment]
I don't know the full history of TimerNode, so I'm not sure if it has always had a `maxValue`. In https://github.com/phetsims/wave-interference/issues/94 we made a decision about what to do when the `maxValue` is reached. We decided to stop the timer because that mirrors the experience of using the stopwatches typically found in classrooms. Also, there really isn't any pedagogical value in continuing to count up the time, as the typical `maxValue` (99:99.99 or 999.99) goes well beyond the useful timescales in the sim. The only people I would expect to reach the max time would be a QA tester or an extremely bored student with lots of time to kill.

I would not be opposed for adding an option to continue to count up the time, but I wouldn't make it the default behavior. I would also be unlikely to ever use such an option in a sim.

Any thoughts on this @ariel-phet?

**Comment by ariel-phet** [comment]
@arouinfar @pixelzoom @samreid 

I agree, it would be unlikely we would use this option. Usually we choose the time to be of a pedagogically useful scale, so allowing it to run on "ad infinitum" doesn't seem particularly useful (also couldn't that potentially cause a memory leak if the sim is used in something like a museum display or such?)

Can the `maxValue` just be set arbitrarily high? It does seem like some kind of cutoff is appropriate, but perhaps as @pixelzoom suggested things could scale down as it gets very large?

**Comment by pixelzoom** [comment]
@ariel-phet asked:
> also couldn't that potentially cause a memory leak if the sim is used in something like a museum display or such?)

`StopwatchNode` would cause no such leak, it does not use more resources over time.  A leak like that would be elsewhere in the code, unrelated to the discussion here.   Gas Properties for example could run forever without allocating more resources. 

> Can the `maxValue` just be set arbitrarily high? It does seem like some kind of cutoff is appropriate, but perhaps as @pixelzoom suggested things could scale down as it gets very large?

Yes, a very large `maxValue` could be chosen.  But again, why should we be limited to 2 inflexible formats for displaying time? 

Here's the `maxValue` option in `StopwatchNode`, where `DEFAULT_MAX_VALUE = 3599.99`:

```js
        // {number} the maximum time value, in seconds. The timer will stop when this value is reached.
        // When set to display time in minutes and seconds (the default for StopwatchReadoutNode),
        // the largest quantity that StopwatchNode can display is minutes, and the smallest is 1/100 second.
        // So the default maxValue is 59 minutes, 59.99 seconds, which is 1/100 second short of 1 hour.
        // See https://github.com/phetsims/masses-and-springs-basics/issues/36
        maxValue: DEFAULT_MAX_VALUE
```

Might want to fix that doc, btw.  Saying that "the default maxValue is 59 minutes, 59.99 seconds" is bogus. The time units are defined by the simulation, not `StopwatchNode`.   E.g. in Gas Properties, the units are ps -- do I really get 59 minutes, 59.99 seconds in that case? I think not. 

And if I want to display more than 59 minutes, 59.99 seconds, then why wouldn't I want to display that as HOURS, minutes, and seconds?

**Comment by pixelzoom** [comment]
We would not have designed a number display (NumberDisplay) that can only display a numeric value in only 1 or 2 formats, with 1 or 2 units.  Why is that approach acceptable for a time display (StopwatchNode)?

**Comment by ariel-phet** [comment]
Discussed with @pixelzoom, he is going to make some comments summarizing decisions and assign back to @samreid

**Comment by pixelzoom** [comment]
Discussed with @ariel-phet via Zoom on 6/17/2020.  

Summary:

* Agreed that being locked into 2 formats is not desirable for a general UI component
* Agreed that allowing the timer to run past `maxValue` should be an option.

Work to be done:

* Replace `StopwatchReadoutNode` with `NumberDisplay( ..., { useRichText: true } )`, sized for `maxValue`, and scale down the value text if it becomes wider than the NumberDisplay.
* Add an option to specify the readout format, provide some canned formats
* Add an option to specify whether the stopwatch should stop when it reaches `maxValue`, OK to default this to `true`.

**Comment by pixelzoom** [comment]
@ariel-phet said:
> Discussed with @pixelzoom, he is going to make some comments summarizing decisions and assign back to @samreid

Back to @samreid.

**Comment by samreid** [comment]
Can NumberDisplay format numbers like 61.0 as 1:01?  Or is that no longer part of the design?

**Comment by pixelzoom** [comment]
NumberDisplay doesn't currently have a general formatting option as part of its API.   The formatting is currently base on options `valuePattern` and `decimalPlaces`.   Relevant formatting code:

```js
    const valuePattern = ( value === null ) ? options.noValuePattern : options.valuePattern;
    const stringValue = valueToString( value, options.decimalPlaces, options.noValueString );
    const align = ( value === null ) ? options.noValueAlign : options.align;

    // update the value
    self.valueText.text = StringUtils.fillIn( valuePattern, {
      value: stringValue
    } );
```

That said, it's not trivial, but it shouldn't be too difficult to add more general formatting.  And there's already option `useRichText` to use either RichText or Text.

**Comment by samreid** [comment]
Are you recommending another option `formatter` which is a function that takes a number and returns a string?  Would it be mutually exclusive with either or both of `valuePattern` and/or `decimalPlaces`?

**Comment by pixelzoom** [comment]
Either a `formatter` option to NumberDisplay.  Or a new class named something like `RichNumberDisplay` or `FormattedNumberDisplay`.

**Comment by samreid** [comment]
Summarizing changes:

* Moved behavior of "when stopwatch reaches max time, pause the stopwatch" from the view to the model
* Specify stopwatch range via `Stopwatch.options.timePropertyOptions`
* Deleted StopwatchReadoutNode
* StopwatchNode now uses a `NumberDisplay` for showing its text.
* StopwatchNode provides a few defaults for converting number to text, with `getRichNumberFormatter` as the most powerful
* StopwatchNode scales down the value text if it becomes too wide (if the StopwatchNode.numberDisplayRange.max is smaller than the Stopwatch.timeProperty.range.max).
* Added tests to scenery-phet demo for "NumberDisplay"
* I did a side-by-side comparison to try to pixel-match the views, but couldn't get 100% accuracy.  Perhaps because the previous version used plain `Text` and a separate `Node` for units, and the new version uses `RichText` with styling for everything.
* Tested the following sims that use stopwatches, to match their "end of time behavior"
* I added `{{value}} {{units}}` as an internationalizable string, now translators will be able to specify how the units and time appear next to each other in the stopwatch readout (but it will default to {{value}} {{units}} if left untranslated).

```
capacitor lab: 	        pauses at 59:59.99.  fixed
cck: 	                not published, allowing to go past 59:59.99 and scale down until design finalized
esp: 	                pauses at 59:59.99. fixed
gas-properties:      pauses at 999.99 ps.  fixed
masses-and-springs:	pauses at 59:59.99. fixed
pendulum-lab:         pauses at 59:59.99. fixed
wave-interference:	pauses at 999.99.  fixed
wave-on-a-string:	pauses at 59:59.99. fixed
```

Gotchas/Questions
* When changing units, formatter or anything else related to the time display, we must trigger that text to update.  That can be done via `NumberDisplay.recomputeText` but developers could forget to call that.
* Right now the Stopwatch.timeProperty.range is independent from the range used to size the display.  I'm not sure if those should be combined or not.  What if you want to have the stopwatch stop at 1000.00 but have it start shrinking down after 99.99?  So those are decoupled right now, but it leaves the opportunity for unintended mismatch.
* The NumberDisplay seems a little "jittery" or "jumpy" at times.  That was a problem we strove to fix in the old version of `StopwatchReadoutNode` but I'm seeing it here for `NumberDisplay`.  Not sure what is causing it or how important it is to fix.  It's somewhat rare and you have to be looking for it.
* Now that it is trivial to allow the stopwatch to go beyond 59:59.00 and have it scale down, will we want to prefer that in the design?  Will we want to change that for any of the sims mentioned above?
* These are significant changes and I recommend to mark as blocks-publication until review is complete.

**Comment by pixelzoom** [comment]
7/16/20 dev meeting:   I said that I won't be able to get to this until the week of 7/20.  @ariel-phet said that should be fine.

**Comment by pixelzoom** [comment]
I haven't gotten to reviewing this yet.  But I did want to note that I'm using NumberDisplay's new `formatter` option in fourier-making-waves, where it's working nicely.

**Comment by pixelzoom** [comment]
Mentioned at 7/30/20 dev meeting.  I'm aware of this issue, but it's at the bottom of my priority list.  It will likely remain there until some sim that has a StopwatchNode needs to create a release branch.

**Comment by pixelzoom** [comment]
Mentioned at 8/6/20 dev meeting. Still on my list, still not a priority.

**Comment by pixelzoom** [comment]
This looks really great, thanks for tacking this big issue.

> Summarizing changes:

The only thing I see here is StopwatchNode option `stopwatchNumberDisplayOptions`.  While I appreciate the “searchability” argument, this violates our naming convention for nested options, and makes this API more difficult to use.  So let's rename this to `numberDisplayOptions`.  

> Gotchas/Questions
>
> When changing units, formatter or anything else related to the time display, we must trigger that text to update. That can be done via `NumberDisplay.recomputeText` but developers could forget to call that.

This requirement for `NumberDisplay.recomputeText` (and `StopwatchNode.redrawNumberDisplay` it appears) is not acceptable, and violates a general pattern: if mutating an attribute requires an update, then that attribute should be private, mutation should be done via a setter, and the setter should handle the update.  This should be addressed.

> Right now the Stopwatch.timeProperty.range is independent from the range used to size the display.  ...

I wouldn't worry about this for now. 

> The NumberDisplay seems a little "jittery" or "jumpy" at times.  ...

I haven't seen this.  Does it occur on specific browsers?  Let's open a separate issue.

> Now that it is trivial to allow the stopwatch to go beyond 59:59.00 and have it scale down, will we want to prefer that in the design? Will we want to change that for any of the sims mentioned above?

I've opened phetsims/gas-properties#188 to review the use of new features in Gas Properties. Recommended to do the same for other sims, or at least notify the designers that these options are now available. 

Back to @samreid.

**Comment by samreid** [comment]
I addressed one of the issues here and will open side issues for the remaining things.  Please review the changes for the options rename.  When that is complete, this issue can be closed.  See you in the other issues!

**Comment by pixelzoom** [comment]
`numberDisplayOptions` change 88ee763 looks good.  Closing.
