### ISSUE TITLE
Generalize StopwatchReadoutNode

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#566]
From https://github.com/phetsims/gas-properties/issues/170#issuecomment-528394405 @pixelzoom said:

> There are a couple of things that I really don't like about StopwatchNode, issues that are rooted in TimerNode and TimerReadoutNode:
> 
> The value display is not general. It can only show "HH:MM:SS" or a value to 2 decimal places. For example, if I wanted to show only "5 ps" or "5.3 ps" (which would have been nice) in Gas Properties, then I'm out of luck. This smells like something that was sim-specific and not properly generalized.

I see one NOTE related to this in the code:

```js
// NOTE: If we need more flexibility for this part, consider inversion of control (i.e. client passing in an alternate Node)
const stopwatchReadoutNode = new StopwatchReadoutNode( stopwatch.timeProperty, options.stopwatchReadoutNodeOptions );
```

@pixelzoom were you envisioning more options and features in StopwatchReadoutNode, or the ability to override the StopwatchReadoutNode with any client-supplied Node?

**Comment by pixelzoom** [comment]
I don't see why StopwatchNode should be locked into "HH:MM:SS" or a value to 2 decimal places.   Why 2 decimal places, why not 1 or 3?  Smells like sim-specific code to me.  

StopwatchReadoutNode also seems unnecessary.  Why can't we use NumberDisplay here?  Time is just a number, with some client-specific formatting.

So... Why not provide a formatting function, like we do for NumberDisplay and NumberControl?

**Comment by samreid** [comment]
This was previously asked in https://github.com/phetsims/scenery-phet/issues/372#issuecomment-419196541 and answered in https://github.com/phetsims/scenery-phet/issues/372#issuecomment-421681294.  The answer included this text:

> This wouldn't work out of the box because TimerNode was requested to have some digits large and some digits small, like this: [...] . We could revisit that decision?

@pixelzoom is there a better implementation strategy that keeps some digits large and some small?  Want to reassign to discuss with a designer whether that feature is necessary?

**Comment by pixelzoom** [comment]
I've never understood the motivation for requiring some digits to be smaller.  I think it would be an OK _option_ (and might be supported via RichText) but certainly not as the only way to show time.  And certainly not requiring 2 decimal places.  Both the smaller digits and 2 decimal places seemed totally uncalled for in Gas Properties, but that's what we were stuck with (and I still cringe whenever I use the stopwatch).

Imo this read out is very inflexible and forces some bizarre requirements on all sims that use it.  I would vote to change it, but will defer that decision to designers.

**Comment by samreid** [comment]
@arouinfar what do you think?

**Comment by arouinfar** [comment]
> I don't see why StopwatchNode should be locked into "HH:MM:SS" or a value to 2 decimal places. Why 2 decimal places, why not 1 or 3? Smells like sim-specific code to me.

Agreed, this was likely sim-specific. I think 2 decimals would be a reasonable default, but I could see wanting to display a different number of decimals (or potentially none at all).

> I've never understood the motivation for requiring some digits to be smaller. I think it would be an OK option (and might be supported via RichText) but certainly not as the only way to show time.

I was not around for the original design of TimerNode, but I believe the motivation was for the seconds and milliseconds to be more visually distinct from one another. This design choice is not uncommon, and is used in the Android stopwatch. 
<img src="https://user-images.githubusercontent.com/8419308/71632465-ee9f6380-2bcb-11ea-973c-77d39e2cbfaa.png" width=150>

My vote would be to keep this as-is, but assigning to @ariel-phet for input.

**Comment by ariel-phet** [comment]
@pixelzoom @samreid @arouinfar 

I would be fine with this node being more general. I do agree with the default design being the smaller numbers, this was a very intentional design choice to mimic the general stop watch designs seen on phones (and old digital stopwatches).

However, I agree, this form of display could be an option with option to display time in other styles (and number of decimal places and such).

I certainly do not have an issue with the current stopwatch in Gas Properities, and we have received no complaints, but given how often we use this component, making it more flexible does seem wise.

**Comment by pixelzoom** [comment]
Other problems with `StopwatchReadoutNode`....

It uses hard-coded separators ':' and '.', making translation problematic:

```js
184    return minutes + ':' + seconds;
200    return '.' + centitime;
```

It requires 2 Text nodes (`bigReadoutText` and `smallReadoutText`) and some conditional logic to implement "big" and "small" numbers.    It would be much simpler and more flexible to use a single RichText node.  For example:

```js
new RichText( '<span style="font-size: 20px;">2</span><span style="font-size: 15px;">.34</span>' );
```

... looks identical to the default font sizes used by `StopwatchReadoutNode`:

<img width="77" alt="screenshot_48" src="https://user-images.githubusercontent.com/3046552/71855916-979fff80-309f-11ea-9bed-3cb0de31b3f4.png">

... and could be easily factored out into a pattern that could be filled in by `StringUtils.fillIn`.

**Comment by samreid** [comment]
I followed that prescribed strategy in https://github.com/phetsims/scenery-phet/issues/565 and it is pending review.  Let's close this as duplicate.
