### ISSUE TITLE
Instrument HeaterCoolerNode

### ISSUE THREAD

**Issue by chrisklus** [phetsims/scenery-phet#568]
HeaterCoolerNode needs to be instrumented to satisfy required tandems (since it has a slider) in EFAC (as well as Gas Properties and soon SOM).

@kathy-phet and @arouinfar said to keep it simple, so only the Node itself and the slider need to be instrumented.

I've been digging into this for a bit, and it's not clear to me yet what's the best way to handle the HeaterCoolerFront and HeaterCoolerBack situation. It seems undesirable to have both appear in Studio, regardless of whether they are nested under a parent like HeaterCoolerNode or not (they are part of HeaterCoolerNode in Gas Props and SOM but EFAC adds HeaterCoolerFront and HeaterCoolerBack separately from the screen view, with no use of HeaterCoolerNode).

In use cases like EFAC, the client (screen view) might have to be responsible for passing the state of HeaterCoolerFront Node Properties to HeaterCoolerBack (as HeaterCoolerNode would do for its children).

Here's a patch to have the illusion of one Node in Studio with just a slider child. The client would pass in a tandem name like `heaterCoolerNode` regardless of whether they are using HeaterCoolerFront or HeaterCoolerNode.

EDIT: patch updated again and pushed below 

Assigning to @arouinfar to comment on the appearance of HeaterCoolerNode in Studio and @samreid for further brainstorming.

**Comment by chrisklus** [comment]
I went again a committed some working changes to be reviewed by @samreid. @arouinfar could you take a look at EFAC Studio on master and see what you think?

**Comment by samreid** [comment]
What about instrumenting just the front, say, and wiring the back's visibility up to the front.  Like:

```js
frontNode.on('visible',visible=>{backNode.visible=visible;});
```

That way we don't need to create a middle adapter layer?

**Comment by chrisklus** [comment]
>That way we don't need to create a middle adapter layer?

I'm not sure what you mean by this.

>What about instrumenting just the front, say, and wiring the back's visibility up to the front.

That's what I was attempting to do - and HeaterCoolerFront is managing that wiring so it's not duplicated, and is the only file that gets a tandem. Call sites using HeaterCoolerNode look like this:

```js
const heaterCoolerNode = new HeaterCoolerNode( property, {
  frontOptions: {
    tandem: tandem.createTandem( 'heaterCoolerNode' )
  }
} );
```

and call sites with separate HeaterCoolerFront and HeaterCoolerBack look like this:

```js
const heaterCoolerBack = new HeaterCoolerBack( property );
const heaterCoolerFront = new HeaterCoolerFront( property, {
  heaterCoolerBack: heaterCoolerBack,
  tandem: tandem.createTandem( 'heaterCoolerNode' )
} );
```

**Comment by samreid** [comment]
You are absolutely right, sorry I misread the change set.  This strategy looks great.

**Comment by samreid** [comment]
In the course of this issue, we added code to Gas Properties to leverage the new instrumentation for HeaterCoolerNode.  @pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
(1) HeaterCoolerNode should be `tandem: Tandem:REQUIRED`.  See (2).

(2) Why was  `GasPropertiesHeaterCoolerNode` instrumented in https://github.com/phetsims/gas-properties/commit/0cd2a6c34d1e4b874859e0e8a0c25bde86c34a7f?  It previously was not instrumented - intentionally, and for very good reasons.  Depending on the "Hold Constant" selection, the HeaterCoolerNode is either under control of the user or the model.  So under no circumstances should the PhET-iO client be controlling the HeaterCoolerNode directly. 

(3) I agree that it's undesirable to expose the front/back pieces of HeaterCoolerNode in PhET-iO. It should appear as one Node.   Does the current implementation accomplished that goal?

**Comment by pixelzoom** [comment]
(1) HeaterCoolerNode should not be `tandem: Tandem:REQUIRED`.  See (2).

(2) Why was  `GasPropertiesHeaterCoolerNode` instrumented in https://github.com/phetsims/gas-properties/commit/0cd2a6c34d1e4b874859e0e8a0c25bde86c34a7f?  It previously was not instrumented - intentionally, and for very good reasons.  Depending on the "Hold Constant" selection, the HeaterCoolerNode is either under control of the user or the model.  So under no circumstances should the PhET-iO client be controlling the HeaterCoolerNode directly. 

(3) It took me several tries to grok this comment in .  Why not just say "privateHeatCoolAmountProperty" instead of "the private implementation-detail Property which is supplied to the slider to support animation." ?

```js
// Link to the corresponding model property, not the private implementation-detail Property which is supplied to
// the slider to support animation.
```

(4) I agree that it's undesirable to expose the front/back pieces of HeaterCoolerNode in PhET-iO. It should appear as one Node.   Does the current implementation accomplished that goal?

**Comment by chrisklus** [comment]
>(1) HeaterCoolerNode should not be tandem: Tandem:REQUIRED. See (2).

Sliders are `Tandem.REQUIRED` so that the data stream is not missing user input events, so HeaterCoolerNode needs to be `Tandem.REQUIRED` as well to meet this requirement.

>(2) Why was GasPropertiesHeaterCoolerNode instrumented in phetsims/gas-properties@0cd2a6c? It previously was not instrumented - intentionally, and for very good reasons. Depending on the "Hold Constant" selection, the HeaterCoolerNode is either under control of the user or the model. So under no circumstances should the PhET-iO client be controlling the HeaterCoolerNode directly.

Before HeaterCoolerNode was instrumented, its slider was part of the list of missing required tandems from `?phetioPrintMissingTandems`, so instrumenting it reduced that list for Gas Properties. As you noticed in (3), we linked the (already instrumented) model Property instead of exposing `privateHeatCoolAmountProperty`. So phet-io clients have no more control over HeaterCoolerNode's value than they did before since the slider just links to the Property that's read-only:

![image](https://user-images.githubusercontent.com/5618316/71837130-ad073080-3083-11ea-9917-0aa76a8f54e4.png)

>(3) It took me several tries to grok this comment in GasPropertiesHeaterCoolerNode. Why not just say "privateHeatCoolAmountProperty" instead of "the private implementation-detail Property which is supplied to the slider to support animation." ?

Good point, thanks. I updated the comment.

>(4) I agree that it's undesirable to expose the front/back pieces of HeaterCoolerNode in PhET-iO. It should appear as one Node. Does the current implementation accomplished that goal?

It does indeed - it looks the same in Studio whether HeaterCoolerNode is being used (Gas Properties) or HeaterCoolerFront and HeaterCoolerBack are being used separately (EFAC).

**Comment by pixelzoom** [comment]
> Sliders are Tandem.REQUIRED so that the data stream is not missing user input events, so HeaterCoolerNode needs to be Tandem.REQUIRED as well to meet this requirement.
> ...
> So phet-io clients have no more control over HeaterCoolerNode's value than they did before since the slider just links to the Property that's read-only:

Gas Properties instrumentation is by no means completed; it's a work in progress that has been "paused".  That said...

The Property in question is `this.heatCoolFactorProperty` in IdealGasLawModel.  It is not read-only, it is `phetioStudioControl: false`.   So unless the designers decide otherwise, `phetioReadOnly: true` should be added.  The alternative is to add some complicated `phetioDocumentation` about when this can be client-controlled, and allow the client to possibly blow up the sim.

**Comment by chrisklus** [comment]
>The Property in question is `this.heatCoolFactorProperty` in IdealGasLawModel.  It is not read-only, it is `phetioStudioControl: false`.

Oh right, thanks. Un-assigning until we hear from @arouinfar.

**Comment by chrisklus** [comment]
From 01/16/2020 SOM design meeting:

A phet-io client would like to be able to leverage the sticky vs snappiness that HeaterCoolerNode supports. I'm going to wrap the `snapToZero` option with a BooleanProperty to accomplish this.

We'd also like to adjust this (phet-brand) option so that when it's off (and the slider stays wherever you leave it), there is still a threshold close to zero where it will snap to zero. This will prevent users from never being able to return the heat/cool to zero, which is how the behavior currently is when `snapToZero` is false.

**Comment by arouinfar** [comment]
I reviewed the HeaterCoolerNode in EFAC in studio with @kathy-phet, and the structure in the tree looks good to us. 

> The Property in question is this.heatCoolFactorProperty in IdealGasLawModel. It is not read-only, it is phetioStudioControl: false. So unless the designers decide otherwise, phetioReadOnly: true should be added. 

Generally, we think this phetioReadOnly should be `false` by default, and it could be set to `true` in the overrides on a sim-by-sim basis (which is what we'd do in GasProps on the screen with the Hold Constant options).

> We'd also like to adjust this (phet-brand) option so that when it's off (and the slider stays wherever you leave it), there is still a threshold close to zero where it will snap to zero. 

Sounds good. We think a good threshold value for `snapToZero` would be +/-5%.

**Comment by chrisklus** [comment]
Implemented in the above commit. @arouinfar I only added the snapping threshold when both heating and cooling are enabled, as when testing the changes, I was reminded that it was not hard to return the slider to zero when only one or the other is being used (like EFAC tea kettle). Could you review the behavior and `snapToZeroProperty` in Studio?

@pixelzoom will you review my changes? I kept the option `snapToZero` as a boolean, and then created a BooleanProperty in the constructor, as I didn't see a reason to follow our `enabledProperty` pattern of allowing a BooleanProperty to be passed in. I also made the Property private for the same reason of this not seeming useful for phet brand.

**Comment by pixelzoom** [comment]
Yep, I can review.  But I'm going to wait until @arouinfar has verified the behavior.

**Comment by arouinfar** [comment]
> I only added the snapping threshold when both heating and cooling are enabled, as when testing the changes, I was reminded that it was not hard to return the slider to zero when only one or the other is being used (like EFAC tea kettle).

👍 

@chrisklus playing with the HeaterCoolerNodes in EFAC, we notice that a threshold of +/-5% is perhaps too small. The slider track isn't very big to begin with, so 5% isn't that much distance from zero. Could you bump up the default threshold to +/-10%? Is this something that could be changed on a sim-by-sim basis if in the future there is some sim with a giant HeaterCoolerNode?

**Comment by arouinfar** [comment]
@chrisklus can you also make the heatCoolLevelProperty featured by default?

**Comment by kathy-phet** [comment]
> @chrisklus can you also make the heatCoolLevelProperty featured by default?
Related to this, we are not sure if "heatCoolLevelProperty" is in the common code, or in the sim? We noticed it had a different name on the second screen. So maybe it is not really possible to make it "featured by default" as part of common code? We would love some insight here.

**Comment by arouinfar** [comment]
@chrisklus we'd also like to feature `snapToZeroProperty` in HeaterCoolerNode, so we're not always overriding it.

**Comment by chrisklus** [comment]
Updates committed above. `snapToZeroProperty` is phet-io featured and the default threshold for snapping to zero has been increased to +/-10%.

>Could you bump up the default threshold to +/-10%? Is this something that could be changed on a sim-by-sim basis if in the future there is some sim with a giant HeaterCoolerNode?

Yes, I made it into an option, though I'm not crazy about it as an option until it's actually needed. I'll let @pixelzoom weigh in here. I do like that it's documented in the options block instead of a random constant in the middle of the file.

> @chrisklus can you also make the heatCoolLevelProperty featured by default?
>Related to this, we are not sure if "heatCoolLevelProperty" is in the common code, or in the sim? We noticed it had a different name on the second screen. So maybe it is not really possible to make it "featured by default" as part of common code? We would love some insight here. 

Right, the Property is not owned by HeaterCoolerNode so there is no way to feature it by default.

**Comment by pixelzoom** [comment]
`snapToZeroThreshold` seems fine as an option, and you did a nice job of documenting it in HeaterCoolerFront.

**Comment by pixelzoom** [comment]
@chrisklus Assuming that this is now ready for review, can you please summarize what needs to be reviewed?  There's a lot of stuff in this issue...

**Comment by pixelzoom** [comment]
@chrisklus Assuming that this is now ready for review, can you please summarize what needs to be reviewed?  Or point me to the relevant comments and commits? There's a lot of stuff in this issue...

**Comment by chrisklus** [comment]
Indeed - just the addition/usages of `snapToZeroProperty` and `options.snapToZeroThreshold`. Relevant code is in https://github.com/phetsims/scenery-phet/commit/f1ea483614bf28d696002dba9b08956f8bd564ee and https://github.com/phetsims/scenery-phet/commit/f16939149ccce7bc761771a6acd48df1b282b564. Thanks!

**Comment by pixelzoom** [comment]
I reviewed those options and related commits, looks nice.  Since `snapToZeroThreshold` is presumably a value between 0 and 1, I would add an assert to verify immediate after the `merge` call.  I'm also not entirely clear on whether 0 or 1 would have any special constraints/behavior, so that might be worth mentioning.  I'm guessing that 1 always snaps, and 0 behaves the same as `snapToZero: false`.

**Comment by chrisklus** [comment]
>Since `snapToZeroThreshold` is presumably a value between 0 and 1, I would add an assert to verify immediate after the `merge` call.

Nice, thanks. Added above.

>I'm guessing that 1 always snaps, and 0 behaves the same as `snapToZero: false`.

Right - I added a comment to explain those cases. Note that 0 behaves the same as the *former* `snapToZero: false` state because this option is used only when `snapToZero` is `false`. Let me know if that isn't clear enough in the docs.

**Comment by pixelzoom** [comment]
👍 closing.

**Comment by zepumph** [comment]
Instrumenting the HeaterCoolerFront as the HeaterCoolerNode caused this bug: https://github.com/phetsims/studio/issues/148, and also made it very challenging to debug.

I wasn't the lead dev on this issue, but do you think that a patch like this could work instead? Then we could add an api to HeaterCoolerNodeIO to make sure that everything works as expected. 

The main issue with the above is that the visibility/opacity Properties now only apply to the front. 

<details>

```diff
Index: js/HeaterCoolerFront.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/HeaterCoolerFront.js	(revision 5c0826794e0346460d9bc1b42c70c3b5cc6c3f2c)
+++ js/HeaterCoolerFront.js	(date 1592524264003)
@@ -176,7 +176,7 @@
     this.addChild( stoveBody );
     this.addChild( this.slider );
 
-    this.mutate( options );
+    this.mutate( _.omit( options, ['tandem'] ) );
 
     // update the back component if provided
     if ( options.heaterCoolerBack ) {
Index: js/HeaterCoolerNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/HeaterCoolerNode.js	(revision 5c0826794e0346460d9bc1b42c70c3b5cc6c3f2c)
+++ js/HeaterCoolerNode.js	(date 1592520919630)
@@ -75,15 +75,9 @@
     this.slider = heaterCoolerFront.slider;
 
     assert && assert( !options.children, 'HeaterCoolerNode sets children' );
-    options.children = [ heaterCoolerBack, heaterCoolerFront ];
+    options.children = [heaterCoolerBack, heaterCoolerFront];
 
-    super.mutate( merge( {}, options, {
-
-      // Do not propagate options.tandem to super because HeaterCoolerFront is the only part of HeaterCoolerNode that's
-      // instrumented, so it will pass the same Tandem to super instead.
-      // See https://github.com/phetsims/scenery-phet/issues/579
-      tandem: Tandem.OPTIONAL
-    } ) );
+    this.mutate( options );
 
     // @public Dispose function used for GC
     this.disposeHeaterCoolerNode = function() {

```
</details>

**Comment by zepumph** [comment]
I would also like to add that the following is very strange:

```

const x = new HeaterCoolerNode( . . . )
x.isPhetioInstrumented() -> false
x.opacity = .5;

// on the  client
phetioClient.invoke( 'heaterCoolerNode.opacityProperty', 'get', [], opacity=> /*opacity is not .5 */);
```

**Comment by chrisklus** [comment]
@zepumph, @samreid and I discussed today and committed a fix over in https://github.com/phetsims/studio/issues/148. We added a flag to HeaterCoolerFront that can be set to false so HeaterCoolerFront is not instrumented. This allows HeaterCoolerNode to be the instrumented node when it's used instead of just its child HeaterCoolerFront. This fixes the strangeness above. Thanks @zepumph, closing.
