### ISSUE TITLE
Add "or group" to help content descriptions when withGroupContent:true

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#570]
From https://github.com/phetsims/gravity-force-lab/issues/214#issuecomment-570013622, this will be best in common code. Basically the description currently is:

'Move to next item with Tab key.' 

but if we have group content @terracoda recommends it to be:

'Move to next item or group with Tab key.'

**Comment by zepumph** [comment]
@jessegreenberg  in the above commit I refactored how "or group" was added to the general help section. I like having a single string that optionally adds the "or group" substring when needed. It feels nicer the me than upwards of 4 duplicated strings with minor additions.

The main weirdness I would like to discuss is how I am manually inputing a space for the `{{space}}` templating variable. This is a strategy that was brainstormed with @twant with some molarity a11y strings (though I can't find the issue) but didn't end up implementing there. I'm wondering how offensive it is to you to see how the "space" is filled in. Again this is to support the fact that translatable strings are trimmed of white space (and there is an assertion for it now too). This doesn't bother me too much, but it also may be a tip-toe around the real problem. Thoughts?

As a side note, please ignore the TODO I added here, as it will be covered over in https://github.com/phetsims/chipper/issues/798.

**Comment by zepumph** [comment]
Marking high priority because it is blocking GFL publication.

**Comment by jessegreenberg** [comment]
I like that this substring is factored out, but the fillIn with space does seem tricky. This kind of things seems like it could be useful for many strings. I am thinking of two alternatives, which you may have considered:
- What if the string pattern were `'Move to next {{items}} with Tab key.'` with possible values of `'item'`, `'item or group'`?
- Maybe we add a `StringUtils.stripOut` that *removes* certain values from the template string? I could see this being a useful operation generally for a11y. I guess we could be left with surrounding spaces, but maybe the util function could be smart enough to turn resultant `'  '` into `' '`?

```js
StringUtils.stripOut( 'Move to next item {{orGroup}} with Tab key.', [ 'orGroup' ] );
```
returns `'Move to next item with Tab key.'`

**Comment by zepumph** [comment]
>What if the string pattern were 'Move to next {{items}} with Tab key.' with possible values of 'item', 'item or group'?

Yes I agree, in general it is always possible to get rid of the trailing/leading space by duplicating some part of a string. I don't like this as a general solution though.

>but maybe the util function could be smart enough to turn resultant ' ' into ' '?

This feel really like the problem that we are trying to solve, as "stripOut" can be accomplished by `fillIn` if you pass it an empty string. Perhaps a `StringUtils` function could help us with stripping duplicated spaces, but I worry a bit about us making too many assumptions in code, and running into barriers around i18n. I know that `{[space}}` isn't ideal, but it is at least obvious what it is doing, and can be manipulated at "translation time" rather than obfuscated into the code usages at run time. 

I also don't want us to forget about the fact that all of this is to get around an assertion about trailing and leading spaces in strings which we came up with. Perhaps there is cause to revert that in the general case to support a11y strings. 

1. Do you think that this issue should block GFL publication (does anything NEED to change)?
2. What is your running favorite for a general solution?

**Comment by jessegreenberg** [comment]
Agreed, sounds like a StringUtils function would be more trouble than it is worth.

> Do you think that this issue should block GFL publication (does anything NEED to change)?

Since this may require changing a translatable string (`keyboardHelpDialog.orGroup`), I think it would be ideal to resolve before publication.

> What is your running favorite for a general solution?

I think we are trading duplication for complexity in code and for translators since this requires string patterns that lack spaces which look a bit strange like
`'Move to next item{{orGroup}} with Tab key.`' and `'{{space}}or group'`

In order of preference my favorites are
- Use a string pattern that duplicates some of the substring but doesn't require inserting a space. I think this avoids duplication where possible, but is still clear for translators and code.
- Live with duplication of the full string, I think that is also clear in the code and for the translator.

**Comment by zepumph** [comment]
Thanks for your recommendations. I think for this specific case I will proceed with the solution that uses a small amount of duplication, not the whole string. 

Moving past this, can you recommend for a general solution? I feel like duplication will not do as a pattern to be used everywhere. Maybe that's for a different issue.

**Comment by jessegreenberg** [comment]
I am not sure that a more general solution is needed here. Duplication of a few words in translated strings feels acceptable to me and a more general solution for this would involve removing spaces from strings or other things that seem problematic for i18n.

**Comment by zepumph** [comment]
After discussing with @jessegreenberg and @jbphet, we feel like the duplication is the best way to make sure that translation is still straight forward and simple. I updated the strings relating to the `{{orGroup}}` pattern and feel good about those changes.

When double checking that `{{orGroup}}` wasn't anywhere else in the project I found https://github.com/phetsims/babel/commit/25208b69584ca4c4fdb59b88f538b2089890b5d5, which was a translation done on Friday. @jbphet can you please explain what is happening here? This string was only on master, so I'm confused how it is now in babel as a translated string value. I feel like this is likely a bug, so I'm going to assign this over to @jbphet with the following questions. How did this string from master get checked into babel? How did rosetta pull from master? The only sims that would use these strings are sims with keyboard nav, and the latest one to be published was GFLB last fall. Any thoughts?

**Comment by zepumph** [comment]
UPDATE:

I found that the about dialog on the latest version of GFLB is from last Friday:
![image](https://user-images.githubusercontent.com/6856943/72450568-0e578f80-3767-11ea-8487-932a5af385b4.png)

So perhaps GFLB is the culprit somehow.

**Comment by jbphet** [comment]
> @jbphet can you please explain what is happening here?

Absolutely.  Common code strings are extracted from master when translating, otherwise we'd have to have a complex system of branching and merging in order to handle the translation of common strings.  This approach definitely has some down sides, and there is an issue at https://github.com/phetsims/rosetta/issues/219 about it.

The bottom line is that what you're seeing makes sense given the current operation of Rosetta, and we should be very careful not to experiment with common code strings on master.  I would suggest manually reverting this change to the string for the given translation.

**Comment by zepumph** [comment]
I'm quite surprised to see this, and I think @jessegreenberg will be too. Thanks for letting me know, and sorry for any trouble I caused. 

> I would suggest manually reverting this change to the string for the given translation.

- [ ] Is this something for me to do or is it best for you to do? I have no idea how I would go about doing so.

- [ ] What documentation currently exists to encapsulate this, as I feel like it is incredibly dangerous to keep things as is without at least a discussion at a dev meeting. I'm not suggesting changing rosetta, but instead wanting to try to educate all devs (and new devs) about this current constraint to i18n.

**Comment by jbphet** [comment]
@zepumph said, in reference to manually reverting the translations of {{orGroup}}:

>  Is this something for me to do or is it best for you to do? I have no idea how I would go about doing so.

I went ahead and did this, the commit should be linked above, you're welcome to take a look if you're interested.  I removed both the value and the history entry of the change.

@zepumph also said:

>  What documentation currently exists to encapsulate this, as I feel like it is incredibly dangerous to keep things as is without at least a discussion at a dev meeting. I'm not suggesting changing rosetta, but instead wanting to try to educate all devs (and new devs) about this current constraint to i18n.

There is a little information about it in the Rosetta "implementation-notes" document, but not a lot.  I'm not at all opposed to spending some time on this aspect of Rosetta to make it more robust, but it has served us reasonably well so far and just hasn't been a priority yet.  Bringing it up in dev meeting would be fine with me in the short term.

**Comment by zepumph** [comment]
@jbphet thank you for https://github.com/phetsims/babel/commit/d670601f5a0130683818e56c01070dce40dad205. 

I think that a dev meeting PSA/checkin sounds nice. I don't think that rosetta needs to change in any large way, I just feel like this is a pretty important aspect of i18n that has completely fallen through the cracks of my PhET education. I wouldn't want it to do so to others in the future. Marking for dev meeting and removing priority list.

**Comment by samreid** [comment]
I read through this issue, but was unclear on the takeaway message, aside from common code strings coming from master (which I was previously unaware of).  I'm looking forward to the PSA/checkin!

**Comment by jonathanolson** [comment]
Clarification of the PSA would be good. I know I'm very hesitant to delete strings anywhere, but I forget the exact reasons.

**Comment by chrisklus** [comment]
From dev meeting 4/4/20:

We talked about this as a PSA that both keys and values of common code strings is dangerous. Marking as high priority so we can discuss more next dev meeting since this one is ending now!

**Comment by jonathanolson** [comment]
Dev meeting decision: @jbphet will add documentation about this to Rosetta.

**Comment by jbphet** [comment]
I'm removing the high-priority label.  I think it was marked as such for the dev meeting.

**Comment by jessegreenberg** [comment]
Also removing dev meeting label after we discussed on https://github.com/phetsims/scenery-phet/issues/570#issuecomment-611681781

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/scenery-phet/issues/570#issuecomment-611681781, the remaining task appears to be "add documentation about this to Rosetta".   Since that was 10 months ago, I'm creating phetsims/rosetta#260 and closing this issue.
