### ISSUE TITLE
is ZoomButton over-instrumented?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#573]
Related to https://github.com/phetsims/ph-scale/issues (ph-scale instrumentation).

`ZoomButton` is a common-code UI component.  Here's what it looks like in ph-scale. There are 2 of them below the linear graph in the _Macro_ screen:

<img width="407" alt="screenshot_86" src="https://user-images.githubusercontent.com/3046552/73689357-4ded0980-468b-11ea-971f-b92d1151216f.png">

Here's the Studio tree structure for one of those ZoomButtons:

<img width="219" alt="screenshot_87" src="https://user-images.githubusercontent.com/3046552/73689447-7b39b780-468b-11ea-8076-d3042699c72e.png">

This looks over-instrumented to me, perhaps vestigial from the "instrument everything" days of PhET-iO.  Why are we instrumenting the parts of the icon (`glassNode`, `signNode`) separately?  If instrumenting the icon is important, why isn't the icon (as a whole) instrumented? 

I recommend that we remove instrumentation of the icon, and make the instrumentation similar to ResetAllButton and other push buttons, i.e.:

<img width="202" alt="screenshot_88" src="https://user-images.githubusercontent.com/3046552/73689620-dcfa2180-468b-11ea-9518-cfa91818a9a1.png">

(EDIT: Note that `isFiringProperty` is specific to ResetAllButton. According to the doc, it's "Commonly used to disable audio effects during reset".)
 
Assigning to PhET-iO designers to review.  If someone from the PhET-iO dev team knows why the icon is instrumented this way, please chime in.

**Comment by samreid** [comment]
I agree, it seems like a symptom of the instrument everything approach, and those extraneous instrumentations should be removed.

**Comment by pixelzoom** [comment]
@arouinfar or @kathy-phet if you agree, I'll proceed with removing instrumentation of the icon.

**Comment by pixelzoom** [comment]
Not only is this over-instrumented, but the instrumentation is incorrect, and was probably not tested.  If I set `glassNode.visibleProperty` to `false`, it looks like the screenshot below.  Only part of the magnifying glass disappears.   Since this is not at all useful, I have to believe that it's buggy.

<img width="283" alt="screenshot_89" src="https://user-images.githubusercontent.com/3046552/73690242-28f99600-468d-11ea-9053-76f1ca060baf.png">

**Comment by arouinfar** [comment]
It's definitely over instrumented @pixelzoom. I see no reason why the icon would be instrumented, rather than the button as a whole.

**Comment by pixelzoom** [comment]
Thanks @arouinfar.  I'll proceed which changes.

**Comment by pixelzoom** [comment]
Changed completed, and API files update in the above commits.  Here's what the Studio tree looks like for ph-scale.  This is identical to ResetAllButton.

<img width="186" alt="screenshot_90" src="https://user-images.githubusercontent.com/3046552/73694998-78908f80-4696-11ea-89ad-3cc38884e17e.png">

**Comment by pixelzoom** [comment]
@arouinfar could you please verify in [ph-scale 1.4.0-dev.5](https://phet-dev.colorado.edu/html/ph-scale/1.4.0-dev.5/phet-io/) ?

In Studio, navigate to `phScale.microScreen.view.graphNode.linearGraphNode.zoomButtonGroup.zoomInButton` and inspect the structure.  It should match what is shown in https://github.com/phetsims/scenery-phet/issues/573#issuecomment-581641191.   If all looks well, please close.

**Comment by arouinfar** [comment]
Looks wonderful @pixelzoom
