### ISSUE TITLE
Add a RewindButton to TimeControlNode?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#574]
From https://github.com/phetsims/gravity-and-orbits/issues/294 - Sim has a RewindButton in its time controls and so they look like this.
![image](https://user-images.githubusercontent.com/6396244/73796893-83bdeb00-477c-11ea-8609-9110b45125ba.png)

Im not sure if it is worth the complexity to add to TimeControlNode. The RewindButton requires custom logic for its enabled/disabled state and so we would need to add a way for the client to control this. We might

- Add option `includeRewindButton` to TimeControlNode, which adds the button.
- The RewindButton would be the left most button, left of the PlayPauseButton or left of a StepBackwardButton if it is included.
- Add a function to control enabled state of RewindButton, `setRewindButtonEnabled( boolean )`

Assigning to @pixelzoom @Denz1994 and @jonathanolson (original authors), do you have a recommendation?

**Comment by pixelzoom** [comment]
If you think RewindButton is generally useful, you could add it to TimeControlNode.  Or you could decorate a TimeControlNode and leave it to the next person who needs a RewindButton. 

That said... I question how we're going about adding features to TimeControlNode.  It might be time to take as step back and attempt to design something that meets the needs of all sims, rather than continuing to bolt on things to meet the immediate needs of specific sims.

**Comment by terracoda** [comment]
I would agree with @pixelzoom, I was just saying to @jessegreenberg in the MAL Interactive Design doc that the Timing Controls widget could be quite complex from an interaction and description perspective as well. If we redesign this group control we should really consider its A11y representation as well.

**Comment by jessegreenberg** [comment]
It sounds like we need to rethink this control a bit. Since we started using TimeControlNode in sims, two buttons have needed to be added to TimeControlNode, and it seems likely that more will be needed.

The review work would look something like
1) Review sims that could still use TimeControlNode and find other things that are missing.
2) Reconsider what TimeControlNode should include once we understand what is missing.
3) Review with the design team to make sure it includes everything we can think of.
4) Description design for this control.
4) Potential implementation changes.

This issue has come up for gravity-and-orbits (PhET-iO) and molecules-and-light (a11y). This is taking more time than anticipated, so @ariel-phet and @emily-phet can we spend time on this issue now? It would save us time in the long run.

**Comment by pixelzoom** [comment]
Issue to (re)design TimeControlNode: https://github.com/phetsims/scenery-phet/issues/575

**Comment by jessegreenberg** [comment]
Thanks for reviewing, we are going to collapse this into #575 so closing this issue.

**Comment by emily-phet** [comment]
@jessegreenberg A few potential paths forward come to mind:
- Holding a couple of ad hoc design meetings at the end of status meeting in February or in March - this option potentially best if we think we can accomplish the design side of this in a few conversations, and dev work would not delay rocks for this quarter. This also may be reasonable given that we seem to be trying to follow as much as possible standard video player conventions, narrowing the design space some. @terracoda please weigh in regarding your availability for involvement - perhaps considering this option for March might work best for you?
- Holding off on this until next quarter (so we can plan in some dedicated effort without jeopardizing this quarter's goals) - may be the best option if need is relatively urgent, but seems likely that working on this now will puts accomplishing Q1 rocks at risk
- Holding off until potentially Fall 2020 or Spring 2021 - we could incorporate this into work on one of the Adaptive Sims features related to timing control. @jessegreenberg recall we once spoke about considering the creation of a timing control bar that could be added to any sim that contains animated/dynamic action.

Thoughts, or other options for moving forward?

**Comment by jessegreenberg** [comment]
Thanks for reviewing @emily-phet, Im going to move your comment to #575
