### ISSUE TITLE
(re)design TimeControlNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#575]
Over in https://github.com/phetsims/scenery-phet/issues/574, there was a proposal to add yet-another feature to TimeControlNode, in order to meet the needs of a specific sim. 

In https://github.com/phetsims/scenery-phet/issues/574#issuecomment-582178503, I said:
> I question how we're going about adding features to TimeControlNode. It might be time to take as step back and attempt to design something that meets the needs of all sims, rather than continuing to bolt on things to meet the immediate needs of specific sims.

In https://github.com/phetsims/scenery-phet/issues/574#issuecomment-582443088, @terracoda said:
> I would agree with @pixelzoom, I was just saying to @jessegreenberg in the MAL Interactive Design doc that the Timing Controls widget could be quite complex from an interaction and description perspective as well. If we redesign this group control we should really consider its A11y representation as well.

**Comment by pixelzoom** [comment]
There a bunch of sims that are apparently not using TimeControl.  So the first step in a (re)design of TimeControlNode would be to identify all current sims that should be using it, to see what their needs are. 

One obvious discrepancy is the radio button group for controlling speed.  `TimeControl` currently provides 2 buttons labeled "Slow" and "Normal", and it looks like this:

<img width="248" alt="screenshot_94" src="https://user-images.githubusercontent.com/3046552/73853213-beac3700-47ed-11ea-94f4-4ba9636eae57.png">

SOM and Bending Light use "Slow Motion". "Normal" is on the bottom in SOM, on the top in Bending Light.  And they both put the radio buttons to the left of the push buttons:

<img width="315" alt="screenshot_96" src="https://user-images.githubusercontent.com/3046552/73853351-f4512000-47ed-11ea-95bb-23f91caf26d6.png">
<img width="325" alt="screenshot_95" src="https://user-images.githubusercontent.com/3046552/73853345-f1562f80-47ed-11ea-81cc-a4f98fdf1620.png">
 
And I also seem to recall at least one sim that has 3 speeds (Slow, Normal, Fast)?

**Comment by pixelzoom** [comment]
I'll start by assigning this to @jessegreenberg and @ariel-phet, to determine how to proceed.

**Comment by jessegreenberg** [comment]
Issues related to this have come up for gravity-and-orbits (PhET-iO) and molecules-and-light (a11y). @ariel-phet and @emily-phet can we spend time on this issue now? Going through this review would save us time in the long run so I think we should do it.

**Comment by jessegreenberg** [comment]
In the last few weeks two buttons have been requested for TimeControlNode, a RewindButton and a StebBackwardButton. Issues: https://github.com/phetsims/scenery-phet/issues/574 and https://github.com/phetsims/scenery-phet/issues/563

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/scenery-phet/issues/574#issuecomment-582461714 @emily-phet said

@jessegreenberg A few potential paths forward come to mind:
- Holding a couple of ad hoc design meetings at the end of status meeting in February or in March - this option potentially best if we think we can accomplish the design side of this in a few conversations, and dev work would not delay rocks for this quarter. This also may be reasonable given that we seem to be trying to follow as much as possible standard video player conventions, narrowing the design space some. @terracoda please weigh in regarding your availability for involvement - perhaps considering this option for March might work best for you?
- Holding off on this until next quarter (so we can plan in some dedicated effort without jeopardizing this quarter's goals) - may be the best option if need is relatively urgent, but seems likely that working on this now will puts accomplishing Q1 rocks at risk
- Holding off until potentially Fall 2020 or Spring 2021 - we could incorporate this into work on one of the Adaptive Sims features related to timing control. @jessegreenberg recall we once spoke about considering the creation of a timing control bar that could be added to any sim that contains animated/dynamic action.

Thoughts, or other options for moving forward?

**Comment by emily-phet** [comment]
However TimeControlNode evolves, let's document in Binder, since it seems like we'll be developing design conventions for when certain attributes of time control are used!

**Comment by jessegreenberg** [comment]
This is taking more time than anticipated but is not a huge amount of work. It would be best to do this sooner rather than later as TimeControlNode is used in more sims and we design description for the control for molecules-and-light. Reviewing usages may be the most time intensive part and can be done outside of meeting time.

**Comment by emily-phet** [comment]
@jessegreenberg Can you list here the total number of sims with timer control? or are there some HTML5 sims with pause/play etc that don't use time control?

**Comment by jessegreenberg** [comment]
We did a search for that in https://github.com/phetsims/scenery-phet/issues/561.

_List of sims that use TimeControlNode:_
bending-light
capacitor-lab-basics
energy-forms-and-changes
energy-forms-and-changes
energy-skate-park
gas-properties
gene-expression-essentials
gene-expression-essentials
masses-and-springs
molecules-and-light
natural-selection
neuron
projectile-motion
wave-on-a-string

_List of sims that would benefit from using it:_
states-of-matter
bending-light
collision-lab
color-vision
fluid-pressure-and-flow
forces-and-motion-basics
gravity-and-orbits
models-of-the-hydrogen-atom
pendulum-lab
rutherford-scattering

**Comment by kathy-phet** [comment]
@emily-phet - There was another issue for unifying to TimeControlNode across simulations so all sims with play/pause are on that common code base and can leverage any work done in the common code on PhET-iO or accessibility. This lists that sims that have play/pause.
https://github.com/phetsims/scenery-phet/issues/561

Ahh -- Jesse listed that just now. Of the sims that he says "would benefit from it", the following will be converted to it this spring/summer for PhET-iO: 
states-of-matter
bending-light
force-and-motion-basics
gravity-and-orbits
pendulum-lab

**Comment by ariel-phet** [comment]
@jessegreenberg it certainly seems reasonable to me to spend time on this work in the near future, but it looks like there are some constraints, so on the time frame question I will defer to @emily-phet 

As for TimeControlNode itself I would the following initial design suggestions:

1. I think we can certainly standardize to Normal and Slow (and remove Slow Motion) for simplicity and consistency

2. We probably need to have the option for "fast" but it should not be the default. There have been some cases we have wanted to have this option. In fact, I believe EFAC used to have it, but it caused some sim specific model/performance issues so we abandon it. But that desire will likely occur in some other future sims. I don't have a strong preference of order, but I would be fine with Normal, then Slow, then Fast 

3. I unfortunately do not think we can constrain the radio buttons to be on the left or the right, we will probably want the ability to have them on either side. Depending on sim layout, it is nice to have this flexibility since we often try to center the play/pause/step group in some way under a viewing area or such. I could see having the radio buttons being on one side or the other being advantageous in certain cases.

4. It seems a bit overwhelming to have a play/pause, step forward, step backward, and a rewind all at once. It seems the default should be play/pause and a step forward button (as that combination appears in many sims). Perhaps we could the option for either a step backward or a rewind button, but not be able to have both of those at once. Having three buttons max in the control group seems ideal to me, but this seems like a good point of discussion for design meeting time.

**Comment by pixelzoom** [comment]
While we're adding a rewind button, should we add a fast-forward button?

**Comment by arouinfar** [comment]
I generally agree with @ariel-phet's https://github.com/phetsims/scenery-phet/issues/575#issuecomment-582775698

> 2. We probably need to have the option for "fast" but it should not be the default. There have been some cases we have wanted to have this option. In fact, I believe EFAC used to have it, but it caused some sim specific model/performance issues so we abandon it. But that desire will likely occur in some other future sims. I don't have a strong preference of order, but I would be fine with Normal, then Slow, then Fast

"Fast Forward" currently exists in Gravity and Orbits & Neuron. I would agree that this could be simplified to "Fast", but we're currently arranging the radio options in decreasing order of playback speed which seems more natural to me.
![image](https://user-images.githubusercontent.com/8419308/73963586-d35ffc00-48cd-11ea-9ef1-e164f3682ee6.png)

> 4. It seems a bit overwhelming to have a play/pause, step forward, step backward, and a rewind all at once. It seems the default should be play/pause and a step forward button (as that combination appears in many sims). Perhaps we could the option for either a step backward or a rewind button, but not be able to have both of those at once. Having three buttons max in the control group seems ideal to me, but this seems like a good point of discussion for design meeting time.

I am very hesitant to generalize the rewind button and add it to TimeControlNode, because it has very sim-specific functionality. As far as I know, the only sim that uses a "rewind" button is Gravity and Orbits, and it's not truly a rewind button. Pressing "rewind" returns the configuration of the bodies to the starting state.  It is often redundant with the scene reset button, unless an experiment has been set up when the sim was paused.

@pixelzoom said:
> While we're adding a rewind button, should we add a fast-forward button?

Frankly, I wouldn't have either of these buttons in TimeControlNode. Holding down the step buttons will animate in the desired direction, which would meet the goal.

**Comment by pixelzoom** [comment]
> "Fast Forward" currently exists in Gravity and Orbits & Neuron. I would agree that this could be simplified to "Fast", but we're currently arranging the radio options in decreasing order of playback speed which seems more natural to me. ...

"Fast Forward" is not a sim speed, it's an action when moving through a timeline, recorded data, etc.   

> Frankly, I wouldn't have either of these buttons in TimeControlNode. Holding down the step buttons will animate in the desired direction, which would meet the goal.

That sounds great to me.  But that apparently wasn't the case for design in phetsims/gravity-and-orbits#294 .

**Comment by pixelzoom** [comment]
Yet-another design, from Normal Modes (see https://github.com/phetsims/normal-modes/issues/42).    It's not clear whether the slider is necessary here or could be replaced with radio buttons. 

<img width="232" alt="screenshot_111" src="https://user-images.githubusercontent.com/3046552/74186770-6ec3da80-4c08-11ea-9f6c-8be8fe9eac46.png">

**Comment by arouinfar** [comment]
@pixelzoom we do not use sliders for sim speed in HTML5 sims. It will be replaced with radio buttons.

**Comment by jonathanolson** [comment]
Using centralized common code for general time controls for simulations (and gaining consistency when possible) sounds great to me.

**Comment by Denz1994** [comment]
As a part of item 2 in https://github.com/phetsims/scenery-phet/issues/575#issuecomment-582453559
> 2. Review with the design team to make sure it includes everything we can think of.

We should consider flexibility for layouts to accommodate the various sims cases above, similar to how layout functions are handled by `NumberControl.options.layoutFunction`. This is in line with standardizing how we organize the main components of `TimeControlNode.

**Comment by pixelzoom** [comment]
@Denz1994 said:
> We should consider flexibility for layouts to accommodate the various sims cases above, similar to how layout functions are handled by `NumberControl.options.layoutFunction`.  ...

I don't think that degree of flexibility is needed here, and is in fact undesirable - it has been a continual source of cost/complication for `NumberControl`. It would preferable to have a standard layout, unless there's a very compelling reason not to do so.  That said...  The order of the buttons is "industry standard", so I don't think we need the flexiblilty to reorder the buttons.  So the only other layout issue (currently) is where the speed radio buttons should be located.  Because the strings have different lengths, I think the best place for these buttons into the right of the buttons.  If we really do need to have an option to place radio buttons, that can be done through a specific option, and doesn't require the complexity of a layoutFunction option.

**Comment by samreid** [comment]
I agree that we should begin by favoring consistency/simplicity over flexibility.

> Normal, then Slow, then Fast

It seems the best user experience would be to put Normal between Slow and Fast.  To me it seems most natural that speed increases as you move down the list:

* Slow
* Normal
* Fast

**Comment by pixelzoom** [comment]
Re, the radio buttons, here's a suggestion....

Create an enumeration for the possible speeds:

`const TimeControlSpeeds = Enumeration.byKeys( [ 'FAST', 'NORMAL', 'SLOW' )`

Then in TimeControlNode:

```js
options = merge( {

   // {TimeControlSpeeds[]|null} create radio buttons for the indicated speeds, null means no buttons
  speedRadioButtons: [ ],
  ...
}, options );

// validate speedRadioButtons
if ( options.speedRadioButtons !== null ) {
  assert && assert( options.speedRadioButtons.length === 2, 'must have at least 2 speed radio buttons' );
  assert && assert( _.every( options.speedRadioButtons, speed => TimeControlSpeeds.includes( speed ), 'invalid speedRadioButtons' );
} 
```

This would handle all possible combinations of 'Fast', 'Normal', 'Slow', and 'no radio buttons'.  It would also make it easy to add additional speeds, if they are needed in the future.

**Comment by emily-phet** [comment]
My takeaways from the above thread, to help with discussion later today.
- Buttons: Play/Pause/Step Forward (most common set), Rewind (GAO & Neuron only), Step Backward (consideration), Fast Forward (consideration)
- Speed Radio Buttons: Open questions around labels and standard order, and supporting flexibility of location. What about supporting flexibility of presence/absence of which radio buttons are present, and possibly the ordering of these?

**Comment by jessegreenberg** [comment]
From discussion today:

The collection of buttons will include StepBackwardButton, PlayPauseStepButton, and StepForwardButton. The radio buttons will be optionally included and could include combinations of "Fast", "Normal" and "Slow" radio buttons. (https://github.com/phetsims/scenery-phet/issues/575#issuecomment-585492444 looks like a good way to do this). It is important to support different horizontal ordering of push buttons and radio buttons. Sometimes the push buttons should be on the left, sometimes the radio buttons should be on the left. The organization in studio should look something like
```
TimeControlNode
  PlayPauseStepButtons
    StepBackButton
    PlayPauseButton
    StepForwardButton
  PlaySpeedRadioButtonGroup 
    Fast radio button
    Normal radio button
    Slow radio button
```

The RewindButton will not be included in these controls. And during meeting it was suggested that it be renamed to RestartButton.

**Comment by jessegreenberg** [comment]
Proposal for changes was made in the above commit to a branch timeControlNodeWIP. This includes pretty large API changes so it would be really helpful to get another developer to review before this is used in sims.

Summary of changes:
 - Added `TimeControlSpeeds` Enumeration to define the supported speeds of TimeControlNode.
   - Added option `timeControlSpeeds` to specify speeds for a given TimeControlNode AND the order they will appear in the RadioButtonGroup. This is an array of TimeControlSpeeds.
    - Added timeControlSpeedProperty option, which is the Property for the AquaRadioButtonGroup. If this is null, radio button  group is included. 
 - Created inner types SpeedRadioButtonGroup and PlayPauseStepButtons to support structure  of  https://github.com/phetsims/scenery-phet/issues/575#issuecomment-586017904
 - Added a couple layout options to support layouts identified in https://github.com/phetsims/scenery-phet/issues/575#issuecomment-582451946

**Comment by jessegreenberg** [comment]
@ariel-phet can you please assign a developer to review?

**Comment by ariel-phet** [comment]
@jessegreenberg considering the list of sims that use this node and those that could benefit from it, @jbphet seems like a good candidate to review.

My impression was that moving this work forward was a higher priority for @emily-phet so I will defer the priority of the review to her.

**Comment by emily-phet** [comment]
@jessegreenberg Up to you - please incorporate this in as it makes sense in the flow of MAL progress.

**Comment by jessegreenberg** [comment]
Sounds good. @jbphet could you please review the proposal in https://github.com/phetsims/scenery-phet/commit/6e547916d26847f0183e8c9733c7c8303016a2a2 before I apply to master and change the API? This diff is prior to es6 modules change, sorry.

**Comment by samreid** [comment]
This would also be good to do in the next few days so it can be incorporated in the next version of Gravity and Orbits.  Let me know if @jbphet doesn't have time to get to it soon and I can take a look.

**Comment by jbphet** [comment]
Overall it looks good and it will be nice to have a solid common-code component for this.

I wasn't sure whether to review master and/or the branch, so I ended up doing both.  There are REVIEW comments on both, thought I think several of the ones on master have been addressed in the branch.

Also, for the master version (I couldn't easily test this on the branch) it looks like the radio buttons get smaller for long strings, see below.  Generally I think we try to avoid this, see the Gas Properties screenshot below this one that depicts the same test without the shrunken radio buttons.

![image](https://user-images.githubusercontent.com/3082831/76360410-9038e480-62e2-11ea-84cb-f16f263d78dc.png)

![image](https://user-images.githubusercontent.com/3082831/76361500-c37c7300-62e4-11ea-8b03-618a9ba162d0.png)

**Comment by pixelzoom** [comment]
> Also, for the master version (I couldn't easily test this on the branch) it looks like the radio buttons get smaller for long strings, see below. Generally I think we try to avoid this, see the Gas Properties screenshot below this one that depicts the same test without the shrunken radio buttons.

Indeed, `maxWidth` should not be set on radio buttons. It should be set on their labels.   The specific problem in this case is at line 164:

```js
      const radioButtonGroupOptions = merge( {
        radioButtonOptions: radioButtonOptions,
        spacing: 9,
        touchAreaXDilation: 10,
164     maxWidth: 150,
```

`maxWidth` should not be set here. It should be set in the options for `normalText` and `slowText`.   If 150 is indeed the limit, then you'll want to reduce that by `radioButtonOptions.xSpacing + ( 2 * radioButtonOptions.radius )`.

**Comment by pixelzoom** [comment]
This also appears to be a problem:

`157        radius: normalText.height / 2.2`

I believe that the PhET standard is to make radio buttons the same height as their labels, not slightly smaller.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/models-of-the-hydrogen-atom/issues/20 is another issue that needs this, bumping to top priority for me.

**Comment by pixelzoom** [comment]
@jessegreenberg Definitely not high-priority for phetsims/models-of-the-hydrogen-atom#20.

**Comment by jessegreenberg** [comment]
Thanks for reviewing @jbphet. The above commits address your review comments, merge changes with master, update usages in sims after API changes.

I also addressed the i18n review comments in https://github.com/phetsims/scenery-phet/issues/575#issuecomment-597346071 and https://github.com/phetsims/scenery-phet/issues/575#issuecomment-597350889. I moved a default `maxWidth` to the radio button label Node. The result of small radio buttons is still there however because of our decision to make the radio buttons the same height as their labels.

**Comment by jessegreenberg** [comment]
I forgot that one more item for this is to rename RewindButton to RestartButton, I will do that now.

**Comment by pixelzoom** [comment]
> The result of small radio buttons is still there however because of our decision to make the radio buttons the same height as their labels.

This is not correct.  PhET radio buttons and checkboxes are supposed to have the same height as their _non-scaled_ labels.  Radio buttons and checkboxes are not supposed to scale - only their text labels are supposed to scale.

**Comment by pixelzoom** [comment]
Demonstration of incorrect use of `maxWidth` in published version of Acid-Base Solutions:

<img width="362" alt="screenshot_199" src="https://user-images.githubusercontent.com/3046552/76881021-27032500-683e-11ea-8649-95ebe90c71bf.png">

Demonstration of correct use of _maxWidth_ in master:

<img width="343" alt="screenshot_198" src="https://user-images.githubusercontent.com/3046552/76881052-32565080-683e-11ea-9f77-f2513d5248ef.png">

**Comment by jessegreenberg** [comment]
Over slack @pixelzoom recommended that to accomplish https://github.com/phetsims/scenery-phet/issues/575#issuecomment-600181929 (radio button height matches label Node height before i18n scaling) to use a test Text, like 

```js
        // by default, radio buttons match height of label before maxWidth scaling adjustments
        radius: new Text( 'test', options.labelOptions ).height / 2
```

That was done in https://github.com/phetsims/scenery-phet/commit/dc419ed9003d857c725ffa5ddea8cfe6cfa9d290

**Comment by jessegreenberg** [comment]
OK, that completes review work. @jbphet would you like to spot check changes or is there anything else to do for this issue?

**Comment by jbphet** [comment]
I did a quick look through the file and tested the strings in SOM, and it looks fine to me.  Let's call it good, at least for now.  Closing.

**Comment by samreid** [comment]
Some improvements being made as part of https://github.com/phetsims/gravity-and-orbits/issues/294

**Comment by pixelzoom** [comment]
Reopening.  @jessegreenberg I still see branch 'timeControlNodeWIP'.  Has that been merged to master? If so, can it be deleted and its associated issue closed?

**Comment by jessegreenberg** [comment]
Thanks, branch was merged and has now been deleted. #582 can be closed as well.

**Comment by pixelzoom** [comment]
Reopening.  

Over in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/20, I converted MOTHA to use TimeControlNode.   There a couple of improvements that I'd like to recommend, name changes.

I ended up with these options for MOTHA:

```js
{
      timeControlSpeedProperty: model.timeSpeedProperty,
      timeControlSpeeds: [ TimeControlSpeed.FAST, TimeControlSpeed.NORMAL, TimeControlSpeed.SLOW ],
      speedRadioButtonGroupOptions: {
        labelOptions: {
          font: new PhetFont( 14 ),
          fill: 'white'
        }
      }
    }
```

In the model,  the Property for time speed would typically be named `timeSpeedProperty`, not `timeControlSpeedProperty`, like this:

```js
this.timeSpeedProperty = new EnumerationProperty( TimeControlSpeed, TimeControlSpeed.NORMAL );
```

It is independent of the control (view), in keeping with MVC may in fact be associated with more than 1 view.  

If my model Property is named `timeSpeedProperty`, I find it odd (of the same reasons) for the enumeration to be named `TimeControlSpeed`.   

Finally, there are 6 options related to "time speed". The API would be easier to understand if (a) those options were grouped together in the code, and (b) if they add used a similar name, either "speed" or "timeSpeed". 

So my suggestions are:

- [ ] rename `TimeControlSpeed` to `TimeSpeed`
- [ ] rename option `timeControlSpeedProperty` to `timeSpeedProperty`
- [ ] rename option `timeControlSpeeds` to `timeSpeeds`
- [ ] use consistent naming for options related to "time speed"

Happy to discuss any of these further, and feel free to push back.

**Comment by pixelzoom** [comment]
Ah... Maybe you're thinking of "time control" as the model and TimeControlNode as a view of that model?   If that's the case, maybe get a second opinion.

**Comment by samreid** [comment]
For https://github.com/phetsims/wave-interference/issues/500, I would like to position the TimeControlNode so that the PlayPauseButton is in the middle of the area.  To accomplish this, I'll generalize `getPlayPauseButtonCenter` to `getPlayPauseButtonBounds` so we may use its bounds.

**Comment by samreid** [comment]
On second thought, I can use `setPlayPauseButtonCenter`

**Comment by pixelzoom** [comment]
It looks like some (?) of the recommendations in https://github.com/phetsims/scenery-phet/issues/575#issuecomment-602847669 were done in the above commits, but the checklist items were not checked off.  And now this issue has been stalled out over 10 months.  

@jessegreenberg what do we need to do to wrap this up?

**Comment by jessegreenberg** [comment]
It looks like the recommendations from https://github.com/phetsims/scenery-phet/issues/575#issuecomment-602847669 were done and reviewed in https://github.com/phetsims/scenery-phet/issues/604 (thanks!).
The three above commits are showing up on 4/21/21 because they were done using copy-history-to-different-repo.sh when we moved molecules-and-light code into greenhouse-effect in https://github.com/phetsims/greenhouse-effect/issues/19 on that date, and that's why github is showing my profile pic twice for them
![image](https://user-images.githubusercontent.com/6396244/132927693-57b9bd6c-7a6b-4bdb-99cc-3de0e6d1a5eb.png)

So I think this can be closed.

**Comment by pixelzoom** [comment]
👍🏻 closing
