### ISSUE TITLE
TimeControlNode phetioFeatured defaults

### ISSUE THREAD

**Issue by arouinfar** [phetsims/scenery-phet#577]
Somewhat related to #575 

TimeControlNode appears in many sims, but the decisions around phetioFeatured are unlikely to change sim-by-sim. It would be nice if the top-level enabledProperty and visibleProperty could be phetioFeatured by default. 

However, speaking with @chrisklus, it's not entirely clear if the enabledProperty could/should be featured within TimeControlNode itself. A sim can pass in its own enabledProperty, but most usages are not using this option according to CK. I would be interested to hear what the other devs think about this.

There isn't a need to do anything for the individual components within TimeControlNode, since buttons already have the desired phetioFeatured behavior and VerticalAquaRadioButton group is being handled in https://github.com/phetsims/sun/issues/564.

Assigning to the PhET-iO team.

**Comment by zepumph** [comment]
> A sim can pass in its own enabledProperty, but most usages are not using this option according to CK. I would be interested to hear what the other devs think about this.

This is the same sort of behavior as we have to Checkboxes and Sliders. What we have done elsewhere, if you want the enabledProperty featured, is to assert that if you pass in your own, that it then best be featured (if you know what's good for you).  Would you like us to do that for this here too?

**Comment by arouinfar** [comment]
> Would you like us to do that for this here too?

Thanks @zepumph. This sounds like a common pattern, so yes, let's do the same for TimeControlNode.

**Comment by arouinfar** [comment]
@samreid took care of this in https://github.com/phetsims/scenery-phet/commit/bd61227693afaf93a4d58e3b6f7de235f52a85e2

I reviewed this in the context of https://github.com/phetsims/gravity-and-orbits/issues/294 and it looks good. Anything else for this issue @samreid?

**Comment by samreid** [comment]
Thanks @arouinfar, @chrisklus or @zepumph can you please review the implementation?

**Comment by chrisklus** [comment]
Looks good to me! And looks like this was already reviewed by @zepumph in https://github.com/phetsims/sun/issues/564, too.

**Comment by samreid** [comment]
Sounds good, thanks! Closing.
