### ISSUE TITLE
Should StepButton use the StepForwardButton sound?

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#578]
From today's Waves Intro design meeting: Should StepButton use the StepForwardButton sound?  It seemed preferable and @jbphet suspects that StepButton is just using the default button sound.

**Comment by jbphet** [comment]
I went ahead and moved the step-forward sound into the `StepButton` type, since it does indeed seem like a better default value than the stock push button sound.  Seems like an improvement.  Closing.
