### ISSUE TITLE
branch: timeControlNodeWIP

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#582]
@jessegreenberg is this the branch that you're using for #575?

**Comment by jessegreenberg** [comment]
Correct, thanks for the issue.

**Comment by jessegreenberg** [comment]
This branch was merged into master and has now been deleted.

**Comment by pixelzoom** [comment]
Due to https://github.com/phetsims/special-ops/issues/196#issuecomment-823486502, this branch was restored.  It will need to be deleted again.  Reopening and self assigning.

**Comment by pixelzoom** [comment]
Re-deleted using GitHub UI.  Closing.
