### ISSUE TITLE
TODOs in ThermometerNode.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#585]
For https://github.com/phetsims/tasks/issues/1017

TODOs by @samreid in ThermometerNode.js:

```
  const bulbFluidDiameter = options.bulbDiameter - options.lineWidth - options.glassThickness; //TODO should this be options.lineWidth/2 ?

  const tubeFluidWidth = options.tubeWidth - options.lineWidth - options.glassThickness; //TODO should this be options.lineWidth/2 ?

  const clipBulbRadius = ( options.bulbDiameter - options.lineWidth - options.glassThickness ) / 2; //TODO should this be options.lineWidth/2 ?

  //TODO this can exceed max/min. should this be clamped? or should it be replaced by dot.Utils.linear?
```

**Comment by samreid** [comment]
TODO created in 1fb52300c084134bedc45015b2629e372a35384b by @pixelzoom, reassigning.

**Comment by pixelzoom** [comment]
One was indeed added by me in https://github.com/phetsims/scenery-phet/commit/1fb52300c084134bedc45015b2629e372a35384b. Looks like the other were added by me in https://github.com/phetsims/scenery-phet/commit/9ec5a6a89680e9bc6d06b334834f1e7a595b5bf7.  All related to reviewing the previous developers' implementation.

**Comment by pixelzoom** [comment]
TODOs have been addressed. Closing.
