### ISSUE TITLE
bad assertion in OutsideBackgroundNode.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#586]
For phetsims/tasks#1017

In OutsideBackgroundNode.js:

```js
  // parameter checking
  //TODO commenting out this assert, there is no options.skyHeight and height is not declared
//    assert && assert( options.skyHeight < height );
```

I added this TODO and commented out the assertion to fix a lint error.  The lint error was introduced in https://github.com/phetsims/scenery-phet/commit/1261880ef3522c750f0138b5c5571468313e641f by @jbphet.

**Comment by pixelzoom** [comment]
Since the option that was involved in the assertion expression no longer exists, I'm guessing that the assertion can simply be deleted.    So that's what I've done in the above commit.  @jbphet please review, since I'm not familiar with this Node.

**Comment by jbphet** [comment]
Looks good to me, closing.
