### ISSUE TITLE
add API to NumberDisplay for setting Text/RichText subcomponent options

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#588]
For https://github.com/phetsims/ph-scale/issues/144, I need to be able to set the `textProperty` of the Text/RichTexst subcomponent of NumberDisplay to `phetioHighFrequency: true`.  There is currently no API for this.

**Comment by pixelzoom** [comment]
I added `options.textOptions` in the above commit.  This is now being used in ph-scale.

@ariel-phet please assign someone to review.

**Comment by Denz1994** [comment]
Some of`textOptions` fields (font, fill, etc.) are overwritten by options supplied in `NumberDisplay.valueNode`. This shouldn't be a problem because the overwritten options are defined and merged at the top of the constructor and will be supplied when `NumberDisplay` is constructed. 

I'll leave to @pixelzoom to close.

**Comment by pixelzoom** [comment]
> Some oftextOptions fields (font, fill, etc.) are overwritten by options supplied in NumberDisplay.valueNode. 

Good catch @Denz1994.  Those options should be moved into `textOptions`.  I'll take care of it.

**Comment by pixelzoom** [comment]
Note to self, here's what needs to be done:

- [ ] move `options.font` to `options.textOptions.font`
- [ ] move `options.numberFill` to `options.textOptions.fill`
- [ ] move `options.numberMaxWidth` to `options.textOptions.maxWidth`
- [ ] identify all uses of the above 3 options and fix use sites (easily the most expensive, tedious part of this change - there are 28 occurrences of `import NumberDisplay`)
- [ ] change instantiation of `valueText` so that it's also possible to override phet-io options:

```js
this.valueNode = new Constructor( longestString, merge( {
    tandem: options.tandem.createTandem( 'valueText' ),
    phetioReadOnly: true
}, options.textOptions );
```

**Comment by pixelzoom** [comment]
I've implemented what is described in https://github.com/phetsims/scenery-phet/issues/588#issuecomment-600969700.  A large numbers of use sites needed to be changed.  To identify use sites, catch any that I might have missed, I added these assertions in NumberDisplay:


```js
  //TODO delete these after https://github.com/phetsims/scenery-phet/issues/588 passes CT
  assert && assert( options.font === undefined, 'font was moved to textOptions.font' );
  assert && assert( options.numberFill === undefined, 'numberFill was moved to textOptions.numberFill' );
  assert && assert( options.textOptions.numberFill === undefined, 'numberFill was renamed to textOptions.fill' );
  assert && assert( options.numberMaxWidth === undefined, 'font was moved to textOptions.numberMaxWidth' );
  assert && assert( options.textOptions.numberMaxWidth === undefined, 'numberMaxWidth was renamed to textOptions.maxWidth' );
```

These assertions will be removed after CT passes.

**Comment by pixelzoom** [comment]
This is looking good in CT, so I've removed the aforementioned assertions in the above commit. 

@Denz1994 would you mind having another look?  List of what I did is in https://github.com/phetsims/scenery-phet/issues/588#issuecomment-600969700.

**Comment by Denz1994** [comment]
Thanks for the changes @pixelzoom. I tested by passing in some text options to ComponentScreenView/NumberDisplay object in Scenery-Phet that looked something like this:

``` 
new NumberDisplay( Property, Range, merge({}, numberDisplayOptions, {
    textOptions:{ fill: 'blue'}
     } )
)
```
The `textOptions` passed into new NumberDisplay override options in numberDisplayOptions as expected. I'll leave to @pixelzoom to close.

**Comment by pixelzoom** [comment]
Thanks @Denz1994. All done here, closing.

**Comment by pixelzoom** [comment]
I have not reviewed the code, because things are not looking right.

Here's Gas Properties 1.0.4 before the change:

<img width="1060" alt="screenshot_238" src="https://user-images.githubusercontent.com/3046552/78202323-3f378e80-7451-11ea-82ae-0b8490069b11.png">

Here's what master looks like:

<img width="1057" alt="screenshot_237" src="https://user-images.githubusercontent.com/3046552/78202263-16af9480-7451-11ea-9a6d-26059fcde7cd.png">

Note the spinners. They're not even close to the same, and the values are all scaled differently.

I see a similar problem in ph-scale, reactants-products-and-leftovers, .... every sim I've looked at that uses NumberSpinner.

Marking this as "block-publication", because we cannot publish with things in this state.
