### ISSUE TITLE
move a11y strings into main strings json

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#589]
From phetsims/chipper#795

**Comment by zepumph** [comment]
Implemented above. This was an extensive one because there were so many strings.

I ended up refactoring by nesting under component as much as possible. My thought there is to try to keep usages in different contexts from using the same string. For example (made up) resetAllButton and slider shouldn't both pull in a string called "reset" because likely that wouldn't translate equally in all languages.

I also removed a lot of usages of "String" as a suffix in the strings files. 

Please review @jessegreenberg.

**Comment by jessegreenberg** [comment]
This looks great, thanks @zepumph. I just added nesting in two places in the above commits. Closing.
