### ISSUE TITLE
Add option to disable PlayPauseButton in TimeControlNode

### ISSUE THREAD

**Issue by terracoda** [phetsims/scenery-phet#592]
Related to https://github.com/phetsims/scenery-phet/issues/575 and https://github.com/phetsims/molecules-and-light/issues/319

Based on interviews for MAL with blind learners and learners without visual impairments we feel an option to disable the Pause/Play button when the Light Source is switched off would be very beneficial.

@jessegreenberg please add any additional details.

**Comment by jessegreenberg** [comment]
Before making this change to common code it would be good to make sure we want to do this. There were a few questions about how this would impact UX in molecules and light, I made https://github.com/phetsims/molecules-and-light/issues/320 to discuss.

**Comment by pixelzoom** [comment]
Do you need to disable the Play/Pause button individually, or should the entire TimeControlNode be disabled?  For example, if there's also a Step button, would it not also be disabled when the Light Source is switched off?

**Comment by pixelzoom** [comment]
Do you need to disable the PlayPauseButton individually, or should the entire TimeControlNode be disabled?  For example, if the TimeControlNode was configured to have a Step button, wouldn't the Step button also be disabled when the Light Source is switched off? 

If you do need to disable the PlayPauseButton individually, that's already supported by sun.  But then do we need to also support disabling the other parts of TimeControlNode individually? If so, why?

**Comment by jessegreenberg** [comment]
I agree with all of the above.

We discussed this during design meeting today and decided that this should not be done for MAL in https://github.com/phetsims/molecules-and-light/issues/320. So this issue can be closed, we are not going to add this feature.
