### ISSUE TITLE
Should a TimeControlNode play/pause button have the same size as a default ResetAllButton?

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#594]
While working on https://github.com/phetsims/circuit-construction-kit-common/issues/572, it seemed they were off by about 4%

**Comment by arouinfar** [comment]
@samreid that seems like a reasonable change to me. I doubt increasing the button size by 4% will cause layout issues in existing sims, since that likely amounts to 1-2 px.

What are the current default sizes of the PlayPauseButton, StepForwardButton, and ResetAllButton? Designers use a common .ai file for buttons and other common components when we create mockups, and I'd like to update the file. It's likely the small inconsistencies in button sizes were unintentional.

**Comment by samreid** [comment]
I created a default ResetAllButton, PlayPauseButton and TimeControlNode like so:

```js
    const r = new ResetAllButton();
    const p = new PlayPauseButton(new BooleanProperty(true));
    const t = new TimeControlNode(new BooleanProperty(true));

    this.addChild(r);
    this.addChild(p);
    this.addChild(t);

    r.top = 10;
    p.top = 10;
    t.top=10;
    r.left = 0;
    p.left = r.right;
    t.left = p.right;
```

It looked like this:

![image](https://user-images.githubusercontent.com/679486/91001817-0c21a300-e58a-11ea-97c5-c06c27f14368.png)

The radius for the time control node play/pause button was set during https://github.com/phetsims/scenery-phet/issues/575 in https://github.com/phetsims/scenery-phet/commit/1927a5556fa11db6ee7127584dd687ac811a5985

@jessegreenberg can the size be adjusted to match the default Reset All Button size?

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/scenery-phet/commit/1927a5556fa11db6ee7127584dd687ac811a5985 did keep the same button size from before the re-design. But I suspect it could be increased slightly, the difference shown in https://github.com/phetsims/scenery-phet/issues/594#issuecomment-678888700 is pretty small. About half the usages of TimeControlNode are using the default radius for the PlayPauseButton. Ill increase it and inspect those usages.

**Comment by jessegreenberg** [comment]
After the above change it looks like this by default:
![image](https://user-images.githubusercontent.com/6396244/91464012-1679c080-e85a-11ea-9014-231d649e0146.png)

I inspected several of the usages of TimeControlNode and sizing seems reasonable, or change is not noticeable. @samreid back to you to review.

**Comment by samreid** [comment]
That looks great, thanks!  As an additional improvement, I recommend factoring out `20.8` which now appears in these 2 spots:

```js
// constants
const RESET_ALL_BUTTON_RADIUS = 20.8;

// ...

      // Options for the PlayPauseButton
      playPauseButtonOptions: {
        radius: 20.8, // default radius matches the size of the ResetAllButton
```

Perhaps we should have `SceneryPhetConstants.DEFAULT_BUTTON_RADIUS`?

**Comment by jessegreenberg** [comment]
That is a very nice idea, I moved the constant to a new SceneryPhetConstants.js. Back to @samreid.

**Comment by samreid** [comment]
Code change looks good, and looks great in CCK-AC, thanks!  Closing.
