### ISSUE TITLE
GaugeNode is over-instrumented

### ISSUE THREAD

**Issue by arouinfar** [phetsims/scenery-phet#595]
When reviewing States of Matter in https://github.com/phetsims/states-of-matter/issues/265, @kathy-phet and I noticed that the foregroundNode of the gaugeNode is instrumented.

<img width="165" alt="Screen Shot 2020-04-03 at 6 33 58 PM" src="https://user-images.githubusercontent.com/8419308/78414539-bac44780-75d9-11ea-925b-6287a61fb2ea.png">

Setting its visibleProperty to false results in the face of the GaugeNode being cleared:
![image](https://user-images.githubusercontent.com/8419308/78414625-476f0580-75da-11ea-8d8a-71cb050fc5f6.png)

This doesn't seem like a particularly useful interaction, and we'd like to suggest that the foregroundNode is uninstrumented.

**Comment by chrisklus** [comment]
Completed in above commits. @zepumph or @samreid please review.

**Comment by samreid** [comment]
Higher priority since it impacts the upcoming publication of States of Matter.

**Comment by samreid** [comment]
I reviewed the commit and tested States of Matter in studio, and it seems reasonable to me, thanks @chrisklus!
