### ISSUE TITLE
TimeControlNode speed radio buttons should have the suffix "RadioButton".

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#596]
For instance, the fast radio button has this phetioID:

gravityAndOrbits.modelScreen.view.timeControlNode.speedRadioButtonGroup.fast

It is preferable for PhET-iO to indicate the type in the suffix, as we do for Properties.  For instance, in this should become:

gravityAndOrbits.modelScreen.view.timeControlNode.speedRadioButtonGroup.fastRadioButton

After making this change in `TimeControlNode`, we will need to run `grunt update` on all phet-io simulations that use TimeControlNode to update their metadata.

This is blocking since we shouldn't publish any PhET-iO simulations with the incorrect tandems.

**Comment by jessegreenberg** [comment]
Thanks @samreid, sounds good. Type suffix was added to Tandem names and api files re-generated.

**Comment by pixelzoom** [comment]
I was poking around in a sim that uses this feature, and it looks great to me (see below).  So I'm going to go ahead and close this.

<img width="210" alt="screenshot_248" src="https://user-images.githubusercontent.com/3046552/78924815-a8be2b00-7a57-11ea-9825-ec059b27f531.png">
