### ISSUE TITLE
add options.tandem to ColorProfile

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#597]
Related to today's discussion about Options dialog in phet-io meeting...

`ColorProfile` currently set its tandem to "global.colorProfile", and there's no way to change it. That makes it impossibel for a sim to create > 1 ColorProfile, or to locate a ColorProfiel where it needs to live in the tandem hierarchy.  So ColorProfile should be modified to take options.tandem, just like other elements.

There are 15 occurrences of new ColorProfile.  These will need to be examined, and revised for iO sims.

@ariel-phet would you like me to take a stab at this, or assign to someone else?

**Comment by pixelzoom** [comment]
@ariel-phet I went ahead and did this, took ~15 minutes.

@arouinfar All that's left is to decide what you want for the default tandem name. It's currently `global.colorProfile.profileNameProperty`.

**Comment by arouinfar** [comment]
@pixelzoom looks good in master. I think `profileNameProperty` sounds reasonable. Was there an alternative you preferred?

**Comment by pixelzoom** [comment]
There was some talk about moving it to `global.model` or `global.view`.  @arouinfar is that no longer being considered?

**Comment by pixelzoom** [comment]
There was some talk about moving it to `global.model` or `global.view`.  @arouinfar is that no longer being considered?   If it's still a consideration, my not-so-informed opinion would probably be `global.view.colorProfile`, since "color profile" is a view thing.

**Comment by pixelzoom** [comment]
Assigned to @arouinfar for ~10 months, so elevating priority to high.  @arouinfar how would you like to proceed with ColorProfile?  For Fourier, it's tandem is `fourierMakingWaves.global.view.colorProfile`.

**Comment by zepumph** [comment]
This issue has been surpassed by the solution in https://github.com/phetsims/scenery-phet/issues/515. I think it is ready to close.
