### ISSUE TITLE
MoveToTrashButton has odd disabled behavior

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#598]
Noticed in https://github.com/phetsims/sun/issues/578, the issue were SunConstants.DISABLE_OPACITY was adjusted.

`MoveToTrashButton` was one of the UI components adjusted, and it looks at little suspect. 

First, there's a bogus comment - "by default the arrow is color-coded for thermal energy":

```js
    // {Color|string} by default the arrow is color-coded for thermal energy, see scenery-phet#320
    baseColor: new Color( 230, 230, 240 ),
    disabledBaseColor: 'white',
    arrowColor: 'black',
```

`arrowColor` is clearly `'black'`, and the comment is 3 lines above it. So I'll go ahead and fix that.

Next is how opacity is handled.  When the button is disabled, it changes the hue and opacity of its icon, making the entire icon black, removing any color coding. Changing the opacity of the icon is definitely not the responsibility of MoveToTrashButton, that should be handled by superclass RectangularPushButton.  And why remove the color coding? 

I looked at the 3 usages of `MoveToTrashButton`, in ESP, MAS, and pendulum-lab.  

They all look like variations of this (enabled on left, disabled on right). Note that the color-coding is removed when the button is disabled.  I'm not sure why this is desirable, and it could be a problem if there were more that one such button.

<img width="171" alt="screenshot_260" src="https://user-images.githubusercontent.com/3046552/79286349-8d02bc80-7e7d-11ea-96cd-80a7f86eae55.png"> <img width="169" alt="screenshot_259" src="https://user-images.githubusercontent.com/3046552/79286353-8f651680-7e7d-11ea-8467-6c963082f113.png">

Here's what it looks like if we make MoveToTrashButton behave like other push buttons (enabled on left, disabled on right). That is, don't mess with the icon, just let RectangularPushButton adjust the opacity.  Note the the color-coding is still present in the disabled button. Again, this seems desirable, especially if there's more than one such button.

<img width="174" alt="screenshot_258" src="https://user-images.githubusercontent.com/3046552/79286216-27aecb80-7e7d-11ea-8b13-238aad9f1219.png"> <img width="173" alt="screenshot_257" src="https://user-images.githubusercontent.com/3046552/79286224-2aa9bc00-7e7d-11ea-8139-003d2fe83d48.png">

Here's the patch:

<details>
<summary>MoveToTrashButton patch</summary>

```diff
Index: js/MoveToTrashButton.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/MoveToTrashButton.js	(revision 0e35bd229ab8755084c34d9ab890773f8abd936e)
+++ js/MoveToTrashButton.js	(date 1586909905907)
@@ -8,24 +8,20 @@
  * @author Jonathan Olson <jonathan.olson@colorado.edu>
  */
 
+import Property from '../../axon/js/Property.js';
 import InstanceRegistry from '../../phet-core/js/documentation/InstanceRegistry.js';
 import inherit from '../../phet-core/js/inherit.js';
 import merge from '../../phet-core/js/merge.js';
 import Node from '../../scenery/js/nodes/Node.js';
 import Path from '../../scenery/js/nodes/Path.js';
 import Color from '../../scenery/js/util/Color.js';
-import ButtonInteractionState from '../../sun/js/buttons/ButtonInteractionState.js';
 import RectangularButtonView from '../../sun/js/buttons/RectangularButtonView.js';
 import RectangularPushButton from '../../sun/js/buttons/RectangularPushButton.js';
 import FontAwesomeNode from '../../sun/js/FontAwesomeNode.js';
-import SunConstants from '../../sun/js/SunConstants.js';
 import Tandem from '../../tandem/js/Tandem.js';
 import CurvedArrowShape from './CurvedArrowShape.js';
 import sceneryPhet from './sceneryPhet.js';
 
-// constants
-const DISABLED_COLOR = new Color( 0, 0, 0, SunConstants.DISABLED_OPACITY );
-
 /**
  * @constructor
  *
@@ -35,7 +31,6 @@
 
   options = merge( {
 
-    // {Color|string} by default the arrow is color-coded for thermal energy, see scenery-phet#320
     baseColor: new Color( 230, 230, 240 ),
     disabledBaseColor: 'white',
     arrowColor: 'black',
@@ -46,26 +41,7 @@
     tandem: Tandem.REQUIRED
   }, options );
 
-  assert && assert( !options.contentAppearanceStrategy, 'MoveToTrashButton sets contentAppearanceStrategy' );
-  options.contentAppearanceStrategy = function( content, interactionStateProperty ) {
-
-    function updateEnabled( state ) {
-      if ( content ) {
-        const enabled = state !== ButtonInteractionState.DISABLED &&
-                        state !== ButtonInteractionState.DISABLED_PRESSED;
-
-        arrowPath.fill = enabled ? options.arrowColor : DISABLED_COLOR;
-        trashPath.fill = enabled ? 'black' : DISABLED_COLOR;
-      }
-    }
-
-    interactionStateProperty.link( updateEnabled );
-    this.dispose = function() {
-      interactionStateProperty.unlink( updateEnabled );
-    };
-  };
-
-  var trashPath = new FontAwesomeNode( 'trash', { tandem: options.tandem.createTandem( 'trashPath' ) } );
+  const trashPath = new FontAwesomeNode( 'trash', { tandem: options.tandem.createTandem( 'trashPath' ) } );
 
   const arrowShape = new CurvedArrowShape( 10, -0.9 * Math.PI, -0.2 * Math.PI, {
     tandem: options.tandem.createTandem( 'arrowShape' ),
@@ -73,10 +49,13 @@
     tailWidth: 4
   } );
 
-  var arrowPath = new Path( arrowShape, {
+  const arrowFillProperty = new Property( options.arrowColor );
+
+  const arrowPath = new Path( arrowShape, {
     tandem: options.tandem.createTandem( 'arrowPath' ),
     bottom: trashPath.top,
-    right: trashPath.left + trashPath.width * 0.75
+    right: trashPath.left + trashPath.width * 0.75,
+    fill: arrowFillProperty
   } );
 
   options.content = new Node( {
```

</details>

Mentioning the original authors, @samreid and @jonathanolson.

Assigning to @arouinfar and @ariel-phet for design thoughts. Would you have any objections to this change?

**Comment by pixelzoom** [comment]
Another reason to change this to behave like other buttons is that this button will become a liability when sun buttons eventually use the `EnabledComponent` mixin.

**Comment by pixelzoom** [comment]
More thoughts...  

I don't see why it's necessary to change this specific button's icon to grayscale when it's disabled.  If that desirable here, why isn't it desirable in general for all buttons, or for anything that's disabled? 

Another reason to change this to behave like other buttons is that this implementation will become a liability when sun buttons eventually use the `EnabledComponent` mixin.

**Comment by arouinfar** [comment]
Thanks for bringing this to our attention @pixelzoom. I see no reason why the `MoveToTrashButton` should behave differently from other push buttons when disabled. I would be in favor of using RectangularPushButton's disabled behavior. 

> Why isn't color-coding when disabled desirable here?

I don't see a problem with keeping the color-coding when disabled. My suspicion is that the color-coding was removed because early versions of the button didn't look sufficiently disabled. For example, the buttons looked like this in [ESPB dev.38](https://phet-dev.colorado.edu/html/energy-skate-park-basics/1.0.0-dev.38/energy-skate-park-basics_en.html). 

![image](https://user-images.githubusercontent.com/8419308/79293147-233fde00-7e90-11ea-8654-df51ab704bb9.png) ![image](https://user-images.githubusercontent.com/8419308/79293132-17541c00-7e90-11ea-97a2-cab0ad9ee0e4.png)

**Comment by ariel-phet** [comment]
@pixelzoom yes, fine with this button following the modern convention. I think as @arouinfar pointed out this is probably just vestigial code given the age of its origins in ESPB, and the pattern has just been followed in later sims. What you have in the patch looks good to me.

**Comment by pixelzoom** [comment]
Thanks @arouinfar and @ariel-phet, I'll proceed with applying the patch, then randomly select one of the authors to review.

**Comment by pixelzoom** [comment]
This work is done.  I applied the proposed patch, converted to ES6 class, and added an "Enabled" checkbox to the scenery-phet demo (_Buttons_ screen) so that this (and other buttons) can be viewed both enabled and disabled.

As I mentioned above, I was planning to randomly assign to either @samreid or @jonathanolson. But I suspect that they are still super busy.  So assigning to @ariel-phet to choose someone to review.

**Comment by pixelzoom** [comment]
For the reviewer:
* inspect MoveToTrashButton.js
* test in scenery-phet _Buttons_ screen, using 'Enabled' checkbox
* inspect in ESP, MAS, or pendulum-lab

**Comment by ariel-phet** [comment]
Assigning to @jessegreenberg since he is working on ESP and should be a fairly brief issue.

**Comment by jessegreenberg** [comment]
I reviewed the issue and changes. MoveToTrashButton looks good, and I reviewed the examples listed in https://github.com/phetsims/scenery-phet/issues/598#issuecomment-614313034. Closing.
