### ISSUE TITLE
LeftRightSpinner and UpDownSpinner issues in scenery-phet demo

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#599]
Discovered while working on https://github.com/phetsims/scenery-phet/issues/598.

Two problems with `LeftRightSpinner` and `UpDownSpinner`:

- [x] They are in the wrong demo screen.  They are currently in _Buttons_, but should be in _Components_.   Yes they are composed of buttons, but they are not buttons.  See NumberSpinner in the sun ComponentsScreenView.

- [ ] There is nothing in the demos that demonstrates the associated Properties.  At the very least, there should be a `Text` node that displays the value, and `Checkboxes` to enabled/disable the buttons. It would also be nice to demo `enabledProperty` for the entire component. Again, see demoNumberSpinner in sun ComponentsScreenView.

Author for these spinners is @samreid.  Assigning to @ariel-phet to prioritize and assign.

**Comment by pixelzoom** [comment]
I moved them to the correct Screen in the above commit.

**Comment by ariel-phet** [comment]
Sounds like the ideal would be coalescing various "spinner" implementations.

Deferring, since https://github.com/phetsims/sun/issues/436 would likely be a better way to resolve the issue above.

**Comment by pixelzoom** [comment]
Agreed @ariel-phet.  I should also point out that the APIs for `LeftRightSpinner` and `UpDownSpinner` (which are both number spinners) are very different from the `NumberSpinner` API.  The most significant differents are:  (1) they don't handle disabling their buttons, that's the responsibility of the client, (2) they are hard-coded with a delta of 1.

Since the only different between `LeftRightSpinner` and `UpDownSpinner` is their orientation, it also seems wrong that they are 2 different classes that don't share anything.  It looks like someone took one of these, make a copy, and just changed the layout manager.

Looks like these spinner currently used only in fractions-comparison.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/scenery-phet/issues/584#issuecomment-783537929, @samreid said:
> Let's delete/deprecate UpDownSpinner and LeftRightSpinner from scenery-phet and recommend using NumberPicker and/or generalizing RoundNumberSpinner instead.

Since these are being deleted, there's no reason to address this issue. Closing.
