### ISSUE TITLE
animated transitions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#60]
At 6/19/14 status meeting, @samreid suggest that PhET include animated transitions as a standard part of user interfaces, especially in games.  That was approved, and we're now supposed to include transitions in all games currently under development (including graphing-lines, balancing-chemical-equations, arithmetic-builder, ...) and future games.

**Comment by pixelzoom** [comment]
@ariel-phet Can we close this issue?   This issue is coming up on 3 years old.  Since then, we've been successfully specifying what does and does not need to be animated on a sim-by-sim basis.  We've been doing these types of animation with TWEEN, and have recently started encapsulating them in twixt.  And I don't really see a need to make all PhET games have the same transitions.

**Comment by ariel-phet** [comment]
@pixelzoom agreed. Thanks for the issue hygiene. Closing
