### ISSUE TITLE
HandleNode dispose should be moved

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#600]
Just noticed while looking at something unrelated, the `dispose` was accidentally put in the `register` call.

**Comment by jessegreenberg** [comment]
@chrisklus can you please review?

**Comment by chrisklus** [comment]
Whoops, thanks @jessegreenberg! Looks great. Back to you to close if all set.

**Comment by jessegreenberg** [comment]
Great, thanks!
