### ISSUE TITLE
Background node not getting set to correct size during construction

### ISSUE THREAD

**Issue by jbphet** [phetsims/scenery-phet#603]
In number-line-integers, I'm seeing an issue where a background node looks tiny if the contained node never changes its size.  In the screenshot below, notice that the label on the right size of the number line point has no background, but it does have a little dot below it and to the left, which I suspect is the background.

![image](https://user-images.githubusercontent.com/3082831/80767979-6774e480-8b06-11ea-8334-026ef1019f8b.png)

**Comment by jbphet** [comment]
It looks to me like the problem was introduced when we migrated from using `.on() ' to using a property for the bounds.  The commit was b43953967a7fab9dde1e635e422fce2db63e7a7a.

**Comment by jbphet** [comment]
@jonathanolson - I committed a potential fix for this.  Please take a look and either close or improve at your discetion.

**Comment by pixelzoom** [comment]
This fix has been assigned to @jonathanolson for 10+ months.  I'm inclined to close this. @jbphet are you confident that the change does not need review?

**Comment by jbphet** [comment]
Yep, I think we're good.  Closing.
