### ISSUE TITLE
changes to TimeControlNode API

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#604]
During 5/14/2020 phet-io meeting, the following changes to TimeControlNode API were identified, to conform to MVC pattern:

- [x] rename enumeration TimeControlSpeed to TimeSpeed
- [x] rename option `timeControlSpeedProperty` to `timeSpeedProperty`
- [x] rename option `timeControlSpeeds` to `timeSpeed`
- [x] rename constant `DEFAULT_TIME_CONTROL_SPEEDS` to `DEFAULT_TIME_SPEEDS`

Also:
- [x] name the model Property `timeSpeedProperty` wherever it makes sense to do so, for PhET-iO consistency

I volunteered.

**Comment by pixelzoom** [comment]
Done in the above commits.

@arouinfar The only tandems that needed to be renamed were in ESP and WI -- they are now "timeSpeedProperty".

@ariel-phet please assign someone to review.

**Comment by pixelzoom** [comment]
Done in the above commits.

@arouinfar The only tandems that needed to be renamed were in ESP and WI -- they are now "timeSpeedProperty".  Have a look and see if I missed anything.

@ariel-phet please assign someone to review code changes.

**Comment by ariel-phet** [comment]
@Denz1994 has used TimeControlNode in several sims, seems like a good person to review.

**Comment by arouinfar** [comment]
@pixelzoom looks good.

The changes to TimeControlNode temporarily broke gravity-and-orbits and states-of-matter in studio because the deprecated `timeControlSpeedProperty` was featured in the overrides (see above commits). That got me wondering if we could simply feature `timeSpeedProperty` in common code rather than the overrides. If so, I would do the same for the PlayPauseButton's `isPlayingProperty`.

Back to @pixelzoom for his thoughts.

**Comment by pixelzoom** [comment]
`timeSpeedProperty` and `isPlayingProperty` cannot be featured in common code. They are created by sim-specific code in the sim's model, and passed to `TimeControlNode`.

**Comment by pixelzoom** [comment]
As for breaking overrides.js...  I'm not aware of tools/process that addresses that, which sounds like a PhET-iO gap.

**Comment by pixelzoom** [comment]
> The changes to TimeControlNode temporarily broke gravity-and-orbits and states-of-matter in studio ...

For the record, the changes that I made to TimeControlNode didn't break states-of-matter.  That was broken by @jbphet in https://github.com/phetsims/states-of-matter/commit/8af05de3957e9e3d4a66fce353a8f16c89b4e5a3, prior to the changes that I made for TimeControlNode in https://github.com/phetsims/states-of-matter/commit/4a488e3b6bf3462bc44b8b963d3a67c1176b70d0.

**Comment by Denz1994** [comment]
A separate issue has been created for review comments in #607.

**Comment by pixelzoom** [comment]
Thanks @Denz1994.  Looks like remaining items are in #607, so I'll close this issue.
