### ISSUE TITLE
Add moveToFront to MeasuringTapeNode

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#608]
While working on https://github.com/phetsims/wave-interference/issues/450 I needed to add `moveToFront` for the measuring tape.  I noticed this code in StopwatchNode:

```js
  const stopwatchVisibleListener = visible => {
    this.visible = visible;
    if ( visible ) {
      this.moveToFront();
    }
    else {

      // interrupt user interactions when the stopwatch is made invisible
      this.interruptSubtreeInput();
    }
  };

// ....


    // Move to front on pointer down, anywhere on this Node, including interactive subcomponents.
    // This needs to be a DragListener so that touchSnag works.
    moveToFrontListener = new DragListener( {
      attach: false, // so that this DragListener won't be ignored
      start: () => this.moveToFront(),
      tandem: options.tandem.createTandem( 'moveToFrontListener' )
    } );
    this.addInputListener( moveToFrontListener );
```

This code was ported from Gas Properties in December 2019.  Is this code fully general and can this pattern be applied in MeasuringTapeNode? 

I considered that it would be simpler to just add `moveToFront` as the first line of the primary input listener.  Then it would also be called when dragging something out of a toolbox.  Would that pattern work instead?

**Comment by pixelzoom** [comment]
I believe that it had to be added as a separate listener in StopwatchNode so that clicking on interactive components (e.g buttons) would also move the node to the front.  Note that StopwatchNode's DragListener is added to its background:

```js
    // dragging, added to background so that other UI components get input events on touch devices
    this.dragListener = new DragListener( merge( {
```

I don't know if that's the case in MeasuringTapeNode.  Seems like you may have the same issue with grabbing the "pull tab" that extends the tape.

**Comment by samreid** [comment]
MeasuringTapeNode accommodated a simpler solution since the "pull tab" was not a Button.

**Comment by samreid** [comment]
This is implemented and working well in Wave Interference.  @ariel-phet can you please assign a reviewer?

**Comment by pixelzoom** [comment]
> MeasuringTapeNode accommodated a simpler solution since the "pull tab" was not a Button.

Your "simpler solution" is to duplicate `this.moveToFront` in the input listener for the base and "pull tab".   The same could have been done in StopwatchNode by adding an addition input listener to each button.  Why is it acceptable to duplicate code in MeasuringTapeNode, rather than to use the approach used in StopwatchNode?

**Comment by samreid** [comment]
StopwatchNode cannot simply add `moveToFront` in the button callback because sometimes the buttons are disabled and do not get fired.  Also, even for enabled buttons, moving them to the front would only happen on mouse release, not on mouse down as is desirable.  Summarizing the differences for clarity, here is the code that StopWatchNode uses to support moveToFront:

```js
   let moveToFrontListener = null;

// ...

    // Move to front on pointer down, anywhere on this Node, including interactive subcomponents.
    // This needs to be a DragListener so that touchSnag works.
    moveToFrontListener = new DragListener( {
      attach: false, // so that this DragListener won't be ignored
      start: () => this.moveToFront(),
      tandem: options.tandem.createTandem( 'moveToFrontListener' )
    } );
    this.addInputListener( moveToFrontListener );

// ...

    if ( moveToFrontListener ) {
      this.removeInputListener( moveToFrontListener );
      moveToFrontListener.dispose();
    }
```

Here is the code in MeasuringTapeNode to support moveToFront:

```js
this.moveToFront();

// ...

this.moveToFront();
```

In my opinion, the latter is much simpler.  If there is a way to apply it to StopwatchNode (avoiding the problems mentioned above), we should do so.

**Comment by pixelzoom** [comment]
I think you've missed the point.  The point is not that I couldn't have added additional listeners to the Buttons in StopwatchNode. The point is that I shouldn't have even if I could have, because that's duplicated code.  The requirement is "move the tape measurer to the front if any part of it is pressed".  You've distributed that requirement to 2 listeners when it can be encapsulated  in 1 listener.  Admittedly more complicated to encapsulate.  If you think the current implementation is OK, I'm happy to move on.

StopwatchNode also calls `moveToFront` when it becomes visible.  You showed that code in https://github.com/phetsims/scenery-phet/issues/608#issue-625234136.  Did you plan to do something similar for MeasuringTapeNode?

**Comment by samreid** [comment]
> If you think the current implementation is OK, I'm happy to move on.

In this case, 1 line of duplicated code seems preferable to 13 lines of code which are (a) scattered across 3 places in the file, (b) introduces a `let` variable (c) introduces 2+ new PhET-iO elements.  To me, the best arguments for using the `moveToFrontListener` pattern are:
* If we think there will be a lot of new StopwatchNode buttons or MeasuringTape features added, where we are likely to forget to call `moveToFront` on each of them
* Creating standardization across our components, perhaps if we pursue a `moveToFront` mixin (if we know we cannot use the MeasuringTapeNode strategy uniformly).

Summarizing, here's a list of what we are trying to minimize:
* Duplication of code
* Code complexity (number of lines of code, disposal)
* Unnecessary phet-io elements
* Unnecessary asymmetry
* Maintenance effort/risk of "forgetting a step" when adding new components
* CPU/Memory considerations

What are your thoughts about a `MoveToFrontListener` or a `ToolMixin`?  Although with either of those patterns it seems we incur creating more phet-io elements which I'm not convinced are desirable.

> StopwatchNode also calls `moveToFront` when it becomes visible.  You showed that code in https://github.com/phetsims/scenery-phet/issues/608#issue-625234136.  Did you plan to do something similar for MeasuringTapeNode?

For tools that are always dragged out of a toolbox, it seems that calling `moveToFront` on `visible=true` is unnecessary because it will be moved to front on drag.  So is this feature primarily for tools that can be activated by a checkbox?  Is changing the layering always desirable when activating a tool via a checkbox?  If it is usually but not always desirable, will we provide an option for shutting that off?

**Comment by pixelzoom** [comment]
> What are your thoughts about a MoveToFrontListener or a ToolMixin? Although with either of those patterns it seems we incur creating more phet-io elements which I'm not convinced are desirable.

I think a mixin might be useful.  I'm also not convinced that this should be automatically added to tools.  For example, we might want a StopwatchNode that's in a fixed location, not movable, and that's currently problematic. 

> For tools that are always dragged out of a toolbox, it seems that calling moveToFront on visible=true is unnecessary because it will be moved to front on drag. So is this feature primarily for tools that can be activated by a checkbox? Is changing the layering always desirable when activating a tool via a checkbox? If it is usually but not always desirable, will we provide an option for shutting that off?

Gas Properties uses the checkbox approach, and the requirement was to make tools move to the front as they became visible. And I think that makes requirement makes sense in general.  I also don't think it hurts to move-to-front in cases where a tool is dragged out of a toolbox.  So it might be better to just handle that, and say that "no matter how a tool appears, it appears in front".

**Comment by samreid** [comment]
We reviewed this and decided to discuss again when @pixelzoom returns.

**Comment by pixelzoom** [comment]
7/23/20 dev meeting:

@jonathanolson has been doing this in the DragListener `start`.  If not done there, recommends using PressListener.  Doesn't think we need a separate type for moveToFront.

@pixelzoom moveToFront doesn't belong in common-code UI components, it's a sim-specific decision. One parent node could manage moveToFront for its children.

@samreid add something like options.startDragCallback that gets called whenever you start dragging some part of the MeasuringTapeNode.  Do moveToFront in the callback.

@zepumph all of our usages are doing moveToFront. Make sure there's a way to opt out.  

@samreid Should all of our usages be using the same approach to doing moveToFront? Or are there different cases that need to be implemented differently?  

Consensus: Let's do `moveToFront` in DragListener so that we don't create another listener that appears in PhET-iO.

@samreid will survey how many places are calling moveToFront and need to be changed.

**Comment by samreid** [comment]
Sims listening to a model Property to call `moveToFront`
* area builder
* balancing act
* balloons and static electricity
* blackbody spectrum
* Circuit construction kit: black box study
* Collision lab
* Energy Forms and Changes (I think)
* Expression Exchange

Sims calling `moveToFront` as one step in a `start` callback:
* Bending Light
* Build a molecule (also moves to front in `drag`)
* Charges and Fields
* Energy Skate Park
* Equality Explorer (also has one model driven call)
* Circuit Construction Kit
* Curve Fitting
* Fluid Pressure and Flow (also has model driven call)

I'm halfway through but will need to resume later.
* Forces and Motion Basics (also has model driven call)

**Comment by samreid** [comment]
StopwatchNode has a dedicated `moveToFrontListener` which looks like it should be changed to use the pattern identified above.  CCK also has a `moveToFrontListener` but it is a callback function, not an input listener, so it doesn't need to be changed.  I'll make the change to `StopwatchNode` then request a review.

**Comment by samreid** [comment]
I committed a proposed implementation which works properly when testing in Gas Properties.  The main problem with the proposed implementation is that it is very easy to accidentally override the default `moveToFront` functionality.  For instance, if I want to provide a `{drag}` element, that would wipe out the `{start}` entry, or I would have to remember to add it separately.  Still, this seemed simpler than (a) detecting whether there was a `start` entry and adding one with `()=>this.moveToFront()` or (b) "patching in" a `moveToFront` to an existing start entry.

@pixelzoom can you please review at your convenience?

**Comment by pixelzoom** [comment]
You've encountered a typical hazard of combining responsibilities. Allowing the client to blow away required functionality is not acceptable. You'll have to do something like this (untested):

```
const DEFAUT_START = () => this.moveToFront();

options = merge( { 
  ...
  dragListenerOptions: {
    start: DEFAUT_START
  }
  ...
}, options );

if ( options.dragListenerOptions.start !== DEFAUT_START ) {
   const start = options.dragListenerOptions.start;
   options.dragListenerOptions.start = () => {
    DEFAULT_START();
    start();
   };
}
```

Or maybe keeping these responsibilities separated is looking better now?

**Comment by pixelzoom** [comment]
And it looks like you've already change (broken?) the behavior of 1 sim by using this approach.  In WavesScreenView.js, you're overriding `dragListenerOptions.start` and the client is not calling `moveToFront`.

```js
    const stopwatchNode = new WaveInterferenceStopwatchNode( model, {
      visibleBoundsProperty: this.visibleBoundsProperty,

      dragListenerOptions: {
        start: () => {
          grabSound.play();
        },
```

**Comment by samreid** [comment]
I committed a change that always calls moveToFront on StopwatchNode drag start.

> Or maybe keeping these responsibilities separated is looking better now?

In my opinion, this wasn't troublesome enough to revisit our consensus.

I tested this in Gas Properties and Wave Interference and it appears to be working as desired.  Ready for re-review.

**Comment by pixelzoom** [comment]
Looks OK. Closing.
