### ISSUE TITLE
generalize ProtractorNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#609]
Noted during code review of https://github.com/heldentodd/xray-diffraction/issues/1.

pendulum-lab and bending-light have implementations of ProtractorNode that are almost identical.  It looks like bending-light was ported from Java by @samreid, then MLL copied to pendulum-lab.

Since the developer of xray-diffraction didn't have access to a common-code implementation, he made yet-another copy at https://github.com/heldentodd/xray-diffraction/blob/master/js/xray-diffraction/view/ProtractorNode.js.

So it would benefit both PhET and 3rd-parties to generalize ProtractorNode.

Assigning to @ariel-phet for prioritization and assignment.

**Comment by pixelzoom** [comment]
When this generalization takes place:

- [ ] fix spelling of param `rotateable`, it should be `rotatable`

**Comment by pixelzoom** [comment]
Something else to maybe address.... Over in https://github.com/heldentodd/xray-diffraction/issues/1#issuecomment-644894336, @heldentodd reported:

- [ ] ProtectorNode fails with `?ea&shuffleListeners`.

**Comment by pixelzoom** [comment]
The first step here would be to compare the implementations of ProtractorNode, consolidate into one implementation (if there are differences), and move it to scenery-phet.   Then notify @heldentodd so that he can use it in xray-diffraction.

After that, someone can work on refining it -- the `shuffleListeners` issue, adding PhET-iO instrumentation (if it's not there already), etc.

**Comment by pixelzoom** [comment]
Discussed with @ariel-phet on 6/17/20.  pendulum-lab/ProtractorNode is actually very different, so we can ignore it (or rename it to be less confusing). 

I will move bending-light/ProtractorNode to scenery-phet, and let @heldentodd know when that has been done, so he can use it in xray-diffraction.

**Comment by pixelzoom** [comment]
ProtractorNode has been migrated to scenery-phet.  

API changes:

* Constructor signature has changed. `rotatable` parameter is now an option.
* Added `createIcon` static method for creating icons (for use in toolboxes, checkboxes, etc.)
* Implemented `dispose`

Internal changes:

* Paths used to create pointer areas have been replaced with the new `hitTestPixels` option for scenery.Image
* Fields that were public (and didn't need to be) have been converted to local variables.
* Now uses DragListener instead of SimpleDragHandler

@samreid There were some changes to bending-light, please review if you wish.

@heldentodd Please proceed with using scenery-phet.ProtractorNode in xray-diffraction. See the note above about the constructor change.  You'll need to set `rotatable: true` via options instead of a constructor parameter.

**Comment by heldentodd** [comment]
Updated code is working great in the xray-diffraction sim. Many thanks.

**Comment by pixelzoom** [comment]
Since `ProtractorNode` is now a common-code component, in the above commit I renamed pendulum-lab's `ProtractorNode` to `PendulumLabProtractorNode`.   Since there is a `PendulumLabRulerNode`, it seemed like there was precedence for this. @jonathanolson FYI.

**Comment by samreid** [comment]
I reviewed the code changes in Bending Light and tested in the browser. Everything looks good to me.  Reassigning to @jonathanolson for the FYI.

**Comment by jonathanolson** [comment]
Thanks!
