### ISSUE TITLE
potential infinite loop in BackgroundNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#611]
Noted while working on https://github.com/phetsims/natural-selection/issues/118.  

This is a potential infinite loop in BackgroundNode.js:

```
    // size the rectangle to fit the node
    node.boundsProperty.link( bounds => {
      if ( !bounds.isEmpty() ) {
        this.background.setRect( 0, 0, node.width + 2 * options.xMargin, node.height + 2 * options.yMargin );
        node.center = this.background.center;
      }
    } );
```

When `node.center` is set, that changes `node.bounds`.  The solution is to observe `node.localBoundsProperty`.

**Comment by pixelzoom** [comment]
BackgroundNode is used by graphing-quadratics, number-line-common, number-line-integers, number-line-operations, and states-of-matter.

**Comment by pixelzoom** [comment]
Fixed and tested usages.  Since most of the usages are in @jbphet sims, assigning to him to review.

**Comment by jbphet** [comment]
The explanation makes sense, the code change looks reasonable, and I tested dynamic resizing of the background node by manipulating points on the "Generic" screen in number-line-operations and verifying that the background of the point labels correctly resizes.  Looks good, closing.
