### ISSUE TITLE
ScientificNotationNode 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#613]
Discovered in https://github.com/phetsims/ph-scale/issues/173.

Example:

```
> phet.sceneryPhet.ScientificNotationNode.toScientificNotation( 9.952541657737637e-8 )
{mantissa: "10.0", exponent: "-8"}
```

So `9.952541657737637e-8` is displayed as "10.0 x 10<sup>-8</sup>", when it should be "1.0 x 10<sup>-7</sup>".

This only occurs when the mantissa is exactly 10. And in that case, that power of 10 needs to be shifted to the exponent. 

This will affect all sims that use `ScientificNotationNode`, which currently includes: blackbody-spectrum, coulombs-law, gravity-force-lab, gravity-force-lab-basics.

**Comment by pixelzoom** [comment]
Fixed in the above commit.  This problem occurs only when the mantissa is exactly 10, so the fix is specific to that value. 

Some tests:

```
> phet.sceneryPhet.ScientificNotationNode.toScientificNotation( 9.952541657737637e-8 )
{mantissa: "1.0", exponent: "-7"}
> phet.sceneryPhet.ScientificNotationNode.toScientificNotation( 9.952541657737637e-8, {mantissaDecimalPlaces: 2} )
{mantissa: "9.95", exponent: "-8"}
> phet.sceneryPhet.ScientificNotationNode.toScientificNotation( 9.9e-8 )
{mantissa: "9.9", exponent: "-8"}
> phet.sceneryPhet.ScientificNotationNode.toScientificNotation( 10e-8 )
{mantissa: "1.0", exponent: "-7"}
> phet.sceneryPhet.ScientificNotationNode.toScientificNotation( 10.1e-8 )
{mantissa: "1.0", exponent: "-7"}
> phet.sceneryPhet.ScientificNotationNode.toScientificNotation( 10.1e-8, { mantissaDecimalPlaces: 1 } )
{mantissa: "1.0", exponent: "-7"}
> phet.sceneryPhet.ScientificNotationNode.toScientificNotation( 10.1e-8, { mantissaDecimalPlaces: 2 } )
{mantissa: "1.01", exponent: "-7"}
> phet.sceneryPhet.ScientificNotationNode.toScientificNotation( 10.1e-8, { mantissaDecimalPlaces: 3 } )
{mantissa: "1.010", exponent: "-7"}
> phet.sceneryPhet.ScientificNotationNode.toScientificNotation( 10.5e-8 )
{mantissa: "1.1", exponent: "-7"}
```

**Comment by pixelzoom** [comment]
Reopening. 

After further digging, I discovered that this bug was introduced by @jessegreenberg in phetsims/scenery-phet@bfa1874 on 9/20/17. There's no GitHub issue referenced in the commit. @jessegreenberg do you recall why this change was made?

**Comment by jessegreenberg** [comment]
Commit https://github.com/phetsims/scenery-phet/commit/bfa1874 actually does reference https://github.com/phetsims/scenery-phet/issues/334 which describes:

> ScientificNotationNode.toScientificNotationNode returns an object like {mantissa:{number}, exponent:{number}}. Since mantissa is a number, we lose the zeroes to the right of the decimal and the precision specified by the option mantissaDecimalPlaces. To keep consistent precision when there are zeroes to the right of the decimal mantissa needs to be a string.

**Comment by pixelzoom** [comment]
Thanks @jessegreenberg -- the issue number didn't show up as a link in WebStorm's "Show History", so I missed it. 

The change I made in https://github.com/phetsims/scenery-phet/commit/65aa972041f601b84190c45ac7391495a981172b doesn't affect the goal of https://github.com/phetsims/scenery-phet/commit/bfa1874.   So I'll leave things as is and re-close.

**Comment by samreid** [comment]
As discovered in https://github.com/phetsims/chipper/issues/946, there are TODOs in the code referring to this issue.  Reopening.

**Comment by pixelzoom** [comment]
Here's the remaining TODO:

```js
      // Convert to a string in exponential notation, where the mantissa has 1 digit to the left of the decimal place.
      //TODO https://github.com/phetsims/scenery-phet/issues/613 toExponential uses Number.toFixed, which doesn't round the same on all platforms
      const exponentialString = value.toExponential( options.mantissaDecimalPlaces );
```

**Comment by samreid** [comment]
In https://github.com/phetsims/dot/issues/113, @zepumph and I changed the implementation of Utils.toFixed to use https://github.com/MikeMcl/big.js, which is described as "A small, fast JavaScript library for arbitrary-precision decimal arithmetic."  @pixelzoom can you please check on the status of this TODO after that change? Please zoom consult with me and or @zepumph at your discretion.

**Comment by pixelzoom** [comment]
Running the tests in https://github.com/phetsims/scenery-phet/issues/613#issuecomment-661983520, this appears to be resolved.  So I deleted the associated TODO comments, and will close this issue.
