### ISSUE TITLE
Eliminate the need to call redrawNumberDisplay and perhaps recomputeText

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#615]
In #565 I said:

> When changing units, formatter or anything else related to the time display, we must trigger that text to update. That can be done via NumberDisplay.recomputeText but developers could forget to call that.

@pixelzoom replied:

> This requirement for NumberDisplay.recomputeText (and StopwatchNode.redrawNumberDisplay it appears) is not acceptable, and violates a general pattern: if mutating an attribute requires an update, then that attribute should be private, mutation should be done via a setter, and the setter should handle the update. This should be addressed.

**Comment by samreid** [comment]
This problem is rooted in the fact that NumberDisplay uses the following option:

```js
      // {function} Takes a {number} and returns a {string} for full control. Mutually exclusive with valuePattern and
      // decimalPlaces.  Named "numberFormatter" instead of "formatter" to help clarify that it is separate from the
      // noValueString/Align/Pattern defined below.
      numberFormatter: null,
```

Since this is a plain `function`, `NumberDisplay` has no idea when to call it, and hence the client code must trigger it to be called at the appropriate time.

Should this be changed to a `Property<function>`, so that `NumberDisplay` will know to call it when the `<function>` changes?

**Comment by pixelzoom** [comment]
`{Property.<function>} numberFormatterProperty` sounds appropriate.

**Comment by pixelzoom** [comment]
`{Property.<function>} numberFormatterProperty` sounds appropriate, if this really needs to be mutable.  Is there currently a case where it needs to be mutable?

**Comment by samreid** [comment]
> Is there currently a case where it needs to be mutable?

Yes, Wave Interference has mutable units in the formatter:

```js
    config = merge( {
      numberDisplayRange: new Range( 0, 999.99 ),
      numberDisplayOptions: {
        numberFormatter: StopwatchNode.getRichNumberFormatter( {
          showAsDecimal: true,
          unitsProperty: unitsProperty
        } )
      }
    }, config );
    assert && assert( !!config.dragListenerOptions, 'end is a required argument' );
    assert && assert( !!config.visibleBoundsProperty, 'visibleBoundsProperty is a required argument' );

    super( model.stopwatch, config );

    // After the StopwatchNode is initialized with the maximal layout, use the correct initial value for the current
    // timeUnits
    model.sceneProperty.link( scene => {
      unitsProperty.value = scene.timeUnits;
      this.redrawNumberDisplay();
    } );
```

@pixelzoom should this issue be blocking publication?

**Comment by samreid** [comment]
@pixelzoom there are 5 sites calling `numberFormatter: {function}`.  Should we support `Property<function>|function`, or just `Property<function>`?

**Comment by pixelzoom** [comment]
> @pixelzoom should this issue be blocking publication?

Not my call.

> @pixelzoom there are 5 sites calling `numberFormatter: {function}`.  Should we support `Property<function>|function`, or just `Property<function>`?

Since there's only 1 use where a Property is actually necessary, `{Property.<function>|function}` would certainly be less of a hassle for all of the other uses.  Similar to the `range` option for `NumberProperty`. 

But I'm still wondering...  If `numberFormtter` is the only thing that needs to be mutable, why don't you just make it private and create `setNumberFormatter` for mutation, which handles the update?  This doesn't seem like it really needs to be a Property.

**Comment by samreid** [comment]
I added `NumberProperty.setNumberFormatter` and used it to support StopwatchNode.  Ready for review.

**Comment by pixelzoom** [comment]
👍🏻 Closing.
