### ISSUE TITLE
Investigate potential jitter in the NumberDisplay

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#616]
From https://github.com/phetsims/scenery-phet/issues/565 and related to https://github.com/phetsims/scenery-phet/issues/402

I said:

> The NumberDisplay seems a little "jittery" or "jumpy" at times. ...

@pixelzoom replied:

>  I haven't seen this. Does it occur on specific browsers? Let's open a separate issue.

There are also notes about the jitter in https://github.com/phetsims/scenery-phet/issues/402 which should be reviewed.  I don't feel this blocks publication, but please correct me if I'm wrong.

**Comment by samreid** [comment]
I saw some jittering in my first test on Chrome.  Then when I tried to record it, I didn't see any jittering in Chrome, Safari or Firefox.  But when I watched the recording back, it had picked up the same kind of jitter I saw during the first time.  Here's what it looked like (in the 1/4 runs), this was recorded using Kap on Mac/Chrome

![Kapture 2020-08-10 at 15 58 52](https://user-images.githubusercontent.com/679486/89835743-8bdb5680-db22-11ea-9123-9a37b9cfe2be.gif)

**Comment by samreid** [comment]
I saw the jitter in my first run of monospace, but haven't seen it again and wasn't able to record it.  It looks like this:

![kap2](https://user-images.githubusercontent.com/679486/89836370-d7423480-db23-11ea-835f-f130e121458f.gif)

**Comment by samreid** [comment]
In the commit, I aligned to the left so there is no high frequency jitter.  It works great in the demos, even for the non-fixed fonts.  However, it looks odd for Gas Properties:

![image](https://user-images.githubusercontent.com/679486/89836913-02795380-db25-11ea-88bd-12de8c4d7b67.png)

I'll revert that for now.

**Comment by samreid** [comment]
I don't think we should publish any sims with a jittery NumberDisplay, so I've marked as blocks publication.

@ariel-phet can you please review this issue and advise?  Some options to consider:
* Use a fixed width font for stopwatch so it won't jitter
* Align left so the jittering is very low frequency instead of high frequency
* Center align to cut the amount of jittering in half
* Set up a test for QA to try to better understand when the jitter occurs
* Decide this is rare or subtle enough that it is not a problem
* Your idea here!

You can review the current behavior in master on phettest:
http://phettest.colorado.edu/scenery-phet/scenery-phet_en.html?brand=phet&ea&screens=3&component=StopwatchNode

**Comment by pixelzoom** [comment]
To clarify for @ariel-phet because I don't see it explicitly stated above...  

The jitter is caused by the fact that the time display is right-aligned and we're using a proportional font.  The default PhET font (`PhetFont`) is a proportional font, where each character occupies as much width as it needs.  So as the width of the numbers varies, the location of the ":" and "." separators moves around.

My vote would be to use a monospaced (aka fixed-width) font, where all characters have the same width.  The other alignments (left, center) look lousy.

**Comment by ariel-phet** [comment]
I have seen this sort of jitter in Collision Lab as well.

@samreid can we try a sans-serif monospace font. I believe "Lucida Console" is considered a web safe font that meets these criteria. "Courier New" I think is the one you are using above and it just looks a bit not so modern.

**Comment by samreid** [comment]
The font specification in master has been:

> font-family: Lucida Console,Arial,Bitstream Vera Sans Mono,monospace;

Note that Lucida Console is a monospace sans-serif font.

I was setting up a test harness to make it easy to compare "requested font" to "actual font" and discovered that the stopwatch text nodes were using the font family above for all but the last span.  To clarify: `richNumberFormatter` was only specifying this font family for the large numbers but not the small numbers, and `getRichNumberFormatter` was only specifying it for the numbers but not the units.

After changing this, I no longer see any jitter in Chrome or Safari.  I temporarily saw a new kind of jitter in Firefox (like the text adjusting), but I was not able to reproduce that.  I think I should commit this fix.

**Comment by samreid** [comment]
I've committed the fix described in the preceding comment, @pixelzoom or @ariel-phet can you please review?

**Comment by samreid** [comment]
After further testing, I'm still seeing a jitter even after the fix. Self-assigning for further investigation.

**Comment by samreid** [comment]
I slowed down the test harness by a factor of 30x and scaled up the stopwatch by 3x and saw that the jitter is happening for the substring "11"

![kap6](https://user-images.githubusercontent.com/679486/89854351-f30fff80-db50-11ea-8bf6-f2444b0c13e6.gif)

Perhaps the reason I was able to see this sometimes and not other times depended on whether "11" was hit exactly on any of the time steps.

**Comment by samreid** [comment]
https://blog.hubspot.com/website/web-safe-html-css-fonts says Andale Mono is a sans-serif websafe font.  It has correct spacing for "11" but unfortunately has dots in the zeros.

![image](https://user-images.githubusercontent.com/679486/89854675-b42e7980-db51-11ea-8713-31d0cf7f1d61.png)

**Comment by samreid** [comment]
According to https://www.cssfontstack.com/ Lucida Grande has 100% mac support and 0% windows support, and even though it is not listed as monospace, apparently the numbers are monospaced (at least on my copy of the font).  It looks like this:

![image](https://user-images.githubusercontent.com/679486/89855287-57cc5980-db53-11ea-9ec6-78c715181945.png)

**Comment by samreid** [comment]
Another topic for this issue, should `NumberDisplay` use monospace by default, or only for cases like the StopwatchNode?

**Comment by pixelzoom** [comment]
Why are we still considering proportional fonts like Lucida Grande?  Why aren't we just using a monospaced font?  If we can find one that's sans serif, great.  If not, use a serifed.  

> Another topic for this issue, should NumberDisplay use monospace by default, or only for cases like the StopwatchNode?

I'd say only for StopwatchNode. This "shifting" problem is specific to StopwatchNode, not generally undesirable. 

So my recommendation is to use a monospace font for StopwatchNode.

**Comment by pixelzoom** [comment]
Lucida Console is monospace and looks pretty nice: https://www.w3schools.com/cssref/css_websafe_fonts.asp

**Comment by samreid** [comment]
Lucida Console was the previous specification (in master), but it doesn't appear on Mac: https://www.cssfontstack.com/

**Comment by ariel-phet** [comment]
@pixelzoom I discussed with @samreid and although a "fully monospaced" font would be safer, it has some issues with the decimal and ":" taking up the same space as the numerals.

Interestingly, many proportional fonts actually have "tabular figures" -- aka monospaced numbers. We are going to go with a couple of proportional fonts the have monospaced numbers with good coverage on Mac and Windows, with a pure monospace font as the backup.

**Comment by samreid** [comment]
@ariel-phet and I committed the change above and tested on Mac/Chrome, Mac/Firefox, Mac/Safari, iOS Safari, Win/Chrome, Win/Firefox.  It seems good and we recommend to close the issue.

**Comment by samreid** [comment]
Reopening, we should check that the specified fonts have support for other languages.

**Comment by jonathanolson** [comment]
> Reopening, we should check that the specified fonts have support for other languages. @jonathanolson can you recommend how to check this? We went with font-family:Trebuchet MS,Lucida Grande,monospace; but only checked it in English.

I believe things should fall back properly (so if the user has the first font, BUT it doesn't have the glyphs for the language needed, only that will fall back). A brief test with a CJK language or something a bit rarer sounds helpful (just specify a locale and you can verify). I don't anticipate issues.

**Comment by samreid** [comment]
zh_CN looked like this in gas properties:

![image](https://user-images.githubusercontent.com/679486/90458157-d75da980-e0ba-11ea-824a-91aa800c37ed.png)

Thanks @jonathanolson, closing.
