### ISSUE TITLE
StopwatchNode API for numberFormatter needs work

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#618]
Related to #617 and https://github.com/phetsims/gas-properties/issues/188...  After trying to change the number of decimal places for the StopwatchNode in gas-properties, I found StopwatchNode's API to be confusing/lacking.

- [ ] `StopwatchNode.numberFormatter`  and `StopwatchNode.richNumberFormatter` provide no ability to adjust the number of decimal places.  You're stuck with 1/100th second.  If you want something else, you need to create your own numberFormatter using `getRichNumberFormatter`.   This is really odd, considering that the refactor of StopwatchNode was motivated primarily by number of decimal places.  It's also odd that one of these supports units and the other doesn't. Let's change these to functions that create formatters with a desired number of decimal places (defaulting to 2 for 1/100th) and optional units.

- [ ] `StopwatchNode.numberFormatter`, `StopwatchNode.richNumberFormatter`, and `StopwatchNode.getRichNumberFormatter` are all poorly documented.

- [ ] `StopwatchNode.numberFormatter`  and `StopwatchNode.richNumberFormatter` provide very specific, rigid formats.  `numberFormatter`  is "MM:SS:CC units", where all characters are the same size.  `richNumberFormatter` is "MM:SS:cc" where the "cc" (1/100ths) are in a smaller font, and there are no units. Their names are much too general.  Rename them to reflect their formats.

- [ ] `StopwatchNode.richNumberFormatter` (if we don't change change it to a creation function as proposed above) should be created by calling `StopwatchNode.getRichNumberFormatter`

Also worth noting is that in https://github.com/phetsims/scenery-phet/issues/617#issuecomment-673172616, @arouinfar is going to review uses of StopwatchNode in sims, decide which need decimals places adjusted, and perhaps make 1 decimal place the default.  The current API makes that change painful.

I wouldn't mind working on this. But it's not related to Natural Selection or pH Scale, so I'll need approval.   Assigned to @ariel-phet for assignment and prioritization.  @samreid FYI.

**Comment by samreid** [comment]
Likewise, I am happy to help on this.  Just let me know how it relates to my other priorities.

**Comment by ariel-phet** [comment]
Since @pixelzoom is quite familiar with this work and the scope is pretty reasonable, it would be most efficient for him to do the work.

Putting this in the "as time allows" category. @pixelzoom can fit this in where he feels appropriate (likely after Ph Scale is finished and NS is in a testing phase)

**Comment by samreid** [comment]
In the commit, I added an option for the number of decimal places in StopwatchNode (only in `getRichNumberFormatter`) since it was requested for Circuit Construction Kit in https://github.com/phetsims/circuit-construction-kit-common/issues/595.  

> It's also odd that one of these supports units and the other doesn't.

I didn't address that part, so I'll leave that top checkbox unchecked.

**Comment by pixelzoom** [comment]
StopwatchNode's API for numberFormatter was improved in the above commits

Summary of changes:

* StopwatchNode now has 2 pre-defined values for numberFormatter: `PLAIN_TEXT_MINUTES_AND_SECONDS` and `RICH_TEXT_MINUTES_AND_SECONDS` (the default).  They replace `numberFormatter` and `richNumberFormatter` respectively, and are hopefully more descriptive.

* `getRichNumberFormatter` has been renamed `createRichTextNumberFormatter`. It does not “get”, it “creates”. And what it creates is in RichText format.

* `StopwatchNode.RICH_TEXT_MINUTES_AND_SECONDS` is created using `createRichTextNumberFormatter`, eliminating duplicate code.

* The scenery-phet demo has been improved to demonstrate `StopwatchNode.PLAIN_TEXT_MINUTES_AND_SECONDS`, `StopwatchNode.RICH_TEXT_MINUTES_AND_SECONDS`, and a custom format created using `createRichTextNumberFormatter`.

* `StopWatchNode.DEFAULT_FONT` is used to initialize the NumberDisplay. When `StopwatchNode.PLAIN_TEXT_MINUTES_AND_SECONDS` was added to the scenery-phet demo, it displayed the jitter that was addressed in d80239dfe04acdbc8469d993d9c18f2decbb52c6 by specifying a font family.  Unfortunately that commit only addressed rich text, not plain text. That is now fixed.

* Option `showAsDecimal` (default `false`) has been changed to `showAsMinutesAndSeconds` (default `true`).  The former was not descriptive because both formats contain a decimal component.  Usages have been adjusted accordingly.

Tested in scenery-phet demo, energy-skate-park, gas-properties, and wave-interference.

@ariel-phet please assign someone to review.

**Comment by pixelzoom** [comment]
Adding the block-publication label until this is review, because this has the potential to introduce regressions.

**Comment by ariel-phet** [comment]
@Denz1994 says he can do this review tomorrow morning.

**Comment by Denz1994** [comment]
These changes look great. This was reviewed and tested in Capacitor-Lab-Basics (https://github.com/phetsims/capacitor-lab-basics/issues/274). The timer in that sim now has one decimal place using the API changes in this issue. Turning back over to @pixelzoom to address the minor suggestion below.

Suggestion:

- [ ] In `ComponentScreenView.js` `unitsProperty.link()` is using the value of `unitsProperty.value`, but it isn't passed in as a parameter in the function argument. Consider changing usage to:
```
unitsProperty.link( units => {
    customStopwatchNode.numberDisplay.setNumberFormatter( StopwatchNode.createRichTextNumberFormatter( {
      showAsMinutesAndSeconds: false, // because we're not showing minutes & seconds
      units: units // instead of unitsProperty.value
    } ) );
  } );
```

**Comment by pixelzoom** [comment]
Thanks @Denz1994.  unitsProperty listener has been improved.  Closing.
