### ISSUE TITLE
should StopwatchNode's NumberDisplay be instrumented? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#619]
From https://github.com/phetsims/scenery-phet/issues/617#issuecomment-672077401:

> Another general design issue is whether StopwatchNode's NumberDisplay should be PhET-iO instrumented. The NumberDisplay subcomponent is instrumented in some other UI components (NumberSpinner, FineCoaserSpinner). That's currently not the case for StopwatchNode. Yes, the client could instrument it via `numberDisplayOptions`, but not without having be responsible for making the tandem hierarchy look correct.

If we decide to instrument StopwatchNode's NumberDisplay (which we've done for other UI components) then the number of decimal places that we display is becomes more important. For some sims, updating its textProperty at 1/100 intervals is spam in the PhET-iO data stream.  And/or we may need a way for the textProperty to be marked as phetioHighFrequency via the StopwatchNode API.

Assigning to @ariel-phet for prioritization and assignment.

**Comment by ariel-phet** [comment]
@pixelzoom I don't think we should instrument this NumberDisplay, I am not sure why that would be useful.

I would say if a client request of this nature comes up, we would consider it, but I am not sure what purpose it would serve. In the data stream you will have the "sim time" at which the stop watch was stop and started. 

Closing until this feature is requested.
