### ISSUE TITLE
Update velocity/acceleration in PhetColorScheme and add momentum

### ISSUE THREAD

**Issue by arouinfar** [phetsims/scenery-phet#621]
Discussion started in https://github.com/phetsims/collision-lab/issues/148

The colors used for velocity and acceleration in [PhetColorScheme](https://github.com/phetsims/scenery-phet/blob/master/js/PhetColorScheme.js) are holdovers from Java and we have been using different colors in HTML5.

Currently, the colors in PhetColorScheme are:
ACCELERATION: `rgb( 0, 255, 0 )`
VELOCITY: `rgb( 255, 85, 0 )` (RED_COLORBLIND)

The colors commonly used in HTML5 are green for velocity and yellow for acceleration, though there have been some  variances.

| Sim | Velocity | Acceleration |
| --- | --- | --- |
| [collision-lab](https://github.com/phetsims/collision-lab/blob/master/js/common/CollisionLabColors.js) | `rgb( 0, 255, 0 )` | N/A |
| [gravity-and-orbits](https://github.com/phetsims/gravity-and-orbits/blob/master/js/common/view/GravityAndOrbitsSceneView.js) | `rgb( 255, 85, 0 )` (RED_COLORBLIND) | N/A |
| [masses-and-springs ](https://github.com/phetsims/masses-and-springs/blob/master/js/common/view/MassesAndSpringsColorProfile.js) | `rgb( 41, 253, 46 )` | `rgb( 255, 253, 56 )` |
| [pendulum-lab](https://github.com/phetsims/pendulum-lab/blob/master/js/common/PendulumLabConstants.js) | `rgb( 41, 253, 46 )` | `rgb( 255, 253, 56 )` |
| [projectile-motion](https://github.com/phetsims/projectile-motion/blob/master/js/common/ProjectileMotionConstants.js) | `rgb( 50, 255, 50 )` | `rgb( 255, 255, 50 )` |

I'd prefer to use the colors from projectile-motion for PhetColorScheme.VELOCITY and PhetColorScheme.ACCELERATION.

Collision Lab additionally has a vector representation for momentum `rgb( 50, 50, 255 )`. Momentum could appear in other PhET sims, so it would be good to add this color to PhetColorScheme.

@ariel-phet asked @brandonLi8 to make these changes to PhetColorScheme, so assigning to him. Once the changes have been made, please reassign to me so I can open issues in the relevant sim repos to update the colors.

**Comment by jonathanolson** [comment]
Applied in common code and collision-lab. @arouinfar back to you!

**Comment by arouinfar** [comment]
Thanks @jonathanolson, looks good. I've created issues in the sim repos for the outstanding work, so I think we can go ahead and close this one.
