### ISSUE TITLE
buggy fill/stroke code in FaceNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#623]
Noted while converting FaceNode to ES6 for https://github.com/phetsims/tasks/issues/1044.

In 72c30fee4cc1078745c7d5e64eef390aea03f5ae, @jonathanolson added this to FaceNode:

```js
    // @private {Property.<Color>}
    this.headFillProperty = new PaintColorProperty( options.headFill );

    // The derived property listens to our headFillProperty which will be disposed. We don't need to keep a reference.
    options.headStroke = options.headStroke || new DerivedProperty( [ this.headFillProperty ], function( color ) {
      return color.darkerColor();
    } );
```

`headFillProperty` never gets used (other than to be disposed), it's `@private`, and I can find no usages where fill or stroke are mutated.  So I don't understand what the intent was here.  Did you mean to pass  `headFillProperty` to the head part of FaceNode, so that its color could be changed dynamically? If so, why is it private?

So I think we should back this out, deleting `headFillProperty`, and reverting to:

```js
options.headStroke = options.headStroke || Color.toColor( options.headFill ).darkerColor();
```

@jonathanolson Do you agree?

**Comment by pixelzoom** [comment]
I went ahead and reverted  72c30fe.  Assigning to @jonathanolson to review.  If you intended to add some feature here, feel free to make another pass at it.

**Comment by jonathanolson** [comment]
I'm a bit confused, when I look at the commit, I see `this.headFillProperty` used directly by the DerivedProperty in `new DerivedProperty( [ this.headFillProperty ], ...`

Presumably in this case it could be converted to a local variable instead of a field. Objections for me to re-apply the commit, but with a local variable instead?

**Comment by jonathanolson** [comment]
Also, this wraps whatever ColorDef was provided into a Color Property, so that we can properly darken that color.

**Comment by pixelzoom** [comment]
Discussed with @jonathanolson and restored 72c30fe.  This is one confusing piece of code, but I don't have time to improve it.  Feel free to do whatever you want with it.

**Comment by pixelzoom** [comment]
This has been assign to @jonathanolson for review for 5+ months.  I'm confident in the changes, so I'm going to close this.
