### ISSUE TITLE
MemoryTestsScreenView is buggy duplicate code

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#624]
Noted while working on https://github.com/phetsims/tasks/issues/1044, converting classes to ES6. 

In https://github.com/phetsims/sun/commit/6a61a07d74b3871b6d4c8d01c48413dafa45384b, I converted sun's MemoryTestsScreenView to ES6, and did some major clean up.  

Then I discovered that scenery-phet had an almost identical copy, also named MemoryTestsScreenView.  That copy has a ton of dead (commented out) code, and a serious flaw -- it will never sets `numTests` back to zero, so after the first call to `step`, every subsequent call is a no-op.

I'm going to attempt to factor out common code and correct problems.  Then I'll assign to @samreid (the author) to review.

**Comment by samreid** [comment]
It looks like the sun one is more up-to-date.  Likely scenery-phet should use the same strategy or implementation.

**Comment by pixelzoom** [comment]
The sun one is more up-to-date because of phetsims/sun@6a61a07.

**Comment by pixelzoom** [comment]
Ready for review and additional cleanup by @samreid.   

Could you please add documentation to the header comment? What are we testing about memory? Are we just testing that dispose isn't leaking, or something more?

SceneryPhetMemoryTestsScreenView is now a subclass of MemoryTestsScreenView.  I deleted all of the dead code in SceneryPhetMemoryTestsScreenView.

After fixing the iteration bug in SceneryPhetMemoryTestsScreenView's `step` method, the default value of `memoryTestCreationMax : 10000` brings the browser to a halt, requiring a force quit.   So I deleted query parameter `memoryTestCreationMax` and replaced it with option `iterationsPerStep` to MemoryTestsScreenView.  SceneryPhetMemoryTestsScreenView uses `iterationsPerStep: 10`.

I have no idea why it's necessary to iterate multiple times in `step` for scenery-phet but not for sun.  If it's not necessary, then I recommend deleting that option.

**Comment by samreid** [comment]
The changes look good.  I haven't used either of these classes for memory testing lately, and I'm not aware of anyone using these recently.  We are getting better about avoiding memory leaks before they are created, and catching them with in-sim testing.  OK if we delete these files?

**Comment by pixelzoom** [comment]
I've never used these. OK with me to delete.

**Comment by samreid** [comment]
Removed, closing.
