### ISSUE TITLE
CT: Cannot set property 'grabDragInteraction' of undefined

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#625]
In d8270ac9df1cf0ac17c30e11b27df728805b6e4f, @zepumph added 

```js
  // Creates a demo for GrabDragInteraction
  const getDemoGrabDragInteraction = tandem => {
    return function( layoutBounds ) {
...
      this.grabDragInteraction = new GrabDragInteraction( rect, {
...
   };
  };
```

When I converted `function( layoutBounds )` to `layoutBounds =>` for https://github.com/phetsims/tasks/issues/1044, that resulted in `this` becoming undefined, and CT failing with:

```
Uncaught TypeError: Cannot set property 'grabDragInteraction' of undefined
```

To reproduce manually:
1. Run the scenery-phet demo
2. Go to "Components" screen
3. Choose "GrabDragInteraction" from combo box

I could revert the change.  But I'm wondering why this private function (defined outside of the class definition) needs to assign to `this.grabDragInteraction`.  I'm guessing that this was a sneaky way of avoiding a lint error, and has now bitten me.  @zepumph?

**Comment by pixelzoom** [comment]
Fixed in the above commit. @zepumph please review.

**Comment by zepumph** [comment]
Sorry about the trouble, it was indeed to bypass the lint error. I updated the disable comment though. As you wrote it, it disabled the rule for the rest of the file.

**Comment by pixelzoom** [comment]
Thanks for fixing the eslint-disable comment.  I didn't realize the distinction, and I made (and fixed) the same mistake in NaturalSelectionScreenView.
