### ISSUE TITLE
convert NumberPicker to ES6 and new input listeners

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#626]
For https://github.com/phetsims/tasks/issues/1044 (ES6 conversion) and https://github.com/phetsims/scenery/issues/1078 (conversion to new input listeners).  Promoting this to its own issue because it was more complicated than other conversions, the work was spread out over several commits, commits were not properly associated with relevant issues, it apparently resulted in a new issue (https://github.com/phetsims/sun/issues/627), and I've been assigned to review the work that is relevant to phetsims/scenery#1078.

So first I need to identify what was really relevant to phetsims/scenery#1078.

There were no commits associated with  https://github.com/phetsims/tasks/issues/1044, which seems incorrect.

Commits associated with https://github.com/phetsims/scenery/issues/1078 are: 

ES6:
https://github.com/phetsims/scenery-phet/commit/400e2ffff01263d4f2eb4c8962b974689fefbe5f
https://github.com/phetsims/scenery-phet/commit/b703053dab6228b18d113c214cd5bbbd2f9a0eec
https://github.com/phetsims/scenery-phet/commit/dd355d204701c8aa08e5ff976465688fb3828a5c

listeners:
https://github.com/phetsims/scenery-phet/commit/08693c7d1895a95371cb4bd33b45ae30926e38a2
https://github.com/phetsims/scenery-phet/commit/ad7eed6680219bd0955d18f95263437e56fe5cf7
https://github.com/phetsims/scenery-phet/commit/7608dfb96f745313afc2b5eb0c8cda70e56b5aee
https://github.com/phetsims/scenery-phet/commit/acc1cf1012731ea17e62ed06b39f6fd4012b3768
https://github.com/phetsims/scenery-phet/commit/e45045041661d4c9fc795ab124d36af8b198faf4

... and it doesn't look like all of those are truly related to phetsims/scenery#1078.

**Comment by pixelzoom** [comment]
Since ES6 conversion touches the entire file, it's difficult to see what was changed for phetsims/scenery#1078 (new input listeners).

I've identify these commits as likely to be associated with phetsims/tasks#1044 (ES6), and tagged them as such:

https://github.com/phetsims/scenery-phet/commit/400e2ffff01263d4f2eb4c8962b974689fefbe5f
https://github.com/phetsims/scenery-phet/commit/b703053dab6228b18d113c214cd5bbbd2f9a0eec

@samreid Did you do ES6 conversion first (as a separate step) and was all of the ES6 conversion in fact done in those 2 commits?

**Comment by samreid** [comment]
> @samreid Did you do ES6 conversion first, as a separate step? And was all of the ES6 conversion in fact done in those 2 commits?

The ES6 conversion was done first, in the commits labeled as "convert var => const" and "convert to class" (first 3 commits). 

commit dd355d204701c8aa08e5ff976465688fb3828a5c
    Convert to class, see https://github.com/phetsims/scenery/issues/1078

commit b703053dab6228b18d113c214cd5bbbd2f9a0eec
    Convert to class, see https://github.com/phetsims/scenery/issues/1078

commit 400e2ffff01263d4f2eb4c8962b974689fefbe5f
    Convert var=>const, see https://github.com/phetsims/scenery/issues/1078

**Comment by pixelzoom** [comment]
@samreid's comments in https://github.com/phetsims/scenery/issues/1078 that are relevant to my review of NumberPicker:

https://github.com/phetsims/scenery/issues/1078#issuecomment-694954322
> I converted one listener in NumberPicker in the commit, but I am very confused about the 'out' state. When is the NumberPicker supposed to be 'out' and how does it differ from 'up'? I don't see that documented anywhere.
> 
> UPDATE: It is described in ButtonListener.

https://github.com/phetsims/scenery/issues/1078#issuecomment-694969471:
> I converted NumberPicker to use FireListener, and combined the listeners. I am not familiar with NumberPicker and have not used it extensively in any sims, so this could use a careful review. Assigning to @pixelzoom for review, since he is listed as primary author of NumberPicker, and I see its usage in sims like Graphing Lines. I did my testing using the scenery-phet harness (for which I also enabled sound), and I also tested in Graphing Lines. I did not test disabling an in-use number picker.

**Comment by pixelzoom** [comment]
NumberPicker appears to be working correctly.

In the above commits:
* converted to arrow functions and named functions where appropriate (should have been done during ES6 conversion)
* added a test for `enabledProperty` to scenery-phet demo
* fixed various doc, bringing it up to PhET standards

I also noticed that NumberPicker has gotten a bit messy, to be cleaned up in #627.

@samreid  question: in `NumberPickerInputListener` why didn't you use a Multilink, like this?

```js
constructor( stateProperty, options ) {
  super( options );
  Property.multilink( 
    [ this.isOverProperty, this.isPressedProperty ],
    ( isOver, isPressed ) => {
      stateProperty.set( isOver && !isPressed ? 'over' :
                         isOver && isPressed ? 'down' :
                         !isOver && !isPressed ? 'up' :
                         !isOver && isPressed ? 'out' :
                         assert && assert( 'bad state' )
      );
    } );
}
```

Back to @samreid.

**Comment by samreid** [comment]
The multilink looks like it will work well, good idea!  Let me know if you would like me to implement that change.

**Comment by pixelzoom** [comment]
I implemented the Multilink.  Seems like this can be closed.  Reopen if I missed anything.
