### ISSUE TITLE
NumberPicker cleanup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#627]
Noted while reviewing changes to NumberPicker for https://github.com/phetsims/scenery-phet/issues/626. There is more cleanup to be done here.

Since its creation, NumberPicker used "up" and "down" terminology for its arrows.  That was a little confusing because there is also 'up' and 'down' button state. Then a11y was added to NumberPicker in bd233bf8f798e0db98a550c31bd7e73f48994b53 for #318 by @jessegreenberg, and "increment" and "decrement" was introduced.   So the implementation has become unnecessarily confusing.   To fix that:

- [x] replace "up" and "down" with "increment" and "decrement" where appropriate
- [x] convert button "state" values to an Enumeration (they are currently `{string}` 'up'|'down'|'over'|'out')

**Comment by pixelzoom** [comment]
I'll wait to do this work until https://github.com/phetsims/scenery-phet/issues/626 is closed.

**Comment by pixelzoom** [comment]
I'll wait to do this work until https://github.com/phetsims/scenery-phet/issues/626 is closed, so that @samreid and I don't collide.

**Comment by pixelzoom** [comment]
Here's what will change in the public API:

options:
* upFunction -> incrementFuction
* downFunction -> decrementFuction
* upEnabledFunction -> incrementEnabledFunction
* downEnabledFunction -> decrementEnabledFunction

PhET-iO:
* upInputListener -> incrementInputListener
* downInputListener -> decrementInputListener

**Comment by pixelzoom** [comment]
Work is done.

Summary of what has changed in the public API:

Fields:
* In anticipation of general work on `enabledProperty` (converting to use the `EnabledComponent` mixin), visibility of `this.enabledPropery` was change from `@private` to `@public`.

These `options` were renamed in 9619ea2, and in sim-specific repos (gravity-force-lab-basics, number-line-operations, vector-addition, unit-rates):
* upFunction -> incrementFuction
* downFunction -> decrementFuction
* upEnabledFunction -> incrementEnabledFunction
* downEnabledFunction -> decrementEnabledFunction

These tandem names were changed in b13963e, and are consistent with the "increment" and "decrement" terminology used in other similar UI components.  This changes the PhET-iO API of any sim with a NumberPicker.
* upInputListener -> incrementInputListener
* downInputListener -> decrementInputListener

@ariel-phet please assign someone to review.  A designer should sign off on the tandem name changes.

**Comment by ariel-phet** [comment]
Assigning @jonathanolson at high priority to review (since potentially blocks some upcoming sims)

@pixelzoom I can sign off on those name changes, they are a good change in my opinion

**Comment by jonathanolson** [comment]
Changes look great! And it looks like since the tandem changes were ok'ed by @ariel-phet this can be closed.
