### ISSUE TITLE
Documentation of listener arrays seems incorrect

### ISSUE THREAD

**Issue by jbphet** [phetsims/scenery-phet#632]
While working on https://github.com/phetsims/faradays-law/issues/174 I noticed that the commentary in `GrabDragInteraction` that describes `listenersForDrag` and `listenersForGrab` seems incorrect and was hard to understand.  The documented type is `{Function[]}`, but the types in all examples that I saw are definitely not function arrays.  Also, it talks about swapping the PDOM structure - which I found hard to understand given that I don't know much about the PDOM - but while working with @jessegreenberg, he told me that these were arrays of listeners that are hooked up and unhooked as the state of the node transitioned between the "grabbable" and "grabbed" state.  That was _way_ easier to understand.  If this is indeed true, I'd recommend renaming them to `listenersForDragState` and `listenersForGrabState` or something similar.  The current name makes it sound as though they are listeners for a particular event.

**Comment by zepumph** [comment]
I definitely like "state" more than "mode". Will you please review and see if that is clearer?

**Comment by jbphet** [comment]
Looks much better.  I reformatted the comment for this to fit within the 120 column limit, and with that, I think we're done here.  Closing.
