### ISSUE TITLE
GrabDragInteraction onGrab should forward an event

### ISSUE THREAD

**Issue by jbphet** [phetsims/scenery-phet#633]
While working on https://github.com/phetsims/faradays-law/issues/174, I found myself wanting to interpret the event in the `onGrab` handler that I was using in an instance of `GrabDragInteraction` so that I could tell whether the drag came from the keyboard or a mouse/touch action.  I ended up finding another way to accomplish what I needed to do, but I think others in the future may run into the same need, so I think it would be wise to make the event available in this handler.

**Comment by zepumph** [comment]
Looks like this was added in https://github.com/phetsims/scenery-phet/commit/40a051092a0d142994135b190e2613b907d43131. 

Thanks for the report, sorry it took so long to get to.
