### ISSUE TITLE
Update SliderKeyboardHelpSection with more options

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#635]
In https://github.com/phetsims/ratio-and-proportion/issues/82, a slider variation was desired for the ratio hands. Instead of duplicating this all over the place, I think making the slider keyboard section more powerful is the way to go. Basically the customization needed is to:

* Change the title (already supported)
* Change the verb (from "adjust" to something else, like "move")
* Maximum word (bottom sometimes)
* Minimum word (top sometimes)
* Provide a noun to overwrite "slider" (like " left or right hand")

- [ ] Note that GFL implements a custom section very similar to this, and we likely should change that once this is implemented.

**Comment by zepumph** [comment]
We have to be careful here, as published sims have been sent out with string keys used in this dialog, so we may need to add new ones without removing the current, hard-coded ones.

**Comment by zepumph** [comment]
@jessegreenberg could you give this a spot check before I take over the conversion of GFL. Note that I kept old keys for published version.

**Comment by jessegreenberg** [comment]
Looks good to me. I checked that the keys in d476145aab75658305ae96d817013e4cdda2285e were not in any translations, so it seems safe. Thanks!

**Comment by zepumph** [comment]
Thanks.
