### ISSUE TITLE
AccessibleValueHandler.a11yRepeatEqualValueText is broken

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#640]
I found while working on https://github.com/phetsims/ratio-and-proportion/issues/221 that I want the same valuetext to repeat on each key press. I thought that this would work:

https://github.com/phetsims/sun/blob/f8156a38545ab207d437aca485e2102471487b75/js/accessibility/AccessibleValueHandler.js#L364-L368

But, at least on NVDA/chrome, it was not. I put a console log into that if statement, and confirmed that we are in there, thus we are appending that hair space. We just don't get a repeat aria-valuetext. 

@jessegreenberg, it would be nice to brainstorm potential solutions tomorrow with you, because this is likely desired for interviews Wednesday and beyond.

**Comment by zepumph** [comment]
https://github.com/phetsims/sun/blob/f8156a38545ab207d437aca485e2102471487b75/js/accessibility/AccessibleValueHandler.js#L329-L351

**Comment by zepumph** [comment]
https://github.com/phetsims/sun/blob/f8156a38545ab207d437aca485e2102471487b75/js/accessibility/AccessibleValueHandler.js#L329-L333

**Comment by jessegreenberg** [comment]
@zepumph and I worked on this today and came up with an improved way to add a the 'hairspace' character to the end of the value-text to ensure that the AT reads the new value even when the content is the same. Anything else to do here @zepumph?

**Comment by zepumph** [comment]
All looks good to me!

**Comment by zepumph** [comment]
(sorry for adding this to scenery-phet even though the component is in sun). I think I'll transfer for history.
