### ISSUE TITLE
StopwatchNode is greyed out when rasterized

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#641]
I noticed that using Node.rasterized on a StopwatchNode will return a greyscaled image. I saw this in energy-skate-park, circuit-construction-kit, and wave-interference. Removing the `rasterized` call for each of these usages has the StopwatchNode displayed in color. @jonathanolson this seems like it could be related to the new greyscale feature, assigning to you.

**Comment by jonathanolson** [comment]
I forgot there was an issue for this! I believe it was fixed in https://github.com/phetsims/scenery/commit/712a27830bcdb894f913911f94d5c53b6d7634d4, can you verify?

**Comment by jessegreenberg** [comment]
Yes, it looks great thanks!
