### ISSUE TITLE
Rename radius option in ZoomButton

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#645]
In https://github.com/phetsims/griddle/issues/91, @zepumph mentioned that `radius` might be an unused option in ZoomButton, because ZoomButton is a RectangularPushButton not a RoundPushButton. `radius` is the option that defines the radius for a RoundButtonView. In this case `radius` also defines the radius for the magnifying glass of the ZoomButton

In https://github.com/phetsims/griddle/issues/91 @zepumph said 
> It would by my opinion to rename this option so that this confusion doesn't happen again. What about zoomRadius?

@jessegreenberg said
> Sure, I could see that. There other options with magnifyingGlass as the prefix so maybe magnifyingGlassRadius

@pixelzoom (original author) do you have an opinion?

**Comment by pixelzoom** [comment]
No opinion on ZoomButton.  Now that we have ZoomButtonGroup (more modern-looking zoom buttons), I doubt that I'll ever use ZoomButton again.

**Comment by jessegreenberg** [comment]
OK good to know, thanks - I wasn't aware of ZoomButtonGroup. I will go ahead with the rename in ZoomButton.

**Comment by arouinfar** [comment]
> I doubt that I'll ever use ZoomButton again

Less than a week ago, we made the explicit decision to continue using zoom buttons with the magnifying glass icons in the ScrollingChartNodes in CCK: AC because +/- is a overloaded in the context of that sim. We will likely make a similar decision again in the future.

Are the Natural Selection-style flat +/- buttons the only zoom buttons we are going to be able to use in the future? If so, that is a very major design decision that should have been made with all stakeholders.

**Comment by jessegreenberg** [comment]
The option has been renamed to `magnifyingGlassRadius`.  I am not seeing a mention of deprecation in ZoomButton or elsewhere, though I do see ZoomButtonGroup in CCK. Ill reassign to @pixelzoom to respond to https://github.com/phetsims/scenery-phet/issues/645#issuecomment-732450377.

**Comment by pixelzoom** [comment]
> Are the Natural Selection-style flat +/- buttons the only zoom buttons we are going to be able to use in the future? If so, that is a very major design decision that should have been made with all stakeholders.

I'm not aware of any such decision and I didn't mean to imply that - sorry if this upset you.

**Comment by pixelzoom** [comment]
@arouinfar said:
> Are the Natural Selection-style flat +/- buttons the only zoom buttons we are going to be able to use in the future? If so, that is a very major design decision that should have been made with all stakeholders.

I'm not aware of any such decision and I didn't mean to imply that - sorry if this upset you.   I said "I doubt that I'll ever use ZoomButton again" (emphasis on "I", not the entire project), and that was based on the sims that I've worked on in the past, and the sims that I'm working on now.

**Comment by arouinfar** [comment]
Thanks for the clarification @pixelzoom! I think the new zoom buttons look great, and will definitely be preferred a lot of the time. I just wanted to make sure that we weren't losing the other style too.

**Comment by jessegreenberg** [comment]
OK, that was all for this issue closing.
