### ISSUE TITLE
Should ZoomButtonGroup support magnifying glass icons?

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#647]
From https://github.com/phetsims/circuit-construction-kit-common/issues/620 "Zoom buttons need magnifying glasses".

Circuit construction kit is using ZoomButtonGroup for the chart zoom in/out buttons, in the aforementioned issue, we said:

> From today's design meeting, "+" and "-" are overloaded in CCK, and showing those as button icons without other context will be confusing.  We need the magnifying glass icons.  This is for the charts and for the play area zoom buttons.

It currently looks like this:

![image](https://user-images.githubusercontent.com/679486/100654975-dcf89b80-3307-11eb-8560-4682c76be9cf.png)

Assigning to the primary developer for ZoomButtonGroup for discussion.

**Comment by samreid** [comment]
I added a comment in https://github.com/phetsims/circuit-construction-kit-common/issues/620#issuecomment-735996468 about what the other zoom buttons in CCK AC look like.  Maybe we should wait for a conclusion on that conversation before going too far with this issue.

**Comment by pixelzoom** [comment]
Strong push back on adding magnifying glasses to ZoomButtonGroup.  If you need magnifying glasses, use ZoomButton.

**Comment by pixelzoom** [comment]
Strong push back on adding magnifying glasses to ZoomButtonGroup.  This was specifically designed for cases where you do not need (heavyweight) magnifying glasses. If you need magnifying glasses, use ZoomButton.

**Comment by samreid** [comment]
Are you recommending a parallel implementation of ZoomButtonGroup that uses the magnifying glass icons?

**Comment by pixelzoom** [comment]
Go for it.

**Comment by pixelzoom** [comment]
> UPDATE: Why not make the icons options that default to "+" and "-"?

More complexity, more cost.  Imo unnecessary.  That's my opinion.  If someone wants to add it, go for it -- and please add yourself as `@author`.

**Comment by samreid** [comment]
On hold until we have a consensus in https://github.com/phetsims/circuit-construction-kit-common/issues/620

**Comment by samreid** [comment]
We added support in https://github.com/phetsims/circuit-construction-kit-common/issues/620, closing.
