### ISSUE TITLE
Should PaintDef support Property<Paint>?

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#651]
Discovered during https://github.com/phetsims/bamboo/issues/16.  Here is the current definition of PaintDef:

```js
  isPaintDef( paint ) {
    return paint === null ||
           typeof paint === 'string' ||
           paint instanceof Color ||
           paint instanceof Paint ||
           ( paint instanceof Property && (
             paint.value === null ||
             typeof paint.value === 'string' ||
             paint.value instanceof Color
           ) );
  }
```

Note that it supports `Paint` but not `Property<Paint>`.  Is that by design, or an oversight?  If it is by design, it should be documented.  If it is an oversight it should be documented or corrected.

@jonathanolson can you please recommend how to proceed?

**Comment by jonathanolson** [comment]
It's not set in stone, however it makes the implementation of `PaintObserver` simpler. Have we run into cases where that would be useful?

PaintObserver would technically need to listen to 3 different levels if we add that (or could be recursive if we allow `Property<paintDef>`. Notably, the `Property` value could change, Color Properties in the Gradient could change, AND the Colors themselves specified in those Properties could change. So it would be more code and more memory usage in general to support it.

Thoughts? Should I just add the blurb above into PaintDef?

**Comment by samreid** [comment]
Thanks for helping me understand--I'd recommend documentation for now.

**Comment by jonathanolson** [comment]
Added documentation, closing.
