### ISSUE TITLE
default options need adjusting in ZoomButtonGroup hierarchy

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#653]
Related to https://github.com/phetsims/scenery-phet/issues/652.  Something I noticed as  I'm converting ph-scale to MagnifyingGlassZoomButtonGroup in https://github.com/phetsims/ph-scale/issues/206...   

ZoomButton uses `buttonAppearanceStrategy: RectangularButton.ThreeDAppearanceStrategy` (the default), while  ZoomButtonGroup uses  `buttonAppearanceStrategy: RectangularButton.FlatAppearanceStrategy`.   

If we want to convert sims from ZoomButton to MagnifyingGlassZoomButtonGroup, and have them look the same as they do now, that means that every sim is going to have to set `buttonAppearanceStrategy: RectangularButton.ThreeDAppearanceStrategy` for MagnifyingGlassZoomButtonGroup.  And we don't want to do that.

So I think the buttonAppearanceStrategy` override should be moved from ZoomButtonGroup to PlusMinusZoomButtonGroup, so that MagnifyingGlassZoomButtonGroup uses 3D buttons. And if @samreid needs them to be flat in CCK:AC, then override `buttonAppearanceStrategy` there.

**Comment by pixelzoom** [comment]
Ditto for cornerRadius.  `cornerRadius: 0` is specific to PlusMinusZoomButtonGroup, it doesn't belong in ZoomButtonGroup. Every sim ported to MagnifyingGlassZoomButtonGroup will be forced to set `cornerRadius: 4` to keep the same look.

**Comment by pixelzoom** [comment]
MagnifyingGlassZoomButtonGroup should default to `buttonOptions.baseColor: PhetColorScheme.BUTTON_YELLOW` in order have the same look as ZoomButton.  Otherwise every converted sim will need to set baseColor.

**Comment by pixelzoom** [comment]
Ditto for `magnifyingGlassOptions.glassRadius`.  MagnifyingGlassZoomButtonGroup uses 10, ZoomButton uses 15. I'm guessing the values here were set for CCK:AC.  They need to be set to match ZoomButton, or converting sims from ZoomButton to MagnifyingGlassZoomButtonGroup is going to be a pain.

**Comment by pixelzoom** [comment]
In the above commits, I've adjusted the default options so that:

* PlusMinusZoomButtonGroup has buttons that are flat, white, square corners.
* MagnifyingGlassButtonGroup has buttons that default to the look of ZoomButton (3D, yellow, rounded corners,...)
* CCK:AC overrides defaults for MagnifyingGlassButtonGroup to provide the "look" that's desired in that sim

@samreid please review.

**Comment by samreid** [comment]
I reviewed the commits and tested the default components in the scenery-phet harness, and tested the buttons in CCK-AC.  Everything looks good to me, thanks!  Closing.
