### ISSUE TITLE
Rename dynamicProperty to mutedProperty for SelfVoicingQuickControl

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#654]
I came across this while looking for example of DynamicProperty for another task that I was working on.  In SelfVoicingQuickControl.js:

```js
    // the webSpeaker uses enabledProperty, the push button uses "muted" terminology -
    // dynamic Property maps between the two so that the button can be pressed when
    // it it is actually not enabled
    const dynamicProperty = new DynamicProperty( new Property( webSpeaker.enabledProperty ), {
      bidirectional: true,
      map: enabled => !enabled,
      inverseMap: muted => !muted
    } );
```

This would be clearer if `dynamicProperty` were renamed to `mutedProperty`, especially since the parameter for `inverseMap` is named `muted`.

**Comment by pixelzoom** [comment]
@jessegreenberg Permission to do this myself?

**Comment by pixelzoom** [comment]
I made this change.  Highly unlikely that it broke anything since it's a rename of a local `const`.  But I don't know how to test self-voicing.  So to be safe, labeling this as blocking, and @jessegreenberg please review with high priority.

**Comment by jessegreenberg** [comment]
Thanks, the rename looks good.
