### ISSUE TITLE
NumberPicker increment and decrement listeners fire when grayed out

### ISSUE THREAD

**Issue by jbphet** [phetsims/scenery-phet#657]
The root cause of the odd behavior described in https://github.com/phetsims/number-line-operations/issues/61 is that the fire listeners for the increment and decrement buttons are being fired when the numerical value is at or beyond the specified range.  Also problematic is that when the arrow buttons are grayed out and the corresponding half of the readout isn't highlighting, the cursor still changes to be a hand.

In my opinion, these portions of `NumberPicker` should not be pickable when at the boundary conditions.

I was able to correct the problem by adding the following two lines of code to `NumberPicker` at line 352, but this component looks to be pretty highly evolved, so I think the original author should have a look and decide how to best handle this.  The lines were:
```
    incrementEnabledProperty.linkAttribute( incrementParent, 'pickable' );
    decrementEnabledProperty.linkAttribute( decrementParent, 'pickable' );
```

Assigning to @pixelzoom to consider and suggest or implement a solution.

**Comment by jbphet** [comment]
I went ahead and implemented a fix for this because I needed to put out a dev release for QA testing.  I did something a little different from what I described above, see the commit.

I regression tested this on number-line-operations and unit-rates, and tested in both a mouse-driven and touch-driven environment and didn't see any problems.

@pixelzoom - please review.  If you end up making changes, please make sure https://github.com/phetsims/number-line-operations/issues/61 is open and assigned to me when you're done so that I can re-test.

**Comment by pixelzoom** [comment]
The change in 1a38780 looks correct to me, and I tested in a few sims that use NumberPicker. 

Back to @jbphet in case there's anything else to do for this or phetsims/number-line-operations#61. Feel free to close.
