### ISSUE TITLE
LaserPointerNode needs an option to move the button closer to the front.

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#661]
For Bending Light, the original design calls for the button to be closer to the nozzle.  I think this is so that there is a bigger grab region for rotating the laser pointer.  This is for https://github.com/phetsims/bending-light/issues/339

**Comment by samreid** [comment]
Implemented in the commit and tested in https://github.com/phetsims/bending-light/issues/339, @pixelzoom can you please review?

**Comment by pixelzoom** [comment]
The approach looks reasonable to me.  But the type expression for `getButtonLocation` is incomplete, and I would name its param `bodyNode` -- `body` looks like a model element to me.    Changes made in the above commit, back to @samreid for review.

**Comment by samreid** [comment]
Thanks for the improvement, I added one more fix which seemed straightforward, closing.
