### ISSUE TITLE
dead code in ProbeNode.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#664]
Encountered while working on https://github.com/phetsims/scenery-phet/issues/488.

Introduced by @samreid in https://github.com/phetsims/scenery-phet/commit/c2c94c4019e629ab755940eaf7304af4f86deb04:

```diff
+      //new Circle( 3, { center: gradientSource, fill: 'blue' } ),
+      //new Circle( 3, { center: gradientDestination, fill: 'red' } )
```

If this code is useful for some reason, please document why it's commented out.  Otherwise delete it.

**Comment by pixelzoom** [comment]
I'm guessing that these are added to show the origins of some subcomponents.  The preferred way to do that is something like:

```js
// Show the origin of ...
if ( phet.chipper.queryParameters.dev ) {
   children.push( new Circle( ... ) );
} 
```

**Comment by samreid** [comment]
I removed the unused code, closing.
