### ISSUE TITLE
SpeakerHighlighter should not depend on joist

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#670]
From https://github.com/phetsims/joist/issues/686, we should allow anything to use this without requiring a sim.

**Comment by zepumph** [comment]
@jessegreenberg please review. Does this seem good to you?

**Comment by jessegreenberg** [comment]
This change looks good, and I read through https://github.com/phetsims/joist/issues/686 to understand the context of getGlobal a bit more. Thanks!
