### ISSUE TITLE
Some sims fail to start in the Android app

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#674]
From https://github.com/phetsims/gravity-and-orbits/issues/382.  We determined that specifying font `'"Trebuchet MS", "Lucida Grande", monospace'` crashes Gravity and Orbits on startup (in the Android app on @KatieWoe test device, but still runs fine in Android Chrome and in the app on @mattpen test device), but `'monospace'` runs fine in both.  Also a note that 

@jonathanolson can you help us investigate?

Also, as part of this issue, we should see what sims have been published with the troublesome fonts to see if they require a maintenance release.  I can help with that step once we isolate and resolve the problem.

**Comment by samreid** [comment]
In discussion with @jonathanolson, he said it could be a number of things.  One potential problem is faulty metrics.  We could probably see the more precise problem if we could see a debugger.

Alternatively, we could set up a test harness that uses little or no phet-specific code to try to track this down.  I volunteered to take a look, but would probably need to coordinate with @KatieWoe .

**Comment by samreid** [comment]
In https://github.com/phetsims/gravity-and-orbits/issues/382#issuecomment-800714007, @mattpen said:

> @KatieWoe the solution I posted can be used to get console output from the app. It uses a Chromium webview, so it will show up when you go the device inspector screen. Happy to help with setup if needed, just ping me on slack. 

Having a debugger set up seems like the most efficient way to diagnose and address this font problem.

**Comment by KatieWoe** [comment]
Got the debugger to work and got this error with rc.2:
<img width="629" alt="consoleerror" src="https://user-images.githubusercontent.com/41024075/111513156-1e298580-8716-11eb-8f2c-b606cd9615e5.png">

**Comment by samreid** [comment]
That looks like the same problem as phetsims/phet-android-app#155, I should investigate and make sure the RC has the patch.

@jessegreenberg can you please assist?  Does gravity-and-orbits 1.4 have the SHAs to correct phetsims/phet-android-app#155 ?

**Comment by jessegreenberg** [comment]
The URL in https://github.com/phetsims/scenery-phet/issues/674#issuecomment-801281800 actually points to GAO 1.4 rc.1, and I would still expect to still see the issue there. I verified that gravity-and-orbits 1.4 was included by the automated MR process with https://github.com/phetsims/gravity-and-orbits/commit/3c59924a33933ea7af0d0b50533cdb9ffc66372c and I see scenery branch https://github.com/phetsims/scenery/tree/gravity-and-orbits-1.4.

So I would expect this to be fixed in gravity-and-orbits rc.2 when that is built with the updated scenery SHA.

**Comment by KatieWoe** [comment]
Sorry, mistyped

**Comment by kathy-phet** [comment]
@KatieWoe - I cannot tell if this is really still an issue. Are there other sims that fail in the Android app right now?

**Comment by KatieWoe** [comment]
There weren't in published when I was testing the app for https://github.com/phetsims/QA/issues/612. This came about from testing a few rcs before they went out and seeing the issue. I don't know of any published that have the issue, but I can, of course, check again to make sure.

**Comment by KatieWoe** [comment]
@samreid let me know if you want me to do a quick search through published sims to see if this issue comes up elsewhere.

**Comment by samreid** [comment]
@KatieWoe did you mention another RC that failed to load in the app--maybe Waves Intro?

**Comment by KatieWoe** [comment]
Yes. This was noted in https://github.com/phetsims/gravity-and-orbits/issues/382#issuecomment-800402302

**Comment by samreid** [comment]
In https://github.com/phetsims/gravity-and-orbits/issues/382#issuecomment-800402302 we said:

> The break happened between

  | 1.2.0-dev.17/ | 2020-10-30 11:47 | - |  
  | 1.2.0-dev.16/ | 2020-09-15 10:34 | - |  

This is the same time frame that `webSpeaker` was being developed.  To identify if fonts are related to the problem, I'd like to publish 2 dev versions from master, one that uses the suspicious font and one that does not.  Then we can test those in the app.  If the suspicious font loads OK, then we can confirm this issue was solely about the web synth.

**Comment by samreid** [comment]
This version uses the suspicious fonts on Android:
Deployed: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.0-dev.3/phet/gravity-and-orbits_en_phet.html

**Comment by samreid** [comment]
This version uses 'monospace' on Android, which should be very safe:
https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.0-dev.4/phet/gravity-and-orbits_en_phet.html

@KatieWoe can you please test 1.5.0-dev.3 and dev.4 in the app? This will help us determine if the font was a red herring.  If dev.3 crashes but dev.4 is OK, can you please test in the app with the debugger to see if there is additional information?

**Comment by jessegreenberg** [comment]
Waves Intro 1.1 rc.4 will also fail to load because of the `onvoiceschanged` error. It's SHAs were updated and that should be fixed in rc.5, see https://github.com/phetsims/QA/issues/603#issuecomment-777985685

**Comment by KatieWoe** [comment]
Both dev.3 and dve.4 seem to work on the device. Not sure why.

**Comment by samreid** [comment]
OK I think the font was a red herring, my mistake!  I think https://github.com/phetsims/phet-android-app/issues/155 was the root cause all along.  I recommend closing this issue, and in https://github.com/phetsims/gravity-and-orbits/issues/382#issuecomment-800402302 I'll revert the font change for Android.
