### ISSUE TITLE
branch: tandem

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#675]
https://github.com/phetsims/special-ops/issues/196 restored some branches that had previously been deleted, and will need to be deleted again.  While inspecting branches for this repo, I discovered the "tandem" branch.  I have no idea what the purpose of this branch might have been, other than perhaps "something related to tandems".  The branch name is not particularly descriptive, and an issue was apparently never created to dscribe/track the branch.

@samreid @zepumph please describe this branch, and whether it should be deleted.

**Comment by samreid** [comment]
This branch is 2482 commits behind master, and is no longer needed.  I think it should be deleted.  I almost clicked the "delete" button in https://github.com/phetsims/scenery-phet/branches but wondered if we need to coordinate efforts in https://github.com/phetsims/special-ops/issues/196

**Comment by pixelzoom** [comment]
I'll handle deleting it when I get the "all clear" for phetsims/special-ops#198.

**Comment by pixelzoom** [comment]
Re-deleted using GitHub UI.  Closing.
