### ISSUE TITLE
Create Measuring Tape

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#68]
A number of our new and upcoming HTML5 simulations need measuring tape, including Gravity and Orbits and Fluid Pressure and Flow.  Please see this issue:
https://github.com/phetsims/fluid-pressure-and-flow/issues/2#issuecomment-52323038

I see 7 measuring tape implementations in Java (not sure if there are any in our Flash sims).

We need to do the following:

(1) review the existing Java + Flash simulations to see what technical requirements + features are needed for our common code measuring tape
(2) review the MLL implementations in GAO and FPAF, and see how the measuring tapes are currently used in the code and in the user interface.
(3) implement new measuring tape from scratch.  The new measuring tape should be touch-friendly and multi-touch friendly (meaning one pointer can drag the "tail" and one pointer can drag the "tip").  I think some of the measuring tapes may also have a readout (we should check).  We will also have to decide whether to draw the body of the measuring tape programmatically or using PNG artwork.
(4) rewrite GAO and FPAF to use the new scenery-phet measuring tape.

@ariel-phet suggested that @aaronsamuel137 work on this.  @aaronsamuel137, please feel free to start on this at your convenience, and let me know if you have any questions.

**Comment by bereaphysics** [comment]
Except for #106, all the issues were addressed. I'll leave #106 as open and close this issue.
