### ISSUE TITLE
Global hotkey for the StepForwardButton should be moved to common code

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#681]
There is currently a hotkey added in molecules-and-light that steps forward the simulation when pressing alt + "l". This should be moved to common code. Most likely to StepForwardButton.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/scenery-phet/issues/682.

**Comment by pixelzoom** [comment]
If move to StepForwardButton, it should be the default hotkey, not the only hotkey.

**Comment by zepumph** [comment]
Subset of https://github.com/phetsims/scenery/issues/1298

**Comment by jessegreenberg** [comment]
This would be done with #682 , we don't need to track this in its own issue. Closing.
