### ISSUE TITLE
NumberControl arrow button enabledEpsilon

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/scenery-phet#684]
For https://github.com/phetsims/density/issues/49, I ran into the need to handle epsilons on the view side (the model part won't know what the slider range is).

I'm adding `options.arrowButtonOptions.enabledEpsilon` as mentioned in Slack, which will slightly increase the range where the arrow buttons are disabled (when provided).

I also noticed arrowEnabledListener wasn't listening to options.enabledRangeProperty (but was depending on it), so I've refactored to fix that.

**Comment by jonathanolson** [comment]
@samreid would you be available to review this?

**Comment by samreid** [comment]
I reviewed the code and tested with an epsilon of 5 in the scenery-phet demo. I did not see any problems, closing.
