### ISSUE TITLE
Rename SimColorProfile.js files to SimColors.js

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#686]
From https://github.com/phetsims/scenery-phet/issues/515, we would like to rename sim color files to be `SimColors.js` instead of `SimColorProfile.js`.  https://github.com/phetsims/scenery-phet/issues/515 is getting a bit long, so I moved this to a side issue.

**Comment by samreid** [comment]
In the above commit, the docs are pointing to the old style ColorProfile.js names, I decided to make it consistent until we can address all occurrences.

**Comment by samreid** [comment]
@pixelzoom said in https://github.com/phetsims/scenery-phet/issues/515#issuecomment-887794140

> I'd like to shed the "ColorProfile" baggage, and call this file MyRepoColors.js.  And I intend to put both `ColorDef` and `ProfileColorProperty` instances in this file.

**Comment by samreid** [comment]
> call this file MyRepoColors.js

Before I work on converting these files, can we decide on the casing? Should it be `myRepoColors.js` or `MyRepoColors.js`?

**Comment by pixelzoom** [comment]
Here's my what I (mostly) see being done across the PhET code base. We've never formalized this, but I think it makes sense. 

* If the file exports  an instance of a class (has a constructor), then it's a singleton, and use lowercase. Like soundManager.js.

* If the file exports an object literal that's a collection of constants, use uppercase, e.g. MyRepoConstants.js.

What we're doing here for colors feels like the latter, so MyRepoColors.js.

**Comment by samreid** [comment]
OK I renamed files to SimColors.js.  @pixelzoom would you like to spot check?

**Comment by pixelzoom** [comment]
👍🏻 closing.
