### ISSUE TITLE
ZoomButtonGroup to support non linear zoomProperty changes

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#687]
While working on https://github.com/phetsims/projectile-motion/issues/245, I found that Projectile Motion is not set up to have a linear delta applied on the zoomProperty, it instead multiplies/divides by 2 (like `[.25,.5,1,2,4]`). I mentioned this to the dev slack channel for assistance and @jonathanolson mentioned that he also has run into this problem:

>I’ve run into this a few times. I believe creating an intermediate workaround DynamicProperty (converting the multiplication into addition) worked well

and 

>. . . looks like I punted in https://github.com/phetsims/pendulum-lab/issues/220 and https://github.com/phetsims/collision-lab/issues/208 because ZoomButtonGroup doesn't support fractional zoom levels, so I couldn't use it anyway. But my DynamicProperty proposal is mentioned in https://github.com/phetsims/scenery-phet/issues/652#issuecomment-778893088

My proposal is to turn the delta options into mapping functions the take in the current value, and return a new value. The default will remain the same, which should support all current usages of ZoomButtonGroup (as I don't see any usages changing the default).

This feels like a small enough change that I will go ahead without a quorum from the dev team.

**Comment by zepumph** [comment]
@jonathanolson, will this suite your needs in the future? Please review. Are there any sims that you would like to create conversion issues in to use ZoomButtonGroup now that it supports your zoom model?

I'll proceed now back in https://github.com/phetsims/projectile-motion/issues/245

**Comment by jonathanolson** [comment]
Looks great to me.

**Comment by zepumph** [comment]
Thanks, I'll reopen if I come across unforeseen trouble in https://github.com/phetsims/projectile-motion/issues/245. Closing
