### ISSUE TITLE
BackgroundNode's backgroundOptions should be named rectangleOptions. 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#690]
While working on Fourier, I used `BackgroundNode`.  It has option `backgroundOptions` which violates the naming conventions for nested options.  It should be named `rectangleOptions`, because they are propagated to a `Rectangle`.  

There are only 5 uses, so I'm going to rename it. The affected sims are:

- [x] fourier-making-waves (1)
- [x] graphing-quadratics (1)
- [x] number-line-common (2)
- [x] states-of-matter (1)

**Comment by pixelzoom** [comment]
These changes were limited to my sims and @jbphet sims.  So I'll ask @jbphet to review.

**Comment by jbphet** [comment]
Changes look good, and I verified that the behavior of `BackgroundNode` seemed correct in number-line-integers.  I made some edits to the comments in `BackgroundNode`, and some of the changes were related to this issue and some weren't.  I don't think they would be too controversial, some I'm closing the issue.
