### ISSUE TITLE
GrabDragInteraction voicing should use ResponsePacket

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#702]
From https://github.com/phetsims/friction/issues/211, I see that the "Released" string is not in a voicing category yet. Let's fix that.

**Comment by zepumph** [comment]
While I was here, I made it so that a statically created utterance was instead created per instance. I quite like that pattern, because it seems more sustainable and less likely to encounter weird bugs (though it is less important since the creation of utteranceWrapper).

@jessegreenberg, will you give me a spot check on the above? Please note that I'm totally in love with `Utterance.alert` supporting `ResponsePacket`. Like over in https://github.com/phetsims/friction/commit/5d94f02ff7e05ee340b3055cfae85bcd7f2a954a.

**Comment by pixelzoom** [comment]
Reviewing scenery-phet issues for Q4 planning...

This has been ready-for-review for > 1 year, and was apparently on @jessegreenberg quarterly goals to review. @kathy-phet please prioritize.

**Comment by jessegreenberg** [comment]
Reviewed, looks good!

> I'm totally in love with Utterance.alert supporting ResponsePacket

Excellent! Happy to hear it.
