### ISSUE TITLE
issues related to "press-and-hold" feature in ArrowButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#71]
ArrowButton should be implemented as a subtype of buttons.RectangularPushButton, and specialized with press-and-hold feature.

New sims needing this included RPAL and Area Builder. But there are several other existing sims that will benefit from this.

**Comment by pixelzoom** [comment]
To summarize the state of this issue.... ArrowButton has been reimplemented using RectangularPushButton.  And PressAndHoldInputListener has been extracted for use by other clients. Waiting for review by @jbphet.

**Comment by pixelzoom** [comment]
There's another bug in ThermometerNode, the backgroundFill option does not fill the sphere. Demonstrated by adding backgroundFill: 'yellow' to scenery-phet demo.  See screenshot below.

![screenshot_449](https://cloud.githubusercontent.com/assets/3046552/6093925/73229a1e-aed1-11e4-9203-35372c937540.png)

**Comment by pixelzoom** [comment]
Another bug... In trying to fix the backgroundFill, I discovered that the height of the tube in not options.tubeHeight.  The rounded part of at the top of the tube is being added to tubeHeight.

**Comment by pixelzoom** [comment]
Ignore the above commits, they were intended for #134.

**Comment by jbphet** [comment]
There is a TODO in this code about how a Scenery input listener if being used for the press-and-hold behavior was used and this approach is "ignoring the listener support of its supertype (RectangularPushButton)"  The comment also says, "It would be preferable to handle this via RectangularPushButton, or at least use sun.ButtonListener. But I couldn't see how to do that - which makes me think this is a deficiency of sun."  I'm thinking that it would probably make sense to at least try making a Sun PressAndHoldButtonListener that would work for this application.  I will give this a shot and see if it's doable.

**Comment by pixelzoom** [comment]
Sounds good, let me know if you need any input from me.

**Comment by jbphet** [comment]
The listener that is currently passed up the hierarchy from ArrowButton is a simple 'fire' listener, i.e. a function that is called when the button model decides that it has been fired, so it can't be used to implement press-and-hold behavior.  After looking at this for a bit, I'm thinking that it may make the most sense to integrate the press-and-hold behavior into PushButtonModel, which would then make it available to any subclass that wanted to use it.  Will discuss with @pixelzoom.

**Comment by jbphet** [comment]
Basic support has been added for what I'm now referring to as the fire-on-hold feature.  There is some other functionality needed by ArrowButton that is somewhat related to this feature that has not yet been added.  I'd like to get some input from other developers on how best to add this functionality before doing it so that I don't end up wasting time.  Will discuss at 6/25/2015 developer meeting.

**Comment by pixelzoom** [comment]
At 6/25/15 developer meeting, we decided that the startCallback and endCallback options are generally useful.  They should be added to ButtonModel (rather than PushButtonModel) so that they are available to all buttons.

The amount of duplication with between PressAndHoldListener and PushButtonModel still bothers me. I'd like to take a closer look, perhaps there's some general "handler" pattern than can be factored out and used in both places.

**Comment by pixelzoom** [comment]
At 6/25/15 developer meeting, we decided:

(1) The startCallback and endCallback options are generally useful.  They should be added to ButtonModel (rather than PushButtonModel) so that they are available to all buttons.

(2) PressAndHoldListener is still generally useful, because there are things other than buttons that require this feature. The amount of duplication with between PressAndHoldListener and PushButtonModel still bothers me. I'd like to take a closer look, perhaps there's some general "handler" pattern than can be factored out and used in both places.

**Comment by pixelzoom** [comment]
> Basic support has been added for what I'm now referring to as the fire-on-hold feature

Just for the record... The design team was referring to this as "press-and-hold", which is why I used that name in related code.

**Comment by pixelzoom** [comment]
PressAndHoldListener has been renamed FireOnHoldInputListener, so that terminology is consistent across implementations.

Regarding the duplication in PressAndHoldListener and PushButtonModel, here's a summary of what I did:

• Factored out duplicate code into sun.CallbackTimer, which manages a callback list and a joist.Timer.
• Used CallbackTimer in sun.PushButtonModel. Since the fire-on-hold feature is optional, PushButtonModel manages its own listener list, and delegates calling its fire function to CallbackTimer if the feature is enabled.
• Used CallbackTimer in scenery-phet.FireOnHoldInputListener. FireOnHoldInputListener delegates handling of its listener list to CallbackTimer, since the timer is not optional.

Assigning to @jbphet to review the above changes.

Remaining work to complete this issue:

• Add startCallback and endCallback options to sun.ButtonModel
• In ArrowButton, set options.fireOnHold:true, pass startCallback and endCallback to supertype constructor, remove FireOnHoldInputListener.

**Comment by pixelzoom** [comment]
Assigned this to myself to complete remaining work.

**Comment by pixelzoom** [comment]
ButtonModel: I added options.startCallback and endCallback. It was odd that I also had to add `@param options` to the constructor, because it should have been passing options to PropertySet for together support. The supertype constructor call was generally messed up, see https://github.com/phetsims/sun/issues/190.

ArrowButton: I removed the FireOnHoldInputListener, and passed the options related to fire-on-hold, startCallback and endCallback to the supertype (RectangularPushButton).  Call sites for ArrowButton where changed to use the new option names for fireOnHoldDelay and fireOnHoldInterval.

I believe that all work for this issue is now completed. Assigning to @jbphet for review.

**Comment by pixelzoom** [comment]
Assigning back to me. ArrowButton startCallback and endCallback are not working in hookes-law.

**Comment by pixelzoom** [comment]
OK, fixed. I was using `property( 'down' ).onValue` to call startCallback and endCallback in ButtonModel. But `onValue` is like `link`, in that it's called immediately.  Converted this to `lazyLink` and hookes-law works as expected.

Back to @jbphet.

**Comment by jbphet** [comment]
I'm trying to test this in order to verify it, but I'm running into an immediate issue.  While running with assertions enabled, I keep hitting the following assertion, which is the first line of the ```fire``` function in CallbackTimer.js and is currently on line 109:

```js
assert && assert( !this.isRunning() );
```

This line of code seems to be saying that the timer shouldn't be running when this function is called, but the other code within this file, such as that in the ```start``` function clearly calls ```fire``` when the timer is running.  Also, since it is a repetitive timer, it makes sense that ```fire``` would get called when the timer is running.  So I'm not sure what's going on here, or how this would have escaped testing.  I'm sending this back to @pixelzoom to help me figure this out.

**Comment by pixelzoom** [comment]
Re: `assert && assert( !this.isRunning() );`

Sorry, that was a stray assertion that got moved over from PhetButtonModel when I factored out the timer code.  It originally looked like this in @jbphet's code, and was in the 'down' handler.

```js
// make sure timers are in the expected state
assert && assert( delayID === null && intervalID === null, 'Timers non-null on button down' );
```

Delete the assertion. Back to @jbphet.

**Comment by jbphet** [comment]
All looks good now.  The desired fire-on-hold (previously knows as press-and-hold) behavior is now a part of the common code buttons instead of being specific to the arrow buttons.  I just tested the behavior on Beaker, Hooke's Law, and the Sun Demo.  Works fine in all cases.  I think our work here is done.  Closing.
