### ISSUE TITLE
Limit the maximum number of charges that can be shown on a capacitor plate

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#713]
From https://github.com/phetsims/circuit-construction-kit-common/issues/772, it is sometimes trying to draw 60,000 or more charges on one plate, which yields poor performance.  PlateChargeNode already has a `NUMBER_OF_PLATE_CHARGES` range, but its max is not being respected.

I tested fuzzing and manually testing Capacitor Lab Basics, and could only get it to try for up to 625, the declared max for the plates.  Therefore, it seems safe to restrict the value to be less than or equal to the max of that range.

I'll make the change then request review from @jessegreenberg since he is listed as an author for these files.

**Comment by samreid** [comment]
Fixed in the commit, and I confirmed it fixes the performance problem described in https://github.com/phetsims/circuit-construction-kit-common/issues/772#issue-1045197327.  @jessegreenberg can you please review, or please reassign if another developer is more appropriate for this review?

**Comment by samreid** [comment]
Elevating priority since this is needed for the CCK AC milestone.

**Comment by jessegreenberg** [comment]
This change looks good to me! Thanks for the fix.

**Comment by samreid** [comment]
Thanks, closing.
