### ISSUE TITLE
Better names for keyboard-help section classes?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#714]
PhET convention is name things based on how they appear on the screen when possible. This makes it easier to locate code.

Would it be possible to rename the predefined keyboard-help sections so that their titles match their class names?  That would make it a lot easier to find what I need, and to understand code that I'm not familiar with.

Some examples...

| title  | class name | better class name |
| :--- | :--- | :--- |
| Basic Actions | GeneralKeyboardHelpSection | BasicActionsKeyboardHelpSection |
| Slider Controls | SliderKeyboardHelpSection | SliderControlsKeyboardHelpSection |

**Comment by jessegreenberg** [comment]
Yes, this sounds good. The title for the general section used to be called "General Navigation" but it changed to "Basic Actions" and we didn't update the class name. Ill rename these.

**Comment by jessegreenberg** [comment]
OK, I renamed

GeneralKeyboardHelpSection -> BasicActionsKeyboardHelpSection
SliderKeyboardHelpSection -> SliderControlsKeyboardHelpSection
SliderAndGeneralKeyboardHelpContent -> SliderControlsAndBasicActionsKeyboardHelpContent

The rest of the names seem appropriate to me, reassigning to @pixelzoom in case there is anything else.

**Comment by pixelzoom** [comment]
Thanks for the quick turnaround on this, it will definitely make things easier going forward.

It looks like you hadn't done a pull-all before renaming, because this broke Geometric Optics. Fixed in the above commit.  

Everything else looks good, closing.
