### ISSUE TITLE
Problems with ComboBoxKeyboardHelpSection

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#715]
This came up in https://github.com/phetsims/geometric-optics/issues/281.

`ComboBoxKeyboardHelpSection` provides keyboard-help content for a _specific_ combo box. The template looks like the screenshot below, where you fill in the blank with a name for the thing you're choosing. 

Providing keyboard help for each individual combo box is not scalable - what if we have 3 combo boxes on a screen, like Fourier?  And it's also repetitive - could we provide a general description for combo box, like we do for slider?

![screenshot_291](https://user-images.githubusercontent.com/3046552/146452504-32926d66-607b-4705-9fd6-5d145bf4ac98.png)

**Comment by jessegreenberg** [comment]
@zepumph what do you think of this patch? It makes the default heading string a little more general. I wasn't sure about this at first because usually a custom string is requested for headings in this dialog, but then I noticed the molarity usage passed a `thingAsTitle` but it wasn't used. We would check "Use a Combo Box" with design.

<details>

```patch
Index: molarity/js/molarity/view/MolarityKeyboardHelpContent.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/molarity/js/molarity/view/MolarityKeyboardHelpContent.js b/molarity/js/molarity/view/MolarityKeyboardHelpContent.js
--- a/molarity/js/molarity/view/MolarityKeyboardHelpContent.js	(revision 7fe99947c17ed1a457e1a81f74339ec8305078f9)
+++ b/molarity/js/molarity/view/MolarityKeyboardHelpContent.js	(date 1639696059184)
@@ -28,7 +28,7 @@
     // slider controls help section
     const sliderKeyboardHelpSection = new SliderKeyboardHelpSection( { headingString: keyboardSliderHelpHeadingString } );
 
-    const changeSoluteHelpSection = new ComboBoxKeyboardHelpSection( molarityStrings.solute, {
+    const changeSoluteHelpSection = new ComboBoxKeyboardHelpSection( {
       headingString: molarityStrings.keyboard.changeSoluteHelpHeading,
       thingAsLowerCasePlural: molarityStrings.solutes,
       thingAsLowerCaseSingular: molarityStrings.soluteLowercase
Index: scenery-phet/scenery-phet-strings_en.json
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scenery-phet/scenery-phet-strings_en.json b/scenery-phet/scenery-phet-strings_en.json
--- a/scenery-phet/scenery-phet-strings_en.json	(revision e6ff90743afeca616f631f3cb9d71b205a8b9532)
+++ b/scenery-phet/scenery-phet-strings_en.json	(date 1639695976917)
@@ -86,6 +86,9 @@
   "keyboardHelpDialog.sliderControls": {
     "value": "Slider Controls"
   },
+  "keyboardHelpDialog.useAComboBox": {
+    "value": "Use A ComboBox"
+  },
   "keyboardHelpDialog.adjustSlider": {
     "value": "Adjust slider"
   },
Index: scenery-phet/js/sceneryPhetStrings.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scenery-phet/js/sceneryPhetStrings.ts b/scenery-phet/js/sceneryPhetStrings.ts
--- a/scenery-phet/js/sceneryPhetStrings.ts	(revision e6ff90743afeca616f631f3cb9d71b205a8b9532)
+++ b/scenery-phet/js/sceneryPhetStrings.ts	(date 1639696084016)
@@ -46,6 +46,7 @@
   },
   'keyboardHelpDialog': {
     'sliderControls': string,
+    'useAComboBox': string,
     'adjustSlider': string,
     'adjustInSmallerSteps': string,
     'adjustInLargerSteps': string,
Index: scenery-phet/js/keyboard/help/ComboBoxKeyboardHelpSection.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scenery-phet/js/keyboard/help/ComboBoxKeyboardHelpSection.js b/scenery-phet/js/keyboard/help/ComboBoxKeyboardHelpSection.js
--- a/scenery-phet/js/keyboard/help/ComboBoxKeyboardHelpSection.js	(revision e6ff90743afeca616f631f3cb9d71b205a8b9532)
+++ b/scenery-phet/js/keyboard/help/ComboBoxKeyboardHelpSection.js	(date 1639695995958)
@@ -17,17 +17,13 @@
 class ComboBoxKeyboardHelpSection extends KeyboardHelpSection {
 
   /**
-   * @param {string} thingAsTitle - the item being changed by the combo box, capitalized as a title
    * @param {Object} [options]
    */
-  constructor( thingAsTitle, options ) {
-    assert && assert( typeof thingAsTitle === 'string' );
+  constructor( options ) {
 
     options = merge( {
 
-      headingString: StringUtils.fillIn( sceneryPhetStrings.keyboardHelpDialog.comboBox.chooseAThingPattern, {
-        thingTitle: thingAsTitle
-      } ),
+      headingString: sceneryPhetStrings.keyboardHelpDialog.useAComboBox,
 
       // the item being changed by the combo box, lower case as used in a sentence.
       thingAsLowerCaseSingular: sceneryPhetStrings.keyboardHelpDialog.comboBox.option,
Index: ratio-and-proportion/js/discover/view/DiscoverScreenKeyboardHelpContent.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/ratio-and-proportion/js/discover/view/DiscoverScreenKeyboardHelpContent.ts b/ratio-and-proportion/js/discover/view/DiscoverScreenKeyboardHelpContent.ts
--- a/ratio-and-proportion/js/discover/view/DiscoverScreenKeyboardHelpContent.ts	(revision 339c71d7dc9f640251d5c9a66f4eb562aa9bb96b)
+++ b/ratio-and-proportion/js/discover/view/DiscoverScreenKeyboardHelpContent.ts	(date 1639696234685)
@@ -6,14 +6,20 @@
  * @author Michael Kauzmann (PhET Interactive Simulations)
  */
 
+import StringUtils from '../../../../phetcommon/js/util/StringUtils.js';
 import ComboBoxKeyboardHelpSection from '../../../../scenery-phet/js/keyboard/help/ComboBoxKeyboardHelpSection.js';
+import sceneryPhetStrings from '../../../../scenery-phet/js/sceneryPhetStrings.js';
 import RAPKeyboardHelpContent from '../../common/view/RAPKeyboardHelpContent.js';
 import ratioAndProportion from '../../ratioAndProportion.js';
 import ratioAndProportionStrings from '../../ratioAndProportionStrings.js';
 
 class DiscoverScreenKeyboardHelpContent extends RAPKeyboardHelpContent {
   constructor() {
-    super( new ComboBoxKeyboardHelpSection( ratioAndProportionStrings.challengeRatio ) );
+    super( new ComboBoxKeyboardHelpSection( {
+      headingString: StringUtils.fillIn( sceneryPhetStrings.keyboardHelpDialog.comboBox.chooseAThingPattern, {
+        thingTitle: ratioAndProportionStrings.challengeRatio
+      } )
+    } ) );
   }
 }
 
```

</details>

**Comment by arouinfar** [comment]
Just to throw in my 2 cents... I'm all for a general heading, but I'm not convinced that the average user is familiar with the term "Combo Box". I'd never heard the term before working for PhET. I would suggest using something like "Dropdown" or "Dropdown menu".  I know that not all ComboBoxes  open downwards, but I think users would be able to identify an upward-opening ComboBox as a "Dropdown". 

Google Forms uses "Dropdown" to refer to a ComboBox answer type.
<img src="https://user-images.githubusercontent.com/8419308/146977449-797187ec-f27a-4b4c-865b-bd58ef141cef.png" width=200>

**Comment by pixelzoom** [comment]
I'm fine with using a term other than "combo box".  

As in https://github.com/phetsims/scenery-phet/issues/714, class name should reflect the title, to make it easy to find.

**Comment by zepumph** [comment]
Thanks for the great patch @jessegreenberg. I think that is perfect. I contemplated updating the heading option to just be a "thing" and forcing us to fill in a generic pattern, like "use a ___", but that seems too rigid. Just as is seems perfect. Just update it to whatever term we decide for "combo box."

**Comment by pixelzoom** [comment]
This is blocking completion of https://github.com/phetsims/geometric-optics/issues/281.

**Comment by pixelzoom** [comment]
Another problem with the current implementation.   The API allows you to supply a value for the `{{thingTitle}}` placeholder in this pattern that appears in scenery-phet-strings_en.json:

```js
  "keyboardHelpDialog.comboBox.chooseAThingPattern": {
    "value": "Choose a {{thingTitle}}"
  },
```

Any `{{thingTitle}}` that starts with a vowel should be preceeded by "an", e.g. "Choose an apple."

**Comment by pixelzoom** [comment]
Doing a search for combo box synonyms, "drop-down list"  comes up quite a bit.  If the name of this things is going to be "down", then consider changing the text for the first "step" in the help, which is "Pop up list of options".

**Comment by jessegreenberg** [comment]
This came up in the quarterly planning meeting for QA 2022, it blocks publication of geometric-optics.

**Comment by pixelzoom** [comment]
We made some improvements to the keyboard help in Geometric Optics, so that we're no longer referring to "combo box".  But `ComboBoxKeyboardHelpSection` makes the rather unfortunate assumption that all nouns begin with a consonant.  So instead of "Choose an Object", we currently have "Choose a Object".  See below.

<img width="373" alt="screenshot_1556" src="https://user-images.githubusercontent.com/3046552/153966898-b987b081-642a-4cb9-a2b5-71a6702a9540.png">

**Comment by pixelzoom** [comment]
I think the patch proposed by @jessegreenberg in https://github.com/phetsims/scenery-phet/issues/715#issuecomment-996267439 is a fine solution, with the caveat that the default "Use a Combo Box" may need to be changed to something more "friendly".   Other than geometric-optics, there are only 2 usages of ComboBoxKeyboardHelpSection (molarity, ratio-and-proportion).   I'd be happy to handle applying the patch. @jessegreenberg OK to proceed?

**Comment by pixelzoom** [comment]
One change from @jessegreenberg's patch...  I think we should remove this scenery-phet strings:

```js
"keyboardHelpDialog.comboBox.chooseAThingPattern": {
    "value": "Choose a {{thingTitle}}"
},
```

... because of the "a" versus "an" problem.  It would be preferrably to just have the clients provide the full title, e.g. "Choose a solute" in molarity and "Choose a Challenge Ratio" in ratio-and-proportion.

**Comment by pixelzoom** [comment]
Interesting that in molarity, the usage is:

```js
    const changeSoluteHelpSection = new ComboBoxKeyboardHelpSection( molarityStrings.solute, {
      headingString: molarityStrings.keyboard.changeSoluteHelpHeading,
      thingAsLowerCasePlural: molarityStrings.solutes,
      thingAsLowerCaseSingular: molarityStrings.soluteLowercase
    } );
```

So the first constructor arg is thrown away, because it's providing option `headingString`.

**Comment by pixelzoom** [comment]
@jessegreenberg I hope you don't mind... But since I had already prototyped 90% of this in my working copy, I took the liberty of completing the work in the above commits.  The existing usages still look the same (see screenshots below), clients provide the full heading via `options.headingString`, and the "a" vs "an" problem no longer exists.

The default header (currently "Use a Combo Box") still needs to be discussed by the a11y team.  But I used string key `sceneryPhetStrings.keyboardHelpDialog.comboBox.headingString` so that the key will not be affected by changes.

@jessegreenberg please review.

<img width="441" alt="screenshot_1558" src="https://user-images.githubusercontent.com/3046552/154087190-66de617b-1ca3-4b9b-bffc-92009e5ecaee.png">
<img width="491" alt="screenshot_1559" src="https://user-images.githubusercontent.com/3046552/154087222-f591f024-6bb5-4046-8f8a-396971f2af0d.png">
<img width="475" alt="screenshot_1560" src="https://user-images.githubusercontent.com/3046552/154087236-b5ea4f30-96ca-4b5b-86d8-e5ebe23743ff.png">

**Comment by jessegreenberg** [comment]
Changes look great, thanks for taking this on. I reviewed usages of ComboBoxKeyboardHelpSection, all seems well. My understanding is that we cannot remove keys in translatable strings files once they have been used in a translation so I added back `keyboardHelpDialog.comboBox.chooseAThingPattern"`. Ill ask @jbphet if we can remove this and also check on the best term for "Combo Box".

**Comment by jessegreenberg** [comment]
I discussed with @terracoda the right default name for this UI component. I suggested "dropdown" but she argued that our ComboBox can open up or down, and that would clash with our help content for ComboBox items which uses terminology "Pop up...". She suggested "Choose an option", but I argued that the user wouldn't identify "option" as the ComboBox UI component, "option" could refer to anything. I suggested "Use a listbox" or "Use a select menu". @terracoda didn't want the heading to start with "Use...". She suggested "Pop open menu". I like this because now all contents of this KeyboardHelpSection can apply to a "pop-up menu" like ComboBox or PhETMenu.

I am going to change the default heading to "Pop open menu", change the name of `ComboBoxKeyboardHelpSection` to `MenuKeyboardHelpSection` (like https://github.com/phetsims/scenery-phet/issues/714). I am going to leave the string keys as `keyboardHelpDialog.comboBox...` because it is not easy to change keys that have been translated.

**Comment by jessegreenberg** [comment]
@pixelzoom could you please review this rename change and decision since it is similar to https://github.com/phetsims/scenery-phet/issues/714?

**Comment by pixelzoom** [comment]
Commits look good.

I like the "Pop open menu" default heading.  

But I don't think we should call this class `MenuKeyboardHelpSection`, as "menu" is too general - for example, this would certainly not be used for the PhET menu.  And a listbox (the part of the combo box that opens) is not technically considered a menu in most UI toolkits (including sun).  So as a programmer, I don't think of this as a menu, and won't be looking for "Menu" keyboard help.

Despite #714, I think it would be preferable to keep the original name, `ComboBoxKeyboardHelpSection`, because its title is not always the same, and (as programmers) we know that this is related to a ComboBox.

**Comment by terracoda** [comment]
Glad you like "Pop Open Menu". Also considered "Pop Open List", "Pop Open Menu Options". Using "Menu" in the heading and "list" or "options" in the first step of instructions may provide clues to learners unfamiliar with the combobox/listbox UI component.

I agree with @pixelzoom that it is likely a good idea to name it as ComboBoxKeyboardHelpSection. While actual menus, like the PhET Menu, are very similar in their keyboard interaction pattern, the code differs slightly as screen readers verbalize them differently. 

VoiceOver reads out the Solute Combobox  as "Solute {{Drink Mix}}, list box pop up, button"
<img width="613" alt="image" src="https://user-images.githubusercontent.com/1902116/154500886-1bc79e79-54b5-4add-81c4-6f98dd0505b7.png">

whereas the PhET Menu is read out as "PhET Menu, menu pop up , button"
<img width="614" alt="image" src="https://user-images.githubusercontent.com/1902116/154501176-19efba98-e706-4109-8445-82d04ec3d1e4.png">

**Comment by jessegreenberg** [comment]
OK, thanks @pixelzoom and @terracoda all sounds good. I renamed it back to ComboBoxKeyboardHelpSection. Is there anything else for this issue?

**Comment by pixelzoom** [comment]
I think that wraps it up, thanks! Closing.
