### ISSUE TITLE
PhET-iO instrumentation for GrabDragInteraction

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#720]
From https://github.com/phetsims/friction/issues/236#issuecomment-940505198, it would be good to understand if there is anything to add to the interoperability. In general, I feel like this isn't. A design meeting may be nice though.

**Comment by arouinfar** [comment]
@zepumph there needs to be a way to disable the GrabDragInteraction pressListener. Otherwise, you can do something like set `atomDragArea.inputEnabledProperty` to false, but it will still be focusable and provide the "Space to Grab or Release" hint which won't actually work.

**Comment by zepumph** [comment]
I added an enabledProperty to GrabDragInteraction. It mimics the opt-in approach used in PressListener/DragListener. This doesn't directly address the concern you had in https://github.com/phetsims/scenery-phet/issues/720#issuecomment-1023572451. This is because of how inputEnabled is set up to work. That doesn't block focus events at this time. I created https://github.com/phetsims/scenery/issues/1369 to discuss this more.

**Comment by zepumph** [comment]
For right now, please go to `friction.frictionScreen.view.atomicView.grabDragInteraction.enabledProperty` to try out the enabledProperty, which believe has the desired effect.

**Comment by zepumph** [comment]
Hide the grab cue when inputEnabled is false.

**Comment by zepumph** [comment]
Alright. I have updated the cues to hide if inputEnabled:false. @arouinfar would you please take another look at this? Close if all is well.

**Comment by arouinfar** [comment]
Thanks @zepumph, I've confirmed that the cues are hidden when `inputEnabledProperty` is false.

**Comment by zepumph** [comment]
Reopening. I think it would be much nicer if toggling inputEnabled on the micro view just changed the grabDragInteraction itself. This means that we can simplify this grab drag interaction instrumentation by making it phetioReadOnly in general. Why would someone want to turn off the keyboard input while keeping other input on? That doesn't seem like the granularity to support.

**Comment by zepumph** [comment]
Actually, I'll just have this work done over in https://github.com/phetsims/friction/issues/285, but will reference over here.
