### ISSUE TITLE
Added faucetNode.enabledProperty to PhET-iO API

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#721]
Over in https://github.com/phetsims/scenery/issues/1340 there was consolidation of the enabledProperty passed to AccessibleSlider, and the one created in Node and automatically instrumented. As a result, FaucetNode is now instrumenting its enabledProperty whereas before it wasn't. This is in general an improvement, and likely if faucetNode was more complete, it would have had this anyways, but I still wanted to double check with a designer before calling it since it effects already-designed sims.

**Comment by zepumph** [comment]
@arouinfar, please take a look at the above updates in ph-scale and energy-forms-and-changes. For example, in EFAC, we were passing faucetNode an instrumented Property for its enabledProperty already, and Node was smart enough to register a linkedElement for us, see 

`energyFormsAndChanges.systemsScreen.view.energySources.faucetAndWaterNode.faucetNode.enabledProperty`

**Comment by arouinfar** [comment]
@zepumph the `faucetNode.enabledProperty` looks good in EFAC and ph-scale. In both cases, the `enabledProperty` is read-only, which I think is the right call. I'll go ahead and close, thanks!
