### ISSUE TITLE
TypeScript conversion

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/scenery-phet#726]
Creating an issue to tag commits (for review), and to discuss potential problems in conversion.

**Comment by jonathanolson** [comment]
@jbphet I converted some tambo bits since Slider depended on the options object for ValueChangeSoundGenerator. Can you review that portion?

**Comment by jonathanolson** [comment]
InteractionStateProperty looks really tricky here. They use different value sets for different concrete controls, but it's used in e.g. RectangularButton. I've had to type it as `IProperty<ButtonInteractionState | RadioButtonInteractionState>` in places.

We may need to parameterize the core types e.g. `class RectangularButton<InteractionState>`, or figure out other solutions.

**Comment by samreid** [comment]
@chrisklus and I noticed that ReadOnlyProperty was written like this:

```ts
export interface ReadOnlyProperty<T> extends Property<T> {
  readonly value: T;

  // Any solution with Omit<Property<T>, 'set' | 'reset'> was failing, as it wasn't assignable to PhetioObject
  set: unknown & any;
  reset: unknown & any;
}
```

However, this means that this code type checks:

```ts
const p = new Property( 1 );
const x: ReadOnlyProperty<number> = p;
x.set( 7 );
```

Also, we were surprised to see https://github.com/phetsims/center-and-spread/commit/b416354f2a0610d3eea7d76f473017c823bb51cc where an IReadOnlyProperty was converted to Property.  It seems it should remain read-only.  @jonathanolson can you please advise?

**Comment by pixelzoom** [comment]
Assigning myself to this issue, since I'm responsible dev for scenery-phet.

**Comment by jonathanolson** [comment]
ReadOnlyProperty is buggy, and not ready for use. I'm not sure it's possible to make it work. Perhaps I should remove it?

**Comment by jonathanolson** [comment]
> Also, we were surprised to see https://github.com/phetsims/center-and-spread/commit/b416354f2a0610d3eea7d76f473017c823bb51cc where an IReadOnlyProperty was converted to Property. It seems it should remain read-only. @jonathanolson can you please advise?

It gets passed as a visibleProperty. Actually this is a situation where the previous type system was hiding something:

<img width="875" alt="image" src="https://user-images.githubusercontent.com/480878/157309018-9d291a47-84a8-4cc8-9a99-e5682184b6f7.png">

Basically, a DerivedProperty passed to visibleProperty + a "node.visible = false;" would error out. Thoughts?

**Comment by pixelzoom** [comment]
> ReadOnlyProperty is buggy, and not ready for use. I'm not sure it's possible to make it work. Perhaps I should remove it?

Yes, probably so.

**Comment by pixelzoom** [comment]
@jonathanolson It's been ~30 days since we discussed deleting `ReadOnlyProperty`, see https://github.com/phetsims/scenery-phet/issues/726#issuecomment-1062357294.  If `ReadOnlyProperty` is not going to be fixed, can we please remove it? More than once, I've accidentally ended up with `ReadOnlyProperty` when I wanted `IReadOnlyProperty`.  See https://github.com/phetsims/scenery-phet/issues/726.

**Comment by samreid** [comment]
I'll work on removing it momentarily.

**Comment by samreid** [comment]
It sounds pretty safe to remove it in a maintenance release commit, if you like.

**Comment by samreid** [comment]
@jonathanolson can you please report on this status?  @zepumph and I are curious whether it's still blocking for the upcoming PhET-iO milestone.

**Comment by jonathanolson** [comment]
I believe ReadOnlyProperty is now part of the axon hierarchy. @samreid anything left to do here?

**Comment by samreid** [comment]
To clarify, `interface ReadOnlyProperty` was removed in https://github.com/phetsims/axon/commit/5a14223cf02db039ea34c6e04ec370a47fab76d0.  Then in June we added `class ReadOnlyProperty` in https://github.com/phetsims/axon/issues/382, which has been working much better.  So I think that aspect of the issue can be closed.

I'm uncertain about https://github.com/phetsims/scenery-phet/issues/726#issuecomment-1059804865 or the rest of the scope of this issue, up to you.

**Comment by pixelzoom** [comment]
Remaining TypeScript work is in scenery-phet is tracked in separate issues. So this issue can be closed.
