### ISSUE TITLE
Convert ThermometerNode to typescript

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#727]
From https://github.com/phetsims/chipper/issues/1205, today during Dev meeting, I volunteered to convert ThermometerNode as a way to get rid of phet-types.d.ts as soon as possible (perhaps by next week).

**Comment by zepumph** [comment]
@pixelzoom please review ThermometerNode if you want. Feel free to close.

**Comment by zepumph** [comment]
Wow. I did not mean to close this, sorry! Also I forgot to fix other usages of ThermometerNodeOptions in the project (thanks @pixelzoom for fixing), and I also didn't remove the global, pushed above.

**Comment by pixelzoom** [comment]
👍🏻 closing
