### ISSUE TITLE
Why is SpectrumSlider deprecated?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#729]
I encountered this while converting SpectrumSlider to TypeScript.

@zepumph added this annotation to SpectrumSlider in f33d9516 for https://github.com/phetsims/phet-io/issues/1657:

```
@deprecated - please use Slider.js with SpectrumSlideTrack/Thumb (or the composite WavelengthNumberControl)
```

Questions:

* It looks like this was motivated by PhET-iO, something about SpectrumSlider not adhering to SliderIO.  It's not clear (to me anyway) from the issue or the deprecation comment why this was specifically done, and what the plan is for SpectrumSlider.  Let's improve the doc.

* SpectrumSlider now extends `AccessibleSlider( Node, 0 )`. Does that change anything about the reason for deprecating?

* SpectrumSlider is the base class for WavelengthSlider.  Is it OK to use WavelengthSlider? Why doesn't that have the same problem?  If it's OK to use WavelengthSlider, can we make SpectrumSlider's constructor protected and remove the deprecation? 
 
* Should we rewrite SpectrumSlider to extend Slider?  Should we create an issue to do that?

**Comment by zepumph** [comment]
I have no recollection of this. Your thoughts all seem reasonable. I don't rememer why SpectrumSlider was marked as such except perhaps a feeling? @samreid do you remember this at all?

**Comment by samreid** [comment]
SpectrumSlider does not extend `Slider`, it uses a separate parallel algorithm for rendering the track.  Once Slider added support for custom tracks and thumbs, `WavelengthNumberControl` was written to leverage that.

> It looks like this was motivated by PhET-iO, something about SpectrumSlider not adhering to SliderIO. It's not clear (to me anyway) from the issue or the deprecation comment why this was specifically done, and what the plan is for SpectrumSlider. Let's improve the doc.

Yes, SliderIO is one concern, but it is more that SpectrumSlider unnecessarily duplicates much of the logic in Slider.js.

> SpectrumSlider now extends AccessibleSlider( Node, 0 ). Does that change anything about the reason for deprecating?

No.

> SpectrumSlider is the base class for WavelengthSlider. Is it OK to use WavelengthSlider? Why doesn't that have the same problem? If it's OK to use WavelengthSlider, can we make SpectrumSlider's constructor protected and remove the deprecation?

No, WavelengthSlider is also deprecated and when running with deprecation warnings those will print out.  It has the same problem.  It's not OK to use WavelengthSlider, it is deprecated.  There are 5 usages, we should convert them to use WavelengthNumberControl.

> Should we rewrite SpectrumSlider to extend Slider? Should we create an issue to do that?

No, SpectrumSlider has no direct usages.  In the future if we have a need for a slider with a spectrum track, we would follow the pattern in WavelengthNumberControl:

```ts
      sliderOptions: {
        trackNode: new SpectrumSliderTrack( property, options.range, {
          valueToColor: VisibleColor.wavelengthToColor,
          size: new Dimension2( 160, trackHeight )
        } ),
```

**Comment by pixelzoom** [comment]
Thanks for the answers.

> No, WavelengthSlider is also deprecated and when running with deprecation warnings those will print out. 

Deprecation warnings aren't typically checked until code review. By then it's too late.  So  WavelengthSlider needs a `@deprecated` annotation.

The `@deprecated` annotation in SpectrumSlider is in the wrong place. It needs to be on the class level, not on the constructor, in order to appear in Webstorm, i.e.:

```js
/**
 * @deprecated use WavelengthNumberControl, or Slider.js with SpectrumSlideTrack and SpectrumSlideTrack,
 *   see https://github.com/phetsims/scenery-phet/issues/729
 */
class SpectrumSlider extends AccessibleSlider( Node, 0 ) {
```

I've fixed these problem in the above commits. WebStorm will now make it very obvious (using strokethrough text) if you attempt to use one of these classes in new code.
