### ISSUE TITLE
Review TypeScript conversion of GradientRectangle

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#733]
Prior to conversion, GradientRectangle contained multiple bugs:

These fields were defined and were unused:

```
    this._topMarginMargin = 0;
    this._bottomMarginMargin = 0;
```

These fields were used in multiple method, but were not defined in the constructor:

```js
this._topMargin
this._bottomMargin
```

This method uses field `this._border` which does not exist:

```js
  /**
   * Returns the border color (see the setter)
   * @public
   *
   * @returns {ColorDef}
   */
  get border() {
    return this._border;
  }
```

**Comment by pixelzoom** [comment]
Converted in the above commit.   

I addressed the above problems by:

(1) Defining fields as `this._topMargin` and `this._bottomMargin`.

(2) Implementing `get border` as:

```js
  public get border(): IPaint {
    return this._borderOverrideProperty.paint;
  }
```

I never did figure out how to test this.  The sole use is in fractions-common TargetNode, whose documentation was not helpful.  It looks like it's used in the Game screen, but I couldn't identify "a container with a given visual representation of the target (what should go in it)",  and I didn't encounter anything that looks like a graident rectangle.

Assigning to the author @jonathanolson for review.

**Comment by pixelzoom** [comment]
@kathy-phet please prioritize this review.

**Comment by pixelzoom** [comment]
@kathy-phet @jonathanolson Noting that this has been ready for review for 9+ months, and I've still received no response.

**Comment by jonathanolson** [comment]
Looks good, thank you!
