### ISSUE TITLE
Incorrect use of nested options in SpeedRadioButtonGroup.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#735]
While working on https://github.com/phetsims/models-of-the-hydrogen-atom/issues/22, I discovered an issue with TimeControlNode.SpeedRadioButtonGroup:

```js
class SpeedRadioButtonGroup extends VerticalAquaRadioButtonGroup {
...
    options = merge( {
...
      // {Object|null} - options for the radio button group, defaults defined below because they are dependent on
      // size of label text
      radioButtonGroupOptions: null
    }, options );
```

SpeedRadioButtonGroup is a subclass of VerticalAquaRadioButtonGroup, so this is an incorrect use of nested `radioButtonGroupOptions`.  Any options related to the group should be at the top-level of the options, not nested.  @jessegreenberg do you agree?

I'll assign this to myself.  I'll need this in MOTHA, but I won't get to it for a couple of weeks.  It looks like there are only 3 occurrences of "radioButtonGroupOptions:" in sims, so this should be relatively easy.

**Comment by pixelzoom** [comment]
Looks like there are only 3 occurrences of "radioButtonGroupOptions:" in sims, so this should be relatively easy.

**Comment by pixelzoom** [comment]
I went ahead and did this.  I tested the 3 sims that were using `radioButtonGroupOptions` (collision-lab, GAO, ESP), tested a few others that were not (gas-properties,...).  And I verified that no PhET-iO APIs were changed.

@jessegreenberg please review. Please close if it looks OK

**Comment by jessegreenberg** [comment]
Yes this looks correct, thanks! I looked around at the usages of `speedRadioButtonGroupOptions` for TimeControlNode and verified they are still working.
