### ISSUE TITLE
Convert TimeSpeed to new enumeration pattern

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#736]
This is a pre-requisite to converting TimeControlNode to TypeScript, needed in MOTHA and other sims.  This will be a big chunk of work, because TimeSpeed and EnumerationDeprecatedProperty are used widely.

**Comment by pixelzoom** [comment]
In the above commits:
* `TimeSpeed` was converted to `EnumerationValue`
* `timeSpeedProperty` was converted to `EnumerationProperty<TimeSpeed>`

Assigning to @jbphet to verify neuron. After I was well into this issue, I discovered that neuron was broken, and wouldn’t even start up - see https://github.com/phetsims/neuron/issues/148.  So please verify that the changes to TimeSpeed work in neuron. The commit for neuron is https://github.com/phetsims/neuron/commit/c2aa5f19c9c8cf9455218c6b50cdc718090715a2

**Comment by jbphet** [comment]
I had to make  minor fix, but everything worked fine after that, so consider the changes verified.  See https://github.com/phetsims/neuron/issues/148 for more info if needed.  Closing.
