### ISSUE TITLE
Convert TimeControlNode to TypeScript

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#737]
Creating an issue for this one because it's relatively complicated, and it looks like some sim(s) will need review.

**Comment by pixelzoom** [comment]
A couple more changes... The inner classes were getting large, and their names weren't quite right, so I factored them out as follows:

* SpeedRadioButtonGroup -> js/TimeSpeedRadioButtonGroup.ts
* PlayPauseStepButtons -> js/buttons/PlayPauseStepButtonGroup.ts

There are a few nested options in TimeControlNode that should be changed to match the class names. but I'm wondering if it's worth the trouble:

* speedRadioButtonGroupOptions -> timeSpeedRadioButtonGroupOptions
* playPauseStepButtonOptions -> playPauseStepButtonGroupOptions

@samreid thoughts?

**Comment by jbphet** [comment]
@pixelzoom - There is a line of what looks like some debugging code in `TimeSpeedRadioButtonGroup`, it looks like this:

```
console.log( `AFTER: options.radioButtonOptions.radius=${options.radius}` );
```

I was going to remove it, but then thought you might still be using it, so I thought I'd just bring it to your attention.

**Comment by samreid** [comment]
I reviewed TimeControlNode and tested the usage in Gravity and Orbits.  Everything looks good.  I made 2 minor commits.  I was unfamiliar with the 2nd type parameter in this optionize call, can you add a code comment or comment here about the intent?

```ts
    const options = optionize<TimeControlNodeOptions,
      Omit<SelfOptions, 'playPauseStepButtonOptions' | 'speedRadioButtonGroupOptions'>, NodeOptions>()( {
```

Does it mean we don't provide defaults for those options?

**Comment by pixelzoom** [comment]
@jbphet or @samreid yes, please remove the console.log in TimeSpeedRadioButtonGroup.

@samreid there's no need for a code comment here. This is a common pattern that PhET developers need to become familair with.  It's how nestOptions are treated so that you don't need to provide a default value.  It was discussed recently in the Slack typescript channel.  If you don't recall it, or don't understand it, please create a GitHub issue to discuss.  But it occurs in many places, so a comment here is definitely not needed or desirable.

**Comment by samreid** [comment]
In the commit, I also corrected some backwards <==> forwards metadata problems discovered in https://github.com/phetsims/phet-io/issues/1815

**Comment by samreid** [comment]
> @jbphet or @samreid yes, please remove the console.log in TimeSpeedRadioButtonGroup. 

I removed that in prior commits.

**Comment by samreid** [comment]
Review complete, closing.
