### ISSUE TITLE
Address TypeScript lint  problems in NumberControl.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#742]
For https://github.com/phetsims/chipper/issues/1253, NumberControl uses `any`. 

For https://github.com/phetsims/chipper/issues/1252, NumberControl uses `merge`.

Since @jonathanolson did the conversion to TypeScript, assigning to him to complete the job.

**Comment by jonathanolson** [comment]
Handled merge in another issue.

**Comment by jonathanolson** [comment]
Handled `any` above, closing.
