### ISSUE TITLE
Expand options for ResetShape for reuse in a SyncIcon

### ISSUE THREAD

**Issue by marlitas** [phetsims/scenery-phet#743]
Mean: Share and Balance is introducing a new "sync" icon that looks like this:
<img width="286" alt="Screen Shot 2022-06-07 at 2 25 41 PM" src="https://user-images.githubusercontent.com/42476338/172475940-2a5fd4b1-551e-4f0b-bb7a-e040e046b16c.png">

The initial build for this icon duplicated a great deal of code in ResetShape.ts
@samreid recommended adding options to ResetShape to increase its usability for the SyncIcon as well as any other future cases. @jbphet approved through Slack message:

> [Marla Schulz]
> Hi John! I copy and pasted a large portion of your ResetShape code and Sam and I were wondering if creating some options to make the code usable for our sync icon would be appropriate. We imagine this icon might be used in other sims as well, and do not want to have large amounts of duplicated code everywhere.
> 
> [John Blanco]
> Sounds reasonable to me.

New options may include:
- startAngle
- endAngle
- arrowHeadSize

**Comment by marlitas** [comment]
Options added, and ResetShape implemented into Mean: Share and Balance. Assigning to author of ResetShape.ts @jbphet for quick review.

Checked consistency of ResetShape on "Reset All" buttons across various published and unpublished sims to ensure changes didn't affect visuals.

Feel free to close issue if all looks good.

**Comment by jbphet** [comment]
The changes to the code look reasonable.  I have two suggestions:
- Change the file name to something like CircularArrowShape, since it is now used in a context that is unrelated to reset.
- Change the header comment to describe the shape, and then state that it was originally created for the reset button but then generalized.

Back to @marlitas for follow-up.

**Comment by marlitas** [comment]
During testing to address review comments I discovered a "Refresh" button that looks very similar to the "Sync" icon created for Mean: Share and Balance. Asked designer for feedback in this issue: https://github.com/phetsims/mean-share-and-balance/issues/35

Holding off on moving forward on this until that question is answered.

**Comment by pixelzoom** [comment]
> @samreid recommended adding options to ResetShape to increase its usability for the SyncIcon as well as any other future cases. @jbphet approved through Slack message:

Let's please _not_ overload/complicate ResetShape in this way. Sync/Refresh should be a separate shape.  Better yet, don't create a Shape. Where possible, PhET should be using fontawesome icons.  In this case https://fontawesome.com/search?q=refresh&s=solid%2Cbrands:

<img width="666" alt="screenshot_1712" src="https://user-images.githubusercontent.com/3046552/175597389-507220e5-12ee-4d9f-b20b-2bf6bdcb0b9c.png">

**Comment by pixelzoom** [comment]
I realize that the fontawesome icon is not identical to the current icon in Mean: Share and Balance.   But I think is an important compromise that designers should be willing to make. Using fontawesome icons saved significant development/maintenance cost, avoids issues like this GitHub issue, and uses iconography that is standard and well-vetted.

**Comment by pixelzoom** [comment]
Also recommended to use the name `RefreshButton`, to align with fontawesome's "fa-refresh" icon.

**Comment by marlitas** [comment]
The SyncIcon has changed and is no longer similar to ResetShape. Will revert changes to ResetShape.ts.

**Comment by marlitas** [comment]
Reverted commits that provided options to ResetShape. Closing.
