### ISSUE TITLE
Confusing to find NumberSpinner in sun and NumberPicker in scenery-phet

### ISSUE THREAD

**Issue by marlitas** [phetsims/scenery-phet#744]
When switching between NumberPicker and Number Spinner in Mean: Share and Balance I was confused to find that I needed to import NumberSpinner from sun, when I had imported NumberPicker from scenery-phet. They are very similar components:
<img width="935" alt="Screen Shot 2022-06-17 at 12 23 11 PM" src="https://user-images.githubusercontent.com/42476338/174356204-954ce19d-0321-451d-9fda-7b88db9b1a35.png">
<img width="935" alt="Screen Shot 2022-06-17 at 12 23 21 PM" src="https://user-images.githubusercontent.com/42476338/174356210-89666df8-271d-453d-af61-a7cdd8f95828.png">

@samreid suggested that maybe these should be consolidated? 

In NumberPicker.ts the documentation reads: `This is actually a number spinner, but PhET refers to it as a 'picker', so that's what this class is named.`
- The documentation seems to indicate they are the same other than the verbal reference used by members of the PhET team.
- Does this indicate renaming of one of the components should occur if it's inconsistent?
- Is there a reason these similar components are in two separate repos?
- If not, should we consolidate?

Assigning to @pixelzoom as the author of both NumberSpinner and NumberPicker.

**Comment by pixelzoom** [comment]
This is a duplicate of https://github.com/phetsims/sun/issues/436, the goal of which is to evaluate/consolidate the various "spinner" implementations. It's been open since 1/2019, but has never been prioritized.   My recommendation is to note the confusion that this caused you in https://github.com/phetsims/sun/issues/436, then close this issue as a duplicate.

**Comment by pixelzoom** [comment]
And by the way...  I've felt from the beginning that NumberPicker was unnecesary and redundant.  But the team (especially the design team) did not agree.  They wanted a very specific "look", which is implemented in NumberPicker.  So combining NumberPicker and NumberSpinner will be not only a challenging implementation task, but a re-design challenge.  And imo it's inappropriate to work on the implementation until the re-design has been done.

**Comment by pixelzoom** [comment]
The term "picker" is also (imo) unnecessary, and unique to PhET.  Let's use standard names for standard UI components. It's a spinner.

**Comment by samreid** [comment]
For now, does it seem reasonable to move NumberPicker to sun?

**Comment by pixelzoom** [comment]
Sure.

**Comment by marlitas** [comment]
Closing as duplicate of: https://github.com/phetsims/sun/issues/436
