### ISSUE TITLE
Add TrashButton to common code.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#745]
Somewhat related to https://github.com/phetsims/scenery-phet/issues/320 ...  

There are at least 3 sims that have trash buttons, all with different implementations:
- [x] equality-explorer
- [x] MOTHA
- [ ] CCK

... and probably others that are not coming up in a search for "trash".

They all use trashAltRegularShape (the FontAwesome icon).  But CCK is a round push button, the others are rectangular.   So I'm going to proceed with a rectangular button.

@samreid FYI... It's not clear to me whether a round button is necessary in CCK (see below). But if it is, I guess you'll need a custom implementation. (It sure would be nice if sun buttons had made the button shape an option, rather than entirely separate branches of the button class hierachy.) 

<img width="344" alt="screenshot_1703" src="https://user-images.githubusercontent.com/3046552/174686156-fb9492b2-4025-4bc0-a9fa-80948e7fea58.png">

**Comment by pixelzoom** [comment]
scenery-phet.TrashButton was added in the above commits, and is used in equality-explorer and MOTHA.

Assigning to @samreid to decide what to do about CCK.  In the shortterm, it would be nice to rename CCK's implementation from TrashButton to CCKTrashButton, to prevent import confusion.

**Comment by arouinfar** [comment]
> @samreid FYI... It's not clear to me whether a round button is necessary in CCK (see below)

A round button is necessary if we want to be consistent with the other similar buttons in the sim. Forcing a rectangular trash button would require us to change all of the other similar buttons in CCK.

<img width="531" alt="image" src="https://user-images.githubusercontent.com/8419308/174907093-dbe8f21f-e8e6-497d-be23-dbc25bdf5064.png">
<img width="522" alt="image" src="https://user-images.githubusercontent.com/8419308/174907141-052b1ecf-a8ec-48bd-9e0d-da0891fa25d7.png">
<img width="518" alt="image" src="https://user-images.githubusercontent.com/8419308/174907169-27c3ac1b-0fc5-4c9d-90c4-4c02024e4731.png">
<img width="198" alt="image" src="https://user-images.githubusercontent.com/8419308/174907230-e1dc2f70-e7f3-4db5-a42d-65552383e89d.png">

**Comment by pixelzoom** [comment]
Thanks @arouinfar. It's clear to me now :)

But it's also clear to me that PhET has a serious deficiency in the design of sun buttons.  Button shape should be an option, not a fork in the class hierachy.

**Comment by arouinfar** [comment]
> Button shape should be an option, not a branch of the class hierarchy.

Totally agree! It would be so nice to have that flexibility from a design perspective, too.

**Comment by samreid** [comment]
I renamed CCK's TrashButton as recommended in https://github.com/phetsims/scenery-phet/issues/745#issuecomment-1160953669.  Please note, the prefix is "CCKC" for Circuit Construction Kit Common.  Regarding the button shape being an option, want to promote https://github.com/phetsims/sun/issues/659 to an epic issue and discuss it for an upcoming quarter?  Anything else for this issue?

**Comment by pixelzoom** [comment]
👍🏻
