### ISSUE TITLE
Triangle thumb node for slider

### ISSUE THREAD

**Issue by marlitas** [phetsims/scenery-phet#748]
While researching a bug on the 3D water cups slider I discovered that Blackbody spectrum also has a triangular thumb node for their slider: 
<img width="350" alt="Screen Shot 2022-06-02 at 3 28 14 PM" src="https://user-images.githubusercontent.com/42476338/171741661-183f6a9d-1022-4627-9283-ded4aeef7aa1.png">
Our triangular thumb node looks like this:
<img width="255" alt="Screen Shot 2022-06-02 at 3 31 24 PM" src="https://user-images.githubusercontent.com/42476338/171741888-f31b36c2-aa85-4a95-be25-94fbfefd4670.png">

Should a triangular thumb node for sliders be implemented into scenery-phet to avoid code duplication?

**Comment by marlitas** [comment]
TriangleNode has been implement into both proportionPlayground and Blackbody-spectrum. Implementing into proportion playground was not as straightforward and required the use of magic numbers to match original. I was not able to understand the local coordinate system on my own and would like review from @jonathanolson as responsible dev to properly implement TriangleNode into proportionPlayground in a manner that functions more seamlessly with existing code.

**Comment by pixelzoom** [comment]
@kathy-phet please prioritize this review.

**Comment by pixelzoom** [comment]
@kathy-phet @jonathanolson Noting that this has been ready for review for 9+ months.

**Comment by pixelzoom** [comment]
@kathy-phet @jonathanolson Noting that this has been ready for review for 18+ months.

**Comment by jonathanolson** [comment]
Looks great! Minor patch above to prevent passing shape/shapeProperty to TriangleNode. Closing.
