### ISSUE TITLE
Address problems with hotkeys.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#749]
Proposed epic for Q3 2022 ...

Since alt-input is now a standard part of sim development, fix problems related to hotkeys. Some of these are serious.

Issues currently include:
https://github.com/phetsims/scenery-phet/issues/716
https://github.com/phetsims/scenery-phet/issues/682
https://github.com/phetsims/scenery-phet/issues/681
https://github.com/phetsims/scenery-phet/issues/680

Assigning to @kathy-phet to decide whether this epic should be scheduled for Q3 2022, and who should be assigned.

**Comment by zepumph** [comment]
@jessegreenberg and I want to create a more general HotKey class and manager that knows about all keys registered, and delivers a consistent API.

**Comment by marlitas** [comment]
This issue is here to manage hotkey work and now we have a Monday board to track that. Any remaining work is already tracked in other issues. Closing.
