### ISSUE TITLE
Airplane icon should match the original

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#75]
Here are the points that define the original airplane in our logo (exported from AI file):

`
<polygon fill="#F2E916" points="221.92,131.225 234.307,135.705 250.253,122.428 237.983,136.955 251.236,141.627 256.021,114.975 
    "/>
<polygon fill="#F2E916" points="238.004,139.547 238.312,146.48 243.254,141.54 "/>
`

Here is the code that draws it in PaperAirplaneNode.js:

``` javascript
    // main body
    bodyShape.moveTo( width, 0 ); // front tip
    bodyShape.lineTo( width * 0.8, height * 0.9 ); // right wing tip
    bodyShape.lineTo( width * 0.45, height * 0.725 );
    bodyShape.lineTo( width * 0.85, height * 0.2 );
    bodyShape.lineTo( width * 0.35, height * 0.675 );
    bodyShape.lineTo( 0, height * 0.5 ); // left wing tip
    bodyShape.close();

    // underneath part
    bodyShape.moveTo( width * 0.45, height * 0.8 );
    bodyShape.lineTo( width * 0.45, height );
    bodyShape.lineTo( width * 0.6, height * 0.875 );
    bodyShape.close();
```

Do these match up sufficiently well?  Why not just use the exact points from the AI so they will match perfectly?

**Comment by jbphet** [comment]
Sounds great to me too (he said sheepishly when he realized the issue has been assigned to him for almost two years).  Or it could just be left as is - it's scaleable now and doesn't seem to be causing problems for anyone.

**Comment by pixelzoom** [comment]
GLRewardNode has since evolved to display multicolored airplanes using the `fill` options of PaperAirplaneNode.  Since it would be nontrivial to change, PaperAirplaneNode is here to stay.

Now back to @samreid's original question: Should PaperAirplaneNode use the actual coordinates from the .ai file, or are @jbphet's "eyeballed" values good enough.  Current implementation looks OK to me, but I must admit that I haven't compared them critically. 

![screenshot_77](https://cloud.githubusercontent.com/assets/3046552/20445559/ccb80674-ad92-11e6-8260-a0a962e95828.png)

**Comment by pixelzoom** [comment]
I'm going to unsubscribe from this issue, since I don't have a strong opinion. @jbphet @samreid whatever you decide is OK with me.

**Comment by samreid** [comment]
It would be best to use the same geometry as in the AI file, and since kite already parses that format, it should be very easy.

**Comment by samreid** [comment]
Also, it is odd that PaperAirplaneNode takes a size option instead of using the built-in scale option.

**Comment by samreid** [comment]
Here's a movie that shows the difference between the estimated airplane and the actual airplane, pretty close!

![airplane](https://cloud.githubusercontent.com/assets/679486/20459894/8bb98578-ae8f-11e6-829b-10ee9c40aa54.gif)

**Comment by samreid** [comment]
Here's a new screenshot of the game over node with the new airplanes:

![image](https://cloud.githubusercontent.com/assets/679486/20460011/d5552d7e-ae92-11e6-9d3e-d67983658edf.png)

**Comment by samreid** [comment]
The pic above seems similar enough to https://github.com/phetsims/scenery-phet/issues/75#issuecomment-261634634 that I'm inclined to close the issue.

Also, the new airplane has its origin at (0,0) and a test at http://localhost/scenery-phet/scenery-phet_en.html?brand=phet&ea&screens=3&component=PaperAirplaneNode
