### ISSUE TITLE
Finish a11y issues

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#750]
Proposed epic for Q3 2022 ...

A11y issues are becoming a growing percentage of the issues in scenery-phet, accumulating technical debt.  These issues are in various stages of completion, with most open for a year or more.  

Let's finish up issues with these labels (current number of issues in parentheses):

* dev:alt-input (13)
* dev:voicing (4)
* dev:description (7)

Recommended to prioritize dev:alt-input, since alt-input is now a standard part of sim development.

Assigning to @kathy-phet to decide whether this epic should be scheduled for Q3 2022, and who should be assigned.

**Comment by jessegreenberg** [comment]
Yes, we are reviewing open issues and prioritizing them in Monday. This can be closed. Thanks @marlitas!
