### ISSUE TITLE
TypeScript error in demoStopwatchNode.ts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#755]
In demoStopwatchNode.ts, the demo for StopwatchNode, there's a TypeScript error.  Option `decimalPlaces` does not exist.

```typescript
const customStopwatchNode = new StopwatchNode( stopwatch, {

    // Supply the formatter on startup as well as on link, so it can detect widest/thinnest text, see NumberDisplay
    numberDisplayOptions: {
      numberFormatter: StopwatchNode.createRichTextNumberFormatter( {
        showAsMinutesAndSeconds: false, // because we're not showing minutes & seconds
        // @ts-ignore numberFormatter.decimalPlaces does not exist
        decimalPlaces: 1,
        units: unitsProperty.value
      } )
    },
    scale: 2,
    tandem: tandem.createTandem( 'customStopwatchNode' )
  } );
```

Assigning to myself and @samreid, since we both worked on StopwatchNode, and git history is unclear on who added this option.

**Comment by pixelzoom** [comment]
In the above commit, I changed `decimalPlaces: 1`  to `numberOfDecimalPlaces: 1`, and I added `baseColor: 'red'` so it's clear which StopwatchNode instance we're dealing with.  The TypeScript error is gone.  But I'm still seeing 2 decimal places in the display, see screenshot below.  Maybe this option is ignored for some display formats?...

@samreid please have a look.

<img width="287" alt="screenshot_1735" src="https://user-images.githubusercontent.com/3046552/176600900-c7ec1330-c2c6-49b2-94df-d9376709e331.png">

**Comment by samreid** [comment]
The problem was that there is a `link` method a few lines after that StopwatchNode is instantiated, which overrides the formatter options and uses the default number of decimal places.  In a commit, I'll factor out the number of decimal places and use it in both places.

**Comment by samreid** [comment]
Fixed and ready for review.

**Comment by pixelzoom** [comment]
👍🏻 closing.
