### ISSUE TITLE
Move layout demos to sun, convert to TypeScript

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#756]
There are 3 demos that feel like they are in the wrong place. They have nothing to do with scenery-phet.

* demoFlowBox.js
* demoGridBox.js
* demoManualConstraint.js

To do:

- [ ] Move to sun/demo/layout/, and add to LayoutScreenView
- [ ] Convert to .ts

Assigned to the author @jonathanolson.

**Comment by pixelzoom** [comment]
Or perhaps they are in scenery-phet because scenery does not have a demo, and scenery-phet is at least related to scenery?  If that's the case, then why is there a Layout screen in sun demo that deals entirely with scenery layout?

**Comment by jonathanolson** [comment]
The demos will be moved to exemplar documentation as part of https://github.com/phetsims/scenery/issues/1474.

**Comment by jessegreenberg** [comment]
I think these can just be removed, layout examples have moved to scenery. I noticed https://github.com/phetsims/scenery/issues/1474#issuecomment-1293700724 even mentions removing examplese from sun so Ill do the same for scenery-phet.

**Comment by jessegreenberg** [comment]
They have been removed.
