### ISSUE TITLE
Convert demoSprites.js to TypeScript

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#757]
Convert demoSprites.js to TypeScript.  I took a stab at this, and there were complications.

Assigning to the author, @jonathanolson.

**Comment by pixelzoom** [comment]
@kathy-phet please prioritize this work.

**Comment by samreid** [comment]
Converted to TypeScript, tested in type checker, linting, and in the demo harness.  Also fixed a memory issue on dispose.  Closing.
