### ISSUE TITLE
Use KeyboardHelpIconFactory.iconRow where possible

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#759]
KeyboardHelpIconFactory looks like it has several methods that should be using KeyboardHelpIconFactory.iconRow.  This will be handled after TS conversion. Self-assigning.

**Comment by pixelzoom** [comment]
In the above commit, I added a demo of all KeyboardHelpIconFactory methods, so that I can confirm that I don't change behavior by mistake.  Here's a screenshot before making changes:

<img width="1070" alt="screenshot_1792" src="https://user-images.githubusercontent.com/3046552/180082164-e3681c77-a6a7-43e3-a724-6a0635405a75.png">
@

**Comment by zepumph** [comment]
Looks really good. Thanks for this.
