### ISSUE TITLE
Replace SimpleDragHandler with DragListener

### ISSUE THREAD

**Issue by marlitas** [phetsims/scenery-phet#768]
During work for: https://github.com/phetsims/scenery-phet/issues/761, @samreid and I found that `SimpleDragHandler` is deprecated and should be converted to `DragListener` as well. 

We found 30 use cases.

In initial discovery, we converted `LaserNode` in Bending Light, and `BlackBodySpectrumThermometer` in Black Body Spectrum, and found the conversion to be incredibly simple and quick. We would like to get the rest of the teams opinion on how to move forward with this chip-away.

**Comment by jonathanolson** [comment]
@marlitas will take the lead, and I'll be available for backup/questions.

**Comment by samreid** [comment]
For a process, I would recommend using a regex to detect all `// eslint-disable-line` that ends there (maybe it is a `$`), query-replace them all with the empty string.  Run lint-everything in WebStorm popup window so you can tap on links to visit each case, then add-back the line with the specific rule that is failing there.

**Comment by marlitas** [comment]
This has been completed in the above commits. 
Moving to to-be-discussed to find a reviewer.

**Comment by marlitas** [comment]
@samreid will spot check to review.

**Comment by samreid** [comment]
I reviewed the commits and tested a few sims with changes, and everything seemed straightforward. Nice work! Closing.
