### ISSUE TITLE
Memory leaks introduced by dynamic strings

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#771]
I’m finding memory leaks in common-code UI components due to how support was added for dynamic locale. It’s not enough to simply change a parameter or option from `string` to `TReadOnlyProperty<string>` .  You also need to dispose of the Text/RichText instance that you’re passing that parameter to.  

So far I've found leaks in the following components (not a complete list):

- [x] NumberControl @jonathanolson
- [x] QuestionBar @marlitas
- [x] RulerNode @pixelzoom
- [x] MenuItem @jonathanolson
- [x] KeypadDialog @jonathanolson

**Comment by pixelzoom** [comment]
@marlitas please review the fix to QuestionBar in https://github.com/phetsims/scenery-phet/commit/a8c0f3b859d166c12d1ac24989f475f6f9838ebb. Let me know if you have any questions, unassign yourself after review.

**Comment by pixelzoom** [comment]
@jonathanolson please review fixes to MenuItem in https://github.com/phetsims/sun/commit/39081e82ec1ea6e77bb130dffdc86c9b1861f5dc.  There are 2 memory leaks, and a few bad names: `text: TReadOnlyProperty<string`, `textNode = new Text`,...

**Comment by pixelzoom** [comment]
@jonathanolson please review fix to NumberControl in https://github.com/phetsims/scenery-phet/commit/0eed95f68bae90e3355f7ee0e1cfd95d5d87e368.

**Comment by pixelzoom** [comment]
@jonathanolson please review the fix to KeypadDialog in https://github.com/phetsims/scenery-phet/commit/fe0f376ce4bc2b8f314137195625b8b45280014c. There was 1 memory leak.

**Comment by pixelzoom** [comment]
I've fixed all of the memory leaks that I was able to identify. Not confident that I got them all.

@jonathanolson @marlitas high priority on review please.

**Comment by jonathanolson** [comment]
I reviewed all of the changes, they look good (I believe this can now be unblocking if @marlitas should further review the change). Apologies about those regressions!

**Comment by pixelzoom** [comment]
@marlitas if https://github.com/phetsims/scenery-phet/commit/a8c0f3b859d166c12d1ac24989f475f6f9838ebb looks OK to you, and you don't have any questions, feel free to close this issue.  If you have questions, ping me on Slack.

**Comment by marlitas** [comment]
Looks good to me. Closing!
