### ISSUE TITLE
Alternative input design for FaucetNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#773]
Discussed briefly with @arouinfar via Zoom.  This is a prerequisite to https://github.com/phetsims/ph-scale/issues/249 (support for alt input). @kathy-phet FYI.

FaucetNode is a common-code UI component used for the faucets in pH Scale and many other sims.  It needs alt input design, including answers to the following:

- [ ] Which keys are used?
- [ ] What are the defaults for KeyboardDragListener options `dragVelocity`, `shiftDragVelocity`, `hotkeyHoldInterval`, etc.?
- [ ] What does the keyboard help look like? (mockup)

Keep in mind that FaucetNode has 2 options that affect it's alt input behavior, and the keyboard help:

* `tapToDispenseEnabled: boolean` -- If true (default), tapping the faucet knob momentarily opens the faucet, then closes it. If false, tapping the knob does nothing.
* `closeOnRelease: boolean` - If true (default), the faucet is closed when released. If false, the faucet remains open.

Sims that use FaucetNode, for context:
* beers-law-lab, concentration
* energy-forms-and-changes
* faradays-electromagnetic-lab, generator
* fluid-pressure-and-flow
* ph-scale, ph-scale-basics
* scenery-phet demo (Components screen)
* wave-interference

**Comment by pixelzoom** [comment]
In addition to general design, we need input from the a11y team on how this should be implemented.  Should it use AccessibleSlider or KeyboardDragListener?  And what do you recommend for keyboard help.  Assigning to @jessegreenberg and @terracoda.

**Comment by pixelzoom** [comment]
I should mention again that this is high priority, because pH Scale and pH Scale: Basics are included in the PhET-iO batch release https://github.com/orgs/phetsims/projects/44.

**Comment by pixelzoom** [comment]
@arouinfar here's a strawman for the keyboard help, implemented in ph-scale master.  For the general case, the "Dispsense a small amount" row is optional, to match how the FaucetNode is configured by the sim.  The optional `closeOnRelease` of behavior of FaucetNode is not mentioned in the keyboard help - does it need to be?   Let me know what you'd like to change.

Also note that FaucetNode currently has no alt input support. So you won't experience the behavior described here.

<img width="522" alt="screenshot_1905" src="https://user-images.githubusercontent.com/3046552/193933626-aa51cb16-60a4-4da3-be00-86299202e3d8.png">

**Comment by pixelzoom** [comment]
Oh my.  My mistake - FaucetNode does how alt input support for its slider aspect.  I didn't realize this because there seems to be an assuption that the FaucetNode is point to the right.  In pH Scale, all of the FaucetNode point to the left.  So (for example) pressing the right arrow move the faucet knob to the left.  

After thinking about it, I sort of get it -- left means decrease the slider value, right means increase the slider value.  But it feels very confusing for the knob to be moving in the opposite direction as the arrow.  @arouinfar does this feel confusing to you? 

I don't see where AccessibleSlider was added in the git history, so assigning to @jessegreenberg and @zepumph.  Do you think something should be changed about how this is behaving in pH Scale?  Or has this been addressed in some other sim?

**Comment by pixelzoom** [comment]
I'll also note that alt input support for the `tapToDispenseEnabled` feature was _not_ added when AccessibleSlider was added. Was that feature intentionally omitted from the alt input design?  Is there an alt input design for FaucetNode that I can refer to?

**Comment by pixelzoom** [comment]
The current alt input implementation is also buggy.  When the beaker is full in pH Scale, the faucet continue to dispense little bursts of "flow".  And it gets stuck in this state, where the flow is off, but there's still fluid visible:

<img width="950" alt="screenshot_1907" src="https://user-images.githubusercontent.com/3046552/193952064-265a2ba5-1a56-416e-baec-c4ac797292fb.png">

**Comment by pixelzoom** [comment]
@arouinfar @terracoda This is another case (similar to https://github.com/phetsims/scenery-phet/issues/610) where a .md file describing the design would be helpful.   So let's make sure that happens as part of this issue.

**Comment by pixelzoom** [comment]
Since FaucetNode is currently implemented as AccessibleSlider, what I proposed for keyboard help in https://github.com/phetsims/scenery-phet/issues/773#issuecomment-1267598379 is incomplete.  So it made sense to use the common-code help for "Slider Controls" help, with a more specific title.   For example, see the help for the _Macro_ screen below.

What's probematic about this is that I haven't been able to figure out how to append additional lines to this help, so that we can provide help for the optional `tapToDispenseEnabled` feature.

<img width="989" alt="screenshot_1909" src="https://user-images.githubusercontent.com/3046552/193957423-4c0e0ec0-37c9-4086-8a7b-1516d00dcb04.png">

**Comment by jessegreenberg** [comment]
I recall testing AccessibleSlider in FaucetNode many years ago in the PhET team a11y sprint. I don't think it ever saw through full design beyond that.

The first thing I noticed when trying it out was `closeOnRelease` is very annoying when using a keyboard. We might want to ignore or change that feature somehow for alt input.

I don't know how important it is to control the flow rate, but a much simpler and more accessible interaction would be to make this behave like a toggle button. Enter/spacebar to toggle the flow of liquid.

**Comment by terracoda** [comment]
I agree with @jessegreenberg, I don't think the pull-faucet maps well to a slider and is more like a toggle.

Waves Intro uses a toggle button to release drops of liquid.

**Comment by zepumph** [comment]
I think it would be worth spending a bit of time implementing with a toggle button interaction as an investigation before we make the decision. Most likely we won't know if it will be an acceptable simplification until we feel it out.

**Comment by jessegreenberg** [comment]
I changed FaucetNode to use `tapToDispense` for alt input so a bit is let out every enter/spacebar press. It seemed like a nice place to start and feel it out since that function is already available. But it could also be switched to an on/off toggle without a timer.

@arouinfar @terracoda over to you to try it out and comment on next steps!

**Comment by arouinfar** [comment]
There is a lot of nuance around the way the FaucetNode behaves in different sims. Sometimes it's important for users to set the flow rate of the FaucetNode. Sometimes it's important for the faucet to `closeOnRelease` because users need to actively control the flow of water. Sometimes it's important to dispense a precise amount of water when clicking on the faucet to allow for finer adjustment of the volume. Essentially, there are both slider-like and button-like qualities to the interaction.

I think the `tapToDispense` behavior @jessegreenberg implemented in pH Scale generally works, but won't scale to all sims. Even so, if the user wants to completely fill or drain the beaker, it will require >20 key presses which is a bit annoying. Could we have modifier keys to add smaller/larger amounts? If so, this would work wonderfully.

The FaucetNode in energy-forms-and-changes and the Water Tower screen of fluid-pressure-and-flow are `closeOnRelease: false`. In these sims, it is critical to be able to set the flow rate, and once it's set, let it keep going while the user interacts with other parts of the sim. This sort of interaction doesn't map well to the behavior currently in pH Scale.

> The first thing I noticed when trying it out was `closeOnRelease` is very annoying when using a keyboard. We might want to ignore or change that feature somehow for alt input.

@jessegreenberg would it be possible to trigger the `closeOnRelease` when the user tabs away from the FaucetNode? I'm imagining a flow something like this (assuming we are dealing with a slider):
1. Tab to FaucetNode
2. Use arrow key to open faucet. The FaucetNode stays open while it still has focus (unless you reach max volume and it becomes disabled).
3. Subsequent arrow keys in the same direction open up the faucet further. 
4. Tab to the next item and the FaucetNode closes.

**Comment by zepumph** [comment]
Subset of https://github.com/phetsims/scenery/issues/1298

**Comment by pixelzoom** [comment]
I'm going to unassign myself for now.  It feels like there are already too many people involved, and I'm happy to use (in ph-scale) whatever the designers/a11y team come up with. I'll be on vacation for a couple of week, feel free to ping me if you need my input.

**Comment by terracoda** [comment]
Are learners expected to move their attention to some where else while the faucet is on?

**Comment by zepumph** [comment]
It isn't clear to me that this is in fact high priority. @pixelzoom is this not longer pressing because ph-scale is proceeding without alt-input?

**Comment by pixelzoom** [comment]
Priority is not my call. Please ask @kathy-phet.

**Comment by arouinfar** [comment]
Supporting alt input for FaucetNode is unlikely to become a priority until there is a need for it in a particular sim. At this point, there isn't any further input needed from me, so I'm going to unassign myself.

**Comment by jessegreenberg** [comment]
This isn't being worked on right now, removing assignments and priority label. I also removed the changes from https://github.com/phetsims/scenery-phet/commit/8b341d51d48abce397e63342a7f678c584f552d3, maybe it will be added back when we come back to this.

**Comment by pixelzoom** [comment]
Faraday's Electromagnetic Lab (FEL) has a faucet in the Generator screen.  If we want that sim to support alt input, then this issue needs to be addressed.  It would be a shame to do work on alt input for FEL, then have to turn it off due to lack of alt input support for FaucetNode -- like we did with pH Scale. More at https://github.com/phetsims/faradays-electromagnetic-lab/issues/14

Assigning this issue to @kathy-phet for consideration during iteration planning.

**Comment by terracoda** [comment]
I think we should have a design meeting about faucet interactions. The issues are not just about implementation.

**Comment by pixelzoom** [comment]
Design meeting notes from https://github.com/phetsims/faradays-electromagnetic-lab/issues/14#issuecomment-1839572776, to support Faraday's Electromagnet Lab 1.0 release:

> Work on FaucetNode (https://github.com/phetsims/scenery-phet/issues/773) is anticipated to start in Feb 2024. That should work with the milestone of "1.0 release in Summer 2024".

**Comment by pixelzoom** [comment]
In preparation for alt input design discussions, I've improved the scenery-phet demo for FaucetNode.  It now demonstrates the 4 combinations of the 2 primary behavior options -- see the screenshot below. 

So that we're all familiar with FaucetNode, please do the following prior to the design meeting: 

(1) Play with the FaucetNode demo, by selecting repository `scenery-phet` in phettest or phetmarks.  FaucetNode is on the "Components" screen.

(2) Read the FaucetNode class documentation at the top of [FaucetNode.ts](https://github.com/phetsims/scenery-phet/blob/main/js/FaucetNode.ts). It describes the primary behaviors.

(3) Scroll down a bit in [FaucetNode.ts](https://github.com/phetsims/scenery-phet/blob/main/js/FaucetNode.ts), and familiarize yourself with `SelfOptions` (currently line 61).  These are the options that are currently available for configuring FaucetNode.  Scroll down a bit more to `const options =` (currently line 86) to see the default values.
<img width="1156" alt="screenshot_2936" src="https://github.com/phetsims/scenery-phet/assets/3046552/39b5c48e-545e-4e80-8fba-ddb809e8820b">

**Comment by pixelzoom** [comment]
Terminology for the faucet, which was established when it was first designed, and is present throughout the FaucetNode code:

* The faucet controls "flow rate", specifically `flowRateProperty: Property<number>`, with a maximum of `maxFlowRate: number`.
* The faucet is "open" or "closed". When open, flow rate is > 0. When closed, flow rate is 0.
* The _shooter_ is the part of the slider that slides left and right, named after a pinball shooter.
* The _knob_ is the part of the shoot that looks like a knob.
* The _horizontal pipe_ extends horizontally from the main mechanism of the faucet. It's length is configurable.
* The _vertical pipe_ connects the main mechanism of the faucet to the _nozzle_, from which fluid flows.
* FaucetNode is not responsible for the fluid that flows from the nozzle; that must be added by the sim.

Notes from yesterday's standup with @arouinfar, plus a few additional thoughts...

* With `closeOnRelease: false`, behavior is like a slider. So perhaps we can leverage AccessibleSlider.
* Faucet can be facing left or right. When facing left, flow increases by moving the shooter to the left, which is different than horizontal sliders.
* With `closeOnRelease: true`, the faucet closes when it is released.  A challenge here is how to "hold" the shoot at one position (flow rate) and then "release" it.
* With `tapToDispenseEnabled: true`, the faucet behaves like a button. Pressing it (spacebar?) opens the faucet to dispense a configurable amount of fluid (`tapToDispenseAmount`) over a configurable amount of time (`tapToDispenseInterval`).
* FaucetNode will need a KeyboardHelpSection. Because some sims have multiple faucets, it would be nice if we could design keyboard help that is general. Alternatively, keyboard help could be parameterized like ComboBoxKeyboardHelpSection.

**Comment by pixelzoom** [comment]
According to @kathy-phet, @jessegreenberg is the lead for implementing FaucetNode alt-input behavior.

**Comment by jessegreenberg** [comment]
Here are notes from a design meeting today with @terracoda @pixelzoom @arouinfar and @jessegreenberg.


Feature list:
- FaucetNode will always be composed with AccessibleSlider. Flow rate is important to control so we always need to control the value with arrow keys. By using AccessibleSlider, all the usual keyboard step functionality works too (page up/home/end/etc.)
- If `tapToDispenseEnabled: true`, an additional listener will be added to make it behave like a button. It will dispense for a short amount of time (just like `tapToDispenseEnabled: true` for mouse/touch)
- If `closeOnRelease: true`, the faucet will auto close on the `blur` event. Otherwise, the user will manually turn off the faucet.
- The 0 key can be pressed to quickly turn off the faucet. It will be useful for people that aren't aware of the "home" command.
- The focus highlight will surround the knob. A group focus highlight will surround the shooter and extend out to show how far the knob can be dragged. Same for interactive highlight.
![image](https://github.com/phetsims/scenery-phet/assets/6396244/56ec926b-053b-4cab-b5ca-9dbb29661b5d)

Potential challenge:
  - Some faucets point left. We need the orientation of the faucet to match the movement from the arrow keys. AccessibleValueHandler has options to support this, but how it gets used/exposed by FaucetNode is the tricky part.

Additional discussion:
- We considered adding key bindings to 1, 2, 3 keys to quickly control the flow rate. We decided against it because it is already easy to explore the range of flow rate values with the arrow keys. And adding additional keys will take up more space in a keyboard help dialog.
- We talked about commands to quickly set resultant values from flow rate like volume or energy. Commands like this could be done in a subclass or in sim specific code, but shouldn't be added to this general component.

**Comment by jessegreenberg** [comment]
This patch is working pretty well, but I want to try to simplify it by mixing AccessibleSlider into the shooter instead. I think it will make the highlight code more simple.

<details>

```patch
Subject: [PATCH] Remove opt out of Interactive Highlights, see https://github.com/phetsims/friction/issues/201
---
Index: js/FaucetNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/FaucetNode.ts b/js/FaucetNode.ts
--- a/js/FaucetNode.ts	(revision c1225ba4f2366945af8da3be87bf904a4161738b)
+++ b/js/FaucetNode.ts	(date 1706205640166)
@@ -26,7 +26,7 @@
 import Bounds2 from '../../dot/js/Bounds2.js';
 import LinearFunction from '../../dot/js/LinearFunction.js';
 import InstanceRegistry from '../../phet-core/js/documentation/InstanceRegistry.js';
-import { Circle, DragListener, Image, InteractiveHighlighting, Node, NodeOptions, Rectangle } from '../../scenery/js/imports.js';
+import { Circle, DragListener, HighlightPath, Image, InteractiveHighlighting, KeyboardListener, Node, NodeOptions, Rectangle } from '../../scenery/js/imports.js';
 import EventType from '../../tandem/js/EventType.js';
 import Tandem from '../../tandem/js/Tandem.js';
 import IOType from '../../tandem/js/types/IOType.js';
@@ -46,6 +46,9 @@
 import optionize from '../../phet-core/js/optionize.js';
 import StrictOmit from '../../phet-core/js/types/StrictOmit.js';
 import { TimerListener } from '../../axon/js/Timer.js';
+import AccessibleSlider, { AccessibleSliderOptions } from '../../sun/js/accessibility/AccessibleSlider.js';
+import { Shape } from '../../kite/js/imports.js';
+import DynamicProperty from '../../axon/js/DynamicProperty.js';
 
 // constants
 const DEBUG_ORIGIN = false; // when true, draws a red dot at the origin (bottom-center of the spout)
@@ -66,6 +69,7 @@
   tapToDispenseInterval?: number; // tap-to-dispense feature: amount of time that fluid is dispensed, in milliseconds
   closeOnRelease?: boolean; // when true, releasing the shooter closes the faucet
   interactiveProperty?: TReadOnlyProperty<boolean>; // when the faucet is interactive, the flow rate control is visible, see issue #67
+  flipSliderInput?: boolean; // when true, the keyboard input for the flow rate is flipped - this is useful if the faucet is flipped horizontally
 
   // Overcome a flickering problems, see https://github.com/phetsims/wave-interference/issues/187
   rasterizeHorizontalPipeNode?: boolean;
@@ -73,10 +77,13 @@
   // options for the nested type ShooterNode
   shooterOptions?: ShooterNodeOptions;
 };
-type ParentOptions = NodeOptions;
-export type FaucetNodeOptions = SelfOptions & ParentOptions;
+
+type ParentOptions = AccessibleSliderOptions & NodeOptions;
 
-export default class FaucetNode extends Node {
+// TODO: How do I add valueProperty to this?
+export type FaucetNodeOptions = SelfOptions & StrictOmit<ParentOptions, 'interactiveHighlightEnabled'>;
+
+export default class FaucetNode extends AccessibleSlider( Node, 0 ) {
 
   private readonly disposeFaucetNode: () => void;
 
@@ -94,11 +101,19 @@
       closeOnRelease: true,
       interactiveProperty: new Property( true ),
       rasterizeHorizontalPipeNode: false,
+      flipSliderInput: false,
+
+      // AccessibleSliderOptions
+      enabledRangeProperty: new phet.axon.Property( new phet.dot.Range( 0, maxFlowRate ) ),
 
       // ParentOptions
       scale: 1,
       enabledProperty: enabledProperty,
 
+      // AccessibleSlider is composed with InteractiveHighlighting, but the InteractiveHighlight should surround
+      // the shooter.
+      interactiveHighlightEnabled: false,
+
       // phet-io
       tandem: Tandem.REQUIRED,
       tandemNameSuffix: 'FaucetNode',
@@ -109,6 +124,14 @@
 
     assert && assert( ( 1000 * options.tapToDispenseAmount / options.tapToDispenseInterval ) <= maxFlowRate );
 
+    // An intermediate Property is given to the AccessibleSlider to flip the input but not the flow rate.
+    options.valueProperty = options.flipSliderInput ?
+                            new DynamicProperty( new Property( flowRateProperty ), {
+                              bidirectional: true,
+                              map: ( propertyValue: number ) => maxFlowRate - propertyValue,
+                              inverseMap: ( propertyValue: number ) => maxFlowRate - propertyValue
+                            } ) : flowRateProperty;
+
     // shooter
     const shooterNode = new ShooterNode( enabledProperty, options.shooterOptions );
 
@@ -273,8 +296,51 @@
     } );
     shooterNode.addInputListener( dragListener );
 
+    const keyboardListener = new KeyboardListener( {
+      keys: [ 'enter', 'space', '0' ],
+      callback: ( event, keysPressed ) => {
+        if ( options.tapToDispenseEnabled && [ 'enter', 'space' ].includes( keysPressed ) ) {
+
+          // stop the previous timeout before running a new dispsn
+          if ( tapToDispenseIsRunning ) {
+            endTapToDispense();
+          }
+
+          tapToDispenseIsArmed = true;
+          startTapToDispense();
+        }
+
+        if ( keysPressed === '0' ) {
+          flowRateProperty.set( 0 );
+        }
+      }
+    } );
+    this.addInputListener( keyboardListener );
+
+    // if close on release is true, the faucet will turn off when focus moves somewhere else
+    if ( options.closeOnRelease ) {
+      this.addInputListener( {
+        blur: () => {
+          flowRateProperty.set( 0 );
+        }
+      } );
+    }
+
+    // The highlights surrounds the knob and shooter, ShooterNode provides a custom shapes.
+    const localHighlightBounds = this.globalToLocalBounds( shooterNode.localToGlobalBounds( shooterNode.focusHighlightBounds ) );
+    const localGroupHighlightBounds = this.globalToLocalBounds( shooterNode.localToGlobalBounds( shooterNode.groupFocusHighlightBounds ) );
+
+    this.focusHighlight = new HighlightPath( Shape.bounds( localHighlightBounds ) );
+    this.groupFocusHighlight = new HighlightPath( Shape.bounds( localGroupHighlightBounds ), {
+      outerStroke: HighlightPath.OUTER_LIGHT_GROUP_FOCUS_COLOR,
+      innerStroke: HighlightPath.INNER_LIGHT_GROUP_FOCUS_COLOR,
+      outerLineWidth: HighlightPath.GROUP_OUTER_LINE_WIDTH,
+      innerLineWidth: HighlightPath.GROUP_INNER_LINE_WIDTH
+    } );
+
     const flowRateObserver = ( flowRate: number ) => {
       shooterNode.left = bodyNode.left + offsetToFlowRate.inverse( flowRate );
+      ( this.focusHighlight as HighlightPath ).right = shooterNode.right + 5;
     };
     flowRateProperty.link( flowRateObserver );
 
@@ -355,6 +421,12 @@
 
   private readonly disposeShooterNode: () => void;
 
+  // Custom bounds that define highlight shapes for the ShooterNode. The FaucetNode uses these as its own
+  // highlight to indicate that the Shooter is the interactive part (but the FaucetNode is composed with
+  // InteractiveHighlighting)
+  public readonly focusHighlightBounds: Bounds2;
+  public readonly groupFocusHighlightBounds: Bounds2;
+
   public constructor( enabledProperty: TReadOnlyProperty<boolean>, providedOptions?: ShooterNodeOptions ) {
 
     const options = optionize<ShooterNodeOptions, ShooterNodeSelfOptions, NodeOptions>()( {
@@ -407,6 +479,21 @@
     knobNode.centerY = flangeNode.centerY;
     knobDisabledNode.translation = knobNode.translation;
 
+    // custom focus highlights that are relative to components of this Node
+    this.focusHighlightBounds = new Bounds2( flangeNode.left, knobNode.top, knobNode.right, knobNode.bottom ).dilated( 5 );
+
+    // the group focus highlight bounds surrounds the whole shooter and extends out to show the range of the knob
+    this.groupFocusHighlightBounds = new Bounds2(
+      shaftNode.left,
+      knobNode.top - 10,
+      knobNode.right + shaftNode.width / 2 + 15,
+      knobNode.bottom + 10
+    );
+
+    // This ShooterNode receives input for Interactive Highlighting so the interactiveHighlight is set here, even
+    // though focus highlights are set on the FaucetNode.
+    this.interactiveHighlight = Shape.bounds( this.focusHighlightBounds );
+
     const enabledObserver = ( enabled: boolean ) => {
       // the entire shooter is draggable, but encourage dragging by the knob by changing its cursor
       this.pickable = enabled;
Index: js/demo/components/demoFaucetNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/demo/components/demoFaucetNode.ts b/js/demo/components/demoFaucetNode.ts
--- a/js/demo/components/demoFaucetNode.ts	(revision c1225ba4f2366945af8da3be87bf904a4161738b)
+++ b/js/demo/components/demoFaucetNode.ts	(date 1706204847037)
@@ -17,6 +17,7 @@
 import Utils from '../../../../dot/js/Utils.js';
 import PickRequired from '../../../../phet-core/js/types/PickRequired.js';
 import Panel from '../../../../sun/js/Panel.js';
+import PickOptional from '../../../../phet-core/js/types/PickOptional.js';
 
 const MAX_FLOW_RATE = 1;
 const FONT = new PhetFont( 14 );
@@ -55,9 +56,16 @@
     closeOnRelease: false
   } );
 
+  const panel5 = new FaucetDemoPanel( panelNumber++, MAX_FLOW_RATE, {
+    tapToDispenseEnabled: true,
+    closeOnRelease: true,
+    flipSliderInput: true
+  } );
+
   const panelsBox = new HBox( {
-    children: [ panel1, panel2, panel3, panel4 ],
+    children: [ panel1, panel2, panel3, panel4, panel5 ],
     spacing: 15,
+    maxWidth: layoutBounds.width - 20,
     resize: false
   } );
 
@@ -71,7 +79,7 @@
 
 class FaucetDemoPanel extends Panel {
 
-  public constructor( panelNumber: number, maxFlowRate: number, faucetNodeOptions: PickRequired<FaucetNodeOptions, 'tapToDispenseEnabled' | 'closeOnRelease'> ) {
+  public constructor( panelNumber: number, maxFlowRate: number, faucetNodeOptions: PickRequired<FaucetNodeOptions, 'tapToDispenseEnabled' | 'closeOnRelease'> & PickOptional<FaucetNodeOptions, 'flipSliderInput'> ) {
 
     const titleText = new Text( `Example ${panelNumber}`, {
       font: new PhetFont( {
@@ -99,6 +107,10 @@
         }
       }, faucetNodeOptions ) );
 
+    if ( faucetNodeOptions.flipSliderInput ) {
+      faucetNode.setScaleMagnitude( -0.7, 0.7 );
+    }
+
     const flowRateStringProperty = new DerivedProperty( [ flowRateProperty ],
       flowRate => `flowRate=${Utils.toFixed( flowRate, 2 )}` );
     const flowRateDisplay = new Text( flowRateStringProperty, {
@@ -111,7 +123,7 @@
     } );
 
     const content = new VBox( {
-      align: 'left',
+      align: faucetNodeOptions.flipSliderInput ? 'right' : 'left',
       spacing: 10,
       children: [
         titleText,

```

</details>

**Comment by pixelzoom** [comment]
I tested in scenery-phet demo, and in FEL.  Behavior looks great - well done!  I'll assign to @arouinfar to take this for a test-drive too, to make sure I didn't misunderstand anything about the design requirements. 

To answer @jessegreenberg's questions...

> For these group bounds, is there a better way to find the width? ...

I don't see any obviously better way to do this. I think it's probably fine.

> To support "reversed" input for left facing FaucetNodes, I added an option to AccessibleValueHandler called `reverseAlternativeInput`. Does that seem reasonable? ...

That seems perfect for AccessibleValueHandler.  

For FaucetNode, it would be nice to have something that's more specific to a faucet API -- like option `direction: 'left' | 'right'` -- and have it set `reverseAlternativeInput` accordingly.  But since it's currently the client's responsibility to change the direction (e.g. `faucetNode.setScaleMagnitude( -0.7, 0.7 )` in demoFaucetNode) I think we can forgo such an option for now.

**Comment by arouinfar** [comment]
I tested in the scenery-phet demo and FEL, and everything is looking great @jessegreenberg! The demo for Example 5 (left/reverse orientation) was also helpful to confirm that reversing the input directions feels correct.

The only question I have is if the keyboard step sizes (including shift and page) are adjustable on a sim-by-sim basis. The demo uses 1% (shift), 5% (regular), and 10% (page) which seems like a reasonable default, but I could imagine different step sizes may be helpful in some sims.

**Comment by terracoda** [comment]
Hi folks, I agree the faucet node works great with the keyboard. The continuous flashing of the lightbulb might be a problem - i.e. might cause seizures. You might already know this.

Additionally, I am confused by the Alt Input on the magnet on the other screens. I'll open an issue for that. The Alt input design has been changed and is not consistent with the existing sim, Faraday's Law. This causes inconsistency across sims which can be confusing.

**Comment by pixelzoom** [comment]
> The only question I have is if the keyboard step sizes (including shift and page) are adjustable on a sim-by-sim basis. 

The answer is yes.  FaucetNode extends AccessibleSlider, so it has options `keyboardStep`, `shiftKeyboardStep`, and `pageKeyboardStep`.  In the above commit, I've added a demonstration of these options to the scenery-phet demo.  The values used are:

```ts
        keyboardStep: 1,
        shiftKeyboardStep: 0.1,
        pageKeyboardStep: 2
```

Back to @jessegreenberg.  If there's nothing else to be done for FaucetNode, I think it's safe to close this issue.

**Comment by jessegreenberg** [comment]
Great, thanks for reviewing everyone! Closing this issue and we will add the keyboard help content in https://github.com/phetsims/scenery-phet/issues/839.
