### ISSUE TITLE
Revise implementation of NumberKeyNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#783]
The current implementation of NumberKeyNode is:

```typescript
export default class NumberKeyNode extends LetterKeyNode {}
```

Being a "number key", it's very odd/unexpected that the constructor does not take a `number` value.  And it allows bogus usages like `new NumberKeyNode( 'A')` and `new NumberKeyNode( 'hello world')`.

It's also missing `NumberKeyNodeOptions`.

Why not something like this?

```typescript
type SelfOptions = EmptySelfOptions;

export type NumberKeyNodeOptions = SelfOptions & LetterKeyNodeOptions;

export default class NumberKeyNode extends LetterKeyNode {
  constructor( value: number, providedOptions?: NumberKeyNodeOptions ) {
    super( value.toString(), providedOptions );
  }
}
```

Also wondering if `value` should be limited to  integers?  If this is specific to input, I would guess "yes".

**Comment by pixelzoom** [comment]
@zepumph FYI.

**Comment by pixelzoom** [comment]
Since I did most of the work above, I went ahead and reimplemented NumberKeyNode. It's only used in 2 places, in RAP. @zepumph please review.

**Comment by pixelzoom** [comment]
Since I did most of the work above, I went ahead and reimplemented NumberKeyNode. It's only used in 2 places, in RAP. @zepumph please review.

**Comment by zepumph** [comment]
Love it. Thanks!
