### ISSUE TITLE
New Keyboard Shortcut for Reset All

### ISSUE THREAD

**Issue by terracoda** [phetsims/scenery-phet#789]
@terracoda to open a issue in scenery-phet for Press buttons and Reset All.

Check Shape and Reset Shape though common shortcuts, their behavior may be sim specific.

_Originally posted by @terracoda in https://github.com/phetsims/quadrilateral/issues/249#issuecomment-1317362409_

**Comment by terracoda** [comment]
In quadrilateral we will have a partial reset called "Reset Shape". We wanted a keyboard shortcut for it, and the team thought it would be good to also have a general shortcut for the Reset All button.

The 2 shortcuts I've chosen from the team feedback are:
- Reset All : [ALT] + [R]
- "Partial" Reset: [ALT] + [Shift] + [R]

My understanding is that the full reset is general and that partial resets are sim specific.

Here's a rough visual that I hack together for Quadrilateral as an example, note the the "Reset All" should come before the "Exit a dialog" :
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/1902116/202000203-5bbcade8-c72a-4e0a-9c62-b3f99493d814.png">

Here's the new accessible content for the Basic Actions section:
**H2: Basic Actions**
- Move to next item or group with Tab key.
- Move to previous item or group with Shift plus Tab key.
- Move between items in a group with Left and Right arrow keys or Up and Down arrow keys.
- Press buttons with Space or Enter keys.
- Toggle checkboxes with Space key.
- Reset All with ALT plus R.
- Exit a dialog with Escape key.

**Thing to do for this issue**
[ ] Create the general Reset All keyboard shortcut
[ ] Update the Basic Actions to include the Reset All shortcut comes just before "Exit a dialog"
[ ] Update the Press buttons item to include both the Space and Enter Keys
[ ] Make sure "Press buttons" comes before "Toggle checkboxes"

**Comment by terracoda** [comment]
Maybe Exit a dialog should remain as the last item.

<img width="972" alt="image" src="https://user-images.githubusercontent.com/1902116/203372304-449c1e10-ce81-431b-bb60-c84c34c1de62.png">

**Comment by jessegreenberg** [comment]
There is still work to be done with KeyboardListener but it is good enough for this issue.

I reviewed the changes in several sims that support alternative input. The extreme layout case is geometric-optics because the dialog is already so full. @arouinfar and @terracoda reviewed it and said it was OK, even though contents of the dialog had to scale down slightly.

@terracoda can you please confirm all is done in this issue?

@zepumph do you have time to review these code changes? You were recently in these dialogs for disposal, and you are most familiar with the new KeyboardListener so I feel you are the best reviewer.

**Comment by zepumph** [comment]
Can you speak to if pdomClick() is the way of the future? I only see 2 other usages in the project, and I wonder if there is a newer more idiomatic way of activating that is independent of input method. Feel free to close.

**Comment by jessegreenberg** [comment]
Thanks for reviewing. I honestly didn't think about it too carefully, but liked it better than calling options.listener() directly. And it has the added benefit of changing the interaction state of the button. Sound OK?

**Comment by zepumph** [comment]
Excellent
