### ISSUE TITLE
ArrowNode variables tipX, tipY, tailX and tailY private when some sims are trying to access

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/scenery-phet#792]
While converting Projectile Motion to TypeScript, @zepumph  and I came across numerous usages of ArrowNode.tipX, ArrowNode.tailY etc. Currently ArrowNode tipX, tipY, tailX and tailY are private and can only be set with ArrowNode.setTailAndTip(). 

@pixelzoom do you think it's best to create public getters for tipX, tipY, tailX and tailY or keep the JS usage the same and switch these to public with documentation?

**Comment by pixelzoom** [comment]
https://github.com/phetsims/scenery-phet/commit/51c2426eeb5fed083220f9cc464321c616f0214e is not the way to accomplish this.  There's a general pattern for the situation where the class needs to modify fields, but they need to be readonly for the API.  

First, make the fields `private` and add an underscore to their name:

```typescript
  private _tailX: number;
  private _tailY: number;
  private _tipX: number;
  private _tipY: number;
```

Next, change any usage of `this.tailX` within the class to `this._tailX`. Do the same for the other 3 fields.

Finally, add an ES5 getter for each field:

```typescript
  public get tailX(): number { return this._tailX; }
  public get tailY(): number { return this._tailY; }
  public get tipX(): number { return this._tipX; }
  public get tipY(): number { return this._tipY; }
```

This effectively results in no change to the ArrowNode API, while making the fields readonly. 

I've made this change in the above commit. Let me know if you have questions.

**Comment by matthew-blackman** [comment]
Reviewed and confirmed that this is working well in Projectile Motion. This issue can be closed.
