### ISSUE TITLE
Adjust LockNode so that it is centered on the closed padlock

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#794]
In Quadrilateral:

<img width="131" alt="image (1)" src="https://user-images.githubusercontent.com/3046552/211161852-7532da9a-588a-465d-ab01-8912f051ddd8.png">

<img width="132" alt="image" src="https://user-images.githubusercontent.com/3046552/211161856-171d1f7b-709a-4bcf-a62d-5c35c974a882.png">

In Slack#design-sims, I commented:

> Very nice. Do you want the “closed” lock to look like it’s centered in the button? In other sims where I’ve used this icon, that has been the request from designers — they want the closed lock to look centered, and it’s OK/preferred that the opened lock does not look centered — because your eye focuses on the alignment of the padlock body, and ignores the shackle/shank. That is not the case in the above screenshots — the closed lock is off-center in the button.  But I can fix that with a relatively easy adjustment in `LockNode`, if you’d like me to do it.

@jessegreenberg said that this would be a nice improvement, so I'll make it so.

**Comment by pixelzoom** [comment]
Noted in Slack#design-sims:

Before I work on https://github.com/phetsims/scenery-phet/issues/794 …. I’m wondering why a checkbox was used in Ratio and Proportion, while a button was used in Quadrilateral — see screenshots below.  Wouldn’t a similar checkbox work in Quadrilateral, replacing “Ratio Lock” with “Small Steps”?  That would provide a consistent UI across sims, and make it unnecessary to do the work in https://github.com/phetsims/scenery-phet/issues/794.

<img width="193" alt="screenshot_2119" src="https://user-images.githubusercontent.com/3046552/211214657-da35cbbd-be60-45c9-822a-4dd14688dc6b.png">
<img width="166" alt="screenshot_2120" src="https://user-images.githubusercontent.com/3046552/211214658-f8d7b42e-6f53-4be5-9e9b-0648b64a6cef.png">

**Comment by jessegreenberg** [comment]
I had a similar question in https://github.com/phetsims/quadrilateral/issues/298 and proposed using the same checkbox. But there was a strong preference for the button and @terracoda even mentioned it would be nice if ratio-and-proportion used a toggle button too. For consistency we might update RaP.

**Comment by pixelzoom** [comment]
OK, I'll proceed with the change.  But be forewarned that if RaP is not changed, there will be an additional bit of space to the left of the closed lock icon.  We can adjust that by changing the spacing between the "Ratio Lock" text and the LockNode.

**Comment by pixelzoom** [comment]
I'll also mention that in Equality Explorer, we did not use a checkbox or button. The lock is the control, it doesn't need a text label because of its context, and it's been working nicely. 

<img width="711" alt="screenshot_2121" src="https://user-images.githubusercontent.com/3046552/211215678-ccdb1d66-0882-4905-b4da-3e4947fadf62.png">

**Comment by terracoda** [comment]
I agree that consistency is very important and would be ideal to update RaP with a button.

**Comment by pixelzoom** [comment]
Ready for review by @jessegreenberg.

Here's how the revised LockNode looks in Quadrilateral:

<img width="170" alt="screenshot_2132" src="https://user-images.githubusercontent.com/3046552/211424158-38f93fb7-c6b8-481f-8f75-96ba5e6034a1.png">
<img width="168" alt="screenshot_2131" src="https://user-images.githubusercontent.com/3046552/211424171-e7fcd0f3-9872-4081-a282-d11d46bdf26a.png">

The look is unchanged in RaP and Equality Explorer.

**Comment by jessegreenberg** [comment]
Thanks for doing this, it looks really nice in quadrilateral.

I did notice the look changed slightly in RaP and equality-explorer. In equality-explorer the lock is centered in published:
![image](https://user-images.githubusercontent.com/6396244/211434038-837c6838-6da4-4f08-bab9-fb8e4414e700.png)
vs
![image](https://user-images.githubusercontent.com/6396244/211434118-623def30-be86-4f61-a5fe-12f3f9f3081c.png)

Do we need `xAlign` to be an option for LockNode?

**Comment by pixelzoom** [comment]
Good catch on equality-explorer.  It had still had a kludgy workaround for centering the lock that I was able to remove from BasicsSceneNode.ts:

```diff
-        centerX: leftToolboxNode.right + ( rightToolboxNode.left - leftToolboxNode.right ) / 2 + 4,
+        centerX: leftToolboxNode.right + ( rightToolboxNode.left - leftToolboxNode.right ) / 2,
```

What's the different in RaP?  And is it worth addressing, or would it be better to spend the time converting to a toggle button like Quadrilateral?

**Comment by jessegreenberg** [comment]
Great! In RaP there is a little more space between the the "Ratio Lock" text and the LockNode. I thought it might have been for the same reason as the off-center look in equality-explorer but it is not.  Lets just switch to the button in RaP, to be done in https://github.com/phetsims/ratio-and-proportion/issues/549. This can be closed, thanks @pixelzoom!
