### ISSUE TITLE
Buttons in ZoomButtonGroup should not have `visibleProperty` instrumented

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#796]
When we have zoom buttons, each button's `visibleProperty` is instrumented by default. And that seems undesirable.

For example in Calculus Grapher, we have zoom buttons that look like this:

<img width="289" alt="screenshot_2218" src="https://user-images.githubusercontent.com/3046552/215654551-07a824da-f6a6-48c9-b63e-a7dee61381fa.png">

... and in the Studio tree you have control of `zoomInButton.visibleProperty` and `zoomOutButton.visibleProperty`:

<img width="274" alt="screenshot_2217" src="https://user-images.githubusercontent.com/3046552/215653849-c7bbdb22-8800-4d61-9152-ef4b9de6ee18.png">

While we do want the client to be able to hide the entire group, I can't think of a reason to support hiding each button individually.   I've been working around this by adding `phetioVisiblePropertyInstrumented: false` to the buttons, but I'm getting a little tired of doing that.  I think the default instrumentation should be changed.

@arouinfar do you agree?

This would be an API change that affects all sims that use `ZoomButtonGroup` or its subclasses.  The code change is trivial (1 line), here's the patch:

```diff
Subject: [PATCH] factor out private updateLayout, https://github.com/phetsims/calculus-grapher/issues/95
---
Index: js/ZoomButtonGroup.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/ZoomButtonGroup.ts b/js/ZoomButtonGroup.ts
--- a/js/ZoomButtonGroup.ts	(revision ea85255ad252c0fc9d39ce72bc68c1dda1664a5c)
+++ b/js/ZoomButtonGroup.ts	(date 1675135015905)
@@ -62,7 +62,8 @@
       buttonOptions: {
         fireOnHold: true,
         fireOnHoldDelay: 600, // ms
-        fireOnHoldInterval: 250 // ms
+        fireOnHoldInterval: 250, // ms
+        phetioVisiblePropertyInstrumented: false
       },
 
       // FlowBoxOptions
```

**Comment by arouinfar** [comment]
Sounds like a similar discussion we recently had in https://github.com/phetsims/circuit-construction-kit-common/issues/947.

> While we do want the client to be able to hide the entire group, I can't think of a reason to support hiding each button individually. I've been working around this by adding `phetioVisiblePropertyInstrumented: false` to the buttons, but I'm getting a little tired of doing that. I think the default instrumentation should be changed.

I completely agree. Let's uninstrument the `visibleProperty` of the individual buttons by default. Similarly, I don't see any reason for clients to set the `enabledProperty` of the buttons, either. The model should be in control, so let's make it `phetioReadOnly: true`.

**Comment by zepumph** [comment]
This will be really nice, thanks for taking this on!

**Comment by samreid** [comment]
Please update Circuit Construction Kit accordingly when this issue is addressed.  Please see https://github.com/phetsims/circuit-construction-kit-common/issues/947 for the sim-specific workaround.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/sun/issues/826 needs to be addressed before I work on this, because there is overlapping work there.

**Comment by pixelzoom** [comment]
@arouinfar said it would be preferrable to have `enabledProperty` uninstrumented.

**Comment by pixelzoom** [comment]
In the above commits, I added this to base class ZoomButtonGroup:

```diff
      buttonOptions: {
        fireOnHold: true,
        fireOnHoldDelay: 600, // ms
        fireOnHoldInterval: 250, // ms
+        phetioVisiblePropertyInstrumented: false,
+        phetioEnabledPropertyInstrumented: false
      },
```

Then I removed any sim-specific usages of `phetioVisiblePropertyInstrumented: false` and `phetioEnabledPropertyInstrumented: false`.

API files were regenerated with `for-each.sh phet-io-api-stable "grunt generate-phet-io-api"`

**Comment by pixelzoom** [comment]
@samreid said:
> Please update Circuit Construction Kit accordingly when this issue is addressed.  Please see https://github.com/phetsims/circuit-construction-kit-common/issues/947 for the sim-specific workaround.

I renamed cck.ZoomButtonGroup to CCKZoomButtonGroup, because the name collision was causing me grief for this changed.  I also thought it was odd that you were setting some option default in CCKZoomButtonGroup, but setting others at instantiation in CCKScreenView:

```
    const zoomButtonGroup = new CCKZoomButtonGroup( model.zoomLevelProperty, {
      tandem: tandem.createTandem( 'zoomButtonGroup' ),
      buttonOptions: {
        phetioReadOnly: true,
        phetioVisiblePropertyInstrumented: false
      }
    } );
```

So I deleted `phetioVisiblePropertyInstrumented: false` here, and moved `phetioReadOnly: true` into CCKZoomButtonGroup.

@samreid would you mind reviewing this issue and the CCK change? Close if OK.

**Comment by samreid** [comment]
In https://github.com/phetsims/phet-io/issues/1873#issuecomment-1414446787 @marlitas pointed out we may need to update other override files.  I'll do that now.

**Comment by samreid** [comment]
OK I removed the extraneous overrides.

**Comment by samreid** [comment]
Looks good.  I just renamed one class to match other nearby prefixes.  Studio tree looks good in CCK.  Closing.
