### ISSUE TITLE
Letter keys should be translatable

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#797]
Promoting to side issue from https://github.com/phetsims/scenery-phet/issues/769#issuecomment-1307958807:

>I spoke with @jessegreenberg and we definitely agree that letter keys should be translatable since word keys are. Unassigning him and making a new issue to tackle that.

**Comment by zepumph** [comment]
Alright, I finally got to this. @jessegreenberg will you please review?

**Comment by jessegreenberg** [comment]
Thanks for doing this! I like the new factory methods. I tested with ?stringTest and saw that LetterKeyNode content is correctly scaled with long strings.

- Can you please comment on phet-io use cases, do we need to go through and make sure all LetterKeyNodes are disposed properly now?
- I see changes to quad, BASE, RaP, faradays-law, do we need to update any other sims in `interactive-description` list?

**Comment by zepumph** [comment]
>Can you please comment on phet-io use cases, do we need to go through and make sure all LetterKeyNodes are disposed properly now?

Yes, this will cause a memory leak for dynamic elements (like the keyboard help dialog) when you set state for PhET-iO. This is only actually important for Ratio and Proportion and Friction and then any PhET-iO sims with alt input in the future, but I really want to focus in on https://github.com/phetsims/phet-io/issues/1810, which may make it so that dialogs don't need to support dispose. It is a fruitful and exciting issue that may totally remove the burden that PhET-iO has put on dialog content for the last few years. I'm planning to vouch for it for next iteration.

>I see changes to quad, BASE, RaP, faradays-law, do we need to update any other sims in interactive-description list?

I think that it is fine to have dialogs leaking in the PhET-io state wrapper for other sims so long as they aren't in the API stable list, especially given the possibility of https://github.com/phetsims/phet-io/issues/1810. It is not worth being proactive here, especially not just on behalf of the letter keys (since everything needs help).

**Comment by jessegreenberg** [comment]
OK, great thanks.

> I see changes to quad, BASE, RaP, faradays-law, do we need to update any other sims in interactive-description list?

To clarify, I was wondering about keys that may not be translatable yet because they weren't updated. Looking for `new LetterKeyNode`, I think you got all except for the ones using `createGlobalHotkeyRow`.

**Comment by zepumph** [comment]
Ahh yes thanks. I fixed those above. Thanks. Here is  a string test proving it (because I'm untrustworthy)

![image](https://user-images.githubusercontent.com/6856943/223858702-d9e9c7ba-1f46-463f-b25a-378a0f471268.png)
