### ISSUE TITLE
Add KeyboardDragListeners to MeasuringTapeNode

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#798]
Over in https://github.com/phetsims/my-solar-system/issues/86 it seemed worth a bit of exploration. Seems like the hardest part is just reusing the same code efficiently between dragListener and keyboardDragListener.

**Comment by zepumph** [comment]
I think it would be nice for @jessegreenberg to review this. The conversion was pretty straight forward. The worst part was that I know that the DragListener is using a bit of an old pattern for supporting dragging, and it wasn't very plug and play to convert it to use positionProperty + offset + transform + dragBoundsProperty settings. Thus, the options passed to DragListener and KeyboardDragListener aren't very aligned. Is there anything else you see?

**Comment by jessegreenberg** [comment]
Changes to MeasuringTapeNode and KeyboardDragListener look right to me, thanks!

If the intent for keyboard input is "smooth" dragging, can we use the velocity options of KeyboardDragListener? I regret the default value of `moveOnHoldInterval` option, it should be a large value for the "drag delta" behavior. I made the change above, keeping the shift drag for the tip slower than the base. Does that seem OK?

**Comment by zepumph** [comment]
- [ ] Add focus highlight around the whole base

**Comment by zepumph** [comment]
On second thought, the design team finds this box acceptable, because the measuring tape image is already kinda boxy:

![image](https://user-images.githubusercontent.com/6856943/223866149-da3d6e4a-ead8-4cbc-b007-00901a33c0d2.png)
