### ISSUE TITLE
Ruler should be made to handle translation better

### ISSUE THREAD

**Issue by jbphet** [phetsims/scenery-phet#8]
This issue was moved from the Gravity Force Lab sim, where it was entitled, "Ruler should only have markings on the top".  The motive for this request was that the current version may not work well if some language has a longer word for "meters" than the English version (see screenshot).

![ruler-pic](https://f.cloud.github.com/assets/3082831/1045276/6b1f9d98-1022-11e3-8724-e89482190309.png)

Here is the history of the issue as logged originally on the GFL sim:

jbphet opened this issue late July 2013
Title: Ruler should only have markings on the top

In the current version of Gravity Force Lab, the ruler has marks on both the top and bottom. In the spec, they are only on the top.

jbphet commented in late July 2013
Vasily - Hold off on working on this one for now. I'll figure out who should modify RulerNode.js so that it can support markings on one side.

pixelzoom commented mid-August 2013
Before I go adding this functionality to RulerNode... Why is this needed? The original (Scala) sim has a ruler with tick marks at the top and bottom. And if you're on a desktop machine and measuring the distance between the vetical dashed lines, it's convenient to have tick marks at the top and bottom of the ruler. So why do we need a ruler that has tick marks only at the top? And is that really a requirement for this sim?

ariel-phet commented mid-August 2013
To clarify, it is not so important that there are tick marks only at the top of the ruler... The issue is that if "meters" is translated to long text it will visually interfere with either the "0" or the "1"... so really we ideally want a ruler that is designed to support translation better. Tick marks only on the top would solve this issue, but may not be the best solution.

pixelzoom commented mid-August 2013
Well, i18n is always going to be a problem. So I don't think an option to remove bottom tick marks makes sense. Either remove them always, or design a ruler that can accommodate both bottom tick marks and localized units.

ariel-phet commented mid-August 2013
I agree that would be the correct solution is to design such a ruler

**Comment by pixelzoom** [comment]
5 months later, repeating... @jbphet made the last commit on this. No indication if that commit addressed this issue. Assigning to him for status.

**Comment by jbphet** [comment]
I checked this on Balancing Act and Gravity Force Lab.  The former has the lower ticks disabled, and works fine with long strings.  The latter looks bad with long strings.  So as of now, this issue is not fully addressed.  Screenshots below.

![ruler-ba](https://cloud.githubusercontent.com/assets/3082831/8088787/236d848e-0f61-11e5-956d-e055e531793f.png)

![ruler-gfl](https://cloud.githubusercontent.com/assets/3082831/8088792/2a46e5b6-0f61-11e5-8a89-3a0eeb5f07ae.png)

**Comment by jbphet** [comment]
List of simulations that currently use the ruler and whether it has issues when strings are doubled:

+ beers-law-lab (no issues)
+ blackbody-spectrum (issue: label overlaps next tick label, see screenshot below)
+ fluid-pressure-and-flow (no issues, but looks croweded)
+ gravity-force-lab (issues, see screenshot in comment above)
+ pendulum-lab (issue: label goes off end of ruler, see screenshot below)
+ under-pressure (no issues)
+ wave-on-a-string (no issues)

blackbody-spectrum:
![ruler-bbs](https://cloud.githubusercontent.com/assets/3082831/8342776/eb0da0f2-1a8b-11e5-997b-219959763b06.png)

pendulum-lab:
![ruler-pl](https://cloud.githubusercontent.com/assets/3082831/8342822/583c786a-1a8c-11e5-9d78-e8334feb21f2.png)

**Comment by jbphet** [comment]
It turns out to be nigh on impossible to position the text as depicted in the mockups shown in https://github.com/phetsims/scenery-phet/issues/8#issuecomment-24346047 due to limitations on the precise positioning of text.  And, to quote @pixelzoom, "it also looks crappy."  In the 6/25/2015 developer meeting, I proposed and demoed an alternative where we maintain the vertical alignment with the tick labels and scale the width of the label to fit between the tick mark labels if needed.  The consensus was that this seemed like a reasonable approach.

**Comment by jbphet** [comment]
I've implemented the approach described above, and also fixed some code in Fluid Pressure and Flow that was doing some odd things to position the units label.  Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
I reviewed the code, looks overall good. But @jbphet why are you using `scale` instead of the new `maxWidth` property of Node?

**Comment by jbphet** [comment]
Ah right - I'd forgotten about maxWidth.  Will change the code to use that.

**Comment by jbphet** [comment]
@pixelzoom has seen the latest set of changes and approves, closing.
