### ISSUE TITLE
Global reset all not working

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#800]
I could not get alt+r to reset while working in https://github.com/phetsims/my-solar-system/issues/93. 

http://localhost:8080/my-solar-system/my-solar-system_en.html?brand=phet&ea&debugger

@jessegreenberg, can you? I see the code in 

https://github.com/phetsims/scenery-phet/blob/b9a061196a39f3a237ddb1e253f92c2d456477c7/js/buttons/ResetAllButton.ts#L124-L134

Can you provide some assistance. I believe it blocks publication of MSS (working towards dev test next week).

**Comment by jessegreenberg** [comment]
I just did a fresh pull and tested http://localhost:8080/my-solar-system/my-solar-system_en.html?brand=phet&ea&debugger and quadrilateral and saw "alt+r" working. Im testing on Windows 10 Chrome. Are you still seeing this?

**Comment by zepumph** [comment]
Weird! It was definitely a fluke because it is working again this morning. I specifically remember refreshing the browser tab, but perhaps Chrome was going through something and needed a restart. I'll re-open if it comes in again and I'll try to save my state for debugging. Thanks and sorry to waste your time.
