### ISSUE TITLE
NumberControl does not accept custom soundGenerators 

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/scenery-phet#802]
While working on https://github.com/phetsims/my-solar-system/issues/105 we got into a problem of providing a custom sound generator. We got around this problem by commenting this assertion https://github.com/phetsims/sun/blob/b1a5196fb47c148959375fd6fb8a3f1c3a732b6a/js/Slider.ts#L227-L228

> 'options should only be supplied when using default sound generator'

What should be done about this?

**Comment by AgustinVallejo** [comment]
@jbphet Could you comment on this workaround?

**Comment by jbphet** [comment]
That doesn't seem like quite the right approach to me.  The idea in the code is that you can use the default sound generator and provide options to it, *or* you can provide a custom sound generator.  You shouldn't need to do both.

If you're trying to provide both a custom sound generator and options for it, why not just supply the options to the custom sound generator where it's created?
