### ISSUE TITLE
FaucetNode is not setting `valueProperty` and `enabledRangeProperty` in options.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#808]
Discovered while chipping away at https://github.com/phetsims/phet-core/issues/130 ...

In FaucetNode.ts:

```tw
type ParentOptions = AccessibleSliderOptions & NodeOptions;
export type FaucetNodeOptions = SelfOptions & StrictOmit<ParentOptions, 'valueProperty' | 'enabledRangeProperty'>;
```

In AccessibleSlider.ts:

```ts
type AccessibleSliderOptions = SelfOptions & AccessibleValueHandlerOptions;
```

And in AccessibleValueHandler.ts:

```ts
type SelfOptions = {
  valueProperty: TProperty<number>;
  enabledRangeProperty: TReadOnlyProperty<Range>;
```

So FaucetNode should be filling in the `valueProperty` and `enabledRangeProperty` options for the superclass.  It is currently providing neither of these values.  So I don't know how this has been working as an accessible slider.

Assigning to @zepumph and @jessegreenberg to resolve.

**Comment by pixelzoom** [comment]
You'll need to address and remove this `ts-expect-error` in FaucetNode.ts:

```tw
// @ts-expect-error see https://github.com/phetsims/scenery-phet/issues/808
```

**Comment by zepumph** [comment]
Looks like since https://github.com/phetsims/scenery-phet/commit/8b341d51d48abce397e63342a7f678c584f552d3 FaucetNode hasn't been an AccessibleSlider, but the AccessibleSliderOptions weren't cleaned up. @jessegreenberg can you please review?

**Comment by pixelzoom** [comment]
@jessegreenberg what is your timeframe for reviewing this issue?

**Comment by jessegreenberg** [comment]
Thanks! Removal of AccessibleSlider options looks good.
