### ISSUE TITLE
TimeControlNode: Uninstrument Text and RichText

### ISSUE THREAD

**Issue by arouinfar** [phetsims/scenery-phet#813]
Related to https://github.com/phetsims/phet-io/issues/1952 and https://github.com/phetsims/greenhouse-effect/issues/341

The Speed RadioButtonGroup contains instrumented `labelText` that is unnecessary.
* `timeControlNode.speedRadioButtonGroup.*RadioButton.labelText`

In https://github.com/phetsims/phet-io/issues/1952 we decided to uninstrument text in common code components as we encounter them in sims. We will also handle migration rules for all affected sims at that time. 

Since the next sim in the queue is Greenhouse Effect, I'll assign @jbphet.

**Comment by jbphet** [comment]
@samreid and I worked together to address this one, and it is done.  Closing.

**Comment by jbphet** [comment]
Reopening.  I thought I'd committed the API changes that go with this, but apparently I didn't, and there are now failures on CT.

**Comment by jbphet** [comment]
API changes committed.  I'll make sure CT cleans up.  Closing.
