### ISSUE TITLE
The EraserButton should use the eraser sound by default

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#818]
As decided in https://github.com/phetsims/center-and-variability/issues/512, we would like the EraserButton to use the eraser sound by default. I started by writing this:

<details>

```diff

Subject: [PATCH] Focus takes precedence for showing the indicator arrows, see https://github.com/phetsims/center-and-variability/issues/518
---
Index: js/buttons/EraserButton.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/buttons/EraserButton.ts b/js/buttons/EraserButton.ts
--- a/js/buttons/EraserButton.ts	(revision 91ed78b60abf4d26e544225d5f0bf0189e0b2abd)
+++ b/js/buttons/EraserButton.ts	(date 1693418563308)
@@ -14,6 +14,8 @@
 import eraser_png from '../../images/eraser_png.js';
 import PhetColorScheme from '../PhetColorScheme.js';
 import sceneryPhet from '../sceneryPhet.js';
+import SoundClipPlayer from '../../../tambo/js/sound-generators/SoundClipPlayer.js';
+import erase_mp3 from '../../sounds/erase_mp3.js';
 
 type SelfOptions = {
   iconWidth?: number; // width of eraser icon, used for scaling, the aspect ratio will determine height
@@ -31,7 +33,11 @@
       iconWidth: 20,
 
       // RectangularPushButtonOptions
-      baseColor: PhetColorScheme.BUTTON_YELLOW
+      baseColor: PhetColorScheme.BUTTON_YELLOW,
+
+      soundPlayer: new SoundClipPlayer( erase_mp3, {
+        soundClipOptions: { initialOutputLevel: 0.22 }
+      } )
     }, providedOptions );
 
     // eraser icon

```

</details>

However, this does not provide an API for changing the initialOutputLevel but leaving the sound mp3 the same. I'm not sure of the best API or implementation for supporting that. @pixelzoom or @zepumph what do you recommend?

**Comment by zepumph** [comment]
Does someone need to change the initialOutputLevel? 

Can you get away with just exposing "soundPlayOptions" in the API? Otherwise, the path is probably to just allow for both `soundPlayerOptions` and `soundPlayer` as mutually exclusive, like we do in EnabledComponent.

**Comment by samreid** [comment]
@AgustinVallejo does this need to be done to publish Kepler's Laws?

**Comment by samreid** [comment]
@Ashton-Morris commented that the volume level from CaV (currently 0.22) is a good value to use for the default in common code.

**Comment by samreid** [comment]
@matthew-blackman @marlitas or @AgustinVallejo can you please take the lead, following the approach prescribed above?

**Comment by AgustinVallejo** [comment]
> @AgustinVallejo does this need to be done to publish Kepler's Laws?

It should be, as we're in the final stages of sound design sign off, and it would be nice to have this ready. I can take the lead, but is the decision to also include API for changing initialOutputLevel? If so, should I go with what @zepumph said or is that only a suggestion? Will implement the default for now.

**Comment by marlitas** [comment]
Unassigning myself and @matthew-blackman since @AgustinVallejo took the lead here.

**Comment by zepumph** [comment]
@AgustinVallejo and I discussed this issue yesterday to see if any more steps were needed that I originally recommended in https://github.com/phetsims/scenery-phet/issues/818#issuecomment-1699744207. It brought up a good conversation about a lack of documentation about common code sound. I made a first pass at doc from that discussion and some slack talks with @Ashton-Morris and @jbphet.


For this issue:
1. @Ashton-Morris can you please confirm that the output level committed for CAV is still appropriate as the general level (now used in Keplers Laws now too). 
2. @Ashton-Morris will you please review [our new common code sound doc](https://github.com/phetsims/tambo/blob/main/doc/adding-sound-to-common-code.md) and make any updates/additions that you feel would be good.

Feel free to close this issue if all seems good.

**Comment by Ashton-Morris** [comment]
Checked. The default levels sound spot on, and the doc for adding sound and the doc for encoding audio look good too. Closing.
