### ISSUE TITLE
MeasuringTapeNode should not reset Properties that it did not create.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#822]
MeasuringTapeNode should not be resetting `basePositionProperty` and `tipPositionProperty` if it did not create them -- ie, if they were provided via options.

This is causing problems in solar-system-common, where we have a measuring tape model element that is responsible for creating and resetting these Properties.  (Until this is fixed, we'll refrain from calling MeasuringTapeNode `reset`.)

Changing this will require testing reset behavior of all sims that use MeasuringTapeNode.

None of the authors of MeasuringTapeNode are available.  So assignig to the responsibile dev for scenery-phet to decide how to proceed.

**Comment by jessegreenberg** [comment]
Sure, I will take a look this might be quick.

Hits for `new MeasuringTapeNode`:

- [ ] charges-and-fields\js\charges-and-fields\view 
    - ChargesAndFieldsToolboxPanel.js 
- [ ] energy-skate-park\js\common\view 
    - EnergySkateParkScreenView.js 
- [ ] fluid-pressure-and-flow\js\watertower\view 
    - WaterTowerScreenView.js 
- [ ] gravity-and-orbits\js\common\view 
    - GravityAndOrbitsSceneView.ts 
- [ ] joist\js 
    - Helper.ts 
- [ ] projectile-motion\js\common\view 
    - ProjectileMotionScreenView.ts 
- [ ] scenery-phet\js 
    - MeasuringTapeNode.ts 
- [ ] scenery-phet\js\demo\components 
    - demoMeasuringTapeNode.ts 
- [ ] solar-system-common\js\view 
    - SolarSystemCommonScreenView.ts 
- [ ] wave-interference\js\waves\view 
    - WavesScreenView.ts 
- [ ] xray-diffraction\js\xray-diffraction\view 
    - XrayDiffractionScreenView.js 

`extends MeasuringTapeNode`:
- [ ] charges-and-fields\js\charges-and-fields\view 
    - ChargesAndFieldsMeasuringTapeNode.js

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/scenery-phet/commit/6e4cd6049f9592a917dbbaa4cb2d6f78a9735825 makes this change, adding the blocks-publication label until this is tested.

**Comment by jessegreenberg** [comment]
OK, I tested and updated usages noted above and added a note for each one. @pixelzoom can you please review and any other testing you would like to see?

**Comment by pixelzoom** [comment]
Looks really great. Thanks @jessegreenberg!
