### ISSUE TITLE
Address `strictAxonDependencies: false` in DragBoundsProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#832]
... or not, because DragBoundsProperty is deprecated.

**Comment by pixelzoom** [comment]
I attempted to resolve this in https://github.com/phetsims/scenery-phet/commit/7c805059ebc243408a1d75e8483030011c66cfe8, and everything seemed fine locally.  But in CT, several sims started failing in ScreenView at line 208:

```ts
  public layout( viewBounds: Bounds2, layoutMatrixOptions?: GetLayoutMatrixOptions ): void {
    this.matrix = ScreenView.getLayoutMatrix( this.layoutBounds, viewBounds, layoutMatrixOptions );
208 this.visibleBoundsProperty.value = this.parentToLocalBounds( viewBounds );
  }
```

@samreid's hypothesis is DragBoundsProperty uses the ScreenView's visibleBoundsProperty -- which is indeed the typical case.

**Comment by pixelzoom** [comment]
Over in https://github.com/phetsims/faradays-electromagnetic-lab/issues/57#issuecomment-1910945878, we turned off strictAxonDependencies when changing listener order via `?listenerOrder`.    

Next step for this issue is to remove `strictAxonDependencies: false` from DragBoundsProperty, then see where it fails in CT.  If it fails in a test related to `?listenerOrder`, then this issue is now irrelevant and can be closed.  If it fails with default listener order, then there's more work to do.

**Comment by pixelzoom** [comment]
Since DragBoundsProperty is deprecated, I decided to do nothinng here, and leave `strictAxonDependencies: false` in place. Closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
