### ISSUE TITLE
getValueProperty doesn't have to be a Property

### ISSUE THREAD

**Issue by marlitas** [phetsims/scenery-phet#842]
After talking with @zepumph about using GroupSortInteraction for the LevelingOut screen in Mean Share and Balance, we determined that `getValueProperty` should just become `getValue`. This helps with a use case in Leveling Out where the items being sorted are not attached to a NumberProperty, but are instead attached to a Property of type `Plate`. 

@zepumph said he can do this refactor and it should be relatively straightforward since we weren't really using getValueProperty as a Property in the first place.

**Comment by zepumph** [comment]
related to https://github.com/phetsims/mean-share-and-balance/issues/137 and #841.

**Comment by zepumph** [comment]
We decided to rename to `getGroupItemValue()`

**Comment by zepumph** [comment]
Alright. It has been done. 

The worst part about it was that we now need `sortGroupItem` to be required, since there isn't way to change a value without a Property. No big deal if you ask me!!

Please review and feel free to close.

**Comment by marlitas** [comment]
Looks really great. Thanks @zepumph! Closing.
