### ISSUE TITLE
Should the CloseButton use generalCloseSoundPlayer by default?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#859]
This option is passed to the CloseButton, should it use this soundPlayer by default?

```js
      soundPlayer: generalCloseSoundPlayer,
```

For phetsims/mean-share-and-balance#270

**Comment by jessegreenberg** [comment]
Thanks @marlitas - I think it should. Ill add it and then remove the usage in mean-share-and-balance (and any others I can find). This will result in a behavior change for cases like Neuron as you have shown, and since it relates to sound Ill see if @jbphet is available for review.

**Comment by jbphet** [comment]
This definitely seems appropriate.  The commits look good, and I test drove it in the Mean Info Dialog in mean-share-and-balance, and it sounds good.  Closing.
