### ISSUE TITLE
Essential Description for Group Sort 

### ISSUE THREAD

**Issue by terracoda** [phetsims/scenery-phet#860]
From https://github.com/phetsims/mean-share-and-balance/issues/307#issuecomment-2206804824

For MSaB we are trying to sort out an accessible name for the group sort interaction, but it is a bit complicated.

In the case of the Group Sort, thus far, 
- The object is the top object in a group of N objects of the same type
- The group of objects are organized in stacks, and the stacks can have a meaningful position, or they can just have a meaningful order.

The pieces we may need to describe the interaction. Using the Candy Bars as an example.
- Group Name: Notepad Candy Bars - maybe in an H3
- Dynamic Description of the Group: {{4}} Candy Bars across {{2}} Stacks.
- Static Group Hint: Explore {{stacks}}, grab and sort {{Candy Bars}}.

The aria role information we may need explore to scaffold operation of the interaction.
- aria-role="application"
- aria-roledescription for pre-grabbed candy bar
    - "grabbable"
    - "grab and sort",
- aria-roledescription for grabbed object 
    - "movable" 
    - "sortable"
 
DRAFT IDEA FOLLOWS:
**Object details on focus we might need now and in the future**
- Accessible Name of focused object: 
- Top Bar {{of 3}} _(this is stack 1)_
- In addition, we might hear a group name and aria-roledescription, e.g. Notepad Candy Bars, group, grab and sort
- Top Bar {{of 1}},  _(this is stack 2)_

**Details on grabbing**
- Initial Grab Response would potentially include instructions about how to move.
- Regular Grab Response
    - Name: Top Bar {{of 3}} (often interrupted depending on the timing delay)
    - Object Response: Grabbed at Stack {{2 of 2}} + aria-roledescription “movable”
    - Context Response as one moves - new position if relevant and new number of objects on the stack.

**Details on releasing**
- Focus returns to the current object where it is release. On focus we would hear the name again and any final relevant context information.
    - Name: Top Bar {{of 4}}
    - Object Response: Released
    - Context Response?: At Stack 1 of 2 + some qualitative detail about the result of the move - being even or uneven??

**Comment by terracoda** [comment]
At the moment, we are only trying to get the object name and possible the group name to read out on focus and release.

**Comment by terracoda** [comment]
It would be good to review how the aria role description attribute is implemented for the grabbed objects in the single object grab and drag, e.g., the role on the grabbed yellow balloon.

**Comment by zepumph** [comment]
From discussion with @terracoda, here is the pattern we would like to see generally, and put into practive in MSAB:



**Selecting:**

roledescription:
  * selecting
  * selectable
  * sortable
  * **navigable**
  * navigating
  * grabbable

Name:  

  * Grab Candy Bar at Stack 1
  * Stack 1, Grab Top Candy Bar
  * Stack 1, Top candy Bar
  * **Stack 1 of 6, Top of 6 Candy Bars (navigable)**

-------------------------

Sorting:
  * movable
  * sorting
  * **sortable**

Name: 
  * Change Stack from Stack 1 
  * Stack 1, Change Stack
  * Stack 1 of 6, Change Stack
  * Stack 1 of 6, Move Top of 3 Candy Bar sortable
  * Stack 1 of 6, Move Candy Bar sortable
  * Stack 1 of 6, Sort Candy Bar movable
  * Stack 1, grabbed change stack
  * **Stack 1 of 6, Top of 3 Candy Bars (sortable)**
  * Stack 1 of 6, Top of 1 Candy Bars sortable (note we don't care about the plural bars, this is fine)

**Comment by zepumph** [comment]
Updates made above. This adds consistent accessible content, accessilbeName behavior, and aria-roledescriptions inside of the group sort common code. And @terracoda and I established a pretty awesome pattern above given that we are just implementing accessible names. @terracoda anything else needed for this issue? Please feel free to close from my end.

**Comment by terracoda** [comment]
No, I think this issues can be closed.

**Comment by terracoda** [comment]
Closing this issue. Please re-open if there is more to do.
