### ISSUE TITLE
Combo box in scenery-phet demo is buggy

### ISSUE THREAD

**Issue by marlitas** [phetsims/scenery-phet#864]
On the Components screen the ComboBox height does not look like it's behaving properly.

<img width="288" alt="image" src="https://github.com/user-attachments/assets/4b23a230-99b3-4d57-811f-70605a706a1d">

**Comment by jbphet** [comment]
My mistake.  I had switched from `CarouselComboBox` to `ComboBox` in an attempt to get support for sound in the tambo demo, but I somehow didn't realize at the moment that I was committing to a common code component in sun.  I've reverted that change and logged [an issue for adding sound support to `CarouselComboBox`](https://github.com/phetsims/sun/issues/891).

The immediate problem is resolved, closing.
