### ISSUE TITLE
GrabDragInteraction: Balloon drag cue doesn't hide immediately when moving the balloon.

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#868]
It only hides once you release and regrab the balloon. I think we probably want this to dissappear. Found while working on https://github.com/phetsims/density-buoyancy-common/issues/364

**Comment by jessegreenberg** [comment]
This was working in BASE 1.4.0 but is broken in 1.5.0 (Nov 2021).

I tried something similar to https://github.com/phetsims/scenery-phet/issues/868#issuecomment-2313715358 but using `KeyboardDragListener.isPressedProperty` but it did not work. The default callback for `showDragCueNode` **always** returns true. And the value for `showDragCueNode` provided by BalloonNode makes an incorrect assumption about the listener order.

Anyway, I am wondering if we can remove these options:
```js
      showGrabCueNode: () => {
        return this.grabDragModel.grabDragCueModel.numberOfKeyboardGrabs < 1 && node.inputEnabled;
      },
      showDragCueNode: () => {
        return true;
      },
```

And make it consistent for GrabDragInteraction? If not, maybe replace those with axon.Propertys so client can directly control visibility?

If continuing with https://github.com/phetsims/scenery-phet/issues/868#issuecomment-2313715359 is best, a new basic listener on `keydown` is probably the way to do it.

**Comment by zepumph** [comment]
I committed the KeyboardListener equivalent of a keyup listener for dragging keys above. In regards to the showDragCueNode defaulting to always true, I believe that this is an acceptable default, as it is up to the client to determine the logic to hid the cueing. I like the idea of using Properties instead, and @samreid and I had also discussed this over in https://github.com/phetsims/scenery-phet/issues/869. I didn't understand the issue with the listener order. Would you like to discuss that more?

**Comment by zepumph** [comment]
@jessegreenberg and I discussed, and we now understand the problem fully, and like the listener that was added above as a solution. Closing.
