### ISSUE TITLE
MutableArrowNode does not line up properly under resizing

### ISSUE THREAD

**Issue by bereaphysics** [phetsims/scenery-phet#87]
The mutable Arrow does not rescale properly. The head of the arrow is no longer centered with respect to the tail of the arrow. 

To repeat the bug. Start with a long arrow and shorten up the length dynamically (with setTailAndTip) such that the length is smaller than the size of the arrow head. The bug will occur when the arrow size is increased from that state. The arrow head is lopsided.. 

![image](https://cloud.githubusercontent.com/assets/7633344/4667068/53ef6388-5559-11e4-9bf0-b0e6499d362f.png)

**Comment by samreid** [comment]
There are currently no usages of MutableArrowNode.js in the code.  I think we should close this issue and move forward with #34

**Comment by pixelzoom** [comment]
If MutableArrowNode is not used anywhere, should it be deleted?

**Comment by pixelzoom** [comment]
Reopening.

Closing this issue because MutableArrowNode is not currently used doesn't address the problem. Either leave the issue open, or delete MutableArrowNode.

**Comment by samreid** [comment]
+1 to delete MutableArrowNode and focus our efforts on improving performance for ArrowNode.

Based on @pixelzoom's comment:

> My personal feeling is that we shouldn't have both ArrowNode and MutableArrowNode.

Let's go ahead and delete it.  I'll assign to @samreid to take care of this.

**Comment by samreid** [comment]
I removed MutableArrowNode.js above. Let us focus our efforts on faster performing arrows in https://github.com/phetsims/scenery-phet/issues/28 when necessary.
