### ISSUE TITLE
Incomplete doc for `interactiveHighlightEnabled` in FaucetNode.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#871]
In https://github.com/phetsims/scenery-phet/commit/985eb3f059cd1b65b3486afd18568bba5c1aba21 for #773, @jessegreenberg made added this option and doc to FaucetNode.  The doc is incomplete, ends in the middle of a sentence.

```ts
      // AccessibleSlider is composed with InteractiveHighlighting, but the InteractiveHighlight should surround
      // the shooter so it is disabled for the faucet and
      interactiveHighlightEnabled: false,
```

**Comment by jessegreenberg** [comment]
Thanks, I filled in this documentation. Closing.
