### ISSUE TITLE
EraserButton: add default for `accessibleName`. 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#879]
Related to https://github.com/phetsims/models-of-the-hydrogen-atom/issues/67 and https://github.com/phetsims/sun/issues/901 ...

EraseButton should have a default for `accessibleName`, rather than every sim adding the same value.   In MOTHA https://github.com/phetsims/models-of-the-hydrogen-atom/issues/67, we identifed 'Erase' as an appropriate default.  This string should be added to scenery-phet-strings_en.json.  We did not identfy a default for `helpText`, since it is liable to be specific to each sim (what is being erased, etc.)

**Comment by jessegreenberg** [comment]
A default was added to EraserButton. Anything else for this issue @pixelzoom?

**Comment by pixelzoom** [comment]
👍🏻 Closing.
