### ISSUE TITLE
string keys need some context

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#88]
Thinking ahead to translation... These keys could use come qualification, so translators know what context they are used in.

>  "pattern_0value_1units": "{0} {1}",
> "pattern_0sign_1number": "{0}{1}"

For example:

>  "WavelengthSlider.pattern_0value_1units": "{0} {1}",
> "FaceWithPointsNode.pattern_0sign_1number": "{0}{1}"

**Comment by pixelzoom** [comment]
I'm now of the opinion that this is not necessary. Assigning to @jbphet for his opinion.

**Comment by jbphet** [comment]
I agree that the context is not needed.  It might be helpful to inexperienced translators, but requiring this would make it harder to use these patterns generally throughout a sim.  And so far, translators have been able to figure it out.  Closing.
