### ISSUE TITLE
TimeControlNode: description design and implementation does not consider options.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#881]
Related to https://github.com/phetsims/models-of-the-hydrogen-atom/issues/67 and https://github.com/phetsims/sun/issues/901 ...

TimeControlNode has many options that affect the configuration of its user interface.  The current description design and implementation seems to not have considered these options, and instead seems specific to some sim.   Here's what it looks like in A11y View:

<img width="392" alt="screenshot_3526" src="https://github.com/user-attachments/assets/3180dfab-21dd-472d-a34f-b20501262d95">

Problems:
- [x] "Play sim on slow speed" does not consider that TimeControlNode may not have a "Slow" speed.  Recommend changing this to "Play sim on slower speed".
- [x] "Timing" is the wrong word here, it means something different.  There is a reason why the UI componnt is named TimeControlNode, and "Time" should be used in the description.  (Ditto for TimingControlsKeyboardHelpSection.)

**Comment by pixelzoom** [comment]
@jessegreenberg and I discussed this issue.  While changing "slow" to "slower" and "Timing" to "Time" would be an improvement, this is not blocking for MOTHA publication.  It can be addressed in a future release, there will be no sim-specific code changes needed to MOTHA, and MOTHA does have a "Slow" speed.

**Comment by marlitas** [comment]
Meeting 11/1/24
- Make the helpText default "smarter" by detecting which options have been passed through to then update accordingly.
- Any default helpText or accessibleName in TimeControlNode should still be able to be overwritten.
- We agreed that the overall design pattern throughout common code is to make accessibleName and helpText mutable.

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/scenery-phet/commit/e168a23cff6dd5805fe231824e0b8a504006b225 I renamed "Timing Controls" to "Time Controls" in a11y and translatable strings, and I changed the description to use "slower", so it is more general for options. I did not touch string keys.

The other commits rename the class TimingControlsKeyboardHelpSection and references in code.

I discussed it with @terracoda and she is OK with these changes.

@pixelzoom would you like to review? Feel free to close, unless I missed something.

**Comment by pixelzoom** [comment]
> ... Feel free to close, unless I missed something.

There are definitely more ways to configure TimeControlNode that break the current description.

Examples:

* `playPauseStepButtonOptions.includeStepForwardButton: false` hides the step-forward button, making "step forward little by little" irrelevant.
* `playPauseStepButtonOptions.includeStepBackwardButton: true` adds a step-backward button, which the description says nothing about.
* lots of things that can be configured dynamically via PhET-iO.

... and there may be others.  So recommended to take a closer look at the TimeControlNode API.   Either remove some options that are undesirable, or make description aware of those options.   

PhET-iO configuration may be too much to tackle in this issue, but it's a problem. And it's going to become a bigger problem with PhET Premium.

**Comment by pixelzoom** [comment]
Also note that the step-backward button has no accessibleName.

**Comment by jessegreenberg** [comment]
OK, thanks for reviewing. Ill take a broader look at the options. Also wondering if we can find more general default help text that would be agnostic to the options.

**Comment by jessegreenberg** [comment]
After reviewing options, it isn't so bad (if we ignore phet-io customizations for now) -
- timeSpeeds?: TimeSpeed[]; // Controls which speed radio buttons are included
- PlayPauseStepButtonGroupOptions:
  - includeStepForwardButton
  - includeStepBackwardButton

**Comment by jessegreenberg** [comment]
Discussed with @terracoda. She recommended these variations in the help text.
- Pause to step through little by little.
- No help text if neither step button is included.

Another option was to be more explicit and describe each case.
- Pause to step forward little by little.
- Pause to step backward little by little.
- Pause to step forward or backward little by little.

We think the first option is reasonable. The buttons themselves will have the accessible names so it doesn't seem necessary to call out each case in the help text.

**Comment by jessegreenberg** [comment]
This was done in [the above commit](https://github.com/phetsims/scenery-phet/commit/05e51cd3d5103b86508a28d05b81040ce4dbb1c9). The other commits rename description -> helpText for consistency.

@pixelzoom can you please review this?

**Comment by pixelzoom** [comment]
👍🏻 Closing.
