### ISSUE TITLE
"Timing" is incorrect term in TimingControlsKeyboardHelpSection.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#882]
Related to https://github.com/phetsims/scenery-phet/issues/881 ...

TimingControlsKeyboardHelpSection should be renamed to TimeControlsKeyboardHelpSection, and the string changed from "Timing" to "Time".

**Comment by marlitas** [comment]
Closing as a duplicate of https://github.com/phetsims/scenery-phet/issues/881
