### ISSUE TITLE
Change the sound API for drag listeners.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#889]
As discovered in https://github.com/phetsims/equality-explorer/issues/215 and https://github.com/phetsims/scenery-phet/issues/888, there are some problems with the current APIs for "sound drag listeners".   Specifically:

* SoundClips (and WebAudio resources) are created for every instance of the drag listener. This is not scalable and wasteful in sims like Equality Explorer, where we have many objects that all have the same grab/release sounds.
* Shared sound players are not used for the defaults:  `sharedSoundPlayer.get( 'grab' )` and `sharedSoundPlayer.get( 'release' )`.
* It's impossible to use shared sound players for custom sounds.
* Creating and immediately playing a SoundClip (as in the creator pattern used in Equality Explorer) is inherently problematic, because the SoundClip needs time to initialize WebAudio resources. 
* There is no way to provide a TSoundPlayer that is not a SoundClip.
* Drag listeners are made responsible for disposing of SoundClips, complicating the code, for example as in https://github.com/phetsims/scenery-phet/issues/888.

Discussed with @jbphet and @jessegreenberg, and the API should be changed so that it is based on TSoundPlayer:

Options:
`grabSoundPlayer?: TSoundPlayer`
`releaseSoundPlayer?: TSoundPlayer`

Defaults:
`grabSoundPlayer: sharedSoundPlayers.get( 'grab' )`
`releaseSoundPlayer: sharedSoundPlayers.get( ‘release’ )`

@jessegreenberg Is going to take a look at this. If it's a significant effort, he'll bring it to planning for scheduling.

**Comment by jessegreenberg** [comment]
This was done in the above commits. Main work is in https://github.com/phetsims/scenery-phet/commit/e4b1132675cad1e4107bf231c65619a6212cc7ad.

Mainly - 
- SoundRichDragListener and related classes now take TSoundPlayers so they can be reused. They no longer create their own SoundClips.
- `wireDisposeListener` was removed, it is no longer necessary.

The only downside to this is that custom TSoundPlayer need to be added to the `soundManager` - easy to forget (https://github.com/phetsims/mean-share-and-balance/commit/111bef642582717306b511a328c441079fc1062c).

I tested mean-share-and-balance and my-solar-system, and combinations of custom `grabSoundPlayer` and `releaseSoundPlayer` in the scenery-phet demo.

@pixelzoom can you please review this? In particular, are [these comments](https://github.com/phetsims/scenery-phet/blob/e4b1132675cad1e4107bf231c65619a6212cc7ad/js/SoundRichDragListener.ts#L63) correct?

**Comment by pixelzoom** [comment]
Main work in https://github.com/phetsims/scenery-phet/commit/e4b1132675cad1e4107bf231c65619a6212cc7ad looks very nice, I don't see any problems.

These constants in SceneryPhetConstants are no longer used. Can they be deleted?

```ts
  DEFAULT_DRAG_CLIP_OPTIONS: { initialOutputLevel: 0.4 },
  DEFAULT_GRAB_SOUND_GENERATOR_ADD_OPTIONS: { categoryName: 'user-interface' }
```

> In particular, are [these comments](https://github.com/phetsims/scenery-phet/blob/e4b1132675cad1e4107bf231c65619a6212cc7ad/js/SoundRichDragListener.ts#L63) correct?

Yes. And the listener added by `linkToDragEvents` is an anonymous function that nothing else has a reference to, so it's not going to result in a memory leak.

**Comment by jessegreenberg** [comment]
Thanks for reviewing, and yes - you are right, I removed those constants. Closing this issue.
