### ISSUE TITLE
FineCoarseSpinner should support dynamic range

### ISSUE THREAD

**Issue by marlitas** [phetsims/scenery-phet#891]
In slack I asked if FineCoarseSpinner should support dynamic range and the response was:

`CM: FineCoarseSpinner looks like it already supports a dynamic range. It takes a NumberProperty, which in turn has rangeProperty. And the implementation is making use of that rangeProperty.`

However in looking through the code it looks like that is not fully supported since FineCoarseSpinner is not listening to the RangeProperty. The following is the suggested approach by @pixelzoom.

```
    // Disable the buttons when the value is at min or max of the range
    const numberPropertyListener = ( value: number ) => {

      // left buttons
      decrementFineButton.enabled = decrementCoarseButton.enabled = ( value !== range.min );

      // right buttons
      incrementFineButton.enabled = incrementCoarseButton.enabled = ( value !== range.max );
    };
    numberProperty.link( numberPropertyListener ); // unlink required in dispose
```
`So in the above code, const range should be removed, and instead of numberProperty.link should probably be Multilink.link( [ numberProperty, numberProperty.rangeProperty ], …. )`

I will implement the above and send to @jessegreenberg for review as responsible dev.

**Comment by marlitas** [comment]
I updated the code and checked usages in Gas Properties and the scenery-phet demo. All seemed to be working as expected and I am also seeing the expected behavior in Forces and Motion Basics. Over to @jessegreenberg to review.

**Comment by jessegreenberg** [comment]
Thanks @marlitas , looks good. Some minor cleanup in the above commit. Back to you for anything else.
