### ISSUE TITLE
Dynamically long speed values can go off spedometer

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/scenery-phet#892]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1179
If the string for speed values becomes long dynamically, it can go off the side of the speedometer. If it is long non-dynamically this does not seem to happen. This is unlikely to show up normally. 

**Visuals**
![unlikelyspeed](https://github.com/user-attachments/assets/f6b70c06-3f20-47d1-8895-fcf9c2c2cb38)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Forces and Motion: Basics‬
URL: https://phet-dev.colorado.edu/html/forces-and-motion-basics/2.4.0-dev.7/phet/forces-and-motion-basics_all_phet.html?dev&stringTest=dynamic
Version: 2.4.0-dev.7 2024-11-26 17:47:57 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by marlitas** [comment]
This has been addressed in the above commit. The only other usage I saw is in Energy Skate Park. It appears to be behaving correctly there and matching what I see in the published version. 

Over to @jessegreenberg to review the code. 
@KatieWoe can you confirm that this is looking better on main now as well?

**Comment by KatieWoe** [comment]
Looks good in main
