### ISSUE TITLE
consolidate EraserButton in scenery-phet

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#92]
There are 3 identical copies of EraserButton, in area-builder, least-squares-regression and plinko-probability. These should be replaced by a single implementation in scenery-phet.  The image file already lives in scenery-phet.

**Comment by aaronsamuel137** [comment]
There is now another implementation of EraserButton in charges-and-fields. Should this be consolidated too?

This version is drawn in code instead of with an image - so it has the potential to be more flexible with regard to color, etc.

Noticed while doing CAF code review: https://github.com/phetsims/charges-and-fields/issues/28

**Comment by pixelzoom** [comment]
+1 for a code-based implementation, if the look is acceptable.

**Comment by samreid** [comment]
There is also an eraser in Energy Skate Park: Basics that should me considered/merged/etc.

**Comment by pixelzoom** [comment]
I'll have a look at doing this one.

**Comment by pixelzoom** [comment]
Changed ESPB to use scenery-phet.EraserButton.

**Comment by pixelzoom** [comment]
Changed ESPB to use scenery-phet.EraserButton, instead of reaching into scenery-phet/images/ and creating its own button. Button sized to match ESPB 1.0.1-dev.2.

**Comment by pixelzoom** [comment]
Hmmm... The implementation is charges-and-fields requires 3 Shapes, 3 Paths, and 3 LinearGradients. And the LinearGradients are currently very specific to creating a pink eraser, not the look used in the other 4 sims.  

Questions:
1. @jonathanolson Which version will perform better? (images or programmatic)
2. @ariel-phet Why do we have a different look for the eraser in charges-and-fields?

**Comment by pixelzoom** [comment]
Email to @arouinfar and @dubson:

Amy, Mike,

I’m contacting you because you’re listed as the designers of “Charges and Fields”.

Regarding the HTML5 version of this sim, please see https://github.com/phetsims/scenery-phet/issues/92

There are 5 sims (enumerated in the issue) with an eraser button. 4 of those sims have the same look. 1 sim (Charges and Fields) has a different look and its own unique implementation.  Is there a reason why Charges and Fields can’t use the same implementation and look as the other 4 sims?

Chris

**Comment by arouinfar** [comment]
@pixelzoom, is the problem with having a pink eraser, a non-yellow button, or both? 

We deliberately did not want to have a yellow button on the equipotential tool because it would be far too eye catching. After giving the button a more muted appearance it had poor contrast with the gray eraser, so we decided to made it pink. If a non-yellow button is acceptable, I can play around with the color to find something that will work with the gray eraser.

**Comment by jonathanolson** [comment]
Re: performance, how will it be used/changed? If there's a 3-gradient solution, I'd start with that. Can always use toImage later or cache it for fast WebGL display?

Other questions to evaluate performance: Does the button move a lot? Does it live in a layer with other things that change every frame? Will the gradients/shapes/paths be changing a lot?

**Comment by pixelzoom** [comment]
@arouinfar asked:
> @pixelzoom, is the problem with having a pink eraser, a non-yellow button, or both?

The problem is primarily the pink eraser. The common-code EraserButton lets you change the button color, but the eraser icon is an image file.

**Comment by arouinfar** [comment]
@jonathanolson, it's likely that the button will be moved around a lot because it is attached to a tool that students will need to drag around the screen.

Thanks, @pixelzoom. I will play with the button color to find something more suitable.

**Comment by arouinfar** [comment]
I've found a more suitable color for the eraser button (RGB (242, 242, 242)), and have created an issue in the Charges & Fields repository to update the color.

**Comment by pixelzoom** [comment]
I've switched charges-and-fields to use scenery-phet.EraserButton, so all eraser buttons are now using the same implementation.  But I have not deleted charges-and-fields.EraserButton.  I'm on the fence about whether to use the programmatic implementation, because it's quite a bit more code than the image-based implementation.  Would like to hear opinions from @jonathanolson, @jbphet, @aaronsamuel137.  My gut instinct is to stick with the image-base (scenery-phet) implementation in this case because it's so simple and has been effective in all cases so far.

**Comment by pixelzoom** [comment]
@arouinfar here's '#F2F2F2'.

![screenshot_532](https://cloud.githubusercontent.com/assets/3046552/7823658/543ff19e-03ba-11e5-824f-8cf02f5cd18b.png)

**Comment by jonathanolson** [comment]
I am fine with the image based solution.

**Comment by pixelzoom** [comment]
I'm going with the image-based solution.  If we ever change our minds, look in https://github.com/phetsims/charges-and-fields/commit/682b5486d92e4551b4c49ebaabd5afa675cf61b6 for the code-based implementation.

All sims are now using scenery-phet.EraserButton.

Closing.
