### ISSUE TITLE
Fluid Pressure and Flow should use the new measuring tape

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#96]
Discovered during #68. Fluid Pressure and Flow currently uses its own copy of the measuring tape.  That version should be deleted and the new one in scenery-phet should be used.

We may also need the feature in measuring tape to change units (may already be supported--I haven't checked).  Many sims that have distance measurements allow the user to measure in meters or feet, for example.

**Comment by bereaphysics** [comment]
The scenery-phet measuringTape has been incorporated in Fluid Pressure and Flow and measuringTapePosition is now a property.  Assigning to @aaronsamuel137 for review

**Comment by bereaphysics** [comment]
The measuringTape is used in FPAF. Closing
